### ISSUE TITLE
Find the most optimal DOSEMU2-compatible Windows display driver

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1075]
@stsp I hope you don't mind I create a ticket here to track issues with different Windows 3.1 applications and different display drivers. (I guess these kinds of issues are not emulation related.)

MS Office seems to have an issue with `t800-5.drv` from `tvgaw31b.zip`:
![afbeelding](https://user-images.githubusercontent.com/877112/77829175-a4714400-7120-11ea-92bd-6154bea6d975.png)

**Comment by stsp** [comment]
Why not to use #265 for that?

**Comment by jschwartzenberg** [comment]
Because that one will quite likely also require changes to DOSEMU2 itself. There are no generic VESA drivers that can do this, so it makes sense to support the Trident drivers available that can do this. It seems to be a matter of adding more memory to the emulated Trident chip (if that's not already there) and interpreting the mode that the higher bit depth drivers use correctly. When you use them now, something legible already shows up.
