### ISSUE TITLE
Console resize garbles output

### ISSUE THREAD

**Issue by leecher1337** [dosemu2/dosemu2#1076]
**Describe the bug**
DOS applications usually cannot cope with sudden resize of the text terminal. This leads to a completely garbled screen and inability to see anything from the application after screen resize.

**To Reproduce**
Start up a Turbovision application with say 80x25 putty terminal and then resize borders.

**Attach program/game binaries or provide an URL**
[charedtv.zip](https://github.com/stsp/dosemu2/files/4398207/charedtv.zip)

Source: http://ftp.lanet.lv/ftp/mirror/x2ftp/msdos/programming/source/dptools.zip

**Additional info**
Proposed fix: Change code in plugin/term/terminal.c function sigwinch to resize back terminal and repaint:

```
sed -i 's/get_screen_size();/printf("\\x1b[8;%d;%dt", Rows, Columns);\n  SLsmg_cls();\n  dos_slang_redraw();/g' src/plugin/term/terminal.c
```
This fixes it for dosemu1. No idea about dosemu2 how console graphics works there.

**Comment by stsp** [comment]
![Снимок экрана от 2020-03-29 05-59-18](https://user-images.githubusercontent.com/3295627/77839080-77ee1400-7182-11ea-937b-fa279648d4df.png)

> This fixes it for dosemu1. No idea about dosemu2 how console graphics works there.

It works as in the screen-shot above.
One more time you bring something
from dosemu1, and you'll never get
a reply.

**Comment by jschwartzenberg** [comment]
@stsp I think you misunderstand the report. He's using Putty which is an SSH/Telnet client, so it's `dosemu -t` that he runs.
Resizing Konsole to exactly 80x25 gives me this:
![afbeelding](https://user-images.githubusercontent.com/877112/77843621-35870000-719f-11ea-81b7-7a55f6c3502e.png)

After some resizing, I get:
![afbeelding](https://user-images.githubusercontent.com/877112/77843637-61a28100-719f-11ea-9274-a2b08c55275b.png)

I think a redraw as proposed by @leecher1337 on a resize would indeed solve this.

**Comment by leecher1337** [comment]
Using *dosemu2* with *putty* (on Windows):

Before resize:
![resize1](https://user-images.githubusercontent.com/6495842/77847767-ce2d7800-71bf-11ea-9c94-a28199fd702a.jpg)

After resize:
![resize2](https://user-images.githubusercontent.com/6495842/77847770-d1c0ff00-71bf-11ea-93d9-8eb05cc4a805.jpg)

**Comment by stsp** [comment]
No, my screen-shot was also done
with -t: the image just stays in the
corner, ignoring the resizing.
But I guess with putty ignoring the
resize is not enough, and the
repaint is still needed?

**Comment by leecher1337** [comment]
Correct, the crucial part is the repaint, but without resize back to the original size, putty also seems to garble the output due to the different window size then. 
It seems you need putty to reproduce this bug.

**Comment by jschwartzenberg** [comment]
Putty in Ubuntu 18.04 shows the same:
![afbeelding](https://user-images.githubusercontent.com/877112/77853791-50309780-71e6-11ea-955e-f47bbeb88b3f.png)

And:
![afbeelding](https://user-images.githubusercontent.com/877112/77853797-5e7eb380-71e6-11ea-88dd-cd686a5d1414.png)

Even just increasing the size makes the UI disappear. In Konsole I had to make the window too small and then bigger again to get that I posted above

Unchecking "Use background color to erase screen":
Before resize:
![afbeelding](https://user-images.githubusercontent.com/877112/77853862-d351ed80-71e6-11ea-9f18-9f99f97ac324.png)

After:
![afbeelding](https://user-images.githubusercontent.com/877112/77853881-ebc20800-71e6-11ea-8e10-a3ca1655d9d1.png)

Maybe that Putty ends up with just an erased screen is relevant.

**Comment by leecher1337** [comment]
As a sidenote, if you try to running the application in fullscreen, dosmeu crashes.
More precisely: If you have >132 columns in the terminal:
```
C:\dptools>charedtv
ERROR: general protection at 0xb7335b00: 0

Ein-/Ausgabe ist möglich
emu2test@debian7:~/dosemu$
```
Maybe this is related to Turbovision screen size support, it's amazing that it supports up to 132 columns anyway :-)
To work around this, I just created a startup shellscript, maybe it's useful for some ppl with the same issue (as terminal size of a remote user cannot be known):
```
#!/bin/sh
resize -u >/tmp/rsz
. /tmp/rsz

checkscreen () {
if [ $COLUMNS -lt 80 ]; then
  COLUMNS=80
  CHANGE=1
fi
if [ $COLUMNS -gt 132 ]; then
  COLUMNS=132
  CHANGE=1
fi
if [ $LINES -lt 25 ]; then
  LINES=25
  CHANGE=1
fi
}

unset DISPLAY
checkscreen
if [ $CHANGE -eq 1 ]; then
  resize -s $LINES $COLUMNS >/tmp/rsz
  . /tmp/rsz
  stty rows $LINES
  CHANGE=0
  checkscreen
  if [ $CHANGE -eq 1 ]; then
    echo Your terminal size is too big, please resize to max. 132 columns and min
    echo 25 lines.
    echo Press RETURN to end now
    rm /tmp/rsz
    read dummy
    exit
  fi
fi
rm /tmp/rsz
```

**Comment by stsp** [comment]
No, you can already do `$_term_set_size="25x80"`
in the config to get the same thing.

**Comment by leecher1337** [comment]
Not exactly the same, the script approximates to the nearest possible size that Turbovision supports and that the user requests by his terminal size whereas $_term_set_size just sets a fixed size from what I can see, which is not what I want in my case, but nevermind, it was just a hint to help users facing the same problem.
The main issue of the ticket remains resizing.

**Comment by stsp** [comment]
`$_term_set_size` is better in this case,
because far not all DOS progs support the
non-standard text sizes. With $_term_set_size
you either set 25x80, or whatever your prog
definitely supports, and no guess-work.

**Comment by stsp** [comment]
Should now be fixed.
