### ISSUE TITLE
Using HXDOS and Microsoft C 8.0, DOSEMU2 crashes

### ISSUE THREAD

**Issue by Tubatstuff** [dosemu2/dosemu2#1091]
I'm using Japheth's HXLDR to provide 32-bit DPMI access to run Microsoft C++ 8.0 (16 bit).  When I 
invoke the compiler, I get the following error:

dosemu.bin: /build/dosemu2-kcMK_a/dosemu2-2.0~pre8-6018/build/../src/arch/linux/mapping/mapping.c:436: mmap_mapping: Assertion `targ >= LOWMEM_SIZE' failed.

DOSEMU2 immediately exits.   Am I missing something?

or provide the download URL.

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.

**Additional info**
Please write here if you did any dosemu2 setup
customizations, like installing any custom DOS
or command.com, or altering the dosemu2
configuration settings. Note that freedos, even
from dosemu-freedos package of dosemu1, counts
as a custom DOS and should be mentioned here.

**Comment by stsp** [comment]
Could you please make this change in your source tree:
```
diff --git a/src/arch/linux/mapping/mapping.c b/src/arch/linux/mapping/mapping.c
index 171cdd6bf..cc9d6536e 100644
--- a/src/arch/linux/mapping/mapping.c
+++ b/src/arch/linux/mapping/mapping.c
@@ -433,7 +433,7 @@ void *mmap_mapping(int cap, dosaddr_t targ, size_t mapsize, int protect)
   if (!(cap & MAPPING_INIT_LOWRAM) && targ != (dosaddr_t)-1) {
     int ku;
     /* for lowram we use alias_mapping() instead */
-    assert(targ >= LOWMEM_SIZE);
+    if (targ < LOWMEM_SIZE) dosemu_error("error\n");
     ku = kmem_unmap_mapping(cap, targ, mapsize);
     if (ku)
       dosemu_error("Found %i kmem mappings at %#x\n", ku, targ);
```

And after reproducing the problem, attach the
log, that the bug form asks you to.

**Comment by stsp** [comment]
Please re-open when you have logs.
