### ISSUE TITLE
Obsolete project link

### ISSUE THREAD

**Issue by skitt** [dosemu2/dosemu2#1094]
The link at the top of https://github.com/dosemu2/dosemu2 hasn’t been updated following the move away from /stsp/; it should be https://dosemu2.github.io/dosemu2 (and perhaps the site could be moved to https://dosemu2.github.io).

**Comment by stsp** [comment]
Thanks, should now be fixed.
Not sure how to move to https://dosemu2.github.io
though.

**Comment by stsp** [comment]
I wonder if someone can draw an icon
for the project. :)

**Comment by jschwartzenberg** [comment]
What about https://github.com/dosemu2/dosemu2/blob/devel/etc/dosemu.xpm?

**Comment by stsp** [comment]
There are few reasons why I don't want to use it.
- I want to distinct from dosemu1, and using
its logo at the same time is a hypocrisy, and
that's the main reason against using that icon.
- It doesn't look modern and stylish. Contrary
to this:
http://icons.iconarchive.com/icons/harwen/pleasant/256/MS-DOS-Application-icon.png
http://icons.iconarchive.com/icons/aroche/delta/128/MS-DOS-icon.png
http://images.all-free-download.com/images/graphiclarge/ms_dos_application_100355.jpg
http://icons.iconarchive.com/icons/harwen/pleasant/64/MS-DOS-Batch-File-icon.png
- I personally would like to see something
else there, for example the linux penguin
together with DOS, to signify that this is a
bridge between linux and DOS.

But the main requirement is to not be similar
to the one of dosemu1.
