### ISSUE TITLE
regression: emufs.com crash with jit

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1096]
**Describe the bug**
Crash on start.

**Attach program/game binaries or provide an URL**
[zxemu034.tar.gz](https://github.com/dosemu2/dosemu2/files/4447686/zxemu034.tar.gz)

**Additional info**
Bisect: 2f921e64c3
Bart, can you take a look?

**Comment by stsp** [comment]
Correction: this has nothing to do with zxemul.
emufs.com crashes.

**Comment by stsp** [comment]
So basically fdpp doesn't boot for me
now, which is strange. I think I tested
these patches.

**Comment by stsp** [comment]
Yes, so indeed fdpp is unbootable now
(crashes on emufs.com) unless I revert
the aforementioned patch.
I have no idea how I tested it before, but
now it is like that.
So it would be good to find a fix quickly,
or revert.

**Comment by bartoldeman** [comment]
Strange that it passed Travis too then (since that tests FDPP+JIT)

**Comment by bartoldeman** [comment]
You can just revert host.h for now. Something causes those macros to fail, in particular `#define FetchW(a)	read_word(a)`. Using `READ_WORD(a)` fails too but `*((unsigned short *)MEM_BASE32((a)))` works. This means something in the aliasing is not quite right, but it'll take me more time to investigate.

**Comment by bartoldeman** [comment]
I investigated a bit further. What happens is that it's a regular write protection page fault on protected jit code memory, but it gives an error code of 6 instead of the regular 7 even though the protections are `r-xs`.

I suspect that this page at 0x100000 has not been read from yet (because it reads from the alias now) so the Linux kernel hasn't paged it in yet and that gives the error code of 6.

So I could see 2 solutions here:
1. Loosen the check in `e_handle_pagefault` to use 
`if (!e_querymprot(addr) || (_err&0x0e) != 0x06) return 0;`
or
2. read a byte from every page after mapping to make sure it's paged in.

which would you prefer.

**Comment by stsp** [comment]
Thanks!
I prefer this:
```
diff --git a/src/base/emu-i386/simx86/memory.c b/src/base/emu-i386/simx86/memory.c
index 33c9598e0..d4e8481c1 100644
--- a/src/base/emu-i386/simx86/memory.c
+++ b/src/base/emu-i386/simx86/memory.c
@@ -310,7 +310,16 @@ int e_handle_pagefault(sigcontext_t *scp)
         * bit 2 = 1    user mode
         * bit 3 = 0    no reserved bit err
         */
-       if (!e_querymprot(addr) || (_err&0x0f) != 0x07) return 0;
+       if ((_err & 0x06) != 0x06)
+               return 0;
+       /* additionally check if page is not mapped */
+       if (addr >= LOWMEM_SIZE + HMASIZE &&
+                       /* can't fully trust _err as page may be swapped out */
+                       !(_err & 1) && !dpmi_read_access(addr))
+               return 0;
+       /* check for codehit */
+       if (!e_querymprot(addr))
+               return 0;
 
        /* Got a fault in a write-protected memory page, that is,
         * a page _containing_code_. 99% of the time we are
```

It arranges the checks by their cost, so
that `_err` checks are done first, and queryprot - last.

**Comment by bartoldeman** [comment]
sure that looks good. I will also later today submit a patch then to tighten the checks in `e_emu_pagefault` which can also use `dpmi_read_access` and `dpmi_write_access` now, and can then otherwise crash dosemu with a backtrace (instead of the "unhandled page fault in vm86" as it does now).

**Comment by stsp** [comment]
So any idea how could it pass all the checks before? :(

**Comment by bartoldeman** [comment]
I guess it's due to the way the Travis run compiles and boots FDPP, that it's just not triggered, or maybe that the paging works slightly differently in a VM, just a few ideas here.
