### ISSUE TITLE
regression: win31 doesn't boot with fullsim

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1100]
**Describe the bug**
win31 no longer boots with fullsim.

**To Reproduce**
Just run.

**Additional info**
Bisect:  70ca014

Bart, can you take a look?

**Comment by bartoldeman** [comment]
For me it was actually 43ac821 that started crashing; fixed in #1101.

**Comment by stsp** [comment]
Not fixed.

**Comment by bartoldeman** [comment]
Hmm it works for me.. do you have a crash log?

**Comment by stsp** [comment]
Sure, what log? -D9+M?

**Comment by stsp** [comment]
[boot.log.gz](https://github.com/dosemu2/dosemu2/files/4465178/boot.log.gz)
Here is -D9+M.

**Comment by stsp** [comment]
> For me it was actually 43ac821 that started crashing; fixed in #1101.

It is very very unlikely that I did a wrong
bisect. Unfortunately its impossible to
revert that patch now on top of devel,
just to make sure. But if you push a revert
as a PR, I'll test.

**Comment by bartoldeman** [comment]
Yes I think our Windows must be slightly different: for me after 43ac821 it crashed with a gdb backtrace so that's why I asked for a crash log. For you it must do something else.

**Comment by stsp** [comment]
Just exception 0xe that you can see in the log.

**Comment by bartoldeman** [comment]
Can you try using just protmode.c from #1098? The idea is that the exception is then changed into a crash and I get a lot more debug info.

**Comment by stsp** [comment]
Please use comcom32 instead.
I checked and the reproducer needs that
rather than freecom (which you definitely use :)

**Comment by bartoldeman** [comment]
ah ok, will try comcom32 a little later.

**Comment by bartoldeman** [comment]
ok, the memory checks also need to check all other DPMI clients' memory blocks.

**Comment by stsp** [comment]
Yes, that works.

**Comment by stsp** [comment]
Thanks.
