### ISSUE TITLE
Building requires symlinking /usr/include/SDL2 to /usr/include/x86_64-linux-gnu/SDL2 on Debian bullseye

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1110]
Today I pulled 2.0pre8-1472-gee61aa7b3 and went about doing a full new build:

```
. autogen.sh
./configure
make
```

It eventually ended with this:

```
gcc -c -MMD -DCFLAGS_STR="-Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.hh -Wno-unused-result -Wcast-qual -Wwrite-strings -Wno-address-of-packed-member -fplan9-extensions -Wno-maybe-uninitialized -fpie -O2   " -I../../../src/include -I../../../src/plugin/include -I../../../src/base/bios/x86 -I[...]/dosemu2/src/include -I[...]/dosemu2/src/base/lib  -iquote . -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.hh -Wno-unused-result -Wcast-qual -Wwrite-strings -Wno-address-of-packed-member -fplan9-extensions -Wno-maybe-uninitialized -fpie -O2    -fPIC -fPIC -I[...]/dosemu2/src/plugin/X/include  -o X_font.o X_font.c
gcc -pthread -pie  -shared -o ../../../2.0-pre8/bin/libplugin_X.so X.o screen.o keyb_X.o keyb_X_keycode.o X_keysyms.o X_keymaps.o X_speaker.o X_font.o -lX11 -lXext 
make[2]: *** No rule to make target '/usr/include/SDL2/SDL.h', needed by 'sdl.o'.  Stop.
make[1]: *** [[...]/dosemu2/src/arch/linux/Makefile.main:97: plugin/sdl] Error 2
make: *** [Makefile:25: default] Error 2
```

I fixed this by doing the following:

```
sudo mv /usr/include/SDL2 /usr/include/SDL2.old
sudo ln -s /usr/include/x86_64-linux-gnu/SDL2 /usr/include/SDL2
```

After this, make succeeded.

This is on a Debian amd64 testing (bullseye) machine.

**Comment by skitt** [comment]
This is a bug in the Debian SDL2 package, which [was fixed yesterday](https://tracker.debian.org/news/1118174/accepted-libsdl2-2010dfsg1-3-source-into-unstable/) in unstable. The fix should be available in Bullseye by the end of the week.

**Comment by stsp** [comment]
Thanks @skitt, but what I see in this
report, makes no sense to me.
`No rule to make xxx` is a strong hint
that the .d files are already present,
and yet the OP says he did the fresh
new build.
Also build shows an X plugin linking
and an error from sdl plugin, which
suggests the parallel build, yet the
report claims to have the plain "make".
So good to know it is already fixed,
plus I think it is misfiled, so lets just
close.

**Comment by ecm-pushbx** [comment]
It was indeed fixed by Debian's SDL libraries that I updated today. Had to run `make clean` and upate my FDPP installation, then the build succeeded again.
