### ISSUE TITLE
Djgpp program running out of KVM memory slots when called multiple times

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1112]
**Describe the bug**
I'm writing some tests to check the file open share modes. Originally I was calling the DOS test just once per dosemu invocation, but although great for debugging it's too slow as there are 225 individual tests. Now I'm running 5 dosemu invocations with 45 tests in a batch file for each. That seems to give problems as towards the end of the batch dosemu crashes out with
~~~
KVM: insufficient number of memory slots MAXSLOT: No such file or directory
~~~

**To Reproduce**
1/ run the unix script `runstandalonetest.sh -td`
2/ run the batchfile `testit`
3/ see the issue

**Attach program/game binaries or provide a URL**
[t1.zip](https://github.com/dosemu2/dosemu2/files/4495594/t1.zip)
Note that the test program source code is sharopen.c

**Attach the log**
test.log is in t1.zip
Notable info is `leavedos(mmap_kvm_no_overlap:409|0) called - shutting down`

**Additional info**
DOS is MS-DOS 6.22
config settings are in t1.zip
64bit Ubuntu 18.04 (kvm available)

BTW, RBIL share info you gave me for #270 is confirmed as correct with MS-DOS 6.22 on FAT.

**Comment by stsp** [comment]
So, try to increase MAXSLOT in kvm.c?

**Comment by andrewbird** [comment]
with 50 I get
~~~
KVM: KVM_SET_USER_MEMORY_REGION: Invalid argument
~~~

with 60 it runs fine to completion

I don't know anything about kvm workings, but doesn't this suggest some sort of resource leak?

**Comment by bartoldeman** [comment]
Yes it smells like a leak, I'll try to investigate.

**Comment by andrewbird** [comment]
Just an additional note, if I use the settings
~~~
$_cpu_vm = "emulated"
$_cpu_vm_dpmi = "native"
$_cpu_emu = "vm86"
~~~
I can call the same program over 500 times without issue. I can workaround it in my testing and it's unlikely to cause others a problem, so from my perspective there's no urgency to fix it immediately.

**Comment by stsp** [comment]
Could you please try this:
```
diff --git a/src/base/emu-i386/kvm.c b/src/base/emu-i386/kvm.c
index 12192cfbc..55cbd1382 100644
--- a/src/base/emu-i386/kvm.c
+++ b/src/base/emu-i386/kvm.c
@@ -475,8 +475,10 @@ void mmap_kvm(int cap, void *addr, size_t mapsize, int protect)
   slot = mmap_kvm_no_overlap(targ, addr, mapsize);
   mprotect_kvm(cap, targ, mapsize, protect);
   /* update EPT if needed */
-  if (cap & MAPPING_IMMEDIATE)
+  if (cap & MAPPING_IMMEDIATE) {
     set_kvm_memory_region(&maps[slot]);
+    maps[slot].memory_size = 0;
+  }
 }
 
 void mprotect_kvm(int cap, dosaddr_t targ, size_t mapsize, int protect)
```

**Comment by andrewbird** [comment]
With this I now see
```diff
diff --git a/src/base/emu-i386/kvm.c b/src/base/emu-i386/kvm.c
index 12192cfbc..55cbd1382 100644
--- a/src/base/emu-i386/kvm.c
+++ b/src/base/emu-i386/kvm.c
@@ -475,8 +475,10 @@ void mmap_kvm(int cap, void *addr, size_t mapsize, int protect)
   slot = mmap_kvm_no_overlap(targ, addr, mapsize);
   mprotect_kvm(cap, targ, mapsize, protect);
   /* update EPT if needed */
-  if (cap & MAPPING_IMMEDIATE)
+  if (cap & MAPPING_IMMEDIATE) {
     set_kvm_memory_region(&maps[slot]);
+    maps[slot].memory_size = 0;
+  }
 }
 
 void mprotect_kvm(int cap, dosaddr_t targ, size_t mapsize, int protect)
diff --git a/test/test_dos.py b/test/test_dos.py
index 0cabca89b..2eae6d4d4 100644
--- a/test/test_dos.py
+++ b/test/test_dos.py
@@ -5113,9 +5113,9 @@ int main(int argc, char *argv[]) {
         mkfile("FOO.DAT", "some data", dname=testdir)
 
         config = """\
-$_cpu_vm = "emulated"
-$_cpu_vm_dpmi = "native"
-$_cpu_emu = "vm86"
+#$_cpu_vm = "emulated"
+#$_cpu_vm_dpmi = "native"
+#$_cpu_emu = "vm86"
 $_floppy_a = ""
 """
 
```

~~~
D:\>c:\sharopen primary SH_COMPAT R SH_COMPAT R ALLOW
KVM: KVM_SET_USER_MEMORY_REGION: Invalid argument
~~~

Not quite sure why that's changed.

**Comment by stsp** [comment]
Could you please try devel now?
Probably fixed.

**Comment by andrewbird** [comment]
Works locally, so I removed the workaround via a commit in travis-ci-18

**Comment by andrewbird** [comment]
Confirmed travis without the workaround is working fine too, thanks!

**Comment by stsp** [comment]
Please don't apply work-arounds next time,
or at least don't un-WIP them.

**Comment by stsp** [comment]
Or at least don't put inside another commits.
