### ISSUE TITLE
Doom1 or Doom2 is playable?

### ISSUE THREAD

**Issue by ThingUroboros** [dosemu2/dosemu2#1115]
Doom1 or Doom2 crash for me not started.

What do I need to set up dosemu config?

I have this error
ERROR: vgaemu: page out of range, 1024 (1024)
ERROR: vgaemu: page out of range, 1025 (1024)

 but when i set more vgaram 
ERROR: touched jit-protected page
ERROR: Sound buffer 0 overflowed (MIC INPUT)
ERROR: Sound buffer 0 overflowed (MIC INPUT)
ERROR: touched jit-protected page
ERROR: touched jit-protected page
ERROR: touched jit-protected page
ERROR: touched jit-protected page
ERROR: Sound buffer 0 overflowed (MIC INPUT)
ERROR: Sound buffer 0 overflowed (MIC INPUT)

**Comment by bartoldeman** [comment]
This is a recent regression which was just fixed in #1113 so please update.

**Comment by ThingUroboros** [comment]
@bartoldeman thx this fix is correct
