### ISSUE TITLE
Specify non-standard library paths during build

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1142]
Is there a way to specify non-standard locations for libraries during the build?  

For example, if I want to build DOSemu with a locally installed version of MUNT, for example, there doesn't seem to be any way to do this.  DOSemu will find MUNT under /usr, or /usr/local, but I want to specify a locally installed copy.

Maybe something like --with-munt=/{path to munt}

**Comment by stsp** [comment]
This is probably possible, at least
very recently such functionality was
added for fdpp.
You can do something like
`./configure --with-plugin-options=munt,some_munt_options`
To find out `some_munt_options` you
can go to `src/plugin/munt` and run
`./configure --help` there.
You may want to pass `--includedir=`
and `--libdir=` to munt.
But this is a very new functionality
and I only tested it with fdpp so far.

**Comment by jharrison03** [comment]
Thanks.  Will test with fdpp.

**Comment by stsp** [comment]
No, I mean I tried it with fdpp _plugin_,
but never with munt plugin yet.
So please try it with munt, not with fdpp. :)
