### ISSUE TITLE
Regression: Tetris Classic suffers from timing issues

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1143]
**Describe the bug**
When playing Tetris Classic there are odd timing aspects going on from time to time. A dropped block then takes longer to get stuck in place or lines take longer to disappear. This happens intermittently but it's not hard to observe when playing the game a bit.

**To Reproduce**
Play the game for a while and observe.

**Attach program/game binaries or provide an URL**
See #492

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/4604488/boot.log)

**Additional info**
Bisecting gives:
bf166e8633e7c771a678ac4d7387367e50c4f08d is the first bad commit

**Comment by stsp** [comment]
Can't reproduce.
Also I really doubt that patch could
do anything of that kind.

**Comment by stsp** [comment]
I have just fixed #1061 which was bisected
to the same patch.
I wonder if this was also affected, could you
please re-test? Although I very much doubt
that.

**Comment by jschwartzenberg** [comment]
I just tested, the issue is still there.

**Comment by stsp** [comment]
It would be good if you re-check if that
exactly patch causes this for you.

**Comment by jschwartzenberg** [comment]
You're right. There's something else going on. I tried a lot of revisions and at some point the problem just stopped occurring even with the latest devel with which I had it earlier. I have no idea what's going on.

**Comment by stsp** [comment]
I think it have something to do with
pic_revert or alike.
Anyway, then this problem looks minor.
