### ISSUE TITLE
Build in Ubuntu 18.04?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1144]
Is it possible to build dosemu2 in current Ubuntu? I was able to get the point where SDL was needed, but Ubuntu wouldn't install all the dependencies for libsdl-dev. Am I missing something obvious? Or could you tell us which distro is used for current dosemu2 development? Thank you.

**Comment by stsp** [comment]
Please get the packages for any
ubuntu from here:
https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa
They are daily built, so are latest.

**Comment by jschwartzenberg** [comment]
To answer the question. Yes, building on Ubuntu 18.04 works fine. I do pretty much all my building and testing on it. `libsdl-dev` is a Ubuntu package, so you probably have a dependency issue due to third party packages. Try installing all the needed dependencies manually if you want to figure out the cause.

**Comment by andrewbird** [comment]
@emendelson if you look at https://github.com/dosemu2/dosemu2/blob/devel/debian/control , you'll see the full list of build dependencies. I'm not sure if you really meant `libsdl-dev` but standard repos for Ubuntu have `libsdl2-dev` and `libsdl1.2-dev`, so perhaps as @jschwartzenberg suggested you are picking up a different package from a third party PPA or other repo?

**Comment by stsp** [comment]
Btw, is there anything LP-alike for
building RPMs online?
In general, I think we do a very good
job for ubuntu, but fedora cannot be
missed. Does anyone know what should
be done to get closer to fedora?
@skitt maybe you do?

**Comment by jschwartzenberg** [comment]
For Fedora/RHEL there is COPR: https://copr.fedorainfracloud.org/
For OpenSUSE/SLES there is OBS: https://build.opensuse.org/

**Comment by stsp** [comment]
Wow!
Does anyone want to try messing with
the above? :)

**Comment by stsp** [comment]
https://build.opensuse.org/package/show/home:linuxcpa/Dosemu2
`If I can't upload source and have it build, this is useless.`
Seems someone have already tried.

**Comment by stsp** [comment]
Oh, and maybe also for bsd?

**Comment by emendelson** [comment]
@andrewbird - Thank you for that list. "libsdl-dev" was my mistake - I was misreading some messages. I'll try again, and this time presumably it will work.

**Comment by jschwartzenberg** [comment]
> Does anyone want to try messing with
> the above? :)

If there's a good spec file or source RPM, COPR should be quite easy. I have some stuff there too (mainly for work). I never used OBS.

**Comment by stsp** [comment]
OK, trying it now...

**Comment by emendelson** [comment]
@stsp - Thank you for the link to dosemu2 downloads. This worked perfectly; no need for me to try building.

**Comment by andrewbird** [comment]
For *BSD there's this https://sourcehut.org/blog/2019-09-12-sourcehut-makes-bsd-software-better/ , though I have no experience with it or BSD.

**Comment by stsp** [comment]
I managed to build on copr:
https://copr.fedorainfracloud.org/coprs/stsp/dosemu2/
comcom32 is not there yet.

**Comment by stsp** [comment]
OBS seems to be using rpmbuild,
and I already switched makefiles
to use rpkg instead, which is what
copr uses.
Not sure if both build systems
should be supported.

**Comment by stsp** [comment]
OK, after a lot of coprology around
djgpp, the copr build is up and running:
https://copr.fedorainfracloud.org/coprs/stsp/dosemu2/
Which is great, as now fedora is also
covered.

**Comment by emendelson** [comment]
> OK, after a lot of coprology around
> djgpp, the copr build is up and running:
> https://copr.fedorainfracloud.org/coprs/stsp/dosemu2/
> Which is great, as now fedora is also
> covered.

Added a wiki page:

https://github.com/dosemu2/dosemu2/wiki/Download-sites-for-dosemu2

**Comment by stsp** [comment]
> You will need to install all three packages: comcom32, fdpp, and dosemu2

But 2 are auto installed by deps.

**Comment by emendelson** [comment]
I see - I didn't notice that you can't download the individual debs directly from that page. Fixed.

**Comment by stsp** [comment]
You can, but there is no reason to do so.
For fedora you need to do:
`sudo dnf copr enable stsp/dosemu2`

**Comment by emendelson** [comment]
I added the "install" line and was coming back to ask if it was right - and saw that you had already added it to your post.
