### ISSUE TITLE
Change text screen size (rows/columns), as with old MODE command?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1146]
In old dosemu, the FreeDOS MODE command let you change the screen size (rows/columns), after using an xmode command to change the font to "vga". Then you used a command like this

`mode con lines=43 cols=90`

Is this possible in dosemu2? I can't find any equivalent but probably I haven't looked in the right places.

**Comment by stsp** [comment]
We do not (yet, or at all) provide any
equivalents of most dos commands.
The current strategy is whether to provide
the particular equivalent, is decided
with the case study, and the rest should
be provided with the download scripts,
that are currently not there. If you are
good in scripting, you can help
@jschwarzenberg to complete them,
and I am not aware of their current
state but I think they are semi-written.

For now you can manually extract
things from dosemu-freedos archive,
or get them by any other means.

**Comment by emendelson** [comment]
OK - I can do simple scripts, but probably not something advanced like this. But I'll see what I can find out there that I can try to modify.

I know that for games and most applications, there's no reason to change the screen size. But it's very useful for text-based applications like WordPerfect, WordStar, XyWrite, etc., where modern hardware lets you edit a large amount of text in a single window if you can change the application's screen size.

**Comment by stsp** [comment]
I found the old @jschwartzenberg branch called
"install_dos" and rebased it to devel, solving
dozens of rejects. You can take a look at that
branch to see if it can be used as a starting
point. It seems to contain quite a lot of stuff.

@jschwartzenberg are you available to revive
that project?

**Comment by emendelson** [comment]
Meanwhile, it seems that the command 

`xmode -font vga`

has no effect at the dosemu2 prompt, but I can set this in the config file:

`$_X_font = "vga"`

and then I can use the dosemu-freedos mode.com to set some video modes. The results are irregular: I can't set 43x80, only 50x80, but I can set 43x132.

It would be very good to have an updated version. I'll look at "install_dos".

**Comment by emendelson** [comment]
I've updated the wiki with instructions for changing text screen sizes.

**Comment by stsp** [comment]
No, not sudo, should be put to C
drive (even when the scripts are written)

**Comment by emendelson** [comment]
OK, fixed. Thank you.

**Comment by emendelson** [comment]
Well, I should have known better. The existing xmode command can change text screen sizes; no need for a separate mode command. The technique is to start dosemu2 with the -X switch, then enter

`xmode -font vga`

and then you can use

`xmode -mode 80`

(anything from 80 through 88 is usable) to change text screen size. And of course mode 7 switches to mode mono.

As I mentioned in a bug report, the CLS command doesn't clear the screen in any mode except mode 3.

**Comment by stsp** [comment]
Is this still of an interest?

**Comment by emendelson** [comment]
No; it's settled now. Thank you again. Closing.
