### ISSUE TITLE
$lpt_2 string should read PDF, not cups-pdf

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1150]
This applies to Ubuntu, and may be incorrect for other distros.

dosemu.conf, line 494, reads:

`# $_lpt2 = "lpr -P cups-pdf"`

But if you install cups-pdf, it creates a printer called PDF, so this line should read:

`# $_lpt2 = "lpr -PDF"`

**Comment by stsp** [comment]
I think it worked on fedora sometime.
But if you think its wrong, please open
a PR with a fix.

**Comment by emendelson** [comment]
Will do.
