### ISSUE TITLE
problem with bfd definitions (include) using binutils-2.34

### ISSUE THREAD

**Issue by jmrcpn** [dosemu2/dosemu2#1153]
Unable to compile dosemu2-2.0pre8 using binutils-2.34

Building process (extract from the spac file)
./autogen.sh
./default-configure					\
        --prefix=%{_prefix}				\
        --includedir=%{_includedir}			\
	--exec-prefix=%{_exec_prefix}			\
        --sysconfdir=%{_sysconfdir}/%{name}		\
        --sbindir=%{_sbindir}				\
	--mandir=%{_mandir}				\
	--libdir=%{_libdir}				\
	--infodir=%{_infodir}				\
	--docdir=%{_defaultdocdir}/%{name}-%{version}	\
	--enable-debug

compilation result.
backtrace-symbols.c:130:9: error: too many arguments to function 'bfd_section_size'
  130 |  size = bfd_section_size(abfd, section);
      |         ^~~~~~~~~~~~~~~~
In file included from backtrace-symbols.c:60:
/usr/include/bfd.h:1205:1: note: declared here
 1205 | bfd_section_size (const asection *sec)

My guess:
Dosemu2 Code need to be adjusted according new BFD definition within /usr/include/bfd.h

Other way  to bypass that problem?

**Comment by stsp** [comment]
Try --disable-xbacktrace

**Comment by jmrcpn** [comment]
Hello,
On Wed, 2020-05-13 at 11:18 -0700, Stas Sergeev wrote:
> Try --disable-xbacktrace
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or
> unsubscribeSeems to 
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/dosemu2/dosemu2/issues/1153#issuecomment-628162302
> ",
> "url": "
> https://github.com/dosemu2/dosemu2/issues/1153#issuecomment-628162302
> ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
Seems to be a solution, at least for now...(no xbacktrace available within dosemu2?)
-- 
You have seen "Linux from scratch" and looking for ISO files
www.osukiss.org

**Comment by stsp** [comment]
This is not a crucial functionality.
Its only needed for logging crashes.
The problem with libbfd is that it
always change their APIs and do
not recommend using it to anyone.
Backtracer should be ported to libelf.
