### ISSUE TITLE
xmode -font vga has no effect

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1154]
In the old dosemu, this command changed the font immediately:

`xmode -font vga`

In dosemu2, it has no effect, although this string in .dosemurc changes the font correctly:

`$_X_font = "vga"`

Is it possible to make the xmode command function in dosemu2?

This command makes it possible to use different text screen sizes with the FreeDOS mode command.

**Comment by stsp** [comment]
I made it to work with `dosemu -X`.
Otherwise - no, pretty much impossible.

**Comment by emendelson** [comment]
I've added some details to the wiki about setting other text video modes. 

One thought for the future: With DOSBox, it's possible to patch the code by adding video modes and small programs to switch to those modes. For text applications, it would be good to be able to switch to 80x43 or 80x50 or 80x60, etc. modes that use the default font, not the X font, as I can do in my patched DOSBox and DOSBox-X. This is presumably something that I'll have to figure out on my own.

**Comment by stsp** [comment]
Not sure why you suggest `dosemu -X`
if you never mentioned xmode there.
What else doesn't work w/o -X?

**Comment by jschwartzenberg** [comment]
I think you misread, DOSBox-X != `dosemu -X`, but it's this project: https://github.com/joncampbell123/dosbox-x

**Comment by stsp** [comment]
No, I mean in wiki:
https://github.com/dosemu2/dosemu2/wiki/Setup-guide-for-complete-beginners-(using-Ubuntu)

**Comment by emendelson** [comment]
Yes, I was wrong - I misunderstood what you said about making it work with dosemu -X. I didn't realize that "xmode -mode" works correctly with plain dosemu. I've fixed the wiki, and also added the commands to change the text screen size.
