### ISSUE TITLE
How to add TEXT_MONO video modes?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1156]
The `vgaemu_modelist.h` file in the dosemu2 source has this line near the top:

` * Modes defined via dosemu.conf will be appended to this list.`

I would like to create some custom text modes  (80x50, 90x43, etc., all using the 9x16 font) but I can't find the place in dosemu.conf where I can define these. I see that there's a line for defining VESA modes, but these aren't VESA modes.

Am I missing something obvious, yet again?

**Comment by stsp** [comment]
All custom modes, even text ones,
should be defined as VESA modes,
in a vendor-specific mode numbers
range.
Currently there is no config to define
VESA text modes, but with a small
hacks you can try to get there.
In vgaemu.c:2087 you can see
`vmi->mode_class = GRAPH;`
Change GRAPH to TEXT.
This will probably break the current
VBE modes, but you don't need them
for an experiment. Mainly, all custom
VESA modes you define, will be text
after that change.
Maybe you will need a few more tweaks
in the same function to get thing work
properly. If you succeed, we can add
the missing configuration options.

**Comment by emendelson** [comment]
OK, I'll have to figure out how to build dosemu2 before I can experiment. If anyone's willing to post a wiki page about building (starting from a system with no build tools installed), that would be very helpful to anyone who wants to experiment.

I've added text modes to DOSBox (and I use 80x43 as the default in my WPDOS systems), but I know how to build DOSBox, and I'll have to learn how to build dosemu2.

**Comment by stsp** [comment]
You can run "make deb" and it will
either complain to missing deps, or
will create the debs (not to confuse
deps vs debs).

**Comment by emendelson** [comment]
So, after figuring out six things that would have been obvious to anyone else, and installing twenty-two new packages, I ran

git clone https://github.com/dosemu2/dosemu2.gitmake
./autogen.sh
./default-configure
make deb

and built a Debian package for dosemu2. I'll start experimenting with this tomorrow.

**Comment by emendelson** [comment]
Experimenting, I added these modes to vgaemu_modelist.h,
 
`{0x20,    -1,  TEXT, TEXT,  4,  720,  688,  80, 43,  9, 16},`  
`{0x21,    -1,  TEXT, TEXT,  4,  810,  688,  90, 43,  9, 16},`  
`{0x22,    -1,  TEXT, TEXT,  4,  720,  800,  80, 50,  9, 16},`

and I can switch to those modes using xmode -mode 32 or 33 or 34, but they don't work correctly, so I'll abandon this until I know how to fix them. The CLS command doesn't work correctly, even though I forked from the latest code, and if I use WPDOS 5.1, Shift-F7, Preview, then F7 to switch back from graphic to text mode, the screen is corrupted. Also, very strangely, the CLS fix stops working in other modes (mode 7 is a clear example), though I made the fork in the last hour.

No need to reply to this.

**Comment by stsp** [comment]
So I think this can be closed, as I
already added the modes for you.

**Comment by emendelson** [comment]
Yes, thank you again!

**Comment by emendelson** [comment]
Question: are some video mode numbers reserved somewhere in the source so that I can't use them when customizing vgaemu_modelist.h? 

Using your new code, I successfully modified this line

`{0x51,    -1,  TEXT, TEXT,  4,  640,  602,  80, 43,  8, 14},`

to this

`{0x51,    -1,  TEXT, TEXT,  4,  720,  688,  80, 43,  9, 16},`

which gives me exactly the readable 80x43 screen that I want.

But if I use the same line, changing only the mode number, like this:

` {0x80,    -1,  TEXT, TEXT,  4,  720,  688,  80, 43,  9, 16}, `

or

` {0x20,    -1,  TEXT, TEXT,  4,  720,  688,  80, 43,  9, 16}, `

then that mode produces a blank window.

I'm trying to create a few more modes that use the 9x16 font, but, for obvious reasons, I'd like to be able to use an unused mode number. Am I missing something obvious yet again?

**Comment by emendelson** [comment]
OK, to answer my own question, int10.c, change:

`  return mode <= 3 || mode == 7 || (mode >= 0x50 && mode <= 0x5a);`

to:

`  return mode <= 3 || mode == 7 || (mode >= 0x40 && mode <= 0x5a);`

and then I can use mode 64-79 for custom modes.

**Comment by stsp** [comment]
Good finding.
I removed that check.

**Comment by emendelson** [comment]
Thank you. I've made a few new 9x16 text modes, and will experiment with the new code tomorrow. I hope this means that it won't be too hard to create text modes from dosemu.conf, but we'll see.

**Comment by emendelson** [comment]
OK, so I made the change to vgaemu.c:2087 that you described above, and tried adding some VESA modes to .dosemurc. It seems clear from the code that it will only accept xres,yres, so I tried adding some sizes, but (1) I don't know which mode number to use and (2) the ones I tried seem to have no effect. As far as I can tell, the existing VESA modes end with 0x120, so I tried xmode -mode 0x121, but it had no effect.

I think this is completely beyond my abilities, and I don't think you should spend any time on this for the few people who would need it.

**Comment by stsp** [comment]
You can also find the needed mode here:
http://www.ctyme.com/intr/rb-0069.htm
and then just add to modelist directly.

**Comment by emendelson** [comment]
> You can also find the needed mode here:
> http://www.ctyme.com/intr/rb-0069.htm
> and then just add to modelist directly.

That's basically what I've done - and there's a version of that mode list on my WordPerfect site: http://www.columbia.edu/~em36/wpdos/videomodes.txt

I've added these to vgaemu_modelist.h:

`/* `  
`   * custom 9x16 text modes `  
`   */ `  
`  {0x20,   -1,  TEXT,  TEXT,  4,  720,  560,  80, 35,  9, 16}, /* 32 */`  
` {0x21,   -1,  TEXT,  TEXT,  4,  810,  560,  90, 35,  9, 16}, /* 33 */`  
`  {0x22,   -1,  TEXT,  TEXT,  4,  720,  688,  80, 43,  9, 16}, /* 34 */`   
`  {0x23,   -1,  TEXT,  TEXT,  4,  810,  688,  90, 43,  9, 16}, /* 35 */`  
`  {0x24,   -1,  TEXT,  TEXT,  4,  720,  800,  80, 50,  9, 16}, /* 36 */`    
`  {0x25,   -1,  TEXT,  TEXT,  4,  810,  800,  90, 50,  9, 16}, /* 37 */`  
`  {0x26,   -1,  TEXT,  TEXT,  4,  720,  960,  80, 60,  9, 16}, /* 38 */`  
`  {0x27,   -1,  TEXT,  TEXT,  4,  810,  960,  90, 60,  9, 16}, /* 39 */`  
`  {0x28,   -1,  TEXT,  TEXT,  4, 1188,  688, 132, 43,  9, 16}, /* 40 */`    
`  {0x29,   -1,  TEXT,  TEXT,  4, 1118,  800, 132, 50,  9, 16}, /* 41 */`   
`  {0x2a,   -1,  TEXT,  TEXT,  4, 1118,  960, 132, 60,  9, 16}, /* 42 */ `   
 
and they work perfectly. I suppose I can offer my own .deb to word-processing users with these built into the mode list.

I also tried adding similar modes with TEXT_MONO instead of TEXT, as in mode 7, but something in the code prevents any TEXT_MONO mode from displaying correctly unless it's mode 7. I'll continue to look for this and see if I can find any way to change it.

**Comment by emendelson** [comment]
To continue...

I tried setting up a TEXT_MONO mode with 35 lines and giving it the number 0x31 (=49, i.e. 7X7,  easy to remember) and changed int10.c: 502 to;:

`  if(mode == 7 | mode == 0x31) {`

but the effect was to create dark blue text on a black background, so I'm obviously missing something somewhere else.

**Comment by stsp** [comment]
Why do you need TEXT_MONO?
Does it matter?

**Comment by emendelson** [comment]
A few people (including me) use it for word-processing. It's the least distracting way to work; the underline attribute is less distracting than a different color for the text. I use it for all my serious writing in WordPerfect - 80x43 in either vDos or my patched version of DOSBox-X. (vDos supports mode mono in any screen size, and DOSBox/DOSBox-X is easy to patch to create new screen sizes).

Since maybe two people in the world will ever want a TEXT_MONO larger than 80x25, it's not worth anyone else's time to think about this.

**Comment by stuaxo** [comment]
There's a line in vga/miscemu.c that mentions mono, maybe this also needs patching ?

https://github.com/dosemu2/dosemu2/blob/0413865b44952d23e24e7434a46228216e0a01f5/src/base/dev/vga/miscemu.c#L96

**Comment by emendelson** [comment]
> 
> 
> There's a line in vga/miscemu.c that mentions mono, maybe this also needs patching ?
> 
> https://github.com/dosemu2/dosemu2/blob/0413865b44952d23e24e7434a46228216e0a01f5/src/base/dev/vga/miscemu.c#L96

I hoped that was the answer, but I couldn't get it to work. I made these changes:

vgaemu_modelist.h - added this line to my (correctly working video modes):

`{0x31,   -1,  TEXT,  TEXT_MONO,  4,  720,  560,  80, 35,  9, 16}, /* 49 */`

int10.c line 502:

`  if(mode == 7 || mode == 15 || mode == 49) { `

miscemu.c line 95:

` if(vga.VGA_mode == 7 || vga.VGA_mode == 15 || vga.VGA_mode == 49) { `

I also tried (after the above didn't work) changing one more line in miscemu.c, line 102:

`    if(vga.VGA_mode <= 3 || vga.VGA_mode == 7 || vga.VGA_mode == 49) `

Since mode 7 works correctly, it should be possible to make another video mode work.

Incidentally, I was curious about that mode 15 in miscemu.c line 95. I see different descriptions of that mode - dosemu2 treats it as a graphic mode, but I've seen it described elsewhere as an EGA mono mode.

**Comment by stsp** [comment]
OK, lets re-open this until the way of
adding TEXT_MONO is found (which
should be pretty simple)

**Comment by emendelson** [comment]
OK, thank you. Just as an experiment, I also tried changing int10.c:500 to read:

`if(config.cardtype == CARD_MDA) mode = 49;`

and then specified in .dosemurc

`$_video = "mda"`

But this produced the same dark blue text on a back background. And (this may be relevant) in the 32-bit NTVDM the same dark blue text on a black background occurs when you try to enter mode 7 in a command.com window (at least that is how I remember it; I can boot to a 32-bit Windows system if it's worth confirming this).

**Comment by emendelson** [comment]
Continuing to experiment, I tried defining mode 7 in vgaemu_modelist.h as a 43-line mode, like this:

`  {0x07,    -1,  TEXT,  TEXT_MONO,  4,  720,  688,  80, 43,  9, 16},`

But when I switched to mode 7 in dosemu, the window was still 25 lines, not 43. It was, however, in mono mode (confirmed when I ran WordPerfect). So something is forcing any TEXT_MONO mode to 25 lines. I don't know if this is any help, so apologies for wasting bandwidth if it says nothing useful.

**Comment by emendelson** [comment]
While we're on the subject, in .dosemurc, 

`$_video = "mda"`

produces a blinking cursor near the top of the text line, and CLS doesn't clear the screen.

The option "mga" produces the same result - but I'm not clear on what "mga" means. There are references in the code to "hgc" (Hercules Graphic Card") but "hgc" is an invalid value in .dosemurc.

**Comment by stsp** [comment]
mga means Matrox.

**Comment by emendelson** [comment]
I should have remembered that. I once had one of those cards, and found that it needed some custom settings in WPDOS to get text attributes right.

**Comment by emendelson** [comment]
More mode mono issues:

If I start dosemu2 normally and then switch to mode 7 (xmode -mode 7), the underline attribute doesn't work. Steps to reproduce:

xmode -mode 7
start WPDOS
Press F11 or Alt-F3 to open Reveal Codes
Type a few letters, then press F8 to turn on underline and type a few more letters.
You'll see [UND]...[und] in Reveal Codes, but no underline. 

There's a note in the documentation about the underline attribute being added in old dosemu, if I remember.

If I start dosemu2 with $_video = "mda" then the underline doesn't work, and there's an additional problem, with the cursor in the middle of the line, not below it.

**Comment by emendelson** [comment]
Yes, here's the reference in ChangeLog.old:

2006-10-28  Bart

	* [r1641] src/env/video/render.c, src/env/video/text.c,
	  src/include/render.h, src/include/vgatext.h, src/plugin/X/X.c,
	  src/plugin/sdl/sdl.c:
	  Create a "bitmap" text system in render.c that is shared by X and
	  SDL. Implemented line drawing (for mono underline) on the canvas.
	  The text cursor and underlining now go through the remapper on X.
	  Remove scaling from the previously used X calls (impossible with
	  X fonts). Screen updates now lock the surface during the whole
	  update for SDL; the SDL code pushes rectangles to be updated and
	  sends them in one go. Mode changes need to be checked before
	  locking the surface: moved the mode adjust calls out of the
	  common update code.

**Comment by bartoldeman** [comment]
The `$_video` options are meant for console video only, not X, so they should not do anything but may do anyway because of historical cruft.

This was written in a time when dosemu was mostly used on the text mode console, and there was also support for dualmon, ie. a second monochrome monitor where the appropriate part of the video memory went to the second monitor, something entirely different from dual monitor setups you can do nowadays. It may still possible to boot Linux that way (using `nomodeset`) but I haven't done it for a while.

**Comment by emendelson** [comment]
Understood. Thank you. My old WordPerfect under Linux page had a lot about mapping Windows drives on a dual-boot system, and I expect that this isn't very common these days either. Meanwhile, is there any hope you might revisit your underline fix for the new version? I know I'm asking a lot, but dosemu2 is really a terrific way to run DOS applications. It's faster in a VMware machine than DOSBox-X is in a real Windows system.

**Comment by jschwartzenberg** [comment]
> It's faster in a VMware machine than DOSBox-X is in a real Windows system.

Are you using a 32-bit or 64-bit guest? It would be interesting to see which one performs better. For a 32-bit system, it might be useful to compile a custom kernel. Newer Windows versions also have virtualization options built in.

**Comment by emendelson** [comment]
> > It's faster in a VMware machine than DOSBox-X is in a real Windows system.
> 
> Are you using a 32-bit or 64-bit guest? It would be interesting to see which one performs better. For a 32-bit system, it might be useful to compile a custom kernel. Newer Windows versions also have virtualization options built in.

I'm patching, etc. on a 64-bit Ubuntu Mate VM; I'm also running the unpatched dosemu2 on a a 64-bit Ubuntu (ordinary version - whatever it's called).

**Comment by emendelson** [comment]
@stsp - Thank you!

**Comment by john-peterson** [comment]
i can't find the palette source 

i looked in the linked file but it looks like its drawing images not console i see no reference to colours

https://raw.githubusercontent.com/dosemu2/dosemu2/master/src/base/video/render.c

can it be this file?

https://raw.githubusercontent.com/dosemu2/dosemu2/master/src/base/video/text.c

if you want to know my issue directly its below the line

---

Can you help me with the colour or removing all colours 

The program I'm trying to run is

https://allowe.com/download/softporn.zip

this is what i tried

wrong colours

```
dosemu SOFTPORN.EXE
```

Still wrong for vga ega cga. mda mga give only black. plainvga give syntax error. I can't seem to touch the actual palette that is just wrong

```
one of: plainvga, vga, ega, mda, mga, cga
dosemu -I 'video {cga}' SOFTPORN.EXE
```


nothing here either?! and after exiting the program mode is back to 3?? why does mode change back from 7 to 3 after the program has exited?

```
insfdusr
mode mono
softporn
```

Nothing here either still wrong

```
dosemu -K .
xmode -mode 7
softporn
```

i also tried this program that did nothing

```
 curl -L https://www.vogons.org/download/file.php?id=54324 -o setmono.zip
dosemu -K .
setmono
softporn
```

whatever i do the colours are unchanged and wrong. the game text is illegible
![Screenshot_20230908-135602](https://github.com/dosemu2/dosemu2/assets/207571/453acdc4-4d69-4d8f-933b-0cf03d4ddb84)


the correct colors are blue and yellow but it picks the closest it can find . light blue for both

![Screenshot_20230908-135738](https://github.com/dosemu2/dosemu2/assets/207571/6609282d-9693-42c8-af02-774dc63c9de3)


i can't use dosbox or x11 because DISPLAY is unset and i have no display

**Comment by stsp** [comment]
https://raw.githubusercontent.com/dosemu2/dosemu2/master/src/plugin/term/terminal.c
