### ISSUE TITLE
mfs: find_file() modifies fname, is it expected behaviour?

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1158]
I made `find_file()` take a `const char *` for fname by copying the input string inside the function before modifying it, but it broke some tests. Before I figure out why, I'd like to know if `find_file()` is supposed to modify its input string?

**Comment by stsp** [comment]
See 7b351640d.
I don't like this either.

**Comment by andrewbird** [comment]
Okay, so whilst not nice at least it's known behaviour. Thanks!
