### ISSUE TITLE
xmode -mode 81 and 85 cause screen corruption

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1159]
**Describe the bug**
The command `xmode -mode 80` produces the correct screen, but modes 81 and 85 cause screen corruption - nonsense characters instead of the prompt, and rows of dashes instead of a blank screen. Both of these are 43-line modes.

**To Reproduce**
`xmode -mode 81` 
or
`xmode -mode 85`

**Comment by stsp** [comment]
Just some unsupported mode I think.
Why would you do that?

**Comment by emendelson** [comment]
Because some DOS text applications work correctly in screens larger than 80x25. My Windows and macOS systems for running WPDOS default to using 80x43 text screens, because that's a generally useful size for word processing. I was hoping to use the same screen size in dosemu. I can use the 50-line mode.

Further detail: mode 81 and 85 both work correctly with `dosemu -X` if you first run the command `xmode -font vga` and then start up those modes. Those modes will also work in non-X dosemu if .dosemurc has the line `$_X_font = "vga"`.

I don't know if it's worth fixing this, but, as far as I can see, the 43-line modes are the only ones that aren't consistent between dosemu-X and dosemu.

**Comment by stsp** [comment]
OK, these are trident svga text modes
with non-standard font size 8x11.
We have no fonts for such, so not sure
why are they supported.

**Comment by emendelson** [comment]
What would be really useful in the modern world would be to have those 43-line modes with the standard bitmap or vga font (9x14?) but that's probably too much to hope for.

**Comment by stsp** [comment]
Why not?
That's exactly the point of adding custom
modes. But in fact... who cares if I just replace
these broken modes with the ones you ask for?
No one will sufficiently hurt.

**Comment by emendelson** [comment]
I would be very, very grateful if you could replace those broken modes that way. No one wants small fonts in modern emulators. The 60-line modes already use large fonts, so the 43-line modes can certainly use them also.

**Comment by emendelson** [comment]
Thank you!
