### ISSUE TITLE
Trace memory mapped I/O

### ISSUE THREAD

**Issue by dos4boss** [dosemu2/dosemu2#1161]
Let's say I have an old ISA card, that uses I/O ports and memory mapped I/O. I can run dosemu2 on the machine with the original software. With passthrough of the ports (`$_ports`) and memory (`$_hardware_ram`), the stuff is working beautifully (well, somehow slow on an old Pentium, but having that passthrough capability by default is a really cool feature of dosemu2).

So far so good. `$_trace_ports` (had to modify to only trace the ports of interest) makes it possible to know what communication is happening there. My question now is: can I achieve something similar to capture the communication via MMIO? That would be very useful for the kind of stuff I explained above..

Thanks!

**Comment by stsp** [comment]
Well, there are not too many ways of
implementing that. From the viable ones
I am aware of (leave aside fault+simulate,
as it is both too difficult and too slow for
that), are:
1. use libipt (that will only work with KVM,
and on a very small amount of CPUs)
2. use the CPU emulator

Option 2 looks very viable to me.
Bart, how would you estimate an efforts
needed to implement the MMIO logging
with cpu emulator? I suppose for SIM it
costs pretty much nothing, as all needed
access handlers you already added recently?
And for JIT, its probably not very difficult
too, at least not much different than was
embedding LDT writes?

**Comment by dos4boss** [comment]
I'd also argue for option 2. Reason being is that especially the old stuff with which you want to debug ISA cards for example usually don't allow any KVM. KVM-capable hardware often does not have ISA slots at all.

If you can point me to the interesting bits and pieces ("access handlers") and mention the possible pitfalls, then I might be able to come up with a first implementation at least for the SIM stuff.

**Comment by stsp** [comment]
Set
```
$_cpu_vm="emulated"
$_cpu_vm_dpmi="emulated"
$_cpu_emu = "fullsim"
```

Then look into dos2linux.c funcs
read_XX() and write_XX() where
XX is either byte, word or dword.
The accesses should go through
these funcs.

KVM-capable CPU is not enough
for this. To get memory traces from
KVM, you need a very specific and
new CPU feature called
"Intel Processor Trace" AFAIK.
Which is why I said libipt is going
to work on a very small amount
of available CPUs.

**Comment by dos4boss** [comment]
I do have a first implementation [here](https://github.com/dos4boss/dosemu2/tree/isa_debug) if someone is interested.

BTW, I have a problem running an .exe, that works under Dosbox. It fails to open '386max$$' if I add file I/O tracing, but I don't know if thats the cause. I do know that it is a 'rebind' PharLap DOS Extender application, but can't find a way to get the extender stub/initializer to print debug output. Any ideas?

**Comment by stsp** [comment]
Memory accessors are a performance-critical
funcs, so I'd rather add a check to avoid calling
mmio_check_and_trace() without a need, like
if (config.mmio_trace) mmio_check_and_trace();
Anyway, would you like to open a PR?

You mean, depending on a debug options,
it behaves differently? That would mean some
bug in dosemu. Is this only with CPU emulator?

**Comment by bartoldeman** [comment]
The tracing could be done just before check_read_pagefault and check_write_pagefault instead to avoid performance issues. This way there are on the slow path -- ie. the traced pages are never added to the unprotected cache. It's then similar to VGA accesses which are a form of MMIO really. Like this:

```
uint8_t do_read_byte(dosaddr_t addr, sim_pagefault_handler_t handler)
{
  if (mem_likely_protected(addr, 1)) {
    /* use vga_write_access instead of vga_read_access here to avoid adding
       read-only addresses to the cache */
    if (vga_write_access(addr))
      return vga_read(addr);
    if (mmio_check(addr))
      return mmio_trace(addr, READ_BYTE(addr), MMIO_READ | MMIO_BYTE);
    check_read_pagefault(addr, handler);
  }
  return READ_BYTE(addr);
}
```

**Comment by dos4boss** [comment]
I have implemented the suggestions regarding performance criticality.

But at least two things are remaining:
1. I want to raise an error, if the cpu is not configured as emulated/fullsim. Unfortunately, the config for `cpuemu/cpu_vm/cpu_vm_dpmi` is parsed after the mmio tracing config, otherwise I would have put that into `src/base/init/parser.y`. So what is the preferred way here? I don't really like to do these checks everytime in `mmio_check` for example.

2. man-page and --help documentation has to get the new debug option `F`. I was to lazy until now...

If those things are done, I will open a PR.



> You mean, depending on a debug options,
> it behaves differently? That would mean some
> bug in dosemu. Is this only with CPU emulator?

No, it is not related to any debug options and also not to this issue. I was just wondering why it is running in dosbox, but not in dosemu2 and hoped that you might have an idea from experience.

**Comment by stsp** [comment]
> So what is the preferred way here?

You can just add a code into `config_post_process()`
or do `register_config_scrub()` and raise an error
on that late stage. You don't need to raise it immediately
when you just parsed your mmio_trace setting. It
doesn't matter when you raise an error, as long as
it is done before boot. All you need is to set some
flag in a config structure and check it later.

> running in dosbox, but not in dosemu2 and hoped that you might have an idea from experience.

But you said `It fails to open '386max$$' if I add file I/O tracing`
which suggests it depends on settings.
Anyway, this may mean an unsupported
DOS extender. But I never seen that. We
do not support PharLap run286, but the
error msg is usually different...
run386 extender is fine.

**Comment by dos4boss** [comment]
> You can just add a code into `config_post_process()`
> or do `register_config_scrub()` and raise an error
> on that late stage.

Thanks, glad I asked. I was not aware of this function but it was exactly what was needed!
PR is opened #1183.



> But you said `It fails to open '386max$$' if I add file I/O tracing`
> which suggests it depends on settings.

What I wanted to say was that I can only see that it tried to open this file if I enable the debug traceing. Otherwise, it will still try it, but I cannot see...
I have found out how to enable debug output from the extender. You had to run `cfig386 <exe name> -DEBUG 10`. So now I know that it is shipped with `TNT DOS-Extender 8.02 -- Copyright (C) 1986-96 Phar Lap Software, Inc.`. And comparing all the debug output with the one from dosbox lead me to the conclusion, that it has to do something with DPMI probably. In dosemu2, it detects DPMI version = 0.90 and hence does not load `386|vmm` as in dosbox, where it does not detect any DPMI. Long story short: How do i disable DPMI in dosemu2? All configurations I have tried crashed immediately..

**Comment by stsp** [comment]
> What I wanted to say was that I can only see that it tried to open this file if I enable

Ah, you meant to say you see that in the log,
not on screen!

> How do i disable DPMI in dosemu2?

No, you can't. Sorry. :)
Can you look for run286 and run386 strings
in a binary? If its run286, then currently there
is no work around that. Maybe one day...

**Comment by stsp** [comment]
`-DEBUG 10` is a nice trick!
The extender that works, is:
TNT DOS-Extender 6.1 -- Copyright (C) 1986-93 Phar Lap Software, Inc

Btw, cfig386 already means that it is
run386, and it is also newer than what
I have, so it should work!
Could you please upload it?

**Comment by dos4boss** [comment]
> `-DEBUG 10` is a nice trick!

Yes, and it was more or less luck I found it. Don't know if it is documented somewhere. Or at least somewhere you can still find it tody..

I have created a short script to get the exe in question. There is additional stuff in it, like for example `cfig386` (also in tools). That's why I have not uploaded just the exe. It will report the exe in question in the end.

``` bash
tmpdir=$(mktemp -d)
filename="basev5.21.zip"
wget http://gotroot.ca/cmu200/BASEV5.21.exe -O ${tmpdir}/${filename}
cd ${tmpdir}
unzip ${filename}
cat ARCHIV.0* | tee -a archiv.tgz > /dev/null
mkdir -p root
tar xf archiv.tgz -C root || true
echo "File in question is ${tmpdir}/root/TOOLS/cmud.exe"
```

**Comment by stsp** [comment]
```
D:\TOOLS>cmud.exe
 
## Error at tme.cpp:652, Revision /main/5.20/2
## Date Sat May 30 23:42:57 2020
  Hex: 0x53
## (repaired)
#Can't store msg on disk.#
 
 
## Error at tme.cpp:652, Revision /main/5.20/2
## Date Sat May 30 23:42:57 2020
  Hex: 0x53
## (repaired)
#Can't store msg on disk.#
#Can't store msg on disk.#
```

What does this mean?
Running on dosbox seems to produce
no output at all.

**Comment by stsp** [comment]
No, it does. Just after a long period of wait.

**Comment by dos4boss** [comment]
> What does this mean?
> Running on dosbox seems to produce
> no output at all.

That's when it is not working... And I'm trying to figure out for days why.

> No, it does. Just after a long period of wait.

Yeah, takes some time, but should end up in a kind of command line interface stating `+++++ CMU Debugger (ISA) 7.06b, Jul 29 2010 +++++` as a header

**Comment by stsp** [comment]
Yes, on dosbox it works under a long start.

**Comment by stsp** [comment]
It does some strange things that
we don't support, like mapping the
PCI space (at 0xc0000000) and
requesting the PHARLAP.32PHARLAP.LINEAR_REMAP
DPMI extension.

Does it work under win9x?
Haven't you happen to have a sources
of that cmu stuff by any chance? :)

**Comment by dos4boss** [comment]
So you are telling me that my MMIO implementation was useless for me in the end? :(
Is it correct then, that if I could stop DPMI, it would use the rebind pharlap stuff, which will support the extension? Which also would be an explanation for a working exe in dosbox?

Have not tested it under win9x, but why woluld it have this proprietary dpmi extension?
And no, unfortunately no source code whatsoever. Was decompiling the exe for quite some time the last days, which is extra annoying because of mixed 16-/32-bit mode...

**Comment by stsp** [comment]
> So you are telling me that my MMIO implementation was useless for me in the end? :(

Depends on if we can find the reason
of a problem. I already fixed a few small bugs
for it to go further, but not much further. :(

> Is it correct then, that if I could stop DPMI, it would use the rebind pharlap stuff,

Not under current impl of dosemu2.
You can try qemu.

> Have not tested it under win9x, but why woluld it have this proprietary dpmi extension?

That's the whole point.
PharLap's 386 extender was made with
win9x (and os/2) DOS box compatibility
in mind. They do not have such an extension,
and if the prog works there, then there is
just some fix needed. But if it doesn't work
under win9x and os/2, then it is likely that
the extension is the problem.

**Comment by stsp** [comment]
Why could it map phys mem at PCI
space (0xc0000000)? Do you have any idea?

**Comment by andrewbird** [comment]
> requesting the PHARLAP.32PHARLAP.LINEAR_REMAP
DPMI extension.

That's an odd name, it almost seems like it wants to be two names
`PHARLAP.32` and `PHARLAP.LINEAR_REMAP`

**Comment by stsp** [comment]
Agree but unfortunately:
```
$ strings cmud.exe |grep LINEAR
PHARLAP.32PHARLAP.LINEAR_REMAP
```
There is no separator.

**Comment by stsp** [comment]
It doesn't even call it however.
I think something else is a problem.

**Comment by andrewbird** [comment]
>There is no separator.

Would that display a nul or some other non printable char? What about 
`strings cmud.exe | grep LINEAR | od -c`

Or perhaps have dosemu print the requests it sees.

**Comment by stsp** [comment]
```
$ strings cmud.exe | grep LINEAR | od -c
0000000   P   H   A   R   L   A   P   .   3   2   P   H   A   R   L   A
0000020   P   .   L   I   N   E   A   R   _   R   E   M   A   P  \n
```

`strings` would wrap a line on a separator.

**Comment by andrewbird** [comment]
Oh well, it just doesn't smell right.

**Comment by stsp** [comment]
Its not.
Its some bug, I suppose it hopes
that the DPMI server would do strncmp().
But it doesn't seem to be the problem anyway.

**Comment by dos4boss** [comment]
> You can try qemu.

Reason for using dosemu2 was port i/o, mm i/o passthrough. According to QEMU IRC they don't support ISA passthrough.



> But if it doesn't work
> under win9x and os/2, then it is likely that
> the extension is the problem.

Was trying to install win95 in dosemu. Not successfull yet, but it is supposed to work, right?



> Why could it map phys mem at PCI
> space (0xc0000000)? Do you have any idea?

No, not really yet. It is running on a Rohde & Schwarz test & measurement device. It has some cards with RF hardware that are controlled via ISA, which is what I want to reverse engineer.
![](https://b.goistatic.com/data/auctions/Auction18869/EU364852.jpg)


Regarding `PHARLAP.32` and `PHARLAP.LINEAR_REMAP`: remember that there is a lot of stuff included in the executable, from my understanding it is rather a capability of the built-in extender.

**Comment by dos4boss** [comment]
For reference, if I enable `-DEBUG 10` via `cfig386`, I do get the following logs:

[dosbox.txt](https://github.com/dosemu2/dosemu2/files/4706781/dosbox.txt)
[dosemu.txt](https://github.com/dosemu2/dosemu2/files/4706782/dosemu.txt)

**Comment by stsp** [comment]
> Was trying to install win95 in dosemu. Not successfull yet, but it is supposed to work, right?

No, only 3.1. :)
I can see that some assertion is
triggered in the program. Trying
to debug, but our debugger doesn't
like the code that is too close to the
segment limit...

**Comment by stsp** [comment]
Bart, did you reduce the logging in
cpu-emu? I do -D9+e and I remember
in the past I was seeing all registers and
even the stack content per every instruction.
Now there is only disasm with a few more
messages.

**Comment by stsp** [comment]
It would still be very interesting to run
this under qemu/win9x.
Can you do such a test?

**Comment by dos4boss** [comment]
> It would still be very interesting to run
> this under qemu/win9x.
> Can you do such a test?

Did a test, and unfortunately it is failing there as well...
![win95](https://user-images.githubusercontent.com/65568577/83350477-ac29b080-a33c-11ea-9f74-5dd9784d56d0.png)

**Comment by stsp** [comment]
OK, that means that on dosemu2 this can't
be supported w/o a lot of reverse-engineering
efforts. But its strange that they managed to
create the unportable (and obviously buggy,
PHARLAP.32PHARLAP.LINEAR_REMAP)
program using a very good extender that IS
supported by dosemu and win9x.

The last hope is to check on an older dosbox
that had DPMI. It had even run286 support
of some sort. So if it works there, we can see
what's missing.

**Comment by stsp** [comment]
There is also PHARLAP.386 driver for windows.
Can you try enabling it?
It seems to provide "PHARLAP.LINEAR_REMAP"
extension.

**Comment by dos4boss** [comment]
![win95_2](https://user-images.githubusercontent.com/65568577/83351391-b4391e80-a343-11ea-889b-b727a51f6907.png)

Guess what, I was too fast stating that...
Trying to find out now what caused it to work in QEMU :D

**Comment by stsp** [comment]
To fast stating what?
Is it under windows?

**Comment by dos4boss** [comment]
> To fast stating what?
> Is it under windows?

Yep, WIN95, I have no idea why it is full screen all of a sudden...

**Comment by stsp** [comment]
Wow!
Please find what makes it start then.

**Comment by dos4boss** [comment]
What makes it run under WIN95 is to execute `cmu_b.bat` before. This script sets some environment variables and tries to start the main exe `BASE\BSW\EXE\BASE.EXE`, which all is failing. Nevertheless, starting `cmud` afterwards is not failing anymore...

For reference, that is the debug output of the extender under WIN95: [win.log](https://github.com/dosemu2/dosemu2/files/4707619/win.log).

**Comment by stsp** [comment]
Then find what variables does it need.

**Comment by dos4boss** [comment]
> Then find what variables does it need.

I replicated all variables under dosemu, but that did not help. Also running cmu_b.bat in dosemu is not helping to start cmud afterwards...

**Comment by stsp** [comment]
But still find what variables helped under win9x.

**Comment by dos4boss** [comment]
Indeed, the following .bat in the tools subdirectory is enough to start in successfully in WIN95:

``` bat
SET PATH=%PATH%;C:\CMU\BIN_V5.21\TOOLS

SET TMP=C:\CMU\TMP
SET TEMP=C:\CMU\TMP
SET CMU_DIRECTORY=BIN_V5.21
SET NO_REBOOT=TRUE
SET SYS_BASE=C:\CMU\BIN_V5.21
SET SYS_LOG_DIR=C:\INTERNAL\LOG
SET SYS_REPORT=C:\INTERNAL\LOG\BIN_V5.21
SET SYS_DSP=C:\CMU\BIN_V5.21\FW\DSP
SET SYS_FW=C:\CMU\BIN_V5.21\FW
SET TZ=1
SET CMDLINE=cmud

cmud.exe
```

**Comment by stsp** [comment]
Please find what exactly (one var) helps it to start.

**Comment by dos4boss** [comment]
Actually, setting `SYS_REPORT` to anything (does not have to be a valid path) is enough to get it running.

**Comment by stsp** [comment]
Could you please try on old dosbox with dpmi support?

**Comment by dos4boss** [comment]
After heavy reverse engineering, I finally found the culprit...
It seems to expect some different response from the PIT. I just hacked a fix, will try to explain the reason for the expected responses later.

In essence, it is doing the following interaction with the PIT:
```
PORT: outp(0x43, 0xb4)
PORT: writing outp(0x43, 0xb4)
PORT: pit_outp(0x42, 0xff)
PORT: pit_outp(0x42, 0xff)
PORT: outp(0x43, 0xe8)
PIT2: ticks=daab latch=daab pin=1
PORT: pit_inp(0x42) = 0xb4
```

The last result of pit_inp is hacked to 0xb4, because the program expects either 0xb4, 0xbc, 0xf4 or 0xfc to not go into failure mode. Actually, the hex number reported is what the program read back (so 0x53 in your [posted](https://github.com/dosemu2/dosemu2/issues/1161#issuecomment-636383163) case). If you execute it one after another, you will find numbers all over the place, but very rarely the expected numbers.

**Comment by stsp** [comment]
Wow!
So have you managed to run it?
How have you found out that stuff?
So was SYS_REPORT actually related,
or just random?

**Comment by dos4boss** [comment]
> So have you managed to run it?

Yes

> How have you found out that stuff?

Decompilation of the binary with [Ghidra](https://github.com/NationalSecurityAgency/ghidra). 

> So was SYS_REPORT actually related,
> or just random?

For dosemu2, it does not seem to be a problem if it is not set. Why that fixed it in WIN95 is still not known. But because I am not interested in that WIN95 stuff, I am not going to try to find out why.

**Comment by stsp** [comment]
> Yes

Congrats! :)

> Decompilation of the binary with Ghidra.

Could you please show how that particular
place looks like after a decompilation? Never
used ghidra.

**Comment by dos4boss** [comment]
The short excerpt is looking like the following:

``` c
    set_pit_ch_2_operating_mode(2);
    set_pit_ch_2_freq(0xffff);
    bVar1 = get_pit_ch_2_readback_latched_status();
    if ((((bVar1 != 0xb4) && (bVar1 != 0xbc)) && (bVar1 != 0xf4)) && (bVar1 != 0xfc)) {
      iVar5 = feh_start(aCmu_fsw_bas_65,extraout_EDX,extraout_ECX,aCmu_fsw_bas_65,
                        PTR_aRevisionMain_5_004b7d7c,0x28c,1);
      iVar5 = feh_report_hex(long,int)((uint)bVar1,extraout_EDX_00,(uint)bVar1,iVar5);
      feh_end_repair(int)(iVar5,iVar5);
    }
```

Fortunately, the symbols for `feh_` (probably `file error handling` or so) were available in the binary. Those PIT-functions have been named by myself. An example looks like that

``` c
undefined4 get_pit_ch_2_high_byte(void)

{
  char cVar1;
  undefined3 extraout_var;
  byte local_14;
  
  sys_outport_byte(ushort,char)(0x43,0xe8);
  cVar1 = sys_inport_byte(ushort)(0x42);
  return CONCAT31(extraout_var,cVar1);
}
```
where I had to look up what the exact I/O ports are doing to come up with a good name for the function.

**Comment by stsp** [comment]
Cool!
And how have you got to PIT?
Did the error msg with the source
file and line number was of any use,
or was an error a complete rubbish?

**Comment by dos4boss** [comment]
> Did the error msg with the source
> file and line number was of any use,
> or was an error a complete rubbish?

Yes, that was exactly the reason why I was able to narrow it down to the found location in the code and hence the PIT. While the source file tme.cpp was cited in several places, only one occurrence with the line number 652 (or 0x28c1, as you can also see in the `feh_start`-call above) was in the binary.

**Comment by stsp** [comment]
So does ghidra understand all those old
binary and debuginfo formats of the DOS era?
Sounds like a good tool to aid the dosemu2
development. :)

**Comment by dos4boss** [comment]
> So does ghidra understand all those old
> binary and debuginfo formats of the DOS era?

Don't exactly know that, because the first analysis was done with IDA Pro. Actually, IDA seems to know about the DOS extender stuff, because it detected it as a 32-bit application. With everything on auto it also did not show me any of the PharLap code or some other 16-bit stuff. This intermediate result was then opened in Ghidra. Although IDA also does decompilation, it has it only for 32-bit in the more recent versions. Ghidra on the other hand is also 16-bit capable.

**Comment by andrewbird** [comment]
Interesting about your use of IDA Pro, did it recognise any library components linked in to your test binary via FLIRT signatures?

**Comment by dos4boss** [comment]
I'm not too familiar with FLIRT, but I don't think it did. But probably because there is no .so/.dll used in the binary, at least that's what I think. More of a linux guy than DOS, no idea what the ldd equivalent is.
What was detected are DOS system calls, so all those INT21h were annotated with 
``` asm
push    ebx
mov     edx, [esp+4+arg_0]
mov     ebx, [esp+4+arg_4]
xor     eax, eax
mov     ah, 43h
int     21h   
; DOS - 2+ - GET FILE ATTRIBUTES
; DS:DX -> ASCIZ file name or directory
; name without trailing slash
```
for example.

**Comment by andrewbird** [comment]
Even without the FLIRT signatures those annotations look nice!

**Comment by dos4boss** [comment]
Oh boy, after being happy to have the exe running on my workstation, I wanted to run it on the actual target machine finally (R&S CRTU, with a Pentium III). But obviously, I ran into the next problem...

Can anybody make sense of the following [boot.log](https://github.com/dosemu2/dosemu2/files/4738460/boot.log)?


From my understanding, it is failing in https://github.com/dosemu2/dosemu2/blob/5fd7c332642e909d98821defd4451e1175b4fde6/src/dosext/dpmi/dpmi.c#L900

But i have no idea why... Also I wonder why it is saying "No symbol table info available.". I'm pretty sure it is (compiled with `CFLAGS="-march=pentium3 -mtune=intel -g -O0 -gdwarf-3 " ./configure --prefix=/usr/local --sysconfdir=/etc --enable-plugins=libao,gpm,extra_charsets,term,X,Xkmaps,charsets,json,console,modemu,dosdrv,doscmd,periph,debugger,sdl --disable-fdpp && make && sudo make install`).
And I expected to get some `DPMI: `  log before crashing when started with `sudo dosemu -s -D+D -t` from https://github.com/dosemu2/dosemu2/blob/5fd7c332642e909d98821defd4451e1175b4fde6/src/dosext/dpmi/dpmi.c#L892 but can't find it in the log...

**Comment by stsp** [comment]
> But i have no idea why...

Obviously a bad selector value causes
an out-of-bounds array access. I added
the missing range check.

> but can't find it in the log...

Try -D9+M

**Comment by dos4boss** [comment]
First of all, I have to thank you for your really quick replies all the time! It is really exceptional, how this project is maintained, thanks!

Next, I think there might be another problem. I can see in the new log now, that just before crashing it is saying 
`DPMI: cs=0xc000f7, ss=0xc000ff, ds=0xaf, es=0x17, fs=0x17, gs=0x17 ip=0x2015`
while it was for example 
`DPMI: cs=0x97, ss=0x9f, ds=0xaf, es=0x17, fs=0x17, gs=0x17 ip=0x6` 
before.

In conjunction with the definition 
https://github.com/dosemu2/dosemu2/blob/4bc0e826c23964802c2573400ea58421493de6d9/src/dosext/dpmi/dpmi.c#L819-L824

it is casting down to `unsigned short` during the call in 

https://github.com/dosemu2/dosemu2/blob/4bc0e826c23964802c2573400ea58421493de6d9/src/dosext/dpmi/dpmi.c#L902

which is causing the function to think it is a valid and used selector. But actually it is much bigger than the short (0xc000f7) and the subsequent shift operation and operator[]-access is causing a segfault. 

Actually, this is also an explanation, why it is running on a 64-bit machine and not on 32-bit because the byte width of `_cs` is architecture dependent (see cpu.h).

Because I am not too familiar what the code is really doing, I can think of two reasons for the bug. First, `_cs` is too wide on 32-bit machines. Second, 'ValidAndUsedSelector' should take a wider datatype as an argument.

**Comment by stsp** [comment]
> it is casting down to unsigned short during the call in

Thanks, I changed that to catch an errors.

> Edit: Or third, cast _cs to be 16-bit before doing all the access with it.

This may work, but I wonder who trashed
the high word. Is it on cpu emulator? Can you
see the same with native or KVM executions?

**Comment by dos4boss** [comment]
> Is it on cpu emulator?

Yes, it is set as you said in https://github.com/dosemu2/dosemu2/issues/1161#issuecomment-631726044.

> Can you
> see the same with native or KVM executions?

Native would be all of those variables commented out? KVM won't be possible on the PentiumIII-machine.

> This may work, but I wonder who trashed
> the high word.

I have tried casting `_cs` and `_ss` before using and on the first try it is crashing with some error from the extender and not enough stack space or so. But rerunning the exe will finally allow it to startup.

**Comment by andrewbird** [comment]
I wonder if hardware vm86() is possible on Pentium III?

**Comment by stsp** [comment]
> Native would be all of those variables commented out?

$_cpu_vm_dpmi = "native"

> I wonder if hardware vm86() is possible on Pentium III?

It should, but for DPMI is quite irrelevant.
But would be nice to test anyway!
So $_cpu_vm = "vm86"

**Comment by dos4boss** [comment]
#### all emulated
The bug is indeed only happening for 

```
$_cpu_vm="emulated"
$_cpu_vm_dpmi="emulated"
$_cpu_emu = "fullsim"
```
It will stop dosemu because of the invalid selector ([boot_emulated.log](https://github.com/dosemu2/dosemu2/files/4740754/boot_emulated.log)).



#### native dpmi
For 
```
$_cpu_vm="emulated"
$_cpu_vm_dpmi="native"
$_cpu_emu = "fullsim"
```
it is giving 
```
Fatal Error TNT.10049: Out of stack buffers, CS:EIP are in error values:
Err values = 00000097h 00000005h
ERROR: DPMI: Warning: trying to leave DPMI when in_dpmi_pm_stack=7
``` 
first, but runs successfully after rerunning the exe ([boot_dpmi_native.log](https://github.com/dosemu2/dosemu2/files/4740758/boot_dpmi_native.log))

#### native dpmi, vm86 mode
For 
```
$_cpu_vm="vm86"
$_cpu_vm_dpmi="native"
$_cpu_emu = "fullsim"
```
it is the same as above (native dpmi only), so working, and it is generally a lot quicker i think ([boot_dpmi_native_vm86.log](https://github.com/dosemu2/dosemu2/files/4740759/boot_dpmi_native_vm86.log)).

#### native dpmi, vm86 mode, cpu emu off
For 
```
$_cpu_vm="vm86"
$_cpu_vm_dpmi="native"
$_cpu_emu = "off"
```
again the same as above, working on second try ([boot_dpmi_native_vm86_off.log](https://github.com/dosemu2/dosemu2/files/4740761/boot_dpmi_native_vm86_off.log)).

**Comment by stsp** [comment]
Cool, so the bug is specific to cpu-emu.
Bart, could you please take a look where
the high word of CS can get garbage in
SIM mode? I suppose its something very
simple, like a forgotten mask in some op.

Anyway, we need to commit some timer
change so that I can test it myself.

**Comment by dos4boss** [comment]
Maybe 
https://github.com/dosemu2/dosemu2/blob/4bc0e826c23964802c2573400ea58421493de6d9/src/dosext/dpmi/dpmi.c#L81 was supposed to be used for _cs and _ss?!

With "native" dpmi, I think mmio tracing stopped working. That is expected, right?

> Anyway, we need to commit some timer
> change so that I can test it myself.

You are talking about #1186 ? I'm still not finished with that, cause the fu**ing exe is trying to measure if the timer is running with the right frequency I suspect. Cause even if the status readback is correct, it will fail after a lot of PIT interaction in the end. Luckily, my first hack (0x42 was always reading back as 0xb4 no matter what) somehow passed this frequency testing, to have it running.

**Comment by stsp** [comment]
As #1186 is fixed, I've got your cmud
working in either SIM or JIT modes.
I can't reproduce either the CS crash
or "starts from second time" problem.

**Comment by stsp** [comment]
Could you please re-check everything?

**Comment by dos4boss** [comment]
Sorry for being silent the last few days, was quiet a busy time in my professional work.
Awesome that the PIT error is fixed now, THANKS! I can confirm, that it seems to work correctly at least on my Linux machine for now.
I honestly don't remember all the details, but without `-D9+M` I can also have the exe starting up successfully now without any further hacks. However, if the logging is enabled, it is only starting on the second try and before is giving me the `Fatal Error TNT.10049: Out of stack buffers...` stuff.

**Comment by stsp** [comment]
What kind of logging?
Could you please minimize the logging
and find which one breaks things?
Also I'd like to get your trace patch in, I
think not too much remained to pass a
review.
Can you give it some time? :)

**Comment by dos4boss** [comment]
`-D9+M` is enough to break it...

Only the boring stuff is remaining for the PR, which might explain my limited interest in it 🗡️ 
But yes, will have a look into it now..

**Comment by stsp** [comment]
> -D9+M is enough to break it...

I tried it many times.
Sometimes it crashes, sometimes not,
even from the first start.
So I think there is no bug on dosemu
side, just some timing problem.
Could you confirm such observation?

**Comment by stsp** [comment]
Could you please try this patch:
```
diff --git a/src/dosext/dpmi/dpmi.c b/src/dosext/dpmi/dpmi.c
index 194094ad0..0d32a8572 100644
--- a/src/dosext/dpmi/dpmi.c
+++ b/src/dosext/dpmi/dpmi.c
@@ -3104,7 +3104,8 @@ void run_pm_int(int i)
    * - STI can be done also by the chained real-mode handler
    * - We need to allow processing the different IRQ levels for performance
    * So simply mask the currently processing IRQ on PIC. */
-  if (i == 8) {
+  if (i == 8 || i == 0x70) {
+    /* PIT or RTC interrupt */
     unsigned char isr;
     port_outb(0x20, 0xb);
     isr = port_inb(0x20);
```

My test-case is very unreliable, for
me it rarely crash even w/o patch.

**Comment by dos4boss** [comment]
> So I think there is no bug on dosemu
> side, just some timing problem.
> Could you confirm such observation?

I can confirm that it is working sometimes already on the first try. But for me that is very rarely the case if `-D9+M` is enabled.
It is also happening with the patch. But it can very well be a timing issue, because I am running the whole linux system in a virtual machine.

But another thing I have noticed: After rebasing for the pull request, I can't start it as sudo anymore, which is required for I/O port forwarding (Running dosemu2 as root is highly discouraged). Why is that? Can I force it to do it still?

**Comment by stsp** [comment]
Not sure what happened with sudo.
Usually you need to start `dosemu -s`
instead of sudo.
Please attach that -D9+M log then.

**Comment by dos4boss** [comment]
Sometimes I have the impression that `tail -f ~/.dosemu/boot.log` during the run causes it to fail more often. No idea if that does make any sense.

[boot.log](https://github.com/dosemu2/dosemu2/files/4853291/boot.log)

**Comment by stsp** [comment]
Please clarify is this with patch applied?
I need with the patch.
Will look later.

**Comment by dos4boss** [comment]
Yep, with patch.

**Comment by stsp** [comment]
I applied one more patch.
Could you please re-test the patch?

**Comment by stsp** [comment]
OK, I applied the patch, as it seems to
be faster than to wait for the testing.
Please check if it works.
If so - please confirm.
Otherwise please attach the -D9+Mr log.

**Comment by dos4boss** [comment]
Can't test unfortunately, always failing with 'ERROR: Bootable drive not found, exiting'. I am on the latest devel commit (6b3b6a3165aa17).

**Comment by stsp** [comment]
Custom build?
Please attach your config.log (from configure)
and `ls ~/.dosemu/drive_c`.

**Comment by dos4boss** [comment]
[config.log](https://github.com/dosemu2/dosemu2/files/4906764/config.log)

Not really using drive_c:
```
ls ~/.dosemu/drive_c/
tmp
```
but instead:
`$_hdimage = "hdimage"`

```
ls ~/.dosemu
boot.log  boot.log.1  boot.log.2  boot.log.3  disclaimer  drive_c  hdimage  run
```

**Comment by stsp** [comment]
> $_hdimage = "hdimage"

What is "hdimage"? An image of the
bootable drive? If not - this is a wrong
configuration.

**Comment by dos4boss** [comment]
Yes, it is, and it was working previously with the exact same config. After updating to devel, it stopped working.

**Comment by stsp** [comment]
[c.tar.gz](https://github.com/dosemu2/dosemu2/files/4906918/c.tar.gz)
I can successfully boot from the attached hdimage.
Could you please check?

**Comment by stsp** [comment]
Can anyone else please check if
hdimage boot still works as before?

**Comment by stsp** [comment]
Seems config parsing was broken.
Can you try again?

**Comment by dos4boss** [comment]
I can confirm, that 63df8af is now working with the hdimage again. And I was also not able to crash the app anymore. So your fix seems to work fine. Thank you!

**Comment by stsp** [comment]
Cool, thanks!
I am sure these patches advance us
with the overall stability quite a lot.
