### ISSUE TITLE
Get dosemu version from dosemu command line?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1162]
When I enter "ver" at the dosemu command line, it seems to give me the version number of comcom32. Is there a way to get the version number of dosemu itself?

**Comment by andrewbird** [comment]
~~~
C:\DOSEMU>isemu
Dosemu version 2.0.0 detected
~~~

**Comment by j2969719** [comment]
echo %DOSEMU_VERSION%

**Comment by andrewbird** [comment]
~~~
C:\>echo %DOSEMU_VERSION%
2.0pre8-20200518-1862-gf98f5ce86
~~~
Nice!

**Comment by stsp** [comment]
Yep, that's correct.
isemu was only supposed to check
the dosemu presence. Not sure if it
worth a trouble to make it display the
full version.
