### ISSUE TITLE
dosdebug: g from breakpoint clears it

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1169]
If you do `g` from a break-point, it will
not retrigger again. If the break-point was
itself on 0xcc instruction, then it will
retrigger forever w/o making any progress.
I wonder how we should engage from a
break-point. Perhaps by doing one TF
step first?

**Comment by ecm-pushbx** [comment]
> Perhaps by doing one TF step first?

That is how I handle G and B type breakpoints in my debugger. (A TP step to be exact; trace except proceed past repeated string ops.)

**Comment by stsp** [comment]
Done that, so now you need to do 2 g
commands consequently to leave a
break-point. But at least it works.
