### ISSUE TITLE
Command run from "unix" --> different output than from Linux terminal

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1174]
**EDIT** OK, you can ignore this unless the information in it is useful to anyone. The solution to my problem is to use xclip instead of xsel. It would still be good to have a built-in way to access the Linux clipboard, but the problem I described below doesn't exist with xclip.

------------------------------------------------------------

I don't know what to make of this, or if it's possible to fix it, but here are the details.

I have a WordPerfect macro that uses the "xsel" command (must be installed first) to write the Linux clipboard to a file that can be pasted into a WP document.

Under old dosemu, I could use "unix xsel -o (etc.)" to create this file. Under dosemu 2, when I use this command, the output includes a line "\ No newline at end of selection". This line is not included in the output when I run xsel from the Linux terminal.

This issue is discussed here:

https://unix.stackexchange.com/questions/337171/to-which-stream-does-xsel-print-the-no-newline-warning

I've tried various ways of directing error output with the unix command, but none of them work. I can't find any way to get the contents of the Linux clipboard into a file without that warning message.

Now, I know perfectly well that I'm asking a lot, but if there's any way to make the dosemu2 "unix" command work more like the old dosemu equivalent, I'll be grateful. Of course, what I'm really looking for is a way to get the Linux clipboard written to a file is dosemu2, and if there is some other way to do this, I won't worry about xsel.

EDIT: DOSBox-X now has a DOS device named $CLIP which contains the text contents of the Windows clipboard, and it's possible to write the contents of $CLIP to a file. Is there any chance that dosemu2 might have something that works the same way?

**Comment by stsp** [comment]
> command work more like the old dosemu equivalent, I'll be grateful.

Its not possible as xsel checks isatty()
and only then prints that silly warning.
They forgot that isatty() returns true also
on pty, and of course I am not going to
remove the use of pty just because of
this bug. You can ask them to remove
that silly warning.

> dosemu2 might have something that works the same way?

Isn't unix.com+xclip enough for that?

**Comment by andrewbird** [comment]
Doesn't shift middle mouse button paste into wp?

**Comment by emendelson** [comment]
@stsp - did you see my edit of my post? I found that xclip worked perfectly and added that information at the top of the post.

**Comment by emendelson** [comment]
> Doesn't shift middle mouse button paste into wp?

Yes, but you can't write middle mouse button into a wordperfect macro. And you need to convert from UTF-8 to the DOS codepage used in dosemu if you're pasting non-ASCII characters.

**Comment by stsp** [comment]
> @stsp - did you see my edit of my post? I found that xclip worked perfectly and added
> that information

Yes but you were asking about $CLIP even
after edit.

> UTF-8 to the DOS codepage used in dosemu if you're pasting non-ASCII characters.

Set $_internal_char_set properly or add you
settings to etc/locales.conf and create a PR.

**Comment by emendelson** [comment]
Here's another example of unix command producing different output from the terminal, this time with xclip.

The clipboard contains this text:

`En Algérie, le régime`

When I run `xclip -o >clp.utf` from the Linux terminal I get this output:

`00000000  45 6e 20 41 6c 67 c3 a9  72 69 65 2c 20 6c 65 20  |En Alg..rie, le |`  
`00000010  72 c3 a9 67 69 6d 65                              |r..gime|`

When I run `unix xclip -o >clp.dos` from the dosemu2 command line I get this:

`00000000  45 6e 20 41 6c 67 82 72  69 65 2c 20 6c 65 20 72  |En Alg.rie, le r|`  
`00000010  82 67 69 6d 65                                    |.gime|`

Is dosemu2 using a different encoding from the terminal (which seems to use UTF-8)?

**Comment by stsp** [comment]
It just means that some characters
were swallowed, which is likely a bug.
Does it swallow any particular chars,
or maybe the chars at a particular position?
Or is this random?

**Comment by emendelson** [comment]
First, I haven't changed the default internal_char_set; it's 437.

Next, to answer your question, it seems to swallow accented non-ascii characters. For example, if I copy this string to the clipboard

`aáàäeéèë`

then `xsel -o >file` from the terminal produces this:

`00000000  61 c3 a1 c3 a0 c3 a4 65  c3 a9 c3 a8 c3 ab        |a......e......|`

and `unix xsel o > file` from dosemu2 produces this:

`00000000  61 a0 85 84 65 82 8a 89                           |a...e...|`

**Comment by stsp** [comment]
> First, I haven't changed the default internal_char_set; it's 437.

And that's the problem.
dosemu2 won't know your charset unless
you update locales.conf and submit a PR.

**Comment by stsp** [comment]
Are these chars in a cp437?

**Comment by emendelson** [comment]
> Are these chars in a cp437?

Yes, áàä are 160, 133, and 132, and éèë are 130, 138, and 137.

> dosemu 2 won't know your charset unless
> you update locales.conf and submit a PR.

But my codepage (437) is already in locales.conf, unless I don't understand what's happening (which is very likely):

{
    /* add your mappings below and send a patch */
    "locales": [
        { "lang": "en_US", "codepage": "cp437" },
        { "lang": "en_GB", "codepage": "cp858" },
        { "lang": "ru_RU", "codepage": "cp866" },
    ]
}

**Comment by stsp** [comment]
OK, so a particular chars from cp437
are eaten? Could you put them to other
places (like making first or last) and see
if they are eaten consistently?

**Comment by emendelson** [comment]
The non-ASCII characters are consistently replaced with UTF-8 question marks, no matter where they are in the text.

**Comment by stsp** [comment]
Same happens with mouse paste, right?

**Comment by emendelson** [comment]
I've never been able to get middle-button mouse paste to work with dosemu2, and I've tried three different mice. It works perfectly in old dosemu in my old Lucid Lynx VMware system, but it doesn't paste in my 20.04 setup. The mouse settings in Ubuntu correctly report that I've clicked the middle button, but dosemu2 doesn't respond to a middle click. So I can't test this unless there's some other way to test it that emulates a middle-mouse-click.

**Comment by stsp** [comment]
Use shift.

**Comment by emendelson** [comment]
Using shift-middle-click, paste works correctly with non-ascii characters at the dosemu2 command line, in WPDOS.

But now I see that this isn't a bug - it's simply a different way that dosemu and dosemu2 work, in old dosemu, the `unix xsel` command produced UTF-8 output, but in dosemu2, it produces output in the same codepage as the dosemu2 codepage (and so does xclip). So, if I work with the output of unix xclip inside dosemu, I don't have to worry about codepages. 

I was assuming that dosemu2 would produce output in UTF-8, and that I would have to use iconv to convert it CP437 (or whatever) to import the clipboard into a DOS program. But the new dosemu2 lets me use the xclip output directly.

So it's not a bug - it's a big improvement. Sorry for not seeing this earlier. I didn't realize that this had changed.

**Comment by stsp** [comment]
> EDIT: Can you try it? Simply copy aáàäeéèë and middle-click in dosemu2?

This doesn't work for me as dosemu2
detects my codepage as 866. Which is
why I asked you instead of reconfiguring
my setup.

**Comment by emendelson** [comment]
> > EDIT: Can you try it? Simply copy aáàäeéèë and middle-click in dosemu2?
> 
> This doesn't work for me as dosemu2
> detects my codepage as 866. Which is
> why I asked you instead of reconfiguring
> my setup.

After I wrote my message, I guessed that this was probably what was happening.
