### ISSUE TITLE
"unix xlcip" doesn't exit when run from dosemu2 command line.

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1175]
**Describe the bug**
In the linux terminal, this command copies the contents of filename.txt to the Linux clipboard.

`xclip file.txt`

At the dosemu2 command prompt this command causes dosemu2 to hang:

`unix xclip file.txt`

I expect this may something to do with the encoding of file.txt, but I've tried various encodings with the same result.

**Comment by stsp** [comment]
```
C:\>unix xclip ~/.dosemu/drive_c/autoexec.bat
C:\>
```

No hang.

**Comment by emendelson** [comment]
Something must be different in your system and mine. I've tried this in both Ubuntu Mate and Ubuntu 20.04 LTS, and I get a hang for any file, for example:

c::\>unix xclip ~/.dosemu/disclaimer

or any other file. I'm running the latest versions on both systems (in VMware).

**Comment by stsp** [comment]
Maybe it have something to do
with codepage, try forcing to 866

**Comment by emendelson** [comment]
Same hang with this in .dosemurc:

$_internal_char_set = "cp866"

Is there something else I should do??

**Comment by emendelson** [comment]
Same hang when I have this is .dosemurc:

$_internal_char_set = "cp866"

Is that the right setting to force 866?

**Comment by andrewbird** [comment]
The same thing happens on my Ubuntu Bionic, so I checked what's happening via the `-verbose` switch
~~~
C:\>unix xclip -verbose ~/.dosemu/disclaimer
Connected to X server.
Using UTF8_STRING.
Reading /home/ajb/.dosemu/disclaimer...
Waiting for selection requests, Control-C to quit
  Waiting for selection request number 1
~~~
I selected something with the mouse and then the command returned. The same behaviour occurs without the `-verbose` flag on dosemu.

I repeated the test in the unix terminal and with the `-verbose` flag the behaviour changed to match that of dosemu for some reason, without it the command returns immediately.

**Comment by andrewbird** [comment]
Could be a known problem of xclip
https://github.com/asweigart/pyperclip/issues/116#issuecomment-387825778

**Comment by stsp** [comment]
Thanks for the research!
@emendelson so how about switching
back to xsel and ask them to please
remove the silly warning?

**Comment by emendelson** [comment]
It's still strange that it works on @stsp 's setup. Meanwhile, I'll take your advice and post a request with the xsel author, but I can't hope for much, since he says he can't give too much attention to the project.

Question: since dosemu2 already has ways of sending text to and from the Linux clipboard, is there any hope that there might be an internal equivalent of xclip, something with a syntax like

`getclip filename` (which writes the clipboard to a file)

or 

`sendclip filename` (which reads the file and sends the contents to the clipboard).

I'm pretty sure the answer to my question is either (1) "no" or (2) "write it yourself," but I thought I might ask anyway...

**Comment by stsp** [comment]
How about simply removing the
offending line from xsel sources
and submit the patch to them?
Its a 5 minutes work.
Clipboard device is inherently
unportable. Every back-end like
SDL, X, term will have toprovide a
separate impl of it, and some (like
console) will not provide it at all.
So its not like its a 2minutes work.

**Comment by emendelson** [comment]
OK, I thought I would ask here first, in case I really don't know what I'm doing (and I usually don't know what I'm doing.

In the xsel source, I think this should do the job, but before I submit a PR, could someone let me know if these really look like the lines to remove? In the PR, of course, I would simply remove the lines and not put the comments around them as I do here.

 /* handle output modes */
  if (do_output || force_output) {
    /* Get the current selection */
    old_sel = get_selection_text (selection);
    if (old_sel)
      {
         printf ("%s", old_sel);
/* remove unhelpful error message
         if (!do_append && *old_sel != '\0' && isatty(1) &&
             old_sel[xs_strlen (old_sel) - 1] != '\n')
           {
             fflush (stdout);
             fprintf (stderr, "\n\\ No newline at end of selection\n");
           }
 */
      }
  }

**Comment by stsp** [comment]
No, just remove 1 line,
` fprintf (stderr, "\n\\ No newline at end of selection\n");`
fflush is still needed.
Tell them that isatty() check is not
helping here, because it returns true
also for pty.

**Comment by emendelson** [comment]
Done. Thank you for your help - as you can see, I couldn't have managed this by myself:

https://github.com/kfish/xsel/pull/37

**Comment by emendelson** [comment]
PR accepted. Now, if the fix doesn't get into the repositories by the time I go public with a page about WordPerfect and dosemu2, it's easy to give instructions for building and installing from source. Thanks again for your help.

**Comment by stsp** [comment]
Good to know.
Maybe eventually we can have
the clipboard device.
I guess its quite possible to have
one with mfs, by the use of some
new prefix.
If you want, you can open an RFE,
but it probably won't happen soon.

**Comment by emendelson** [comment]
OK, will do, in the full knowledge that it won't happen quickly, if it happens at all.
