### ISSUE TITLE
winoldap clipboard API

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1179]
It would be good to have DOS device named something like $CLIP that could be used for writing to, and reading from, the Linux clipboard. DOSBox-X has a device with that name, and it makes it easy to send text in both directions using batch files, macros, etc. 

I know there are other ways to get text into and out of the clipboard, but something like this would be easier to use, especially for automated transfers.

And I understand that this is inevitably a low-priority request.

**Comment by jschwartzenberg** [comment]
If this could be accessed from win16 applications as well, it would be very nice for win31 as well.

Another separate idea that would seem nice is to have a text buffer available of all the text that is displayed even when running in X/SDL mode. Then you can access the text that you can normally only copy when running in terminal mode.

**Comment by j2969719** [comment]
unix xsel?

**Comment by stsp** [comment]
No one likely needs $CLIP, but it would
make sense to have the winoldap clipboard
API, as it is used by some programs like NDN,
and perhaps also by WP? Then at least it
has some advantage over `unix xsel`.

> If this could be accessed from win16 applications as well

Very unlikely w/o a windows driver.
Even the winoldap will likely not help
(I don't think it is used by win16 apps,
but maybe there are a few).

> Then you can access the text that you can normally only copy when running in terminal mode.

But who said that copy only works in terminal mode?

**Comment by andrewbird** [comment]
> But who said that copy only works in terminal mode?

Not sure that was the intent, for me running in terminal mode allows access to old text via the terminal's scroll buffer. Of course the Shift mouse functions are available for currently displayed text.

**Comment by stsp** [comment]
I think the scroll buffer only works
in dumb mode, no?

**Comment by andrewbird** [comment]
Yes, that's true but I don't know of another of capturing DOS output that's scrolled off the screen.

**Comment by stsp** [comment]
But I am not sure of who and when
was talking about a scroll-back buffer
in particular.

**Comment by emendelson** [comment]
> But I am not sure of who and when
> was talking about a scroll-back buffer
> in particular.

@jschwartzenberg wrote: "Another separate idea that would seem nice is to have a text buffer available of all the text that is displayed even when running in X/SDL mode. Then you can access the text that you can normally only copy when running in terminal mode."

But it's hard to imagine how this could work with applications like word-processors where you can edit whole paragraphs - it's not like the command line where you can't change text after pressing the Enter key.

**Comment by stsp** [comment]
But how is that quote talks about a
scroll-back buffer? Quite the opposite,
it says "text buffer available of all the text _that is displayed_"
"That is displayed" != "scroll-back"

**Comment by emendelson** [comment]
You're right. Ignore it...

**Comment by jschwartzenberg** [comment]
Ah yeah I remember there's a selection with the mouse too then. Is it possible to obtain all the text without using a mouse? It would be nice to capture the textual content from a script.

**Comment by stsp** [comment]
Yes, use 0xb8000 address to capture from.

**Comment by jschwartzenberg** [comment]
Can that be done from a shell script? Maybe you have an example?

**Comment by stsp** [comment]
Of course you can: with dosdebug.

**Comment by andrewbird** [comment]
So that's [int2f/17xx](http://www.ctyme.com/intr/rb-4636.htm)?

**Comment by stsp** [comment]
Indeed.
Do you want? :)

**Comment by andrewbird** [comment]
Probably a lot quicker if someone else chooses to do it as I'm very busy with no Dosemu stuff at the moment.

**Comment by jschwartzenberg** [comment]
I replaced the OCR parts in my automatic installation script with reading out the text with `dosdebug` now. This makes the whole process a lot more reliable and speeds things up too:
https://github.com/jschwartzenberg/dos-download-scripts/blob/master/include/rc.sh#L46

**Comment by stsp** [comment]
But this will not help with win31 and alike?

**Comment by jschwartzenberg** [comment]
Indeed this only does the text mode portions, but there are still quite a lot of those for win31. Maybe win31 stores the displayed text somewhere in memory too so that it could be read out. That would be neat.

**Comment by andrewbird** [comment]
I did a first try of implementing this here https://github.com/andrewbird/dosemu2/tree/clip-01 with just the SDL plugin mods mostly complete. I do have a deviation from Dosemu usual in that I use iconv for codepage <-> utf-8 conversion as I was struggling to get the usual dosemu codepage conversions working properly. Currently it is hardcoded to use cp858 as I didn't find out yet how to get the string of the current codepage. It seems to work okay in both directions with https://www.horstmuc.de/div.htm#wclip with and without codepage translation.
Is the current method of extending the video plugins okay?
I figured I could add an X plugin too, but does clipboard for any others make sense?
Adding support for 'CLIP$' device looks possible, with most of the code in C rather than asm.

**Comment by stsp** [comment]
> I did a first try of implementing this

Thanks for taking that up!

> with just the SDL plugin mods mostly complete.

And who needs anything else! :)

> the usual dosemu codepage conversions working properly.

But I thought you already used that
in many places? I think we need to
switch to iconv eventually, but I am
not sure doing so for one particular
place makes sense.

> Currently it is hardcoded to use cp858 as I didn't find out yet how to get the string of the current codepage.

I think you can use `trconfig.dos_charset`.

> Is the current method of extending the video plugins okay?

I'd rather say, please add a separate
subsystem ops. Then you won't be limited
to just 1 member function, and you won't
need to clutter all video plugins with NULL.

> I figured I could add an X plugin too, but does clipboard for any others make sense?

Just if you have a lot of time. :)
IMHO having SDL is more than enough,
at least as a first step.

> Adding support for 'CLIP$' device looks possible, with most of the code in C rather than asm.

Would be cool, just make sure name
matches the one of dosbos (ppl here
were calling it `$CLIP` not `CLIP$`.

**Comment by andrewbird** [comment]
I don't know about dosbox itself, but dosbox-X seems to have clip$ as the name
https://dosbox-x.com/wiki/Guide%3AClipboard-support-in-DOSBox%E2%80%90X

> I'd rather say, please add a separate
subsystem ops. 

Can you point to an example within Dosemu2 that I can base my code on?

> But I thought you already used that
in many places?

I tried it here but I kept getting trailing crap, I wonder if it handles the CR and LF properly?

> I think you can use trconfig.dos_charset.

Thanks, I'll try it.

**Comment by stsp** [comment]
> Can you point to an example within Dosemu2 that I can base my code on?

What do you mean?
We have a separate ops structures
for everything, eg `struct video_system`,
`struct render_system`, `struct text_system`
are separate. It would be a big mess to
put these to the single `struct video_system`.

> I wonder if it handles the CR and LF properly?

Yes, it should.
Maybe some '\0' was missing?
Please show your problem.

**Comment by stsp** [comment]
This also needs to be disabled by
default. But you can add an error
saying "app is trying to access clipboar
which is disabled. Change this and
that option to enable."

**Comment by andrewbird** [comment]
> What do you mean?
We have a separate ops structures
for everything, eg struct video_system,
struct render_system, struct text_system
are separate.

Exactly, I just needed the name of one to study, thanks!

> Maybe some '\0' was missing?
Please show your problem.

I still have some version of the write code in an old branch, but I'll work on rearranging into a subsystem first.

> This also needs to be disabled by
default.

Okay, understood. I guess you want it disabled in case anybody wants to install Windows and provide a real Windows clipboard?

**Comment by stsp** [comment]
No, its just that there are too many
ways to annoy the user by interfering
with his clip-board, or even attack
scenarios.

**Comment by stsp** [comment]
Say, what if the app will clear your
clip-board every second?
Whole desktop will break.

**Comment by stsp** [comment]
Winoldap part merged.

**Comment by stsp** [comment]
So do we need `CLIP$` or
winoldap is enough?

**Comment by stsp** [comment]
I have documented the clipboard usage:
https://github.com/dosemu2/dosemu2/wiki/clipboard-usage
So I think this can now be closed.

**Comment by stsp** [comment]
@ecm-pushbx reminds this doesn't yet
work with `-t`.

**Comment by ecm-pushbx** [comment]
Discussion in https://github.com/dosemu2/dosemu2/pull/2088#issuecomment-1712755996
