### ISSUE TITLE
Prevent window-resize by dragging?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1184]
Is there a setting that will prevent text-mode windows from being resized by dragging? In bitmapped text modes, the text looks fairly good at the specified size. It tends to look really bad if the window is resized. Is there a setting that prevents window-resizing? If so, I can't find it. I can see a setting that preserves aspect ratio, but that's not the same thing.

In my patched version of DOSBox-X (for use with WP) I change an SDL setting so that the window can't be resized. If there isn't anything like this in dosemu2, could it be listed as feature request (and I know that it would have to wait a long time)?

**Comment by stsp** [comment]
I don't see the need in such option.
If you don't want to resize, then don't resize.

**Comment by emendelson** [comment]
OK - I was thinking about the user who resizes by accident and then has a hard time getting back the original size. But it's not worth worrying about.

**Comment by stsp** [comment]
Maybe some hotkey can be used to resize it back.

**Comment by emendelson** [comment]
That would be very good to have.
