### ISSUE TITLE
Intel 8254 PIT Read-back command bug

### ISSUE THREAD

**Issue by dos4boss** [dosemu2/dosemu2#1186]
During #1161, I have discovered a problem with the Intel 8254 PIT implementation. As you can see in the **8253/8254 control word** table of the corresponding [wiki page](https://en.wikipedia.org/wiki/Intel_8253), at least one of the three read-backs (that are not 'Do nothing') is not handled correctly. There is no distinction between the status bit cases if the count bit is being zero. But it should give back status and then count for one case and only count for the other. Currently, it is only giving back latched count values I thin.

https://github.com/dosemu2/dosemu2/blob/0ea41e373505e26656a6f952dc2c66e2fbbc78e8/src/base/dev/misc/timers.c#L496-L506

Also, in the else branch, it is not correctly setting up for a status word latch. With looking to 
https://github.com/dosemu2/dosemu2/blob/0ea41e373505e26656a6f952dc2c66e2fbbc78e8/src/base/dev/misc/timers.c#L224-L240
I guess the else branch has to use the value of 0x80 instead of 0x40.

Cause all of it is a little messy (0x40, 0x80 should have been preprocessor macros describing what they are doing), I am not 100% sure what was the original intention.

**Comment by stsp** [comment]
> I guess the else branch has to use the value of 0x80 instead of 0x40.

See this:
https://github.com/dosemu2/dosemu2/blob/0ea41e373505e26656a6f952dc2c66e2fbbc78e8/src/base/dev/misc/timers.c#L316

0x40 seems to be flipped to 0x80,
so the next time status is latched.
So I _hope_ that place is correct,
but you are right: that entire code
is so obfuscated, that it is better to
rewrite it or port from qemu.

Anyway, could you please present
the exact sequence of operations
that confuse the program? Maybe
we'll be able to deduce something
from that.

**Comment by dos4boss** [comment]
It was basically given in https://github.com/dosemu2/dosemu2/issues/1161#issuecomment-636547504. The last line would have been `PORT: pit_inp(0x42) = 0xda` without my hacking, because it is giving latch counter values instead of the status.

**Comment by stsp** [comment]
So what dosemu2 does, is:
```
PORT: outp(0x43, 0xe8)
PORT: pit_inp(0x42) = 0xda
```
right?
Now, according to the table in wiki,
0xe8 means
`Next read of selected counters will read back latched status`
and
`Read-back command applies to counter 2`.
So why do you think it applies to status?
What am I missing?

**Comment by stsp** [comment]
Maybe it wrote 0xb4 there, then
didn't issue the "latch" command,
and as such, expects to get the
same value back?

**Comment by dos4boss** [comment]
> Now, according to the table in wiki,
> 0xe8 means
> `Next read of selected counters will read back latched status`
> and
> `Read-back command applies to counter 2`.

Yes, that is correct up to here.

> So why do you think it applies to status?
> What am I missing?

I don't get your question here.

> Maybe it wrote 0xb4 there, then
> didn't issue the "latch" command,
> and as such, expects to get the
> same value back?

This 0xb4 was forced by chaging the source of dosemu. Originally, it was giving me counter values only.

I think the implementation is ok up to this point:
https://github.com/dosemu2/dosemu2/blob/0ea41e373505e26656a6f952dc2c66e2fbbc78e8/src/base/dev/misc/timers.c#L502-L505
It is correctly saying in the comment, that now the status register should be returned on readback instead of any counter value. The question now is, if the value to be returned should already be written into `p->read_latch` during this call to `pit_latch` from the shown `pit_control_outp` function or if it should be done during a second `pit_latch` call from `pit_inp`. Your mentioned line https://github.com/dosemu2/dosemu2/blob/0ea41e373505e26656a6f952dc2c66e2fbbc78e8/src/base/dev/misc/timers.c#L315-L316 might indicate, that the latter is true. 
The problem then might be located in https://github.com/dosemu2/dosemu2/blob/0ea41e373505e26656a6f952dc2c66e2fbbc78e8/src/base/dev/misc/timers.c#L339-L340 where no second `pit_latch` call happens because `p->read_latch` is not -1.

**Comment by stsp** [comment]
> I don't get your question here.

Yes, that was the wrong kind of question.
Why do you think that this is "read status
then count" command?

> might indicate, that the latter is true.

Only for "read status then count" command,
which is not the case here. I pointed to that
place before analysing your I/O example,
because you said "read status then count"
is not properly supported. I think it is, but
something else isn't.

Maybe something like this will help?
```
diff --git a/src/base/dev/misc/timers.c b/src/base/dev/misc/timers.c
index c5e496ff7..30c6d3386 100644
--- a/src/base/dev/misc/timers.c
+++ b/src/base/dev/misc/timers.c
@@ -500,9 +500,10 @@ void pit_control_outp(ioport_t port, Bit8u val)
        if (val & 0x08) pit_latch(2);
       }
       else if ((val & 0x10) == 0) {   /* latch status words? */
-       if (val & 0x02) { pit[0].mode |= 0x40; pit_latch(0); }
-       if (val & 0x04) { pit[1].mode |= 0x40; pit_latch(1); }
-       if (val & 0x08) { pit[2].mode |= 0x40; pit_latch(2); }
+       int or_mask = ((val & 0x20) == 0 ? 0x40 : 0x80);
+       if (val & 0x02) { pit[0].mode |= or_mask; pit_latch(0); }
+       if (val & 0x04) { pit[1].mode |= or_mask; pit_latch(1); }
+       if (val & 0x08) { pit[2].mode |= or_mask; pit_latch(2); }
       }
       break;
   }
```

**Comment by stsp** [comment]
I applied the fix and made sure the cmud
actually works!
So many thanks for reversing that one!
