### ISSUE TITLE
Sound support in WordPerfect 6.x

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1189]
In ancient Linux versions and the old DOSEMU, WordPerfect 6.x was able to play sound clips. I haven't been able to make this work in the current version. My old wpdos.org/linux.html page says to try the setting $_sound = (2) instead of the default setting, and I've tried that also, but WPDOS locks up with that setting also.

Here is a full WPDOS 6.2 installer (please let me know when you've downloaded it), so that you can install the sound drivers. In installing, I chose the SoundBlaster driver, and then did this in WPDOS 6.2: http://wpdos.org/WP62INST.7z

Ctrl-F7 (or Tools, Sound Clip), then Setup... Shift+F1.
In the Sound Setup menu, I chose Type ... Sound Blaster, and in the Hardware Setup, IRQ5 and 220.

In the Sound Clips in Document menu I chose, Add Clip... then selected C:\COREL\WP62\GRAPHICS\FANFARE1.MID, then pressed P for Play/Pause, and WPDOS locked up.

I don't think this is worth a great deal of effort, but it may point to other issues, so I thought it was at least worth mentioning it.

**Comment by stsp** [comment]
Please provide -D9+S log.

**Comment by emendelson** [comment]
Here's the log:
[boot.log](https://github.com/dosemu2/dosemu2/files/4725934/boot.log)
And the terminal showed this error:
`INFO: booting with comcom32, this is very experimental'  
`ERROR: PCM: "sdl" too large delay, start=42200829.036281 min=42200840.000000 d=10.963719`

**Comment by stsp** [comment]
Please provide the same log from dosemu1.

**Comment by emendelson** [comment]
Will do later tonight or tomorrow.

**Comment by emendelson** [comment]
Well, my dosemu1 VM system is useless for this - I seem to have removed or never installed sound support, and there's no way to get it installed in Ubuntu 10.10. For what it's worth, here's what I wrote ten years ago about sound in dosemu1:

--------------------------

DOSEMU (like DOSbox) is one of the few modern environments that makes it possible to use the sound-clip feature in WPDOS 6.x. DOSEMU emulates an original SoundBlaster card, and you may be able to use the SoundBlaster or SoundBlaster Pro support in WPDOS 6.x With older versions of Ubuntu Linux (through 7.10, perhaps), WPDOS sound works perfectly without any special effort. With more recent versions, sound may cause WPDOS either to stall briefly or lock up. Depending on your distribution, sound may not work at all unless you change a setting in .dosemurc so that the line

 # $_sound = (on)

reads instead (note the removal of the comment mark at the start of the line):

 $_sound = (2)

In WPDOS, when setting up hardware, make sure to match the IRQ setting to the setting shown in .dosemurc.

Also, if sound does not work correctly, you may need to replace the ALSA sound system in Linux with the older OSS system. Instructions for making this change in recent versions of Ubuntu Linux may be found on this Ubuntu support page. Do not attempt this unless you are prepared to restore your Linux system from a backup in case of problems!

--------------------

The log seems to say that there's no support in the system for sound, so this won't be useful at all.

[boot1.log](https://github.com/dosemu2/dosemu2/files/4726738/boot1.log)

I'm not sure I can do any more with this. If you have a more recent dosemu1 VMware system somewhere that I can download, I'd be glad to try it.

**Comment by emendelson** [comment]
Wait - I downloaded a Ubuntu 16.04 VM image and installed dosemu1 in it, changed $sound to (2), and WPDOS 6 successfully played the sound clip.

The trouble is that I can't send a log, because when I start dosemu1 with -D9+S, the sound clip won't play! The terminal reports:

`ERROR: PCM: "Sound Output: SDL device" out of sync`

Is there a different logging option that I can use that won't produce that error?

**Comment by emendelson** [comment]
Anyway, for what it's worth, here's a log created with dosemu1 when I did NOT try to play the sound file:
[boot-noplay.log](https://github.com/dosemu2/dosemu2/files/4731621/boot-noplay.log)

I realized also that a log might be useful for the attempt I made to play the sound file when, the ERROR: PCM: appeared, and here it is. But I think I ran into a limit in the size of the log, because there's nothing in it but errors about AdLib timers...

[boot.log](https://github.com/dosemu2/dosemu2/files/4731628/boot.log)

**Comment by emendelson** [comment]
Well, this gets more interesting. I installed dosemu2 OVER dosemu1 in Ubuntu 16.04, and successfully played the sound clip in WPDOS. Here is the log:

[boot-dosemu2.log](https://github.com/dosemu2/dosemu2/files/4731701/boot-dosemu2.log)

So, sound support works in Ubuntu 16.04, but not in 20.04 - but it may be relevant that I installed dosemu2 over dosemu1.

**Comment by emendelson** [comment]
Continuing to experiment: I installed dosemu2 in a clean Ubuntu 16.04 system (where dosemu1 had never been installed), and WP62 locked up when I tried to play a sound clip. So it isn't enough to install dosemu2 in 16.04. 

So I installed dosemu1 in a clean 16.04 system, set cpu emulation to vm86sim (required for dosemu1 to run WP62), sound to (2), and successfully played the sound clip. However, once again, it would NOT play if I ran dosemu -D9+S.

**Comment by stsp** [comment]
The hang happens with either freedos
or fdpp, but not with ms/pc dos.
So you can use those as a work-around.
For the best sound quality you need to
select Sound Blaster Pro Stereo and
enable External MIDI synthesizer in the
setup dialog. You won't regret that.

**Comment by emendelson** [comment]
OK, thank you. I don't really want to play sound through WPDOS, but thought it was worth experimenting in case it helped someone make changes in the dosemu2 code. - I already chose External MIDI synthesizer in the setup dialog, but hadn't tried Sound Blaster Pro Stereo.

**Comment by stsp** [comment]
> External MIDI synthesizer in the setup dialog, but hadn't tried Sound Blaster Pro Stereo.

In this case you don't need to do
anything else as the external synth
won't change. I just thought you
play through adlib midi.

**Comment by stsp** [comment]
No, this have nothing to do with
any DOS. Spoke too soon.
This have to do with delays.
WP uses busy loops to create
the delay, and during that busy
loops it expects the certain amount
of timer interrupts to come.
Also it makes sure the effect
is reliable by running the test
several times. And unfortunately
it tests infinitely, which looks like
the lock-up.
The only work-around on dosemu
side is to switch to CPU emulator
in SIM mode. Then it is slow enough
to get the needed amount of
interrupts.
I made a binary patch for vmp.com
that avoids this problem:
```
Comparing C:\WP62\vmp.old and C:\WP62\VMP.COM
00002C4B:     72        90 
00002C4C:     0D       90
00002C5B:     01        00
```

**Comment by jschwartzenberg** [comment]
Maybe you could put that binary patch somewhere? You developed quite a few and some of them are in the DOSEMU2 docs in the repo.

Possibly it would be good to provide such patching plus instructions/tricks to automate applying them in another repo as they could help a lot of people beyond DOSEMU2 users.

**Comment by stsp** [comment]
Added to docs.
As for automating - you are the boss of automatization! :)
So waiting for a script.

**Comment by emendelson** [comment]
Since this really isn't a dosemu2 problem, I'm doubly grateful to you for working on it.

Here, if anyone is interested, are some results:

With the patched version of VMP.COM, I can set up WPDOS Sound to use the Sound Blaster Pro, Mono, driver, set to IRQ 5 and Base Address 220. This works correctly. (The Sound Blaster driver and the Sound Blaster Pro, Stereo drivers also work; Sound Blaster ASP produces a hardware error.)

For this to work I have to UNcheck "External Synthesis (via MIDI port)". If that option is turned on, then no sound gets produced, though there is no lockup.

In all cases, the terminal produces the error:

`ERROR: PCM: "sdl" too large delay, start=375539833.142871 min=375540141.000000 d=307.857129`

But the sound plays anyway. This is excellent. Thank you!!

**Comment by stsp** [comment]
That's not the proper sound.
You need Sound Blaster Pro Stereo
with external synth, and believe me,
you won't regret hearing it.
I updated the packaging info.

**Comment by stsp** [comment]
`DOSEMU emulates an original Sound Blaster card`
No, it emulated SB16, but not SB16ASP.
Surprisingly WP62 doesn't have the driver
for plain SB16.

**Comment by emendelson** [comment]
OK, I've revised my instructions:

http://www.columbia.edu/~em36/wpdos/linux.html#sound

On my setup, I don't hear any sound with external synth (though that option works with 16.04 running dosemu1). Obviously, since you recommend it, something's odd about my system (maybe caused by VMware). 

WordPerfect seems to use same driver for Sound Blaster and Sound Blaster Pro. I get sound when I choose the plain Sound Blaster driver, but I don't mention this in the revised page.

**Comment by stsp** [comment]
> Obviously, since you recommend it

I updated the packaging info.
Now not only me recommends it, but
the package itself. So it should work.

**Comment by emendelson** [comment]
All I can do is report that on two separate VMware setups (one standard Ubuntu 20.04, the other Ubuntu MATE 20.04) I hear sound when playing with External Synth NOT checked, and don't hear sound with External Synth checked. For what it's worth, here are two logs, one with External Synth, the other without:

[bootlogs.zip](https://github.com/dosemu2/dosemu2/files/4737532/bootlogs.zip)

**Comment by emendelson** [comment]
> 
> 
> > Obviously, since you recommend it
> 
> I updated the packaging info.
> Now not only me recommends it, but
> the package itself. So it should work.

Beginner's question: how does a user see that recommendation?
