### ISSUE TITLE
Lotus 1-2-3 Installer crashes dosemu

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1190]
**Describe the bug**

I've found that the Lotus 1-2-3 installer crashes dosemu in `-term` mode.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run `dosemu -term`
2. Run the attached `install.exe`, it is an original installation program from Lotus 1-2-3.
3. The installer will give some error message about missing files.
4. Press any key, and dosemu will crash.

Reproduces on current git for me.

The program needs the three files `123I.DLD`, `INSTALL.EXE`, and `INSTEXT.RI` to get far enough to trigger the crash.

[123-dosemu-crash.zip](https://github.com/dosemu2/dosemu2/files/4732936/123-dosemu-crash.zip)

```
H:\123>dir
 Volume in drive H is HOME TAVISO
 Directory of H:\123

.                    <DIR>  06-04-20  2:48p
..                   <DIR>  06-04-20  2:55p
123I     DLD        32,810  07-29-94  1:23a
INSTALL  EXE       179,707  07-29-94  1:23a
INSTEXT  RI         74,373  07-29-94  1:23a
         3 file(s)        286,890 bytes
         2 dir(s)    156,520 Mega bytes free
```

**Attach the log**

The log usually works, but I can't seem to get gdb to work in this state.

**Additional info**

I used the binary freedos 1.0 tarball from dosemu1, unmodified.

**Comment by stsp** [comment]
Do you mean it works properly w/o -term?
In this case try `$_umb_a0 = (off)`

**Comment by taviso** [comment]
Thanks, I tried it, it still crashes.

I did try it with `-dumb` just to check - and then it doesn't seem to crash. I don't have an X11 build, I usually only use `-term` 😄

**Comment by stsp** [comment]
But with -dumb you won't even see its screen.
Please attach the -D9+c log.

**Comment by taviso** [comment]
Right, the installer has a fallback mode, but I guess it acts differently.

[boot.log](https://github.com/dosemu2/dosemu2/files/4733139/boot.log)

**Comment by stsp** [comment]
I asked you to set `$_umb_a0 = (off)`.
Log doesn't confirm you did.
Please do what I say.

**Comment by taviso** [comment]
I did, but it still crashed, so I put it back the way it was. The log is identical.

**Comment by stsp** [comment]
If it is identical, then you didn't do that.
When you do, its not identical.

**Comment by taviso** [comment]
Not literally identical, I meant there is no additional useful debugging data at the time of the crash.

I added it back for you.

[boot.log.txt](https://github.com/dosemu2/dosemu2/files/4733191/boot.log.txt)

**Comment by stsp** [comment]
But where is the crash?
The log just ends w/o any crash
messages.
Are the crash messages on terminal?
Also you have altered confing.
You have cpu_emu enabled in
config, why?
But even with that settings it doesn't
crash for me.

**Comment by taviso** [comment]
Right, the log just ends without any crash, I don't know why. All I get on the terminal is:

```
Segmentation fault (core dumped)
Terminated with signal 11
```

Regarding `cpu_emu`, I was trying all the options to see if I could get it to work, it still crashes with all of the cpu settings to default.

**Comment by stsp** [comment]
Is there anything in dmesg?
Try `dmesg | tail`

**Comment by amluto** [comment]
This is probably hitting the signal delivery failure path in the kernel -- if the kernel tries and fails to deliver SIGSEGV, it will disable your signal handler and try again.

Your best bet is probably to look at the core dump.

**Comment by stsp** [comment]
Such things are noted in dmesg IIRC, right?

**Comment by amluto** [comment]
> Such things are noted in dmesg IIRC, right?

Not as such.  That is probably worth changing some day.

**Comment by stsp** [comment]
Then perhaps some user-space framework
is putting this in my dmesg:
`[565875.227331] systemd-userwor[2184082]: segfault at 370f8 ip 00000000000370f8 sp 00007ffee88f6388 error 14`
So I thought such things are noted.

**Comment by amluto** [comment]
That comes from the kernel.  But there's nothing that says "signal delivery failed -- sending SIGSEGV instead" or "SIGSEGV delivery failed -- killing the task".

**Comment by stsp** [comment]
I suppose the logic is: if signal is handled -
no msg. If its not handled - msg. For dosemu
this is more or less equal to `SIGSEGV delivery failed -- killing the task`
as it always sets the handler.
Of course it would be great if the more
detailed info is printed, and especially
the reason why the delivery could fail.

Anyway, @taviso in this case the best
would be to find the core file and do
```
gdb dosemu.bin core.<pid>
(gdb) bt
```
... as attaching core here will likely
not help unless also all binaries are
attached.

**Comment by stsp** [comment]
I applied the patch that could
potentially fix/affect this.

**Comment by taviso** [comment]
Thanks, I just got around to trying it and it did work - it installs and works. Thanks!

**Comment by stsp** [comment]
Found your blog here:
https://blog.cmpxchg8b.com/2020/09/finding-console-word-processor.html
Thanks for sharing that.
Would be good if you adjust
the security chapter.
dosemu2 is a sandboxing
emulator, so it tries to secure
your data and will not allow
the DOS program to access
it. At least not willingly. Of course
its full of bugs so someone can
"break" it, but many other emulators
do not even try to keep things secure.
We do.

**Comment by taviso** [comment]
Oh - It's definitely not a criticism of dosemu! I understand what you mean, you support limiting things like redirection and `unix.com` to restrict what code can do inside dosemu - but that would still be enough for a malicious macro to access or delete all your documents for example.

That's what I meant by `don't use unsupported software` - I meant WordPerfect, not dosemu (which is actively maintained, and I'm very grateful for).

I actually got interested in trying out more old DOS productivity software, I wrote another here: https://lock.cmpxchg8b.com/lotusagenda.html

**Comment by stsp** [comment]
Yes, cool article, thanks. :)

> by don't use unsupported software I meant WordPerfect

Yes, I know.
But the whole point of dosemu2 is to
lower the risk of running old, unsupported
software.

> but that would still be enough for a malicious macro to access or delete all your documents for example.

Yes, all WP documents, so to say. :)
But it won't steal your credit card number
or a private ssh key, it won't delete your
`~/*` files or steal passwords from firefox.
So dosemu2 security only applies to the
non-dos data (which is, presumably, much
more valuable than the dos-related data).
You may say its obvious, but its not, because
other emulators (including wine AFAIK)
do not try to secure even that. Any untrusted
code under wine can do everything wine
could do itself, AFAIK, and without a need
to "break" wine - no, its just all "allowed".
Which is why it would be good to mention
that under dosemu2 at least your non-dos
data is protected (and dos data is very
unlikely to be too valuable these days).
Security is a big marketing buzz-word
today, so mentioning it always helps. :)
And besides, you already created the
security chapter! So why not to fill it in
with more info. :)

**Comment by andrewbird** [comment]
@taviso an interesting article about Lotus Agenda. One thing though, you mention the software was $800 value when on sale but wouldn't accounting for inflation make it more in today's money?

**Comment by stsp** [comment]
Unless this was just added, the text
already says:
`Apparently this was an $800 software package (That’s $395 adjusted for inflation from 1989)`

**Comment by andrewbird** [comment]
I read that as $800 dollars in 1989, $395 today.

**Comment by andrewbird** [comment]
But I also see how it can be read otherwise!

**Comment by taviso** [comment]
Okay, I added the sentence "DOSEMU2 does make an effort to safely contain safely software, and can be configured to limit access to the host." :-)

@andrewbird: Thanks, I can see I worded that confusingly! I'll edit that when I get a chance.
