### ISSUE TITLE
EMS function 67.4D does not return entries for empty (zero-page) handles, but does count them

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1192]
**Describe the bug**

While working on my debugger I noticed that its status display seemed to have an error when an EMS handle was (accidentally) re-allocated to have zero pages allocated to it. I eventually figured out that the error is in dosemu2 and extracted a test program from the debugger's sources.

The error is that dosemu appears to skip any handles that have zero pages allocated to them in the EMS function 4Dh (on interrupt 67h), "Get pages for all handles". Although they are not entered into the table, dosemu still returns the count in bx "number of active EMM handles" in a way that does count these handles. This results in the caller using uninitialised memory at the end of its table. (Function 4Bh also returns the number of handles in a way that counts these handles. In the example that number is 6.)

A handle may be allocated with zero pages either by using the function 5A00h, or by allocating with function 43h to a non-zero amount of pages then using function 51h to re-allocate to zero pages. The debugger sources state that allocating zero handles with function 43h to begin with is invalid. This is not of interest for this bug report.

Forcing the test to use the non-table enumeration of handles using function 4Ch on each possible handle results in the correct results. The handles are specified as present and having zero pages allocated to them.

**To Reproduce**

Run the test program. Output:

```
$ hg id
937e285cde09 tip
$ nasm -f bin -o emstest.com -l emstest.lst emstest.asm -I ../lmacros/ && dosemu -dumb -K "$PWD" -E "emstest.com" -D+9E
dosemu2 2.0pre8-20200521-1872-g51906bfc3
Configured: 2020-05-26 09:01:38 +0200
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org

FreeDOS kernel - SVN (build 2042 OEM:0xfd) [compiled Sep 22 2017]
Kernel compatibility 7.10 - BORLANDC - FAT32 support

(C) Copyright 1995-2012 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
EMUFS host file and print access available                                     
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.8 installed.
dosemu CDROM driver installed (V0.2)
Kernel: allocated 30 Diskbuffers = 15960 Bytes in HMA
emufs: redirector enabled
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre8-20200521-1872-g51906bfc3
About to Execute : emstest.com
About to Execute : emstest.com
Handle 0000 has 0018 pages allocated
Handle 0001 has 0004 pages allocated
Handle 0002 has 0002 pages allocated
Handle 0004 has 0008 pages allocated
Handle 3222 has B46F pages allocated
Handle 9911 has 5A37 pages allocated

Handle 0000 has 0018 pages allocated
Handle 0001 has 0004 pages allocated
Handle 0002 has 0002 pages allocated
Handle 0003 has 0000 pages allocated
Handle 0004 has 0008 pages allocated
Handle 0005 has 0000 pages allocated

$ 
```

**Attach program/game binaries or provide an URL**

https://hg.ulukai.org/ecm/emstest/file/937e285cde09/emstest.asm (needs NASM and lmacros collection to assemble)

**Attach the log**

[boot.log](https://github.com/dosemu2/dosemu2/files/4740464/boot.log)

**Additional info**

Running the following shell and kernel:

```
C:\>ver /r
 
FreeCom version 0.84-pre7 - GNUC - XMS_Swap [Dec 29 2019 15:36:33]
DOS version 7.10
FreeDOS kernel - SVN (build 2042 OEM:0xfd) [compiled Sep 22 2017]
C:\>
```

**Comment by stsp** [comment]
You seem to understand the problem
well, so why not to provide the fix?
