### ISSUE TITLE
Dosdebug mhp_bpclr() function

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1194]
I'm trying to understand the `mhp_bpclr()` function and when it should be used. So I can see that it scans the breakpoint table and looks for valid breakpoints.
- there's a global nothing to do check
- if a valid breakpoint is found that has a is_dpmi flag that doesn't match the current dpmi mode that breakpoint is marked invalid without replacing its 0xcc opcode in the program with the saved value. Is that correct?
- why should dosdebug care if a breakpoint is to be triggered in DPMI?
- assuming the existing program code has 0xcc at the breakpoint address, its value is overwritten with the saved original opcode. Since this is done for each breakpoint, once this `mhp_bpclr()` is called aren't all breakpoints effectively disabled, even though they are still in the breakpoint table?

**Comment by stsp** [comment]
> Is that correct?

No, but your description isn't, either.
It checks not current mode, but rather
whether DPMI is active at all, or client
exited. If it did, it resets all its break-points.
But I don't think it makes any sense
these days, as comcom32 is always
running. I think it can follow the realmode
logic: if breakpoint is overwritten, then
disable.

> why should dosdebug care if a breakpoint is to be triggered in DPMI?

These days not a big reason indeed.

> called aren't all breakpoints effectively disabled, even though they are still in the breakpoint table?

Exactly. This is what this fn does.
mhp_bpset() can reverse its effect.

**Comment by andrewbird** [comment]
So `mhp_bpset()` and `mhp_bpclr()` are really `mhp_bp_enable()` and `mhp_bp_disable()` and only clear as a by product of inconsistency?

**Comment by stsp** [comment]
Something like that, yes.

**Comment by andrewbird** [comment]
So now that I understand that `mhp_bpclr()` is disabling all the current breakpoints, why is that necessary in the process to delete just one? i.e.
https://github.com/dosemu2/dosemu2/blob/858244eee737b3a408e8e7d8766a3cb826540dda/src/plugin/debugger/mhpdbgc.c#L1947-L1961

**Comment by stsp** [comment]
"bad code" example.
It relies on the fact that mhp_bpset()
will undo things, but the cleared one
will remain. Very fragile logic, if still
true at all.

**Comment by andrewbird** [comment]
So any reason why the delete operation shouldn't write the saved opcode back to the brkaddr itself and leave any other valid breakpoints enabled?

**Comment by stsp** [comment]
I don't think there is any reason against
doing what you say. Of course I would
expect other pitfalls that you'll have to
fix in a process.

**Comment by andrewbird** [comment]
Another thought, is this whole bpset/bpclr pairing purely so that disassembly shows the proper code not the 0xCC, as I can't think why it's necessary to do the enable/disable cycling?

**Comment by stsp** [comment]
I recently used that to engage from the
active break-point, too. You can't do that
w/o temporary disabling.
