### ISSUE TITLE
Beginner question: use LREDIR on dual-boot system

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1195]
Under dosemu1, these instructions made it possible to use LREDIR to access a drive on a Windows partition in a dual-boot system. I've now created a real-hardware Ubuntu MATE system on my machine, and would like to find out how to access a folder on one of my NTFS partitions as a drive letter in dosemu2, but I hesitate to start editing /usr/fstab if that's no longer the proper method.

If I mount an NTFS partition in the Ubuntu file manager, then this command works in DOSEMU:

LREDIR X: \\LINUX\FS\media\edward\D-Drive

But of course only if I've mounted that drive first in Linux. Can anyone tell me the current method of accessing that drive (or directory) automatically? I'll add the details to the wiki as soon as I know them.

**Comment by stsp** [comment]
I dont think somethig else but a mounting
is possible. dosemu2 does not support
gvfs or alike to do it on its own.

**Comment by emendelson** [comment]
So it should be possible to write a bash script that mounts an NTFS partition, runs dosemu2, and then unmounts the partition. When I figure this out, I'll post instructions in the wiki.

**Comment by jschwartzenberg** [comment]
You could do the mounting from a any batch file using `unix` and `gvfs-mount` it seems.

**Comment by emendelson** [comment]
> You could do the mounting from a any batch file using `unix` and `gvfs-mount` it seems.

Of course - I should have realized that, but I wasn't thinking. Thank you.

**Comment by emendelson** [comment]
Thank you for the batch-file suggestion. I've now spelled out the relevant steps in the wiki.

**Comment by stsp** [comment]
It is actually even better to create
wp.bat for that, than to pollute userhook.

**Comment by stsp** [comment]
Wrong thread, sorry.

**Comment by emendelson** [comment]
Have revised.

**Comment by emendelson** [comment]
Thanks to @andrewbird - here is another solution, using autofs

`sudo apt install autofs`
`sudo gedit /etc/auto.master` [or nano or whatever your editor is]  

Add to the end of auto.master:

`/misc    /etc/auto.misc`  (but "misc" can be any string)

Then edit /etc/auto.misc and add a line like this at the end, where `/dev/sda4` is your NTFS Windows partition (use the real address of course):

`win         -fstype=ntfs-3g     :/dev/sda4`  

You will now have created a mount point `/misc/win` that corresponds to your Windows partition.

Now start up dosemu2. Enter commands like these; the first command accesses the mount point, and something like that is required for the second command to work; the second command maps a folder in that mount point to a dosemu drive:

`unix test -d /misc/win`
`lredir w: \\LINUX\FS\misc\win\WP51`  (or whatever folder you want to access from dosemu)

**Comment by andrewbird** [comment]
So without the Unix test -d what did the lredir respond?

**Comment by emendelson** [comment]
> So without the Unix test -d what did the lredir respond?

`Error 35 (network name not found) while redirecting drive W: to \\LINUX\FS\MISC\WIN\WP51`

**Comment by andrewbird** [comment]
Yes, but first does it work if you don't map the wp51 subdirectory but the upper one?

**Comment by emendelson** [comment]
Same error 35 with 

`lredir w: \\LINUX\FS\misc\win`

**Comment by andrewbird** [comment]
Interesting as that suggests that dosemus MFS is searching /misc for win rather than doing access /misc/win. It's probably to do with implementing case insensitivity.

**Comment by jschwartzenberg** [comment]
Why do you want the partition to be unmounted? `autofs` is typically used for network mounts, but I'd expect your partition to be always available. You could mount it at boot-up in `/etc/fstab` or some autostart in either dosemu2 or your DE with `gvfs-mount`. At system shutdown it would be unmounted in any case.

**Comment by emendelson** [comment]
> Why do you want the partition to be unmounted? 

Simply for security, and to prevent inadvertent damage to the files on that partition. I'm writing these instructions for other people to use, and it seems sensible to set things up in the safest possible way.

**Comment by emendelson** [comment]
> Interesting as that suggests that dosemus MFS is searching /misc for win rather than doing access /misc/win. It's probably to do with implementing case insensitivity.

@andrewbird - OK, let me know if you want any testing done here. I've now set up a dual-boot Windows-Linux VMware system, so it's easy to test without rebooting my main system to Linux.

**Comment by jschwartzenberg** [comment]
> Simply for security, and to prevent inadvertent damage to the files on that partition.

In that case `autofs` might not be what you want as it will just mount the partition whenever an attempt is made to access anything through its mount point.

**Comment by emendelson** [comment]
> > Simply for security, and to prevent inadvertent damage to the files on that partition.
> 
> In that case `autofs` might not be what you want as it will just mount the partition whenever an attempt is made to access anything through its mount point.

You're right. Will keep thinking about this.
