### ISSUE TITLE
Automatic shutdown script/batch?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1197]
Is there any chance that dosemu2 could add a shutdown-script feature? This would be a batch file that runs automatically when dosemu2 exits. This would be useful if USERHOOK.BAT includes a command to mount a partition, and you want the partition to be unmounted when you quit dosemu2.

I realize that this is very low-priority.

**Comment by stsp** [comment]
In userhook you can run pre-script
then wp then post-script.

**Comment by andrewbird** [comment]
>includes a command to mount a partition

Have you thought about setting up [autofs](https://help.ubuntu.com/community/Autofs). I use it for NFS mounting of directories etc where I can mount on demand just by accessing the directory. I believe it should be possible to setup direct mounts on local directories, not just NFS and SMB etc.

e.g.
~~~
$ df | grep /CDs # nothing mounted
$ ls /CDs
applications  get.sh	    VFon1				 Windows
AspireOne     Ubuntu	    VMSTUFF
DOS	      UbuntuPrepay  volumio-2.619-2019-09-24-pi.img.zip
$ df | grep /CDs
oliver:/space/CDs       1547924992 765042688 704228864  53% /CDs
~~~
After some configurable timeout period(5 minutes default), the idle directory is unmounted.

**Comment by emendelson** [comment]
Will try autofs, Thank you; it's new to me.

**Comment by emendelson** [comment]
@andrewbird - have taken up your suggestion about autofs here: https://github.com/dosemu2/dosemu2/issues/1195#issuecomment-640271313
