### ISSUE TITLE
Option to ignore USERHOOK.* on startup?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1198]
Is there a way to ignore USERHOOK.BAT and USERHOOK.SYS during startup, without editing the files in Linux? If this exists, I can't find it. 

Ideally, there could be a startup switch that would do this, or (like macOS) you could bypass these files by holding down the shift key during startup.

If this optional already exists, just ignore me.

**Comment by stsp** [comment]
If you dont need them, then dont
create them.
You can run dosemu -Y
and skip userhook.sys during
interactive startup.
Right shift can skip all boot files,
including those.

**Comment by emendelson** [comment]
> If you dont need them, then dont
> create them.
> You can run dosemu -Y
> and skip userhook.sys during
> interactive startup.
> Right shift can skip all boot files,
> including those.

Thank you. I know not to create them if I don't need them - this was for quick debugging when the .BAT and .SYS files cause problems.

**Comment by emendelson** [comment]
As far as I can tell, right-shift doesn't skip all boot files. And -Y isn't documented; I'll post a PR for that.

**Comment by stsp** [comment]
If shift doesnt work, use -Y and then F8.
Cant check right now.

**Comment by emendelson** [comment]
> If shift doesnt work, use -Y and then F8.

Seems to work, but gave a strange error message about not being able to open C:\AUTOEXEC.BAT.

**Comment by stsp** [comment]
```
SWITCHES=#0[Y,N]?N
Process 0 starting: C:\command.com /D /P /E:256
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
Bypassing '\autoexec.bat'.
C:\>
```

Is this what you see?

**Comment by stsp** [comment]
I only get this:
```
SWITCHES=#0[Y,N]?N
Process 0 starting: L:\command.com /D /P /E:256
C:\>
```

**Comment by emendelson** [comment]
Will experiment again and report.

**Comment by stsp** [comment]
Please re-open if you find something new.
