### ISSUE TITLE
Mouse tracking wrong position in Trident VGA modes >25 lines or >80 columns

### ISSUE THREAD

**Issue by severach** [dosemu2/dosemu2#1208]
**Describe the bug**
Clicking on the graphical DOS window generates a mouse click in the wrong place when the screen is not mode 0x03 80x25 or 80x50.

**To Reproduce**
`xmode -mode` any Trident mode 0x50 to 0x5a. Foxpro System Capture, drag a box in the window. The box is drawn behind the cursor. 80 column modes track properly left to right. 25 row modes track properly up and down.

Standard VGA modes 80x25 and 80x50 track properly.  The mouse also tracks properly when the screen is set to a VESA text mode by `mode con: lines=43 cols=132` or `xmode -mode 0x10a`

**Comment by stsp** [comment]
Should now be fixed.
What is that sudden interest to
non-std text modes? Never seen
that before.

**Comment by severach** [comment]
I found the mode table so I can test all modes. I was particularly interested in getting the mouse to work in my custom 132x65 mode.
