### ISSUE TITLE
Space Quest III (and similar Sierra games) won't start

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1210]
**Describe the bug**
Starting Space Quest III, and other Sierra games from this engine/time period won't start.  These games worked previously, perhaps two months ago.  Hero's Quest I (Quest for Glory) and Conquests of Camelot fail in a similar way.

**To Reproduce**
Start Space Quest III.

**Attach program/game binaries or provide an URL**
[sq3.zip](https://github.com/dosemu2/dosemu2/files/4825480/sq3.zip)

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/4825492/boot.log.zip)

**Additional info**
This DOSEmu2 is running with MS-DOS 6.22, and the games are running off a Netware share.   This bug is not MIDI-related, as I've tried to play this game with PC Speaker too.

**Comment by jharrison03** [comment]
[dosemurc.zip](https://github.com/dosemu2/dosemu2/files/4825538/dosemurc.zip)

**Comment by stsp** [comment]
Please try `$_cpu_vm = "emulated"` emulated
to exclude the kvm problem.
Also if you happened to know if it ever
worked on dosemu1 - please share that
info.
If you know if it is a DPMI or realmode
program - please specify.

**Comment by jharrison03** [comment]
These are real-mode programs, and worked previously under DOSemu2.  I have not tried DOSemu1, but I can do so if that would be helpful.

With $_cpu_vm = "emulated", DOSEmu2 crashes with the following printed to the console:

`ERROR: EMU86: error 2`

[boot.log.zip](https://github.com/dosemu2/dosemu2/files/4827249/boot.log.zip)

**Comment by stsp** [comment]
> These are real-mode programs, and worked previously under DosEmu2.

This is the most helpful, thanks.
I updated the bugreport template
to ask for a regression.

**Comment by bartoldeman** [comment]
I tried it myself and sq3 works for me, both with KVM and CPUEMU.
I also added these to my dosemurc like in your example:
```
$_set_int_hooks = (on)
$_force_int_revect = (on)
$_umb_b0 = (on)
```
and it still works. This is with FreeDOS though.

You have CPUEMU crashing by the way when it tries to execute part of the interrupt table. That's usually a very bad sign and probably means memory is corrupted somewhere.

**Comment by stsp** [comment]
For me it starts as well.
Both on PC-DOS and fdpp, and with midi.
You dosemu is not latest, but I don't think
that's the reason.
Anyway, you should isolate the problem
more cleanly. It either is something with
dosemu options you probably changed,
or some customizations in config/autoexec?

**Comment by jharrison03** [comment]
The only thing I've changed in awhile is DOSemu itself.  I'll try to work my way back through some of the older releases to see where I started to have this problem.

**Comment by jharrison03** [comment]
OK, so the game fires up right away if I run it off a local drive.  It's when the game is run off the network share that it crashes.

**Comment by stsp** [comment]
Maybe no other programs work from that share?

**Comment by stsp** [comment]
May be some permission problem, like the
missing write access.

**Comment by andrewbird** [comment]
Perhaps you could change the debug info to `-D+a-k`, as currently the log is truncated due to many keyboard messages?

**Comment by stsp** [comment]
Please re-open when you have more info.

**Comment by jharrison03** [comment]
OK, 

$_umb_b0 = (on)

is what is triggering this for me.  turning this off, these games now run.

**Comment by stsp** [comment]
OK, thanks for an update.
$_umb_b0 is not on by default.
