### ISSUE TITLE
$_unix_exec does not work

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1227]
**Describe the bug**
As reported in the PR.

**To Reproduce**
```
julius@wijsvinger:~/checkouts/dosemu2$ tail /etc/dosemu/dosemu.conf 
# svgalib is available only if it is compiled in.
# "vesa" will probably work; if not, try "plainvga". Default: "vesa"

# $_chipset = "vesa"

# [priv] if you have one vga _plus_ one hgc (2 monitors)

# $_dualmon = (0)

$_unix_exec = "/bin/ls"
julius@wijsvinger:~/checkouts/dosemu2$ dosemu
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : Bestand of map bestaat niet open /dev/snd/midiC0D0 failed
INFO: booting with comcom32, this is very experimental
ERROR: execution of ls is not allowed.
Add /bin/ls to $_unix_exec list.
```

**Attach program/game binaries or provide an URL**
n.a.

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/4908156/boot.log)

**A regression?**
This is a new feature. Did you consider a compilation flag to disable it entirely? It would be to be able to choose between hardened/unhardened at compile time.

**Additional info**
nothing

**Comment by stsp** [comment]
No, it is a regression.
I think the config parsing is now unreliable.
Someone also says $_hdimage="image"
doesnt work, but it works for me.
Could you please check if the recent
removal of dosemu1 security system is
the problem here?

**Comment by jschwartzenberg** [comment]
How would you recommend to test this? Revert a particular commit or bisect?

**Comment by stsp** [comment]
Revert 010a18cee99beb5842c791b97877294f0fffde94
or checkout before it.

**Comment by jschwartzenberg** [comment]
I can confirm that the revision before that one works.

**Comment by stsp** [comment]
Not sure how would I reproduce that,
if everything works for me.
ssh? :)

**Comment by stsp** [comment]
And what exactly works?
Allows you to add a proper exec permission?

**Comment by jschwartzenberg** [comment]
Yes, with the same config, I could execute `unix ls`, but `unix dir` would give an error that the path to `dir` had to be whitelisted.

**Comment by stsp** [comment]
So I broke the config parsing in
a way that isn't reproducible for
me on both fedora and ubuntu
focal. Which is rather frightening.
Will appreciate an ssh.

**Comment by stsp** [comment]
Ah, I can reproduce!
I broke only /etc/dosemu/dosemu.conf
because I never use it.
~/.dosemu/.dosemurc is still fine.
Will fix tomorrow.

**Comment by stsp** [comment]
Should now be fixed.
Please check.

**Comment by jayschwa** [comment]
I am experiencing a (probably) related issue after upgrading my Ubuntu build. I have not modified `/etc/dosemu/dosemu.conf` as it is shipped in the Debian package.

```
$ apt list --installed | grep dosemu2
dosemu2/focal,now 2.0~pre8-6244-63df8af+202007141831~ubuntu20.04.1 amd64 [installed]

$ dosemu
Error in /etc/dosemu/dosemu.conf: (line 887) syntax error
1 error(s) detected while parsing the configuration-file
1 error(s) detected while parsing the configuration-file

$ nl -ba /etc/dosemu/dosemu.conf | tail
   877	# $_dualmon = (0)
   878	
   879	##############################################################################
   880	## Host permissions
   881	
   882	# list of commands (by their full pathes) allowed to execute via unix.com
   883	# Example: "/bin/ls /bin/echo" will enable commands ls and echo.
   884	# Default: "" (host execution not allowed)
   885	
   886	# $_unix_exec = ""
```

**Comment by stsp** [comment]
Should now be fixed.

**Comment by jayschwa** [comment]
Thanks. Will the fix make it to the Ubuntu PPA?

**Comment by jschwartzenberg** [comment]
I can confirm this works now.
