### ISSUE TITLE
Problem starting Dosemu with --Fimagedir

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1228]
**Describe the bug**
I wish to run dosemu from the build directory just like Travis does, but the script I usually use has stopped working for me
~~~
#!/bin/sh

GDB=""
GDB_DOSEMU_ARGS=""

if [ x${1} = "x-gdb" ] ; then
  GDB="gdb --args"
  GDB_DOSEMU_ARGS="-I 'cpuemu vm86sim cpu_vm emulated cpu_vm_dpmi kvm'"
fi

DSP=""
if [ x${1} = "x-S" ] ; then
  DSP="-S"
elif [ x${1} = "x-X" ] ; then
  DSP="-X"
elif [ x${1} = "x-t" ] ; then
  DSP="-t"
elif [ x${1} = "x-td" ] ; then
  DSP="-td"
fi

#LOG="-D9+MEDd#"
#LOG="-D+xc"
#LOG="-D+f"
LOG="-D+Dd"
#LOG="-D+k"

env FDPP_KERNEL_DIR=`pwd`/../fdpp.git/fdpp ${GDB} bin/dosemu.bin \
	-n ${DSP} -f test-imagedir/dosemu.conf ${LOG} -o test.log \
	--Fimagedir `pwd`/test-imagedir \
	--Flibdir `pwd`/test-libdir \
	${GDB_DOSEMU_ARGS}
~~~

**To Reproduce**
- `rm -rf ~/.dosemu`
- Run the script above: `$ ./mintest.sh`
~~~ 
dosemu.bin: parser.y:2560: set_drive_c: Assertion `!err' failed.
Aborted (core dumped)
~~~

**Attach the log**
[test.log](https://github.com/dosemu2/dosemu2/files/4913083/test.log)

**A regression?**
I suspect it's to do with the commits that removed Dosemu1 security (A good idea by the way!)

**Additional info**
- If I create the directory `~/.dosemu/drive_c`, I get no assertion but boot freezes after FDPP sets up the drives.
~~~
ajb@polly:/clients/common/dosemu2.git$ mkdir ~/.dosemu/drive_c
ajb@polly:/clients/common/dosemu2.git$ ./mintest.sh 
INFO: booting with comcom32, this is very experimental
~~~
![2020-07-13-153101_722x580_scrot](https://user-images.githubusercontent.com/220835/87316709-06ae5300-c51e-11ea-8dd6-c0b9aa3a9c11.png)

But since I set the imagedir, I don't think it should be looking in `~/.dosemu` for drives.

- My custom `test-imagedir/dosemu.conf` has just `$_force_fs_redirect = (off)` inside.

**Comment by andrewbird** [comment]
Further info: If I create a symlink as follows, the boot is successful.
~~~
ajb@polly:/clients/common/dosemu2.git$ rmdir ~/.dosemu/drive_c
ajb@polly:/clients/common/dosemu2.git$ ln -s `pwd`/test-imagedir/dXXXXs/c ~/.dosemu/drive_c
~~~

**Comment by stsp** [comment]
Great finding!
2 old bugs: one in freedos (went to
fdpp verbatim), one in dosemu.
Every time I think fdpp is stable and
should be released, I see the bug like
this one. :)

**Comment by andrewbird** [comment]
So that's better (no hang with non-existent `~/.dosemu`, but I still have problems with my drive C:
![2020-07-13-220526_722x430_scrot](https://user-images.githubusercontent.com/220835/87353651-1bf2a400-c555-11ea-9a30-a3977387f8f2.png)

**Comment by stsp** [comment]
Not sure what the problems are,
but use --Fdrive_c if you want the
non-default location of it.

**Comment by andrewbird** [comment]
Yes it's fine now, my own stupidity meant I was trying to run a setup created by a test that didn't configure the C drive! Just searching for the offending test now!
