### ISSUE TITLE
freedos tests fail

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1232]
DPMI-JIT test fails:
https://travis-ci.com/github/dosemu2/dosemu2/builds/178006231
```
  File "test/test_dos.py", line 5886, in test_cpu_jit
    self._test_cpu("emulated", "emulated", "full")
  File "test/test_dos.py", line 5839, in _test_cpu
    self.assertEqual(len(lines), 5056)
AssertionError: 5057 != 5056
```

Bart, do you have an idea what can this be?
It was long ago since I last touched JIT, so maybe
the test is not reliable?

freedos tests all fail:
https://travis-ci.com/github/dosemu2/dosemu2/builds/178015268
This is because I renamed freedos's autoexec.bat.
Andrew, any hint?

**Comment by andrewbird** [comment]
Yes, just testing first, then will post PR

**Comment by stsp** [comment]
Could you please exclude freedos from tests?
I've got enough...

**Comment by andrewbird** [comment]
Presumably that's because the workaround for bad int2f/1217 was removed. I could build FreeDOS from current git and test that or just remove FreeDOS test completely?

**Comment by stsp** [comment]
I don't think the tests themselves depend
on that. It is more likely the setup no longer
works, i.e. you probably do some lredir
before testing, and it fails?

**Comment by andrewbird** [comment]
But FreeDOS 1.20 won't work with MFS without the workaround, that's why it was added.

**Comment by stsp** [comment]
What do you mean?
Only the unattended lredir won't work.
fatfs redirects still work fine.

**Comment by andrewbird** [comment]
I should have said creating new MFS drives where there was no previous drive won't work on FreeDOS <= 1.20 without the workaround.

**Comment by stsp** [comment]
Yep but that's going to break anyway,
as eg FCB is also broken so find_free_drive()
is unreliable.
I am just not sure what LFN tests do have
to do with that...

**Comment by andrewbird** [comment]
At least two of the tests map a temporary path to an arbitrary drive letter, so I'll look reworking those to use an MFS drive that was converted from fatfs.

> Yep but that's going to break anyway,
as eg FCB is also broken so find_free_drive()
is unreliable.

Is that true in the general case, i.e. not just from within config.sys? I'm wondering if you are expecting `lredir x: /tmp` to break on FreeDOS 1.20?

**Comment by stsp** [comment]
Thats a hard question at that point, but
I suspect that to break in some form for
all doses, for security reasons. Of course
there will be a way, or a few, to achieve
similar results, or even allow such constructs
directly, but not by default.
As for freedos - yes, I think I fed up with
its bugs and work-arounds (and the bugs
in a work-arounds), and do not want this
to work any more. Or do you think its a big
deal?

**Comment by stsp** [comment]
I.e. we seem to always say, this dos does
not implement this or that functionality.
Some do not even have redirectors at all,
but in most cases the bugs in other doses
are minor, and are worked around on
config/autoexec level.
Why for freedos, the buggiest dos in the
world (among only those that have
redirector support, as others do not count),
we make an exception and embed evil
hacks in our code? Just why? We have
plenty of doses that just work, so why to
care about something that doesnt?

**Comment by andrewbird** [comment]
> Or do you think its a big
deal?

Not to me as I don't actually use Dosemu for anything, but others might find it so as there's no formal FreeDOS release with the bug fixes in. I should probably run the tests against FreeDOS git to see what the current situation is.

> we make an exception and embed evil
hacks in our code? Just why?

I guess that was my not wanting to break the only free software option for many users, but now we have FDPP and can fix things ourselves.

I looked at those two LFN tests and can see why they needed to create a drive on the fly. The tests are to find the lfn file size info and check its validity. During the test I need to create a 6GiB file to examine, this is currently done as a sparse file and can't be in a directory that will be converted to fatfs (for 2 reasons: fatfs is FAT16B; file gets filled out to consume space). I'm not sure what to do about this, so I'll probably just disable them for FreeDOS 1.20.

**Comment by stsp** [comment]
I dont think you need to run tests against
freedos git, as our tests should test dosemu,
not freedos. Lfn tests are completely
independent of dos (lfn is fully implemented
in dosemu itself), so I see no big deal with
testing lfns with just one dos.

**Comment by andrewbird** [comment]
> I dont think you need to run tests against
freedos git, as our tests should test dosemu,
not freedos.

Agreed as part of Travis, but I meant as a one off just to see what we can expect should there ever be a new release.

**Comment by stsp** [comment]
If you care that much, I would definitely
not stop you. But consider a practical
question: how much time will the build
take, if you also build open watcom or
ia16-gcc?
Consider theoretical question: what exactly
do you expect from 1.3 release, more
than a finally working lredir? We know
it was fixed, and we know nothing else was.
So the results will hardly be surprising.

**Comment by andrewbird** [comment]
> But consider a practical
question: how much time will the build
take, if you also build open watcom or
ia16-gcc?

Funny you should say that, I added a PR to FreeDOS to add watcom builds under Travis but nobody appears to be interested in picking it up https://travis-ci.com/github/FDOS/kernel/builds/150203644 . Using the PPA for gcc and the snapshot binary for watcom, the total build time was about 1.5 minutes.

> Consider theoretical question: what exactly
do you expect from 1.3 release, more
than a finally working lredir? We know
it was fixed, and we know nothing else was.
So the results will hardly be surprising.

And they weren't :smile:, I saw problems with
- FCB
- share on FAT ( share.exe wasn't updated )
- create PSP

**Comment by stuaxo** [comment]
I'll see if I can poke anyone into merging it... :D

**Comment by andrewbird** [comment]
I just saw that odd emulation error on Travis too.
~~~
======================================================================
FAIL: Test MS-DOS-6.22 CPU test: JIT vm86 + JIT DPMI 
----------------------------------------------------------------------

Traceback (most recent call last):

  File "test/test_dos.py", line 5886, in test_cpu_jit
    self._test_cpu("emulated", "emulated", "full")
  File "test/test_dos.py", line 5839, in _test_cpu
    self.assertEqual(len(lines), 5056)

AssertionError: 5057 != 5056
~~~

There's further info in the link that might provide a clue.

https://travis-ci.com/github/andrewbird/dosemu2/jobs/367322102#L2686

**Comment by bartoldeman** [comment]
I can have a look at the jit issue later today. Must be something small as tests were passing for  my last pr

**Comment by andrewbird** [comment]
There seems to be an element of randomness to it.

**Comment by bartoldeman** [comment]
From that log freedos passes the jit but MS-DOS fails so it looks like a recent change has caused MS-DOS to take a different code path triggering a bug somewhere.

**Comment by andrewbird** [comment]
@stuaxo I guess you poked someone as that PR just got merged, thanks!

**Comment by stsp** [comment]
Hi Bart, see also this link please:
https://travis-ci.com/github/dosemu2/dosemu2/builds/178006231
It says that freedos fails.
So MS-DOS can fail too... now we know
that sad news.

**Comment by stsp** [comment]
All with DPMI jit it seems, but these tests
are not supposed to use DPMI.

**Comment by stsp** [comment]
Btw, Andrew, would you like to add
a test or 2 running under valgrind?
Especially interesting would be to
have that with fdpp's valgrind support,
it just needs to grep out false-positives.
But w/o fdpp (and hence w/o false-positives)
would be good too.

**Comment by bartoldeman** [comment]
Almost all cpu test use dpmi, as it's a djgpp program, though it has a few special tests for vm86 too. I'm just away from a computer now so can't really check yet.

**Comment by stsp** [comment]
Ah, indeed! Thanks for info.

**Comment by stuaxo** [comment]
> @stuaxo I guess you poked someone as that PR just got merged, thanks!

Yes, I don't have too much time for dev stuff, randomly emailing people doesn't take much bandwidth :)

**Comment by andrewbird** [comment]
> Btw, Andrew, would you like to add
a test or 2 running under valgrind?

Yes I was thinking about running some tests purely under FDPP in a separate test script for those tests that should not be DOS specific. My first target was the pcmos build you asked for a long while back. I'll see if I can get that working first, then running valgrind could be a second test.

**Comment by stsp** [comment]
Build pcmos under `dosemu -valgrind`. :)

**Comment by stsp** [comment]
Reopen if DPMI-jit fails again.

**Comment by stsp** [comment]
Not a good time to close, as it fails
on an lredir branch.
Andrew, could you please adjust the
setup accordingly,
```
ERROR: redirection of /tmp/ rejected
Add the needed path to $_lredir_paths list to allow
```

**Comment by andrewbird** [comment]
will do...

**Comment by stsp** [comment]
Thanks!

**Comment by stsp** [comment]
> And they weren't smile, I saw problems with

Btw, I can see that with old freedos
the redirections fail now even for fatfs
drives past E. I suppose your lastdrive
bug was increasing that up to F, which
is enough for an fdpp setup, so I have
never seen that problem before.
This is very strange, as it seems
LASTDRIVE doesn't cover all physical
drives during config.sys processing.
But in latest freedos there is no such
problem.

**Comment by andrewbird** [comment]
I know I keep mentioning it, but CDS size and drive unit allocation isn't finalised until after config.sys processing. Device driver Init functions are only supposed to use a very small set of msdos functions (01..0c and 30), obviously int 21/5f03 is not one of them. I do think that trying to assign drives from within config.sys with `device=` is very DOS dependant, although doing it with `install=` should be okay.
> This is very strange, as it seems
LASTDRIVE doesn't cover all physical
drives during config.sys processing.

Why would you expect it to be valid, it's set to be the highest of '5', number of physical units discovered after processing built-ins + device=block devices, and Lastdrive value set in config.sys? At the very least you should expect it to increase from 5 after config.sys processing, but it may never actually be set at all during config.sys processing.

**Comment by stsp** [comment]
I think what you suggest is a bit weird, as
that would most certainly imply that such
physical drives are unaccessable during
config.sys. But all physical drives should
be accessible during entire config.sys, so
LASTDRIVE should already be sane as
well.
Maybe in old freedos, config.sys can't
work with any drive past E?

**Comment by andrewbird** [comment]
> But all physical drives should
be accessible during entire config.sys

Certainly not if they were added during config.sys processing via `device=block.sys`, as the CDS array needs to grow to accommodate them. So do you expect that the array is resized and lastdrive set after processing each `device=` statement?

>Maybe in old freedos, config.sys can't
work with any drive past E?

That's possible, my thought here is that the CDS array resize and lastdrive set doesn't happen until all the `device=` statements within config.sys have been processed. Of course you are concerned with fatfs drives that are discovered and units added to reference the built-in HDD driver rather than `device=block.sys`, but I think expecting the CDS array to always be the right size during processing of config.sys relies upon undefined behaviour.

**Comment by stsp** [comment]
But fatfs/physical drives are not added by
device= processing. They are added at init.
You can even see the drive map before
config.sys processing - freedos prints it.

**Comment by andrewbird** [comment]
When you speak of 'old freedos', which version do you mean? I just tested Freedos 1.20 here and I see with
`$_hdimage = "dXXXXs/c:hdtype1 dXXXXs/d:hdtype1 +1"`
~~~
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
G: HD5, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB 
~~~

G: is accessible both as MFS, and also after `lredir -d g:` as fatfs.

**Comment by stsp** [comment]
```
FreeDOS kernel build 2036 cvs [version Aug 18 2006 compiled Aug 18 2006]
Kernel compatibility 7.10 - WATCOMC - 80386 CPU required - FAT32 support
```

On loading emufs.sys I see this:
```
ERROR: INT21: redirecting F: failed (err = 15)
```
and drive F is not present (`$_hdimage = "+0 +1"`).
Can you reproduce?

**Comment by andrewbird** [comment]
So that's FreeDOS 1.00
~~~
FreeDOS kernel build 2036 cvs [version Aug 18 2006 compiled Aug 18 2006]
Kernel compatibility 7.10 - WATCOMC - 80386 CPU required - FAT32 support
 
(C) Copyright 1995-2006 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the

GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
EMUFS host file and print access available
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.8 installed.
dosemu CDROM driver installed (V0.2)
Kernel: allocated 41 Diskbuffers = 21812 Bytes in HMA
emufs: redirector enabled
C:\>prompt $P$G
C:\>path c:\bin;c:\gnu;c:\dosemu
C:\>system -s DOSEMU_VERSION
C:\>system -e
C:\>lredir
Current Drive Redirections:
C: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\c\ attrib = READ
/WRITE
D: = \\LINUX\FS\clients\common\dosemu2.git\test-libdir\dosemu2-cmds-0.2\ attrib
= READ/WRITE
E: = \\LINUX\FS\clients\common\dosemu2.git\..\fdpp.git\fdpp\ attrib = READ/WRITE
~~~

and see `ERROR: INT21: redirecting F: failed (err = 15)` in the launching terminal

If I use either FreeDOS 1.10 or 1.20 things are fine, perhaps this is the change that made it work https://github.com/dosemu2/fdpp/commit/0c38351fe7114454ce123183359e3ca6b9c8c539

**Comment by stsp** [comment]
Not the best possible fix I think, but
oh well. :)
