### ISSUE TITLE
Python 3.8.5 in HX runtime crashes

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1243]
**Describe the bug**
A description of what the problem is.

**To Reproduce**
Obtain HX runtime and Python 3.8.5: 

```
hxldr32
python
```
Edit: I wasn't clear with the shot, pressing enter with this will crash DOSEMU2.
![Screenshot_20200815_223238](https://user-images.githubusercontent.com/877112/90321154-5af68980-df47-11ea-816b-ba439c7ccd4e.png)

**Attach program/game binaries or provide an URL**
https://github.com/Baron-von-Riedesel/HX/raw/master/bin/HXRT218.zip
https://www.python.org/ftp/python/3.8.5/python-3.8.5-embed-win32.zip

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/5079435/boot.log)

**A regression?**
unlikely

**Additional info**
n.a.

**Comment by stsp** [comment]
Why do you think it is supposed to work?

**Comment by jschwartzenberg** [comment]
I don't think it's supposed to work, but it just shouldn't crash DOSEMU2 like that.

**Comment by stsp** [comment]
Like what exactly?
The log indicates the clean shutdown
upon an invalid opcode.
So unless @Baron-von-Riedesel thinks
it should work, lets close this.

**Comment by jschwartzenberg** [comment]
Alright, I'll check this on real hardware.

**Comment by jschwartzenberg** [comment]
I just checked on real hardware, I get a messages about missing DLLs but no crash.

**Comment by stsp** [comment]
@Baron-von-Riedesel any idea why running
python could cause invalid opcode under dosemu?

**Comment by Baron-von-Riedesel** [comment]
Perhaps a "mov eax,cr2"? 
AFAIK, that's the only deliberate "invalid opcode" used by dkrnl32.dll in v2.18, used when a page fault has occured.
It has been removed in v2.19, because hdpmi supports v1.0 exception handling, where contents of cr2 is supplied.

You could download the v2.19 prerelease to check: [html]https://github.com/Baron-von-Riedesel/HX/releases/download/v2.19pre1/HXRT219pre.zip[/html]

**Comment by stsp** [comment]
> Perhaps a "mov eax,cr2"?

Looks different:
`0f 00 70 00 16 00 70 00 2c 00`.

> Shouldn't dosemu be able to tell the "opcode"?

Yeah, its in the log.

> And it has been removed in v2.19

Would be interesting to try. :)
