### ISSUE TITLE
implement get_redirection fn 5f06h

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1259]
0x5f05 allows large buffers, but unfortunately
doesn't take its size in CX.
We need to implement 0x5f06 and
switch lredir to it.
This will allow to have long linux pathes
being mapped to DOS drives.
Andrew, do you want? :)

**Comment by andrewbird** [comment]
> CX is already in use for signature, is it okay to DX instead for the resource size?

I don't know what I was looking at yesterday (maybe 5f03) but input CX is not already in use for signature.

**Comment by stsp** [comment]
Indeed!
The signature is already stored at
that point, and can be checked in
drives[] data, if there is a need.

**Comment by stsp** [comment]
Implemented.

**Comment by stsp** [comment]
I can't find that recent discussion where
@bartoldeman said why lfn shares code
with mfs, and I said that we can avoid
sharing mfs state.
Does anyone remember where it is?

**Comment by andrewbird** [comment]
I think it was in a devs discussion https://github.com/orgs/dosemu2/teams/devs/discussions/7. I'm not sure (I know it was my fault) that having discussions about specific topics there is a really good idea.

**Comment by stsp** [comment]
Thanks.
I don't see the search capability for
discussions. Is there one?

**Comment by andrewbird** [comment]
I didn't see one yet. I also suspect that @mentions in a devs discussion don't work outside the membership of 'devs'.

**Comment by stsp** [comment]
Hmm.
We need to check that.
I pinged @stuaxo in a
discussion.
@stuaxo have you got a
notification from a discussions,
or only from this ticket?

**Comment by stuaxo** [comment]
Just tickets, this thread is the first time I'd heard of discussions.

I'll get into the mail that github points to later and verify there's nothing there.

**Comment by stsp** [comment]
OK, so the mentions do not work in
the discussions indeed... and that is
quite upsetting.
You haven't heard about discussions
because you rejected my invitation to
them. :) But this is not a problem by
itself. If notifications worked, that would
still be fine...

**Comment by stuaxo** [comment]
Problem is user: github mails go to a place I don't see them, will actually check now :)

**Comment by stuaxo** [comment]
I couldn't find it, maybe try invited me again?    It's very possible I fat-fingered this on my phone and declined by accident.

Spent a minute or two to google discussions to see what it github discussions actually is now at least.

**Comment by stsp** [comment]
Yes, sure, I invited you again.
I don't like this invitation stuff,
but it doesn't look like I can make
them public. :(

**Comment by stuaxo** [comment]
Cheers, found the other one - I probably need to check that mail more often than once every month or two.

**Comment by stsp** [comment]
You can use https://github.com/notifications
to see everything.
