### ISSUE TITLE
Is it really necessary to specify boot drive for fdpp when $_floppy_a is set

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1275]
I've just seen some surprising behaviour when trying to install Borland C++. I need to specify `$_floppy_a` so that I can install from it, but if I do then fdpp can't find the boot files.

I have .dosemurc of
~~~
$_floppy_a = "/home/ajb/.dosemu/a.img"
#$_bootdrive = "e"
~~~

and see 
~~~
Non-System disk or disk error
Replace and strike any key when ready
~~~

My next guess was to set `$_bootdrive="c"` which gave me the same message, and finally guessing `e` which works. Is that what you expect?

**Comment by stsp** [comment]
Yes, this is expected: floppy
overrides the boot sequence,
as otherwise there would be
no floppy boot.
But of course `$_bootdrive = "e"`
is not intuitive enough for a
guess.
I guess something like "noboot"
floppy flag can solve the problem?

**Comment by stsp** [comment]
> My next guess was to set $_bootdrive="c" which gave me the same message,

Are you sure?
For me its not like that.
If I define $_floppy_a and set
$_bootdrive="c", then I get
`ERROR: Drive unbootable, exiting`.
Could you please re-check?

**Comment by andrewbird** [comment]
Yes quite correct, writing what I thought I saw, not what I actually saw!

with `$_bootdrive="c"`,  I really see
`ERROR: Drive unbootable, exiting`

**Comment by stsp** [comment]
So in case you see `noboot`
floppy flag as an adequate solution,
would you like to code that up?

**Comment by andrewbird** [comment]
I have a few other half finished things to do first though.

**Comment by andrewbird** [comment]
Just a thought, rather than introduce a new flag, how about ignoring floppy for boot if `$_bootdrive` not set to 'a'? In my distant memory I think that's how it used to work. Is there any downside to this?

**Comment by stsp** [comment]
Its exactly how it is now!
However, deducing "e" is a too
hard task for a user.

**Comment by andrewbird** [comment]
Not quite what I mean, but these scenarios:

1.
   1. non bootable floppy image in $_floppy_a
   2. $_bootdrive not set
   3. Dosemu ignores boot floppy and follows normal procedure (ultimately booting off `e:`)

2. 
   1. non bootable floppy image in $_floppy_a
   2. $_bootdrive set to `a`
   3. Dosemu recognises floppy and dos tries to boot from it (ultimately ends with non system disk message)

3.
   1. non bootable floppy image in $_floppy_a
   2. $_bootdrive set something other than `a`
   3. Dosemu gets dos to try to boot from whatever is specified in bootdrive (like now)

**Comment by stsp** [comment]
How would you know if the image
is bootable?

**Comment by andrewbird** [comment]
I'm not suggesting we care, only that we ignore the floppy in the case that `$_bootdrive` is not set to `a`. Normal DOS boot procedure would determine if it's bootable

**Comment by andrewbird** [comment]
I suppose in the case that the image is bootable the scenarios would be:

1.
   1. bootable floppy image in $_floppy_a
   2.  $_bootdrive not set
   3.  Dosemu ignores boot floppy and follows normal procedure (ultimately booting off e:)

2.
   1. bootable floppy image in $_floppy_a
   2. $_bootdrive set to a
   3. Dosemu recognises floppy and dos tries to boot from it (ultimately ends with it booting from floppy)

3.
   1. bootable floppy image in $_floppy_a
   2. $_bootdrive set something other than a
   3. Dosemu gets dos to try to boot from whatever is specified in bootdrive (like now)

**Comment by stsp** [comment]
So basically you propose to ignore
the floppy boot unless the $_bootdrive
is explicitly set to "a"?

**Comment by andrewbird** [comment]
Yes.

**Comment by stsp** [comment]
Its a simplest solution indeed, but
its just not the way old PCs worked.
What do other ppl think, should we
ignore floppy boot unless explicitly
asked in a config?

**Comment by stsp** [comment]
OKey, please prepare the patch, and
if no one objects, we'll think and/or apply.

**Comment by andrewbird** [comment]
Okay, cool. So what's the method of tricking DOS into ignoring the floppy, faking drive not ready until we've booted, or something else?

**Comment by stsp** [comment]
Its not DOS, its a bios business.
But in dosemu2 - just find `boot()` fn.
