### ISSUE TITLE
lfn: get rid of drives[] access

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1278]
It seems lfn.c accesses drives[] array
quite a lot. But now we can use get_redirection()
API to get drive root and parameters.

**Comment by stsp** [comment]
Andrew, would you like to take a look? :)

**Comment by andrewbird** [comment]
Not sure how much time I'll have in the fairly near future. It's probably best if you do it, although I'll try to look at what you have done from to time.
