### ISSUE TITLE
dosemu.bin blithely ignores -q (quiet) option?

### ISSUE THREAD

**Issue by tkchia** [dosemu2/dosemu2#1279]
This was seen with commit 8fa742a08c5675c2f8c6c2db491c0a86ebe1c0c5 (`hello.com` is a simple "Hello world" program):
```
$ dosemu.bin -td -q -K . -E hello.com
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
dosemu2 2.0pre8 Configured: 2020-09-16 03:05:27 +0000
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

FDPP kernel 1.0final [GIT: ] (compiled Aug 21 2020)
Kernel compatibility 7.10 - GNUC - 80386 CPU required - FAT32 support

Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled                                           
dosemu EMS driver rev 0.8 installed.
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)
Kernel: allocated 115 Diskbuffers = 62560 Bytes in HMA
Process 0 starting: F:\command.com /e:384 /k %FDPP_AUTOEXEC%
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre8
About to Execute : hello.com
Hello world!
```

It should say just
```
Hello world!
```
or at most (as in earlier versions of `dosemu2`)
```
About to Execute : hello.com
Hello world!
```

This issue is currently messing with my [`libi86`](https://gitlab.com/tkchia/libi86) automated testing.

Thank you!

**Comment by stsp** [comment]
-q have indeed changed a bit.
I think the property you desire, is only
applicable to -td, so perhaps I can allow
to write -tdq for that?

**Comment by tkchia** [comment]
Hello @stsp,

> so perhaps I can allow to write -tdq for that?

Perhaps so.  But I am curious what `-q` _is_ supposed to mean now...

Thank you!

**Comment by stsp** [comment]
As always, it is supposed to suppress
various errors and any interactive stuff.
It was very important before, when
dosemu asked to confirm the read of
a disclaimer on first run: you could use
-q to suppress that behaviour.
Now as there is no more a disclaimer
prompt, -q is not that powerful, as it
only suppresses the errors.

In any case, I am thinking about
something like `-tde` that will just
redirect the DOS output to stderr
instead of stdout, and the -E prog
to stdout. That will allow
you to silence stderr yourself.

**Comment by stsp** [comment]
Please use `-tde` now.
Andrew, are you interested in that
functionality as well?
Might allow you to drop those games
with command prompt.

**Comment by tkchia** [comment]
Hello @stsp ,

Thanks for the new option!  I am now trying it out with my `libi86` tests.

**Comment by stsp** [comment]
I am just not sure where you
redirect stderr to /dev/null, as this
option would require.

**Comment by ecm-pushbx** [comment]
I believe I'm running into this bug, using "Build 2.0pre8-20201013-2403-gd92cff46b" (based on revision d7c9be2c8e4aacdca01e44f43aad03e6664f0085 of current git devel branch). Here's [my use case](https://hg.ulukai.org/ecm/ldebug/file/32f3151c9923/source/mak.sh#l386):

```
decompsize="$(( $( \
        dosemu -K "${PWD}/${rootpath}tmp/$inicomp_suffix" -E $tpre"$build_name".$comext -dumb -quiet 2> /dev/null \
        | tee /dev/stderr | sed -re '/^(about to execute|error:|note:|info:)/Id;s/[\r\n]+$//g' \
        ) * 16 ))"
```

That is, I use -K and -E to run the test, and I pass `-dumb -quiet` to dosemu and use redirection of stderr to /dev/null. Then I filter out lines starting with "about to execute", "note:", or "info:". It is expected that the only remaining word is an integer written on its own line by the test program. I require both `-dumb` and `-quiet` for this. Please restore this functionality!

**Comment by ecm-pushbx** [comment]
Thanks, that works!

**Comment by ecm-pushbx** [comment]
I just noticed you broke it, but differently. Using only `-dumb` without `-quiet` should show the DOS startup messages but is now the same as `-dumb -quiet`. This is not as bad as the prior use case failure however. (`dosemu -dumb -A -I "floppy { device bootimgu.img }"` (no `-quiet`) somehow does show the dosemu2 boot up message and I'm not sure why. Would be a bug if it didn't.)

**Comment by stsp** [comment]
No, its not the same, it depends on the
redirection of stderr.

**Comment by ecm-pushbx** [comment]
Ah okay. The change is a bit weird though.

**Comment by stsp** [comment]
> Ah okay. The change is a bit weird though.

OK, quiet now removed.
