### ISSUE TITLE
dosemu2 ignore -f option

### ISSUE THREAD

**Issue by bpranoto** [dosemu2/dosemu2#1280]
**Describe the bug**
When launching dosemu with -f with the alternate configuration, the alternate configuration is not read.

**To Reproduce**
dosemu -f /etc/dosemu/test.conf

test.conf is not parsed and read, see the log

**Attach the log**
attached.

**A regression?**
Yes, but I am not sure in which version it start to be broken

**Additional info**
Unfortunately, when I  compile the source within my system (ubuntu 18.04), the dosemu executable refuses to run because the libudev version (237) is older than expected (240)

So I install from the ppa, and the package name changes to dosemu2-legacy? ...and the compile date is 2020-08-20

[boot.log](https://github.com/dosemu2/dosemu2/files/5238302/boot.log)

**Comment by stsp** [comment]
> So I install from the ppa, and the package name changes to dosemu2-legacy? ...and the compile date is 2020-08-20

I updated the legacy build now, so
it has that problem fixed.
Yes, legacy builds are only updated
on request.
