### ISSUE TITLE
$_ipxsupport = (on) is ignored

### ISSUE THREAD

**Issue by bpranoto** [dosemu2/dosemu2#1281]
**Describe the bug**
After updating dosemu2 from ppa, $_ipxsupport = (on) seems to be ignored.

Previously, with the setting $_ipxsupport = (on) , in the autoexec.bat I just need to call vlm (netware dos client) and then I can login into the netware server. However, after this recent update, it doesn't work anymore.

**To Reproduce**
1. Set $_ipxsupport = (on) , leave $_ipx_network commented.
2. run dosemu
3.within the dos session just call vlm.exe

**Attach the log**
boot.log attached
vlm error message attached.

**A regression?**
Yes.

[boot.log](https://github.com/dosemu2/dosemu2/files/5239266/boot.log)

[errorvlm.txt](https://github.com/dosemu2/dosemu2/files/5239291/errorvlm.txt)

[dosemu.conf.txt](https://github.com/dosemu2/dosemu2/files/5239302/dosemu.conf.txt)

**Comment by bpranoto** [comment]
Thanks.

Could you please update the  ppa's package?

**Comment by stsp** [comment]
Updated legacy packages.
