### ISSUE TITLE
kvm-DPMI: problem with ia16-elf-gcc compiled libi86 test

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1284]
**Describe the bug**
I'm trying to get the libi86 tests running as single dosemu2 test so that I can add it to the suite. One of the meta tests to validate the test environment is failing with a DPMI error, even though the test itself is believed to be a non DPMI app.

**To Reproduce**
Difficult to run these tests standalone on anything other than where the libi86 test suite was run, but I can reproduce simply by running the `a.exe` by hand, because as yet I haven't figured out how to pass custom options to dosemu via the libi86 test suite, so all dosemu.conf values are standard.

**Attach program/game binaries or provide an URL**
[03.tar.gz](https://github.com/dosemu2/dosemu2/files/5240632/03.tar.gz)

**Attach the log**
It is located in tar file as `a.log`
.
**A regression?**
no idea, it's the first time I compiled and ran this binary

**Additional info**
1. The testsuite.log, shows that the test exe, compiled with different options appears to work, only the final test fails.
2. I do note that `a.exe` does appear to be a `.com` file
3. My environmnt is FDPP + comcom32

**Comment by stsp** [comment]
This is related to KVM.
```
DPMI: int31, ax=0009, ebx=00000177, ecx=000000f7, edx=0000642f
        edi=0000f501, esi=0000643b, ebp=0000091e, esp=0000fffe
        eip=0000017e, eflags=00083282
        cs=0167, ds=0177, ss=0177, es=017f, fs=0000, gs=0000
DPMI: SetDescriptorAccessRights[0x002e;0x0177] 0x00f7
EMU86: modify_ldt 11 16 [0000002e 00007700 0000ffff 00000002]
EMU86: LDT entry 0x2e type D16: b=00007700 l=ffff fl=00f6
DPMI: cs=0x167, ss=0x177, ds=0x177, es=0x17f, fs=0, gs=0 ip=0x17e
DPMI: switch to dpmi
DPMI: Return to client at 0167:0000017e, Stack 0x177:0x0000fffe, flags=0x83282
DPMI: switch to dosemu
DPMI: do_cpu_exception(0x0c) at 0x167:0x18a, ss:esp=177:fffe, cr2=0x40f2f000, er
r=0
DPMI: eip: 0x0000018a  esp: 0x0000fffe  eflags: 0x00093246
        trapno: 0x0c  errorcode: 0x00000000  cr2: 0x40f2f000
        cs: 0x0167  ds: 0x0177  es: 0x017f  ss: 0x0177  fs: 0x0000  gs: 0x0000
EAX: 00000008  EBX: 00000177  ECX: 00000000  EDX: 0000002b
ESI: 0000643b  EDI: 0000f501  EBP: 0000091e
OPS  : b8 08 00 8c d3 31 c9 ba 2b 00 -> cd 31 16 1f e8 3e 01 e8 3c 01
STACK: 46 32 70 07 7e 01 67 01 82 02 -> 00 00 5a 00 00 ff ff 00 00 00
```

So the client sets the access rights
of the segment that is currently in SS
register, changing it from 0xf2 to 0xf7,
i.e. making the stack expand-down.
But kvm produces stack fault after.
Somehow it "doesn't like" the fact that
current stack segment was altered.

Bart, what do you think?

**Comment by stsp** [comment]
Hmm, in fact, its quite obvious that
flipping the expand-down bit on a
current stack would get the stack
fault, as previously valid region becomes
invalid.
Why this doesn't happen with native
DPMI is because we trap 0x31, but
commit 99fa6f96 removed the trapping
from KVM. Reverting that commit "fixes"
the problem.
But the commit is correct, test-case is buggy.

**Comment by stsp** [comment]
Of course we could work around
that. For example we could use
task-gate for int 0x31, and then
int 0x31 will never get stack fault,
because stack will be switched.
Bart, how difficult would it be to
use task gate for 0x31? If its
something else than "quite trivial",
I'd rather not. But if its simple to
implement...

**Comment by bartoldeman** [comment]
It may not be so hard. I'll have a look at what other DPMI servers do with int31 though (cwsdpmi and co).

**Comment by stsp** [comment]
> I'll have a look at what other DPMI servers do with int31 though

I think they switch ring, which leads
to a stack switch. So they do not need
task-gate but we do.

**Comment by stsp** [comment]
OK, since Bart is interested, lets reopen.

**Comment by tkchia** [comment]
Hello @stsp, @andrewbird, @bartoldeman,

> So the client sets the access rights of the segment that is currently in SS register, changing it from 0xf2 to 0xf7, i.e. making the stack expand-down.

Hmm... OK.  The crashing code is part of the [startup code I wrote in `newlib-ia16`](https://github.com/tkchia/newlib-ia16/blob/newlib-2_4_0-ia16-tkchia/libgloss/ia16/dos-models-crt0.S), for the `-mdpmiable` mode in `gcc-ia16`.  For reference:
```
	# Limit %cs so that it does not go beyond the end of our actual
	# code.  Note that %ax == 0 is preserved from above.
	movb	$0x08,	%al
	movw	%cs,	%bx
	xorw	%cx,	%cx
	movw	$__etext-1, %dx
	int	$0x31
	# Make %ss an expand-down descriptor, and limit it.
	movw	%ss,	%bx
	larw	%bx,	%cx
	xchgb	%cl,	%ch
	or	$0x04,	%cl
	movw	$0x0009, %ax
	int	$0x31
	jc	.Lcont_dpmi
	movw	$0x0008, %ax
	movw	%ss,	%bx
	xorw	%cx,	%cx
# ifdef TINY
	movw	$0x2c-1, %dx
	int	$0x31
	pushw	%ss
	popw	%ds
# else
	movw	$__sdata-1, %dx
	int	$0x31
# endif
.Lcont_dpmi:
.Lno_dpmi:
```

The intention is to limit the program's data (= stack) segment to only addresses _above_ the actual start of the data area.  I figured that to do that, I would likely either have to make `%ss` effectively invalid for a short while, or add more code to temporarily create and destroy new descriptors.

I guess I had not counted on `int $0x31` possibly using the same stack as user code.

Thank you!

**Comment by stsp** [comment]
You probably can still avoid the big
changes if you use SetDescriptor (0x0c).
That way you'll be able to flip the
expand-down bit and adjust the limit
atomically, avoiding the temporary
invalid stack.

**Comment by stsp** [comment]
> The intention is to limit the program's data (= stack) segment to only addresses above the actual start of the data area.

Are you sure expand-down is a match
to that desire?

**Comment by bartoldeman** [comment]
Having a look at cwsdpmi, it looks like the IDT entries it creates are ring 3, DPL=3, type 0xee00 so will not change stacks either.

The code they execute is then in `tables.asm`:

```
        push    ds              ; 1 byte
        call    ivec_common     ; 3 bytes
...

ivec_common:
        push    g_pdata
        pop     ds
        pop     ivec_number
        sub     ivec_number, offset _ivec1      ; pushes address *after* call
        shr     ivec_number, 2
        pop     ds
        jmpt    g_itss                  ; macro for jump to task segment itss
```
so it looks like it's using the stack a little and then jumps to a TSS.

on the other hand @tkchia's code has code to specifically skip cwsdpmi it seems?

**Comment by tkchia** [comment]
Hello @stsp ,

> You probably can still avoid the big changes if you use SetDescriptor (0x0c).

Thanks for the suggestion!  I have modified the startup code in `newlib-ia16` according to your method, so it is now like this:
```
	# Limit %cs so that it does not go beyond the end of our actual
	# code.  Note that %ax == 0 is preserved from above.
	movb	$0x08,	%al
	movw	%cs,	%bx
	xorw	%cx,	%cx
	movw	$__etext-1, %dx
	int	$0x31
	# Make %ss an expand-down descriptor, and limit it.  Use the area
	# just after BSS (which will be the heap/stack area) to temporarily
	# hold %ss's descriptor entry.
	movw	$0x000b, %ax
	movw	%ss,	%bx
# ifndef TINY
	movw	%bx,	%es
# endif
	movw	$__ebss, %di
	int	$0x31
	jc	.Lcont_dpmi
# ifdef TINY
	movw	$0x2c-1, (%di)
	orb	$0x04,	5(%di)
	andb	$0x30,	6(%di)
# else
	movw	$__sdata-1, %ss:(%di)
	orb	$0x04,	%ss:5(%di)
	andb	$0x30,	%ss:6(%di)
# endif
	movw	$0x000c, %ax
	int	$0x31
# ifdef TINY
	pushw	%ss
	popw	%ds
# endif
.Lcont_dpmi:
.Lno_dpmi:
```

> Are you sure expand-down is a match to that desire?

Well, I am not sure, but using an expand-down segment kind of works for now. :-)

Hello @andrewbird,

The meta-tests should hopefully work now.  Sorry for the trouble.

Hello @bartoldeman,

> on the other hand @tkchia's code has code to specifically skip cwsdpmi it seems?

Well, yes.  CWSDPMI force-quits any program that asks for 16-bit DPMI services, and my startup code has to try to work around this.

Thank you!

**Comment by andrewbird** [comment]
@tkchia I'm just waiting for your PPA to update, then I'll try this out straight away. No trouble, this is the point of adding tests and whether it's a dosemu2 or newlib problem is immaterial.

Many thanks!

**Comment by stsp** [comment]
> Well, I am not sure, but using an expand-down segment kind of works for now. :-)

I would rather just create a new segment.
What I am puzzled with, is that you seem
to have the same value in DS, so DS also
becomes expand-down... so how would
you access the data below limit?

**Comment by andrewbird** [comment]
Hi @tkchia,
   With your DPMI fix all of the libi86 tests now pass under Dosemu2, but for some reason they take a very long time. Here's what the testsuite.log shows:
~~~
testsuite: starting at: Sat Sep 19 19:07:18 BST 2020                            
1. dos2unix (metacheck.at:19): ok     (0m0.004s 0m0.001s)                       
2. dosemu (metacheck.at:23): ok     (0m1.422s 0m0.591s)                         
3. GCC toolchain (metacheck.at:32): ok     (1m41.156s 0m34.420s)                
4. Console output testing (metacheck.at:50): ok     (1m47.271s 0m36.278s)       
5. _bios_memsize (bios.h.at:19): ok     (1m42.655s 0m33.942s)                   
6. _bios_equiplist (bios.h.at:48): ok     (1m38.729s 0m33.657s)                 
7. _bios_keybrd (bios.h.at:61): ok     (0m57.732s 0m19.643s)                    
8. _bios_disk (bios.h.at:93): ok     (0m43.496s 0m14.630s)                      
9. _bios_joystick (bios.h.at:182): ok     (1m40.950s 0m34.762s)                 
10. cprintf, cputs (conio.h.at:19): ok     (1m45.037s 0m35.723s)                
11. getch, getche, kbhit, ungetch (conio.h.at:34): ok     (1m47.418s 0m35.956s) 
12. inp, outp (conio.h.at:61): ok     (0m49.857s 0m18.653s)                     
13. inportb, outportb (conio.h.at:132): ok     (0m47.353s 0m17.392s)            
14. bdos, bdosptr (dos.h.at:19): ok     (1m38.582s 0m33.493s)                   
15. intdos (dos.h.at:42): ok     (2m23.113s 0m48.380s)                          
16. intdosx (dos.h.at:87): ok     (2m10.952s 0m43.439s)                         
17. _dos_close (dos.h.at:235): ok     (1m39.467s 0m34.006s)                     
18. _dos_getdrive, _getdrive (dos.h.at:254): ok     (1m37.838s 0m33.666s)       
19. _dos_getfileattr (dos.h.at:271): ok     (1m43.787s 0m35.366s)               
20. _dos_setfileattr (dos.h.at:326): ok     (1m42.497s 0m34.844s)               
21. _dos_allocmem, _dos_freemem (dos.h.at:377): ok     (0m43.968s 0m15.103s)    
22. _setvideomode (graph.h.at:19): ok     (0m29.972s 0m9.790s)                  
23. FP_SEG, FP_OFF (i86.h.at:19): ok     (1m39.502s 0m34.817s)                  
24. segread (i86.h.at:64): ok     (1m40.841s 0m34.431s)                         
25. int86 (i86.h.at:100): ok     (3m17.741s 1m8.909s)                           
26. int86x (i86.h.at:143): ok     (1m54.109s 0m39.738s)                         
27. intr (i86.h.at:243): ok     (1m53.568s 0m39.140s)                           
28. _disable, _enable (i86.h.at:320): ok     (1m39.860s 0m34.914s)              
29. _psp (stdlib.h.at:19): ok     (1m40.753s 0m34.715s)                         
30. _osmajor, _osminor (stdlib.h.at:38): ok     (1m37.749s 0m34.767s)           
31. _fmemcpy (string.h.at:19): ok     (0m58.762s 0m19.705s)                     
32. _fmemmove (string.h.at:67): ok     (0m29.326s 0m9.857s)                     
testsuite: ending at: Sat Sep 19 20:24:44 BST 2020                              
testsuite: test suite duration: 1h 17m 26s                                      
~~~

I don't see any single test longer than 3.5 minutes, so I wonder where the extra time was spent?

**Comment by andrewbird** [comment]
This seems okay to me now that https://github.com/tkchia/newlib-ia16/commit/851aecac20582ecdd3113ecadc7d378c6940609b was added, shall I close this?

**Comment by stsp** [comment]
Lets allow Bart to close this,
if he doesn't feel like having a
task-gate (or any other work-around)
would be good.
I personally don't care much, but
if it is not a big problem to implement...

**Comment by bartoldeman** [comment]
Using an IDT with only ring-0 entries (but DPL=3) is another solution -- this way int31 can exit KVM without needing to go through a GPF, and the stack from the TSS is used. However to keep the improved performance the ring-0 IDT handler then needs the table of DPMI-0x0205 hooked interrupts, so it's not a super-easy change.

**Comment by stsp** [comment]
> Using an IDT with only ring-0 entries (but DPL=3) is another solution

Then I don't see why we can't just
revert 99fa6f96e. It seems, we had
DPL=3 even before that patch.
I now think that the patch is misleading,
and doesn't do what was advertised:
`KVM: use DPL=3 for IDT even in non-debug default case` -
but DPL was 3 even before, its just
that RPL was 0.
Is this understanding correct?
If so - we can revert it (not doing
what is advertised, is a reason by
itself) and get DPL=3/RPL=0, which
seems to match what you suggested
above.

But I have to admit I only partially
understand your suggestion, and
judged that patch mostly by its log
entry.

**Comment by bartoldeman** [comment]
No before that patch we had DPL=0 for unhooked (default) int31 (the comment was a little out of sync before), and with DPL=RPL=0 there was a GPF.
Only hooked interrupts used DPL=RPL=3 for that short while.

**Comment by stsp** [comment]
But even before the patch we had:
`monitor->idt[i].DPL = (i == 3 || i == 4 || i > 0x10) ? 3 : 0;`
in `set_idt_default()`.
The patch started to use `set_idt()`
instead, which also has 3. No?

**Comment by stsp** [comment]
OK, I ended up reverting that patch.
It does the contrary to what was advertised.
We need DPL=3/RPL=0, which was,
in fact, before the patch - not after.

**Comment by stsp** [comment]
Andrew, what happens here?
https://travis-ci.com/github/dosemu2/dosemu2/builds/191313100

**Comment by andrewbird** [comment]
Just testing a tweak https://github.com/dosemu2/dosemu2/pull/1322
