### ISSUE TITLE
dosemu2 doesn't find vga11x19 font

### ISSUE THREAD

**Issue by bpranoto** [dosemu2/dosemu2#1285]
**Describe the bug**
I set in the dosemu.conf:
`$_X_font = "vga11x19"`

However, on calling dosemu, it complains:

```
You do not have the DOSEMU vga11x19 font installed and are running
remote X. You need to install the vga11x19 font on your _local_ Xserver.
Look at the readme for details. For now we start with the bitmapped
built-in font instead, which may be slower.

```

However, the font exists in /usr/share/fonts/X11/misc and output of xset q shows:

```
Font Path:
  /usr/share/fonts/X11/misc,/usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins

```
Misteriously, if I:
 uninstall dosemu2-legacy 
 install the old dosemu2 version, run it
 uninstall the oldversion
 reinstall dosemu2-legacy
 run dosemu2-legacy, the font is correctly loaded

But after reboot, it cannot find the font again 

**To Reproduce**
Reboot or relogin 
Set in the dosemu.conf  `$_X_font = "vga11x19"`
Run dosemu

**Attach the log**
Attached with -Dv

**A regression?**
Yes

[boot.log](https://github.com/dosemu2/dosemu2/files/5243895/boot.log)

**Comment by bpranoto** [comment]
The installation doesn't update /usr/share/fonts/X11/misc/fonts.alias
[fonts.alias.txt](https://github.com/dosemu2/dosemu2/files/5244145/fonts.alias.txt)

**Comment by stsp** [comment]
IIRC the alias name should match
package name, so can you try this:
```
diff --git a/debian/install b/debian/install
index 247dabe21..bfaa31062 100644
--- a/debian/install
+++ b/debian/install
@@ -1,2 +1,2 @@
 debian/dosemu.desktop usr/share/applications/
-etc/dosemu2.alias etc/X11/fonts/misc/
+etc/dosemu2.alias etc/X11/fonts/misc/dosemu2-legacy.alias
```

**Comment by andrewbird** [comment]
I'm just wondering why the package name needs to be different at all?

**Comment by stsp** [comment]
Just to make it obvious that this is
a reduced, unsupported build.
Its not "right" to say some ppl that
their build is unsupported, without
a clear indication (for them) that it
is actually the case and that they
could have deduced that on their
own.

**Comment by bpranoto** [comment]
> IIRC the alias name should match
> package name, so can you try this:

Doesn't work.

It creates /etc/X11/fonts/misc/dosemu2-legacy.alias/dosemu2.alias

But /usr/share/fonts/X11/misc/fonts.alias is still not updated.

**Comment by stsp** [comment]
Thanks for the check.
I suspected that the rename cannot
be done that way.
I created the branch "alias" I created
a symlink with the right name.
Could you please check if that works?

**Comment by bpranoto** [comment]
Yes, it works.

**Comment by stsp** [comment]
Thanks.
