### ISSUE TITLE
instremu.c overlapping assignments

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1289]
Coverity is complaining about overlapping target and source for an assignment, which I believe is because they are part of the same union. I've attached the screenshots from the tool. What's the correct fix here, to use an intermediate variable?
![362308](https://user-images.githubusercontent.com/220835/94298814-aba5cd00-ff5e-11ea-9aee-118c6a3e9752.png)
![362239](https://user-images.githubusercontent.com/220835/94298815-ac3e6380-ff5e-11ea-9762-44a4b6a360f4.png)

**Comment by stsp** [comment]
> What's the correct fix here, to use an intermediate variable?

Depends on level of "correctness". :)
But whatever fix you come up with,
I _think_ it should assign only AH,
not AX. So either an intermediate
var shifted right by 8 and assigned
to AH, or perhaps just implement
CBW literally:
`AH = (AL & 0x80) ? 0xff : 0;`
(I guess its the way it works)

**Comment by andrewbird** [comment]
I like your idea, but for CWDE I couldn't see if the upper word of eax is addressable via the union, so will something like this be okay?

```c
  case 0x98:                                                                    
    if (x86->operand_size == 2) { /* cbw */                                     
      AH = (AL & 0x80) ? 0xff : 0;                                              
    } else {                      /* cwde */                                    
      if (AX & 0x8000)                                                          
        x86->eax |= 0xffff0000;                                                 
      else                                                                      
        x86->eax &= 0x0000ffff;                                                 
    }                                                                           
    eip++; break;                                                               
```

Which seems to pass the cpu tests in the suite (but I'm not sure if we have good coverage)

**Comment by stsp** [comment]
Why not.
