### ISSUE TITLE
Support for OPL2LPT and OPL3LPT devices

### ISSUE THREAD

**Issue by volkertb** [dosemu2/dosemu2#1294]
It would be great if DOSEMU2 could support the [OPL2LPT](https://www.serdashop.com/OPL2LPT) and [OPL3LPT](https://www.serdashop.com/OPL3LPT) devices.

With "support", I mean the ability to present these devices to the DOS VM as actual OPL2 or OPL3 devices as part of the emulated Sound Blaster 16 (or Pro?), and passing the music through from the game in the VM to such a device on the parallel port of the host computer, instead of emulating these FM synthesizers in software.

This would bring with it several advantages:

- Not having to emulate FM synthesis in software saves quite a few CPU cycles, especially on slower host systems
- Nothing beats the actual synthesizer chips in terms of accuracy
- This would allow people to use these devices with protected mode games, which aren't supported by the [ADLiPT](https://github.com/pdewacht/adlipt) TSR.

For programming these devices in Linux, I think you can copy the code from the ScummVM project, specifically this source file:

https://github.com/scummvm/scummvm/blob/master/audio/opl2lpt.cpp

It's GPLv2 licensed, just like DOSEMU2, so that shouldn't be a problem, right? :slightly_smiling_face: 

Please note that in the case of the Sound Blaster, Sound Blaster Pro and Sound Blaster 16, the FM synthesizer should be accessible both through its Adlib-compatible I/O ports (base 388h) and its Sound Blaster specific ports (usually base 220h), in order to be fully compatible with all games. For a proper example on how to combine support for OPLxLPT devices with Sound Blaster emulation, see the adlipt source code at https://github.com/pdewacht/adlipt/tree/master/adlipt (appears to be released under the ISC license, which should be compatible with GPLv2)

You can also find some useful example code linked from the following blog post: https://vincent.bernat.ch/en/blog/2018-adlib-opl2lpt

I'm willing to order and donate an OPL3LPT to @stsp and/or @andrewbird if they are seriously willing to implement this, and don't have one yet. (The OPL3LPT is backward-compatible with the OPL2LPT.)

Also, perhaps we can ask @vincentbernat and/or @pdewacht if they're willing to help us out with this. :wink:

At any rate, thank you for considering this feature request.

**Comment by jschwartzenberg** [comment]
The would be neat! It's just that my box with a parallel port already has a Sound Blaster in it :)
How is the hardware support for these devices in ALSA? It would seem good to have a single abstraction layer that could work with all sorts of hardware OPL2/3 chips.



> Nothing beats the actual synthesizer chips in terms of accuracy

This is true. I think we should still strive to report concrete issues on differences in the emulation and the real chip, so that the emulation can become more accurate. Maybe support for real chips can help with comparing. The same stream could be sent to both the emulation and a real chip. Then the recordings could be compared in audio analysis tools.


> This would allow people to use these devices with protected mode games, which aren't supported by the [ADLiPT](https://github.com/pdewacht/adlipt) TSR.

Does the TSR work with the parallel port in DOSEMU2 redirected to the device?

**Comment by volkertb** [comment]
> The would be neat! It's just that my box with a parallel port already has a Sound Blaster in it :)
> How is the hardware support for these devices in ALSA? It would seem good to have a single abstraction layer that could work with all sorts of hardware OPL2/3 chips.

Interesting suggestion,  and ALSA indeed seems to support FM synthesizer chips on some sound cards. However, if I understand it correctly, ALSA exposes them as MIDI devices, which would imply some kind of generic MIDI-to-FM mapping. So you'd have to pick General MIDI or MT-32 support in the DOS game and then the MIDI instruments would be mapped to reasonably well matching FM timbres. That wouldn't sound even close to the native FM support in such games. Usually, when you have to map MIDI to FM, the quality is a lot less, since a lot gets "lost in translation". The FM synthesis support in the games was done by the original composers and the developers and they tuned and optimized it specifically for OPL2 and OPL3 synthesizers. Also, it wouldn't work at all with games that support only FM synthesis and no MPU-401 MIDI devices.

Basically, what @vincentbernat did, [when he implemented OPLxLPT support in ScummVM](https://github.com/scummvm/scummvm/pull/1137), was integrate a user-space driver in the application that would send the original FM commands to a physical parallel port on the host system, making use of the libieee1284 API to provide the necessary cross-platform abstraction. I believe that's the best way to go.

But now that you mention it, perhaps it would indeed not be a bad idea at all to define an API called `oplxapi` or something, which would provide the same interface as defined in `opl2lpt.cpp` in ScummVM, and then develop different implementations, including one for OPLxLPT, one for actual Sound cards with register-level Adlib/OPL2 or OPL3 compatibility, and several software emulators such as Nuked OPL3 (a high quality emulator, which is a bit CPU intensive), etc.

That would allow for a pluggable solution that would enable developers of [ScummVM](https://github.com/scummvm/scummvm), QEMU, DOSEMU2, [dosbox-staging](https://github.com/dosbox-staging/dosbox-staging) and what-have-you to only have to implement a single API.

Also, removing the OPLx software emulation from the application would perhaps allow the emulation to be handled more easily in separate threads as well, which would benefit host systems with multiple CPU cores.

> This is true. I think we should still strive to report concrete issues on differences in the emulation and the real chip, so that the emulation can become more accurate. Maybe support for real chips can help with comparing. The same stream could be sent to both the emulation and a real chip. Then the recordings could be compared in audio analysis tools.

That would indeed be possible. But there's no need to reinvent the wheel. There are several OPL2/OPL3 emulators out there already, notably the aforementioned Nuked OPL3. They vary in quality, but the choice between them provides for a nice trade-off between emulation accuracy and CPU utilization. Again, a single API would allow users to freely pick one, depending on their needs or preferences. See here for an extensive list: https://doomwiki.org/wiki/OPL_emulation
 
> Does the TSR work with the parallel port in DOSEMU2 redirected to the device?

I don't know. I don't have one yet myself to test :joy:. What I do know is that such a set-up is known to work in VirtualBox (passing the parallel port through from the host to the guest VM). [This thread](https://github.com/pdewacht/adlipt/issues/3) contains a link to a PDF file with instructions on how to set it up. However, the downside of this is that this would still require either loading the  ADLiPT TSR in the guest VM (which, as I mentioned in the OP, wouldn't work with protected mode games), or patching the games individually. Having the hypervisor perform the same hardware emulation instead would potentially allow it to work with any DOS game, whether real mode or protected mode, and without having to load any TSRs or patch anything.

**Comment by stsp** [comment]
> Also, removing the OPLx software emulation from the application would perhaps allow the emulation
> to be handled more easily in separate threads as well

We already have it in different threads
of course. No need to remove anything.

Anyway, I ported the scummvm impl
and put in a branch "lpt".
Since I don't have LPT or that device,
someone else have to test & fix bugs.
For now you need to manually set up
port name in `lpt2opl_init()` as
`config.opl2lpt_parport` is not initialized
yet. Once you get it working, I'll add
the config bit and merge to devel.

**Comment by volkertb** [comment]
Wow, that was quick! Thanks for acting on this so quickly! :hugs:

Should you be interested, my offer to fund an OPL3LPT device (as well as an LPT card if you need one) still stands. Do you have a PayPal address or something?

If you prefer that someone else tests this instead, I'd be happy to order one for myself and try this out.

Let me know.

**Comment by stsp** [comment]
I am not rejecting donations or
the like things, but it would really
be much quicker if you do the test.
The only thing needed is to specify
the port name manually in the code.
The rest should work as is, perhaps.

**Comment by vincentbernat** [comment]
I can test this week-end if it helps!

**Comment by stsp** [comment]
Of course it helps.
Perhaps also moving i/o to a separate
thread would be a good idea, because of
those usleeps.

**Comment by volkertb** [comment]
@vincentbernat Do you still have time to test this weekend? I'll order an OPL3LPT device for myself, but it will probably take some time to get here.

**Comment by vincentbernat** [comment]
I had some time to try. Documentation is a bit difficult. I don't know if I did things correctly.

```
PKG_CONFIG_PATH=$HOME/src/fdpp/build\~/target/lib/pkgconfig ../configure --enable-plugins=+ieee1284
make
```

Then, I have copied a FreeDOS installation in `etc/freedos`. I was able to run Indy3 with AdLib support (`indy3.exe a`) but it does use AdLib emulation. I suppose this is because the plugin is not initialized. When using `make install`, I don't get a `libplugin_ieee1284.so`, which may explain the issue. However, the plugin is compiled correctly.

**Comment by stsp** [comment]
It will use adlib emulation unless you
specify the proper lpt port name directly
in the file - so far I havent added an option.
The rest should work.

**Comment by stsp** [comment]
See the beginning of opl2lpt_init().
Patch in the name there and rebuild.

**Comment by vincentbernat** [comment]
OK, I was putting `/dev/parport0` instead of `parport0`. I had also to set `_type` to `Config_kOpl2`, so that's also something you want to add as a configuration file. Then, it works!

**Comment by vincentbernat** [comment]
Here is the result. There is a glitch toward the end because I put dosemu2 fullscreen:
[indy.mp3.gz](https://github.com/dosemu2/dosemu2/files/5322186/indy.mp3.gz)

**Comment by volkertb** [comment]
So cool to hear this working! :relaxed:

@vincentbernat I did notice the sound in your MP3 recording only coming from the left speaker. Not sure if that's because of how you recorded it?

**Comment by vincentbernat** [comment]
OPL2LPT. I didn't remember the sound wasn't replicated on both channels, but this is also the case with the test program. I may have done things differently in the past.

**Comment by volkertb** [comment]
Okay, thanks. I guess it would be a good idea to have someone with an OPL3LPT test this as well, before it gets merged.

Perhaps some people on VOGONS are willing to help test this.

**Comment by volkertb** [comment]
@vincentbernat In the meantime, if you have a little more time for this, could you please also test a game with Sound Blaster (both FM and DAC) support? To verify that the combination of FM (through the OPL2LPT device) and digital audio (through software emulation) also works properly? Just to be sure.

It's okay if you're out of time, though. I'm going to order an OPL3LPT to test this further myself.

Thanks again!

**Comment by vincentbernat** [comment]
I can test with the OPL3LPT as well. I have both.

**Comment by stsp** [comment]
Another interesting experiment might
be to off-load the SB's direct DAC access
to covox. dosemu2 is very good at emulating
the DMA audio, but SB also has direct
DAC control. You can see that with
Goblins2 game for example. Because
of the timing constraints, the emulation
is not very good, but with covox it could
be much better.

**Comment by stsp** [comment]
I added the config options and merged
to devel. Please make sure that things
work now as expected.

**Comment by volkertb** [comment]
Thanks. Yes @vincentbernat, if you can, please test with the OPL3LPT as well, with a Sound Blaster game with both FM and DAC output if you can, just to be sure. Thanks. :relaxed:

@stsp That's unexpected and ironic, that a more complex mechanism like DMA-driven audio emulation is actually easier to emulate properly than direct I/O-driven audio. :sweat_smile: I guess that's because in the former case, the game offloads the work to the emulated sound card (and thus to dosemu2) instead of bit-banging the I/O ports of the emulated sound card with very precise timings. 

But I love the idea! So if I understand correctly, basically you'd have a host PC with two parallel ports, with an OPLxLPT device plugged in one port, and a Covox Speech Thing plugged in the other, with dosemu2 emulating a Sound Blaster 16, sending the FM music to the OPLxLPT device and the direct I/O DAC output to the Covox Speech Thing? 

That would be pretty cool indeed. :slightly_smiling_face:

I see you haven't opened an issue for such a feature request yet, so I'll open one right away. :grin:

Thanks for implementing OPLxLPT support so quickly, by the way. Within less than a week after this issue was opened! :+1:

**Comment by stsp** [comment]
> I guess that's because in the former case, the game offloads the work to the emulated
> sound card (and thus to dosemu2) instead of bit-banging the I/O ports of the emulated
> sound card with very precise timings.

Yes, that's the big problem, but
looking at the code, I think dosemu2
makes things worse by trying to
"deduce" the SB DAC access frequency
(by doing the long-timed measurements)
and then resamples that to the output
frequency.
I am actually not sure why it is
doing that, I wrote that stuff 15 years
ago. Need to try without that resampling
heuristic.

> So if I understand correctly, basically you'd have a host PC with two parallel ports,

I'd just ask the 8bit guy to please
combine the opl3 with covox on the
same device, as LPT ports are
"precious" these days. But yeah,
2 ports for now I guess.

**Comment by volkertb** [comment]
Actually the 8-bit guy didn't develop the OPLxLPT devices. He just imports and resells them to US customers through his merch page. The one who developed these gadgets is a Belgian guy who goes by the nickname dreamblaster on VOGONS. He also developed some other cool retro stuff, such as Waveblaster daughterboards, etc. You can find the stuff he sells at https://www.serdashop.com

So that's the guy we'd have to convince to create such a variant.

Perhaps someone else could make some kind of multiplexer that you could plug both devices into, and which would switch between the two by pulling one of the control pins on the parallel port high or low. It would have to be a control pin not yet in use by the OPL3LPT, though.

The good news is that parallel port adapters (PCI, PCI Express, or ExpressCard) aren't that expensive and are easy to come by, so a modern PC could fairly easily be equipped with two such ports.

(For other people reading this: USB parallel port adapters aren't suitable for these devices and won't work.)

**Comment by stsp** [comment]
> (For other people reading this: USB parallel port adapters aren't suitable for these devices and won't work.)

None of them?
I actually thought some of them
do allow bit-banging.

**Comment by volkertb** [comment]
I believe the problem is that there is too much latency in USB adapters to get timing-critical stuff right, like driving a covox, or even an OPLxLPT. USB is serial after all, so there's always some serialization and deserialization going on, before the bytes get mapped to the pins.

**Comment by vincentbernat** [comment]
USB adapters are using the USB Printer Device Class. To my knowledge, none of them allow bit-banging.

**Comment by volkertb** [comment]
Do you think it would theoretically be possible to design one, though?

I mean a USB parallel port adapter that would support bit-banging, with low enough latency as to allow driving an OPLxLPT, or even a Covox Speech Thing at high mixing frequencies. Obviously, it would not use the USB Printer Device Class as an abstraction layer. And I guess it would probably have to be at least USB 2.0, right?

Here's a relevant discussion about USB 2.0 vs USB 3.0 w.r.t. latency, which mentions some numbers: https://stackoverflow.com/questions/13831008/what-is-the-minimum-latency-of-usb-3-0

**Comment by volkertb** [comment]
I found a few projects on-line to interface with a parallel port EPROM programmer using a microcontroller such as an Arduino or an AVR. I assume EPROM programmers that work on a parallel port require bit-banging too. Those microcontrollers can interface with a host PC through USB, so something like that could be rigged up for an OPLxLPT or a Covox Speech Thing as well. Still curious about the latency of such a solution, though.

**Comment by vincentbernat** [comment]
So, I have tested the version from devel with both OPL2LPT and OPL3LPT and it works for me. As for running a game supporting also Sound Blaster for PCM, I have tried with Doom, but even alone, I am not able to make it work with the OPL2LPT. I wanted to try a few other games but even the VGA version of Indy 3 is failing for me. I have tried Indy 4, Monkey Island 2. I have 531K of free conventional RAM, I think this should be enough but I am a bit rusty will all this.

**Comment by vincentbernat** [comment]
As for latency, USB is OK for most games. For example, I was able to make the OPL2 Audio Board with many games: https://vincent.bernat.ch/en/blog/2018-opl2-audio-board. Only Another World is failing but not only because of USB, but also because emulation timing is too simplified.

**Comment by volkertb** [comment]
Hmmm... :thinking: Doom should definitely have worked, since it's a protected mode game and doesn't require the maximum amount of conventional memory to work. Did you run the setup first? I don't think Doom auto-detects the Sound Blaster without you having to configure it first. The emulated Sound Blaster 16 should be configured with its typical values: base I/O port 220h, IRQ 5, DMA 1, high DMA 5.

Also, dosemu2 should properly set the BLASTER environment variable for you, but could you double-check by entering `echo %BLASTER%` on the DOS prompt?

That OPL2 Audio Board is a cool thing to play with. And cool how you added support for that board to DOSBox and ScummVM as well. I guess that could be ported to dosemu2 as well, for platforms that don't have a parallel port. :slightly_smiling_face: Is there an OPL3 variant of that board as well?

**Comment by stsp** [comment]
> Do you think it would theoretically be possible to design one, though?

I am sure it is entirely possible technically.
But it won't be covox, simply because
it will NOT use the standard LPT IO
ports. That would be just an audio
card, and a covox emulation in dosemu2
or another emulator. To make it use the
standard IO ports, you may need to
somehow customize the PC bios, to
add some kind of LPT to USB redirection,
the same way they do for PS/2.

**Comment by stsp** [comment]
> conventional RAM, I think this should be enough but I am a bit rusty will all this.

If even doom doesn't run then
your dosemu2 is misconfigured.
I would recommend to remove
~/.dosemu and try again. It will
re-create it with all the default
settings (unless you also altered
/etc/dosemu/dosemu.conf).

**Comment by vincentbernat** [comment]
Doom runs. The OPL2LPT doesn't work with it though (but emulation is OK). Monkey 2 gives just a black screen. Indy3 VGA complains about "out of heap memory". My Indy4 copy seems altered (MONSTER.SOU is missing), it doesn't work on DOSBox either. Flashback is far too slow. Day of the Tentacle doesn't work with OPL2LPT (even Sound Blaster sounds, even when disabling FX).

Maybe I have also something odd about my installation. I have copied a FreeDOS installation in `etc/freedos`, is that what I am expected to do?

**Comment by vincentbernat** [comment]
> Is there an OPL3 variant of that board as well?

No OPL3 variant. This seems quite a niche compared to the OPL2LPT/OPL3LPT.

**Comment by stsp** [comment]
> Maybe I have also something odd about my installation. I have copied a FreeDOS
> installation in etc/freedos, is that what I am expected to do?

No but that shouldn't matter.
dosemu2 simply doesn't look into
/etc/freedos, that's the first time I
hear about such location.
But no worries, as long as it simply
doesn't look there.
Let me see if I can find that
indy3 and try it myself.

**Comment by stsp** [comment]
Indina Jones the last crusade?
Seems can't be downloaded, needs
to be bought from GoG...

**Comment by stsp** [comment]
https://www.dosgamesarchive.com/file/indiana-jones-and-the-last-crusade-the-graphic-adventure/lastcrus/
This one?
But it has indy.exe, not indy3.exe...

**Comment by stsp** [comment]
Anyway, the default dosemu2 setup
should have that amount of memory:
```
C:\>mem
 
Memory Type        Total       Used       Free
----------------  --------   --------   --------
Conventional          640K        12K       628K
Upper                 164K        42K       122K
Reserved              220K       220K         0K
Extended (XMS)      8,256K        64K     8,192K
----------------  --------   --------   --------
Total memory        9,280K       338K     8,942K
 
Total under 1 MB      804K        54K       750K
 
Total Expanded (EMS)                8,576K (8,781,824 bytes)
Free Expanded (EMS)                 8,128K (8,323,072 bytes)
 
Largest executable program size       628K (642,608 bytes)
Largest free upper memory block        72K ( 73,792 bytes)
FreeDOS is resident in the high memory area. 
```

You definitely messed something up.

**Comment by vincentbernat** [comment]
Well, I did get that from `strace`, so it definitely looks there. Otherwise, it is looking for a `command.com` I don't have. That's why I think I didn't understand something important!

There are several versions of Indy3: CGA/EGA (the one I am able to make it work) with INDY3.EXE, VGA with INDY256.EXE and an FM Town version with OGG music (and not running on DOS I think, I don't have an executable). Grab it from here: https://media.luffy.cx/files/indy3.zip (I'll remove the files in a few hours).

**Comment by stsp** [comment]
Yes, I confirm that Indy3 complains
about out of memory, no matter how
many memory you have.
And "last cruside" needs loadfix to
start under dosemu2.

**Comment by stsp** [comment]
But days of the tentacle works
perfectly for me with sound and
music.

**Comment by stsp** [comment]
> Monkey 2 gives just a black screen.

I downloaded one from here:
https://www.old-games.ru/game/download/504.html
(Full-Rip), and it works for me.

> Indy3 VGA complains about "out of heap memory".

This is finally fixed.
