### ISSUE TITLE
Some (minor) issues in int 0x13 error code handling

### ISSUE THREAD

**Issue by tkchia** [dosemu2/dosemu2#1295]
**Describe the bug**
There are some issues with the returning of error codes by the BIOS disk service interrupt `int 0x13`, under `dosemu2` version https://github.com/dosemu2/dosemu2/commit/ac3a40839f15b978affc1bad5f940c9c9b9075b1 :
  * `int 0x13` with `ah = 1` (get status of last operation) does not correctly track and return the result of the last `int 0x13` operation.  Neither do the BIOS data area variables at `0x40:0x41` (last operation status for diskettes) and `0x40:0x74` (last operation status for fixed disks).
  * For some reason, some `int 0x13` operations return their statuses in `al` rather than `ah`.

These can probably be considered as minor issues, since most programs only check the returned carry flag from `int 0x13`, and do not use `ah = 1`.  But it will be nice if these problems can be fixed.

**To Reproduce**
Assemble the following `.com` program with `nasm` and run it:
```
	[org	0x100]

	xor	cx,cx
	mov	ds,cx
	;
	mov	ah,0
	mov	dl,0
	int	0x13
	cmp	[0x0441],ah
	jnz	bad
	mov	ah,1
	mov	dl,0
	int	0x13
	cmp	[0x0441],ah
	jnz	bad
	;
	mov	ax,0x0201
	mov	bx,buf
	mov	cx,0xffff
	mov	dx,0x0000
	int	0x13
	cmp	[0x0441],ah
	jnz	bad
	mov	ah,1
	mov	dl,0
	int	0x13
	cmp	[0x0441],ah
	jnz	bad
	;
	mov	ah,0
	mov	dl,0x40
	int	0x13
	cmp	[0x0441],ah
	jnz	bad
	mov	ah,1
	mov	dl,0x40
	int	0x13
	cmp	[0x0441],ah
	jnz	bad
	;
	mov	ah,0
	mov	dl,0x80
	int	0x13
	cmp	[0x0474],ah
	jnz	bad
	mov	ah,1
	mov	dl,0x80
	int	0x13
	cmp	[0x0474],ah
	jnz	bad
	;
	mov	ax,0x0201
	mov	bx,buf
	mov	cx,0xffff
	mov	dx,0x0080
	int	0x13
	cmp	[0x0474],ah
	jnz	bad
	mov	ah,1
	mov	dl,0x80
	int	0x13
	cmp	[0x0474],ah
	jnz	bad
	;
	mov	ah,0
	mov	dl,0xc0
	int	0x13
	cmp	[0x0474],ah
	jnz	bad
	mov	ah,1
	mov	dl,0xc0
	int	0x13
	cmp	[0x0474],ah
	jnz	bad
	;
	mov	ax,0x4c00
	int	0x21
	;
bad:	mov	al,'!'
	int	0x29
	mov	ax,0x4cff
	int	0x21

buf:
```
The program will display `!` indicating an incorrect result (it should display nothing).

**Attach program/game binaries or provide an URL**
n.a.

**Attach the log**
n.a.

**A regression?**
n.a.

**Additional info**
n.a.

**Comment by stsp** [comment]
I did a blind fix, please test if its ok.

**Comment by tkchia** [comment]
Hello @stsp,

Thanks --- the fix is incomplete though.  I have proposed an additional patch to fix the problems more completely.

Thank you!
