### ISSUE TITLE
LFNs aren't returned from MFS on VFAT 

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1296]
**Describe the bug**
If a VFAT image, partition, or disk is mounted under Linux and lredir makes it available for use in Dosemu, its filesystem filenames are supposed to be passed through to DOS. After fixing an issue with IOCTL in #1293, it can be seen that the filenames returned from lfn.c are the short names in the LFN calls.

~~~
root@polly:~# mount
/img/dosemu.img on /mnt/dosemu type vfat (rw,noexec,relatime,uid=500,gid=500,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=win95,errors=remount-ro)

root@polly:~# ls -l /mnt/dosemu/
total 1
-rwxr-xr-x 1 ajb sphere 6 Sep 30 12:06 AndrewBird2.Txt
-rwxr-xr-x 1 ajb sphere 0 Sep 30 12:05 AndrewBird.Txt
~~~

~~~
C:\>lredir X: LINUX\FS\mnt\dosemu
X: = \\LINUX\FS\MNT\DOSEMU attrib = READ/WRITE
C:\>lredir
Current Drive Redirections:
C: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\c\ attrib = READ/WRITE
D: = \\LINUX\FS\clients\common\dosemu2.git\commands\ attrib = READ/WRITE
E: = \\LINUX\FS\clients\common\fdpp.git\fdpp\ attrib = READ/WRITE
F: = \\LINUX\FS\usr\share\comcom32\ attrib = READ/WRITE
X: = \\LINUX\FS\mnt\dosemu\ attrib = READ/WRITE
C:\>rem end
C:\>dir x: /lfn
 Volume in drive X is  MNT DOSEMU
 Directory of X:\
 
ANDREW~1 TXT             0  09-30-20 12:05p ANDREW~1.TXT
ANDREW~2 TXT             6  09-30-20 12:06p ANDREW~2.TXT
         2 file(s)              6 bytes
         0 dir(s)       1,457,152 bytes free
~~~

**To Reproduce**
1/ create a VFAT disk image under linux using `mkfs -t vfat`
2/ mount it under linux `mount -t vfat`
3/ copy some long filenames to it from linux
4/ configure Dosemu to allow lredir of the mounted image
5/ lredir the directory
6/ Using freecom with /lfn option list the drive.
7/ See that the LFNs are actually copies of the SFNs

**A regression?**
I'm sure this once worked, but it's unknown when it stopped working

**Additional info**
Tested with FDPP, and FreeCOM (from FreeDOS 1.20)

**Comment by bartoldeman** [comment]
I'll check what happens here later today ...

**Comment by andrewbird** [comment]
Interestingly I've just written a test that uses DJGPP's findfirst and it returns both SFNs and LFNs correctly as required. So I wonder what Freecom's DIR /LFN is doing differently?

**Comment by andrewbird** [comment]
Just so you can see what's happening
~~~
Current Drive Redirections:
C: = \\LINUX\FS\clients\common\dosemu2.git\test-imagedir\dXXXXs\c\ attrib = READ/WRITE
D: = \\LINUX\FS\clients\common\dosemu2.git\commands\ attrib = READ/WRITE
E: = \\LINUX\FS\clients\common\fdpp.git\fdpp\ attrib = READ/WRITE
F: = \\LINUX\FS\usr\share\comcom32\ attrib = READ/WRITE
X: = \\LINUX\FS\mnt\dosemu\ attrib = READ/WRITE
C:\>x:
X:\>c:\mfsfind
         4 18:36:10 10/01/2020 verylongfilename.txt
         5 18:36:10 10/01/2020 verylongfilename2.txt
         5 18:36:10 10/01/2020 space embedded filename.txt
         7 18:36:10 10/01/2020 MixedCaseFilename.ext
X:\>rem end
X:\>dir /lfn
 Volume in drive X is  MNT DOSEMU
 Directory of X:\
 
VERYLO~1 TXT             4  10-01-20  6:36p VERYLO~1.TXT
VERYLO~2 TXT             5  10-01-20  6:36p VERYLO~2.TXT
SPACEE~1 TXT             5  10-01-20  6:36p SPACEE~1.TXT
MIXEDC~1 EXT             7  10-01-20  6:36p MIXEDC~1.EXT
         4 file(s)             21 bytes
         0 dir(s)       1,455,616 bytes free

X:\>ver /r
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
DOS version 5.0
FDPP kernel 1.0final [GIT: 1.0] (compiled Aug 30 2020) 
~~~

**Comment by andrewbird** [comment]
Nope latest git of freecom doesn't change anything.
~~~
X:\>c:\mfsfind
         4 18:36:10 10/01/2020 verylongfilename.txt
         5 18:36:10 10/01/2020 verylongfilename2.txt
         5 18:36:10 10/01/2020 space embedded filename.txt
         7 18:36:10 10/01/2020 MixedCaseFilename.ext
X:\>rem end
X:\>dir /lfn
 Volume in drive X is  MNT DOSEMU
 Directory of X:\
 
VERYLO~1 TXT             4  10-01-20  6:36p VERYLO~1.TXT
VERYLO~2 TXT             5  10-01-20  6:36p VERYLO~2.TXT
SPACEE~1 TXT             5  10-01-20  6:36p SPACEE~1.TXT
MIXEDC~1 EXT             7  10-01-20  6:36p MIXEDC~1.EXT
         4 file(s)             21 bytes
         0 dir(s)       1,455,616 bytes free
X:\>ver/r
 
FreeCom version 0.84-pre7 - GNUC - XMS_Swap [Oct  1 2020 19:01:10]
DOS version 5.0
FDPP kernel 1.0final [GIT: 1.0] (compiled Aug 30 2020)   
~~~

**Comment by andrewbird** [comment]
I think the problem lies with truename
##### c:\ (ext4)
~~~
C:\>truename c:\veryl~3g.txt
C:\verylongfilename.txt
~~~

##### x:\ (vfat)
~~~
X:\>truename VERYLO~1.TXT
X:\VERYLO~1.TXT
~~~

**Comment by stuaxo** [comment]
It would be nice to know why they changed CH to 0x80 in these patches.

**Comment by andrewbird** [comment]
RBIL suggests it's to support SUBST https://fd.lod.bz/rbil/interrup/dos_kernel/217160cl02.html

**Comment by stsp** [comment]
Is this fixed?

**Comment by andrewbird** [comment]
Can't remember what the problem is, but I'm pretty sure I'll have to look over it again as after all the mfs changes in lock it'll definitely need a rebase at the minimum.

**Comment by andrewbird** [comment]
Interestingly on linux mounted vfat the attributes are exposed to the user, which might also be useful?
```c
#include <inttypes.h>
#include <sys/ioctl.h>
#include <linux/msdos_fs.h>

int fd = open("/mnt/fat/...", ...);
__u32 attrs;
ioctl(fd, FAT_IOCTL_GET_ATTRIBUTES, &attrs);
attrs = ATTR_NONE;  /* ATTR_{RO,HIDDEN,SYS,VOLUME,DIR,ARCH} */
ioctl(fd, FAT_IOCTL_SET_ATTRIBUTES, &attrs);
```

**Comment by stsp** [comment]
This is exactly what current vfat
code in mfs already does.

**Comment by andrewbird** [comment]
I hadn't looked, I just assumed it only dealt with unix perms :-), so nothing to do there then!

**Comment by mcericdos** [comment]
dosemu2-2.0pre8 revision 6157 seems to have the same issue, as visible with DIR /LFN in FreeDOS:

G:\DJGPP\BIN when DJGPP is a symlink from the Linux directory posing as G: to a directory on a FAT drive:

```
GCOV-D~1 EXE     1.638.912  13.04.20  6:32 GCOV-D~1.EXE
GCOV-T~1 EXE     1.661.440  13.04.20  6:32 GCOV-T~1.EXE
```

The same, now using a copy of the DJGPP directory from the same FAT drive to my non-FAT Linux directory:

```
GCOV-~3G EXE     1.638.912  13.04.20  6:32 gcov-dump.exe
GCOV-~!X EXE     1.661.440  13.04.20  6:32 gcov-tool.exe
```

**Comment by stsp** [comment]
It seems Andrew has patches in
his local branch. They are listed
here in this ticket.

**Comment by andrewbird** [comment]
Have rebased them now to current HEAD, but no time to test (as they might not even compile) until tomorrow.

**Comment by andrewbird** [comment]
I added a draft PR #1494
