### ISSUE TITLE
kvm: 32rtm crashes dosemu2

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1297]
**Describe the bug**
ERROR: KVM: exit_reason = 0x6

**To Reproduce**
Run 32rtm

**Comment by stsp** [comment]
Bart, would you like to take a look?

**Comment by bartoldeman** [comment]
ok

**Comment by Baron-von-Riedesel** [comment]
This "exit_reason 6"-error also appears whenever I start a hx extended binary in dosemu2.

**Comment by stsp** [comment]
This is very bad, but for now you can set
$_cpu_vm_dpmi = "native"

**Comment by Baron-von-Riedesel** [comment]
I already did this in /etc/dosemu/dosemu.conf, but had no effect ( there's no ~/.dosemurc ).

**Comment by stsp** [comment]
Maybe its a different bug.
Maybe you forgot to uncomment.
Please attach the -D9+M log.

**Comment by stsp** [comment]
Also check for ~/.dosemu/.dosemurc

**Comment by Baron-von-Riedesel** [comment]
Sorry, my last comment was premature. I did edit /etc/dosemu/dosemu.conf, but forgot to remove the '#'

**Comment by stsp** [comment]
I applied a patch that makes things
slightly better. I wonder if it helps in
your case or not.

**Comment by stsp** [comment]
> This "exit_reason 6"-error also appears whenever I start a hx extended binary in dosemu2.

I committed the first batch of fixes for this.
Could you please check?

**Comment by stsp** [comment]
Hmm, running quake2 with HX I am
getting "Couldn't load pics/colormap.pcx".
I think it used to work in the past...

**Comment by stsp** [comment]
@Baron-von-Riedesel where can I get
the version of dummy hx winsock that doesn't
hang? I think you mentioned you have one
somewhere.

**Comment by stsp** [comment]
Found it in hxrt219 which seems to be
deleted everywhere, but still possible to
find via google. :)

**Comment by ecm-pushbx** [comment]
https://github.com/Baron-von-Riedesel/HX/releases/tag/v2.19pre5 ?

**Comment by stsp** [comment]
Indeed. :)

**Comment by j2969719** [comment]
sdltest from hx sometime still crashes dosemu
```
ERROR: Fault in dosemu code, in_dpmi=1
ERROR: cpu exception in dosemu code outside of DPMI client!
sig: 11 trapno: 0x0e  errorcode: 0x00000004  cr2: 0x40d831fb
eip: 0x7f20b90a529b  esp: 0x7f206081fc58  eflags: 0x00010287
cs: 0x0033  ds: 0x0000  es: 0x0000  ss: 0x002b
fs: 0x0000  gs: 0x0000
fsbase: 0x7f20b8ff7740 gsbase: (nil)  
```

**Comment by stsp** [comment]
Please open another ticket.
Pretty much everything seems to crash
these days...
