### ISSUE TITLE
kvm: random KVM_EXIT_FAIL_ENTRY problem

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1306]
**Describe the bug**
Random kvm related failure occurs approximately 2 times in 10 attempts

`ERROR: KVM_EXIT_FAIL_ENTRY: hardware_entry_failure_reason = 0x80000021`

**To Reproduce**
Run this test from the suite
`python3 test/test_dos.py PPDOSGITTestCase.test_memory_dpmi_japheth_r`

**Attach the log**
[t1.tar.gz](https://github.com/dosemu2/dosemu2/files/5341965/t1.tar.gz)

Would you like me to add some extra debug flags?

**A regression?**
I didn't ever see it on Ubuntu 18.04 (x86_64) but since an upgrade of same machine to Ubuntu 20.04 it occurs

**Additional info**
~~~
ajb@polly:/clients/common/dosemu2.git$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping	: 11
microcode	: 0xba
cpu MHz		: 1600.118
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4800.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
~~~

~~~
ajb@polly:/clients/common/dosemu2.git$ uname -a
Linux polly 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
~~~

**Comment by stsp** [comment]
Should wait for #1274 to settle.

**Comment by stsp** [comment]
This test requires some VARIOUS.tar.
Where can I get one?

**Comment by andrewbird** [comment]
http://www.spheresystems.co.uk/test-binaries/VARIOUS.tar see travis_test.sh for hints.

**Comment by stsp** [comment]
I can't reproduce.
Could you please re-check?

**Comment by andrewbird** [comment]
I retested 20 times with latest devel and no failures. This a 'living' system that gets updated often, so it's possible that some kernel update fixed it. Anyway it looks like it's no longer a problem, thanks! I'll close it, we can always reopen if it reoccurs.
