### ISSUE TITLE
Version upgraded 10/7/20 on Ubuntu Focal 20.04 and is unstable.

### ISSUE THREAD

**Issue by erlrodd** [dosemu2/dosemu2#1307]
**Describe the bug**
When the old "dosemu" package disappeared from Ubuntu Focal, I downloaded dosemu2. 2.0-pre8

On Oct 7, 2020, a regular Ubuntu update put in a new version. After this, DOSEMU2 has been unstable.
There are a variety of symptoms. The worst instability is with the -E option. From messages it almost appears that sometimes
the command specified with -E runs at different points in the dosemu startup.

However, the most consistent is a with DIR.
With C: mapped  to LINUX\FS\DOSC (/dosc is a directory on the main Linux ext4 drive).
  a DIR C:
  will sometimes work once, then hang when done again. The only way to get out of the hang is to "x" the window.

(Note: Even before today, DIR does not work. a DIR * will show a file, but a DIR filename says file does not exist.
I suspect this has to do with lredir?)

**To Reproduce**
Start dosemu.
lredir C: LINUX\FS\DOSC
dir (one or more times)

[boot.log](https://github.com/dosemu2/dosemu2/files/5344507/boot.log)
[boot.log](https://github.com/dosemu2/dosemu2/files/5344513/boot.log)

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.

**A regression?**
If you happened to know this problem didn't
exist on dosemu1 or some earlier versions of
dosemu2, please write.

**Additional info**
Please write here if you did any dosemu2 setup
customizations, like installing any custom DOS
or command.com, or altering the dosemu2
configuration settings. Note that freedos, even
from dosemu-freedos package of dosemu1, counts
as a custom DOS and should be mentioned here.
Also make a note if it is a protected or real-mode
program. If you suspect any particular dosemu2
component (DPMI, PIC, PIT etc) to be responsible
for the problem, please write.
FDPP kernel 1.0final [GIT: ] (compiled Oct  3 2020)
fdpp: plugin loaded
CONF: Parsing built-in dosemu.conf file.
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Disabling use of pentium timer
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: JIT CPUEMU set to 0 for 586
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x20000)
CONF: DPMI linear reserve base addr = 0xffffffff
CONF: DPMI linear reserve size = 0x8000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
default_drives 0
Setting up drive C, ~/.dosemu/drive_c
Creating default drive C
Added drive 0 (80): ~/.dosemu/drive_c
default_drives 1
Added drive 1 (81): /usr/share/dosemu/dosemu2-cmds-0.3
Setting up default drives from E
Added drive 2 (82): /usr/share/fdpp
Added drive 3 (83): /usr/share/comcom32
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 disabled.
CONF: config variable c_system unset
Linux kernel 5.4.0; CPU speed is 1077040000 Hz
CPU-EMU speed is 1077 MHz
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
DBG_FD already set
DOSEMU-2.0pre8 is coming up on Linux version 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64
Compiled with gcc version 9.3.0 64bit
CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wno-string-plus-int -Wno-address-of-packed-member -fplan9-extensions -Wno-maybe-uninitialized -fpie -ggdb3 -g -O2 -fdebug-prefix-map=/build/dosemu2-HIgsOM/dosemu2-2.0~pre8-6470=. -fstack-protector-strong -Wformat -Werror=format-security
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 8Kb at 0xFC000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0246
initial segment bases: fs: 0x7fa712ff0740  gs: (nil)
ERROR: KVM: error opening /dev/kvm: No such file or directory
KVM not available: No such file or directory
using CPU emulation for vm86()
VID: initializing SDL plugin
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Conventional memory mapped from 0x7fa700510000 to 0x41ef0000
DPMI memory mapped to 0x42000000 (reserve) and to 0x44000000 (main)
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
VID: initializing video sdl
VID: SDL plugin initialization completed
Registering HWRAM, type=e base=0x408f9000 size=0x400000
CONF: reserving 4096Kb at 0x408F9000 for 'e' (VGAEMU LFB)
loading fonts for cp437
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
SERIAL $Id$
Your fluidsynth is too old
DPMI: mem init, mpool is 136273920 bytes at 0x44000000
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============

CONF: freeing region for 'E' (EMS page frame)
booting with comcom32
config.boot_dos set to 20000
config.int_hooks set to 0
config.force_revect set to 0
CONF: reserving 116Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 48Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)

**Comment by stsp** [comment]
> (Note: Even before today, DIR does not work. a DIR * will show a file, but a DIR filename says file does not exist.

Counted.

> will sometimes work once, then hang when done again.

This probably have something to do
with the content of your C: as I can't
reproduce. See if DIR in other directories
also hang.

The rest I don't understand, please
provide screen-shots.

**Comment by andrewbird** [comment]
I notice kvm is not working, I wonder why? Processor type, VT not enabled in BIOS, or some other reason? Also add `-D+d` when you generate logfiles as it will add debug logging to the filesystem operations and give some clues about what is going wrong.

**Comment by erlrodd** [comment]
When I enabled virtualization in BIOS, the whole issue of hanging went away. I did not know about KVM. A little research told me to how to tell it was not turned on and to turn it on in BIOS.
There remains the strange DIR behavior:
F:
DIR (shows 2 files)
DIR command.com  (says does not exist)
Screen shot:
![dosemuscreen](https://user-images.githubusercontent.com/72529818/95442401-53d96f80-0929-11eb-935e-2453660eca35.png)

**Comment by andrewbird** [comment]
I can reproduce with comcom32, but with FreeCOM it's fine
~~~
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
DOS version 5.0
FDPP kernel 1.0final [GIT: 1.0] (compiled Oct  5 2020)
C:\>f:
F:\>dir
 Volume in drive F is RE COMCOM32
 Directory of F:\
 
COMMAND  COM       187,904  09-26-20  2:32a
COMCOM32 EXE       187,904  09-26-20  2:32a
         2 file(s)        375,808 bytes
         0 dir(s)     17,466 Mega bytes free
F:\>dir command.com
 Volume in drive F is RE COMCOM32
 
 Directory of F:\
 
COMMAND  COM       187,904  09-26-20  2:32a
         1 file(s)        187,904 bytes
         0 dir(s)     17,466 Mega bytes free
~~~

**Comment by andrewbird** [comment]
So the `dir` part of this ticket seems to be a comcom32 problem with it assuming the argument is a directory. In this test the file is called `command.off` and does exist on the `c:` drive
~~~
C:\>dir command.off
 Volume in drive c is IR DXXXXS C
 Directory of c:\command.off\
 
File not found
~~~

The instability part of this ticket looks to be to do with CPU emulation, or at the very least only visible without kvm enabled.

**Comment by stsp** [comment]
Andrew, I counted that problem already
in https://github.com/dosemu2/dosemu2/issues/1307#issuecomment-705252164
Its a comcom32 problem of course, but
do we have a regression in DPMI-JIT or not?
This is what will now be unclear, as you switched
the poor guy to KVM. :)

**Comment by andrewbird** [comment]
> This is what will now be unclear, as you switched
the poor guy to KVM. :)

Yes true, but until I did we didn't know where the instability wasn't. He can always set the ` $_cpu_emu` options to switch over for testing now.

**Comment by stsp** [comment]
@erlrodd could you please set
$_cpu_vm = "emulated"
and see if that gets the instability back?
If not, please set also
$_cpu_vm_dpmi = "emulated"
and see again.
This will help us to isolate the instability
more precisely.
As soon as it is back, please make
a screen-shot of what is
"From messages it almost appears that sometimes
the command specified with -E runs at different points in the dosemu startup."
as I have no idea what does this mean.

**Comment by stsp** [comment]
I fixed the breakage with cpu-emu
and filled ticket
https://github.com/dosemu2/comcom32/issues/43
about the DIR <filename> problem.
