### ISSUE TITLE
FreeDOS kernel 2042: "redirecting ... failed (err = 15)" and "ERROR: Cannot find a drive"

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1311]
**Describe the bug**

After pulling dosemu2 and fdpp today, and running `./configure` then `make` then `sudo make install` for fdpp, then `make clean`, `./default-configure -d`, `make`, `sudo make install` for dosemu2, now redirecting a G: drive with the -K option does not work any longer.

**To Reproduce**

```
$ echo -ne "@echo off\r\necho TEST\r\n" > test.bat
$ dosemu -dumb -K "$PWD" -E "test.bat"
dosemu2 2.0pre8-20201012-2402-gd7c9be2c8 Configured: 2020-10-13 15:14:45 +0200
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

FreeDOS kernel 2042 (build 2042 OEM:0xfd) [compiled May 11 2016]
Kernel compatibility 7.10 - WATCOMC - FAT32 support

(C) Copyright 1995-2012 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
ERROR: INT21: redirecting /home/test/20201013 failed (err = 15)                
                                                               EMUFS host file and print access available
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.8 installed.
dosemu CDROM driver installed (V0.2)
Kernel: allocated 45 Diskbuffers = 23940 Bytes in HMA
ERROR: INT21: redirecting /home/test/20201013 failed (err = 15)
                                                               emufs: redirector enabled
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre8-20201012-2402-gd7c9be2c8
ERROR: Cannot find a drive
C:\>exitemu
$ 
```

**Attach program/game binaries or provide an URL**

Using the kernel 2042 build from http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/dos/kernel/2042/ (ke2042_86f32.zip)

**Attach the log**

[boot.log](https://github.com/dosemu2/dosemu2/files/5371729/boot.log)

**A regression?**

Yes, but do not have handy which revision of dosemu2 I used previously to this. (git pull said `Updating 3d204bced..d7c9be2c8` so it was probably at 3d204bcedd4fe3a6c1357f422c3b8ac0529b0309 of 2020-06-09.)

**Additional info**

This is in the file ~/.dosemu/drive_c/fdconfig.sys:

```
rem config.sys for DOSEMU + FreeDOS
SWITCHES=/F
DOS=UMB,HIGH
dosdata=umb
lastdrive=Z
files=40
stacks=0
buffers=10
device=d:\dosemu\emufs.sys /all
device=d:\dosemu\umb.sys
devicehigh=d:\dosemu\ems.sys
devicehigh=d:\dosemu\cdrom.sys
install=d:\dosemu\emufs.com
shellhigh=command.com /e:1024 /k d:\fdautoem.bat
```

**Comment by ecm-pushbx** [comment]
I just edited out the "/all" switch on emufs.sys loading in the fdconfig.sys (added that in an attempt to help it along) and the result is almost exactly the same, but the "ERROR: INT21: redirecting ... failed" message only occurs once now.

**Comment by stsp** [comment]
Yes, /all is not for freedos.
Its for dr-dos and fdpp.
As for why redirection doesn't work
with freedos - only @andrewbird knows. :)
I think you need to build freedos from
git, but I also think that freedos kernel
from 1.2 distribution works too?

We need to document that "secret knowledge"
somewhere.

**Comment by andrewbird** [comment]
Redirection doesn't work for freedos 1.20 when it needs to create a new drive, but overlaying a fatfs drive is okay. This is because the int2f/1217 workaround was removed. With freedos current git it should be okay creating new drives too.

**Comment by ecm-pushbx** [comment]
Can you upload a release archive with the compiled kernel that's new enough, please? As noted in https://github.com/FDOS/kernel/issues/26 FreeDOS doesn't currently provide any such.

**Comment by stsp** [comment]
[kernel.sys.gz](https://github.com/dosemu2/dosemu2/files/5377490/kernel.sys.gz)
Try this one.
Not sure how recent is it, but
redirections seem to work.

**Comment by andrewbird** [comment]
Just in case that doesn't suit you for some reason, here's the Watcom compiled kernel from current git (completely untested) 
[watcom.tar.gz](https://github.com/dosemu2/dosemu2/files/5377586/watcom.tar.gz)
