### ISSUE TITLE
Regression: commands do not work with fdtarball

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1315]
**Describe the bug**

I believe commit 121f3d066508223cac7c2a0e63562d2c579693b9 broke the fdtarball configure option.

I had a previously working checkout of dosemu2 using these configure options:

```
./configure --prefix=${HOME}/dosemu --enable-plugins=term,charsets,dosdrv,doscmd,periph --disable-fdpp --with-fdtarball=dosemu-freedos-1.0-bin.tgz
```

That would produce a working dosemu2 installation. After 121f3d066508223cac7c2a0e63562d2c579693b9 , it no longer works. I've verified that one commit before (i.e. `git checkout 121f3d066508223cac7c2a0e63562d2c579693b9^`) works again

**To Reproduce**
Steps to reproduce the behaviour:

- Download freedos for [tarball](http://prdownloads.sourceforge.net/dosemu/dosemu-freedos-1.0-bin.tgz?download)

**Comment by stsp** [comment]
Could you please fill in the info?
What is "no longer works" and "works again"?
Why in "steps to reproduce" I need to
download it? Well, it downloads fine, so
steps work.

**Comment by taviso** [comment]
Well, download and then run the command listed.

The type `make` then `make install`.

When you run `dosemu -term`, you don't get a command prompt.

Before that commit, you did get a working command prompt.

**Comment by taviso** [comment]
I think it doesn't matter what plugins you select, those are just the ones I used for testing.

**Comment by stsp** [comment]
> Now run ${HOME}/dosemu/bin/dosemu -term

Why?
Please run `dosemu` instead.
AKA /usr/local/bin/dosemu

**Comment by taviso** [comment]
???

The reason is because I didn't think you would want to overwrite your current installation while testing. If you don't care, then fine here are updated instructions:

- Download the freedos tarball, and place it in the root of your dosemu2 source tree.
- `./autogen.sh`
- `./configure --enable-plugins=term,charsets,dosdrv,doscmd,periph --disable-fdpp --with-fdtarball=dosemu-freedos-1.0-bin.tgz`
- `make`
- `make install`

Now run `dosemu -term`, you should get errors about missing commands, and no commands work - e.g. exitemu, system, unix, etc.

The rest of the instructions are the same.

**Comment by taviso** [comment]
Pretty frustrating that this was just closed after I spent a few hours bisecting out the exact commit that broke the build.

I think perhaps you must have misread the instructions and assumed `${HOME}/dosemu` is my source tree.

**Comment by stsp** [comment]
Yes, I havent noticed the prefix, but
otherwise things work fine for me.
So it fails to find commands and not
freedos? Please post what path does
it say "not found".

**Comment by stsp** [comment]
Initially you said command prompt does
not appear, but now you edited it out.
Of course you realize commands have
nothing to do with fdtarball.
Ok, will re-check about commands.

**Comment by stsp** [comment]
Yes, there is a problem with commands.

**Comment by stsp** [comment]
Should now be fixed.
I think it have actually regressed by e63e83387,
not 121f3d0, but these commets are very close
to each other anyway.
