### ISSUE TITLE
fdppauto.bat produces bad %PATH% on FreeCOM

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1316]
**Describe the bug**

The default `fdppauto.bat` contains these lines:

```bat
path %DOSEMUDRV%:\dosemu;
if not "%SHELLDRV%" == "" path %PATH%%SHELLDRV%:\;
if not "%FREEDOSDRV%" == "" path %PATH%%FREEDOSDRV%:\bin;%FREEDOSDRV%:\gnu;
if not "%USERDRV%" == "" set TEMP=%USERDRV%:\tmp
```

FreeCom discards trailing semicolons, so this doesn't make a working path.

```
C:\>ver
FreeCom version 0.84-pre2 XMS_Swap [Aug 07 2006 00:05:31]
C:\>path
PATH=D:\dosemuF:\F:\bin;F:\gnu
```

**To Reproduce**

- Use this [command.com](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/dos/command/0.84pre/command.com) with an fdpp build.
- Type `path`
- Notice that the paths are all concatenated together, and binaries in those paths are not found.

**Additional info**

I used this patch, but presumably comcom32 must allow trailing semicolons or you would have noticed it didn't work?

Is it safe to just add more semicolons anyway, or does an empty component mean cwd like in sh?

```diff
diff --git a/src/bindist/fdppauto.bat b/src/bindist/fdppauto.bat
index 7859db878..f36ca2969 100644
--- a/src/bindist/fdppauto.bat
+++ b/src/bindist/fdppauto.bat
@@ -1,8 +1,8 @@
 @echo off
 rem autoexec.bat for DOSEMU2 + FDPP
 path %DOSEMUDRV%:\dosemu;
-if not "%SHELLDRV%" == "" path %PATH%%SHELLDRV%:\;
-if not "%FREEDOSDRV%" == "" path %PATH%%FREEDOSDRV%:\bin;%FREEDOSDRV%:\gnu;
+if not "%SHELLDRV%" == "" path %PATH%;%SHELLDRV%:\;
+if not "%FREEDOSDRV%" == "" path %PATH%;%FREEDOSDRV%:\bin;%FREEDOSDRV%:\gnu;
 if not "%USERDRV%" == "" set TEMP=%USERDRV%:\tmp
 prompt $P$G
 emusound -e
```

**Comment by stsp** [comment]
Both comcom32 and 4dos handle that
correctly, so I wonder if its a freecom bug?
@mcericdos @bartoldeman what do you
think?
Anyway, since trailing semicolon is not
required in DOS, I suppose it is better to
fix this than to not...
