### ISSUE TITLE
[Question] How to disable default drives with command line parameters?

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1321]
Use case: I am testing my [bootimg script](https://hg.ulukai.org/ecm/bootimg/file/01b58abefd74/bootimg.asm), particularly its FAT32 support, and the MBR and DOSEMU image header wrappers that I added just today. (The [image header](https://github.com/dosemu2/dosemu2/blob/f41c0f267fec/src/include/disks.h#L132) is a reliable (**working**) way to tell dosemu what CHS geometry to use.)

Here's an example run. (You need to run the mcopy calls before executing instsect (inst32bi.com) unless you're using [a patched mtools](https://lists.gnu.org/archive/html/info-mtools/2020-10/msg00000.html).)

```
bootimg$ time nasm bootimg.asm -I ../lmacros/ -I ../ldosboot/ -o bootimg.img -l bootimg.lst \
-D_PAYLOADFILE="bootimg.asm,../ldosboot/testpl.com,../RxDOS/rxdos-7.2x/bin/RxDOS.COM,../RxDOS/rxdos-7.2x/bin/RxCMD.EXE,/usr/local/share/dosemu/dosemu2-cmds-0.3/dosemu/exitemu.com,i3.com" \
-D_BPE=32 -D_SPI='(32*1024*2 + 4*1024)' -D_SPF='((32*1024*2 + 4*1024) * 4 / 512)' \
-D_CHS_HEADS=16 -D_CHS_SECTORS=32 -D_MBR -D_MBR_PART_TYPE=fat32_chs \
-D_MBR_DOSEMU_IMAGE_HEADER

real	0m5.506s
user	0m5.230s
sys	0m0.076s
bootimg$ mcopy -i bootimg.img@@528s -o zeros12m.bin ::ZEROS12M.BIN && \
mcopy -i bootimg.img@@528s -o ../lDebug/build/bin/lddebugu.com ::LDDEBUGU.COM && \
mcopy -i bootimg.img@@528s -o ../lDebug/build/bin/ldebug.com ::LDEBUG.COM && \
(cd ../ldosboot; nasm boot32.asm -I ../lmacros/ -D_LOAD_NAME="'LDEBUG'" \
-D_MAP=boot32bi.map -l boot32bi.lst -o boot32bi.bin) && \
nasm ../instsect/instsect.asm -I ../ldosboot/ -I ../lmacros/ -D_FAT12=0 -D_FAT16=0 \
-D_PAYLOAD_FAT32="'boot32bi.bin'" -o inst32bi.com && \
dosemu -dumb -quiet 2> /dev/null -I "disk { hdimage bootimg.img }" -K "$PWD" \
-E "inst32bi.com G:" && (cd ../ldosmbr; nasm oldmbr.asm -o oldmbr.bin -l oldmbr.lst -I ../lmacros/) && \
dd if=../ldosmbr/oldmbr.bin of=bootimg.img conv=notrunc bs=1 seek=8192 count=440 conv=notrunc
boot32.asm:1150: warning: FAT32: 76 bytes still available. [-w+user]
boot32.asm:1538: warning: FSINFO: 21 bytes still available. [-w+user]
../instsect/instsect.asm:2408: warning: dropping trailing empty parameter in call to multi-line macro `_ascii_prefix_suffix' [-w+macro-params-legacy]
Detected FAT32 FS.
1st name: "LDEBUG.COM"
Using auto unit.
Writing FSINFO to sector.
Writing boot sector to sector.
oldmbr.asm:233: warning: 124 bytes left [-w+user]
440+0 records in
440+0 records out
440 bytes copied, 0.000590176 s, 746 kB/s
bootimg$ (cd ../ldosboot; nasm boot.asm -I ../lmacros/ -D_USE_PART_INFO=1 \
-D_QUERY_GEOMETRY=1 -D_LBA=1 -D_LOAD_NAME="'LDEBUGU'" \
-D_FAT16=0 -D_MAP=boot12u.map -l boot12u.lst -o boot12u.bin) && \
nasm bootimg.asm -I ../lmacros/ -I ../ldosboot/ -o bootimgu.img -l bootimgu.lst \
-D_PAYLOADFILE="'../lDebug/build/bin/ldebugu.com'" -D_BOOTFILE="'boot12u.bin'" && \
dosemu -dumb -A -I "floppy { device bootimgu.img }" -I "disk { hdimage bootimg.img }" \
-I "serial { com 2 device /tmp/vptty-dos }" -D+d
boot.asm:1600: warning: FAT12: 10 bytes still available. [-w+user]
dosemu2 2.0pre8-20201019-2417-gf41c0f267 Configured: 2020-10-19 18:57:04 +0200
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.


-boot hde
-q

-rv
V0=00000000 V1=00000000 V2=00000000 V3=00000000   DCO=00000000 DCS=00000000
V4=00000000 V5=00000000 V6=00000000 V7=00000000   DAO=00000007 DAS=00000007
V8=00000000 V9=00000000 VA=00000000 VB=00000000   DIF=0100F008 DPI=0000:0000
VC=00000000 VD=00000000 VE=00000000 VF=00000000   DPR=8AC1     DPP=0000
Current mode: Virtual 86 Mode
-boot quit
bootimg$
```

Now what I want is to have dosemu register the bootimg.img (HDD image with DOSEMU image header) as unit 80h (hda) and thus the FAT32 FS I created in the active, primary, only partition as drive C: for DOS. It should boot from the image instead of whatever drives are created by default. (It would be okay if the default drives were still allocated units > 80h.) I tried the following command line switches without success:

- `-I "bootdrive { G }"`

- `-I "bootdrive { g }"`

- `-I "bootdrive g"`

- `-I "bootdrive=g"`

- `-I "default_drives"`

- `-I "default_drives {}"`

- `-I "default_drives 2"`

- `-I "default_drives 3"`

- `-I "default_drives 0"`

- `-I "skip_drives 4"`

- `-I "bootdrive \"\""`

- `-I "default_drives \"\""`

- `-I "hdimage \"\""`

- `-I "hdimage {}"`

- `-I "hdimage { +1 }"`

- `-I "skip_drives 100"` (shows a runtime error)

- `-I "skip_drives 31"` (shows a runtime error)

- `-I "skip_drives 0"`

- `-I "default_drives 00"`

Andrew seems to address something similar [in the test scripts](https://github.com/dosemu2/dosemu2/blob/f41c0f267fecd7ba0da7cf10e59496b5b7845f7d/test/test_dos.py#L164):

```
        results = self.runDosemu("testit.bat", config="""\
$_hdimage = "dXXXXs/c:hdtype1 dXXXXs/d:hdtype1 +1"
$_floppy_a = ""
""")
```

I'd rather not use a config file though, I think dosemu should allow disabling the default FATFS/redirected drives from the command line.

**Comment by stsp** [comment]
Try `dosemu -I 'disk { image c.img }' -C<num>`
See the above commit for what is <num>.
Not the most user-friendly way, but should
give you a start.
