### ISSUE TITLE
Adlib Tracker 2 crashes on startup

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1327]
**Describe the bug**
Adlib Tracker 2 crashes on startup with the following error --

![2020-11-10-193925_1024x768_scrot](https://user-images.githubusercontent.com/44394516/98750646-804f3400-238c-11eb-966b-469a50a4bf72.png)

**To Reproduce**
Start Adlib Tracker 2.

**Attach program/game binaries or provide an URL**
http://www.adlibtracker.net/downloads.php

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/5520952/boot.log.zip)

**A regression?**
Unknown.

**Additional info**
DOSemu configured for SoundBlaster.
[dosemurc.zip](https://github.com/dosemu2/dosemu2/files/5520957/dosemurc.zip)

**Comment by stsp** [comment]
Not confirmed, works perfectly here.

Could you please remove your .dosemurc,
create it from scratches and put there only
the values you want to change?
I know that our howto suggests otherwise,
but it should stop doing so right now.

**Comment by stsp** [comment]
Otherwise its impossible to find what have you changed there.

**Comment by jharrison03** [comment]
I should have clued into the fact the error was in the "process_config_file" routine --

I run most of my stuff off a Novell share, and running Adlib Tracker 2 off a local disk allows the program to run.  This is an issue I've had with a small amount of software under DOSemu.  (The program runs under native DOS with the same Netware setup.)

This is the log from AT2 running off the local disk --
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/5535003/boot.log.zip)

**Comment by stsp** [comment]
Maybe some problem with permissions?
Anyway, please check the branch "lock"
where we test the new code for remote
(and local) filesystems.
Maybe it will help in some way.

**Comment by stsp** [comment]
Please try again, maybe something have
changed with recent mfs updates.

**Comment by stsp** [comment]
I added more checks, so we will see if
this is a problem with unsupported locking.
Closing until you have more info.
