### ISSUE TITLE
Seeing this warning on build of cpu tests

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1329]
**Describe the bug**

Seeing this message on travis test (Bionic)

~~~
make[1]: Leaving directory '/home/travis/build/dosemu2/dosemu2/src'
make: Entering directory '/home/travis/build/dosemu2/dosemu2/src/tests'
i586-pc-msdosdjgpp-gcc -Wall -O2 -g -fno-strict-aliasing -fno-pic -fno-pie  -o test-i386.exe test-i386.c test-i386-code16.S test-i386-vm86.S -lm
test-i386.c: Assembler messages:
test-i386.c:887: Warning: no instruction mnemonic suffix given and no register operands; using default for `fist'
~~~

**Comment by andrewbird** [comment]
This looks to be fixed now, closing.

**Comment by stsp** [comment]
No, why do you think so?

**Comment by andrewbird** [comment]
Perhaps there's something different about that compiler on Bionic then, as I don't see the warning on my Focal system.

**Comment by stsp** [comment]
I still see it also on fedora.

**Comment by stsp** [comment]
It is probably a gas bug as it doesn't
accept the seemingly valid suffix.

**Comment by stsp** [comment]
Filled the gas bug.
If not a bug, at least they'll tell us the truth.
