### ISSUE TITLE
Tool XMSSTAT makes dosemu2 silently terminate

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1331]
the very harmless tool XMSSTAT, included in the Jemm386 package, makes dosemu2 terminate.

**To Reproduce**
just run the tool

**Attach program/game binaries or provide an URL**
https://github.com/Baron-von-Riedesel/Jemm/releases/download/v5.80pre9/JemmB_v580pre9.zip

**Additional info**
it's a call of the XMM that causes the trouble:

```
mov dx,0
mov ah,10h
call [XMSdriver]
```

Apparently dosemu2 doesn't like it if someone tries to allocate an UMB of size 0.
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/5558440/boot.log.zip)

**Comment by stsp** [comment]
Should not crash now.
I also hope the errors about a screen
resolution in your log, are also fixed,
could you please check that?

Anyway, we do not implement 4309h.
Would you like to submit an impl of that? :)

**Comment by Baron-von-Riedesel** [comment]
> Should not crash now.
I can confirm that.
But I'm not 100% happy, because the failed call hasn't set the BL register; should be 0xB1 if no more UMB memory is available, and 0xB0 if no UMB handler is installed.

> I also hope the errors about a screen
> resolution in your log, are also fixed,
I use a self-written tool to set screen resolution to 37 lines ( using VESA 800x600x4 mode ). It doesn't fully work currently (neither fullscreen nor windowed) - and I've forgotten if it worked in the past.

> Would you like to submit an impl of that? :)
Well, if you can make Jemm386 run in dosemu2, then yes. :)

**Comment by stsp** [comment]
> and 0xB0 if no UMB handler is installed.

I set the error to 0xa7, which means invalid size.

> I use a self-written tool to set screen resolution to 37 lines

I mean the error messages I see in your
log: `ERROR: X res changed: 720 -> 1680`
and alike. Have they disappeared?

> Well, if you can make Jemm386 run in dosemu2, then yes. :)

If you can implement myJEMM extensions, then yes. :)

**Comment by Baron-von-Riedesel** [comment]
> set the error to 0xa7, which means invalid size.

That code is for the block move function only, if the length field is odd or too large.

> Have they disappeared?

Yes. I assume they appeared when I changed to fullscreen mode.

**Comment by stsp** [comment]
> That code is for the block move function only, if the length field is odd or too large.

But how can I use b0 or b1 if they
do not fit the situation?

**Comment by stsp** [comment]
OK, if we are not set to implement 4309h,
then lets close this. :)

**Comment by Baron-von-Riedesel** [comment]
> But how can I use b0 or b1 if they do not fit the situation?

I see. However, MS Himem ( or, probably more exactly, MS EMM386 ) allows a size of 0.
I checked this: it creates a single linked list of special MCBs:
offset
0: byte, 'M'
1: word: segment address of contents (or 0000 if UMB is free)
3: word: size in paragraphs
8: string[8]: containing 'UMB',0,0,0,0,0

So, if you allocate UMBs of 0 and there are still free UMBs, you get segment addresses increasing by 1 each time.

That's just for the record. I don't suggest to implement this.
