### ISSUE TITLE
dosemu -A -dumb 2> result.err > result.log newly writes all output to stderr, instead of just error messages

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1333]
**Describe the bug**

In [a script of mine](https://hg.ulukai.org/ecm/ldosboot/file/dd9b6d5222ba/test/test.sh#l395) I am using the following command:

```
    timeout --foreground 10 "$DOSEMU" \
     -I "$dosemu_category { $dosemu_device $name.img }" \
     "$options_dosemu_direct" -dumb 2> result.err > result.log
```

(This expands to the command `dosemu -I "floppy { device diskette.img }" -A -dumb 2> result.err > result.log`.)

In dosemu2 revision g8596bd5b this worked to split apart error messages (into result.err) and terminal output from DOS (into result.log). In more recent revisions like gf927b902e and g60656f9a6 instead, all output goes to stderr (into result.err). I want to receive the DOS terminal output in one file and possible dosemu error messages (as seen in the second example) in another file.

**To Reproduce**

Here are two runs on two different systems. The dosemu2 versions can be read from the result.* file contents. In both cases, we are passing the _LOAD_MIN_PARA def with the value 1000h (4096, corresponding to 64 KiB) to the lDOS's boot.asm assembling, in order to provoke an error and subsequent timeout of the actual test run.

First, the local system with the more recent dosemu2. Just now pulled and rebuild with the commands `dosemu2$ git pull && make clean && ./default-configure -d && make && sudo make install && update-dosemu-files.sh` results in:

```
ldosboot/test$ hg log -r "$(hg id -i)"
changeset:   557:dd9b6d5222ba
tag:         tip
user:        C. Masloch <pushbx@ulukai.org>
date:        Tue Nov 17 21:50:03 2020 +0100
summary:     boot: optimisation, no need to push bx

ldosboot/test$ ./test.sh diskette direct -D_LOAD_MIN_PARA=1000h
timeout
failure, log contains:
Result log file empty, dosemu error?
ldosboot/test$ cat result.log; echo

ldosboot/test$ cat result.err; echo
dosemu2 2.0pre8-20201118-2457-g60656f9a6 Configured: 2020-11-19 15:43:05 +0100
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

E
ldosboot/test$ 
```

Then on another (remote) system, which has an older dosemu2 still:

```
ldosboot/test$ hg log -r "$(hg id -i)"
changeset:   557:dd9b6d5222ba
tag:         tip
user:        C. Masloch <pushbx@ulukai.org>
date:        Tue Nov 17 21:50:03 2020 +0100
summary:     boot: optimisation, no need to push bx

ldosboot/test$ ./test.sh diskette direct -D_LOAD_MIN_PARA=1000h
timeout
failure, log contains:
lDOS boot error condition letter "E" = Not enough file data
ldosboot/test$ cat result.log; echo
dosemu2 2.0pre8-20190609-1074-g8596bd5b
Configured: 2019-06-09 20:56:57 +0200
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org

E
ldosboot/test$ cat result.err; echo
ERROR: alsa_midi (ALSA lib): seq_hw.c:466:(snd_seq_hw_open) : No such file or directory open /dev/snd/seq failed

ldosboot/test$ 
```

**Attach program/game binaries or provide an URL**

The following needed components can be downloaded from the hg repos:

* https://hg.ulukai.org/ecm/ldosboot/file/dd9b6d5222ba lDOS boot (boot.asm, testwrit.asm, iniload.asm, multboot.asm, test/* files)

* https://hg.ulukai.org/ecm/lmacros/file/81f88c8f797c (lmacros?.mac)

* https://hg.ulukai.org/ecm/scanptab/file/0e53081c1531 (scanptab.asm)

* https://hg.ulukai.org/ecm/bootimg/file/8fc72897d862 (bootimg.asm)

* (lDebug, ldosmbr, instsect, a DOS kernel, and a DOS shell are not needed for `diskette direct` test runs)

(Refer to `ldosboot/test/cfg.sh` on how the script determines where to find these components.)

The following programs are used:

* dosemu2

* NASM (2.15 ish tested)

* setsid (can be skipped by calling `./test.sh selfcall ...` instead)

* stty, ps, grep, sed, tr, cut, kill, timeout

* mtype (of mtools)

* perl

**Attach the log**

I don't think the log is needed for this.

**A regression?**

Works fine on g8596bd5b.

**Comment by stsp** [comment]
Should now be fixed.
However, this will introduce the
"inconvenience" for your case in
#1279 
To get back the old behaviour of
1279, please replace -E with -exec.

**Comment by ecm-pushbx** [comment]
Is it valid to run `EXEC=1 dosemu -E cmd` to get the `-exec` behaviour? Ideally I want my scripts to work across several dosemu2 revisions (though not all).

**Comment by stsp** [comment]
You can probably use
`dosemu -dumb -te -E cmd`
to work with more versions.
On current version its the same
as -exec, and on older one
-te will be ignored, and dumb
will work as before.

**Comment by ecm-pushbx** [comment]
Tested adding `-te` to the dosemu call in lDebug's mak.sh and it seems to work, on the server with the older dosemu2. Will test with the newer dosemu2 later. Thank you!

**Comment by stsp** [comment]
Ideally your script should run `dosemu -v`
and see what revision is there. And form
the cmd line accordingly.
Unfortunately I usually forget to update
revisions when changing some options...
Now I have updated it, so you can check
for `>= 6156` for new syntax.

**Comment by ecm-pushbx** [comment]
I tested the `-te` option and [added it to my script](https://hg.ulukai.org/ecm/ldebug/rev/5bc9a9362ca1). This seems to work fine so I'll leave it at that for now. But it's good to know about `dosemu -v`.

**Comment by ecm-pushbx** [comment]
Oh by the way the new revision fixes my issue with not getting the DOS terminal output into the result.log file. Thanks.
