### ISSUE TITLE
Error f (invalid drive) while redirecting drive F: to \\LINUX\FS\HOME\xxx\DOS

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1336]
**Describe the bug**
The message in the title is displayed by LREDIR in autoexec.bat

**To Reproduce**
enter: LREDIR f: \\linux\fx\home\user\directory

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/5577198/boot.log.zip)

**A regression?**
Yes, it once "worked".

LASTDRIVE=Z in fdconfig.sys

**Comment by stsp** [comment]
What is \fx?
That never worked.

**Comment by andrewbird** [comment]
I'm guessing from your mentioning `fdconfig.sys` that you are using FreeDOS. Until fairly recently there was a dosemu workaround in place to cover over a broken int2f/1217 function in FreeDOS 1.20 and below. This [commit](https://github.com/FDOS/kernel/commit/0dc6a02450ff170101ce911cf9f628187d17fe2f) fixes it in their repo, but obviously the current release 1.20 still has the problem. Since the bug only affects creating brand new drives, you may work around this problem by creating adding another little fat image to your `$_hdimage` line in dosemu.conf which presumably becomes `f:` and then your existing lredir (with initial double slash) should work to overlay it. However there may be a more elegant solution, although I haven't tried it myself. It's described in the https://github.com/dosemu2/dosemu2/wiki/Setup-guide-for-advanced-users-and-ambitious-beginners-(using-Ubuntu) under the `Modify dosemu2 configuration` section, and is to specify a unix path in the `$_hdimage` line itself.

**Comment by stsp** [comment]
I made it now to print the right error msg,
assuming your guess is correct.

> However there may be a more elegant solution

... to not use freedos.
Its unsupported in dosemu2.

**Comment by Baron-von-Riedesel** [comment]
> What is \fx?
> That never worked.

Well, yes, it was a typo in the bug report - of course it's FS. My autoexec.bat:
´´´
@echo off
emusound /e
set comspec=C:\command.com
set prompt=$p$g
set DPMILDR=2056
set path=C:\DOS;C:\DIV;C:\HX\BIN;D:\dosemu
lredir f: \\linux\fs\home\sam\DOS
´´´ 
> I'm guessing from your mentioning fdconfig.sys that you are using FreeDOS.

No, actually I use MS-DOS 7.1. I just wanted to say that I'm sure that LASTDRIVE=Z

**Comment by Baron-von-Riedesel** [comment]
> ... to not use freedos.
> Its unsupported in dosemu2.

Is that mentioned somewhere? Perhaps as a comment in the source?
In my boot.log there is, at the very beginning:

ERROR: Neither FreeDOS nor comcom32 installation found.

So one might indeed come to think that freedos is ok to use ( and MS-DOS probably is not ).

**Comment by andrewbird** [comment]
Then if it's MS-DOS obviously the bug doesn't apply, so did you add the following to `dosemu.conf`? 
`$_l_redir_paths = "/home/sam/DOS"`

**Comment by stsp** [comment]
> ERROR: Neither FreeDOS nor comcom32 installation found.

Ah, that's a bad wording.
It was looking for freedos only to find freecom.
I now clarified the sentence.
It just says basically that it haven't found
any known command.com (but of course
it will go on and try an unknown one too).

**Comment by stsp** [comment]
> Then if it's MS-DOS obviously the bug doesn't apply

But I think it does. :)
Note that the message was edited, and
no longer claims that it wasn't freedos.

**Comment by Baron-von-Riedesel** [comment]
Ok, since FreeDOS isn't supported, I installed fdpp (again, from my last experience I'm a bit sceptical ).
Now it exits with 

ERROR: Bootable drive not found, exiting

This is also a "not too helpful" message. Have I to install comcom32, or is COMMAND.COM from MS-DOS 7.1 good enough or has that message nothing to do with the command interpreter ( as I suspect )?

**Comment by stsp** [comment]
> Ok, since FreeDOS isn't supported

Well, its not supported in a sense that we
(usually) can't help you here. Not in a sense
that it can't be booted at all. :)
We try to keep it more or less alive.

> ERROR: Bootable drive not found, exiting

I suspect that your dosemu2 is built w/o
fdpp support. You probably didn't have
fdpp installed at a build time. In that case
dosemu2 knows nothing at all about fdpp
and can't say anything useful.

**Comment by stsp** [comment]
I now made it so that the error is printed
into the log when fdpp support is not compiled
in. I don't want to promote it to an error
visible on terminal, as some people still
package dosemu2 with freedos and will
likely treat such actions as an unnecessary
pressure on them...

**Comment by andrewbird** [comment]
> But I think it does. :)

Only FreeDOS has the int2f/1217 bug I'm talking about. I really did test all the other flavours in this commit message https://github.com/FDOS/kernel/commit/0dc6a02450ff170101ce911cf9f628187d17fe2f including MS-DOS 7.10. I'm sure it must be something else, but the error code 0xf is suspiciously similar!
@Baron-von-Riedesel I think you need to post your `dosemu.conf` and `-D+d` boot log

**Comment by stsp** [comment]
> Only FreeDOS has the int2f/1217 bug I'm talking about.

See the messages above.
OP edited out the claim that it wasn't
freedos. So it was!

**Comment by andrewbird** [comment]
Ahh, I missed that change, thanks! Log and conf files would still help greatly though.

**Comment by Baron-von-Riedesel** [comment]
> OP edited out the claim that it wasn't freedos. 

Yes. I was confused because I had both kernels (MS-DOS and FreeDOS) installed on C:\. I was running the FreeDOS kernel, though ( and COMMAND.COM from MS-DOS ).

Now I installed FDPP and recompiled dosemu2 and the system indeed boots. I tried to compile comcom32, but that obviously is not for beginners, so I gave up and installed FreeDOS command.com.

After editing dosemu.conf ($_lredir_paths) the lredir command works. So far it works.

However, fdpp still seems to be pretty unstable. as soon as one of my hx binaries terminate, dosemu exits.

**Comment by stsp** [comment]
You can always open a bug report.

**Comment by stsp** [comment]
> I tried to compile comcom32, but that obviously is

Please use binary package for that one.
There is also no need to recompile dosemu2
after installing comcom32, so with binary
package its for novice.

And it will give you an additional challenge:
try to make sure you can run 32rtm resident
from comcom32 under hdpmi. You can't! :)
(under dosemu2 that works... if you disable KVM)

**Comment by Baron-von-Riedesel** [comment]
> try to make sure you can run 32rtm resident
> from comcom32 under hdpmi. You can't! :)

Yes, I can! :)) I just have to set environment variable HDPMI=2048 before hdpmi32 is loaded.
However, what has this 32rtm-bug to do with comcom32?

**Comment by stsp** [comment]
But how do you make sure that when
you run eg bc, then the interrupts are
delivered to 32rtm, but when comcom32
works, then everything is delivered to it?
It wasn't easy at all for me to implement
that logic in dosemu2...
https://github.com/dosemu2/dosemu2/commit/8330d87ee7116ade12ac359fc35eb77a6d5f36f2

**Comment by Baron-von-Riedesel** [comment]
> But how do you make sure that when you run eg bc, then the interrupts are
> delivered to 32rtm, but when comcom32 works, then everything is delivered to it?

I don't understand. Setting HDPMI=2048 activates a few lines of code:

```
	test bEnvFlags2,ENVF2_CLRHIWORD
	jz @F
	movzx esi,si
	movzx edi,di
@@:
	pop ds
	iretd   ;return to the client
```
that code is run when the client initially switches to protected-mode
The 32rtm but I'm referring to is that 32rtm just "forgets" to clear hiwords of EDI (and probably ESI)
and that causes a GPF in HDPMI32 as soon as 32rtm calls int 0x31, ax=0x300, es:edi->RMCS.

**Comment by stsp** [comment]
The problem have nothing to do
with 32rtm bug or whatever.
Just run comcom32 then 32rtm then
bc.exe, then exit bc.exe.
Do things still work?

**Comment by Baron-von-Riedesel** [comment]
I just read the bug you are refering to. Now I understand the possible conflict.
It's surely no problem with HDPMI if it's installed with the -a switch, because then the clients are pretty well separated. And that's my favorite setting. I'll test without that setting.

**Comment by stsp** [comment]
When they are well separated its
still a problem, because bc wants
to work in a context of 32rtm.
So whatever binary comcom32
executes, should work in 32rtm
context, but comcom32 itself should
not.

**Comment by Baron-von-Riedesel** [comment]
I just tested without the aforementioned switch and got a GPF in ring0. So yes, this won't work.

> When they are well separated its still a problem, because bc wants to work in a context of 32rtm.

But It works. The separation is almost as if two instances of the host are loaded. They have their own IDT, LDT, CR3, host stack, locked pm stack and real-mode stack.

**Comment by stsp** [comment]
But how exactly it works?
Maybe bc doesn't see 32rtm because
of the separation, and as such, acts as
if 32rtm was not loaded?

Also how do you switch these "VMs"?
32rtm does not inform a DPMI host
about its staying resident. It just jumps
to exit addr in real mode. How do you
properly return to comcom32 after that,
if current client is still 32rtm? Or do you
associate the "VMs" with current PSP?

**Comment by Baron-von-Riedesel** [comment]
> Also how do you switch these "VMs"?

This happens "naturally", there's no work involved. Since IDT and LDT are separated, it's impossible that a switch may be needed while you're in protected-mode. A VM switch requires to switch "back" to real-mode, and then enter protected-mode of the other "VM". The "real-mode to protected-mode" switches automatically also switch "VMs".

Let's assume you have 3 protected-mode apps, all have modified IRQ 1, the keyboard IRQ.

1. current client gets IRQ, decides not to handle it
2. its dpmi host routes IRQ to real-mode
3. the 2. host routes the IRQ to protected-mode, since its client also wants IRQ 1.
4. the 2. client decides not to handle the IRQ
5. its host routes the IRQ back to real-mode
6. the 3. host again routes it to protected-mode
7. the 3. client finally wants to handle the IRQ, sends EOI to PIC and does IRET
... and now the way back with again 3*2 mode switches.

**Comment by stsp** [comment]
> its dpmi host routes IRQ to real-mode

... where bios take it up and sends EOI?

The question is more, when the "procedure
with far return frame" returns, how do you
know which client should now be active?
The last one? No, that would be 32rtm and
not comcom32.

**Comment by Baron-von-Riedesel** [comment]
> how do you know which client should now be active?
There's never any active "decision" to do. IMO everything depends upon proper handling of 2 stacks: the host stack and the real-mode stack. And real work has to be done only if the host is "reentered" (real-mode callback, IRQs, "initial switch to protected-mode"). Then the current stack status has to be saved and, when the callback is finished, restored.

**Comment by stsp** [comment]
IRQ is just one part of the problem.
Currently not interesting part.
Consider this:
- comcom32 does "simulate real mode interrupt" and spawns 32rtm
- 32rtm jumps to exit address
- the control is back to protected mode, int21 returned

What client is now active?

**Comment by stsp** [comment]
I have now applied the patch that binds
the client number to the realmode stack.
So switching the realmode stack would
switch the DPMI client.
This is just as an example to demonstrate
you the problem.
Some magic had to be applied to "find"
the needed value in stack. :)

**Comment by stsp** [comment]
The magic didn't work though, because
the client can provide its own RM stack,
whose length is not known...
So now I just allocate multiple return
addresses, one per client. I suppose
this is also what happens under hdpmi
when it uses one host per client.

**Comment by Baron-von-Riedesel** [comment]
> So now I just allocate multiple return addresses, one per client. I suppose
> this is also what happens under hdpmi when it uses one host per client.

No. I guess real-mode stacks in hdpmi and dosemu and handled pretty differently.
hdpmi's real-mode stack handling is as follows:

1. on "initial switch to protected-mode" the client provides a "default" real-mode stack (0x200 bytes). This stack is used when a switch to real-mode is requested and the client doesn't provide a specific one (like setting SS:SP in the real-mode call struct ).
2. when the host is "reentered" ( a real-mode callback, or a new "initial switch to pm", as well as IRQs ), this "default" real-mode stack is pushed onto the host stack and the current real-mode SS:SP becomes the new "default" real-mode stack.
3. when the callback is done, the previous "default" real-mode stack is popped from the host stack.

**Comment by stsp** [comment]
Yes, this is a nice trick to save some
DOS mem. We just request 3K for stacks
from client at init.
But this doesn't answer my question.
If you return from real-mode procedure
(300,301,302), then how do you know
which client is now active?

**Comment by stsp** [comment]
More precisely, when you return from
300h with BL=21h and AX in a realmode
struct was set to 4b. Which means you
called DOS exec. Which could be 32rtm.
On return from 0x300 call, how do you
know which client is active?

**Comment by Baron-von-Riedesel** [comment]
> If you return from real-mode procedure (300,301,302), then how do you know
> which client is now active?

Simply the very same as before the call. The client cannot have changed.

> More precisely, when you return from 300h with BL=21h and AX in a realmode
> struct was set to 4b. Which means you called DOS exec. Which could be 32rtm.
> On return from 0x300 call, how do you know which client is active?

It's again simply the same as before the call. If the call was an "execute program", and the new program
has switched to protected mode on its own, it has been terminated by now - else the caller wouldn't regain control.

**Comment by stsp** [comment]
Sure, of course same as before!
Before the call. But not before return
from the call, because, right before
return, 32rtm was the active client.
Now when return happens, how do
you find the number of the currently
active client? How you find the number
of the client "before the call"? How
do you know which client did the call?
Computer doesn't understand "I need
same client as before the call". You
either store a number somewhere, or
you can't find one. I tried to store the
number on realmode stack - no luck.

**Comment by Baron-von-Riedesel** [comment]
> Now when return happens, how do you find the number of the currently active client?

The "problem" is that in hdpmi clients don't have any numbers associated with them. So hdpmi also doesn't need to "find" them. There are only "current" stacks.

**Comment by stsp** [comment]
Stack is not enough, because when
32rtm terminates, its still on top of stack.
You need to find out which client made
the real-mode call, and that is the problem.

**Comment by Baron-von-Riedesel** [comment]
> Stack is not enough, because when 32rtm terminates, its still on top of stack.

Not with hdpmi and option -a, since there's simply no stack of clients. The tsr (32rtm) terminates and if it hasn't hooked a real-mode interrupt, it has no chance to wake up again ( and thus activate the hdpmi instance bound to it ).

**Comment by stsp** [comment]
> The tsr (32rtm) terminates

It just jumps to exit address.
The DPMI have no way of noticing
it went TSR. It would still think its an
active client.
The only possibility is to have multiple
return points, one per client. Then you
know the client number from the return
address of real-mode call.

**Comment by Baron-von-Riedesel** [comment]
> The DPMI have no way of noticing it went TSR. I

Yes, this is a problem and that's probably why there's no (documented) way to write a dpmi tsr.

It works if the tsr is installed as first client or at least unloaded before the current client terminates.

I guess I will adjust hdpmi so that in the problematic case there's just an "orphaned" instance remaining in memory.

**Comment by stsp** [comment]
> Yes, this is a problem and that's probably why there's no (documented) way to write a dpmi tsr.

Not sure why are you saying that.
But as I remember you were saying that
also 10 years ago, this time I'll answer with
URLs. :)
http://www.delorie.com/djgpp/doc/dpmi/api/310c00.html
http://www.delorie.com/djgpp/doc/dpmi/api/310c01.html
These were supported by dosemu, but do
not seem to work right with comcom32.
Needs to investigate...
Another functions that dosemu2 supports and
hdpmi likely not, are d00/d01.

> I guess I will adjust hdpmi so that in the problematic case there's just an "orphaned" instance remaining in memory.

This is what I do too, but that still doesn't
answer the question, how do you find the
right client when real-mode procedure returns
from int21/4bh.

**Comment by Baron-von-Riedesel** [comment]
> http://www.delorie.com/djgpp/doc/dpmi/api/310c00.html
> http://www.delorie.com/djgpp/doc/dpmi/api/310c01.html

I know those, but these were in dpmi v1.0 only, and nobody (except you) implemented that.

> how do you find the right client when real-mode procedure returns from int21/4bh.

I just rely on the correct status of the host stack. When a new client starts, that's - for hdpmi - virtually the same as if the host has been reentered by a real-mode callback - it has to save the current stack+segment status on the host stack. When the new client terminates, these saved values are popped off the stack - and the int 21h, ax=0x4b00 can properly return. And that's also the reason, why it doesn't work if the new client jumps to real-mode and terminates with a "go resident" call. This returns to the caller, but the saved values on the host stack haven't been restored yet - resulting in a crash. Btw., IIRC the dpmi specs warn explicitely not to exit a client while in a real-mode callback.

If hdpmi is used with -a option, each client has its own host stack and there's a good chance that in this configuration this all may work finally - currently it doesn't, however.

**Comment by andrewbird** [comment]
Sorry to butt in here with an off topic question, but I really like those graphics used for register use representation i.e. ![x](http://www.delorie.com/djgpp/doc/dpmi/api/r/ax+E+edi.gif)
Does anyone know what they are called or what tool is used to generate them?

**Comment by stsp** [comment]
> Does anyone know what they are called or what tool is used to generate them?

Wrong forum, DJ Delorie is not here to answer that.

**Comment by andrewbird** [comment]
Sure I just thought it might be common knowledge, no matter!

**Comment by stsp** [comment]
> I know those, but these were in dpmi v1.0 only, and nobody (except you) implemented that.

When most of everyone seeks for a
way to create a DPMI tsr and I see a
documented one, of course I'd rather
go and implement it. :)
Please make a world the favour and
implement them (and d00/d01) in hdpmi! :)

> Btw., IIRC the dpmi specs warn explicitely not to exit a client while in a real-mode callback.

I currently don't remember what 32rtm
did, but IIRC this had nothing to do with
real-mode callback. I think it just jumps
to the exit addr stored in PSP.

> If hdpmi is used with -a option, each client has its own
> host stack and there's a good chance that in this configuration
> this all may work finally - currently it doesn't, however.

Indeed!!!
You were saying it works, so you might
be cheating.
Anyway, lets see how would you fix that
w/o checking the return address from
realmode interrupt. I think there is no
other way to fix it correctly.

**Comment by Baron-von-Riedesel** [comment]
> You were saying it works, so you might be cheating.

Well, it doesn't crash, the system remains stable ( except that some dos memory is consumed, and hdpmi cannot be unloaded anymore ). But it surely can't work the way 32rtm has intended it.

**Comment by stsp** [comment]
Hmm, the fact that comcom32 remains functional,
means that you actually find the right client to continue.
How?

**Comment by stsp** [comment]
> I know those, but these were in dpmi v1.0 only

v1.0 is actually a quite convenient API.
I have now implemented most of the remaining
calls, and converted msdos.c to them:
https://github.com/dosemu2/dosemu2/pull/1343
After that, the program I was showing to
you as an example of a tsr usage, will probably
do a bit more than just write some string to
screen. Its actually the full port of msdos.c
to DOS. So maybe it will be able to run windows
on top of cwsdpmi, or alike.

**Comment by Baron-von-Riedesel** [comment]
> Its actually the full port of msdos.c to DOS. So maybe it will be able to run windows on top of cwsdpmi, or alike.

That would be useful - but: since cwsdpmi doesn't install the dpmi v1.0 tsr functions, how will it install itself under that host?

> Hmm, the fact that comcom32 remains functional, means that you actually find the right client to continue.

I'm still confused about how 32rtm works. It's quite similiar to the hx dos extender, but you cannot really mix their components. Although, IF the components are mixed (hdpmi32 + 32rtm), some tools run (tasm32), and some tools don't (tlink32). Generally, I have the impression that 32rtm does strange things - even the simple DPMI.EXE supplied with HX behaves differently when 32rtm is installed.

**Comment by stsp** [comment]
msdos.c uses full stack of 1.0 functions
(linear allocs, page attributes, shared mem
etc). It would be silly to seek work-arounds
for tsr, if all other funcs are used anyway.
I'd like it to work on hdpmi, but if not, I can
try dpmione.

It doesn't matter much how 32rtm works.
What matters is that return to comcom32
happens when dpmi host still thinks 32rtm
is an active client.

**Comment by stsp** [comment]
Btw, I now know why dpmi-1.0 spec says that
the exceptions should be routed to rm interrupts
(bypassing pm interrupts). They say
`Clients which run under DPMI 1.0 should use Int 31H Functions 0212H
and 0213H to set the addresses of exception handlers.`
and if you use these funcs instead of 203,
then indeed it is no longer routed to PM int
handlers.
