### ISSUE TITLE
incorrect syntax of $_lredir_paths causes dosemu2 to silently terminate at startup

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1340]
I wanted to add a second path to $_lredir_paths. Since there is no example in /etc/dosemu/dosemu.conf how to do that I had to guess. One of my guesses so far was:

$_lredir_path "/mnt/sam/xxx" "/mnt/sam/yyy"

which causes dosemu to silently refusing to start, without any messages in boot.log.

This could surely be improved. Btw, WHAT is the correct syntax?

**Comment by stsp** [comment]
No, its not silent.
It says:
```
Error in /home/stas/.dosemu/.dosemurc: (line 021) unrecognized command '"/home/stas"'
1 error(s) detected while parsing the configuration-file
1 error(s) detected while parsing the configuration-file
```

I added more examples.

**Comment by stsp** [comment]
Wait, its not in boot.log indeed.

**Comment by stsp** [comment]
Should now be there.
