### ISSUE TITLE
dpmi tsr crash with comcom32

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1341]
Attached is a demo DPMI tsr program.
[pmdapi.exe.gz](https://github.com/dosemu2/dosemu2/files/5589942/pmdapi.exe.gz)

It works fine with freecom, but not with
comcom32: dosemu crashes.

@Baron-von-Riedesel have a good luck
running it under hdpmi. :)

**Comment by Baron-von-Riedesel** [comment]
Perhaps it would be good to know what to expect from this program.

If I run it, it displays a line: cs=xxxx ds=xxxx cs_base=xxxx ds_base=xxxx

Nothing else. After that, if I try to start another dpmi prog, I get an "DPMI: unhandled Exception 0d - Terminating Client'
I always get this error then, no matter what command.com is active.

**Comment by stsp** [comment]
Yes, it prints that, but only if functions
c00 and c01 are available.
So I have no idea how have you started
it, you might be cheating.

**Comment by stsp** [comment]
> I always get this error then, no matter what command.com is active.

Yes, this seems to be the bug on its own.
I fixed the comcom32-related crashes, but
this one is still here.

**Comment by stsp** [comment]
Phew, this wasn't easy at all!
You also need to update pmdapi is you
want to test it further.

**Comment by andrewbird** [comment]
I've noticed before that when I leave you alone, you come up with a fix for an issue with a really difficult to find cause. I'll try not to bother you too much! :smile:

**Comment by stsp** [comment]
> I'll try not to bother you too much! smile

By not writing xattrs support? :)
OK, good hint.

**Comment by andrewbird** [comment]
xattrs supporting is continuing, but trying to write tests and iron out the wrinkles. https://github.com/andrewbird/dosemu2/tree/travis-ci-46

**Comment by stsp** [comment]
[pmdapi.exe.gz](https://github.com/dosemu2/dosemu2/files/5778822/pmdapi.exe.gz)
Updated test case.

**Comment by andrewbird** [comment]
Is that something that provides a simple pass/fail or other predictable output that would be worth adding to the test suite?

**Comment by stsp** [comment]
No, not yet.
Maybe eventually.

**Comment by stsp** [comment]
Wrong fix.

**Comment by stsp** [comment]
Got it to work for 32bit clients.
For 16bit ones something is still not good...
But getting closer.

**Comment by stsp** [comment]
Btw, the DPMI-1.0 doc is flawed wrt rsp
functionality:
file:///home/stas/dos/c/tools/docs/syst/dpmi/ch4.8.html
It passes client handle in BX, but on
termination call the one also needs the
handle of prev client.
As an extension, I now pass such handle
in CX.
Probably this is the reason 0xc00 is
rarely implemented?

**Comment by stsp** [comment]
> termination call the one also needs the
> handle of prev client.

This is because the selectors of RSP are
not preserved. They are allocated for every
new client, so the RSP should be able to
set segregs to the values that are valid
in context of the current client. So when the
current client terminates, RSP needs to know
what selectors to load into segregs next time.
And for that it needs the handle for prev client.

**Comment by stsp** [comment]
Finally I figured out what went wrong.
When chaining to the (prev) 16bit int21 handler,
there can be no such handler, in which
case msdos checked the THUNK_16_32x
and seen then 32bit caller.
Obviously this breaks only when the higher
words of some 32bit regs are garbled, so
win31 was becoming unstable but it was
quite difficult to locate.
Now I disable THUNK_16_32x before every
call-out.
So I don't suppose it can work with hdpmi
for 16bit clients, but for 32bit clients it uses
only documented DPMI API, so should work.
[pmdapi.exe.gz](https://github.com/dosemu2/dosemu2/files/5811957/pmdapi.exe.gz)

**Comment by stsp** [comment]
Andrew, it would be cool to turn it into a
test-case now, as it finally works again.
This can be done by building and loading
pmdapi before some other DPMI test, for
example ecm test.
