### ISSUE TITLE
write lock manager for share modes and protection of opened files

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1345]
Recently we implemented the share modes
support via some hacks that encode them,
together with open modes, into 6 lock bytes...
(namely: read, write, deny_read, deny_write,
compat, non_compat)
In addition, the directory exclusive lock is used
to make such operations atomic.
In addition to that, certain operations (like delete,
rename) needs to be rejected if the file is opened.
This is achieved via the region directory locks
(otherwise you would need to open the file itself
before delete and check for some locks).

Lets say all these hacks are exceptionally clever,
but we need the lock manager instead.
It should put exclusive locks on all files opened
by any dosemu session, so that no other dosemu
process can modify them on another machine
via the network FS. Perhaps also the exclusive
lock will have to be applied on a directory that
contains any opened file, to prevent their deletion
on another machine. Lets say that fine-grained
coordination between 2 machines is too difficult
to try, and just locking files and dirs exclusively,
should be sufficient for the first impl.
Note that current dir locking hacks may also
not work across machines because I use the
inode number to identify the file, which may
not be consistent across the network FS. So
lock manager approach will not be a regression
wrt communication over the network.

The challenge would be to make the lock
manager API atomic (so that it does not have
to query other dosemus to make a decision),
and yet not to code the share logic directly into
the lock manager, leaving it in dosemu.
That will require some clever ideas.

In addition to that, region locks may also
go the via lock manager. The reason is that
exclusive region locks can only be applied
to the RW-opened files. So currently we
open all files RW and check write access
by hands. And RW-open fails on RO files,
so there no region locks are possible.

**Comment by Patriciogonza9090** [comment]
I am running a Clipper application in different computers. Some users access via Putty, and a couple run the DOS application on a Windows Xp machine accessing to the DBF files via Samba shares.
The Putty users have different user names to access the Fedora Server 34.
I am experiencing some problems, apparently the data is not being written to disc, when some concurrent users are working on the same tables, they see different data. This was not happening in previous DOSEMU old version installation. Is there any configuration that I have to consider in order to avoid this situation of data loss?

**Comment by andrewbird** [comment]
@Patriciogonza9090 I suspect the effect you are seeing is the result of windows client side caching, I haven't used windows/samba myself for a good while, but I suggest you search for 'smb client side caching` and `opportunistic locking`, you may want to disable both on that share. There is another thing though, I'm not sure that current Samba and Dosemu locking mechanisms play very well together. They probably don't respect each other's locks, so if you solve the caching problem you might find database corruption.
Hope it helps.

**Comment by stsp** [comment]
Let's start from simplest theories.
Maybe we forget fsync() (aka dos_flush() )
when locks are released?

**Comment by Patriciogonza9090** [comment]
Stas, do you mean the dos_flush instruction is missing in the code of our
Clipper application?
Or it is related to server configuration parameters?


Patricio González

**Comment by stsp** [comment]
It is probably missing in dosemu2.
Andrew can check that. :)

**Comment by stsp** [comment]
> They probably don't respect each other's locks

I hope they only do not respect
each other's "share modes".
I believe (or at least hope so) the
locks should work quite well.

> smb client side cachingandopportunistic locking

I think this is only relevant for
SMB clients, like cifsfs, but it
probably does not expose that
"feature" to the posix FS that
it provides. Because there is
probably no such thing in posix,
so I would guess that cifsfs just
disables that feature on its own.

**Comment by stsp** [comment]
Will something like this help?
```
diff --git a/src/dosext/mfs/mfs.c b/src/dosext/mfs/mfs.c
index 624984733..9282041ef 100644
--- a/src/dosext/mfs/mfs.c
+++ b/src/dosext/mfs/mfs.c
@@ -3421,6 +3421,9 @@ static int lock_file_region(int fd, int lck, long long start,
 {
   struct flock fl;
 
+  if (!lck)
+    dos_flush(fd);
+
 #ifdef F_GETLK64       // 64bit locks are promoted automatically (e.g. glibc)
   static_assert(sizeof(struct flock) == sizeof(struct flock64), "incompatible flock64");
 
```

**Comment by Patriciogonza9090** [comment]
Today I only allow DOSEMU2-PUTTY users and all worked well.
Apparently the combination of both type of users or the Windows XP users are causing the file corruption problems.

**Comment by stsp** [comment]
So its not a dosemu problem then?

**Comment by stsp** [comment]
Are you using share/deny modes
or file locks?

**Comment by stsp** [comment]
I applied the data flush patch
for safety anyway. It shouldn't
hurt.

**Comment by Patriciogonza9090** [comment]
> So its not a dosemu problem then?

I will confirm in the following days, I hope so.

**Comment by stsp** [comment]
Well, it appears the mandatory locks
that can block open() calls, are actually
present on linux! Its an F_SETLEASE
fcntl()s.

Andrew, would you like to evaluate if
they suit implementing share modes?
Looks quite promising.

**Comment by stsp** [comment]
Although since there is no atomic
"open and get lease", it doesn't look
any better than what we have now...

Interestingly, NFSv4 has a fully
windows-compatible open semantic
called "share reservations". Samba
has its own locking.dtb impl of the
same thing. Kernel's ksmbd also
supports share modes.
So there are at least 3 servers with
share modes support, but seems to
be no user-space client library that
allows to use such functionality. And
in case of ksmbd, it is essentially
unclear how does it export such
functionality (if at all).

**Comment by stsp** [comment]
Hi Andrew, the func_ds3_lock_readlckd.py
test-case demonstrates that the lock applied
to the O_RDONLY file, can exclude other's
reads... which means its a write lock.
I wonder if this is correct and consistent with
fatfs behavior. I suppose all these tests are
run on fatfs and on a redirector?
So does this mean DOS has only write-locks
and we need an ability to set write locks on
a read-only files that posix (rightly) disallow?

Yes, I remember that question was already
raised, but I think it was raised in context of
a deny mode emulation. Would be good to
get a confirmation that we actually need
write locks on an R/O files even if we do not
emulate share modes with locks...

**Comment by stsp** [comment]
Also do we have tests that test
locking between multiple dosemu2
instances? All tests I look in, seem
to spawn 2 processes within 1
dosemu2 instance.

**Comment by andrewbird** [comment]
> I wonder if this is correct and consistent with
fatfs behavior. I suppose all these tests are
run on fatfs and on a redirector?

All tests are derived from MS-DOS 6.22 / share behaviour on FATFS (except a slight extension for partial read) and tested on both FATFS / MFS.

> So does this mean DOS has only write-locks
and we need an ability to set write locks on
a read-only files that posix (rightly) disallow?

I don't remember, it's been a while. But the lock function in question is that implemented by djgpp, so you might find some clues there https://www.delorie.com/djgpp/doc/libc/libc_175.html

> Also do we have tests that test
locking between multiple dosemu2
instances?

Not in the test suite at present, but we did run the Burton systems test here https://github.com/dosemu2/dosemu2/issues/270. I would have included that, but there was a problem with the test itself generating invalid timestamps and so giving spurious failures.


I'd like to add a multiple dosemu2 instance test but I have no spare time at the moment, I'm sorry :disappointed:

**Comment by stsp** [comment]
> All tests are derived from MS-DOS 6.22 / share behaviour on FATFS (except a slight extension
> for partial read) and tested on both FATFS / MFS.

OK, in that case I think we need another
"extension" here to not set the write locks
on an R/O fd. At present I solve that with
opening the file always in RW mode and
checking the write perms by hands on write().
This is silly, and also RW open may fail
due to no write permission. And writing a
lock manager just for that, would be even
sillier. So I am quite determined to remove
that code.
Unfortunately there is still the question
how to emulate share modes on an R/O
fd, as we use the write locks also for that...
This is a difficult one, but moving away
the generic locking from that tricky area
would already be a relief.

**Comment by stsp** [comment]
> I'd like to add a multiple dosemu2 instance test but I have no spare time at the moment, I'm sorry
> disappointed

We need to have a list of missing tests, or
its all gets forgotten quickly. :(

**Comment by stsp** [comment]
> So I am quite determined to remove
> that code.

... together with the test that prevents such
an "extension". :)

**Comment by stsp** [comment]
> Not in the test suite at present, but we did run the Burton systems test here

Hmm, IIRC there were the failing tests
that you (rightly) digged up to the bugs
in their test-suite. But now all tests are
passing! Both remote and local.
Have they updated the tests, following
your investigations or what?
Miracle. :)

**Comment by stsp** [comment]
OK I merged the lock manager now,
which is fortunately not a separate
process but a library code that plays
around the uucp-style lockfiles.
They can now be seen in
`/var/lock/dosemu2_*` dirs
and `/tmp/dosemu2`
in a rather high quantities. :)
(though these dirs are dynamically
created and removed all the time,
so you may actually not see anything
in most cases)

Semantic change is just one:
multiple readers can now grab read locks
concurrently, as posix locks allow to. Otherwise
we'd need to force the write mode (chmod and
other hacks).
Affected tests:
- test_mfs_ds3_lock_two_handles - updated to
  distinguish the DOS and posix semantic, and
  work properly in both cases.
- test_mfs_ds3_lock_readonly - disabled.

Initial intention was to also allow the unlocked
readers to work concurrently with locked
readers, as this is what trivially maps to posix
locks. But unfortunately then also
test_mfs_ds3_lock_readlckd starts to fail,
so I decided to write a compatibility code
for such case, which required the "shadow fd"
tricks.

**Comment by andrewbird** [comment]
> Hmm, IIRC there were the failing tests
that you (rightly) digged up to the bugs
in their test-suite. But now all tests are
passing! Both remote and local.
Have they updated the tests, following
your investigations or what?

I seem to remember that the tests were randomly failing, something to do with file time, see https://github.com/dosemu2/dosemu2/issues/270#issuecomment-449586157

**Comment by stsp** [comment]
Yes, I can indeed confirm the very rare
failure of 1 test. This is great as I thought
there are more of those.
Anyway, I am done with the locks, and
hopefully this time - for long. :)

**Comment by stsp** [comment]
Actually more work can be done here.
It would be good to structure the code
the way the ofd-locks limitations are
clearly visible, and draft an extension
RFC.

**Comment by stsp** [comment]
Hi Andrew, can you reproduce these
CI errors locally?
https://github.com/dosemu2/dosemu2/actions/runs/5306269671/jobs/9603742509
Seems to work for me, and I haven't
pushed anything that bypassed CI...

**Comment by andrewbird** [comment]
From the CI log files the problem seems to be only affecting FreeDOS / DR-DOS and they are only tested on the weekly scheduled CI run.

That said, locally I don't seem to be able to even run FDPP. However I do have several filesystems including my /home on NFS and expect that combination has not seen any testing at all recently.

I have no time to chase this down today though, sorry.

**Comment by stsp** [comment]
```
 test/test_dos.py FRDOS130TestCase.test_libi86_item_007
Test FR-DOS-1.30 libi86 item   7 Console output testing                          ... ok (  3.69s)

----------------------------------------------------------------------
Ran 1 test in 3.692s

OK
```

```
$ test/test_dos.py DRDOS701TestCase.test_libi86_item_007
Test DR-DOS-7.01 libi86 item   7 Console output testing                          ... ok ( 15.12s)

----------------------------------------------------------------------
Ran 1 test in 15.115s

OK
```

So seems like I still can't reproduce. :(

**Comment by stsp** [comment]
```
$ test/test_dos.py DRDOS701TestCase.test_mfs_ds3_share_open_twice
Test DR-DOS-7.01 MFS DOSv3 share open twice                                      ... ok (  9.32s)

----------------------------------------------------------------------
Ran 1 test in 9.322s

OK
```

**Comment by stsp** [comment]
In fact, I don't even see the failure
in the log:
`Continuous timestamp test - complete`
is the last line of the log on CI, and yet
it counted the test as failed?
Maybe return code from dosemu process
got messed up...

**Comment by stsp** [comment]
https://lkml.org/lkml/2023/6/20/379
I drafted an RFC to lkml about the OFD lock
extensions.
Not sure if it is going to generate any
interest among the linux community -
will see.
But you are welcome to review it and
add your own wishes. IIRC Andrew
had lots of wishes around OFD locks,
but I forgot them already.

**Comment by stsp** [comment]
Seems to be scheduled for 6.6:
https://www.spinics.net/lists/linux-fsdevel/msg248322.html
Finally we'll get proper locking w/o
major hacks.

**Comment by stsp** [comment]
Added some untested support for
the upcoming 6.6 extension.
