### ISSUE TITLE
Rename test failing on MFS

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1346]
**Describe the bug**
 Rename is failing on MFS

**To Reproduce**
~~~
python3 test/test_dos.py MSDOS622TestCase.test_mfs_fcb_rename_simple
~~~

**Attach the log**
~~~
======================================================================
FAIL: Test MS-DOS-6.22 MFS FCB file rename simple                                     
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dos.py", line 1217, in test_mfs_fcb_rename_simple
    self._test_fcb_rename_common("MFS", "simple")
  File "test/test_dos.py", line 1164, in _test_fcb_rename_common
    self.assertIn("Rename Operation Success", results)
AssertionError: 'Rename Operation Success' not found in 'testit.bat\r\r\n\r\nC:\\>d:\r\n\r\nD:\\>c:\\mfsfcbr1\r\nRename Operation Failed\r\nD:\\>DIR\r\n\r\n Volume in drive D is IR DXXXXS D\r\n Directory of D:\\\r\n\r\nTESTA    BAT             7 11-29-20   1:50a\r\n        1 file(s)              7 bytes\r\n                   2,147,450,880 bytes free\r\n\r\nD:\\>'

----------------------------------------------------------------------
Ran 1 test in 3.257s

FAILED (failures=1)
ajb@polly:/clients/common/dosemu2.git$ git bisect bad
4115e8971181a4a1a3a7c0e94a0d2856ae4f961c is the first bad commit
commit 4115e8971181a4a1a3a7c0e94a0d2856ae4f961c
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Tue Nov 10 02:26:45 2020 +0300

    mfs: implement mfs_rename() [#270]

 configure.ac         |  6 ++----
 src/dosext/mfs/mfs.c | 61 +++++++++++++++++++++++++++++++++++++++++++++++-----
 2 files changed, 58 insertions(+), 9 deletions(-)
~~~

**A regression?**
Yes, see git bisect

**Additional info**
Test fails on both FDPP and MS-DOS 6.22

**Comment by andrewbird** [comment]
So just to follow up, as I don't see the same test failing in Travis I'm wondering if it's something special about my environment (NFS, groupps or umask etc).

**Comment by stsp** [comment]
Works perfectly here as well.
Is there anything interesting in the full log?

**Comment by stsp** [comment]
> So just to follow up, as I don't see the same test failing in Travis I'm wondering if it's something special
> about my environment (NFS, groupps or umask etc).

Maybe you have renameat2 and they don't?
Just guessing.

**Comment by andrewbird** [comment]
So a little news, the test passes on the same machine using ext4 partition. That doesn't necessarily rule out `renameat2()` as the trigger because my NFS client machine that the test is run on is Ubuntu 20.04, and the NFS server is Ubuntu 16.04. I'm not sure what `renameat2()` requires of the server. I may adjust the code to make it not use `renameat2()` just to see if we are thinking along the right lines. 

I didn't see anything in the logs that told me what was going on yet.

**Comment by andrewbird** [comment]
I looks like the `renameat2()` doesn't work for me over NFS. So whether that's because of the old NFS server I don't know.
~~~
ajb@polly:/clients/common/dosemu2.git$ python3 test/test_dos.py MSDOS622TestCase.test_mfs_fcb_rename_simple
Test MS-DOS-6.22 MFS FCB file rename simple                                      ... ok (  3.43s)

----------------------------------------------------------------------
Ran 1 test in 3.440s

OK
~~~
~~~
ajb@polly:/clients/common/dosemu2.git$ git diff
diff --git a/src/dosext/mfs/mfs.c b/src/dosext/mfs/mfs.c
index 2f5d61949..67d39b082 100644
--- a/src/dosext/mfs/mfs.c
+++ b/src/dosext/mfs/mfs.c
@@ -803,7 +803,7 @@ static int do_mfs_rename(const char *dname, const char *fname,
             close(dir_fd);
             return ACCESS_DENIED;
     }
-#ifdef HAVE_RENAMEAT2
+#if 0 // HAVE_RENAMEAT2
     err = renameat2(dir_fd, fname, -1, fname2, RENAME_NOREPLACE);
 #else
     err = access(fname2, F_OK);
~~~

Is there an easy way to tell `default_configure` that I don't want `renameat2()`?

**Comment by stsp** [comment]
Please try w/o RENAME_NOREPLACE, as I don't
think renameat2 is at fault, but rather a flag.

**Comment by andrewbird** [comment]
Not sure if zero was correct, but with it it's working.
~~~
ajb@polly:/clients/common/dosemu2.git$ python3 test/test_dos.py MSDOS622TestCase.test_mfs_fcb_rename_simple
Test MS-DOS-6.22 MFS FCB file rename simple                                      ... ok (  3.42s)

----------------------------------------------------------------------
Ran 1 test in 3.434s

OK
ajb@polly:/clients/common/dosemu2.git$ git diff
diff --git a/src/dosext/mfs/mfs.c b/src/dosext/mfs/mfs.c
index 2f5d61949..dc03eb13e 100644
--- a/src/dosext/mfs/mfs.c
+++ b/src/dosext/mfs/mfs.c
@@ -804,7 +804,7 @@ static int do_mfs_rename(const char *dname, const char *fname,
             return ACCESS_DENIED;
     }
 #ifdef HAVE_RENAMEAT2
-    err = renameat2(dir_fd, fname, -1, fname2, RENAME_NOREPLACE);
+    err = renameat2(dir_fd, fname, -1, fname2, 0);
 #else
     err = access(fname2, F_OK);
     if (err)  // err means no file
~~~

**Comment by stsp** [comment]
Cool, could you please check what errno
does it return?

**Comment by andrewbird** [comment]
RENAME_NOREPLACE: err = -1

**Comment by andrewbird** [comment]
and errno
RENAME_NOREPLACE: errno = Invalid argument, 22

**Comment by stsp** [comment]
Should now be fixed.
Lets concentrate on https://github.com/dosemu2/fdpp/issues/152
for a while. :)
Would you like to add the missing tests?

**Comment by andrewbird** [comment]
Thanks, that works fine. Yes I'll look at adding more locking tests.

**Comment by stsp** [comment]
Can we also now disable the attr tests
as the remaining seems fixed?

**Comment by andrewbird** [comment]
Can you think why the `test_mfs_ds2_file_seek_2_position_forward_large` test would have got slower recently, as I'm now hitting test timeout. I notice that it's also over 10 secs on NFS, but < 2 secs on ext4. 

Yes, I think we can disable those setfattrs tests on MFS as only the RDONLY bit was being tested on MFS anyway.

**Comment by stsp** [comment]
You mean it became slower only on nfs?
Because <2secs means the normal invocation.

**Comment by stsp** [comment]
One thing that could (in theory) make things
slow, is flock() locks. I do not use LOCK_NB
with them, so they could block (unlike fcntl
locks where I use the non-blocking version).
But I guess its not your case, as they were in
the lock branch from the very beginning.

**Comment by andrewbird** [comment]
> You mean it became slower only on nfs?

Not sure, for all I know it might have been taking 9.9 secs before and now it takes 10.1, but the same test on ext4 takes less than 2 secs.

I'm probably going to use an env variable to steer the test directory to somewhere on ext4. I doubt that many people use dosemu on NFS hosted home directories (I could be wrong) so I'm probably making things too hard for myself, in any case it will allow the testing here of xattrs should anyone add that support.
