### ISSUE TITLE
handle local config via include

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1348]
Currently there are disputes how the local
config should be called:
https://github.com/dosemu2/fdpp/issues/154#issuecomment-735765667
Simply renaming the local config may be
an offence to the users.
Alternative approach is to just add something
like 
```
$_include = "~/.dosemu/dosemurc"
$_include = "~/.dosemu/.dosemurc"
$_include = "~/.dosemurc"
```
to /etc/dosemu/dosemu.conf.
Then we will pretend there is officially no
local config at all, but the user can have
one or many, with whatever name he wants.
Of course the local config should also be
able to include anything else.

**Comment by andrewbird** [comment]
I don't know that there's really any dispute here, certainly not on my part. I would think though that having this include method just adds to the potential sources of bad config to consider when trying to help someone debug their problem.

**Comment by stsp** [comment]
3 different config names do not help
much either.
Note that all options in dosemu.conf are
by default commented out. So even if
the user didn't update dosemu.conf, these
settings will work, and he won't see them.
Same as if they are hard-coded (as now).

**Comment by stsp** [comment]
As for easier debugging, here's the proposal:
`$_include_either "~/.dosemu/dosemurc ~/.dosemu/.dosemurc ~/.dosemurc"`
This directive will make sure that exactly
one of the specified files, does exist. If
not - if will abort and write proper diagnostic.

**Comment by andrewbird** [comment]
> Same as if they are hard-coded (as now).

If `~/.dosemu/dosemurc`,  `~/.dosemu/.dosemurc`, `~/.dosemurc` all exist are they each parsed or is just one?

**Comment by stsp** [comment]
You are late. :)
See above comment.

**Comment by andrewbird** [comment]
:smile:

**Comment by jschwartzenberg** [comment]
It used to be common practice to have `.somethingrc` as the user config in the homedir. If things are moved around, I'd say look into using `.config` and `.local`.

**Comment by stsp** [comment]
Its convenient to have a config
per DOS installation. We have
now `dosemu -dos <dos_name>`
which also selects another config.

**Comment by stsp** [comment]
This is probably a bad idea as in
this case the config is no longer
relocatable. Currently we can select
its location with -f, but with explicit
include we probably can't.
