### ISSUE TITLE
DOSEMU2 crashes while loading PC/GEOS (w/ FDPP & COMCOM32)

### ISSUE THREAD

**Issue by bolle732** [dosemu2/dosemu2#1349]
**Describe the bug**
Since the commit 53601bbff43b1fe5a9f7f59dc98d194aef72b656, I've several problems on my installations.

Using FDPP and COMCOM32, I get errors on startup of DOSEMU2:
```
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : Datei oder Verzeichnis nicht gefunden open /dev/snd/midiC0D0 d
ERROR: INT21: redirecting C: failed (err = 15)
ERROR: INT21: redirecting D: failed (err = 15)
ERROR: INT21: redirecting E: failed (err = 15)
ERROR: INT21: redirecting F: failed (err = 15)
```

When starting PC/GEOS, DOSEMU2 crashes:
```
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 536, len 1
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 1, len 1
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 252, len 1
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 6295, len 5
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 6300, len 13
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 2007, len 1
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 6313, len 1
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 1, len 1
ERROR: fatfs write ignored: dir <HOME>/.dosemu/drive_c, sec 252, len 1
ERROR: unexpected CPU exception 0x06 err=0x00000000 cr2=00000000 while in vm86 (DOS)
Real-mode state dump:
EIP: c102:00008a25 ESP: 02f5:000011d6  VFLAGS(b): 01011 01000010 10010011
EAX: 000002ae EBX: 5c3a8365 ECX: 4552fe7a EDX: 3b6e1352 VFLAGS(h): 000b4293
ESI: 00409804 EDI: 000011d5 EBP: 0000eb12 DS: e803 ES: 02f5 FS: 6e67 GS: 0a75
FLAGS: CF AF SF IF NT RF VM VIF  IOPL: 0
STACK: c1 05 03 e8 16 eb 5c 02 02 7a -> d5 11 08 00 d9 11 00 00 dd 11 
OPS  : 00 f7 1c 57 fe 06 32 f7 1c 57 -> fe 16 32 f7 1c 57 fe 16 32 00 
```

**To Reproduce**
Checkout DOSEMU2 53601bbff43b1fe5a9f7f59dc98d194aef72b656 or newer, use a current FDPP and COMCOM32.

Start DOSEMU2 by simply typing "dosemu". Load PC/GEOS.

**Attach program/game binaries or provide an URL**
It can be provided on request.

**Attach the log**
Will provide a new one if needed. Please let me know the debug options to use.
[boot.log](https://github.com/dosemu2/dosemu2/files/5617343/boot.log)

**A regression?**
Yes, it worked smooth with the commit 78a2a90305c9b9feaab056d1fbec400340a386df before.

**Additional info**
cat  ~/.dosemu/drive_c/userhook.sys 
```
FILESHIGH=120
STACKS=0
```

With FreeDOS KERNEL.SYS and COMMAND.COM, this errors and the crash does not occur, but PC/GEOS get stalled / hangs on some operation, I think mostly related to file operations.

**Comment by stsp** [comment]
I can only suspect a bad build.
If redirector won't work (as it is for you),
people would complain.

**Comment by stsp** [comment]
It may also be some non-standard setup,
so that your config/autoexec or maybe
dosemu tools are not up-to-date (were
copied by you somewhere and are not
updated).

**Comment by bolle732** [comment]
Thanks for your reply. Yes, there has been a problem in with my build here.

The redirector errors are gone, after purging the `dosemu` and `fdpp` folders in `/usr/local/share`. Then I rebuilded and reinstalled both from a clean checkout.

Now, PC/GEOS started to work with FDPP and COMCOM32 again.

With FreeDOS, the hang was due to the option `FULL` when loading `UMB.SYS`. After removing this option, PC/GEOS worked again with FreeDOS kernel and COMMAND.COM.

So, this ticket can be closed.

**Comment by stsp** [comment]
But there is no /FULL in fdconfig.sys.
Its only in fdppconf.sys which is never
loaded by freedos.
So you messed up things quite heavily.

**Comment by stsp** [comment]
Have you fixed the stacks= bug in geos?

**Comment by bolle732** [comment]
Maybe I've not been very clear.

I have 2 setups:

1. Everything default in ~/.dosemu with FDPP and COMCOM32. Only the 2 lines for FILES and STACK in the userhook.sys
2. A fully independent directory with FreeDOS. All *.com and *.sys are copied locally and I'm using my own CONFIG.SYS / AUTOEXEC.BAT

The option FULL has been in the second setup with my own CONFIG.SYS.

No, the problem with STACKS= is still not fixed. The developers are currently focusing to DOSBOX for using as the default environment for debugging :( But I'll keep poking.

Still have the hope that FDPP / CC32 will be able to replace the FreeDOS as my default setup at one day ;-)

**Comment by stsp** [comment]
> The option FULL has been in the second setup with my own CONFIG.SYS.

Why don't you use the one provided with
dosemu2? We provide sample configs for
every DOS.

> Still have the hope that FDPP / CC32 will be able to replace the FreeDOS as my default setup at one day ;-)

What is cc32 and what is "one day"?
Doesn't this cc32 work with fdpp already?

**Comment by bolle732** [comment]
I use my own CONFIG.SYS / AUTOEXEC.BAT to have the optimal setup for running PC/GEOS...

Ahm, CC32 should be stand for COMCOM32. Sorry, if this hasn't been obvious...

Currently with FreeDOS, I have a lot more upper memory available then what I'm able to squeeze with FDPP. Reasons are mostley that with FDPP I can't set `$_dpmi = (0)` and `$_ems_uma_pages = (0)`.

**Comment by stsp** [comment]
> Ahm, CC32 should be stand for COMCOM32. Sorry, if this hasn't been obvious...

Ah, maybe it was for someone, but I
started to think into a direction of C Compiler=CC.

> Currently with FreeDOS, I have a lot more upper memory available then what I'm able to squeeze with FDPP.
> Reasons are mostley that with FDPP I can't set $_dpmi = (0) and $_ems_uma_pages = (0).

But in the past you could!
What changed?
Have you tried "umb.sys /FULL"?

**Comment by bolle732** [comment]
I remember that you told me sometimes that DPMI is a requirement for FDPP/COMCOM32. I still can set ` $_dpmi = (0)` for FreeDOS.

Loading `umb.sys` with or without `/FULL` doesn't change anything for me on the current git.

Under FDPP/COMCOM32, setting `$_ems_uma_pages = (0)` in `dosemurc` makes PC/GEOS crashing on startup with

```ERROR: general protection at 0x7fa9023dc2af: 0```

 or hangs on black screen with:

```ERROR: vgabios: unimplemented, biosfn_write_teletype:623```

**Comment by stsp** [comment]
Not sure why /full doesnt work for you,
as it definitely does for me.
Try to update from git again and disable
ems completely.
