### ISSUE TITLE
kvm: qemm mft hangs on start under pc-dos

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1350]
**Describe the bug**
Hangs.

**To Reproduce**
Run mft

**A regression?**
Yes.

**Comment by andrewbird** [comment]
Which version? I remember raising #819 some time ago, but it seemed to be version specific.

**Comment by stsp** [comment]
It says 9.0.
Plus I never had another version.
This one worked.
Well, there is something strange here,
because it works for me properly only
on 1.4.0.8 but not, say, 2.0-pre8.
So if its a regression, it is very old.

**Comment by stsp** [comment]
Well, the behaviour is not quite clear.
On PC-DOS: broken with kvm (works with cpu-emu)
On fdpp: broken permanently
On freedos: works with any settings

**Comment by stsp** [comment]
Opened fdpp ticket: https://github.com/dosemu2/fdpp/issues/155
With that bisect, it works on fdpp+kvm too,
so its good.
Lets keep this one for PC-DOS+KVM breakage.

**Comment by stsp** [comment]
I've found a fix but I don't know why it
is needed. I do not know that code well
enough. I've just found out that on TF
exception the flags are out of sync if
the TF exception was itself provoked
by popf. So I get the right flags from
KVM, and then it works...

@bartoldeman could you please help
explaining that? I do not suppose my
fix is correct.

**Comment by stsp** [comment]
Actually I removed that commit since
its most definitely wrong. But it is still
visible here.
So the problem is: if POPF clears TF,
then TF would remain on stack of the
trap fault, as if it wasn't cleared prior
to the trap.
Maybe it is some VME errata?

**Comment by jharrison03** [comment]
I reported in  #819 that it worked for me, but now it's broken again.

**Comment by stsp** [comment]
Yes, its now broken also in fdpp, so the
breakage should finally be reliable.

Andrew, would you like to write a test-case
for that? Just do 2 POPFs in a row, then NOP.
First POPF sets TF and second one clears.
Make sure the int1 handler was invoked
only once, after the second POPF, but not
after NOP.

**Comment by stsp** [comment]
With such test-case we'll be able to ask
our Intel friend for help. I suspect this is
a kernel's KVM problem again...

**Comment by andrewbird** [comment]
If you are looking for something to add to the test suite I think it'd be better if you write the DOS part as you know what you want exactly, I can wrap it with the python to suit afterwards.

**Comment by stsp** [comment]
Test case:
```
.code16
.text
        .globl  _start16
_start16:

        movw    $0x2501, %ax
        movw    $int1, %dx
        int     $0x21
        pushw   $0x3003
        pushw   $0x3303
        popf
        popf
        nop
        movb    $2, %ah
        movb    cnt, %dl
        addb    $'0', %dl
        int     $0x21
        movb    $'\r', %dl
        int     $0x21
        movb    $'\n', %dl
        int     $0x21
        ret

int1:
        incw    %cs:cnt
        iret

cnt: .word 0
```

Prints 1 with cpu-emu and 3 with kvm.

**Comment by stsp** [comment]
[FLOPPY.img.gz](https://github.com/dosemu2/dosemu2/files/5645804/FLOPPY.img.gz)

Here is the boot floppy that you can
try on both dosemu2 and qemu.
But I have recently updated to fedora
rawhide (big mistake), so qemu doesn't
work for me, as many other things.

Can someone please boot that floppy
on qemu and run tftst.com?

**Comment by stsp** [comment]
Ah, got qemu working more or less...

**Comment by stsp** [comment]
On qemu it says 1 (as it should), but
qemu is not running v86+vme, but rather
unrestricted guest + real mode.
So I don't know how to create similar
testing conditions under qemu.

**Comment by stsp** [comment]
@Baron-von-Riedesel I am sure you have
some memory manager that sets up v86+VME?
[tftst.com.gz](https://github.com/dosemu2/dosemu2/files/5645856/tftst.com.gz)

Can you try that test-case under VME under
qemu both with and without --enable-kvm switch?

**Comment by stsp** [comment]
Ok, can someone run the test-case
on an Intel cpu? So that we know its
not specific to amd.

**Comment by andrewbird** [comment]
I have
~~~
ajb@polly:/clients/common/dosemu2.git$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz
stepping	: 11
microcode	: 0xba
cpu MHz		: 1599.921
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm
vmx flags	: vnmi flexpriority tsc_offset vtpr vapic
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4799.76
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
~~~

Will that do? Can you post the exact qemu cmd lines you use and I'll try your floppy img, please?

**Comment by stsp** [comment]
Under qemu its quite difficult to reproduce,
unless @Baron-von-Riedesel tells us that
his jemm386 uses VME.
Try under dosemu for now.

**Comment by andrewbird** [comment]
So that's just a boot from `a:`?
~~~
ajb@polly:/clients/common/dosemu2.git$ cat test-imagedir/dosemu.conf 
$_force_fs_redirect = (off)
#$_hdimage = "dXXXXs/c:hdtype1 dXXXXs/d:hdtype1 +1"
$_hdimage = ""
$_floppy_a = "dXXXXs/FLOPPY.img:boot"
~~~

I did that, but I end up in freedos install program
![Screenshot_2020-12-05_11-07-05](https://user-images.githubusercontent.com/220835/101240931-60403580-36ea-11eb-8ab3-fb817bf00620.png)
so I exited that without doing anything, and ran tftst.com
![Screenshot_2020-12-05_11-08-52](https://user-images.githubusercontent.com/220835/101240972-85cd3f00-36ea-11eb-815f-ef1a77077361.png)
is that okay?

**Comment by stsp** [comment]
In this comment I uploaded the com file itself:
https://github.com/dosemu2/dosemu2/issues/1350#issuecomment-739057718
so you don't need a boot floppy.

No, its not okey, at least this is not what I
get here. Are you sure its kvm?

**Comment by andrewbird** [comment]
From the log

~~~
Warning: Using V86 mode inside KVM                                              
Conventional memory mapped from 0x7f11a96ed000 to 0x40c78000                    
DPMI memory mapped to 0x40d88000 (reserve) and to 0x42d88000 (main)             
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))          
VID: initializing video sdl                                                     
VID: SDL plugin initialization completed                                        
Registering HWRAM, type=e base=0x4b7ab000 size=0x400000                         
CONF: reserving 4096Kb at 0x4B7AB000 for 'e' (VGAEMU LFB)                       
loading fonts for cp858                                                         
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)                     
Warning: SERIAL $Id$                                                            
Warning: Your fluidsynth is too old                                             
DPMI: mem init, mpool is 140468224 bytes at 0x42d88000                          
Warning: Using DPMI inside KVM                                                  
CONF: detected layout is "uk"                                                   
CONF: detected alternate layout: fr-latin1                                      
TIME: using 9154 usec for updating ALRM timer                                   
MFS: Inside initialization                                                      
dev /clients/common/dosemu2.git/test-imagedir/dXXXXs/FLOPPY.img is an image     
IMAGE auto-sensing                                                              
Warning: WARNING: image filedesc not open                                       
IMAGE auto floppy /clients/common/dosemu2.git/test-imagedir/dXXXXs/FLOPPY.img; t=80, h=2, s=18
CONF: freeing region for 'E' (EMS page frame)                                   
~~~

**Comment by stsp** [comment]
Hhhrrrrmmmm...
So can you try that w/o nested virtualization then?

**Comment by andrewbird** [comment]
Do you mean a boot from that floppy on metal, or something else?

**Comment by stsp** [comment]
Just dosemu2, but w/o nesting it under
qemu as you did before.

**Comment by andrewbird** [comment]
No, I didn't nest anything, that's dosemu running on my desktop machine.

**Comment by stsp** [comment]
OK, so this bug is somehow amd-specific.
Anyone else here with AMD cpu to check?
It would be good to find out if it is AMD-FX
specific or happens with any AMD.

**Comment by Baron-von-Riedesel** [comment]
> unless @Baron-von-Riedesel tells us that his jemm386 uses VME.

jemm386 < v5.79 used VME by default.
jemm386 v5.79+ uses VME optionally, it's off by default. Can be set from the cmdline: "jemm386 vme"

**Comment by Baron-von-Riedesel** [comment]
> OK, so this bug is somehow amd-specific.
> Anyone else here with AMD cpu to check?

Isn't there a known bug with some AMD cpus that report they support VME but actually did not?

**Comment by stsp** [comment]
VME works, but the problem here is that
if you do POPF that clears TF, then an
interrupt gate (of int1) pushes the flags
with TF bit still set.
Would you be able to run the aforementioned
com file under VME to see how it behaves
with jemm386?

**Comment by Baron-von-Riedesel** [comment]
> Would you be able to run the aforementioned com file under VME to see how it behaves with jemm386?

Yes, it always displays 1 (real-mode, v86-mode with/without VME)

cpuinfo:
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 113
model name	: AMD Ryzen 5 3600 6-Core Processor

**Comment by andrewbird** [comment]
I also tried my old Amd server machine and got
~~~
ajb@oliver:/export/clients/common/dosemu2.git$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 6
model name	: AMD Turion(tm) II Neo N54L Dual-Core Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs spectre_v1 spectre_v2
bogomips	: 4392.82
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
~~~
~~~
ERROR: /usr/local/lib/dosemu/libplugin_X.so: cannot open shared object file: No such file or directory
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)                         
Warning: Using V86 mode inside KVM                                              
Conventional memory mapped from 0x7f41ef828000 to 0x40b2c000                    
DPMI memory mapped to 0x40c3c000 (reserve) and to 0x42c3c000 (main)             
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))          
ERROR: /usr/local/lib/dosemu/libplugin_term.so: cannot open shared object file: No such file or directory
VID: Video set to Video_none                                                    
Registering HWRAM, type=e base=0x4b65f000 size=0x400000                         
CONF: reserving 4096Kb at 0x4B65F000 for 'e' (VGAEMU LFB)                       
loading fonts for cp437                                                         
ERROR: CPI not found for cp437                                                  
CONF: reserving 4Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)                      
Warning: SERIAL $Id$                                                            
ERROR: /usr/local/lib/dosemu/libplugin_alsa.so: cannot open shared object file: No such file or directory
ERROR: /usr/local/lib/dosemu/libplugin_alsa.so: cannot open shared object file: No such file or directory
DPMI: mem init, mpool is 140468224 bytes at 0x42c3c000                          
Warning: Using DPMI inside KVM                                                  
ERROR: /usr/local/lib/dosemu/libplugin_XKmaps.so: cannot open shared object file: No such file or directory
ERROR: Unable to open console or check with X to evaluate the keyboard map.     
Please specify your keyboard map explicitly via the $_layout option. Defaulting to US.
TIME: using 9154 usec for updating ALRM timer                                   
MFS: Inside initialization                                                      
dev /export/clients/common/dosemu2.git/test-imagedir/dXXXXs/FLOPPY.img is an image
IMAGE auto-sensing                                                              
Warning: WARNING: image filedesc not open                                       
IMAGE auto floppy /export/clients/common/dosemu2.git/test-imagedir/dXXXXs/FLOPPY.img; t=80, h=2, s=18
~~~

~~~
A:\>dir
 Volume in drive A is FD-SETUP
 Volume Serial Number is 3533-1019
 Directory of A:\

FDSETUP              <DIR>  12/20/2016  8:57a
AUTOEXEC BAT         1,870  12/20/2016  8:57a
COMMAND  COM        66,945  08/28/2006 10:38p
FDCONFIG SYS           225  12/20/2016  8:57a
KERNEL   SYS        46,685  05/11/2016  9:42p
SETUP    BAT         6,398  05/06/2016 10:29a
TFTST    COM            45  12/05/2020 12:59a
         6 file(s)        122,168 bytes
         1 dir(s)         128,512 bytes free
A:\>tftst
1
A:\>

~~~

**Comment by stsp** [comment]
OK, what kernels are those?
I so far tried on
kernel-5.10.0-0.rc6
kernel-5.6.6

**Comment by andrewbird** [comment]
Server Ubuntu 16.04 `AMD Turion(tm) II Neo N54L Dual-Core Processor` has `4.4.0`
Desktop Ubuntu 20.04 `Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz` has `5.8.0`

**Comment by stsp** [comment]
Ok, for me it would be difficult to test 4.4.0.
Lets try the other way around.
Baron, could you please upload the qemu
image with vme so that I try it on my kernel?

**Comment by Baron-von-Riedesel** [comment]
Sorry, I didn't follow this thread, so I was unaware that you spoke of running your test prog under qemu.

My qemu version (v3.1.0) does not offer the VME feature (at least I don't know the option how to make qemu offer it), so I cannot activate VME with Jemm386.

**Comment by stsp** [comment]
On what were you running the test then?

Well, the option should be `--enable-kvm` -
hope it works on such an old qemu as yours.
Anyway, what about uploading a floppy image?

**Comment by Baron-von-Riedesel** [comment]
> On what were you running the test then?
On the real machine of course.

> Well, the option should be --enable-kvm -
Well, THAT option is set and active. I talked about the VME feature.

> Anyway, what about uploading a floppy image?
I have none handy. I start qemu with an ms-dos.qcow2 HD image ( and a raw HD image as disk 2, on which I copy the files to test ).

**Comment by stsp** [comment]
> Well, THAT option is set and active. I talked about the VME feature.

That one should enable all features supported
by your CPU under nested virtualization. Which
should also include VME, but with such an old
qemu who knows.

**Comment by stsp** [comment]
OK, I created the qemu image with "jemm386 vme"
and it says "Jemm386 loaded" (among other things),
so I suppose it doesn't have a  problem with VME here.
And my test shows 1, so this is getting really weird.
Then lets examine my own understanding.
Am I right that the interrupt redirection bitmap in
TSS does not affect the trap exception? I mean,
your jemm386 has a handler that reflects that
exception back to real-mode interrupt, right?
Or is there some way of directing the trap
exception directly to rm int?

**Comment by stsp** [comment]
Oops!
jemm386.exe says "VME is off", and yet
no errors on loading with "vme" flag.
Wtf?

**Comment by Baron-von-Riedesel** [comment]
> Oops! jemm386.exe says "VME is off", and yet no errors on loading with "vme" flag.Wtf?

:)). Yes, that was implemented to "confuse the Russians".

You simply have to run jemm386 on the command line to get the real settings. jemm386 won't activate the VME bit in CR4 if the cpu doesn't support this feature.

**Comment by stsp** [comment]
You think ignoring command-line option
confuses only them?

Anyway, the right command to enable VME
is: `--enable-kvm -cpu host`.
Still my test says 1.
Does the trap exception go via an interrupt
gate in your code?

**Comment by Baron-von-Riedesel** [comment]
> Does the trap exception go via an interrupt gate in your code?

Yes ... that is, if the TSS interrupt redirection bitmap entry for INT 1 is 1 ( and it should be 1), the Virtual 8086 handler is called directly, of course, and no switch to the v86-monitor is done - that's the purpose of VME, after all.

**Comment by stsp** [comment]
Grr, I can't make any sense from that test-case,
and now also from what you say, all together.

> Yes ... that is, if the TSS interrupt redirection bitmap entry for INT 1 is 1 ( and it should be 1),
> the Virtual 8086 handler is called directly

This contradicts to that description:
http://www.rcollins.org/ddj/Mar98/Mar98.html
`and its corresponding bit is set in the interrupt redirection bitmap, an interrupt will fault`
So 1 means fault, not the other way around.

> of course, and no switch to the v86-monitor is done - that's the purpose of VME, after all.

Again, doesn't match what I read on the
same URL above:
`Hardware interrupt (IRQs) and CPU-generated exceptions are not influenced by the interrupt redirection bitmap.`
So I would say the trace exception should
always go through an interrupt gate.

**Comment by stsp** [comment]
But maybe I happened to have the CPU
that agrees with you, and not with manuals...
Because it doesn't seem to behave as advertised.

**Comment by Baron-von-Riedesel** [comment]
> So 1 means fault, not the other way around.

You're right here, sorry!

However, my tests reveal that not all events that cause an INT 01 are "exceptions". I enabled debug displays in Jemm386 and can tell which event is redirected to protected-mode and which isn't. For example, if you setup a debug register (DR0) for a watchpoint in v86-code, and the address has been hit, the monitor displays "exc 01 occured ..."  - obviously the protected-mode code has been called. OTOH, if the trace flag is set, the monitor remains silent ...

**Comment by stsp** [comment]
Can you make sure that this depends
on an appropriate int bitmap bit? Or
maybe it depends on something else.

**Comment by Baron-von-Riedesel** [comment]
Again sorry, I made a mistake: I had not activated all relevant displays ( exc 0..7 don't push an error code, and are therefore handled slightly differently in the monitor ). So it's as the docs are telling: (all) exceptions are routed from v86 to protected-mode, no matter what VME or the interrupt bitmap  are telling.

**Comment by stsp** [comment]
I think you can still have int3 to honour
the bitmap bit, if you do `cd 03` instead of `cc`.
But its all legacy anyway.
One needs to try the arm programming to
see just how legacy is x86. :)

**Comment by Baron-von-Riedesel** [comment]
>  if you do cd 03 instead of cc

I did test that. Yes, opcode [B]CD 03[/B] isn't logged if VME is on, so it's no exception. And the ICEBP (F1) always causes an exception 01.

**Comment by stsp** [comment]
For some very strange reason our code was
using trap gate instead of an interrupt gate.
Still my test says "3" and I don't know how to
reason it up.

So next question: if we have DPL=0 in IDT,
then will it GPF from v86 or will work?

**Comment by Baron-von-Riedesel** [comment]
> So next question: if we have DPL=0 in IDT, then will it GPF from v86 or will work?

Jemm sets descriptor attributes in IDT to 0xEE ( 386 interrupt gate, DPL=3 ). I haven't tried DPL=0, but I vaguely remember having read in the AMD docs that DPL for interrupt gates is ignored, because due to the nature of interrupts they can occur at any time and hence it would be "silly" to make it depending on DPL.

**Comment by stsp** [comment]
Well, maybe it is ignored when HW
interrupt comes, but I don't believe it
can be ignored for sw interrupts either.
And the question is here because kvm
in dosemu seems to be using DPL==0
for tf and DPL==3 for cc/int3, which is
more than strange!

**Comment by stsp** [comment]
Well the thing is, the flags are popped
correctly, except for the TF flag. So its
not like the old value, no. Someone just
forcing the TF flag back. Which would
be very strange from the CPU bug, and
looks more like a software bug, but where...

**Comment by stsp** [comment]
So if I replace popf with iret this way:
```
        pushw   $0x3003
        pushw   %cs
        pushw   $1f
        pushw   $0x3303
        popfw
        iretw
1:
        nop
```
then everything works as expected.
So the problem is specific to popf rather
than any environment. Also I checked
the saved value right in the beginning
of the interrupt handler (by backing it up
to a different location) and the TF is set
there from the very beginning. So no one
could set it there by mistake.

So its almost 100% a cpu bug, but why
it doesn't manifest with jemm386 is something
we'll never know.

I'll apply some hack to just clear the TF flag.

**Comment by stsp** [comment]
Hmmm!
But if I replace popfw with popfl, then it
works fine!
Now does this make any sense? :)

**Comment by stsp** [comment]
So this works:
```
        pushl   $0x3003
        pushl   $0x3303
        popfl
        popfl
        nop
```
Progress? :)

**Comment by stsp** [comment]
Minimized the difference.
This works:
```
        pushl   $0
        pushw   $0x3303
        popfw
        popfl
```

This doesn't:
```
        pushl   $0
        pushw   $0x3303
        popfw
        popfw
        popfw
```

And if we are to suspect some higher
flags affecting this, then no, as this
doesn't work just as well:
```
        pushl   $0
        pushl   $0x3303
        popfl    ; clear higher eflags word
        popfw
        popfw
```

So the problem is with 16bit popf
(probably in combination with 32bit
idt gate).

**Comment by stsp** [comment]
Well, popfl (aka popfd) is not
accelerated by VME at all, so
it works simply because it doesn't
go to int1 gate, but rather GPFs.
So that finding doesn't give anything...

**Comment by stsp** [comment]
Added the hack to clear TF manually,
If someone have any ideas to check, I will. :)

**Comment by stsp** [comment]
Btw, Andrew, please add this to a test-suite.
The successful run is when the test prints "1"
and no "KVM: applying TF fixup" on terminal.
That way we'll find more info about the bug.
If it is not only on my CPU, we may eventually
see the test failure.

**Comment by andrewbird** [comment]
Do you have the final test source code, plus the dosemu.conf for testing? That's because it would be nicer to build the binary as part of the test.

**Comment by stsp** [comment]
The one posted here should do.
Its nore or less final, please build it.

**Comment by andrewbird** [comment]
I had to tweak the test slightly to give myself some text around the result to make it easily identifiable, I hope it's still valid.

I'd like to test under kvm and emulation. What's the magic incantation for dosemu.conf, is it ?
##### kvm
~~~
$_cpu_emu = "off"                                                               
$_cpu_vm = "kvm"                                                                 
~~~
##### emulation
~~~
$_cpu_emu = "off"                                                               
$_cpu_vm = "emulated"                                                                 
~~~

I guess I don't have to worry about dpmi virtualisation?

I just raised PR #1360 for review

**Comment by stsp** [comment]
```
$_cpu_emu = "off"                                                               
$_cpu_vm = "emulated"                                                                 
```

This is obviously wrong.
I suspect it will work the way you
expect because $_cpu_vm overrides
$_cpu_emu.

**Comment by andrewbird** [comment]
To be honest I find that cpu config quite confusing. Should it be 
~~~
$_cpu_emu = "vm86"                                                               
$_cpu_vm = "emulated"
~~~

and 
~~~
$_cpu_emu = "vm86"                                                               
$_cpu_vm = "kvm"
~~~

I could keep guessing, or you could just tell me :smile:

**Comment by stsp** [comment]
$_cpu_emu is disabled and ignored when
$_cpu_vm = "kvm". There is no any magic here. :)
Its only needed for cpu-emu.

**Comment by stsp** [comment]
> $_cpu_emu = "vm86"

Ah, I understand the confusion.
It should have been "v86", not "vm86".
Not sure if its a good time to change now...

**Comment by stsp** [comment]
> Not sure if its a good time to change now...

Well, there will be no better time any later.
Filled #1361.

**Comment by jharrison03** [comment]
I'm not sure if this was closed because it was fixed, but it hadn't worked for me several weeks ago but it works as of tonight (with KVM).
