### ISSUE TITLE
$_X_font mute sound?

### ISSUE THREAD

**Issue by j2969719** [dosemu2/dosemu2#1351]
For some reason sound disappears for me after setting $ _X_font in .dosemurc.
https://pastebin.com/1fWTDbWE

**Comment by stsp** [comment]
Because in this case it switches from
SDL to X.
You need to build dosemu2 with libao
support, or you can use -S to force SDL
for sound.

**Comment by stsp** [comment]
In fact, there seems to be already an
SDL fall-back if libao is missing.
So can it be that libao is compiled in
for you, but somehow doesn't work?
Please attach the -D9+S log
(yours doesn't have -D9).

**Comment by j2969719** [comment]
dosemu -S do the trick, thanks

sound missing only when launch dosemu w/o -S

[boot.log](https://github.com/dosemu2/dosemu2/files/5628960/boot.log)

$ls /usr/lib/dosemu/
libplugin_alsa.so        libplugin_json.so    libplugin_term.so
libplugin_console.so     libplugin_ladspa.so  libplugin_XKmaps.so
libplugin_fdpp.so       **libplugin_libao.so**   libplugin_X.so
libplugin_fluidsynth.so  libplugin_sdl.so
libplugin_gpm.so         libplugin_slirp.so

**Comment by stsp** [comment]
Could you please retry with current git?
I added more debug output.

**Comment by j2969719** [comment]
sure
> ERROR: libao: unable to open output device

[boot.log](https://github.com/dosemu2/dosemu2/files/5629175/boot.log)

**Comment by j2969719** [comment]
yep, it seems libao.conf simply rollbacked to system defaults at some point and i didn't notice

sorry

**Comment by stsp** [comment]
Off-topic: your avatar says China, but from
the log I can see you current locale. :)
Привет.

**Comment by j2969719** [comment]
Off-topic: и без локали по ломанному английскому легко сдиванонить
и вам привет)
