### ISSUE TITLE
Can't append to Foxpro .fpt memo files

### ISSUE THREAD

**Issue by severach** [dosemu2/dosemu2#1352]
**Describe the bug**
Adding new data to .fpt file causes out of disk space error

**Attach program/game binaries or provide an URL**
`mmodemo.prg` Foxpro DOS 2.6
````
* Can't append to Foxpro .fpt memo files

clos data
erase ("mmo.dbf")
erase ("mmo.fpt")
erase ("mmo.dbt")

create table ("mmo") ( ;
  test m ;
)
append blank
repl test with "test"
clos data
use mmo
append blank
* This replace crashes
* Not enough disk space for
* D:\GC001V\MMODEMO\MMO.FPT
repl test with "test2"
clos data
erase ("mmo.dbf")
erase ("mmo.fpt")
erase ("mmo.dbt")
````

**A regression?**
Works  in a6324821e86c6cd3acf77ddda76bda187cad00db 2020-11-19 21:50 +0000 Andrew Bird           [refs/pull/1334/head] Travis: Add file set attribute tests
Broken in a030d0128b0b897cad1930bca0947ef3d31d2564 2020-11-20 14:21 +0300 Stas Sergeev          Merge pull request #1334 from andrewbird/travis-ci-38

**Comment by stsp** [comment]
Please provide -D9+dDi# log and try to
bisect to 1 particular commit.
Is this with fdpp?

**Comment by stsp** [comment]
Please try branch "mfs".
Maybe I've found some suspicious code.

**Comment by severach** [comment]
[chris@fujitsu dosemu2]$ git bisect good
984431f5b3fe61e66f2565111e7ce281dbce5e75 is the first bad commit

Freedos.

[Issue#1352.zip](https://github.com/dosemu2/dosemu2/files/5631464/Issue.1352.zip)

No crash on the mfs branch.

**Comment by stsp** [comment]
> No crash on the mfs branch.

What does this mean, no crash?
Do you confirm that the problem is fixed there?
Because the commit you point to, have
nothing to do with what I tried on mfs
branch, so I am puzzled.

**Comment by severach** [comment]
mmodemo and my production memo files are working on the mft branch. None of my commits seem to be related.

**Comment by stsp** [comment]
OK, I take it as this is now fixed.
