### ISSUE TITLE
Foxpro is incompatible with comcom32

### ISSUE THREAD

**Issue by severach** [dosemu2/dosemu2#1355]
Launching unix xsel within Foxpro DPMI session crashes DOSEMU on second Foxpro run

**Describe the bug**
Launch Fox, run xsel, quit Fox, launch Fox, DOSEMU window closes

**To Reproduce**
````
$ echo 'xsel -bi < /tmp/unix.sh' > /tmp/unix.sh
$ killall xsel
C:\>unix bash /tmp/unix.sh
C:\>fox
# Fox does not crash when xsel is launched from DOS
quit
$ killall xsel
C:\>fox
!unix bash /tmp/unix.sh
quit
C:\>fox
# DOSEMU window may close on launch or on quit
quit
````

**A regression?**
DOSEMU crashes with fdpp+comcom32. Works good with with FreeDOS.

**Comment by stsp** [comment]
This is a foxpro bug actually.
It eats up all available memory and then
no wonder comcom32 can't work...
I added a work-around to have 4Mb reserved
for comcom32.
But it would be better if you report the like
bugs to foxpro, not here.

**Comment by severach** [comment]
Foxpro DOS 2.6 development ended in 1992. The time for bugs is long past. There are no newer or older versions of any value.

**Comment by stsp** [comment]
That would be impossible, as pharlap of
1992 would not be compatible with dosemu.
And indeed, winworld lists 2.6 as 1994 and
also offers 2.6a (and 3.0 but for windows).
