### ISSUE TITLE
rework $_cpu_emu option

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1361]
This option didn't change when $_cpu_vm and
$_cpu_vm_dpmi were added, and now it only
confuses people. No one understands how (and
why) do they work in combination.

I think it should now only select between "jit"
and "sim", and the rest should be deduced from
the 2 aforementioned options.

**Comment by andrewbird** [comment]
I think it's the comment that confuses me
~~~
# Usage of cpu emulation: "off" (default on x86-32),                            
# "vm86" - emulate only v86 (default on x86-64) using JIT back-end.             
# "vm86sim" - uses simulation for v86.                                          
                                                                                
# $_cpu_emu = "off"                                                             
~~~

So am I right in saying that:
 1. `$_cpu_emu` now only has effect when `$_cpu_vm` is set to emulated (or auto has selected emulated)?
 2. `$_cpu_emu` now only has two proper values `vm86` and `vm86sim`?
    - it would be really nice to rename these to 'jit' and 'sim', as you suggest
 3.  `$_cpu_emu = "off"` default value is bogus, should be one of `vm86` or `vm86sim`?
 4.  `$_cpu_emu` 'Usage of cpu emulation' comment, could be more properly described as 'Type of cpu emulation'?
 5.  Comment / value section ordering in dosemu.conf is misleading, coming first in the file it looks like `$_cpu_emu` is the primary control knob, whereas actually it is only in effect if `$_cpu_vm` or `$_cpu_vm_dpmi` is set to emulated?

**Comment by stsp** [comment]
> $_cpu_emu now only has effect when $_cpu_vm is set to emulated (or auto has selected emulated)?

This is mostly correct, except that I think
there is some untrivial logic that allows
$_cpu_emu to control other 2 options
when they are commented out. Which
is why it is/was fine for it to be before others.
And you can still use it as you did on dosemu1,
unless you uncomment other 2.
But this all just adds the confusion and
difficult to understand code.

> $_cpu_emu = "off" default value is bogus, should be one of vm86 or vm86sim?

No because of the above hack.
It can control other 2 options, so "off"
was good for a default. But its purely
for backward compatibility, and should
be changed.

> $_cpu_emu now only has two proper values vm86 and vm86sim? 

Also "full" and "fullsim".

> $_cpu_emu 'Usage of cpu emulation' comment, could be more properly described as 'Type of cpu emulation'?

Yes, because "Usage of CPU emulation" was
already off-loaded to other 2 options. This one
was just getting the compatibility hacks added
instead of being fully rewritten. User-visible and
programmer-visible problems are very different,
so I just missed that one when it was much easier
to address than now.
