### ISSUE TITLE
Mouse cursor desynchronized in terminal mode

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1371]
**Describe the bug**

Mouse cursor in term mode can become desynchronized . This isn't specific to any particular program, but I've found a shareware program that makes it easy to reproduce reliably.

**To Reproduce**

Steps to reproduce the behaviour:

- Run `dosemu` in term mode with mouse enabled.
- Run `thedraw.exe`
- Left click on the screen, move the mouse then press Escape.
- The mouse cursor is now desynchronized.

Video demonstration:

![dosemu-term-mouse](https://user-images.githubusercontent.com/123814/102721678-2c037200-42b1-11eb-855e-7821e98871a4.gif)
 

**Attach program/game binaries or provide an URL**

[TheDraw 4.6.3](http://artscene.textfiles.com/viewers/dos/tdraw463.zip)

**Additional info**

This patch seems to fix it, but I don't really understand why, I was just experimenting to understand how the mickeys are calculated. Perhaps it's a useful clue to someone who actually understand how it works 😀

```diff
diff --git a/src/base/mouse/mouse.c b/src/base/mouse/mouse.c
index 204c45de8..23ba6742b 100644
--- a/src/base/mouse/mouse.c
+++ b/src/base/mouse/mouse.c
@@ -1960,6 +1960,7 @@ static void int33_mouse_move_absolute(int x, int y, int x_range, int y_range, 
                dragged.y_range = y_range;
                return;
        }
+       mouse.cursor_on = 1;
        if (mouse.need_resync) {
                /* this is mainly for Carmageddon. It can't tolerate the
                 * mickeys getting out of sync with coords. So we recalculate
```

**Comment by stsp** [comment]
Your fix is almost correct, as we should
force the visibility for those back-ends that
do not support the visibility setting.

> Perhaps it's a useful clue to someone who actually understand how it works

The biggest problem of dosemu2 is that
almost no one can understand how it works,
and the mouse code is one of the examples.
"If you think you understand quantum mechanics, you don't understand quantum mechanics." - R.Feynman

**Comment by taviso** [comment]
Thanks Stas, works perfectly!
