### ISSUE TITLE
Reduce delay on Escape-Key when running in terminal

### ISSUE THREAD

**Issue by ant6n** [dosemu2/dosemu2#1378]
Hio,
I'm scripting an old dos-program to extract data. The running time will probably be 2 weeks or so. So far I'm using dosemu in terminal mode, inside a tmux terminal, controlling it via python using libtmux (which allows sending keys and capturing the terminal). I have to send a lot of escape keys to the software, which appear to have a half-second delay built in. I'm not sure where it comes from, but even when running dosemu inside a normal terminal (without tmux) in ubuntu 20.04, I'm getting the delay. It probably has something to do with waiting for modifier-keys. Running the software in dosbox or dosemu the the GUI-emulator, there is no delay on escape (so it's not the DOS software). I'm trying to get rid of the delay, because it seems about 50% of the time of the script is spent waiting for the software to receive those escape keys.

I can't figure out where the delay comes from (bash? dosemu itself?), so I thought I could perhaps remap the escape key to a different letter for dosemu (e.g. 'Q'), so if I send that key to dosemu it will emulate an escape press. Unfortunately, it appears in -t mode, '$_layout = "load de-latin1"' does not appear to have an effect.

Do you guys have any idea how to get rid of the delay, or some workaround so I can send escape keys to the dos software instantly? Thanks!

ant6n

**Comment by andrewbird** [comment]
I suspect you are running to the VT100 key logic. VT100 uses a sequence of chars started by an Esc to convey various special keystrokes or actions, for example `^[J` (Esc J) clears the screen from current cursor to end. The VT spec doesn't seem to expect an Esc key to be sent on its own, but since it was written VT100 codes have been used for many uses beyond interaction between server and terminals. From what I've seen VT100 terminals and emulators tend to wait for a potential escape sequence for a short time after seeing an Esc. There are some suggestions in the follow-up to this stackoverflow [question](https://stackoverflow.com/questions/2420671/whats-the-vt100-escape-code-for-the-esc-keyboard-key-itself)  (I'd try sending two Esc's first)
I'm not familiar with libtmux myself, but do you need to use Dosemu in terminal slang mode `-t`, you may have better results if you use dumb mode `-td`?

**Comment by andrewbird** [comment]
Actually I just checked some long ago mods (1.2.2) I did for a friend experiencing a somewhat similar problem it seems like I did something similar to what you've suggested. Here's the snippet that would need to go into the libslang mapping.
~~~
+  {"\033[34~", KEY_ESC },              /* ajb real hack - hijack F20 Key for escape
~~~

So being that that was for 1.2.2 , you'd need to change the KEY_ESC for DKY_ESC I think. After which you should be able to send `\033[34~` from your python program each time you want the dos program to receive Esc.

**Comment by stsp** [comment]
One of those legacies we still need to
deal with...
But xterm usually comes up with protocol
extensions to solve these kind of things.
Is there one for that problem?

**Comment by stsp** [comment]
So I can think of 3 possible attack vectors
to that problem, all can be done in parallel:
1. See if xterm have some extension
2. Apply the above hack to at least have a
solution for non-interactive mode.
3. Try to map Esc key to slang, as we do
for other keys, and hope slang will do all
the needed delays himself.

**Comment by andrewbird** [comment]
I see this
https://github.com/dosemu2/dosemu2/blob/4684a2ede64f86baa5509e0ccd98bab3afd1a22d/src/plugin/term/keyb_slang.c#L775-L794
so I definitely think you should try sending EscEsc from your python code before hacking anything else up.

**Comment by stsp** [comment]
OK, so 2 (solution for non-interactive mode) is already there.
As for 1 (xterm extensions) - there is an extension 2017 for
that (probably named by the year of its invention).
I checked and unfortunately it is only implemented
in a kitty terminal emulator, and nowhere else (even
not in rxvt which is quite keen to all extensions).

Still I am pretty sure we need to support kitty then.
Once this is done, we can start asking around about
adding that extension to other terminals.

You can try out an extension by doing:
`echo -e "\033[?2017h"`
After that, Esc press will generate:
`"\033[?2017h"KpAy"`
and release will generate:
`"\033[?2017h"KrAy"`

**Comment by stsp** [comment]
I've also found another extension.
You can do `echo -e "\033 G"`
and then all function/arrow keys
stop generating `^[` escape, and
use something entirely different,
whereas the Escape key remains
unchanged.

**Comment by stsp** [comment]
There seems to be also an extension
7727, but I haven't found any terminals
under linux to support it (seems to be
specific to a few terminals under windows:
mintty, teraterm).

**Comment by stsp** [comment]
Should now be fixed.
Please use double-Esc to avoid time-out.
