### ISSUE TITLE
Mouse desynchronized in WordPerfect when using terminal mode.

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1382]
**Describe the bug**

The mouse in WordPerfect 6 gets desynchronized very easily in terminal mode, most other text mode programs that use the mouse work correctly.

![dosemu-term-mouse](https://user-images.githubusercontent.com/123814/103448794-5a8b3080-4c53-11eb-97ad-f27215195d0e.gif)

**To Reproduce**

Move the mouse around rapidly in an XTerm window while using WordPerfect.

**Attach program/game binaries or provide an URL**

https://winworldpc.com/product/wordperfect/6x-dos

**Attach the log**

[wp-mouse-log.txt](https://github.com/dosemu2/dosemu2/files/5759627/wp-mouse-log.txt)

**A regression?**

Not a regression, I've checked old builds and it has been broken for a long time. 

**Additional info**

I noticed [this](https://github.com/dosemu2/dosemu2/blob/ce87cbeedffbb332ba8815c56a3e64e7fddfef8c/src/base/mouse/mouse.c#L1312) comment in mouse.c:

```c
  /* WP reads mickeys, and then sets the cursor position to make certain
   * it doesn't loose any mickeys.  This will catch that case, and keeps
   * us from breaking all apps under X that set the mouse position.
   */
```

This sounds correct to me, here is a sample from a log:

My mouse position, bottom right corner of a 80x25 terminal:

`XTERM MOUSE: movement detected to pos x=79: y=24`

Translated into 632x192 of a 640x200 canvas, sounds good to me:
```
mouse_move_absolute dx:1 dy:0 mickeys: 0 0 -> 8 0
mouse_move_absolute(79, 24, 80, 25) 639 0 -> 632 192 
MOUSE: move: x=632,y=192
```

```
MOUSE int74 helper
MOUSE: event 1, x 632, y 192, mx 8, my 0, b 0
MOUSE: .........jumping to 9fdc:01b6
```

WP calling Read Mouse Motion Counters
```
MOUSE: int 33h, ax=b bx=0
MOUSE: read mickeys 8 0
Called/ing the mouse with AX=b 
```

I don't understand why it's calling set mouse cursor pos to a different value than we just reported, but it does have it's own "mouse acceleration" setting. I've tried disabling it, and that doesn't change anything.

```
MOUSE: int 33h, ax=4 bx=0
MOUSE: set cursor pos x:639, y:0 delta x:7, y:-192
Called/ing the mouse with AX=4 
```
Regardless, do you think it makes sense to send fake movement when wp does this, to try to get it synchronized? It seems like we can figure out where WP thinks the mouse is, and we know where the mouse actually is.

**Comment by stsp** [comment]
I can't reproduce this with wp62.
But I have to do `emumouse x 8 y 32`
before starting wp, or mouse gets out
of sync immediately.

**Comment by stsp** [comment]
Maybe @emendelson knows why his
WP (which also I have) doesn't have
such problem.

**Comment by taviso** [comment]
Hmm, I was just using the default `emumouse` settings - if I use `x 8 y 32` it's unusably fast.

What do you have for Mx and My?

What is the acceleration factor in WP? (It's listed in file->setup->mouse)

**Comment by stsp** [comment]
The important is not Mx or My
(which are not there for me at all),
and not an acceleration factor (24),
but rather that the driver is "Absolute/Pen".
And yours?

**Comment by taviso** [comment]
Ah-ha, that does seem to fix it - I was using MOUSE.COM, as far as I know I didn't change that setting, it must be the default.

Switching to Absolute/Pen with your `emumouse` configuration does indeed stay synchronized!

**Comment by taviso** [comment]
I guess this is not a dosemu bug, it's just WordPerfect trying to be too smart with the mouse, and there is a workaround.

Thank you Stas, and happy new year!

**Comment by stsp** [comment]
Happy new year!

**Comment by stsp** [comment]
@emendelson Would you like to add the
mouse setup chapter to your wp6 howto?

**Comment by emendelson** [comment]
I saw this for the first time today - almost two years late. I will belatedly add this to my instructions. EDIT: Added.
