### ISSUE TITLE
[Question] Is there a way for a program to detect a dosemu serial port being in use?

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1386]
I'd like to detect whether a serial port in dosemu is backed by an actual connection. Assume I am running with a switch like `-I "serial { com 2 device /tmp/somefile }"`. Bonus would be if it works even for the bootloaded debugger, not just after DOS is loaded.

**Comment by stsp** [comment]
No idea what do you mean.
The number of serial ports is available
in 40:10h BDA area.
The IO port numbers are stored in
40:0 - 40:8 BDA locations.
HTH.

**Comment by stsp** [comment]
Btw, you no longer need to open tickets.
We have discussions now, and they look
rather unused.
So you can ask there instead. :)

**Comment by ecm-pushbx** [comment]
Thanks, I wasn't aware that dosemu only sets up those for ports that are in use. The following works for me:

```
$ dosemu -dumb -K "$PWD" -I "serial { com 2 device /tmp/vptty-dos }" -E "ldebug"
-h (word [40:10] >> 9) & 7
0001  decimal: 1
-dw 40:0 l 8
header     0    2    4    6    8    A    C    E    0123456789ABCDEF
0040:0000  0000 02F8 0000 0000-                    ........
-q
```

**Comment by ecm-pushbx** [comment]
If anyone cares, here's a crude script I dropped into my ~/.dosemu/drive_c/ (as ldebug.sld), which I use with lDebug stored in rxdos.com so that dosemu boots into the debugger. https://ulukai.org/ecm/test/20210114/ldebug.sld

```
:bootstartup
; Welcome to lDebug!
@r ysf |= 4000
if not exists y ldp/ldbgseri.tmp then goto :loopend
r v0 0
:loop
if (v0 >= 8) then goto :loopend
r v1 = word [40:v0]
if not (v1) then goto :loopnext
r dspvp = v1
r v2 = 0
if (v1 == 2F8) then r v2 = 3
if (v1 == 3F8) then r v2 = 4
if not (v2) then goto :loopnext
r dspvi = 8 + v2
r dspvm = 1 << v2
r dspvp .
r dco |= 4000
if (dco & 4000) then goto :end
:loopnext
r v0 += 2
goto :loop
:loopend
if exists y ldp/ldbgterm.tmp then goto :end
if not exists y ldp/fdkernel.sys then goto :end
boot protocol=freedos ldp/fdkernel.sys
if not (rc) then q
:end
rv
```
