### ISSUE TITLE
Date does not rollover after midnight.

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1389]
**Describe the bug**

If you leave DOSEMU running past midnight, the reported date will be incorrect.

This doesn't seem to bother some programs (Lotus Agenda handles it just fine), but others get confused.

**To Reproduce**

Steps to reproduce the behaviour:

- Launch dosemu, run `date`.
- Leave dosemu running until the next day.
- Run `date`, and notice that the time is correct, but the date has not advanced.

**Comment by skitt** [comment]
Nice catch, it reproduces a bug present in MS-DOS in some configurations ;-). (I suspect the reasons are different; midnight handling was done by [function 0x0A](http://www.delorie.com/djgpp/doc/rbinter/id/74/25.html), and DOS 5’s DOSKEY replaced that but forgot to handle midnight...)

**Comment by stsp** [comment]
There is a `$_timemode` setting.
Please see how does it affect the problem.
Can you simulate the problem by adjusting
the system time, rather than to wait for a
midnight?

**Comment by stsp** [comment]
I left dosemu2 hanging overnight, and
here are the results:
```
C:\>ver
comcom32 v0.1
 Source Control Revision ID: alpha-2-18-g7196d34+
C:\>date
Current date is Sat 02-06-2021
C:\>time
Current time is 11:49:25.00p
[ left over nigh ]
C:\>time
Current time is 12:38:04.00a
C:\>date
Current date is Sun 02-07-2021
```

So I am quite sure the date is correct.
The time is not correct: it didn't account the
hibernation time of a PC. But that's expected.

**Comment by stsp** [comment]
> Nice catch, it reproduces a bug present in MS-DOS in some configurations ;-).

Could you please clarify?
At least with fdpp I can't reproduce anything like that.
