### ISSUE TITLE
Status of scalable-font support?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1390]
Apologies if this is answered somewhere; I simply haven't found it. 

Is it possible to run dosemu2 with TrueType fonts rather than bitmap fonts? Or is this still in an early stage of development?

Thanks for any answers, and apologies if I'm wasting bandwidth.

**Comment by stsp** [comment]
Would be cool to find out if Andrew is
still up to that work. :)

**Comment by andrewbird** [comment]
Sorry I'm working on something else at the moment. From what I remember we'd come to the consensus that it'd be better to start again using something called stb_truetype. I'm not likely to get back to this anytime soon so it'd be cool if somebody else picked up the task and the bounty!

**Comment by stsp** [comment]
That depends on your bandwidth.
I am perfectly fine with any other solution
that can be finished in a smaller time
frame. We can switch to stb_truetype later.
Bounty should work for SDL_ttf too, if it
works well enough to be merged.

**Comment by stsp** [comment]
So this is answered.
Unfortunately no solution yet. :(

**Comment by stsp** [comment]
Please see/test #1398 for a status
of scalable-font support.
