### ISSUE TITLE
quake2 doesn't work

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1393]
**Describe the bug**
Says "Couldn't load pics/colormap.pcx".

**To Reproduce**
Set up  https://github.com/Baron-von-Riedesel/HX/releases/tag/v2.19pre5
And run quake2 with it.

**A regression?**
Seems so.

**Comment by stsp** [comment]
Bisect: 30bffbbc

**Comment by stsp** [comment]
Does anyone know what does this
Quake2 says at the beginning?
I've found the very same phrase on
the youtube video gameplay:
https://youtu.be/bhBJsmm_v0o?t=19
but still can't make any sense of
the phrase.

**Comment by skitt** [comment]
Something about “possible camouflaged access in West sector 432”

**Comment by stsp** [comment]
Wow, you are good at that! :)
All I could hear, is something like
"crumbled in escape, possible to kill and crash successfully, white sector, point resumed" :)

**Comment by stsp** [comment]
For the very same reason, early duke3d
versions in Russian were saying
"Опять я ввязался в какую-то халэпу,
опять мне придётся кого-то бить и убивать".
This is because the now famous
"Damn, these alien bastards are gonna
pay for shooting up my ride" was heard
by the translators as
"Damn, so have to give some pain and shooting
of my rifle". :)

**Comment by jschwartzenberg** [comment]
Did they really dub dude3d into Russian? I might try to play that version some day...

**Comment by stsp** [comment]
> Did they really dub dude3d into Russian?

Yes, and even with V.Tsoy songs in the night clubs. :)
That was very hilarious. And I say that
"Опять я ввязался в какую-то халэпу,
опять мне придётся кого-то бить и убивать"
is much, much better than the current
"Эти ублюдки конченые заплатят мне ещё
за тачку", which is what we have in the remake.
I think Russian Duke3d translation was the best
of all translations, and of the original as well.
That made the translator guy very famous
within days, so he was able to open his own
gamedev studio IIRC.

**Comment by stsp** [comment]
I never play shooters, as I hate them.
But duke3d was so hilariously translated,
that I think I played the level or 2. :)
