### ISSUE TITLE
Pasting broken in terminal mode

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1400]
**Describe the bug**

I just updated by dosemu2 build, and now pasting is broken in term mode.

I used to be able to paste text into a dosemu session from another xterm. Here is a gif demonstrating how it used to work:

![dosemu-term-paste](https://user-images.githubusercontent.com/123814/108281428-965f5400-7134-11eb-8488-5fae659ec9ba.gif)

Now pasting any text breaks further input. Here is how it works with a new build:

![dosemu-term-paste2](https://user-images.githubusercontent.com/123814/108281669-07067080-7135-11eb-8f4f-b1b6e8b9a0ed.gif)

Note that when it's stalling, I'm pressing keys. 

I bisected the problem, it's 7e6edf6d76d43fefaf19fea3d71849c8a90e8d5b.

Reverting that patch fixes the issue.

**To Reproduce**
Steps to reproduce the behaviour:

- Open two xterm windows.
- Start `dosemu -term` in one window.
- Select some text in the non-dosemu window, and middle click paste it in the other.
- Notice that input editing is now really weird.

**A regression?**

I bisected the problem, it's 7e6edf6d76d43fefaf19fea3d71849c8a90e8d5b.

Reverting that patch fixes the issue.

**Comment by stsp** [comment]
Thanks, should now be fixed.
Completely forgot about pasting. :(

**Comment by taviso** [comment]
That was quick, thanks Stas!

I just made a fresh build, and it seems to be working now. Thank you!

**Comment by stsp** [comment]
Yeah, except that Esc got broken now... :)

**Comment by taviso** [comment]
Oops, I see what you mean!

**Comment by stsp** [comment]
Should now work.

**Comment by taviso** [comment]
Thanks, confirmed Esc and pasting are working again!
