### ISSUE TITLE
Question: Performance of CGA framebuffer writes

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1405]
Hello, I've been using Lotus 1-2-3 in dosemu2, it works great but it lacked a feature I wanted. Lotus has a modular driver architecture, so I decided to write my own video driver and implement the missing features.

It's working, but I can already see it's significantly slower than the original one.

I didn't even bother thinking about performance, and just read/write directly to the framebuffer at 0B8000h as needed. I just assumed dosemu2 would be able to handle everything orders of magnitude faster than original hardware.

The original driver is careful to maintain a shadow framebuffer, and only sync it when the video status bits are in retrace. I thought that would be unnecessary, oops 🤣 

I guess my question is, am I out of luck and I need to rewrite my driver to be more careful about framebuffer access?

Thank you!

**Comment by stsp** [comment]
dosemu2 simply does periodic memcmp
between the text framebuffer and its old
copy, and starts updating on a mismatch.
So likely you turn 1 update into many.
Maybe just reducing the update freq in
dosemu will help, or some optimization
in text.c.

**Comment by taviso** [comment]
I see, thanks! Is it safe to ignore the retrace status bit?

I don't care if it works on real hardware or not, only under dosemu.

Thank you!

**Comment by stsp** [comment]
Yes, under dosemu its safe to ignore
the retrace status bit. On real hw IIRC
at worst you can get snow effect.

**Comment by taviso** [comment]
Thank you for the help! I'm not a DOS programmer, so it's been an interesting learning experience 😃

**Comment by taviso** [comment]
In case you're interested, the problem I'm trying to solve is that 123 hardcodes the text mode resolution for the various video modes, so you can have 80x25, 80x50, 40x25 or nothing.

This is what 123 looks like if you try to use a non-standard resolution:

![Screenshot 2021-02-27 111021](https://user-images.githubusercontent.com/123814/109397617-6bbb8b00-78ec-11eb-83bf-c80ebb059851.png)

I know that dosemu supports arbitrary text mode resolutions, and reports it via int 10,F - and I've seen old applications that query that and just work (like foxpro, wordperfect, etc).

I figured that 123 must internally be able to generate an arbitrary sized canvas, and then asks the driver what the hardware supports. I figured out the API the drivers use with a disassembler, and wrote my own.

It works - I haven't got colors working yet, but it can draw the foreground:

![Screenshot 2021-02-27 111406](https://user-images.githubusercontent.com/123814/109397712-ed131d80-78ec-11eb-9aee-59bfe478e911.png)

It's usable but noticeably slower than the original driver, I think I'll just need to batch framebuffer writes.


I think this must be the first Lotus 123 driver written in 30 years 🤣

**Comment by andrewbird** [comment]
Impressive!

**Comment by stsp** [comment]
Try something like this:
```
diff --git a/src/arch/linux/async/signal.c b/src/arch/linux/async/signal.c
index 691f6a2bc..c4f7426d3 100644
--- a/src/arch/linux/async/signal.c
+++ b/src/arch/linux/async/signal.c
@@ -1035,19 +1035,24 @@ static void SIGALRM_call(void *arg)
   static int first = 0;
   static hitimer_t cnt200 = 0;
   static hitimer_t cnt1000 = 0;
+  static hitimer_t cnt10 = 0;
   int i;
 
   if (first==0) {
     cnt200 =
     cnt1000 =
+    cnt10 =
     pic_sys_time;      /* initialize */
     first = 1;
   }
 
   process_callbacks();
 
-  if (video_initialized && !config.vga)
-    update_screen();
+  if ((pic_sys_time-cnt10) >= (PIT_TICK_RATE/100)) {
+    cnt10 = pic_sys_time;
+    if (video_initialized && !config.vga)
+      update_screen();
+  }
 
   for (i = 0; i < alrm_hndl_num; i++)
     alrm_hndl[i].handler();
```

**Comment by taviso** [comment]
Wow - it's a lot better - it's still slow enough that you can see the lines drawing, but it's better than it was!

![dosemu-123](https://user-images.githubusercontent.com/123814/109400045-4124fe80-78fb-11eb-9483-21aa479820ae.gif)

I wouldn't say the original driver is lightning fast, but it is faster than mine.

I figured mine would be faster, because it calls int 10h before every write and I don't bother lol.

**Comment by stsp** [comment]
Try `/10` instead of `/100` as in the patch.

**Comment by taviso** [comment]
It's definitely faster, but screen updates look jerky at `/10`. I think `/100` is optimal, it's much faster than it was and still looks very smooth.

I should I need to fix my code to batch the writes more efficiently if I want it faster  😀

Thanks so much for your help!

**Comment by stsp** [comment]
At least calling int10 before every write
is quite bad.

**Comment by taviso** [comment]
I did get it working, you can now look at 26 columns simultaneously if you want to 🤣

![Screenshot 2021-02-28 131609](https://user-images.githubusercontent.com/123814/109433807-25872a00-79c7-11eb-8024-0005ed3b9c27.png)

A combination of being smarter about updates and some code re-organization and it's fast now. I'll clean up the code a bit and put it on github, in case anybody else wants to use it!

**Comment by taviso** [comment]
FYI, here is the code in case anyone searches for this in future 😄 

https://github.com/taviso/lotusdrv

It is much faster than the original now, and is *mostly* working...

**Comment by andrewbird** [comment]
Thank you, you have a very interesting write up too.

**Comment by stsp** [comment]
Looks cool indeed, except that I wonder
what makes it specific to dosemu2.
IIRC in pure DOS you could have a lot of
non-standard text resolutions with mode.com.
