### ISSUE TITLE
$cpu_emu="emulated" show lot of error messages in boot.log

### ISSUE THREAD

**Issue by bpranoto** [dosemu2/dosemu2#1406]
**Describe the bug**

Environment:
ubuntu 18.04 - 64bits
kernel version 4.15.0-136
package: dosemu2-legacy

Running with options:
$_cpu_vm = "emulated"
$_cpu_vm_dpmi = "emulated"

shows a lot of error messages in boot.log

**Attach the log**
run with -De
[boot.log](https://github.com/dosemu2/dosemu2/files/6053909/boot.log)

**Comment by stsp** [comment]
Can you attach your test-case program?

**Comment by bpranoto** [comment]
Actually, I only let it boots opendos, load vlm dos netware clients  and then exitemu.

To give a puristic view, I tried again. This time I renamed my old .dosemu so I will boot with the default fdpp

I then called dosemu -D9+gQDdi# dosemu crashed with messages on console:
`ERROR: Accessing reserved memory at 556d8d41a460
	Maybe a null segment register
ERROR: cpu exception in dosemu code outside of VM86()!
sig: 11 trapno: 0x0e  errorcode: 0x00000015  cr2: 0x556d8d41a460
eip: 0x556d8d41a460  esp: 0x7ffd090d8d70  eflags: 0x00010202
cs: 0x0033  ds: 0x0000  es: 0x0000  ss: 0x002b
fs: 0x0000  gs: 0x0000
fsbase: 0x7f592ae65740 gsbase: (nil)

ERROR: Please install gdb, update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

Terminated with signal 11
`
attached is the boot.log
[boot.log](https://github.com/dosemu2/dosemu2/files/6054431/boot.log)

**Comment by stsp** [comment]
I rebuilt legacy branch.
That should now be fixed.

**Comment by stsp** [comment]
So can you check again please?

**Comment by bpranoto** [comment]
Yes, it is fixed. But setting $_X_font = "vga11x19" is ignored.
![image](https://user-images.githubusercontent.com/7417263/109408432-57df5a00-79bc-11eb-94ef-6f2087a1ef78.png)

BTW, is emulated wo

**Comment by stsp** [comment]
Few things to try.
dosemu -X
should give you X font again.
Resizing dosemu window with mouse
to the needed aspect ratio may load
the desired font too.

kvm is supposed to be faster than
emulated. But something went wrong
and its not the case. But now as I
simplified the kvm code considerably,
maybe we can make it fast again.
Also for dpmi, emulation is simply not
mature enough while kvm/dpmi was
recently stabilized.

So do you still see emulator errors in
the log?

**Comment by bpranoto** [comment]
dosemu -X some times some times failed to start.

When it's failed it print this error in console

```
$ dosemu -X
ERROR: thread dosemu: render got signal 11
removing stale files:
/home/bambang/.dosemu/run/dosemu.dbgin.23791
/home/bambang/.dosemu/run/dosemu.dbgout.23791

```

When it comes up, it shows a unresizeable window. But the font is not sharp as it used to be. My font setting is vga11x19

Here is the log with -De when it is shown up, there are many SIGPROF lines at the bottom
[boot.log](https://github.com/dosemu2/dosemu2/files/6056535/boot.log)

**Comment by bpranoto** [comment]
This is the log when it is crashed.
[boot.log](https://github.com/dosemu2/dosemu2/files/6056540/boot.log)

**Comment by stsp** [comment]
Yes, I confirm that $_X_font is broken.

> SIGPROF lines at the bottom

Sigprof is not an error.
In #1404 you attached the log full of
```
ERROR: no mark at 36dc1 (1)
1 1 1 1 1 0
corrupted at 36dc6
```

In this ticket you have never attached
such a log.

**Comment by stsp** [comment]
> You said that it was already fixed, then indeed it was... :)

No.
What was fixed, is https://github.com/dosemu2/dosemu2/issues/1406#issuecomment-787067890
And now I am interested in https://github.com/dosemu2/dosemu2/issues/1404#issuecomment-786779296
which had lots of "corruption at" errors.

**Comment by bpranoto** [comment]
The 1404 comment was with old version of dosemu2-legacy (compiled many months ago).

After you said you have rebuilt the  legacy package, I updated my package in my computer from the ppa. It is not the same package anymore.

**Comment by stsp** [comment]
Yes but it wasn't supposed to be fixed.
Can you check your opendos boot with all
the same settings as before?

**Comment by bpranoto** [comment]
Ok, what -D parameter do you want?

**Comment by stsp** [comment]
-D+e as before.

**Comment by bpranoto** [comment]
Just to be sure, Here I copy paste my dosemu.conf
```
# Select cpu virtualization mode.
# "vm86" - use v86 mode via vm86() syscall. Only available on x86-32.
# "kvm" - use KVM, hardware-assisted in-kernel virtual machine.
# "emulated" - use CPU emulator
# "auto" - select whatever works
# Default: "auto"

$_cpu_vm = "emulated"

# Select cpu virtualization mode for DPMI.
# "native" - use native LDT via modify_ldt() syscall (Warning: INSECURE!)
# "kvm" - use KVM, hardware-assisted in-kernel virtual machine
# "emulated" - use CPU emulator
# "auto" - select whatever works
# Default: "auto"

$_cpu_vm_dpmi = "emulated"

```
Here is the log.

[boot.log](https://github.com/dosemu2/dosemu2/files/6056655/boot.log)

**Comment by stsp** [comment]
OK, `dosemu -X` should now be fixed.

**Comment by bpranoto** [comment]
Thanks, I will wait the new legacy package in the ppa

**Comment by stsp** [comment]
Its there.

**Comment by bpranoto** [comment]
Yes, dosemu -X runs fine now. Thank you

However, in previous version I didn't need to specify the argument -X as long as the $_X_font is specified.

Is it an  intended change?

**Comment by stsp** [comment]
Yes.
As I said, now you can even w/o
-X resize dosemu with mouse to the
needed aspect ratio, and it will use
the proper font.
So the need for $_X_font is very
small now.

**Comment by bpranoto** [comment]
Oh yes, I just tried now. Really cool!

**Comment by stsp** [comment]
Yeah but eg dosbox uses quite good
scaling filters and I can hardly see
the difference.
