### ISSUE TITLE
Handling SIGWINCH in dosemu

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1413]
This might be impossible, but do you think dosemu could handle SIGWINCH and change the mode automatically, or update the BIOS data area?

The idea would be that resizing an xterm running `dosemu -term ...` might "just work" if an application knew it could check..

**Comment by stsp** [comment]
Updating BDA will make things slightly
inconsistent: no progs query BDA
periodically, so it will not match the
displayed resolution.
And even in your case I wonder in
what form do you want SIGWINCH
to be translated to your prog, or will
you poll BDA periodically?

So I would propose the dosemu
helper to query window size
(using our gettermcap() fn).
Once you detect the change, you
set the video mode again, and it
should query the new size.
And none of the existing prog will
break.

Should be quite simple, please
submit a patch. :)

**Comment by stsp** [comment]
A more real reason against updating
BDA directly is that in mouse code we
rely on it.
So please go for a helper fn.

**Comment by stsp** [comment]
Well, so NOW we depend on the right
BDA values. :)

**Comment by taviso** [comment]
Haha, well that commit points me to reference code to understand how it works 😄 

Thanks, I'll take a look.

**Comment by stsp** [comment]
Please take a look also into int.c:dos_helper()
fn where we add dosemu-specific helpers
accessible with int 0e6h.
And in video_mem_setup() for how to use
gettermcap().

**Comment by stsp** [comment]
I extended the GET_TERM_TYPE helper
to get the terminal size.
Enjoy.
