### ISSUE TITLE
fedora packages crash on startup

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1415]
**Describe the bug**

I just tried to install the official dosemu2 packages on Fedora 32, but it crashes on startup. This is the version that got installed:

```
$ rpm -q dosemu2
dosemu2-0.0.git.2327.9aeca377-1.fc32.x86_64
```

With an entirely empty `.dosemurc` and `.dosemu` directory, it just crashes on startup. This used to work, I'm not sure when it broke, or if it's something unusual on this system.

```
$ dosemu 
ERROR: KVM: error opening /dev/kvm: No such file or directory
ERROR: JIT fault accessing invalid address 0x7ffd39190f90, RIP=0x7ffd39190f90
ERROR: cpu exception in dosemu code outside of VM86()!
sig: 11 trapno: 0x0e  errorcode: 0x00000015  cr2: 0x7ffd39190f90
eip: 0x7ffd39190f90  esp: 0x7ffd39190f38  eflags: 0x00010206
cs: 0x0033  ds: 0x0000  es: 0x0000  ss: 0x002b
fs: 0x0000  gs: 0x0000
fsbase: 0x7fd14fd16740 gsbase: (nil)
```

With `$_cpuemu = (1)` in `.dosemurc` (and nothing else) it works perfectly.

**Attach the log**

[boot.log](https://github.com/dosemu2/dosemu2/files/6079761/boot.log)

I am certain the official fedora packages used to work, but I ran `dnf downgrade dosemu2` a few times and it still didn't work, so I couldn't find the working build.

Here is the -D9+e log  [boot.log](https://github.com/dosemu2/dosemu2/files/6079785/boot.log)

**Comment by taviso** [comment]
I just built dosemu2 from source on this system (all default configure options, using the official fdpp and comcom32 packages).

I'm at 9aeca37777dda9ec4806e13fe76c847b1eab5b81 and the resulting binary works fine.

There must be something wrong with the dosemu2 rpms?

**Comment by taviso** [comment]
Ah-ha, I had CFLAGS set in my environment, if I unset it then build dosemu2, that binary is broken.

- `make CFLAGS+=-O2`: works
- `make`: broken

This must be a codegen issue, let me see if I can bisect which object file is causing the issue....

**Comment by stsp** [comment]
Thanks, should now be fixed.

**Comment by taviso** [comment]
You're too quick Stas! 🤣 

I was running this:

```bash
find . -iname '*.c' | while read file; do
     make --assume-new=${file} install CFLAGS+="-O3"
     dosemu -quiet -dumb -E 'exitemu 0' && { echo culprit is $file; break; }
done
```

**Comment by taviso** [comment]
Confirmed, just built and tested and your fix works! Thanks you!

**Comment by stsp** [comment]
You probably won't find anything
with that trick. I think we only check
CFLAGS during configure, but during
make this may be ignored.
Let me know if it actually works the
way you expect.

**Comment by taviso** [comment]
It definitely uses the flags on the commandline, although it blamed a different file - probably just enough difference that the register wasn't clobbered just by chance.

**Comment by stsp** [comment]
copr build still seems to crash.

**Comment by stsp** [comment]
Which file was blamed?

**Comment by taviso** [comment]
`kvm.c` 🤷‍♂️ (I know it sounds unlikely, but the resulting build does work here)

**Comment by stsp** [comment]
Not fixed.
Giving up for today...

**Comment by stsp** [comment]
Now its fixed.
These days you can't do call's from
inline asm unless you specified -mno-red-zone
and what's next?

**Comment by taviso** [comment]
Just a confirmation that I did `dnf update` and the new build worked.

**Comment by stsp** [comment]
Cool, something like a first build that
doesn't crash on start... in 7 years. :)
10 years more and we'll get to something.
