### ISSUE TITLE
FDPP won't boot for me

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1420]
**Describe the bug**
FDPP fails to boot (from devel directory), terminal has whinges about unable to open files but names are garbled.

**To Reproduce**
Try this
`test/test_dos.py PPDOSGITTestCase.test_cpu_trap_flag_kvm`

**Attach the log**
[t1.tar.gz](https://github.com/dosemu2/dosemu2/files/6115678/t1.tar.gz)

**A regression?**
Yes, it was working a few days ago

**Comment by stsp** [comment]
```
$ test/test_dos.py PPDOSGITTestCase.test_cpu_trap_flag_kvm
Test PP-DOS-GIT  CPU Trap Flag KVM                                               ... ok (  2.31s) known bad cpu 'AMD FX(tm)-8350 Eight-Core Processor'

----------------------------------------------------------------------
Ran 1 test in 2.311s

OK
```

Please find all tests passing fine
also on github, so?

**Comment by andrewbird** [comment]
Yes, just looking at that. I see it has FDPP_KERNEL_DIR set, which was optional before I think. I wonder if that's fixing it up.

**Comment by stsp** [comment]
Its optional only if you did make install before.

**Comment by andrewbird** [comment]
okay, I'll figure it out here, thanks.

**Comment by stsp** [comment]
What was the problem?

**Comment by stsp** [comment]
OK, there is a bug if it doesn't find it.

**Comment by andrewbird** [comment]
Thanks, it works even without make install now!

**Comment by stsp** [comment]
Good but I don't know how can this
be a regression. I think this include
was forgotten before the yesterday's
elf commits.
