### ISSUE TITLE
Question: Unicode characters

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1421]
I have got basic ascii art graphs working in 1-2-3, it's actually kinda fun:

![123-sinewave](https://user-images.githubusercontent.com/123814/110643345-dbd9d480-8168-11eb-89ac-51e941456ad7.gif)

I'm doing this by translating the drawing primitives 1-2-3 uses to libcaca calls, and hacking libcaca to use the CGA framebuffer as it's canvas.  It works fine, but if I could use unicode characters I could have a far higher effective resolution.

I think I'm currently limited to CP437 characters, because that's all that will fit in the text mode framebuffer. Is there a way around that? Perhaps some way of asking for raw access to the terminal so I can print a unicode character at x/y position?

**Comment by stsp** [comment]
Text mode just scans the VGA text
buffer (obviously not unicoded) and
represents it on a terminal.
If you do your own raw terminal output
then you'll need to suppress the text
mode by using -dumb.
Which is not what you want.
I am not sure what does unicode have
to do with resolution. You might be able to
get a higher resolution w/o any unicode.
Just use the higher resolution text mode.

**Comment by taviso** [comment]
The reason is there are more characters to use for drawing, it doesn't change the canvas size.

**Comment by stsp** [comment]
Are you sure libcaca would use fancy
unicode chars to improve the picture?
I suppose it doesn't do so.
Especially if you compile it under DOS
(which is what I think you do).

**Comment by taviso** [comment]
It does, it natively uses utf32 everywhere - I had to hack it to use pure CP437.

That still lets me use box drawing characters, but obviously unicode has thousands more options that would work in an xterm if I could get dosemu to print them.

I think the answer is that it's out of scope for dosemu2? 😃

**Comment by taviso** [comment]
For DOS, but the "canvas" is just a memory buffer. It can contain fancy unicode characters that make nice looking graphs, so my question is is there any way to display those in text mode.

I think the answer is no, I could use `-dumb` , but `-term` will only work with characters that will fit in the framebuffer?

**Comment by stsp** [comment]
So I still don't understand.
You say you hacked it to use cp437.
How did it do with unicode under DOS
without your hack?

> but -t will only work with characters that will fit in the framebuffer?

It will mess up your terminal if you write
something directly. Only -dumb can allow
you to write something directly.

**Comment by stsp** [comment]
Consider using second terminal
via emulated serial port.

**Comment by taviso** [comment]
It didn't, it could use them internally but wouldn't be able to display them in DOS.

Hmm, interesting idea about the serial port, thanks!

**Comment by stsp** [comment]
> It didn't,

What exactly?
`it natively uses utf32 everywhere - I had to hack it to use pure CP437.`
That's what you said, so I wonder what
it did under DOS w/o your hack.

> it could use them internally but wouldn't be able to display them in DOS.

Could you please describe how the DOS
port worked w/o your hack?

**Comment by taviso** [comment]
Hmm, the canvas is just a memory buffer, like `uint32_t canvas[i][j]`, so obviously that works fine under DOS. The problem is displaying it.

They had some `conio.h` output routines, but obviously it doesn't use all the possible characters, it's effectively `iconv()` converted down to ASCII.

**Comment by stsp** [comment]
> The difference is that I have to limit the output to CP437, but my terminal supports UTF8.

Which is true for DOS in any case.
So I suppose your change was simply
not needed. If you wanted to do some
pass-through, you'd better stay with the
utf8 internal buffer. Which you seem to
have removed.

> we can add our own interrupts, why not i/o ports? smiley

There are IO ports for an emulated
serial port to connect your second terminal
to. Use pty link with socat.

**Comment by taviso** [comment]
Not sure what change you mean, I needed the canvas to map onto the CGA framebuffer. If you put a uint32_t in there, it will just be interpreted as junk and not display anything that makes sense.

Each character in the CGA framebuffer is uint16_t, the top 8bits are a CP437 character and the lower 8 bits are attributes. Writing a uint32_t to it will be interpreted as two characters and two attributes, not a single character as intended. Clearly it must be converted, they are not compatible formats.

> There are IO ports for an emulated
> serial port to connect your second terminal
> to. Use pty link with socat.

Thanks, I'll think about it, although not sure it's a nice solution 😃

**Comment by stsp** [comment]
> Clearly it must be converted, they are not compatible formats.

But you said they were:
`it's effectively iconv() converted down to ASCII.`
So why that didn't work?

**Comment by taviso** [comment]
That's what their `conio` driver did, you asked how libcaca normally works on DOS.

I can't use conio - I have to manage the framebuffer directly.

**Comment by stsp** [comment]
> That's what their conio driver did, you asked how libcaca normally works on DOS.

Yes and how come it doesn't do the same
under dosemu. It should normally work as
under DOS.

> I can't use conio - I have to manage the framebuffer directly.

Why?

**Comment by stsp** [comment]
> As far as I know, you can't do that with conio.

But you have to.
Either by conio (changing the attrs
per every cell individually) or by any
other way. If you want it to work with
utf8 terminals via some pass-through,
you are not supposed to use the
terminal's "screen buffer" directly,
as there is no such thing.
You can only use the terminal escapes
to feed your unicode buffer to the terminal
sequentially.
Under DOS you can have it both ways,
but under terminal - not.
This is probably why you say the serial
port solution is "not nice", but there is
no any other one.
