### ISSUE TITLE
FDP_IDX undefined with --disable-fdpp

### ISSUE THREAD

**Issue by atsampson** [dosemu2/dosemu2#1423]
Building current master with `--disable-fdpp` fails with:

```
fatfs.c:124:21: error: ‘FDP_IDX’ undeclared here (not in a function); did you mean ‘FDP_D’?
```

I think this was the result of the changes in 108c35041f6c926a61511ddf17785a335a588aa5.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by atsampson** [comment]
Yes, that's fixed it. Thanks very much!

**Comment by stsp** [comment]
Why would you do that anyway?
