### ISSUE TITLE
Windows for Workgroups crashes on startup

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#1425]
**Describe the bug**
I recently updated dosemu2 to the current git code and my WfW installation no longer works. It crashes with a DPMI exception:

```
DPMI: Unhandled Exception 0d - Terminating Client
It is likely that dosemu is unstable now and should be rebooted

```

stdout prints

`ERROR: DPMI: Warning: trying to leave DPMI when in_dpmi_pm_stack=1
`

I have attached a boot.log with -D DPMI. Search for the error above to see where things fail.

The issue happens regardless of the selected DPMI cpu type. I tried native, kvm and emulated. My dosemu build is a 64 bit build. Dosemu commit ID is 0d6017b58b3d62a8affa07039e7ba314403cd720, fdpp c3f476a11a00ebed3727858260a43a9942b74d4b . I have an ancient comcom32 though, not sure if that matters.

**To Reproduce**

Install Windows for Workgroups (or presumably any other Win 3.1 version) and run win or system\krnl386.exe.

**Attach the log**
Done :-)

**A regression?**
Yes, it is a regression. I haven't updated dosemu2 in a while - I believe my previous build was e8d5184a6, which worked. I can run a bisect if you cannot reproduce the problem.

[boot.log.gz](https://github.com/dosemu2/dosemu2/files/6163226/boot.log.gz)

**Comment by stsp** [comment]
I test win31 quite regularly.
But not 3.11.
Please see if the same happens with
win.com, and if so - please tar up your
windows copy.

**Comment by stefand** [comment]
Yeah it also happens with win.com. I'll get you a copy of my Windows installation. Here is an updated log, using -D9+M instead of the wrong but by luck probably working -D DPMI :-D

[boot.log.gz](https://github.com/dosemu2/dosemu2/files/6163515/boot.log.gz)

**Comment by stefand** [comment]
It may have something to do with my ancient comcom32, taken from some Gentoo layman overlay. I replaced it with freecom.exe, now Win311 starts again.

Do you have comcom binaries somewhere? djgpp is a bit awkward to find...

**Comment by stefand** [comment]
I updated comcom32 to 0.1~alpha2-138-d64f704+202102060048~ubuntu20.04.1 found at https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa . The problem remains, Windows refuses to start from comcom32 but starts with freecom.

**Comment by stsp** [comment]
Wow, it worked perfectly here.
But I use Dos Navigator shell.
I tried w/o loading DosNavigator,
and the problem is reproduced,
also with my version of win31.
So the fact that I frequently test
win31 doesn't always work out
right. :)

**Comment by stefand** [comment]
I noticed that if I use freecom as my startup shell and start comcom32 from it, Windows starts OK. freecom inside comcom32 does not work. Some issue going from one DPMI client (comcom32) to another (Windows)?

Relatedly, what's the advantage of comcom32 over freecom? I guess a while ago it allowed the command interpreter to run natively on the CPU on a 64 bit host because it is a 32 bit DPMI client whereas freecom was running in the emulated CPU before the kvm backend was introduced. Is there any reason for comcom32 left when kvm real mode support is in place?

**Comment by stsp** [comment]
> Some issue going from one DPMI client (comcom32) to another (Windows)?

Seems like you need fdpp+comcom32 for
a crash. I don't see the crash with freedos+comcom32
for example.

> Relatedly, what's the advantage of comcom32 over freecom?

That you can build it on LP and COPR.
And overall - with a GPL compiler tool-chain.

> Is there any reason for comcom32 left when kvm real mode support is in place?

comcom32 will go away once it is ported
to 64bits, so that it can be built with clang
instead of djgpp.
But freecom is the buggiest command.com
in existence, its not a replacement. 4dos is
a replacement, but you can't compile it with
GPL tool-chain I suppose.

**Comment by skitt** [comment]
> But freecom is the buggiest command.com
> in existence, its not a replacement. 4dos is
> a replacement, but you can't compile it with
> GPL tool-chain I suppose.

... and more importantly, 4DOS itself isn’t open source, its license only allows building for FreeDOS :-(.

**Comment by stsp** [comment]
I wonder what is "building for FreeDOS".
A special, functionality-reduced target
in its makefiles?

**Comment by skitt** [comment]
> I wonder what is "building for FreeDOS".
> A special, functionality-reduced target
> in its makefiles?

No, a statement in the license:

```
  (2) The Software, or any portion of it, may not be compiled for use on any
  operating system OTHER than FreeDOS without written permission from Rex Conn
  <rconn@jpsoft.com>
```

**Comment by stsp** [comment]
IMHO in an absence of the special
makefile target, this statement is pointless,
as then you will compile the same binary
for ANY os.
But I can understand the attitude to not
trust the licenses with pointless statements.

**Comment by stsp** [comment]
I suspect they meant "you can distribute
4dos only as part of a freedos distribution",
or something along the lines.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by skitt** [comment]
> IMHO in an absence of the special
> makefile target, this statement is pointless,
> as then you will compile the same binary
> for ANY os.

Not everything ends up encoded in code or build infrastructure... See http://wiki.freedos.org/wiki/index.php/4DOS for what was really meant; the idea was to restrict the use of modified versions of 4DOS to DOS-based platforms, to avoid someone taking the 4DOS code and building a competitor for 4NT.

**Comment by stsp** [comment]
That would still mean "please don't add
a new targets into a build system (eg the
win32 target)".
Which for us would mean no 64bit port.

**Comment by stuaxo** [comment]
> > IMHO in an absence of the special
> > makefile target, this statement is pointless,
> > as then you will compile the same binary
> > for ANY os.
> 
> Not everything ends up encoded in code or build infrastructure... See http://wiki.freedos.org/wiki/index.php/4DOS for what was really meant; the idea was to restrict the use of modified versions of 4DOS to DOS-based platforms, to avoid someone taking the 4DOS code and building a competitor for 4NT.

Exactly - it may be worth asking, for DOSEMU 64 bit, they will probably be OK as it won't run in Windows.

**Comment by jschwartzenberg** [comment]
Such statement still puts a restriction in place that goes against the four freedoms, so such package couldn't be adopted by Debian for example.

**Comment by stsp** [comment]
> Exactly - it may be worth asking, for DOSEMU 64 bit, they will probably be OK as it won't run in Windows.

This won't help (for the reason expressed above),
but to add, it would be very difficult to port a 16bit
real-mode code to 64bits, anyway. And I suppose
4dos is real-mode. I am surely not going to write
yet another fdpp-alike framework any soon.
I took the 32bit command.com to simplify the
64bit porting of it. It would be a very challenging
task, but not even remotely as difficult as the
real-mode porting framework (fdpp).
