### ISSUE TITLE
Source Code Pro TTF font rendering issue

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#1426]
Let me say that I love the new scalable fonts. Therefore I am going to spam you with some bugs I found.

I tried to use the Adobe Source Code Pro font. It is picked up ok, but the text layout is not right in the default window size. My guess is that the font has a different width:height ratio than the default VGA font, breaking some not-yet-updated code. See the attached qbasic-broken.png.

**To Reproduce**
1) Install Adobe Source Code Pro fonts.
2) $_SDL_fonts = "Source Code Pro"
3) start dosemu

Most likely you can already see issues after boot. A TUI program that tries to draw a layout over the entire screen is most likely to show visible issues.

Interestingly, the problem goes away when switching to a graphical mode and back (e.g. starting windows). In that case it seems like dosemu's window receives a w:h ratio that matches the font's and everything looks ok. See qbasic-ok.png. Shiny :-)
![qbasic-broken](https://user-images.githubusercontent.com/521262/111697208-9175e900-8835-11eb-837e-478a4bed9eab.png)
![qbasic-ok](https://user-images.githubusercontent.com/521262/111697257-a2bef580-8835-11eb-80e6-1986f60581d6.png)

**Comment by stefand** [comment]
To show that this isn't simply running qemu in a non-80x25 mode: Here is an example of the dosemu rendering looking broken running just its own things: See the "fy", "000 MB" leftovers from the drive descriptions on the right side, a stray "TE" and the E above the C:\> prompt.

![boot-broken](https://user-images.githubusercontent.com/521262/111699805-dd765d00-8838-11eb-9650-2fb8d6e5abe2.png)

**Comment by stefand** [comment]
Fyi, the updated version of the Flexi IBM VGA Fonts look less comic sans-y: https://int10h.org/blog/2020/12/more-font-updates-oldschool-pack-flexi-vga/#flexi-ibm-vga-v2-0

**Comment by stsp** [comment]
I updated the fonts from that URL, thanks.

**Comment by stuaxo** [comment]
Its better, they still have some issues with corners not being sharp, but can't complain for free 🙂

**Comment by stsp** [comment]
You can report to the font's author, if you want.

**Comment by stefand** [comment]
He knows about this; And I wanted to post the link in 1427 not here...

**Comment by stsp** [comment]
This is actually reproducible.
Andrew, would you like to take a look? :)

**Comment by stsp** [comment]
OK, this is quite a nasty one, so looking...

**Comment by stsp** [comment]
Proportional fonts are now supported.

**Comment by stefand** [comment]
Source Code Pro isn't a proportional font - I, i, l and M have the same width. It must be some other property of the font that caused the problem. I'd expect a DOS screen in an actual proportional font like Times New Roman to look rather terrible.

Anyway, I'll test the fix tomorrow, fixed is fixed :-)

**Comment by stsp** [comment]
Andrew asks the same so I reply to
both: letters are not the only possible
chars in a font. Take line-drawing
chars, or even simple -+_ and you'll
see them not matching the char width.
So lets say this font is just broken.

**Comment by stsp** [comment]
In either case I am quite happy with my
fix-up because fighting with broken fonts
and their users is not realistic. No one
will fix the font out of our complains.

**Comment by andrewbird** [comment]
How's the speed now that you are writing chars not strings?

**Comment by stsp** [comment]
How can one measure?
Perhaps you have an ascii-art demo
that keeps the text renderer busy?
If so, I would expect such demo to
result in a higher cpu load: too many
ops per char plus padding rectangle.
But the only alternative is to fight with
such fonts and their users. And that
will not lead to font's correction.
If you want, I can add an error print for that
case.

**Comment by stefand** [comment]
If +-_ or spaces don't have the same width that'd be an awful bug in a font that's supposed to be monospaced and advertised for rendering source code. In a quick test I can't reproduce any width difference with that font in kwrite though. Might the bug be hiding elsewhere?

**Comment by stsp** [comment]
Well, the bug is applicable only to cartain
small sizes of the font. Even before my
patch, the rather large sizes had no problems.
But one needs a lot of ttf internals knowledge
to say for sure.

**Comment by stefand** [comment]
Yeah I suspected it is some issue with small sizes. Some bugs in antialiasing hinting? Embedded bitmap pre-renderings of small font sizes that get interpolated incorrectly? Bug in freetype?

I tested all (integer) font sizes in kwrite down to size 5

**Comment by stsp** [comment]
Can it be that the bug only happens
with such sizes where a proper aspect
ratio cannot be precisely kept? That
would be a good guess but unfortunately
I've seen chars 2 pixels thiner than
expected - not just 1 pixel thiner.
The smaller size you take, the worse are
rounding errors.

**Comment by stsp** [comment]
Why would you need kwrite?
Just hack on dosemu source, add a print
where it draws a padding rectangle, and
find out what chars on what size needs
how much padding.

**Comment by stefand** [comment]
I am currently sitting on my Nvidia Shield, which has an ARM cpu. And to ask a different program to render text with this font. If I can reproduce it in kwrite it rules out a fault in dosemu itself.

At what size do you get differences in width?

**Comment by andrewbird** [comment]
> How can one measure?

I don't know really, but it seems fine to me in my minimal use. I'm just curious as at one time I was considering ttf rendering each char in the active codepage at resize time to a rect, then do a rect copy to the required position at draw time. I figured that would be a GPU operation.

**Comment by stefand** [comment]
Maybe the guy from #1405 has an opinion on text rendering speed?

**Comment by stsp** [comment]
> At what size do you get differences in width?

ptsize 1 OK (h=2 w=1)
ptsize 2 height 3 exp_width 2 real_width 1
ptsize 3 height 4 exp_width 3 real_width 2
ptsize 4 height 6 exp_width 3 real_width 2
ptsize 5 height 7 exp_width 4 real_width 3
ptsize 6 OK (h=8 w=4)
ptsize 7 height 9 exp_width 6 real_width 5
ptsize 8 height 11 exp_width 6 real_width 5
ptsize 9 height 12 exp_width 6 real_width 5
ptsize 10 height 13 exp_width 7 real_width 6
ptsize 11 OK (h=14 w=7)
ptsize 12 height 16 exp_width 8 real_width 7
ptsize 13 height 17 exp_width 9 real_width 8
ptsize 14 height 18 exp_width 10 real_width 8
ptsize 15 height 19 exp_width 10 real_width 9
ptsize 16 OK (h=21 w=10)
ptsize 17 height 22 exp_width 11 real_width 10
ptsize 18 OK  (h=23 w=11)
ptsize 19 height 24 exp_width 12 real_width 11
ptsize 20 height 26 exp_width 13 real_width 12
ptsize 22 height 28 exp_width 14 real_width 13
ptsize 24 height 31 exp_width 15 real_width 14
ptsize 25 height 32 exp_width 16 real_width 15

Does this help?

**Comment by andrewbird** [comment]
Where does the expected width come from? Does the real width vary between chars?

**Comment by stsp** [comment]
It comes from font_with, which you
derive from char W.

**Comment by stsp** [comment]
And the real width differs between chars
(well, differs from W at least)

**Comment by stsp** [comment]
Just use this:
```
diff --git a/src/plugin/sdl/sdl.c b/src/plugin/sdl/sdl.c
index 075d7309d..66944413c 100644
--- a/src/plugin/sdl/sdl.c
+++ b/src/plugin/sdl/sdl.c
@@ -498,6 +498,10 @@ static TTF_Font *do_open_font(int idx, int psize, int *w, int *h)
 
   // get metrics
   TTF_SizeText(f, "W", w, h);
+int w1, h1;
+TTF_SizeText(f, ".", &w1, &h1);
+if (w1 != *w)
+error("size mismatch: W(%i) .(%i)\n", *w, w1);
   return f;
 }
 
```

It gives:
```
ERROR: size mismatch: W(48) .(47)
ERROR: size mismatch: W(47) .(46)
ERROR: size mismatch: W(45) .(44)
ERROR: size mismatch: W(44) .(43)
ERROR: size mismatch: W(42) .(41)
ERROR: size mismatch: W(41) .(40)
ERROR: size mismatch: W(40) .(39)
ERROR: size mismatch: W(39) .(38)
ERROR: size mismatch: W(38) .(37)
ERROR: size mismatch: W(38) .(37)
ERROR: size mismatch: W(36) .(35)
ERROR: size mismatch: W(35) .(34)
ERROR: size mismatch: W(34) .(33)
ERROR: size mismatch: W(33) .(32)
ERROR: size mismatch: W(32) .(31)
ERROR: size mismatch: W(30) .(29)
ERROR: size mismatch: W(29) .(28)
ERROR: size mismatch: W(28) .(27)
ERROR: size mismatch: W(27) .(26)
ERROR: size mismatch: W(27) .(26)
ERROR: size mismatch: W(25) .(24)
ERROR: size mismatch: W(24) .(23)
ERROR: size mismatch: W(24) .(23)
ERROR: size mismatch: W(23) .(22)
ERROR: size mismatch: W(21) .(20)
ERROR: size mismatch: W(21) .(20)
ERROR: size mismatch: W(20) .(19)
ERROR: size mismatch: W(20) .(19)
ERROR: size mismatch: W(18) .(17)
ERROR: size mismatch: W(17) .(16)
ERROR: size mismatch: W(17) .(16)
ERROR: size mismatch: W(16) .(15)
ERROR: size mismatch: W(15) .(14)
ERROR: size mismatch: W(15) .(14)
ERROR: size mismatch: W(14) .(13)
ERROR: size mismatch: W(14) .(13)
ERROR: size mismatch: W(13) .(12)
ERROR: size mismatch: W(12) .(11)
ERROR: size mismatch: W(11) .(10)
ERROR: size mismatch: W(10) .(9)
ERROR: size mismatch: W(10) .(8)
ERROR: size mismatch: W(9) .(8)
ERROR: size mismatch: W(8) .(7)
```

Does this help?

**Comment by andrewbird** [comment]
Ahh I see, thanks. I wonder if the advance is constant http://sdl.beuc.net/sdl.wiki/SDL_ttf/Functions/Attributes/TTF_TTF_GlyphMetrics

**Comment by andrewbird** [comment]
Have to dash out now, but see
~~~
ajb@polly:/clients/common/dosemu2.git$ ./runstandalonetest.sh 
ERROR: size mismatch: W(15) .(14)
ERROR: size mismatch: W(12) .(11)
ERROR: size mismatch: W(9) .(8)
ERROR: size mismatch: W(8) .(7)
ajb@polly:/clients/common/dosemu2.git$ git diff
diff --git a/src/plugin/sdl/sdl.c b/src/plugin/sdl/sdl.c
index 075d7309d..6af78195b 100644
--- a/src/plugin/sdl/sdl.c
+++ b/src/plugin/sdl/sdl.c
@@ -498,6 +498,23 @@ static TTF_Font *do_open_font(int idx, int psize, int *w, int *h)
 
   // get metrics
   TTF_SizeText(f, "W", w, h);
+
+
+  int w1, h1;
+  TTF_SizeText(f, ".", &w1, &h1);
+  if (w1 != *w) {
+    int a, a1;
+    int mx, my, Mx, My;
+
+    error("size mismatch: W(%i) .(%i)\n", *w, w1);
+
+    TTF_GlyphMetrics(f, 'W', &mx, &my, &Mx, &My, &a);
+    TTF_GlyphMetrics(f, '.', &mx, &my, &Mx, &My, &a1);
+    if (a1 != a) {
+      error("advance mismatch: W(%i) .(%i)\n", a, a1);
+    }
+  }
+
   return f;
 }
~~~

**Comment by stsp** [comment]
I already checked that, and you seem to
be right! Advance is smaller than the width
returned from SizeText(), presumably because
SizeText also accounts some spacing between
chars.
So perhaps my patch can be reverted.

**Comment by stsp** [comment]
OK, TTF_GlyphMetrics() is in use now,
Thanks!

**Comment by stsp** [comment]
And yesterday's patch reverted too.
My excuse would be that the initial
bug is from Andrew, not mine. :)

**Comment by stsp** [comment]
Obviously the oldschool VGA fonts
have zero spacing between chars (which
is correct for VGA), so we were getting
the right thing from TTF_SizeText() just
by the luck.

**Comment by stsp** [comment]
Actually the unaccounted spacing is
not possible or it would break even now.
So what's wrong with TTF_SizeText()
and why it works right for some fonts
and not for others, is still unclear to me.
The description says:
```
Calculate the resulting surface size of the LATIN1 encoded text rendered using font. No actual rendering it done,
however correct kerning is done to getthe actual width. The height returned in w is the same as you can get using
3.3.4 TTF_FontHeight. 
```
The amount of typos in that description
is astonishing. Most importantly it says
that it returns height in w! I'd say its just
another typo, but they don't seem to be
kidding, and indeed return something in
w that doesn't stand for a width.

**Comment by stsp** [comment]
> Actually the unaccounted spacing is
> not possible or it would break even now.

It appears there is!
So it seems, with this font we always
get 1 or 2 trailing pixels in the drawing,
which we cut off by doing
`rect.w = min(srf->w, font_width * len);`
This trailer is not per every char, but
rather per most strings. It seems to
depend on what the last char in the
string is.
I checked the VGA fonts, and they have
the same problem too, but it affects
much, much fewer chars, and obviously
doesn't affect W char, so our metrics
from W were good.
So... while the monospaced fonts should
not do any kerning between chars, it looks
like they do some at the end of the line.
So what can this be?

**Comment by andrewbird** [comment]
Cool, thanks working fine now. Sorry about the historical bug!

Interesting, the docs here https://www.libsdl.org/projects/docs/SDL_ttf/SDL_ttf_32.html are as you mention, however over here http://sdl.beuc.net/sdl.wiki/SDL_ttf/Functions/Attributes/TTF_SizeText seem to be fine. I wonder which is the current official version?

**Comment by stsp** [comment]
> Sorry about the historical bug!

Its still unclear.
I suspect there is still the bug in the
fonts. So likely not yours.

**Comment by andrewbird** [comment]
Mmm, it seems I've faced this before, here's a clip from an unpushed experiment branch
```c
+    // get metrics (fontlineskip x advance)
+    if (TTF_GlyphMetrics(f, 'W', NULL, NULL, NULL, NULL, &fontsizes[i].width) == -1)
+      TTF_CloseFont(f);
+      printf("TTF_FontGlyphMetrics: error is '%s'\n", TTF_GetError());
+      return 0;
+    }
+    fontsizes[i].height = TTF_FontLineSkip(f);
~~~

**Comment by stsp** [comment]
Probably we need a test-case that
checks all chars for a mismatch between
TTF_FontGlyphMetrics and TTF_SizeText,
and post the results to the font authors.
TTF_SizeText() is not buggy - its in agreement
with the actual rendering. Its just that we
cut off the resulting size by hands now,
so that works. More or less.

**Comment by andrewbird** [comment]
It seems that official link you posted is a stale copy on the same site, the second one appears fine!
https://www.libsdl.org/projects/docs/SDL_ttf/SDL_ttf_32.html
https://www.libsdl.org/projects/SDL_ttf/docs/SDL_ttf_39.html#SEC39
