### ISSUE TITLE
Black window after resize with TTF fonts

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#1428]
**Describe the bug**
When starting dosemu with scalable fonts the output works at first. But after resizing the window (either through manipulating the window size or ctrl-alt-f) the window turns black and stays that way.

**To Reproduce**
1) Run dosemu with a scalable font
2) ctrl-alt-f

**Attach the log**
I haven't found any obvious channels to enable

**Additional info**
$_SDL_hwrend = (off)
Using an Nvidia GPU. I don't have an AMD GPU for testing right now.

The display can be recovered by starting a VGA program and exiting it.
1) start dosemu
2) ctrl-alt-f or resize the window manually. The screen is black now
3) start windows. Ideally you have "win" in your %PATH% now because you are blind
4) ctrl-alt-f twice; Somehow needed to recover in fullscreen mode. Not needed when you just resize
5) quit windows
6) Enjoy working high res fonts

This is how I created the qbasic-ok.png screenshot in bug 1426.

**Comment by stsp** [comment]
I added more verbose output on ttf errors.
If that catches nothing, please see if in the
+v log the strings "SDL_draw_string" are
appearing after its already dark.

**Comment by stefand** [comment]
No new error is printed afaics.

Boot.log is attached. And yes, SDL_draw_string still shows up.


[boot.log.gz](https://github.com/dosemu2/dosemu2/files/6167597/boot.log.gz)

**Comment by stefand** [comment]
setting a mode with xmode (including a redundant change) also brings back display output.

**Comment by stsp** [comment]
There is this code in sdl.c:
```
      case SDL_WINDOWEVENT_RESIZED:
        v_printf("SDL: window resized %dx%d\n", event.window.data1, event.window
        real_win_width = event.window.data1;
        real_win_height = event.window.data2;
#if defined(HAVE_SDL2_TTF) && defined(HAVE_FONTCONFIG)
        if (current_mode_class == TEXT)
          setup_ttf_winsize(event.window.data1, event.window.data2);
#endif
```

Could you please check that setup_ttf_winsize()
is actually called on every resize?
And that the resize events are actually coming in.

**Comment by stefand** [comment]
The events come in and setup_ttf_winsize is called

**Comment by stefand** [comment]
Fwiw no SDL_WINDOWEVENT_RESIZED event is coming in on manual xmode -mode XX calls, which restore the text.

**Comment by stefand** [comment]
but setup_ttf_winsize is called on those. And the difference is the "i" at the end:

calling setup_ttf_winsize
SDL: setup_ttf_winsize called with xtarget 1004, ytarget 762
SDL: point size 20 fits xtarget = 1004, xnow = 960, ytarget = 762, ynow = 650
SDL: setup_ttf_winsize called with xtarget 960, ytarget 650
SDL: point size 0 fits xtarget = 960, xnow = 960, ytarget = 650, ynow = 650

Does the "reduce to fit if necessary" loop confuse a font index with a font size?

**Comment by stefand** [comment]
Calling SDL_change_mode(0, 0, event.window.data1, event.window.data2); instead fixes the issue. I guess some of the setup work in SDL_change_mode is necessary for drawing to work on the resized window.

**Comment by stsp** [comment]
Does patch from Andrew fix also this?

**Comment by andrewbird** [comment]
I wouldn't expect it to.

**Comment by stsp** [comment]
> SDL: point size 0 fits xtarget = 960, xnow = 960, ytarget = 650, ynow = 650

I don't see such thing in your log.

**Comment by stsp** [comment]
> I guess some of the setup work in SDL_change_mode is necessary for drawing to work on the resized window.

Check if maybe this is some op with
render, like:
```
SDL_RenderSetLogicalSize(renderer, 0, 0);
SDL_SetRenderDrawColor(renderer, 0, 0, 0, 0);
SDL_RenderClear(renderer);
SDL_RenderPresent(renderer);
```

Try adding these lines manually where
`Calling SDL_change_mode(0, 0, event.window.data1, event.window.data2); instead fixes the issue. `.

**Comment by andrewbird** [comment]
~~~
but setup_ttf_winsize is called on those. And the difference is the "i" at the end:

calling setup_ttf_winsize
SDL: setup_ttf_winsize called with xtarget 1004, ytarget 762
SDL: point size 20 fits xtarget = 1004, xnow = 960, ytarget = 762, ynow = 650
SDL: setup_ttf_winsize called with xtarget 960, ytarget 650
SDL: point size 0 fits xtarget = 960, xnow = 960, ytarget = 650, ynow = 650
~~~

`point size 0` - that's odd

**Comment by stefand** [comment]
> SDL_RenderSetLogicalSize(renderer, 0, 0);
> SDL_SetRenderDrawColor(renderer, 0, 0, 0, 0);
> SDL_RenderClear(renderer);
> SDL_RenderPresent(renderer);
> ```
> 
> Try adding these lines manually where
> `Calling SDL_change_mode(0, 0, event.window.data1, event.window.data2); instead fixes the issue. `.

This helps; However, dosemu randomly crashes on resize. Calling SDL_change_mode does not have that problem

**Comment by stsp** [comment]
Which one helps?

**Comment by stefand** [comment]
SDL_RenderPresent is enough to make text show up, but without SDL_RenderClear the output is sometimes corrupted after resizing (can be perceived as flickering during resize). The corruption looks as if a small surface is memcpy'd onto a bigger surface without taking their respective pitch into account.

**Comment by stsp** [comment]
So where precisely do you put that in,
can you show the diff?

**Comment by stefand** [comment]
Here you go. It is very crude I know...
[font.txt](https://github.com/dosemu2/dosemu2/files/6185563/font.txt)

**Comment by stsp** [comment]
There is a func `do_redraw()` that also
does RenderPresent.
Please make sure it is called after resize
(it should be called many times, by timer).
If it is - I have no idea how your RenderPresent
is better than my RenderPresent. :)

**Comment by stsp** [comment]
Maybe you can give me the
vnc access to fix this.

**Comment by stefand** [comment]
ah sorry, I am travelling and did not have much time to look into it. And right now I don't even have a public IP address :-(

**Comment by stsp** [comment]
Hmm, so because we don't use the
intermediate texture when rendering
text, we update only the part of the
screen, and the remainder becames
dark?

**Comment by stefand** [comment]
No, that's what happens with hwrend = on.

This bug here also happens with hwrend = off. I guess there is some race condition when resizing the window.

**Comment by stsp** [comment]
Maybe there are multiple bugs here.
But I find it rather risky to depend on
a fact that renderer keeps our old
image after RenderPresent(), after
resize etc.
So I applied a small patch into a
branch sdl_txt - could you please
see if it makes any difference?

**Comment by stsp** [comment]
I also have closed a few races.

**Comment by stefand** [comment]
Well, this is weird: With those patches I get the CPMMListener signals with hwrend = off too.

Maybe SetRenderTarget forces hwrend???

**Comment by stefand** [comment]
Looking at what it is actually supposed to fix: No, it doesn't work, I think because of SDL_draw_text_cursor and/or SDL_draw_line.

**Comment by stefand** [comment]
[cursorfix.txt](https://github.com/dosemu2/dosemu2/files/6672336/cursorfix.txt)

This on top of your sdl_txt branch makes TTF text work correctly with hwrend=on and hwrend=off, both in windowed and fullscreen mode. (Somehow windowed mode on Nvidia didn't actually flip front/back but copy like software rendering did).

I'd have to check on my AMD card with threaded rendering on.

**Comment by stsp** [comment]
Thanks, I re-pushed the missing bits.
Could you please re-check?
I also wonder if missing locks alone
change something, so I rearranged
the patches and put them before render
target.

**Comment by stefand** [comment]
Now this is weird: this branch now works perfectly, even with nvidia + hwrend = on + threaded render. I am rebuilding to see if I screwed up something

**Comment by stefand** [comment]
yeah never mind the previous line. I was running the wrong build.

To answer the questions:
1) threaded render = 1: CPMMListener issues, regardless of hwrend
2) threaded render = 0: text + graphics work fine, with hwrend = 1 as well as hwrend = 0

**Comment by stsp** [comment]
> threaded render = 0: text + graphics work fine, with hwrend = 1 as well as hwrend = 0

What exactly patch fixed the
problem? Locking or render target?

**Comment by stsp** [comment]
... or there was no problem with !threaded case?

**Comment by stefand** [comment]
The render target changed fixed it. I.e. my patch before you pushed the extra locking.

**Comment by stsp** [comment]
OK, thanks.

**Comment by stsp** [comment]
Hi @stefand I've finally got to
revamp the SDL rendering, so
that now it is both threaded and
fully supports HW accel. :)
Such a mix appears possible
because SDL has
`SDL_CreateSoftwareRenderer()`
which can co-exist with HW
renderer - something I didn't
know before. So it appears SDL
"kinda" supports threaded rendering,
if you are very careful. :)

Could you please re-spin your
earlier HW-accelerated tests?
Would be good to know how it
goes and can (or should?) I enable
the HW rendering by default now.
