### ISSUE TITLE
PPA broken as of 2021-03-19

### ISSUE THREAD

**Issue by robert-j** [dosemu2/dosemu2#1430]
**Describe the bug**
A description of what the problem is.

Starting with release `dosemu2 (2.0~pre8-6766-0a698c26d+202103190250~ubuntu20.10.1)` the installation does not provide the "dosemu" binary anymore. It renders the package useless.

**System**

Ubuntu 20.10 groovy amd64

**To Reproduce**

Either install from PPA or just look at the currently provided DEB file:

`mkdir tmp`
`apt-get download dosemu2`
`dpkg-deb -R dosemu2_2.0~pre8-6766-0a698c26d+202103190250~ubuntu20.10.1_amd64.deb  tmp`

You'll find no binaries in tmp. Only /usr/share/* and /etc/* files.

**Comment by robert-j** [comment]
The issue persists in `dosemu2_2.0~pre8-6767-faba3cf63+202103192047~ubuntu20.10.1_amd64.deb`

**Comment by stsp** [comment]
Unfortunately LP is currently down
and doesn't rebuild the package.
Hope will work tomorrow.

**Comment by stsp** [comment]
It says "in 5 hours (estimated)"

**Comment by robert-j** [comment]
Thank you. I have already built dosemu2 from sources so it's not urgent for me.

**Comment by stsp** [comment]
I think the repo is up and running, so
the problem should now be fixed.
Its quite surprising though, as I had to
revert an absolutely ancient patch...
