### ISSUE TITLE
what's wrong with EMS test?

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1431]
https://github.com/dosemu2/dosemu2/runs/2157791400
```
======================================================================
ERROR: Test MS-DOS-6.22 Memory EMS (Borland)                                           
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dos.py", line 3370, in test_memory_ems_borland
    pt3start = results.index("  PART THREE")
ValueError: substring not found
```

And locally it works perfectly.
What error is that?

**Comment by andrewbird** [comment]
I looked and can't see anything wrong in the test results, but I wonder if some timeout is being hit since the switch to emulation from kvm slowed things down. I expect if run again it will be fine!

**Comment by stsp** [comment]
But is `ValueError: substring not found` the right
way of reporting a timeout? I think it means a bug
in a script?

**Comment by andrewbird** [comment]
>But is ValueError: substring not found the right
way of reporting a timeout?

Certainly not! It means I didn't consider the string wouldn't be there. At the very least I should print what is there at that point in time. It's a little awkward with this Borland test as it expects user response to page the results. I'll have a look to see what can be done to make it more robust.

**Comment by stsp** [comment]
If the test can't be handled reliably,
feel free to disable. Last thing we need
is the unreliable tests.

**Comment by andrewbird** [comment]
I'm thinking it might be better to just patch out the wait for keypress in the binary. It that okay in principle?

**Comment by stsp** [comment]
If there are no sources...

**Comment by stsp** [comment]
Since you keep that archive on your
server anyway, then just patch it manually
and re-upload, rather than in the test script, right?
