### ISSUE TITLE
Debian package support?

### ISSUE THREAD

**Issue by NoaHimesaka1873** [dosemu2/dosemu2#1435]
I use debian on my old laptop and I want to use this. Sadly there's no debian deb and those binaries on GitHub is too old.

**Comment by stsp** [comment]
There are no debian deb but are
daily ubuntu debs. Are they not suitable
for you? Please provide more details.

**Comment by NoaHimesaka1873** [comment]
@stsp forcibly adding ubuntu ppa into debian and installing it throws dependency error. i currently use debian unstable/sid
![스크린샷_2021-03-25_13-39-54](https://user-images.githubusercontent.com/39993457/112419930-9ffd5c80-8d6f-11eb-8e94-243d99f20c31.png)

**Comment by stsp** [comment]
https://www.addictivetips.com/ubuntu-linux-tips/use-ubuntu-ppas-on-debian-linux/

See step 6 in this guide.
You need to make it use focal packages,
not hirsute. If even focal is too high, try
bionic, but the package there is called
dosemu2-legacy and is unsupported.

**Comment by NoaHimesaka1873** [comment]
@stsp ah yes, focal works for me. closing the issue.

**Comment by stsp** [comment]
If you want, you can write up the
instructions for debian users, to
help others with similar problem.

**Comment by javacom** [comment]
Manually add this key.
wget -qO - https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xebe1b5ded2ad45d6 | sudo apt-key add -
