### ISSUE TITLE
Stop CDDA playback on exit?

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#1436]
Settlers 2 has an option to play CD Audio tracks, which works mostly fine via dosemu2 and cdemu [1]. Settlers 2 doesn't bother to stop playing the track on exit, and in the good old days that meant you could reboot your box and have CD sound while editing your bios settings.

Nowadays the audio keeps playing after dosemu2 exits. While it is technically correct, it feels more like a bug than a feature. Is it possible to issue a CDDA stop command on exit if (and only if, as there may be some other app playing) cd playback has been started in the dosemu session?

1: https://github.com/cdemu/cdemu/issues/8

**Comment by stsp** [comment]
I think this is a cdemu bug: why doesn't
it stop when the cdrom fd closes?
Anyway, I added the explicit stop.
