### ISSUE TITLE
lredir t: \\linux\fs\ gives assertion error

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1437]
**Describe the bug**
When I run `lredir t: \\linux\fs\` this error is printed:
```
dosemu.bin: mfs.c:3089: path_list_contains: Assertion `plen && path[plen - 1] == '/'' failed.
```
Then CPU usage is high for a while and DOSEMU2 quits.

**To Reproduce**
Type `lredir t: \\linux\fs\` in a freshly started DOSEMU2.

**Attach program/game binaries or provide an URL**
n.a.

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/6217339/boot.log)

**A regression?**
Seems so.

**Additional info**
Pretty standard FDPP install.

**Comment by stsp** [comment]
Should now be fixed.

> When I run lredir t: \\linux\fs\ this error is printed:

Only if $_lredir_paths was customized.

**Comment by jschwartzenberg** [comment]
Yeah, I have `$_lredir_paths = "/"` :)

**Comment by stsp** [comment]
Bad practice.
`~` is now supported in `$_lredir_paths`.

**Comment by jschwartzenberg** [comment]
I'm redirecting also stuff outside my homedir, notably `/nas`.

**Comment by stsp** [comment]
You can add it as well.

**Comment by jschwartzenberg** [comment]
It seems the issue isn't fully fixed yet:
![Screenshot_20210328_234147](https://user-images.githubusercontent.com/877112/112769028-3a36fc00-901f-11eb-828f-c4ebdaabc916.png)
Console output:
```
ERROR: MFS: invalid path \
```

**Comment by andrewbird** [comment]
Proper format of the UNC should now be \\Linux\fs/

**Comment by jschwartzenberg** [comment]
Ah yeah that works, thanks! I didn't know that compatibility was being broken. That might be useful to highlight somehow.

**Comment by stsp** [comment]
> I didn't know that compatibility was being broken.

This was a long ago deprecated syntax.
If you see `lredir -h` - it says only about
using unix paths, w/o any prefixes at all.
Prefixes may disappear in the future too.

**Comment by andrewbird** [comment]
> Prefixes may disappear in the future too.

It would be simpler for lredir use, but I think that the redirector still has to accept them (via int21/5f03 etc) or things like pcgeos/breadbox automatic drive restoration (#710) will begin to fail.

Also seeing that we've broken compatibility, is there any reason now for lredir2 to exist, so could its functionality be merged back into lredir?

**Comment by stsp** [comment]
> pcgeos/breadbox automatic drive restoration (#710) will begin to fail.

What is the exact reason for
them to fail w/o prefixes?

> is there any reason now for lredir2 to exist

Does it?

```
C:\>lredir2
Bad command or file name - lredir2
```

**Comment by andrewbird** [comment]
> Does it?

Apparently not! You caught me! I never used it, I just continued to used the old lredir and ignored any deprecation messages. :smile:

> What is the exact reason for
them to fail w/o prefixes?

I'm guessing here, but from what I understand the response from int21/5f02 is remembered (it would normally include the prefix else we don't know which redirector is providing each drive), and that same resource string is supplied next time to int21/5f03 to restore it, so they have to match. It may not be a problem if we don't return the prefix on each int21/5f02 result, but I don't know for sure.
It would seem that just trimming the `\\LINUX\FS` prefix from the strings displayed by lredir would give the same impression to the user, and leaving the int21/5f0? interface as is wouldn't break anything.

**Comment by stsp** [comment]
> I never used it,

See emudrv.com nevertheless.

> It may not be a problem if we don't return the prefix on each int21/5f02 result, but I don't know for sure.

I hope its not a problem.
But so far I do not rush at the
removal of prefix. There is an
additional stopper, which is a
printer resource name.

> It would seem that just trimming the \\LINUX\FS prefix from the strings displayed by lredir would give the same impression

Might be a good idea, feel free
to implement. So far I made it to
display the unix path but with prefix.

**Comment by stsp** [comment]
Yes but that would make an asymmetry
with the input functions. And geos will stop
working. :)

**Comment by andrewbird** [comment]
No, I don't think so. PCGEOS won't use EX6 as it calls the 5f02 function itself, not lredir.

**Comment by stsp** [comment]
OK, I haven't thought of a possibility
of using normal API across lredir
internally, but use EX6 exclusively
for displaying purposes.
So if that looks simpler than the
alternative (stripping prefix by hands),
feel free to do that. :)

**Comment by stsp** [comment]
Done it the EX6 way.
