### ISSUE TITLE
Unable to kill command-line programs with Ctrl+C

### ISSUE THREAD

**Issue by magiblot** [dosemu2/dosemu2#1438]
**Describe the bug**
Command-line programs such as `cat` cannot be killed by pressing keys like Ctrl+C, Ctrl+D or Ctrl+Break.

**To Reproduce**
Run `cat` and try to exit it.
![Screenshot_20210328_211054](https://user-images.githubusercontent.com/20713561/112764684-17e6b380-900a-11eb-8429-545fee443029.png)

**Attach the log**
`-Da` log: [boot.zip](https://github.com/dosemu2/dosemu2/files/6217914/boot.zip)

**Additional info**
Using https://github.com/dosemu2/dosemu2/commit/32bd2894bdc3676d111574b38a21c2214c4b98cc, https://github.com/dosemu2/fdpp/commit/ad970d626ed33578d8b188df3aa4d8b8bc80ec9f and https://github.com/dosemu2/comcom32/commit/d64f704d370e75b2fdc48c247cdea14c34e8a754.

**Comment by stsp** [comment]
Break control is not yet implemented
in comcom32. You can use freecom as
a work-around.

**Comment by magiblot** [comment]
Thanks for the clarification. Actually, is there any advantage in using comcom32?

**Comment by stsp** [comment]
No big ones.
If freecom suits your needs, feel free
to switch. So far comcom32 have loose ends.

**Comment by stsp** [comment]
Note that ^D is not a EOF in dos,
it is so in unix.
You can use ^Z perfectly though,
even with comcom32.

**Comment by stsp** [comment]
I tried to address a few bugs in int23
code, before adding the BREAK support
to comcom32. But the patches are
untested, as was the initial int23 impl
17 years ago... well, actually 17 years
ago I tested them, made sure they do
not work, and committed nevertheless
(thinking that buggy impl is better than
no impl), but now I forgot what was the
test-case. :)

 @Baron-von-Riedesel IIRC you were
saying that many DPMI apps have bugs
wrt ^C interruption. That made me to
commit the code that I never got to work -
why to care if the clients are buggy. :)
But reviewing that problem again, I hope
the proper handling is possible. Do you
still remember what was the test-case?
Where are those buggy DPMI progs that
crash when int23 handler tries to terminate
them? I'd like to re-test them, but I have
completely forgot where they are.

**Comment by Baron-von-Riedesel** [comment]
> Do you still remember what was the test-case?

No, sorry!

**Comment by stsp** [comment]
Does int23 work reliably under hdpmi
these days?

**Comment by ecm-pushbx** [comment]
I determined that lDebugX in Protected Mode receives a call to its PM int 23h handler upon Control-C but regardless of the return its process is *not* aborted. This is why I switched to using `rawinput` in DPMI even when reading from DOS stdin (instead of calling int 21h service 0Ah for line editing) so that I can detect the flag set by my PM int 23h handler at any time.

**Comment by stsp** [comment]
Cool!
Could you please retry with current git?
Note: it will not terminate unless both of
the below is true:
- you left the flags word on stack
- you set CF

If either condition is not satisfied,
the termination request is suppressed.

**Comment by stsp** [comment]
How about checking with dosemu2?

**Comment by ecm-pushbx** [comment]
Checked with the same patched lDebugX on `dosemu2 2.0pre8-20210410-2880-g65853ec95 Configured: 2021-06-16 14:45:10 +0200` and it crashes the VM if I enter the following:

```
ldebugx.com lddebugx.com dpmimini.com
r dco3 or= 300_0000
g
r dco3 or= 300_0000
g
g 15D
^C
```

So it appears that dosemu2 indeed tries to terminate the process, which crashes eventually. (lDebugX without the patch always returns with No Carry and retfd 4 so everything is fine in that case.)

**Comment by stsp** [comment]
Why testing an old revision?

**Comment by ecm-pushbx** [comment]
Because that's the most recent one I have around without rebuilding right now. By the way, setting flag DCO3 100_0000h of lDDebugX only makes it work. That's the "set Carry" option. Setting flag DCO3 200_0000h (with or without 200_0000h), which is the use retfd (not retfd 4), causes a crash always.

**Comment by ecm-pushbx** [comment]
I'll pull and rebuild now.

**Comment by ecm-pushbx** [comment]
Trying with the latest dosemu2 results in DCO3 flags both clear, or one of them set and the other clear, in not terminating the process. Which means it works for my purposes. Setting both flags crashes somewhat (though not the entire VM). So that appears to do what you want it to. https://pushbx.org/ecm/test/20210811.2

```
$ ~/proj/newnewdosemu/dosemu2/bin/dosemu -I 'floppy { device diskette.img }' -dumb -I "serial { com 2 device /tmp/vptty-dos }"
dosemu2 2.0pre8-20210811-3089-g822e48a85 Configured: 2021-08-11 16:15:39 +0200
Get the latest code at http://dosemu2.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.


-; Welcome to lDebug!
FreeDOS kernel - SVN (build 2042 OEM:0xfd) [compiled Jan 24 2020]
Kernel compatibility 7.10 - BORLANDC - 80386 CPU required - FAT32 support

(C) Copyright 1995-2012 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
EMUFS host file and print access available
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
dosemu CDROM driver installed (V0.2)
Kernel: allocated 36 Diskbuffers = 19152 Bytes in HMA
emufs: redirector enabled
Bad command or filename - "d:\autoexec.bat".
C:\>a:
A:\>ldebugx.com lddebugx.com dpmimini.com
-g
DPMI entry hooked, new entry=02BE:85D6
~-g
DPMI entry hooked, new entry=1F7A:85F6
Protected mode breakpoint at 015Dh.
32-bit code segment breakpoint at 016Fh.

Unexpected breakpoint interrupt
AX=0200 BX=00E6 CX=0105 DX=000A SP=FFFC BP=0000 SI=0253 DI=85F6
DS=3C49 ES=4C4A SS=3C49 CS=3C49 IP=013E NV UP EI PL ZR NA PE NC
3C49:013E 89E5              mov     bp, sp
~-g 15d
Succeeded in unhooking interrupt 2Fh.
Succeeded in unhooking interrupt 2Fh.
AX=0001 BX=00E6 CX=0105 DX=000A SP=FFFC BP=FFFC SI=0253 DI=85F6
DS=00AF ES=00B7 SS=00AF CS=0157 IP=015D NV UP EI PL NZ NA PO NC
0157:015D 8CCB              mov     bx, cs
~#^C
^C
~#r dco3 or= 100_0000
~#^C
^C
~#r dco3 xor= 300_0000
~#^C
^C
~#r dco3 or= 300_0000
~#^C
Invalid opcode
AX=0200 BX=0031 CX=0000 DX=0000 SP=B9E4 BP=B9FA SI=0BD2 DI=B5CF
DS=1F7A ES=1F7A SS=1F7A CS=00D9 IP=1528 NV UP DI PL ZR NA PE NC
00D9:1528 FF                db      FF
-
```

**Comment by stsp** [comment]
In what environment does it work right?
QDPMI?

**Comment by ecm-pushbx** [comment]
HDPMI32 as I indicated never kills the process, whatever DCO3 flag combination is set. Some more details: It appears that our interrupt 22h entrypoint does not clean up DPMI state of the debugger. Arguably it should, I'll look into patching this.

**Comment by stsp** [comment]
> HDPMI32 as I indicated never kills the process

This doesn't qualify as "works right",
or is it?

> interrupt 22h entrypoint does not clean up DPMI state of the debugger. Arguably it should

Probably not as dosemu2 is supposed
to wipe the DPMI context before returning
to DOS that will call to int22 at some point.

**Comment by ecm-pushbx** [comment]
> > HDPMI32 as I indicated never kills the process
> 
> This doesn't qualify as "works right",
> or is it?

Depends on your expectations.
 
> > interrupt 22h entrypoint does not clean up DPMI state of the debugger. Arguably it should
> 
> Probably not as dosemu2 is supposed
> to wipe the DPMI context before returning
> to DOS that will call to int22 at some point.

The debugger has to learn that it is no longer in Protected Mode. I collected a few patches for that in https://hg.pushbx.org/ecm/ldebug/shortlog/dpmi-int23-test but it isn't complete yet.

As is, Control-C with DCO3 flags 300_0000h set will return lDebugX to 86 Mode but the PSP variable is still set to a PM selector. A command like this will reveal the variables used by the debugger:

`s $dpr:0 l ffff psp&ff psp>>8 dpr&ff dpr>>8`

That word needs to be edited to a real PSP, such as the one of DPMIMINI. Then `g=psp:0` can be used to terminate that DOS process and return to a somewhat workable state.

lDDebugX is probably harder to fix because we need to insure it won't try mode switching to PM to set or reset its handlers.

**Comment by stsp** [comment]
> The debugger has to learn that it is no longer in Protected Mode.

Maybe it should do that in int23
instead, _before_ returning with CF
set? That would avoid all the headaches.

**Comment by ecm-pushbx** [comment]
Then it would fail under HDPMI32 which doesn't terminate the process.

**Comment by stsp** [comment]
> Then it would fail under HDPMI32 which doesn't terminate the process.

Why would you return with CF there?

**Comment by ecm-pushbx** [comment]
Hmm. The PM int 21h service 4Ch [handler](https://hg.pushbx.org/ecm/ldebug/file/198b4f876797/source/pmentry.asm#l74) resets the mode switching variables and resets the handlers but it still expects the debugger be re-entered in one of its entrypoints, such as interrrupt 1, or 3, or 22h (the one that child processes of the debugger get, which is int22 in run.asm, not the one for the debugger process itself, which is debug22 in debug.asm).

**Comment by ecm-pushbx** [comment]
> > Then it would fail under HDPMI32 which doesn't terminate the process.
> 
> Why would you return with CF there?

I don't see a way to tell which DPMI host will behave which ways so if we were to return with `stc`/`retfd` we would need to support either HDPMI behaviour (no termination) or dosemu2 behaviour (termination, given some other conditions about the PSP).

**Comment by ecm-pushbx** [comment]
Anyway, I don't *want* int 23h to terminate the DPMI client part, I just would (ideally) like it to cancel the running DOS command (such as service 0Ah) and tell me in some way (callback?). Setting a flag in my application is fine for other DOS commands but precludes using service 0Ah because the service 0Ah call won't be cancelled by the int 23h.

**Comment by stsp** [comment]
> I don't see a way to tell which DPMI host will behave which ways

You need to expect the correct behavior,
and you can use fn 0x401 to see which
host is it.

> Anyway, I don't want int 23h to terminate the DPMI client part, I just would (ideally) like it to cancel the running DOS command

Of course you can if that command
has a separate PSP (not the one of
the DPMI app).

**Comment by stsp** [comment]
So will that study help us to conclude
whether the dosemu2's int23 impl is
currently buggy? Have you managed
to get it working?
dosemu2 should not terminate your
DPMI app if the PSP is different, so
is this what you want or not?

**Comment by stsp** [comment]
PSP check prevents the termination of
the DPMI app that spawned a real-mode
app, as we need to terminate only the later
one. I don't understand what you are
trying to achieve: avoid the termination
of a DPMI app and only terminate the
real-mode debugger, or what? But the
debugger is not real-mode, so obviously
you need to terminate its DPMI part too?

Anyway, I removed the sanity check now,
and you can do `retf 2` with CF set, to get
the RM-only termination. DPMI termination
is `retf` with CF set plus PSP match.
Does this work?

**Comment by ecm-pushbx** [comment]
> I don't understand what you are
> trying to achieve: avoid the termination
> of a DPMI app and only terminate the
> real-mode debugger, or what? But the
> debugger is not real-mode, so obviously
> you need to terminate its DPMI part too?

The debugger PSP is self-parented which is intended so that Critical Errors or Control-C result in control returning to the debugger. (Self-parented DOS process termination is similar to DOS TSR termination (service 31h); that is files and memory are *not* freed.)

Ideally I'd want the Control-C while the debugger is in Protected Mode eventually return control to the debugger, staying in Protected Mode, not ending the DPMI client or DOS process, aborting only the DOS service call that was in progress. (NB most DOS service calls by the debugger are actually done by calling the Real/Virtual 86 Mode DOS interrupt.)

> Anyway, I removed the sanity check now,
> and you can do `retf 2` with CF set, to get
> the RM-only termination. DPMI termination
> is `retf` with CF set plus PSP match.
> Does this work?

I can check later. Don't think I want it this way though, but I'll check.

**Comment by stsp** [comment]
> Ideally I'd want the Control-C while the debugger is in Protected Mode

There is no such thing.
int23 is always raised by DOS, so in
real mode. But DPMI server intercepts
it and calls the prot mode handler.
The handling rules of int23 (and int24
and int1c) are different from normal ints.

**Comment by stsp** [comment]
> not ending the DPMI client or DOS process, aborting only the DOS service call that was in progress.

So by self-parenting the PSP you
avoid the RM termination. By doing
`retf 2` with CF set you avoid the PM
termination (with the latest git).
What remains is the termination of an
I/O call and return to PM.
I think this is exactly what you ask for.

**Comment by ecm-pushbx** [comment]
> > It's unclear to me how to manage the syscall cancellation and the return to PM
> 
> RBIL says:
> 
> ```
> return via RETF with CF set or (MS-DOS 1,DR DOS) RETF 2 with CF set
> DOS will abort program with errorlevel 0
> else (RETF/RETF 2 with CF clear or IRET with CF ignored)
> interrupted DOS call is restarted
> ```
> 
> Which presumably means the system call is
> not restarted for the first case, even with
> self-parented PSP.
> I haven't checked that theory though.

That's correct, but it doesn't get us all the way to where I want to go.

**Comment by stsp** [comment]
Break handling was added to comcom32
and the dosemu2 code seems reliable too,
except that I haven't tested the ^C of the
PM app.
