### ISSUE TITLE
Default windowed resolution results in blurring in KDE Plasma

### ISSUE THREAD

**Issue by magiblot** [dosemu2/dosemu2#1441]
**Describe the bug**
Newly opened dosemu windows look blurred due to having the wrong resolution in the KDE Plasma desktop environment (X11 with or without compositing / Wayland). This doesn't appear to be an issue in GNOME and Weston.

Actual behaviour (window's interior is 710x394):
![Screenshot_20210402_194937](https://user-images.githubusercontent.com/20713561/113440902-974efb00-93ed-11eb-9f0b-5ee5a0eef786.png)

Expected behaviour (window's interior should be 720x400):
![Screenshot_20210402_194953](https://user-images.githubusercontent.com/20713561/113440912-9c13af00-93ed-11eb-9864-e22724cc297b.png)

**Attach the log**
`-Da` log: [boot_3.zip](https://github.com/dosemu2/dosemu2/files/6250746/boot_3.zip)

**A regression?**
Used to work fine in 18b56eb3014b5e23c63e68b403cdf440a47ff925 (the version I used before upgrading).

**Additional info**
Using https://github.com/dosemu2/dosemu2/commit/997f2c1a36df3264be61dc0f41ce5897ebcaae2a.

**Comment by stsp** [comment]
Try reverting feda0dc, maybe it
causes some problems...

**Comment by magiblot** [comment]
After #1442 was fixed, I realized this only affects the X plugin, which I'm not interested in using. So feel free to just close this issue.

**Comment by stsp** [comment]
Ok, good to know.
