### ISSUE TITLE
Display artifacts in text-based applications

### ISSUE THREAD

**Issue by magiblot** [dosemu2/dosemu2#1442]
**Describe the bug**
Text-based applications may experience display artifacts:

![mpv-shot0007](https://user-images.githubusercontent.com/20713561/113452259-f3247e80-9403-11eb-9aaa-7d6296d4c4f8.png)

The following only happens in X11 environments:

![mpv-shot0006](https://user-images.githubusercontent.com/20713561/113452339-14856a80-9404-11eb-93d5-815593a3a4cd.png)

**To Reproduce**
See the following screen recording:

https://user-images.githubusercontent.com/20713561/113452400-2e26b200-9404-11eb-80b5-a7e1170598f0.mp4

**Attach program/game binaries or provide an URL**

[tvdemo16.zip](https://github.com/dosemu2/dosemu2/files/6251183/tvdemo16.zip)

**Additional info**
Using https://github.com/dosemu2/dosemu2/commit/997f2c1a36df3264be61dc0f41ce5897ebcaae2a, Linux 5.11.11, SDL2 2.0.14, KDE Plasma 5.21.3.

**Comment by andrewbird** [comment]
> The following only happens in X11 environments:

Does it happen when using the SDL plugin in those X11 environments, or only with the X plugin?

**Comment by magiblot** [comment]
> > The following only happens in X11 environments:
> 
> Does it happen when using the SDL plugin in those X11 environments, or only with the X plugin?

I can reproduce with both `-X` and `-S`, if that's what you mean.

**Comment by andrewbird** [comment]
Yes, that's what I meant , thanks!

**Comment by stsp** [comment]
Does this happen with `$_force_vga_fonts = (on)`?

**Comment by magiblot** [comment]
> Does this happen with `$_force_vga_fonts = (on)`?

Yes, it does, with both `-X` and `-S`.

**Comment by stsp** [comment]
Tried with bc 3.1 (which is
also turbo-vision) and can't
reproduce that.
Is this specific to some prog?

**Comment by magiblot** [comment]
No, I can reproduce with any text-based application. Even in the BC 3.1 IDE:

![Screenshot_20210402_234010](https://user-images.githubusercontent.com/20713561/113456219-ebb5a300-940c-11eb-961e-1fdf71117004.png)

**Comment by stsp** [comment]
Does this happen when #1441
does not trigger? I.e. on the properly
sized window.

**Comment by magiblot** [comment]
Yes, even in fullscreen :(

I think I got it: it only happens with `$_X_lin_filt = (on)` or `$_X_bilin_filt = (on)`.

**Comment by stsp** [comment]
On SDL???
Did you set $_SDL_hwrend=(on)?

**Comment by magiblot** [comment]
> On SDL???

Yes. In `.dosemurc` it says `Some apply to SDL (dosemu -S) driver as well.`, maybe this is the case of the (bi)linear filtering options.

> Did you set $_SDL_hwrend=(on)?

Toggling that option does not change the result.

**Comment by stsp** [comment]
> Toggling that option does not change the result.

There was no filtering in SDL
itself w/o that option. Software
renderer never had it.
But I guess you took SDL from
hg, and maybe now there is one...
Still doesn't explain why the same
problem can happen with -X.

**Comment by magiblot** [comment]
During application startup the following error occurs:

```
ERROR: /usr/lib/dosemu/libplugin_sdl.so: undefined symbol: setup_ttf_winsize
```

Maybe it falls back on X because of that.

**Comment by stsp** [comment]
Of course it does.
Should now be fixed.

**Comment by magiblot** [comment]
Thank you. Everything works as expected now. And sorry for not having shared a log in the first place, it would have helped find this earlier.

During build the following warnings were issued. You may be interested in turning them into errors so that this kind of issue doesn't happen in the future:

```
sdl.c: In function ‘SDL_change_mode’:
sdl.c:788:5: warning: implicit declaration of function ‘setup_ttf_winsize’ [-Wimplicit-function-declaration]
  788 |     setup_ttf_winsize(w_x_res, w_y_res);
      |     ^~~~~~~~~~~~~~~~~
sdl.c:788:5: warning: nested extern declaration of ‘setup_ttf_winsize’ [-Wnested-externs]
```

So many of the issues I've been facing are related to the X plugin. I guess you already assume some things are broken there and you expect people to just use the SDL plugin. To avoid issues like this in the future, it may help to also print a warning that the SDL plugin is not being used even if the `-S` argument was provided,

**Comment by andrewbird** [comment]
IMHO if a user specifies -S then no fallback should be performed if SDL is unavailable, just an error and quit. Is that reasonable?

**Comment by stsp** [comment]
> IMHO if a user specifies -S then no fallback should be performed if SDL is unavailable, just an error and quit.
> Is that reasonable?

Yes but currently the handling of -S
and the actual load of sdl plugin are
a bit dis-joined. So I just added the
plain errors. Feel free to submit the
patch if you want a hard termination
in that case.
