### ISSUE TITLE
Cosmo's Cosmic Adventure doesn't start

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1443]
**Describe the bug**
When starting the game only a black screen stays.

**To Reproduce**
Install and run the game.

**Attach program/game binaries or provide an URL**
ftp://ftp.3drealms.com/share/1cosmo.zip

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/6252345/boot.log)

**A regression?**
No, dosemu 1.4 has the same issue.

**Comment by jschwartzenberg** [comment]
Woa you're fast!!! Is the game buggy? I'm curious if you could fix #102 similarly or whether you already looked at it and it seems harder :)

**Comment by stsp** [comment]
Yes, that one is more difficult
as it end up not seeing some
keypresses that are needed
to start the game.

**Comment by jschwartzenberg** [comment]
Hmm, that gives me three (probably silly) questions:
1. Why does a game need keypresses to start it?
2. Would bashing keyboard keys work to start it as a workaround?
3. Can't a similar patch be made to skip the need for keypresses?

**Comment by stsp** [comment]
> Why does a game need keypresses to start it?

Because the game (any) is
controlled by a keyboard.

**Comment by stsp** [comment]
Gratis Bio Menace is also affected.
See #1575
