### ISSUE TITLE
Wrong mouse location after INT 10h, 1130h

### ISSUE THREAD

**Issue by magiblot** [dosemu2/dosemu2#1444]
**Describe the bug**
16-bit Turbo Vision applications exhibit weird mouse behaviour when the keyboard caret is visible. In particular, the mouse location is reported to be (0, 0) after a mouse click until the mouse is moved again:

https://user-images.githubusercontent.com/20713561/113492989-f55a0c00-94db-11eb-8dfe-3cd17e103ff2.mp4

In the video, pay attention to the `.where = TPoint` output, which shows the reported mouse location. When the "Event Viewer" window is focused, the keyboard cursor becomes visible: when clicking anywhere on the event viewer, the mouse location becomes (0, 0). When focusing another view, such as the help window or the menus, the keyboard cursor is hidden and the mouse location is reported properly again.

I tracked the problem down to the following invocation to INT 10h, service 11h, sub-service 30h in the function responsible of  making the keyboard cursor visible:

https://github.com/magiblot/tvision/blob/222c5042bd4ffd0ac8fb673c680d0d9301a2ab23/source/tvision/tvcursor.asm#L122-L131

```asm
        CALL    @TDisplay@isEGAorVGA$qv
        JE      @@cga

        MOV     AX, 1130H
        XOR     BL, BL
        PUSH    BP
        INT     10h ; <<<< here
        POP     BP
        MOV     [base], CL
@@cga:
```

If I comment out the invocation to INT 10h, the mouse location is no longer misreported:

https://user-images.githubusercontent.com/20713561/113493189-95fcfb80-94dd-11eb-889b-ed95eb957202.mp4

This problem does not occur on Windows XP or MS-DOS 7.1 on real hardware.

If it has any importance, Turbo Vision uses an asynchronous callback to read mouse events:

https://github.com/magiblot/tvision/blob/40939a6a8de6ad67a36678a5b27d8b724f83f8b2/source/tvision/tevent.cpp#L248-L286
https://github.com/magiblot/tvision/blob/40939a6a8de6ad67a36678a5b27d8b724f83f8b2/source/tvision/tevent.cpp#L83
https://github.com/magiblot/tvision/blob/cad8f215ceb6b319ea06ef3d5e308546281002e5/source/tvision/tmouse.cpp#L165-L179

**Attach program/game binaries or provide an URL**
The program used in the first video: [TVDEMO.zip](https://github.com/dosemu2/dosemu2/files/6253675/TVDEMO.zip)

**Attach the log**
`-D+9mv` log: [boot.zip](https://github.com/dosemu2/dosemu2/files/6253697/boot.zip)
`-D+9mv` log after commenting out the aforementioned INT 10h instruction: [boot.zip](https://github.com/dosemu2/dosemu2/files/6253707/boot.zip)

**Additional info**
Using dcf83c350.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by magiblot** [comment]
Great! Thank you.
