### ISSUE TITLE
Can't redirect ${HOME} since eb1bf967d

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#1450]
**Describe the bug**
Since commit eb1bf967d3671d1783fa68a14e2d380492a85124 redirecting ${HOME}, or subdirectories thereof, is broken. It either complains (incorrectly) about $_redir_paths or that the directory is not found.

C:\>lredir f: \\linux\fs/${HOME}
Error 5 (access denied) while redirecting drive F: to \\linux\fs/${HOME}
Add the needed path to $_lredir_paths list to allow

old syntax fails too:
C:\>lredir f: \\linux\fs\${HOME}
Error 5 (access denied) while redirecting drive F: to \\linux\fs\${HOME}
Add the needed path to $_lredir_paths list to allow

Even if $_lredir_paths="/" the same error occurs. I guess parsing the variable was accidentally dropped.

I haven't spotted any relevant change in doc/ that would indicate a PEBKAC problem. If I missed it please enlighten me :-) . I did see the / vs \ lredir change though.

**A regression?**
Yes, bisected to eb1bf967d3671d1783fa68a14e2d380492a85124. Later commits change the behaviour from not permitted to path not found.

**Comment by stsp** [comment]
Lets say, this is not yet implemented
in dosemu2. :) I removed the remnants
of dosemu1's impl, and made
`lredir -n ${HOME}` (which will likely
be the new syntax ) to return the
sensible error for now.

**Comment by andrewbird** [comment]
As a workaround, is it possible to do this?
~~~
system -s HOME
lredir -n %HOME%
~~~

**Comment by stsp** [comment]
That indeed works! :)

**Comment by stsp** [comment]
And I wonder if anything else
is even needed then.

**Comment by stsp** [comment]
Well, perhaps at least `~`
should be supported "natively".
Otherwise its probably a bit confusing.

**Comment by stsp** [comment]
With the rest being done
with your "work-around".
That would probably be the
simplest solution.

**Comment by stefand** [comment]
Yep, @andrewbird's suggestion worked. I had to move my lredirs from fdppconf.sys to one of those dosrc.d bat files, but that feels like a better place for them anyway. I should reduce the number of changes to fdppconf, fdppauto and dosemu.conf files in my setup anyhow.

Once the documentation is updated I consider this bug solved :-)

**Comment by stsp** [comment]
Variables are now allowed.
rc.d stuff is system-wide so is not
supposed to be used that way.
Please use userhook.bat.

**Comment by stsp** [comment]
Andrew, could you please see
why "MFS FCB file read alternate DTA"
now fails? How can it be affected
with the lredir change?

**Comment by andrewbird** [comment]
strange, will look tomorrow.

**Comment by stefand** [comment]
> Variables are now allowed.
> rc.d stuff is system-wide so is not
> supposed to be used that way.
> Please use userhook.bat.

Ya, I have a multi-user install of various games (Wine and DOS) for Lan parties, so I want my own modified defaults to apply system wide.

**Comment by andrewbird** [comment]
> Andrew, could you please see
why "MFS FCB file read alternate DTA"
now fails?

I can't make that fail here locally.

On the GA test the error produced was
~~~
D:\>c:\fcbradta

Open Operation Failed
~~~

But reading the test source, the only way that could occur is if the `open fcb int21/0f` actually failed (returned al != 0)
https://github.com/dosemu2/dosemu2/blob/4d63c0129ca4f42c9adab9388d43321484a274d1/test/test_dos.py#L776-L876

Not sure what to suggest.
