### ISSUE TITLE
Windows 3.1 installation GUI doesn't come up with default mouse driver

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1451]
**Describe the bug**
When you leave the default mouse driver, the GUI doesn't come up:
```
ps2mouse = 2:mouse.drv,   "Microsoft, or IBM PS/2",            x:*vmd
```
![Screenshot_20210411_053743](https://user-images.githubusercontent.com/877112/114291489-14cad900-9a88-11eb-938f-2f194d0b970a.png)

Instead you get thrown to the prompt with the colors of the installer and the text remaining:
![Screenshot_20210411_053843](https://user-images.githubusercontent.com/877112/114291509-35932e80-9a88-11eb-8c82-38b3fe767f10.png)

**To Reproduce**
Probably just switching win31 to `mouse.drv` is enough, otherwise run the installer & leave the defaults.

**Attach program/game binaries or provide an URL**
Let me know if you can't reproduce with your copy :)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/6291150/boot.log)

**A regression?**
Definitely.

**Additional info**
This happens with both FDPP & MS-DOS 6.

**Comment by stsp** [comment]
Should now be fixed.
