### ISSUE TITLE
Windows 3.1 installation on MS-DOS 6.22 results in crash

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1452]
**Describe the bug**
With a work-around for bug #1451 the installation crashes on MS-DOS 6.22. Windows 3.1 could be installed without issues on MS-DOS 6.22 in the past.

**To Reproduce**
Install MS-DOS 6.22.
Install Windows 3.1, switch to `i33mouse.drv` during setup.

**Attach program/game binaries or provide an URL**
https://ia801604.us.archive.org/view_archive.php?archive=/12/items/IBM_PC_Compatibles_TOSEC_2012_04_23/IBM_PC_Compatibles_TOSEC_2012_04_23.zip

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/6291155/boot.log)

**A regression?**
Definitely.

**Additional info**
This does not occur with FDPP. It does occur with MS-DOS 6.22 with `himem.sys` loaded.

**Comment by andrewbird** [comment]
From your log
~~~
ERROR: MFS: failed to set xattrs: Actie wordt niet ondersteund
~~~

What's your underlying Unix filesystem, NFS? Can you try on filesystem that does have xattrs, as it's pretty much required now for Dosemu?

**Comment by stsp** [comment]
Wow!
Should we add the hard terminate?

**Comment by stsp** [comment]
Added a hard terminate.
I wonder if this bug is now "fixed".

**Comment by jschwartzenberg** [comment]
> What's your underlying Unix filesystem, NFS?

No, `tmpfs`. I tend to redirect dosemu (previously through the `dosemu__hdimage` environment variable, now with `--Fdrive_c` to use `/tmp` when testing. I understand this is not supported anymore?

**Comment by stsp** [comment]
Of course it is supported:
https://cateee.net/lkddb/web-lkddb/TMPFS_XATTR.html
Just ask your distro to
enable the support.

**Comment by stsp** [comment]
Please ignore the above comment. :)
Seems this patch:
https://acl-devel.bestbits.narkive.com/pmUWTy8e/user-extended-attributes-for-tmpfs
was never integrated.
So perhaps indeed, this is
an unsupported scenario. :(

**Comment by stuaxo** [comment]
That's a pain does it look like there was a reason or maybe it was just missed ?

**Comment by andrewbird** [comment]
I haven't tried this, but maybe it's possible to overlay the xattrs on tmpfs
https://github.com/fbarriga/fuse_xattrs

**Comment by jharrison03** [comment]
> From your log
> 
> ```
> ERROR: MFS: failed to set xattrs: Actie wordt niet ondersteund
> ```

I see this all the time (ERROR: MFS: failed to set xattrs: Operation not supported) -- presumably this has something to do with the fact I'm working off network drives (Netware) and this call isn't supported.

It doesn't seem to harm anything in my case, though.

**Comment by andrewbird** [comment]
> I see this all the time (ERROR: MFS: failed to set xattrs: Operation not supported) -- presumably this has something to do with the fact I'm working off network drives (Netware) and this call isn't supported.

@jharrison03 It shouldn't appear on any drive other than MFS. Be prepared that the error has just been altered to exit dosemu when it occurs. Now it's going to be necessary to figure out how this occurs on your Netware drives, if you could raise another ticket for this it would help greatly. Please specify what version of Netware client you are using, as they don't all interact with the redirector.

**Comment by stsp** [comment]
I soften that a bit so exit won't
occur on reads at least.
@jschwartzenberg could you please
check that your setup is supported
again?

**Comment by jschwartzenberg** [comment]
Yeah that helps! Setup goes further now, but there's another new error:
![Screenshot_20210412_220105](https://user-images.githubusercontent.com/877112/114454409-deea3980-9bda-11eb-92dc-5a483c85e11c.png)
[boot.log](https://github.com/dosemu2/dosemu2/files/6299498/boot.log)

**Comment by stefand** [comment]
I have a similar issue with xattr - Part of my dos directories are on aufs and some games reside on that. xattr on aufs seems to be complicated. It isn't working on my mount, but I haven't found out yet if this is a generic aufs limitation or a setup problem on my end.

E.g. settlers 2 now refuses to start because the fallback in file_is_ro is to consider a file read only if xattrs are missing. If I hack this out I get the still-remaining hard exit behaviour on attribute write.

**Comment by stefand** [comment]
Ok in the case of AUFS it was a kernel option that was disabled in my build. It supports user_xattr (good enough for dosemu), but not more or less file system specific xattrs.

Still I wonder how wise it is to rely on user_xattr to not crash when creating a file. I think a fallback to user/group write permissions would be a good idea. The reliance on xattr would also break lredir'ing a real dos installation (yes, I am aware it can be used as HD image instead)

**Comment by andrewbird** [comment]
> The reliance on xattr would also break lredir'ing a real dos installation

If I understand you correctly, you're describing a (V)FAT partition mounted by linux that subsequently gets accessed by dosemu via MFS? There is still some code that uses FAT_IOCTL_{G,S}ET_ATTRIBUTES to read/write the real DOS attributes in preference to xattrs on those filesystems. I don't currently have tests for this to say it definitely works, though I did some experiments last year that suggest that at least the SFN support should work correctly.
See this example
https://github.com/dosemu2/dosemu2/blob/4d63c0129ca4f42c9adab9388d43321484a274d1/src/dosext/mfs/mfs.c#L1278-L1296

**Comment by stsp** [comment]
> E.g. settlers 2 now refuses to start because the fallback in file_is_ro is to consider a file read only if xattrs are missing.

I made a fall-back more predictable now.

> The reliance on xattr would also break lredir'ing a real dos installation

It shouldn't, as described above.
But who uses real dos installs these
days, is difficult to say.

> Still I wonder how wise it is to rely on user_xattr

Ask some wine devs whose
xattr code I copy/pasted to dosemu2. :)
Having attrs in a wine-compatible format
should be/is a bonus.

> I think a fallback to user/group write permissions would be a good idea.

Good ideas usually do not work.
You can only map R/O attr more or
less consistently to unix perms, with
the rest being random/unsupported.
This is what dosemu1 tried to do, but
it didn't implement file locking. We took
the OFD locks (another new technology
not always supported by every FS) and
implemented locking, but OFD locks
require write permission to a file. So
you can't map the R/O attr there any
more. We tried to move the R/O attr
to S_IWGRP, but as the group write
is usually disabled on all unix files,
people immediately started to get all
files defaulted to R/O!
So we looked at wine and did what
it does.
I know that dosemu2 has a bad rep
of breaking existing setups and not
working properly even in the most
favourable configurations. And I think
we should concentrate only on the
second part of the problem: maybe
one day we'll work properly at least
in some setups.

**Comment by stsp** [comment]
> people immediately started to get all
> files defaulted to R/O!

Of course we could keep
using S_IWGRP for R/O
but add the S_IWOTH to
the picture and use it as an
indication of whether to trust
S_IWGRP.
That way you could more or less
reliably map 1 DOS attr to unix
perms, in an exchange of making
an insecure setup (fiddling with
S_IWOTH is insecure).
So no, its not like we break things
out of nothing to do. We break
things for a very good reasons. :)

**Comment by jharrison03** [comment]
> > I see this all the time (ERROR: MFS: failed to set xattrs: Operation not supported) -- presumably this has something to do with the fact I'm working off network drives (Netware) and this call isn't supported.
> 
> @jharrison03 It shouldn't appear on any drive other than MFS. Be prepared that the error has just been altered to exit dosemu when it occurs. Now it's going to be necessary to figure out how this occurs on your Netware drives, if you could raise another ticket for this it would help greatly. Please specify what version of Netware client you are using, as they don't all interact with the redirector.

False alarm.  I was re-directing a tmpfs filesystem right before the Netware login in a batch file.  The error was due to the tmpfs, not the network drive.

**Comment by jschwartzenberg** [comment]
With the current Git, it fails even earlier in the installation, when selecting the right video driver. I get this output:
```
ERROR: MFS: failed to get xattrs, unsupported!
ERROR: MFS: failed to get xattrs, unsupported!
ERROR: MFS: failed to set xattrs: Actie wordt niet ondersteund
```

**Comment by jschwartzenberg** [comment]
Installing in my homedir instead (no tmpfs) gives:
![Screenshot_20210606_071444](https://user-images.githubusercontent.com/877112/120913373-fe5f8900-c696-11eb-8f63-d2c0fb7abb22.png)

I have enough space:
```
$ df -h /home/
Filesystem                  Size  Used Avail Use% Mounted on
/dev/mapper/matrix-homevol  707G  162G  510G  25% /home
```

**Comment by stsp** [comment]
Is this specific to fdpp?

**Comment by jschwartzenberg** [comment]
No, this is with MS-DOS 6.22.

**Comment by stsp** [comment]
This should better be bisected.

**Comment by jschwartzenberg** [comment]
7f3d876aef0faa3eba1181cbc296effb87bd7c3a is the first bad commit
```
commit 7f3d876aef0faa3eba1181cbc296effb87bd7c3a
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Jan 23 00:15:05 2021 +0300

    msdoshlp: port all asm helpers to C
    
    ... and consequently move them away from bios.s.

 src/base/bios/x86/bios.s   | 111 --------------------------------------
 src/dosext/dpmi/msdoshlp.c | 129 +++++++++++++++++++++++++++++++++++----------
 src/include/memory.h       |   3 --
 3 files changed, 102 insertions(+), 141 deletions(-)
```

**Comment by stsp** [comment]
While that may sound very weird,
I successfully installed win31 now
with pc-dos7 first, and then with
fdpp.
That's really strange given that when
this ticket was created, it didn't
work so well...

**Comment by stsp** [comment]
Note that the patch 7f3d876 that
you point to, can be cleanly reverted
from current devel.
So with the revert, what problems
do you still see?
As I am obviously seeing none...

**Comment by stsp** [comment]
Sorry, bad testing: I was already
testing with the revert of the patch
you mentioned.
So... it seems the revert of that
patch, causes ALL win31 problems
to disappear!
So thanks for such a great bisect. :)
Can you check that no more problems
do exist after a revert?

**Comment by jschwartzenberg** [comment]
Yep, confirming that simply reverting that commit on latest `devel` solves the problems!

**Comment by stsp** [comment]
Should now be fixed.
As I suppose 1024+ other win31 tickets. :)

**Comment by stsp** [comment]
So I think we are on a very good
track with win31 now. Even Alt-Tab
in dos prompt is now compatible
with comcom32, and seemingly no
problems specific to fdpp.
More than I could ever hope for. :)

**Comment by jschwartzenberg** [comment]
Yep, it's indeed working now.
In some cases I get this though:
![Screenshot_20210607_225916](https://user-images.githubusercontent.com/877112/121086969-1f81c000-c7e4-11eb-9e4e-e2eb5e12f576.png)

Simply starting over again usually does the trick. The error can occur at different moments during the installation process, it's hard to reproduce. I did not see this in the past.

**Comment by stsp** [comment]
So I assume this is still related to
the same patch, right?
I applied the potential fix.
If its not about the patch 7f3d876
then please fill another bug.

**Comment by jschwartzenberg** [comment]
The issue is still there. I'll create another bug.

**Comment by stsp** [comment]
Please check if it is related to the
revert or not first.
