### ISSUE TITLE
Mouse trapping?

### ISSUE THREAD

**Issue by jallennk** [dosemu2/dosemu2#1458]
I've been trying dosemu2 with OrCAD- an old CAD program that uses auto-panning- it means the screen pans when the mouse hits the edge of the screen.  But the mouse does not quite work correctly.  I'm expecting the mouse to be trapped in the window, but it isn't- when I hit the edge it just escapes.  This causes the emulated mouse and X mouse to get out of sync.

Am I missing something? Is there a way to force the mouse to stay trapped in the emulated window?

Thanks!

**Comment by stsp** [comment]
Of course: please use Ctrl-Alt-Home
to grab mouse.
Please use Ctrl-Alt-k to grab kbd.
HTH.
