### ISSUE TITLE
Man page is incorreect

### ISSUE THREAD

**Issue by jallennk** [dosemu2/dosemu2#1460]
**Describe the bug**

The man page says I should do this:

       $ dosemu -dumb dir > listing

But it does not work. I think it should say this:

        $ dosemu -dump -E dir >listing

**To Reproduce**

type "man dosemu" and try to follow the instructions.

I know this is a minor issue, but it's confusing for new users.

**Comment by stsp** [comment]
The correct syntax is
`$ dosemu -dump -exec dir >listing`
as otherwise you would get all
dosemu messages in the listing,
along with the dir output.
