### ISSUE TITLE
"MFS: failed to set xattrs: Operation not supported" on redirected drive on tmpfs

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1467]
**Describe the bug**
"MFS: failed to set xattrs: Operation not supported" on redirected drive

**To Reproduce**
Use lredir.com to install a redirected drive as such on a tmpfs filesystem.

c:\dosemu\lredir.com i: linux\fs/tmp/dosemu/micronv

and then write to the drive

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/6386955/boot.log.zip)

**A regression?**
Yes.

**Comment by stsp** [comment]
This is a known problem.
The patch with user xattrs for tmpfs,
was not applied to linux kernel:
https://acl-devel.bestbits.narkive.com/pmUWTy8e/user-extended-attributes-for-tmpfs
Would you like to fill such a report
to linux kernel?

**Comment by stsp** [comment]
This needs an option to disable
attributes.

**Comment by jharrison03** [comment]
I'll test the kernel patch and will ask LKML for inclusion.

For now, I just bypassed the leavedos() in xattr_err.  Would this cause any problems with the underlying fs?

**Comment by stsp** [comment]
The patch is for 2.6.20 so its
very unlikely that you can test it.

> Would this cause any problems with the underlying fs?

This will disable the DOS file
attributes so some programs
will fail. Note that the exit is
done if the program is trying
to set attributes. So maybe it
actually needs them.

**Comment by stsp** [comment]
Added an option to disable attrs.

**Comment by jharrison03** [comment]
The $_attrs_support=(off) flag in .dosemurc seems to be ignored:

```
ERROR: MFS: failed to set xattrs: Operation not supported
Try to set $_attrs_support=(off)
```

**Comment by stsp** [comment]
I missed the create case, please
try again.

**Comment by stsp** [comment]
Also please see if maybe now you
don't need to disable?

**Comment by grapeli** [comment]
> This is a known problem.
> The patch with user xattrs for tmpfs,
> was not applied to linux kernel:
> https://acl-devel.bestbits.narkive.com/pmUWTy8e/user-extended-attributes-for-tmpfs
> Would you like to fill such a report
> to linux kernel?

It was turned on a long time ago.
[tmpfs: implement generic xattr support](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b09e0fa4b4ea66266058eead43350bd7d55fec67)

```
touch xattr_test && sudo setfattr -n trusted.md5sum -v d41d8cd98f00b204e00998ecf8427e xattr_test
sudo getfattr -d -m - xattr_test
```
https://man7.org/linux/man-pages/man5/tmpfs.5.html
_The tmpfs filesystem supports extended attributes (see xattr(7)), but **user extended attributes are not permitted**._
https://stackoverflow.com/questions/30760177/xattr-extended-attributes-not-settable-for-file-in-tmp-while-in-home-on-same-m
https://man7.org/linux/man-pages/man7/xattr.7.html

**Comment by jharrison03** [comment]
> Also please see if maybe now you
> don't need to disable?

It works now with $_attrs_support = (off).  It doesn't work still if this is disabled.
