### ISSUE TITLE
DOSEMU2 crashes when running DPMI programs

### ISSUE THREAD

**Issue by deadbeatz** [dosemu2/dosemu2#1472]
In a previous install of Dosemu2 on Ubuntu 18.04 via PPA, around August 2020, Dosemu functions as intended with several Dos DPMI programs.

This version is numbered: dosemu2-2.pre8, Revision: 3696

Installing Dosemu via PPA again on Ubuntu 18.04 or 20.04 causes crashing when running the same programs without any error indication.
 
The current version installed: dosemu2-2.pre8, Revision: 6157

The programs that are being run are vintage Dos BBS door games, namely TradeWars 2002. A lot of us BBSers were happy to finally have a Dosemu2 version that successfully ran the game and I am submitting this after spending some time trying to debug what changed.

UPDATE: Non DPMI programs run fine under Rev: 6157. Added required logs and info below.

Thanks in advance for any help.

# Dos Version
Using default Dos that comes with the application.

# File - TradeWars 2002 3.09 (DPMI)
Unzip, then run "install.bat" within Dosemu. On Rev: 3696 it installs no problem. On Rev: 6157, it crashes with the below log output.
[Trade Wars 2002 3.09 DPMI Dos](http://www.digitaldistortionbbs.com/api/files.ssjs?call=download-file&dir=dosbbsdg&file=2002D309.ZIP)
# .dosemurc:
```
$_cpu = "80486"
$_cpu_emu = "vm86"
$_hogthreshold = (10)
$_external_char_set = "utf8"
$_internal_char_set = "cp437"
$_layout = "us"
$_rawkeyboard = (0)
$_joy_device = ""
$_speaker = ""
$_sound = (off)
$_com1 = "virtual"
```
```$_com1="virtual"``` can be commented out and it the issue still persists.

# boot.log:
```
FDPP kernel 1.3 [GIT: ] (compiled May  3 2021)
fdpp: plugin loaded: 1
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: config variable c_user set
CONF: Parsing /home/analog/.dosemu/.dosemurc file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Disabling use of pentium timer
CONF: timer freq=18, update=54925
CONF: CPU set to 486
CONF: CPUEMU set to jit
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x20000)
CONF: DPMI linear reserve base addr = 0xffffffff
CONF: DPMI linear reserve size = 0x8000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
CONF: Keyboard-layout us
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
default_drives 0
Setting up drive C, ~/.dosemu/drive_c
Creating default drive C
Added drive 0 (80): ~/.dosemu/drive_c
default_drives 1
Added drive 1 (81): /usr/share/dosemu/dosemu2-cmds-0.3
Setting up default drives from E
Added drive 2 (82): /usr/share/comcom32
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 disabled.
CONF: config variable c_system unset
Warning: Linux kernel 5.4.0; CPU speed is 4001969000 Hz
Warning: CPU-EMU speed is 4002 MHz
CONF: V86 cpu vm set to -1
CONF: DPMI cpu vm set to -1
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
Warning: DBG_FD already set
Warning: DOSEMU-2.0pre8 is coming up on Linux version 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
Warning: Compiled with gcc version 7.5.0Warning:  64bit
Warning: CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wno-string-plus-int -fplan9-extensions -Wno-maybe-uninitialized -fpie -ggdb3 -g -O2 -fdebug-prefix-map=/build/dosemu2-jcwpwR/dosemu2-2.0~pre8-6322=. -fstack-protector-strong -Wformat -Werror=format-security
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 8Kb at 0xFC000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0246
initial segment bases: fs: 0x7fe559593740  gs: (nil)
ERROR: KVM: error opening /dev/kvm: No such file or directory
Warning: KVM not available: No such file or directory
Warning: using CPU emulation for vm86()
Warning: using CPU emulation for DPMI
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Conventional memory mapped from 0x7fe554001000 to 0x4013f000
DPMI memory mapped to 0x4024f000 (reserve) and to 0x4224f000 (main)
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
VID: Video set to Video_term
ERROR: term: stderr still on tty, closing
Registering HWRAM, type=e base=0x4a845000 size=0x400000
CONF: reserving 4096Kb at 0x4A845000 for 'e' (VGAEMU LFB)
loading fonts for cp437
CONF: reserving 4Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
DPMI: mem init, mpool is 140468224 bytes at 0x4224f000
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============

CONF: freeing region for 'E' (EMS page frame)
booting with comcom32
config.boot_dos set to 400000
config.int_hooks set to 0
config.force_revect set to 0
CONF: reserving 124Kb at 0xC1000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 48Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
ERROR: EMU86: error 96
        tid=261 state=3 name=fdpp thr off=0
coopthreads stopped
======================= LEAVE CPU-EMU ===============
```

**Comment by andrewbird** [comment]
I really think you need to supply the log file, dosemu.conf, version of DOS that you are running and the url/zip of the binary that's causing the crash. The bug report template specifies these are needed else we'd just be guessing what the problem might be.

**Comment by deadbeatz** [comment]
Doing some log comparisons between the two revisions, the Rev 3696 log shows:
```
======================= LEAVE CPU-EMU ===============


Package info:
dosemu2: installed
dosemu2 2.0~pre8-6303-379e92896+202008102359~ubuntu18.04.1
fdpp: installed
fdpp    1.0~rc3-1012-b912843+202007312114~ubuntu18.04.1
analog@d9fbeca6a56e:~/.dosemu$ dosemu --version
dosemu2-2.0pre8
Revision: 3696
```

and the Rev 6157 log show:
```
======================= LEAVE CPU-EMU ===============


Package info:
dosemu2: not-installed
dosemu2
fdpp: installed
fdpp    1.3-1152-488c1ae+202105030117~ubuntu18.04.1
```

The difference being that the latest Rev shows ```dosemu2: not-installed```.

I don't know what that exactly means as I can run Dosemu2 but that might help?

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
> We run dosemu2 under a BBS (yes old school) shell environment and are not using KVM.

Since the instruction that caused the crash was never emulated until now, it's reasonable to assume that you weren't using emulation in the past, else it would have crashed. That means you could have been using either KVM or vm86 (if the machine is 32bit), probably without knowing it as the automatic selection of those is preferred over emulation. There have been changes both to the Linux kernel and Distros that sometimes make emulation the only available choice. Since you are running Dosemu not on local display I suspect that the problem is with permissions on `/dev/kvm`. Normally when using the desktop, the login process will give the logged in user permission via an acl on that device file. Here's mine:
~~~
ajb@polly:~/Desktop$ getfacl /dev/kvm
getfacl: Removing leading '/' from absolute path names
# file: dev/kvm
# owner: root
# group: kvm
user::rw-
user:ajb:rw-
group::rw-
mask::rw-
other::---
~~~
Which means when I start Dosemu I get a kvm based DOS environment. But if another user logged in via serial or ssh etc they'd get emulation. As I mentioned earlier those acls now get created and removed on demand, so probably the easiest thing if your machine has a kvm group defined, is to add your non desktop users to the kvm group.

Hope it helps.

**Comment by deadbeatz** [comment]
> 
> 
> > We run dosemu2 under a BBS (yes old school) shell environment and are not using KVM.
> 
> Since the instruction that caused the crash was never emulated until now, it's reasonable to assume that you weren't using emulation in the past, else it would have crashed. That means you could have been using either KVM or vm86 (if the machine is 32bit), probably without knowing it as the automatic selection of those is preferred over emulation. There have been changes both to the Linux kernel and Distros that sometimes make emulation the only available choice. Since you are running Dosemu not on local display I suspect that the problem is with permissions on `/dev/kvm`. Normally when using the desktop, the login process will give the logged in user permission via an acl on that device file. Here's mine:
> 
> ```
> ajb@polly:~/Desktop$ getfacl /dev/kvm
> getfacl: Removing leading '/' from absolute path names
> # file: dev/kvm
> # owner: root
> # group: kvm
> user::rw-
> user:ajb:rw-
> group::rw-
> mask::rw-
> other::---
> ```
> 
> Which means when I start Dosemu I get a kvm based DOS environment. But if another user logged in via serial or ssh etc they'd get emulation. As I mentioned earlier those acls now get created and removed on demand, so probably the easiest thing if your machine has a kvm group defined, is to add your non desktop users to the kvm group.
> 
> Hope it helps.

This is interesting. I'm actually running this under Docker so theoretically, I was pulling the same 18.04 LTS image before and after the updated version that led to crashing. I do agree that KVM is probably not executing due to permissions and since we're running in Docker, I can adjust perms without too much risk to the host. I'm a little confused how anything has changed as the Ubuntu image I am running in Docker is the same exact image I was running previously. It may be a kernel update like you said.

Thanks for all the help here. Glad this project is seeing life lately. A lot of us underground BBSers are very happy this the DPMI compatibility. 

Cheers!

**Comment by andrewbird** [comment]
> I do agree that KVM is probably not executing due to permissions and since we're running in Docker, I can adjust perms without too much risk to the host.

I'm not familiar with Docker, so I can't say whether I expect KVM to work for guests within it.

> Glad this project is seeing life lately. A lot of us underground BBSers are very happy with the DPMI compatibility.

That's really good to know, have fun!

**Comment by stuaxo** [comment]
You certainly could share /dev/kvm with the host in Docker and it should work, which is probably useful if you don't care about security between the host and guest (I tend to not care - Docker is still pretty useful, with the easy layering and bring up / shutdown it offers).
