### ISSUE TITLE
$_lredir_paths is ignored

### ISSUE THREAD

**Issue by bpranoto** [dosemu2/dosemu2#1473]
**Describe the bug**
$_lredir_paths in /etc/dosemu/dosemu.conf is ignored.

In my autoexec.bat I make a drive redirection:

```
lredir D: LINUX\FS\home\bambang
lredir G: LINUX\FS\home\bambang\dosprogram
lredir H: LINUX\FS\home\bambang\develop\dos

```
I have enabled $_lredir_paths in /etc/dosemu/dosemu.conf

`$_lredir_paths = "/home/bambang"`

dosemu throws error messages:

```
ERROR: redirection of \home\bambang/ rejected
Add the needed path to $_lredir_paths list to allow
ERROR: redirection of \home\bambang\dosprogram/ rejected
Add the needed path to $_lredir_paths list to allow
ERROR: redirection of \home\bambang\develop\dos/ rejected

```

**To Reproduce**
Set $_lredir_paths in /etc/dosemu/dosemu.conf and try lredir in dosemu session

**Attach the log**
Attached with -Dc flag

**A regression?**
YES

**Additional info**
dosemu2-legacy package run on ubuntu 18.04
[boot.log](https://github.com/dosemu2/dosemu2/files/6447188/boot.log)

**Comment by stsp** [comment]
Should now be fixed.
