### ISSUE TITLE
Copy command misses the first letter of file name when lredir is issued with the /

### ISSUE THREAD

**Issue by nnn19** [dosemu2/dosemu2#1474]
**Describe the bug**
The **copy command** misses the first letter of the file name in the copied file on **non home folder**

**To Reproduce**
Create a folder **test** under **/mnt/**
Set the same user:usergroup.
Give all required attributes.
Set **$_lredir_paths** to **"/mnt/test"** under **dosemu.conf**
Under dosemu2
`lredir g: linux\fs/mnt/test`
and copy a file from (may be) c: to g:
`copy abc.txt g:`
This copies the file **abc.txt** into **g:\bc.txt**
missing the first letter of file name.

Same is the case when **/tmp/** is **lredir**ed to **g:**.

But this error does not show up under **lredir**ed drives under **home folder**.

**A regression?**
This bug does not exist in **dosemu**.

**Additional info**
**OS** - Ubuntu 20.04.2 LTS (Focal Fossa)
**dosemu2** - 2.0\~pre8-6865-9b6fe141c+202105031233\~ubuntu20.04.1 
**arch** - amd64

**Comment by stsp** [comment]
What is `FreeDOS Copy command` please?
You mean you installed freecom or what?

**Comment by stsp** [comment]
Please add the `-D9+Dd` log.

**Comment by nnn19** [comment]
I meant copy command under dosemu2.

And it is a surprise that the same bug is **not** reproducable after I ran
**dosemu -D9+Dd**

Attached.
[boot.log](https://github.com/dosemu2/dosemu2/files/6447685/boot.log)

**Comment by stsp** [comment]
Please find out when it stops
reproducing.
Try `-D+D` or `-D+d` and see
if its there or not.
Also this doesn't look like the
`-D9+Dd` log at all.
Also you need to update the
dosemu2 package before
anything else.

**Comment by nnn19** [comment]
**Feedback in full**
The same bug does not show up after the Ubuntu CPU is rebooted for plain **dosemu** command itself.
Tried -D+D and -D+d. Bug does not show up.
Then, I anyway, updated dosemu2.
For sure, until a particular point of time, the bug was consistently showing up.
I am anyway attaching -D9+Dd boot log
[boot.log](https://github.com/dosemu2/dosemu2/files/6447723/boot.log)

Also, will post if the same appears again.

**Comment by nnn19** [comment]
Could reproduce the same issue again (title changed).

On a plain command dosemu
`lredir g: linux\fs/mnt/test/`
produces the same bug.

Hope the trailing / is allowed and could not be considered as n erroneous lredir command.

and the log.
[boot.log](https://github.com/dosemu2/dosemu2/files/6447799/boot.log)

**Comment by nnn19** [comment]
The same is reproduced using
dosemu -D9+Dd

and the log
[Uploading boot.log…]()

**Comment by stsp** [comment]
Should now be fixed.

**Comment by nnn19** [comment]
OS - Ubuntu 20.04 LTS
dosemu2 -  2.0~pre8-6885-72f72c6b2+202105101232~ubuntu20.04.1  -  amd64

The bug is fixed.

Thanks  **Stas Sergeev**.
