### ISSUE TITLE
A Question: Any change in sending printer output to Linux recently?

### ISSUE THREAD

**Issue by nnn19** [dosemu2/dosemu2#1477]
**A Question:**
Is there any change in sending printer output to Linux in the recent times (after Apr. 11th roughly)?

**Explanation:**
A month back the dosemu2 was giving the printer output as a file named **output...** by preserving some of the features of printer vide bold, underline, etc. And the same is not available now.

I reviewed the launchpad.net commits list - and there is nothing pertaining to this. Still I am asking this as I could not reproduce the same (good) feature now.

Thanks in advance.

**Comment by stsp** [comment]
Maybe 3222e9a74?
It moves some prn code around,
but I would suspect its not a problem.
You simply need to configure
$_lptX properly.

**Comment by stsp** [comment]
Is this still a problem?

**Comment by nnn19** [comment]
It is still missing.

Not an error or issue. But as mentioned, around 45-50 days back, when a printer is not connected, the $_lpt1 printer output simply got assembled into output.pdf file under home folder. Especially I could see the **Dot Matrix formatted output** got rendered into output.pdf very nicely with all bold, underline, character width, centering, etc. And this does not exist now.

The $_lpt3 sending pdf files is there (always). But this generates output differently - stops rendering if the output has bold, underline, etc. And if the output is a plain text, we shall have a pdf file with fixed width characters and a blank page if the output has any control codes.

**Comment by stsp** [comment]
> The $_lpt3 sending pdf files is there (always).

Huh.
Default config is:
```
# $_lpt1 = "lpr -l"
# $_lpt2 = "lpr -P PDF"
# $_lpt3 = ""
```

So there is nothing on lpt3.
So you obviously messed up
your config yourself.

> when a printer is not connected, the $_lpt1 printer output simply got assembled into output.pdf file under home folder.

So you had the print to file set
as your system printer somewhere
in the printer config of your system.
Have nothing to do with dosemu.

**Comment by nnn19** [comment]
Yes. My lpt3 configuration - had deviated this thread. 

Anyway, please look into this. This was possible 45-50 days back. A rendered pdf file had bold, underline, centered text etc rendered exactly.  The first line is bold and centered. Next two lines are both left aligned with underline.

![image](https://user-images.githubusercontent.com/42749498/119840035-41489080-bf22-11eb-9bf6-95f99aa150e7.png)

Now if the same output is sent to PDF, it renders a blank page if there are printer control codes for bold, underline, etc.

And even now, the output to PDF works well when the output is plain text.

**Comment by stsp** [comment]
All dosemu is doing, is executing
the commands in $_lptX.
So you can do
`$_lpt1 = "cat >/tmp/output.txt"`
to capture the raw output to
/tmp/output.txt.
Then you can do
`cat /tmp/output.txt | lpr -l`
or
`cat /tmp/output.txt | lpr -P PDF`
or whatever, to experiment with
printing.
dosemu does nothing with that.
Its all about your system setup.

**Comment by nnn19** [comment]
Yes. Yes. I understand that the captured output is forwarded to lpr. Let me do some more trials and come back on this (if there is anything to be done). As I mentioned in the title itself - this is just a question and not an error / issue.
