### ISSUE TITLE
Mouse Pointer Vanishes after exiting program

### ISSUE THREAD

**Issue by nnn19** [dosemu2/dosemu2#1478]
**Describe the bug**
Mouse Pointer Vanishes after exiting program (Foxprox).

**To Reproduce**
Under Dosemu2, the mouse pointer is visible and active usually. When inside the program (foxprox), the mouse pointer is visible / active. And after exiting the program the mouse pointer vanishes (appears in rest of the screen where other Linux programs are running).

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/6460176/boot.log)

**A regression?**
dosemu (old) does not have this issue.
dosemu2 continuously has this issue since I started using the same.

**Comment by stsp** [comment]
What makes this a bug?
If you run foxpro again, the
pointer is again there, right?

**Comment by stsp** [comment]
> When in dosemu2 freshly, the mouse pointer is available.

Because it was considered a bit
more user-friendly than to have it
off from the beginning.
Since I can't imagine how this can
hurt, I'd rather leave it as it is.

**Comment by stsp** [comment]
Note that if the invisible cursor
hurts you too much, you can press
shift, which makes it visible for a
moment. That way you can always
"find" it if you miss it too much.

**Comment by stsp** [comment]
I made this now configurable.
It is still on by default, but you can
do `emumouse c 0` to switch off,
or you can bypass autoexec (that
now does `emumouse c 1`) and
have it off by default.

**Comment by nnn19** [comment]
I am attaching a recorded screen.

https://user-images.githubusercontent.com/42749498/119838385-fe39ed80-bf20-11eb-911c-e2ea2192d64c.mp4

The mouse pointer is visible until I exit the foxpro app. After which the mouse pointer vanishes within the dosemu2 window - but available beyond.

**Comment by stsp** [comment]
You are not following.
I already implemented `emumouse c 1`
for you to re-enable, if you want.
You can also do `emumouse c 0`
after boot, or just skip autoexec, to
get it disabled by default.

**Comment by nnn19** [comment]
The previous feedback is after checking that `emumouse c 1` is set. I had checked that it is on by default. Even with emumouse on, the mouse pointer vanishes.

**Comment by stsp** [comment]
You need `emumouse c 1` AFTER
FOXPRO to regain pointer.
Create foxpro.bat if you want, that
will do that for you.

**Comment by nnn19** [comment]
Oh. I never anticipated an application to change the emulator's settings.

So, the application, somehow, disables it and we need to enable it ourself. 

Ok.

**Comment by stsp** [comment]
They do not change any setting,
they just control the mouse pointer.
`emumouse c 1` does not change
any setting either, it just enables
the host's cursor forcibly.

**Comment by nnn19** [comment]
Oh. Ok. And thanks.
