### ISSUE TITLE
ERROR: SDL: duplicate keypress events

### ISSUE THREAD

**Issue by AlbertHamik** [dosemu2/dosemu2#1483]
**Describe the bug**
Occasionally, for some reason I can't figure out, this crash will occur with the error description in the title of this bug report coming up as the culprit. I think it could be perfectly timed double inputs? I honestly don't know because I'm not doing stuff that would make duplicate keypresses occur, at least not as far as I'm aware?

**Comment by stsp** [comment]
Please don't strip the template.
The reports without a log are no
longer considered.
