### ISSUE TITLE
When building on Ubuntu Focal, libfdpp.so: cannot open shared object file

### ISSUE THREAD

**Issue by andy5995** [dosemu2/dosemu2#1485]
**Describe the bug**
When building on Ubuntu Focal, libfdpp.so: cannot open shared object file

**To Reproduce**
I cloned the repo inside a docker image of Ubuntu Focal and ran `ci_prereq.sh`  and `ci_build.sh`, then `make install`

**Attach the log**
[config.log](https://github.com/dosemu2/dosemu2/files/6572418/config.log)

**Additional info**
```
$ dosemu
ERROR: libfdpp.so: cannot open shared object file: No such file or directory
ERROR: can't load fdpp
ERROR: KVM: error opening /dev/kvm: No such file or directory
ERROR: userspace pings are disabled.
	To enable them, do as root:
	echo 0 65535 > /proc/sys/net/ipv4/ping_group_range
ERROR: term: stderr still on tty, closing
```

After adding the line `/usr/local/lib/dosemu` to /etc/ld.so.conf.d/libc.conf and then running `ldconfig`, and creating a symlink from libplugin_fdpp.so to libfdpp.so in /usr/local/lib/dosemu:

```
$ dosemu
/usr/local/bin/dosemu: symbol lookup error: /usr/local/lib/dosemu/libplugin_fdpp.so: undefined symbol: FdppInit
```

```
$ ldd dosemu.bin 
	linux-vdso.so.1 (0x00007ffc1dee3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4dabf6f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4dabf69000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4dabe1a000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f4dabe00000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4dabdf5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4dabc03000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4dac891000)
```

**Comment by stsp** [comment]
Please add src/plugin/fdpp/config.log

**Comment by andy5995** [comment]
[fdpp_config.log](https://github.com/dosemu2/dosemu2/files/6572476/fdpp_config.log)

**Comment by stsp** [comment]
Please show `ldd ibplugin_fdpp.so`

**Comment by andy5995** [comment]
```
# ldd libplugin_fdpp.so 
	linux-vdso.so.1 (0x00007ffd9f3d1000)
	libfdpp.so => /root/dosemu2.git/localfdpp/lib/fdpp/libfdpp.so (0x00007f6bb3302000)
	libubsan.so.1 => /lib/x86_64-linux-gnu/libubsan.so.1 (0x00007f6bb298b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6bb2799000)
	libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007f6bb277d000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6bb259c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6bb244d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6bb2430000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6bb242a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6bb2407000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6bb3414000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6bb23eb000)
```

**Comment by stsp** [comment]
`ls -l /root/dosemu2.git/localfdpp/lib/fdpp/libfdpp.so`

**Comment by andy5995** [comment]
# ls -l /root/dosemu2.git/localfdpp/lib/fdpp/libfdpp.so
-rwxr-xr-x 1 root root 12753488 May 31 15:20 /root/dosemu2.git/localfdpp/lib/fdpp/libfdpp.so

**Comment by stsp** [comment]
Please run
`strace -f -o ~/strace.log dosemu.bin`
and attach ~/strace.log

**Comment by andy5995** [comment]
[strace.log](https://github.com/dosemu2/dosemu2/files/6572530/strace.log)

I ran that as root, and got a dos prompt.

Could this have something to do with permissions? I've been trying to normally run dosemu as an unprivileged user.

**Comment by stsp** [comment]
So you added the log that doesn't
reproduce the problem?

**Comment by stsp** [comment]
As user do `ls -l /root/dosemu2.git/localfdpp/lib/fdpp/libfdpp.so`

**Comment by stsp** [comment]
Obviously you can't access files under
/root with the user.

**Comment by andy5995** [comment]
Here's the log from when try as an unprivileged user while the symlink I manually created still exists:
[unpriv_strace.log](https://github.com/dosemu2/dosemu2/files/6572545/unpriv_strace.log)

And with the symlink removed:
[strace_no_symlink.log](https://github.com/dosemu2/dosemu2/files/6572547/strace_no_symlink.log)

**Comment by stsp** [comment]
```
243   openat(AT_FDCWD, "/root/dosemu2.git/localfdpp/lib/fdpp/libfdpp.so", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
```

ci_build.sh is just not suitable for
building dosemu2 that can be used
by non-root. Its only for CI.

**Comment by stsp** [comment]
If you want to build dosemu2 yourself,
then you can at least get the pre-packaged fdpp.

**Comment by andy5995** [comment]
Ok, so I installed fdpp via apt-get, ran make distclean, and rebuilt.  It is working now.

Would you like me to make to add the information to the README and submit a PR?

**Comment by stsp** [comment]
You want to write how to build from
sources?
Perhaps our wiki page is a better place
for this, as README probably doesn't
need that kind of info (99% of people
will just install from packages).
Can you edit wiki?

**Comment by andy5995** [comment]
Yes, I've created an initial page with build instructions.

**Comment by stsp** [comment]
We don't have any interesting
material on wiki to refer to in a
README. Some docs are outdated,
some are incorrect, some are
not properly written.
Docs should be maintained just
as well as the code, but so far
no one took that task up.

> First, clone the repo, or download the source from the latest release.

Missing instruction on how to clone
the repo. Reference to completely
outdated (unfortunately) releases
page.

> After the requirements listed in that script are installed, install fdpp.

No instructions how to do this
(you need to activate the PPA repo).
Also you might need to install "comcom32"
and optionally "install-freedos" packages.

> If you'd like to install the program without superuser privileges, use configure --prefix=$HOME/.local

Unneeded, you can run dosemu2
right from the build directory.

> An unofficial docker image containing all the prerequisites is available at andy5995/dosemu2-dev.

That probably doesn't belong to
this wiki page, and can indeed be
README.
Feel free to create the pull request
with adding the docker info to readme,
but:
- It should contain the detailed description
of what is it, how to use and who needs
that.
- Someone from dosemu2 devs will
need to review the recipes in there
(I myself am completely ignorant about
a docker, so maybe someone else can).
- We currently rely on "daily builds" of
our code, so please specify the update
procedure of your docker. Will it be
daily updated with new sources?

**Comment by stsp** [comment]
> (you need to activate the PPA repo).
> Also you might need to install "comcom32"
> and optionally "install-freedos" packages.

Ah, these are probably covered by
yours running of ci_prereq.sh. Oh well,
interesting trick. :)

**Comment by stsp** [comment]
ci_prereq.sh doesn't install "install-freedos"
though, so this can be added.

**Comment by stsp** [comment]
@andrewbird would you think that
suggesting ci_prereq.sh as a generic
way of installing things, is a normal
practice? :)

Also I am not sure why the writing
has "ci_prereq.sh in the root directory" -
I suppose its not a root directory, but
rather it should be run with root
privs (sudo).

**Comment by stsp** [comment]
In fact, no, ci_prereq.sh is not an
adequate answer here. It installs
too many thing that are not needed
for the user: gcc-djgpp, python3-cpuinfo,
gcc-ia16-elf, gcc-multilib etc etc.

Something like this might be needed
instead:
https://askubuntu.com/questions/74478/how-to-install-only-the-dependencies-of-a-package

**Comment by stsp** [comment]
Btw we support `make deb` and `make rpm`
to create packages locally.
Maybe you can integrate also
`make docker` into our build system?

**Comment by andy5995** [comment]
> Btw we support `make deb` and `make rpm`
> to create packages locally.
> Maybe you can integrate also
> `make docker` into our build system?

I started a [discussion](https://github.com/dosemu2/dosemu2/discussions/1489) about that.

> 
> > First, clone the repo, or download the source from the latest release.
> 
> Missing instruction on how to clone
> the repo.

I won't spend time writing docs on how to clone a git repo. :) There's already instructions on the Internet for how to do that. ;)

> > If you'd like to install the program without superuser privileges, use configure --prefix=$HOME/.local
> 
> Unneeded, you can run dosemu2
> right from the build directory.

Oh... maybe the tail end of the configure output needs to be changed then. It says "you must run make install..."

> > An unofficial docker image containing all the prerequisites is available at andy5995/dosemu2-dev.
> 
> That probably doesn't belong to
> this wiki page, and can indeed be
> in the README.
> Feel free to create the pull request
> with adding the docker info to readme,

We'll discuss it more first on the discussion I created, and figure out what exactly the goal is for the image.

> 
>     * Someone from dosemu2 devs will
>       need to review the recipes in there
>       (I myself am completely ignorant about
>       a docker, so maybe someone else can).

The short answer is

* I pulled an ubuntu docker image
* I ran the image with `docker run -it ubuntu:latest`
* I ran `apt-get update && apt-get dist-upgrade`
* I committed the changes to the image and saved them to a new image called `andy5995/dosemu2k-dev`
* I cloned the dosemu2 repo
* I installed the build dependencies the way I mentioned in a previous post on this ticket

> 
>     * We currently rely on "daily builds" of
>       our code, so please specify the update
>       procedure of your docker. Will it be
>       daily updated with new sources?

I don't know how to do that, or if a paid docker hub account would be needed.

**Comment by andy5995** [comment]
> Also I am not sure why the writing
> has "ci_prereq.sh in the root directory" -
> I suppose its not a root directory, but
> rather it should be run with root
> privs (sudo).

Because the file is in the root directory of the repo. I just now edited the wiki to make it more clear.

**Comment by stuaxo** [comment]
It looks like you are building the docker image manually ?
Roughly:

The first step would be to make automate the building / updating of the Dockerfile.

Then each day you have something that grabs the latest version, updates dosemu2 in it and tags the image.

If you have a your Dockerfile in a repo somewhere and the scripts to build it, I can certainly have a look at some point.

**Comment by stsp** [comment]
> I won't spend time writing docs on how to clone a git repo. :)

But its just one command.

> Oh... maybe the tail end of the configure output needs to be changed then. It says "you must run make install..."

No, that's correct for a default prefix.
No one is saying you _should_ run
dosemu2 from a build dir.
But doing so should be preferred to
re-compiling it with the custom prefix,
if the only thing you need, is to quickly
run it w/o root privs. Maybe in some
cases you would want a per-user
install, for which you need a custom
prefix indeed, but I haven't heard
about such a needs. If all you want
is a quick run, just run from a build dir.
