### ISSUE TITLE
ERROR: SDL: duplicate keypress events (W/ LOG)

### ISSUE THREAD

**Issue by AlbertHamik** [dosemu2/dosemu2#1486]
**Describe the bug**
 Occasionally, for some reason I can't figure out, this crash will occur with the error description in the title of this bug report coming up as the culprit. I think it could be perfectly timed double inputs? I honestly don't know because I'm not doing stuff that would make duplicate keypresses occur, at least not as far as I'm aware?

**To Reproduce**
Accidentally do duplicate keypress events?

**Attach program/game binaries or provide an URL**
N/A

**Attach the log**
FDPP kernel 1.3 [GIT: ] (compiled May  1 2021)
fdpp: plugin loaded: 1
ERROR: Neither freecom nor comcom32 installation found.
Use DOSEMU2_EXTRAS_DIR env var to specify location of freedos
or DOSEMU2_COMCOM_DIR env var for alternative location of comcom32
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Enabling use of pentium timer
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to 1
CONF: CPU VM set to 1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x20000)
CONF: DPMI linear reserve base addr = 0xffffffff
CONF: DPMI linear reserve size = 0x8000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
Setting up hdimage /home/user/.dosemu/msdos622.img
Set up as an image
CONF: disk type 'Image' header_size: 0 drive C:
CONF: disk type 'Directory' drive D:
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 disabled.
CONF: config variable c_system unset
Warning: Linux kernel 5.10.36; CPU speed is 4267277000 Hz
Warning: CPU-EMU speed is 4267 MHz
CONF: V86 cpu vm set to 1
CONF: DPMI cpu vm set to 1
CONF: Denying use of pentium timer on SMP machine
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1001 (cached 1001)
CONF: priv operations unavailable
Warning: DBG_FD already set
Warning: DOSEMU-2.0pre8 is coming up on Linux version 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64
Warning: Compiled with gcc version 10.2.0Warning:  64bit
Warning: CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wno-string-plus-int -Wno-address-of-packed-member -fplan9-extensions -Wno-maybe-uninitialized -fpie -O2
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 8Kb at 0xFC000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0246
initial segment bases: fs: 0x7f4867296740  gs: (nil)
VID: initializing SDL plugin
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Warning: Using V86 mode inside KVM
Conventional memory mapped from 0x7f4860144000 to 0x41316000
DPMI memory mapped to 0x41426000 (reserve) and to 0x43426000 (main)
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
VID: initializing video sdl
VID: SDL plugin initialization completed
Registering HWRAM, type=e base=0x4bef9000 size=0x400000
CONF: reserving 4096Kb at 0x4BEF9000 for 'e' (VGAEMU LFB)
loading fonts for cp437
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
Warning: Your fluidsynth is too old
ERROR: Your fluidsynth is too old and soundfonts not found
DPMI: mem init, mpool is 140468224 bytes at 0x43426000
Warning: Using DPMI inside KVM
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
ERROR: hdimage size is not cylinder-aligned (1323 sectors), truncated!
CONF: freeing region for 'E' (EMS page frame)
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
coopthreads stopped

**A regression?**
N/A

**Additional info**
N/A

**Comment by stsp** [comment]
Please add the `-D9+g` log.

**Comment by AlbertHamik** [comment]
Well I can do that, although if I haven't made it clear already, this crash is hard to replicate. It's only happened to me a couple times, so few in fact I never thought to ask about it until last night when I had it happen again for the first time in ages.

**Comment by stsp** [comment]
OK then, no need for -D9+g log.
The needed logging was simply missing.
I added it now.
Please reproduce the problem without
any special options, but on the newer
build.

**Comment by AlbertHamik** [comment]
I'll try, but I can't promise an immediate crash log. Like I said, it's really hard to reproduce. I'm at least glad you aren't making me do the -D9+g thing again, the log files got ridiculously huge from that.

**Comment by stsp** [comment]
I understand its not quick, and
I am quite sure we'll get a good
hint this time.
I predict that it will point to kvm...

**Comment by AlbertHamik** [comment]
If it points to KVM then that will be annoying, because I rely on KVM for my particular situation, that maybe you remember me mentioning in the past. Basically a troublesome late era DOS game that only seems to work correctly with CPU-based VM acceleration that corrects the timing somehow.

**Comment by stsp** [comment]
If your prog uses DPMI, then you may avoid
any performance penalty with this config:
```
$_cpu_vm = "emulated"
$_cpu_vm_dpmi = "native"
```

At least worth a try.

**Comment by AlbertHamik** [comment]
Would that work with `$_rdtsc = (on)`?

**Comment by AlbertHamik** [comment]
Welp, I was doing some casual playing of the game hoping I'd trigger the thing again and well I don't know if this log gives better info but here's my latest crash log:

FDPP kernel 1.3 [GIT: ] (compiled May  1 2021)
fdpp: plugin loaded: 1
ERROR: Neither freecom nor comcom32 installation found.
Use DOSEMU2_EXTRAS_DIR env var to specify location of freedos
or DOSEMU2_COMCOM_DIR env var for alternative location of comcom32
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Enabling use of pentium timer
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to 1
CONF: CPU VM set to 1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x20000)
CONF: DPMI linear reserve base addr = 0xffffffff
CONF: DPMI linear reserve size = 0x8000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
Setting up hdimage /home/user/.dosemu/msdos622.img
Set up as an image
CONF: disk type 'Image' header_size: 0 drive C:
CONF: disk type 'Directory' drive D:
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 disabled.
CONF: config variable c_system unset
Warning: Linux kernel 5.10.36; CPU speed is 4277193000 Hz
Warning: CPU-EMU speed is 4277 MHz
CONF: V86 cpu vm set to 1
CONF: DPMI cpu vm set to 1
CONF: Denying use of pentium timer on SMP machine
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1001 (cached 1001)
CONF: priv operations unavailable
Warning: DBG_FD already set
Warning: DOSEMU-2.0pre8 is coming up on Linux version 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64
Warning: Compiled with gcc version 10.2.0Warning:  64bit
Warning: CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wno-address-of-packed-member -fplan9-extensions -Wno-maybe-uninitialized -fpie -O2
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 8Kb at 0xFC000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0246
initial segment bases: fs: 0x7f479e7fc740  gs: (nil)
VID: initializing SDL plugin
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Warning: Using V86 mode inside KVM
Conventional memory mapped from 0x7f4796ea9000 to 0x40d60000
DPMI memory mapped to 0x40e70000 (reserve) and to 0x42e70000 (main)
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
VID: initializing video sdl
VID: SDL plugin initialization completed
Registering HWRAM, type=e base=0x4b943000 size=0x400000
CONF: reserving 4096Kb at 0x4B943000 for 'e' (VGAEMU LFB)
loading fonts for cp437
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
Warning: Your fluidsynth is too old
ERROR: Your fluidsynth is too old and soundfonts not found
DPMI: mem init, mpool is 140468224 bytes at 0x42e70000
Warning: Using DPMI inside KVM
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
ERROR: hdimage size is not cylinder-aligned (1323 sectors), truncated!
CONF: freeing region for 'E' (EMS page frame)
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
leavedos_main(kvm_run:858|0) called - shutting down
coopthreads stopped

**Comment by AlbertHamik** [comment]
I had been testing again and I had posted a log a bit ago but I realized I made a very silly mistake. I had not actually enabled native DPMI mode, it was still in KVM mode. I did notice something interesting however, while playing with a weird emulated + KVM for DPMI mode, I didn't experience a crash but my log file presented me with the ERROR SDL stuff again, contained inside of the CPU emulation part of the log.

**Comment by AlbertHamik** [comment]
So it does seem to likely be a crash related to KVM, now that I think of it. That's a little annoying, although emulation with native DPMI acceleration works way better than I was expecting. There are some downsides to it however (more CPU intensive, longer loads, etc.) and I am hoping KVM mode can be fixed.

**Comment by stsp** [comment]
OK, so this indeed have pointed
to kvm, but unfortunately the important
pieces of logging were missing again. :(
Please retry the logging with the latest
additions.

**Comment by stsp** [comment]
@andrewbird Have you seen the last
test failure? What can that be?

**Comment by andrewbird** [comment]
That test looks for the systype string in dosemu's boot.log (although I have renamed it for the test), unfortunately the boot.log is empty now.

**Comment by andrewbird** [comment]
I have an idea, and will test it out tomorrow

**Comment by stsp** [comment]
But I already solved that,
or what do you mean?

**Comment by andrewbird** [comment]
Oh did you, I didn't notice until now! No worries then.

**Comment by stsp** [comment]
Your hint about an empty log
was enough, thanks. :)

**Comment by AlbertHamik** [comment]
I haven't tested for crashes again yet but was there nothing to be gleaned from my observation that I wasn't having DOSEMU2 crash when at least the main part of it was not using KVM, even when DPMI was? And it was still showing the SDL ERROR messages in the log.

**Comment by stsp** [comment]
That only means that your
prog is not using KVM.
Unfortunately most logging
was still missing.

**Comment by AlbertHamik** [comment]
It wasn't using DPMI? Weird. Anyways, had a crash again and I wasn't pressing any keys when it occured, though perhaps there was a delay:
```

FDPP kernel 1.3 [GIT: ] (compiled May  1 2021)
fdpp: plugin loaded: 1
ERROR: Neither freecom nor comcom32 installation found.
Use DOSEMU2_EXTRAS_DIR env var to specify location of freedos
or DOSEMU2_COMCOM_DIR env var for alternative location of comcom32
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Enabling use of pentium timer
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to 1
CONF: CPU VM set to 1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x20000)
CONF: DPMI linear reserve base addr = 0xffffffff
CONF: DPMI linear reserve size = 0x8000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
Setting up hdimage /home/user/.dosemu/msdos622.img
Set up as an image
CONF: disk type 'Image' header_size: 0 drive C:
CONF: disk type 'Directory' drive D:
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 disabled.
CONF: config variable c_system unset
Warning: Linux kernel 5.10.36; CPU speed is 4300810000 Hz
Warning: CPU-EMU speed is 4301 MHz
CONF: V86 cpu vm set to 1
CONF: DPMI cpu vm set to 1
CONF: Denying use of pentium timer on SMP machine
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1001 (cached 1001)
CONF: priv operations unavailable
Warning: DOSEMU-2.0pre8 is coming up on Linux version 5.10.36-2-MANJARO #1 SMP PREEMPT Tue May 11 19:38:44 UTC 2021 x86_64
Warning: Compiled with gcc version 10.2.0Warning:  64bit
Warning: CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wno-address-of-packed-member -fplan9-extensions -Wno-maybe-uninitialized -fpie -O2
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 8Kb at 0xFC000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0246
initial segment bases: fs: 0x7f04cd102740  gs: (nil)
VID: initializing SDL plugin
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Warning: Using V86 mode inside KVM
Conventional memory mapped from 0x7f04c57af000 to 0x40716000
DPMI memory mapped to 0x40826000 (reserve) and to 0x42826000 (main)
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
VID: initializing video sdl
VID: SDL plugin initialization completed
Registering HWRAM, type=e base=0x4b24c000 size=0x400000
CONF: reserving 4096Kb at 0x4B24C000 for 'e' (VGAEMU LFB)
loading fonts for cp437
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Warning: Your fluidsynth is too old
ERROR: Your fluidsynth is too old and soundfonts not found
DPMI: mem init, mpool is 140468224 bytes at 0x42826000
Warning: Using DPMI inside KVM
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
ERROR: hdimage size is not cylinder-aligned (1323 sectors), truncated!
CONF: freeing region for 'E' (EMS page frame)
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
ERROR: SDL: duplicate keypress events
KVM: KVM_RUN: Interrupted system call
leavedos_main(kvm_run:858|0) called - shutting down
coopthreads stopped
```

**Comment by AlbertHamik** [comment]
Ah y'know, the error actually does appear in logs that don't end up crashing and I had my default settings with KVM like above. So... I hope that doesn't mean the SDL thing **_isn't_** my problem.

**Comment by stsp** [comment]
> It wasn't using DPMI? Weird.

I have no idea, but as you say the crash
disappears even though DPMI still uses
KVM, then the only conclusion I can make
is that your prog does not use DPMI.

> So... I hope that doesn't mean the SDL thing isn't my problem.

Its irrelevant.

Anyway. the bad news are that the
logging was not good again, but we
are getting closer.
Please make yet another log.

**Comment by AlbertHamik** [comment]
Well it's comedic to say that I did a full playthrough of my game to try and have the crash happen again, but to no avail. Hoping it happens again soon but it really sucks that it's likely not the SDL thing... Probably...

I'm genuinely not sure how it happens. And it is rare for sure.

**Comment by stsp** [comment]
There is a chance that the previous
patch have actually fixed it.
At least I hope so.
