### ISSUE TITLE
ini / config file writer in krnl386 not working right

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#1493]
**Describe the bug**
Multiple Windows programs crash in krnl386.exe 0001:6BD1. I have seen it affect the WfW network setup tool and Solitaire.

**To Reproduce**
1) Delete %WINDIR%\sol.ini
2) Start Solitaire
3) Go to game -> options
4) Change something (e.g. switch to vegas scoring) and press ok.
5) Crash

From now on sol.exe will crash on startup. An empty sol.ini was created.

A workaround for sol.exe is to copy a pre-populated sol.ini to %WINDIR%, e.g. this one written by Wine:
```
[Solitaire]
Options=91
```

**Attach the log**
[boot.txt.gz](https://github.com/dosemu2/dosemu2/files/6643692/boot.txt.gz)

-D+9DM log is attached.

My windows directory is F:\dos\win311. Look for "INT21: open file "F:\DOS\WIN311\SOL.INI"" in the log.

**A regression?**
Yes, but I don't know when it started. I don't change solitaire settings on a routine basis. I played with the network stuff, got a crash and noticed I get a crash at exactly the same address in Solitaire too. I guess somewhen a few months back I successfully changed the scoring from standard to vegas.

**Comment by stefand** [comment]
![Screenshot_20210613_121036](https://user-images.githubusercontent.com/521262/121803430-ced5f100-cc41-11eb-93b5-03c23076d415.png)

**Comment by stsp** [comment]
Not happening for me.
I didn't even had sol.ini before
I changed options. So after it
appeared, the game didn't crash
too.
Please produce -D9+Mg log.
Also perhaps checking if 1d8ca751
commit works (the one before
recent win31 fixes) would be good.

**Comment by stefand** [comment]
I believe it's something about my configuration. I reset my dosemu.conf, now things work ok. I'll try to figure out what causes it.

**Comment by stefand** [comment]
Hmm no, it was fixed in git, by 527aa975. Weird, I thought I had those Win311 fixes in my build.

I'm closing this for now, but I can't rule out that I shot myself in the foot somewhere during my testing
