### ISSUE TITLE
In -dumb mode output is only shown after a linebreak, current input line is not shown

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1498]
**Describe the bug**
I had to recompile dosemu2 on our Debian 10 server. I took the opportunity to pull the latest revision. Now whenever I start in -dumb mode the current input line (in FreeCOM 0.84-pre2) isn't shown. Only after ending the current input with Enter is the content of that line shown. 

**To Reproduce**

git describe of the offending revision says `2.0pre8-3000-g6ece83264`

This is what I have to do to make the problem occur:

```
48963  [2021-06-16 14:55:28 +0200 Jun Wed] git clone https://github.com/dosemu2/dosemu2
48964  [2021-06-16 14:55:36 +0200 Jun Wed] cd dosemu2/
48965  [2021-06-16 14:56:04 +0200 Jun Wed] ./default-configure -d --disable-fdpp
48966  [2021-06-16 14:56:48 +0200 Jun Wed] make
48967  [2021-06-16 14:57:55 +0200 Jun Wed] 2.0-pre8/bin/dosemu -dumb
```

**Attach the log**
https://pushbx.org/ecm/test/20210616.log

**A regression?**
Revisions `2.0pre8-2880-g65853ec95` and `2.0pre8-1234-g0984731c9` are both fine.

**Additional info**
Using a 2042 FreeDOS kernel and FreeCOM.

**Comment by stsp** [comment]
Not a problem with comcom32?

**Comment by ecm-pushbx** [comment]
Just compiled comcom32 `Source Control Revision ID: alpha-2-37-g91f699a` and it behaves the same way as FreeCOM.

**Comment by stsp** [comment]
OK, I can reproduce.
Will fix later today.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by ecm-pushbx** [comment]
Appears to work as expected now. Thanks!
