### ISSUE TITLE
Harddisk image doesn't seem to enforce the `:ro` attribute

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1501]
**Describe the bug**
Writes are allowed even though hard disk image has the `:ro` attribute

**To Reproduce**
1/ Create a fat image
2/ Attach it to dosemu using `$_hdimage = "dXXXXs/c:hdtype1 fat12.img:ro +1"`
3/ Start dosemu
4/
~~~
C:\>d:
D:\>dir
 Volume has no label
 Directory of d:\
 
2021-06-20 16:33            17 FOO.DAT
         1 file(s)             17 bytes
         0 dir(s)           10364 KB free
D:\>echo hello > bob.txt
D:\>dir
 Volume has no label
 Directory of d:\
 
2021-06-20 16:33            17 FOO.DAT
2021-06-20 17:17             8 BOB.TXT
         2 file(s)             25 bytes
         0 dir(s)           10360 KB free   
~~~

**A regression?**
Not sure

**Comment by stsp** [comment]
Have you tried `readonly` not `ro`?

**Comment by andrewbird** [comment]
Yes, that fails to start as it's looking for a file called fat12.img:readonly
`CONF aborted with: hdimage /tmp/test-imagedir/fat12.img:readonly not found`

**Comment by stsp** [comment]
Should now be fixed.

**Comment by andrewbird** [comment]
Now that the readonly flag is passed in properly, I see that it does prevent writing. However the failure status is being lost somehow as the djgpp program thinks the write succeeded. Here's the transcript.

~~~
C:\>testit
 
C:\>d:
D:\>rem Internal share
D:\>c:\fileaccs WRITE
Info: File Open success
Info: File Write success(num=17)
Error: File not closed

D:\>rem end
~~~

The test source/exe is here [t1.zip](https://github.com/dosemu2/dosemu2/files/6686483/t1.zip)

I can't see where things are going wrong. In disks.c the CF is set along with DOS error in AH, and my reading of the DJGPP source for `_dos_write()` indicates it should return non zero if the CF is set. However I see return zero and 17 bytes written.

http://www.delorie.com/djgpp/doc/libc/libc_185.html

I also note that the behaviour is the same on MS-DOS 6.22, so I doubt it's a FDPP thing.

**Comment by stsp** [comment]
Try writing with comcom32 - djgpp
app.

**Comment by andrewbird** [comment]
So just using shell redirection in comcom32, no file is created (good), but no error is reported(is that unexpected?) and the echo somehow goes to stdout instead.
~~~
C:\>d:
D:\>dir
 Volume has no label
 Directory of d:\
 
2021-06-21 12:34             8 FOO.DAT
         1 file(s)              8 bytes
         0 dir(s)           10364 KB free
D:\>echo hello > bob.txt
hello
D:\>dir
 Volume has no label
 Directory of d:\
 
2021-06-21 12:34             8 FOO.DAT
         1 file(s)              8 bytes
         0 dir(s)           10364 KB free
D:\>
~~~

**Comment by andrewbird** [comment]
Here's the djgpp source for `_dos_write()`
https://www.delorie.com/bin/cvsweb.cgi/djgpp/src/libc/dos/compat/d_write.c?rev=1.6

**Comment by stsp** [comment]
Its not a problem with write,
but rather with handle.
_dos_open() returns you handle 5,
but _dos_write() uses handle 1.
Please add a few prints to see how
can that be.

**Comment by andrewbird** [comment]
I sprinkled a few printfs, but handle is always 5 for me
~~~
C:\>testit
 
C:\>d:
D:\>rem Internal share
D:\>c:\fileaccs WRITE
Info: File Open success
File handle = 5
File handle = 5
Info: File Write success(num=17)
File handle = 5
File handle = 5
File handle = 5
Error: File not closed
 
D:\>rem end
~~~

**Comment by andrewbird** [comment]
Or did you mean printfs in dosemu, rather than the test case?

**Comment by stsp** [comment]
In test-case.
But I already added them myself
and the handle is right, but dosemu
sees 1. Something is corrupted.

**Comment by andrewbird** [comment]
The handle swap might explain why the shell redirection output to file(5?) ends up being shown on stdout(1)
~~~
D:\>echo hello > bob.txt
hello
~~~

I notice that Dosemu is writing last status to DOS memory
`src/include/bios.h:#define BIOS_HDISK_STATUS               0x474`
I wonder exactly where the storage for that is?

**Comment by andrewbird** [comment]
As a test I swapped to use FreeCOM, which didn't help the djgpp compiled testcase, but the shell redirection test looked better.
~~~
C:\>d:
D:\>echo gello > bob.txt
Error writing to drive D: DOS area: drive not ready
(A)bort, (I)gnore, (R)etry, (F)ail?
Can not redirect output to file 'bob.txt'.
~~~

I wonder if I need to setup an int24 handler in djgpp somehow?

**Comment by stsp** [comment]
Probably not, as I see the wrong
handle at the beginning of a write
call, not at the end.
Should be too early for int24 I think.

**Comment by andrewbird** [comment]
> I see the wrong
handle at the beginning of a write
call

Is that the very first write call, as I see multiple attempts to write the same data? That might be retrying because on harddisks dosemu returns 'Write fault' not 'Write protected'.

**Comment by andrewbird** [comment]
I rewrote the test to compile with ia16-elf-gcc and ran under FreeCom, so eliminating the DPMI for now. As you can see the write still succeeds when it shouldn't, then for some reason the int24 handler gets called. The same thing occurs under
MS-DOS 6.22 (with and without share loaded).

~~~
C:\>testit
C:\>d:
D:\>rem Internal share
D:\>c:\fileaccs WRITE
Info: File Open success
Info: File Write success(num=17)
Error writing to drive D: DOS area: drive not ready
(A)bort, (I)gnore, (R)etry, (F)ail?               
~~~

**Comment by stsp** [comment]
Ah, so handle was a red herring.
It writes to handle 1 (stdout) to
display some messages.

**Comment by stsp** [comment]
So error 24 happens on close and
write succeeds because of a caching.
Mystery solved.

**Comment by andrewbird** [comment]
> write succeeds because of a caching.

What caching? Dosemu never writes the data to disk, supposedly the error DERR_WRITEFLT is returned with CF set before that write and I think DOS should act upon that. I can't see how `_dos_write()` should ever succeed when the data has not even attempted to be written to disk. It feels like some synchronisation issue with CF flag.

**Comment by stsp** [comment]
> What caching?

`BUFFERS=` in config.sys.

**Comment by stsp** [comment]
If you are unhappy with error on close,
use fflush or alike.
But there is no way to get the failure on
write. DOS doesnt accept BUFFERS=0
so caching cant be disabled.

**Comment by andrewbird** [comment]
I guess I'm just not seeing the benefit of being able to open a file on a readonly disk with RDWR. Yes I'll try `_dos_commit()` and ignore the status from write.

**Comment by stsp** [comment]
It seems there is no provision of a
read-only status. The only way to know
if the media is read-only, is to try the write.
I can see that mscdex adds an ioctl to
get the status in advance, but for hdd
there seem to be no such extension.
Likely because int13 doesnt have one too.

**Comment by andrewbird** [comment]
Here's what I have now with MS-DOS 6.22

~~~
D:\>c:\fileaccs WRITE
Info: File Open success
Info: About to write
Info: About to commit
 
Write fault error writing drive D
Abort, Retry, Ignore, Fail?f
 
Write fault error writing drive D
Abort, Retry, Fail?f
Info: File Commit failed(ret = 0x06)
Info: About to close (in error path)
 
Write fault error writing drive D
Abort, Retry, Fail?f
 
D:\>rem end
~~~

So it seems to me that I need to
- remove the close() in the error path, it will always fail
- write an int24 handler to provide the `f` non interactively

**Comment by stsp** [comment]
No you should not remove close.
close is one of (only one?) those weird
syscalls whose error doesnt mean the
action didnt happen. It only tells you via
an error that the data wasnt written, but
surprisingly, the file descriptor would be
removed nevertheless.
So when you are told by someone smart
to never ignore the close() return value,
dont hesitate to ask him what does that
value mean and how it can be used. :)

**Comment by stsp** [comment]
In fact, it seems posix made a
desperate attempt to fix close()
by adopting this change just a
year ago:
https://www.austingroupbugs.net/view.php?id=529
Their wording is so vague that
I'd better write a summary here,
than to ask someone to read that
all.
So they add a new syscall:
`int posix_close(int fildes, int flag);`
They also add a define, `POSIX_CLOSE_RESTART`.
If this is defined (!!!) then close(2)
will not close an fd when EINTR is
returned. You can't however use that
fd any more for anything other than
close(2) again (!!!).
Now this `POSIX_CLOSE_RESTART`
can also be passed as the only possible
flag to posix_close(), in which case
posix_close() will also give you that
"semi-closed" fd on EINTR, and if the
flag is 0 then "fully-closed".

Now it became rather obvious that
the scope of this "fix" was EINTR, not
EIO! While it is actually EIO that means
that write failed, and _that_ had to be
dealt with.
No wonder no one is implementing this
silly posix_close().
How could the one add a new syscall
out of nothing to do? Amazing piece of
crap. :)

**Comment by skitt** [comment]
Given that DOSEMU targets Linux, the relevant information is [the Linux `close` manpage](https://man7.org/linux/man-pages/man2/close.2.html), which is (unsurprisingly) much more specific and explicit than POSIX.

`posix_close` isn’t part of any published POSIX standard yet, it will be included in P1003.1-202x which is currently in draft, and will probably be published in 2022.

**Comment by andrewbird** [comment]
> remove the close() in the error path, it will always fail

I hope I didn't send people off down a rabbit hole here. I should have written `_dos_close()` as I'm not using Posix I/O in this test. This is a slim wrapper around the DOS function int21/3e close call.

**Comment by stsp** [comment]
> which is (unsurprisingly) much more specific and explicit than POSIX.

Yes, though it uses a separate chapter,
`Dealing with error returns from close()`
instead of saying in the `RETURN VALUE`
paragraph that the fd is closed, no matter
what the return value is. This is because
such behaviour is rather broken, so a
separate chapter looks like a better option.
And when you introduce the new syscall,
like `posix_close()`, you are not bound by
the compatibility obligations too much. So
at least they could fix that problem there,
but did not.
Essentially an error from a syscall should
mean that no observable side effects were
made.

**Comment by stsp** [comment]
> I should have written _dos_close() as I'm not using Posix I/O in this test.

Yes, I know. But the only difference I
know about, is that _dos_close() also
calls an error handler. Which is much
better than to not - it could return success
though, to indicate that fd is closed.
Error handler is quite enough to detect
the write error - whoever needs better
detection, uses fsync().

**Comment by skitt** [comment]
> Essentially an error from a syscall should
> mean that no observable side effects were
> made.

Not in a non-transactional system — for example, how would you deal with `write` and `ENOSPC`?

**Comment by stsp** [comment]
> Not in a non-transactional system — for example, how would you deal with write and ENOSPC?

Perfectly fine.
write() is allowed to return smaller
values than requested:
```
Note  that  a  successful  write() may transfer fewer than count bytes.
Such partial writes can occur for various reasons; for example, because
there was insufficient space on the disk device to write all of the re-
quested bytes
```

ENOSPC means that exactly 0 bytes
were writte, which mean "no observable
side effect".
So its already dealt with.
I really believe that only close() is
still offending, and making the same
thing for posix_close() is not funny.

**Comment by skitt** [comment]
> > Not in a non-transactional system — for example, how would you deal with write and ENOSPC?
> 
> Perfectly fine.

Oh yes, duh, silly me!

**Comment by andrewbird** [comment]
So now I have the test working on FAT with int24 handler etc, I'm moving on to MFS. I see some differences
- Open of file on R/O device with mode RDWR fails with INVALID_FUNCTION
- If I tweak that so it continues, then I see that unlike the FAT the first write fails with ACCESS_DENIED rather than doing int24 on a following commit.
~~~
D:\>c:\fileaccs WRITE
Info: File Open success
Info: About to write
Info: File Write failed(ret = 0x05)
 
D:\>rem end
~~~

Test branch is here https://github.com/andrewbird/dosemu2/tree/ci-53

tweak patch for open
```diff
diff --git a/src/dosext/mfs/mfs.c b/src/dosext/mfs/mfs.c
index ff985a164..94271e6d4 100644
--- a/src/dosext/mfs/mfs.c
+++ b/src/dosext/mfs/mfs.c
@@ -4408,7 +4408,7 @@ static int dos_fs_redirect(struct vm86_regs *state, char *stk)
 
       Debug0((dbg_fd, "Open existing file %s\n", filename1));
 
-      if (read_only(drives[drive]) && (dos_mode & 3) != READ_ACC) {
+      if (read_only(drives[drive]) && (dos_mode & 3) == WRITE_ACC) {
         SETWORD(&state->eax, ACCESS_DENIED);
         return FALSE;
       }
@@ -4898,7 +4898,7 @@ do_create_truncate:
         do_update_sft(f, fname, fext, sft, drive, 0, FCBcall, 1);
         return TRUE;
       }
-      if (read_only(drives[drive]) && dos_mode != READ_ACC) {
+      if (read_only(drives[drive]) && dos_mode == WRITE_ACC) {
         SETWORD(&state->eax, ACCESS_DENIED);
         return FALSE;
       }
```

**Comment by stsp** [comment]
Yes, except that open_existing
already have such check at line
4450, so the one you change, can
as well be removed.

**Comment by andrewbird** [comment]
I'm away from the computer at the moment so can't check but remember that this switch has those horrid inter case jumps.
