### ISSUE TITLE
bootp doesn't work

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1504]
libslirp 4.6.0 has broken dhcp and
4.6.1 has broken bootp.
I filled the bug report here:
https://gitlab.freedesktop.org/slirp/libslirp/-/issues/51
Once fixed, we will need to
exclude the broken versions perhaps.

**Comment by stsp** [comment]
@mateuszviste are there any sources
for the old wattcp that only supports bootp?
It seems the libslirp guys claim its not
rfc-compliant (see the URL above).
The sources could help to find out why
wattcp insists on a minimal bootp reply
size larger than what they expect.

**Comment by mateuszviste** [comment]
Originally wattcp was hosted on the author's website at http://www.erickengelke.com/wattcp/ but this site is defunct nowadays.
The only archival version of WatTCP I know about is the one hosted on ibiblio, here: https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/net/wattcp/

The BOOTP code is in src/pcbootp.c

**Comment by stsp** [comment]
OK, thanks.
They have a simple typo in the
code, see the above ticket.

**Comment by stsp** [comment]
OK so wattcp had a bug, and unfortunately
that resulted slirp devs to revert their (correct)
patch, rather than to give me some work-around.
So I guess not much remained on a dosemu2
side to do.
