### ISSUE TITLE
xattrs crash on read-only file when DOS attributes should be changed

### ISSUE THREAD

**Issue by 1ras** [dosemu2/dosemu2#1508]
**Describe the bug**
If a file was marked as read-only with older Dosemu2, it was marked read-only on the Linux file system. Now Dosemu2 uses extended attributes to map all DOS attributes, including read-only. Mapping archive, hidden and system as extended attributes is a very nice idea as they have no direct reflection on the Linux file systems, but I am not convinced about read-only.

Currently, if a file is read-only on the Linux file system (because e.g. older Dosemu2 marked it as read-only), the current Dosemu2 devel does not detect this and crashes if the file should be modified.

**To Reproduce**
Linux:
```
$ echo foo > test.txt
$ chmod -w test.txt
$ ls -l test.txt
-r--r--r-- 1 andi andi 4 Jul  4 18:03 test.txt
```

Dosemu2:
```
c:\>attrib c:\test.txt
_____  c:\test.txt
c:\>attrib +a c:\test.txt
```

ERROR: MFS: failed to set xattrs: Permission denied
Try to set $_attrs_support=(off)
leavedos(xattr_err:1268|0) called - shutting down

**A regression?**
yes

**Additional info**
Filesystem is ext4, 4DOS 8.00 attrib or DR-DOS 7.03 attrib is used.

Disabling attributes completely is not the solution as the file system supports extended attributes. There should be a mapping between file system read-only and Dosemu2 read-only, as one can always have a read-only file on a file system and this should not crash Dosemu2.

**Comment by stsp** [comment]
Should now be fixed, please test.

**Comment by 1ras** [comment]
Yes, the above test case works now, thanks!

Interestingly a read-only media (CD-ROM) works as well by denying access at DOS level.

But on a writable media if the file is owned by a different user, then its still crashing. Is it possible to deny access at DOS level in such a case as well? Don't get me wrong, this is not such a common and therefore important case, but I think anything else would be better than a crash.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by 1ras** [comment]
That's solved as well, thanks!
