### ISSUE TITLE
Picture stuttering when using TTF fonts

### ISSUE THREAD

**Issue by 1ras** [dosemu2/dosemu2#1509]
**Describe the bug**
It looks like $_SDL_hwrend is now on by default but dosemu.conf still says it's off by default.

**Additional info**
I needed to disable it with my older Intel graphics and just found out by accident that it's actually now on by default.

dosemu.conf should be updated.

**Comment by andrewbird** [comment]
What makes you believe that it's on? I just ran with debug `-D+8c`, then the log file had the following within.

~~~
SDL_hwrend 0                                                                    
SDL_fonts "Flexi IBM VGA False, Flexi IBM VGA True"                             
vesamode_list (nil)                                                             
~~~

**Comment by 1ras** [comment]
Ohoh, it seems issue is with $_SDL_fonts, not with $_SDL_hwrend, never change two settings at a time :-( Sorry for that.

With the default setup, Dosemu2 devel sleeps every maybe 300ms for maybe 100ms. This interruptions can be e.g. seen when pressing and holding a key on the DOS command prompt, because it's printed irregularly. I was assuming its related to hardware rendering, but unfortunately I also disabled $_SDL_fonts (set it to an empty string) at about the same time due to graphical glitches witch DR-DOS edit and dosbook.

With `-D+v` there is at regular intervals a `SDL_draw_string` message which might match the interval of the issue, but that's just a best guess. How can I better debug this?

My [last checkout](https://github.com/dosemu2/dosemu2/tree/98853f286c11343cd3b05509e7bcf8edbd8535e6) that I used had already TTF fonts but was not affected.

**Comment by stsp** [comment]
Please rename the ticket name properly
and make sure the problem doesn't happen
with `dosemu -X`.

**Comment by 1ras** [comment]
Okay second try ;-) The x key is held down on all three videos.

This is `dosemu -S` with TTF fonts enabled (`$_SDL_fonts` at default settings):

https://user-images.githubusercontent.com/45467075/124398511-59c47b80-dd16-11eb-82fd-18b6f04555ea.mp4


This is `dosemu -S` with `$_SDL_fonts = ""`:

https://user-images.githubusercontent.com/45467075/124398582-ae67f680-dd16-11eb-895e-d9f78a532902.mp4


This is `dosemu -X`:

https://user-images.githubusercontent.com/45467075/124398593-c2135d00-dd16-11eb-8ca2-9d3880a1f790.mp4

**Comment by stsp** [comment]
Should now be fixed.

@stefand could you please bench
this up? I think its going to be faster
now.

**Comment by 1ras** [comment]
This is solved, thanks!

BTW for TTF fonts, do you have plans to add support for redefined fonts (for DOS applications that use their own fonts or "misuse" fonts to display the mouse cursor)?

**Comment by stsp** [comment]
Use `$_force_vga_fonts = (on)`

**Comment by stuaxo** [comment]
@1ras I wonder if some future version could have TTF versions for some of the well known apps that redefine fonts, like the Norton apps and scandisk etc ?

**Comment by 1ras** [comment]
@stsp I see, that's how you properly disable TTF fonts (not with setting $_SDL_fonts to an empty string, as I did). Doing this at application level (I saw you opened a new issue for it) would be a nice thing.

@stuaxo Yes, some support would be nice. E.g. the so called _"NewUI"_ on DRDOS can be disabled to _"do not redefine font"_, but the mouse cursor is still a redefined font ;-)
