### ISSUE TITLE
Novell-DOS cannot load its buffers into HMA due to memory consumption of first buffer

### ISSUE THREAD

**Issue by 1ras** [dosemu2/dosemu2#1511]
**Describe the bug**
I am currently testing my favorite DOS environments and found out that Novell DOS 7 cannot load its buffers into HMA due to memory consumption of the first buffer. The dconfig.sys as shipped with Dosemu2 should load 10 buffers each needs 532 bytes. But for some reason there is only 1 buffer loaded and it consumes 53012 bytes which fit of course not into HMA.

**To Reproduce**
Novell-Dos 7.0 update 15/2 (German) with unmodified src/bindist/dconfig.sys and src/bindist/dautoemu.bat and Dosemu2 devel:

![pasted_image](https://user-images.githubusercontent.com/45467075/125197533-70ab2680-e25e-11eb-9d51-e83be64775bb.png)

**A regression?**
I think Dosemu2 master was not affected, but if you need to know then I need to double-check.

**Comment by 1ras** [comment]
DR-DOS 7.03 is not affected.

**Comment by stsp** [comment]
So will it help if we write BUFFERS=0?

**Comment by 1ras** [comment]
Same with BUFFERS=0 and BUFFERS=1. I think that's a bug within Dosemu. For some reason Novell-DOS 7 allocates way more memory for the buffers as it is supposed to do. I am relatively sure this was not the case with older Dosemu versions but I need to double-check.

**Comment by stsp** [comment]
And if you just remove BUFFERS=?
Yes, please check if a regression.

**Comment by 1ras** [comment]
Same with BUFFERS removed and DOSBOOK (the Novell-DOS documentation) says that BUFFERS can be between 3 and 99 and default is 15, so I guess that explains it.

**Comment by stsp** [comment]
So BUFFERS=3?

**Comment by 1ras** [comment]
No, I mean that explains it why BUFFERS=0, BUFFERS=1 and removing BUFFERS makes no difference. Because default is 15 and minimum is 3.

The issue is the same with BUFFERS=3

**Comment by stsp** [comment]
So nothing at all makes any difference?
Can you try some other emulator, like
qemu or dosbox, to compare?

**Comment by 1ras** [comment]
A native installation on a 486 is not affected, just in case you want to rule out a general bug within Novell-DOS itself. I am currently checking to see if it's a regression within Dosemu.

**Comment by 1ras** [comment]
I tested my old builds and:

Not affected: https://github.com/dosemu2/dosemu2/tree/master (with dconfig sys from current devel):

![pasted_image001](https://user-images.githubusercontent.com/45467075/125203068-15d1f900-e277-11eb-9582-2c716ae49886.png)


Affected: https://github.com/dosemu2/dosemu2/tree/0904a5e7b92bf3a1bf607d4b0f2d9a223fd57d1e

Okay, that's still a period of two years and I probably need to narrow it down a bit more. Any specific commits you want me to test?

**Comment by stsp** [comment]
Would be cool if you run git bisect on that.
But don't forget to disable fdpp or you
won't be able to bisect.

**Comment by 1ras** [comment]
I did a git bisect and the issue is with line 1442-1447 of https://github.com/dosemu2/dosemu2/commit/6113a859cb1599e3792b70463dad0fe7dc1c48dc
For testing purpose I removed this part on current devel and BUFFERS are loaded correctly.

I then did a few more tests with the problematic part and the issue only happens when there are 3 or more hard drives and no floppy drive available during boot:

• Drive C and D available during boot: Everything works as expected.
• Drive C, D and E available during boot: Issue happens.
• Drive A, C, D and E available during boot: Everything works as expected.

**Comment by stsp** [comment]
Could you please figure out
what exactly int13 request does
it make for a floppy?
Maybe not all requests should
be aborted with that code.

**Comment by 1ras** [comment]
I changed the "no such fdisk" message to also print the registers:

`d_printf("INT13: no such fdisk %x ax=%04x cx=%04x dx=%04x\n", disk, LWORD(eax), LWORD(ecx), LWORD(edx));`

And then started Dosemu with `dosemu -D+d`. And here is what I get:

```
INT13: no such fdisk 0 ax=0000 cx=0000 dx=0000
INT13: no such fdisk 0 ax=1502 cx=0002 dx=0000
INT13: no such fdisk 0 ax=0802 cx=0002 dx=0000
INT13: no such fdisk 0 ax=1500 cx=0001 dx=0000
INT13: no such fdisk 0 ax=0800 cx=0001 dx=0000
```

Is this what you are looking for?

**Comment by stsp** [comment]
Yes, thanks, I applied untested patch.
Please check if it fixes the problem.

**Comment by 1ras** [comment]
Cool, this is fixing the issue, thanks!
