### ISSUE TITLE
No UMB available with supplied default configuration for DR/Novell/Open DOS

### ISSUE THREAD

**Issue by 1ras** [dosemu2/dosemu2#1512]
**Describe the bug**
Dosemu2 supplies a dconfig.sys example at src/bindist/dconfig.sys for DR/Novell/Open DOS which uses DOS=UMB,HIGH followed by UMB.SYS. In this order there is however no UMB available for DOS within Dosemu. To get UMB available for DOS, the order need to be changed, first UMB.SYS need to be loaded, then DOS=UMB,HIGH can follow.

**To Reproduce**
DR-DOS 7.03 with unmodified src/bindist/dconfig.sys:

![pasted_image001](https://user-images.githubusercontent.com/45467075/125200248-845c8a00-e26a-11eb-98f1-0e442ddb280f.png)

DOS=UMB,HIGH **after** UMB.SYS:

![pasted_image002](https://user-images.githubusercontent.com/45467075/125200254-8e7e8880-e26a-11eb-953b-f34ed70617d0.png)

**A regression?**
DR-DOS/Novell-DOS own EMM386.EXE is not affected and the order on a native Installation doesn't matter.
With Dosemu this behavior exists for a long time and even affected Dosemu 1.4.

**Additional info**
On DR-DOS/Novell-DOS the config.sys entries are executed in the supplied order and are not reordered like with MS-DOS. It's entirely possible that EMM386.EXE takes special care for this case and that's why it works with a native installation.

For the supplied examples shipped with Dosemu, DOS=UMB,HIGH should come after UMB.SYS, but before all DEVICEHIGH entries.

**Comment by stsp** [comment]
Would you like to test and supply
the patch as a PR?

**Comment by 1ras** [comment]
I don't know if it's related, but UMB.SYS sets the error level when executed successfully. I checked with:
```
device=d:\dosemu\umb.sys
onerror => 1 ? "An error occurred, press any key to continue." :
```
And the ONERROR command of DR-DOS is triggered. 

Do you maybe know how this can be prevented so that UMB.SYS returns 0 on success?

**Comment by stsp** [comment]
No idea but there are not too many
ways of returning an error status.
See umb.s:99 - one of the places.
Try replacing `orw` with `movw` to
make sure the error code is always 0.
Another possibility is CF flag.
Try adding `clc` after line 104 that
does `popa`.

**Comment by andrewbird** [comment]
From memory this probably should be `movb` not `movw`
https://github.com/dosemu2/dosemu2/blob/105d88c5fdd4c40918f83467ee10bd7e505598ab/src/plugin/dosdrv/umb.s#L168

**Comment by stsp** [comment]
Yes, good catch.
But will likely not fix anything real.

**Comment by 1ras** [comment]
Replacing `orw` on  umb.s:99 with `movw` fixed the issue with the wrong return code.

But even then the reported issue persist. As a next step I tested JEMMEX with a native DR-DOS installation and found out that it has the same limitation. So I think DR-DOS own EMM386 does something special to support this kind of setup.

My conclusion is that for DOS=UMB,HIGH to work with third-party memory managers, it need to be after the memory manager. And for the DEVICEHIGH rules to work, it has to come before the DEVICEHIGH rules. That limits it to a very small area.

**Comment by stsp** [comment]
Please provide the screen-shot with
this error code problem.
Please provide the patch/PR for DOS=
problem, if you want.

**Comment by andrewbird** [comment]
This is odd, the only place I can see that ax could be != 0 is if the call index is bigger than the jump table. Other errors generated by the Init() should cause an error message to be printed and DOS should fail to install the driver.

https://github.com/dosemu2/dosemu2/blob/f391de607bcf200cc7557aef50dea15d7517100a/src/plugin/dosdrv/umb.s#L99

**Comment by stsp** [comment]
Which is why I asked for a screen shot.

**Comment by andrewbird** [comment]
I'm not familiar with drdos onerror , does it display error message at any time for a loaded driver / tsr or only for the command currently executing? If it's any time, I wonder if the error is being posted after the init call for a different function that drdos expects the driver to support. I note that the driver is advertising ioctl support(commented too) but only dummy stub function exists.

**Comment by stsp** [comment]
Yes, seems to be the right guess.
See emufs.c:93 for an ioctl definition.

**Comment by 1ras** [comment]
ONERROR works for the return code of the previous command. I added a few more ONERROR lines for the other device drivers and the error message contains now the name of the device driver. This should make it easier to see which one is triggered.

dconfig.sys as text file:
[dconfig.sys.txt](https://github.com/dosemu2/dosemu2/files/6819052/dconfig.sys.txt)

Screenshots:
![Screenshot_20210714_233129](https://user-images.githubusercontent.com/45467075/125696005-efb34231-bfb1-4cc0-8cb3-2f61bf6ee676.png)
![Screenshot_20210714_233150](https://user-images.githubusercontent.com/45467075/125696011-b9ae5a69-26d4-4ced-b1a5-16db5abcca18.png)
![Screenshot_20210714_233209](https://user-images.githubusercontent.com/45467075/125696017-a868403f-5d6c-42a8-9a9a-bf566dd48346.png)
![Screenshot_20210714_233234](https://user-images.githubusercontent.com/45467075/125696025-5b023c41-cdbd-4500-8d72-ef23a1a835a2.png)

**Comment by stsp** [comment]
OK, thanks.
I enlarged the tables for ems/umb.sys.
Please see if it changed anything.

**Comment by 1ras** [comment]
Nope:

![Screenshot_20210714_235612](https://user-images.githubusercontent.com/45467075/125698456-c7f165c7-83ca-418d-8619-645144909a2b.png)

**Comment by 1ras** [comment]
BTW I just saw that the URL at line 2 is outdated:
`Get the latest code at http://stsp.github.io/dosemu2`

**Comment by stsp** [comment]
Can you try changing in line 96 the
expression $0x8003 to $0?

**Comment by andrewbird** [comment]
I can reproduce this here using DR-DOS 7.01. I see that only the Init() function is being called in the driver (good), the hookhimem macro returns with carry set (unsure), and the umb driver is not loaded by DOS as the error path intends(good). So I wonder why the hookhimem returns with carry set but the success message is still printed.

**Comment by stsp** [comment]
I wanted to reproduce too, but
found that neither install-otherdos
nor install-freedos work.
Hope @jschwartzenberg (or you? :)
can fix those.

Are you sure umb.sys behaves that
way? I can only see that ems.sys
ignores hookhimem.

**Comment by andrewbird** [comment]
I just use the testsuite to create a minimal environment
~~~
test/test_dos.py DRDOS701TestCase.test_systype
Test DR-DOS-7.01 SysType                                                         ... ok (  3.14s)

----------------------------------------------------------------------
Ran 1 test in 3.158s

OK
~~~

Then edit the `test-imagedir/dXXXXs/c/dconfig.sys` to add `onerror ` after 
```dos
device=d:\dosemu\umb.sys
onerror => 1 ? "UMB.SYS: An error occurred, press any key to continue." :
```

With this patch I get this
```asm
ajb@polly:/clients/common/dosemu2.git$ git diff
diff --git a/src/plugin/dosdrv/umb.s b/src/plugin/dosdrv/umb.s
index 118d346a5..2942717cd 100644
--- a/src/plugin/dosdrv/umb.s
+++ b/src/plugin/dosdrv/umb.s
@@ -140,7 +140,7 @@ Init:
 
 1:
        call    HookHimem
-       jc      Error
+       jc      .LHookHimemFail
 
        movb    $9, %ah
        movw    $UmbInstalledMsg, %dx
@@ -149,6 +149,12 @@ Init:
        xorw    %ax, %ax
        ret
 
+.LHookHimemFail:
+       movb    $9, %ah
+       movw    $HookHimemFailMsg, %dx
+       int     $0x21
+       jmp     Error
+
 .LdosemuTooOld:
        movb    $9, %ah
        movw    $DosemuTooOldMsg, %dx
@@ -177,6 +183,9 @@ Error:
        movw    $0x800c, %ax            # error
        ret
 
+HookHimemFailMsg:
+       .ascii  "ERROR: HookHimem has carry set, umb.sys not loaded.\r\n$"
+
 DosemuTooOldMsg:
        .ascii  "ERROR: Your dosemu is too old, umb.sys not loaded.\r\n$"
```

~~~
Starting DOS...
 
EMUFS host file and print access available
dosemu XMS 3.0 & UMB support enabled
ERROR: HookHimem has carry set, umb.sys not loaded.
UMB.SYS: An error occurred, press any key to continue.
dosemu EMS driver rev 0.9 installed.
dosemu CDROM driver installed (V0.2)
 
Caldera OpenDOS 7.01
~~~

and dosdebug shows the umb.sys driver is not loaded

~~~
dosdebug> mem
Command 'mem' not implemented
dosdebug> mcbs

ADDR(LOW) PARAS  OWNER
024a:0000 0x00fd [DOS]
  => ADDR      PARAS TYPE USAGE
     024b:0000 0x000a [D] Driver (EMUFS)
     0256:0000 0x000c [D] Driver (EMS)
     0263:0000 0x0031 [D] Driver (CDROM)
     0295:0000 0x0091 [F] Files
     0327:0000 0x0020 [B] Buffers
0348:0000 0x001e [COMMAND]
0367:0000 0x0040 [00841]
03a8:0000 0x000b [FREE]
03b4:0000 0x000c [FREE]
03c1:0000 0x168d [FREE]
1a4f:0000 0x85b0 [00841] (END)
~~~

My lack of DOS knowledge means I don't know what the correct action should be if Himem can't be hooked, but at the moment it looks like umb.sys isn't loaded (possibly correct), and the `dosemu XMS 3.0 & UMB support enabled` message suggests that it is(seems wrong). The driver loading return value seems correct for the situation.

**Comment by stsp** [comment]
I seem to recall what does this mean.
If umb.sys doesn't see the external himem.sys,
it just enables the internal UMB driver
and unloads completely as its no longer needed.

**Comment by stsp** [comment]
However it prints success because
everything works with internal driver
quite fine too.

**Comment by stsp** [comment]
Does something like this work?
```
--- a/src/plugin/dosdrv/umb.s
+++ b/src/plugin/dosdrv/umb.s
@@ -140,7 +140,7 @@ Init:
 
 1:
        call    HookHimem
-       jc      Error
+       jc      Noload
 
        movb    $9, %ah
        movw    $UmbInstalledMsg, %dx
@@ -170,11 +170,10 @@ Init:
 Error:
        movw    $0, %cs:HdrAttr         # Set to block type
        movb    $0, %es:13(%di)         # Units = 0
-
+       movw    $0x800c, %ax            # error
+Noload:
        movw    $0,%es:14(%di)          # Break addr = cs:0000
        movw    %cs,%es:16(%di)
-
-       movw    $0x800c, %ax            # error
        ret
 
 DosemuTooOldMsg:
```

**Comment by andrewbird** [comment]
> If umb.sys doesn't see the external himem.sys,
it just enables the internal UMB driver
and unloads completely as its no longer needed.

Then the non zero return value is correct (to prevent loading), however I wonder if we can come up with a better solution where resident size is set to zero and but the return value is success. I'm not sure this would work across all DOSes, though.

Edit: It looks like you beat me to it! I'll need to test later though.

**Comment by stsp** [comment]
Except that in my patch Noload
doesn't zero out AX, so its still wrong.
So I am not going to beat you on that. :)

**Comment by stsp** [comment]
> resident size is set to zero and but the return value is success. I'm not sure this would work across all DOSes, though.

We have a fall-back option to
actually load the himem.sys first.
Except that I have the vague recollections
that openDOS's himem.sys didn't
work under dosemu.

**Comment by 1ras** [comment]
You are right, HIMEM.SYS of DR-DOS 7.03 is not an option:

![Screenshot_20210715_170126](https://user-images.githubusercontent.com/45467075/125812450-fa97c057-c04d-4ca5-86e7-83adf7ce62da.png)

**Comment by 1ras** [comment]
HIMEMX.EXE works and return code of UMB.SYS is correct:

![Screenshot_20210715_172558](https://user-images.githubusercontent.com/45467075/125814446-1be78e6a-ea6a-48e6-b8f5-391c5705a26b.png)

**Comment by 1ras** [comment]
> _Make sure himem.sys is loaded right before ems.sys in your config.sys._

Should be "_right before **umb.sys** in your config.sys_" I guess.

**Comment by stsp** [comment]
Message fixed.
What does umb.sys say when loaded
before `DOS=HIGH,UMB`?

**Comment by 1ras** [comment]
It was loaded before `DOS=HIGH,UMB`. I should have uploaded the config files too, please see now attached.
[dconfig.sys.himem.txt](https://github.com/dosemu2/dosemu2/files/6824646/dconfig.sys.himem.txt)
[dconfig.sys.himemx.txt](https://github.com/dosemu2/dosemu2/files/6824647/dconfig.sys.himemx.txt)

Let me also test with `DOS=HIGH,UMB` before UMB.SYS.

**Comment by 1ras** [comment]
The `DOS=` line is now before UMB.SYS. No difference to the above two screenshots.

There is no UMB available this way.

The order of `UMB,HIGH` vs. `HIGH,UMB` doesn't matter in all 4 setups (tested as well).

[dconfig.sys.himem-umb,high-first.txt](https://github.com/dosemu2/dosemu2/files/6824705/dconfig.sys.himem-umb.high-first.txt)
[dconfig.sys.himemx-umb,high-first.txt](https://github.com/dosemu2/dosemu2/files/6824706/dconfig.sys.himemx-umb.high-first.txt)

**Comment by stsp** [comment]
So you mean, in both cases it
prints that umb.sys successfuly
installed, right?
Now does the result on ONERROR
changes in such scenarios?
Sorry, `DOS=HIGH,UMB` string is
not visible on any screen-shots, so
they tell nothing to me about the
ordering.

**Comment by 1ras** [comment]
Screenshot https://github.com/dosemu2/dosemu2/issues/1512#issuecomment-880787879
corresponds to the attached files
**dconfig.sys.himem.txt** and **dconfig.sys.himem-umb,high-first.txt**

Screenshot https://github.com/dosemu2/dosemu2/issues/1512#issuecomment-880792172
corresponds to the attached files
**config.sys.himemx.txt** and **dconfig.sys.himemx-umb,high-first.txt**

**Comment by stsp** [comment]
So himemx&umb.sys are after
`DOS=HIGH,UMB` and the message
is success, but does UMB actually
work in that case?

**Comment by 1ras** [comment]
In this case no UMB.

Config: 
[dconfig.sys-himemx+umb.sys-after-dos=high,umb.txt](https://github.com/dosemu2/dosemu2/files/6824897/dconfig.sys-himemx%2Bumb.sys-after-dos.high.umb.txt)

Screenshots:
![Screenshot_20210715_184755](https://user-images.githubusercontent.com/45467075/125826587-eb90ced1-e7b1-4211-88c8-0bddf2bacf2b.png)

![Screenshot_20210715_184805](https://user-images.githubusercontent.com/45467075/125826602-36f2d3f3-b7c1-4d61-9dd7-07aa6b5579a4.png)

**Comment by 1ras** [comment]
Oh, it seems that UMB is available but **not for DOS applications**. The DOS kernel code can load itself into UMB:

![Screenshot_20210715_190435](https://user-images.githubusercontent.com/45467075/125828294-cab9fa89-f2b3-4d7a-bbc1-f048d3741ff1.png)

But actually the DOS kernel code should not be loaded into UMB, it should be loaded into HMA where space is reserve for it but not used (that's a different strange behavior which I have under observation, I will document it in another bug report to not make things too complicated):

![Screenshot_20210715_190635](https://user-images.githubusercontent.com/45467075/125828598-13ad0610-fffa-4377-af22-787e877bf5d4.png)

**Comment by stsp** [comment]
Can you check hihemx -> `DOS=HIGH,UMB` -> umb.sys?

**Comment by 1ras** [comment]
No difference with himemx -> DOS=HIGH,UMB -> umb.sys.

**Comment by stsp** [comment]
OK, so UMB is available, but its
size seems to be smaller that usual,
and its not available to DOS apps.
More than strange. :)
Please provide 2 screen-shots: one
with default boot (where UMB is broken)
and one with "fixed" boot where you
put umb.sys earlier. In both cases
no himem/himemx.

**Comment by andrewbird** [comment]
It's taking too much time for me to understand how the various memory types (xms, umb, ems) interact. I originally intended just to see if I could make a driver return with success even without it becoming resident. That turned out to be the easy bit. Interestingly it's now more clear to me why DOS driver loading doesn't depend upon the status returned by its `Init()` function and is determined by header attributes plus resident code size. So in any case an interesting rabbit hole for me, although I don't really have the time to wrap it up in a proper PR. As I don't want to hold anybody up, it's probably best if you can make the changes to the xms.inc etc to get the proper behaviour as you understand what's required there.

Here's the fragment that sets the third exit option you might find useful
```asm
Error:
	movw	$0x800c, %ax		# error
	jmp 4f

SuccessNoload:
	xorw    %ax, %ax		# okay

4:
	movw	$0, %cs:HdrAttr		# Set to block type
	movb	$0, %es:13(%di)		# Units = 0
	movw	$0,%es:14(%di)		# Break addr = cs:0000
	movw	%cs,%es:16(%di)
	ret

SuccessLoad:
	xorw 	%ax, %ax
	ret
```

**Comment by stsp** [comment]
I removed UMB support from ems.sys.
Does this help?

**Comment by stsp** [comment]
I opened #1515 
Does this work?

**Comment by andrewbird** [comment]
With the onerror lines added I see this
~~~
Starting DOS...
 
EMUFS host file and print access available
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
dosemu CDROM driver installed (V0.2)
 
Caldera OpenDOS 7.01
~~~

and mcbs shows it's not loaded

~~~
dosdebug> mcbs

ADDR(LOW) PARAS  OWNER
024a:0000 0x00fa [DOS]
  => ADDR      PARAS TYPE USAGE
     024b:0000 0x000a [D] Driver (EMUFS)
     0256:0000 0x0009 [D] Driver (EMS)
     0260:0000 0x0031 [D] Driver (CDROM)
     0292:0000 0x0091 [F] Files
     0324:0000 0x0020 [B] Buffers
0345:0000 0x001e [COMMAND]
0364:0000 0x0040 [00838]
03a5:0000 0x000b [FREE]
03b1:0000 0x000c [FREE]
03be:0000 0x168d [FREE]
1a4c:0000 0x85b3 [00838] (END)
~~~

However the MS-DOS 6.22 boot seems to hang, not sure why (but I can see in config.sys the next line is emufs.com

~~~
Starting MS-DOS...
 
 
HIMEM is testing extended memory...done.
EMUFS host file and print access available
dosemu EMS driver rev 0.9 installed.
dosemu CDROM driver installed (V0.2)
< stuck here > 
~~~

**Comment by stsp** [comment]
The only difference might be that
we no longer return an error, so can
you try on SucceNoload to return
0x8000? Would be error but zero
error code.

**Comment by andrewbird** [comment]
Setting 0x8000 made no difference. I'm going to test devel as well because there was the removal of xms.inc too.

**Comment by stsp** [comment]
But I don't see the umb.sys messages
on your screen, only ems.sys. Haven't
you loaded umb.sys at all?

**Comment by andrewbird** [comment]
It's the standard config the but the message isn't printed
Here's devel, where it is
~~~
Starting MS-DOS...
 
 
HIMEM is testing extended memory...done.
EMUFS host file and print access available
dosemu UMB driver installed
dosemu EMS driver rev 0.9 installed.
dosemu CDROM driver installed (V0.2)
emufs: redirector enabled
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
"Welcome to dosemu2 2.0pre8-20210717-3047-g8cbe51add!"
Interactive Prompt!
C:\>
 ~~~

**Comment by stsp** [comment]
So it seems it jumps to NoLoad
wehreas it should actually load?
(you have himem.sys so it should)

**Comment by andrewbird** [comment]
That's my impression too.

**Comment by 1ras** [comment]
I did a few more tests with a native PC and with

```
DOS=HIGH
DEVICE=DRDOS\EMM386.EXE
```

And UMB is available. It looks like `DOS=UMB` is optional with DR-DOS own EMM386. That might explain why the order doesn't matter with their own EMM386.

![snarf000](https://user-images.githubusercontent.com/45467075/126042890-a5741133-78f7-4e82-a428-7193e8c0a67d.png)

**Comment by 1ras** [comment]
Dosemu devel with DR-DOS 7.03 and onerror check:

umb.sys > DOS=HIGH,UMB:
Works, no error, UMB available.

himemx.exe > umb.sys > DOS=HIGH,UMB:
Works, no error, UMB available.

himem.sys > umb.sys > DOS=HIGH,UMB: 
```
EMUFS host file and print access available
HIMEM.SYS: Cannot control address line A20.
HIMEM.SYS 2.34
Unable to hook into himem.sys, UMB disabled.
Make sure himem.sys is loaded right before umb.sys in your config.sys.
UMB.SYS: An error occurred, press any key to continue.
```

I added the last case just to see if the error condition still works.

**Comment by stsp** [comment]
Finally the installer of opendos works,
and I reproduced this problem with
odconfig.sys.
So fixed also there now.
