### ISSUE TITLE
File corruption of the Dos Navigator configuration file

### ISSUE THREAD

**Issue by 1ras** [dosemu2/dosemu2#1517]
**Describe the bug**
Dos Navigator 2.14 configuration file corruption when long file name support is switched off.

**To Reproduce**
1. Required Dosemu configuration: `$_lfn_support = (off)`
2. Install [Dos Navigator 2.14](http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/repositories/1.3/pkg-html/dn2.html)
3. `speed 3` (looks like Dosemu2 is too conservative with Dos Navigator 2)
4. Start `dn.com`
5. Alt+X to exit DN, so that it saves it's initial configuration
6. `dir dn.cfg` and you should have a configuration file with about 18091 bytes
7. Start `dn.com` again
8. Open the configuration setup and confirm it with ok (you don't need to change anything): Alt+o Enter Enter Enter
9. The file size of the `dn.cfg` file should not grow. But with dosemu devel it almost doubles in size and grows each time the configuration is saved.

**A regression?**
Yes, git bisect says it's related to https://github.com/dosemu2/dosemu2/commit/9f7035e56b88b1557f9b28274d090e6c42e948a2

**Additional info**
The original [Dos Navigator 1.51](https://www.ritlabs.com/en/products/dn/) is affected as well, so I guess all open source versions are affected.

**Comment by stsp** [comment]
Mouse seems to be broken in
dn-2.14. Is this a dosemu bug?

**Comment by 1ras** [comment]
The scroll wheel works with DN 2.14 but it seems that it has issues with the other buttons in Dosemu. On a native system mouse works (CuteMouse driver).

Older DN versions like the 1.51 also work in Dosemu.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by 1ras** [comment]
Both works, thanks!
