### ISSUE TITLE
Vertical wraparound with very large terminals

### ISSUE THREAD

**Issue by taviso** [dosemu2/dosemu2#1518]
**Describe the bug**

It seems that when the terminal reports more than 63 lines, there is some vertical wraparound in the display.

This was originally reported as a possible 123 driver bug in https://github.com/taviso/lotusdrv/issues/7, but it reproduces with wordperfect and foxpro too, so I think it's a dosemu bug.

**To Reproduce**
Steps to reproduce the behaviour:

Make your terminal at least 64 lines high, then start a program that supports arbitrary vga screen size (wp, foxpro, 1-2-3).

**A regression?**

Unsure.

**Comment by stsp** [comment]
Is it possible to reproduce with something
simple, like dos navigator?
I am struggling to even set up such size.
The notebook resolution is not enough.
I tried to make the terminal to span multiple
virtual work-places, but it doesn't work
that way, at least on ubuntu.
So I guess I can't help much unless you
tell me some trick for such sizes to became
possible.

**Comment by stsp** [comment]
Oh, I can make a smaller font, lets try again...

**Comment by stsp** [comment]
Confirmed.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by taviso** [comment]
Thanks Stas!
