### ISSUE TITLE
QuickTime for Windows 2.00 installation fails

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1521]
**Describe the bug**
The installation stops with this screen:
![Screenshot_20210801_110633](https://user-images.githubusercontent.com/877112/127765593-4c465d83-c231-4022-9829-03fd52367595.png)
The mouse can still be moved.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Sim City from its CDROM
2. Try to run the Maxis Sampler
3. Go along with its suggestion to install QuickTime

**Attach program/game binaries or provide an URL**
https://archive.org/details/SimCity_201708

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/6912409/boot.log)

**A regression?**
Unknown.

**Additional info**
This is with FDPP as usual.

**Comment by stsp** [comment]
Hmm.
That usually means int24 not correctly
passed to PM.

**Comment by stsp** [comment]
Please add -D9+M log.

**Comment by stsp** [comment]
`-D9+Mi#` please.

**Comment by jschwartzenberg** [comment]
> `-D9+Mi#` please.

[boot.log.gz](https://github.com/dosemu2/dosemu2/files/6912814/boot.log.gz)

**Comment by stsp** [comment]
Is this fdpp-specific?

**Comment by jschwartzenberg** [comment]
Seems not really, with MS-DOS 6.22 I get this:
![Screenshot_20210801_212556](https://user-images.githubusercontent.com/877112/127783013-3b1f255f-b346-497e-90bf-95793be5357c.png)

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
So it installed something, and maybe
it actually worked? :) What was installed?

**Comment by jschwartzenberg** [comment]
It dropped some stuff below the `c:\windows` directory, but it's not really clear what. No icons were created. I tried to see if there was a logging feature, but it seems the installer doesn't have it. `/?` gives a list of arguments but nothing related to logging.

**Comment by stsp** [comment]
Then please open new bug, see if
it is fdpp-specific, and all that.

**Comment by stsp** [comment]
![Снимок экрана от 2021-08-05 00-34-05](https://user-images.githubusercontent.com/3295627/128258268-cd3a4ee0-9a21-4fdb-b60f-df40a9b481fe.png)

**Comment by stsp** [comment]
![Снимок экрана от 2021-08-05 00-36-57](https://user-images.githubusercontent.com/3295627/128258330-91988bf2-57f1-4787-88ba-8f1574ce7081.png)

**Comment by jschwartzenberg** [comment]
Cool :) I guess you did it in a pretty much clean environment? Probably my environment was messed up by something. Btw. the second screen I had as well, the Maxis installer doesn't do any error checking and will even display that message when you cancel the QuickTime installation.

I hope you had (have) fun trying this out :)

**Comment by jschwartzenberg** [comment]
> ![Снимок экрана от 2021-08-05 00-34-05](https://user-images.githubusercontent.com/3295627/128258268-cd3a4ee0-9a21-4fdb-b60f-df40a9b481fe.png)

That was with FDPP and nothing special right? I just tried with a fresh environment and still get this error. Could these be related?
```
ERROR: MFS: failed to get xattrs, unsupported!
ERROR: MFS: failed to get xattrs, unsupported!
```

I'm not using `/tmp` here for drive C, this is in the default directory in my home directory which is on ext4.

**Comment by stsp** [comment]
Of course it can be related.

> default directory in my home directory which is on ext4.

The code that prints your error is this:
```
  if (size == -1 && errno == ENOTSUP) {
    error("MFS: failed to get xattrs, unsupported!\n");
    return -1;
  }
```

So it checks for ENOTSUP which
means unsupported. Maybe you need
to enable them in fstab/mount opts.

**Comment by jschwartzenberg** [comment]
In that case it would be important to provide information about that in the error I guess if users encounter this on systems with default settings.
I actually don't know if this error is from the mounted cd-rom or the home dir, I have these entries in my current mount table that are applicable:
```
/dev/mapper/matrix-homevol on /home type ext4 (rw,relatime)
/dev/sr0 on /run/media/julius/SimCity type udf (ro,nosuid,nodev,relatime,uid=1000,gid=1000,iocharset=utf8,uhelper=udisks2)
```
I ran dosemu with `dosemu -cdrom /run/media/julius/SimCity`.

Would it be possible to at least display which filesystem is lacking xattrs? Or are you certain it is the home dir that is lacking them here? If it'd be the udf filesystem, what would seem the best way to handle it?

**Comment by stsp** [comment]
Done.

**Comment by jschwartzenberg** [comment]
Now I get:
```
ERROR: MFS: failed to get xattrs for /run/media/julius/SimCity/GOODIES/SAMPLER/SETUP.LST, unsupported!
```

So I guess that's not a difference between our environments.

**Comment by stsp** [comment]
Who knows?
Maybe I extracted the CD to
the DOS partition? I don't remember.

**Comment by andrewbird** [comment]
/run on my Ubuntu machine is tmpfs.

**Comment by jschwartzenberg** [comment]
Found it! I had `$_attrs_support=(off)` in my `.dosemurc`. Commenting that out fixed the installer.

**Comment by stsp** [comment]
OK I removed that option.
It seems it now enables the
fall-back that is always enabled
anyway.

**Comment by jschwartzenberg** [comment]
Great! Always good when I have fewer ways to screw things up :)
