### ISSUE TITLE
How to turn on TTF fonts?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1523]
Apologies for ignorance. I'm coming back to this project after a few months away. I can't find anything in the conf file that enables TTF output, and a search here doesn't show anything obvious. For the sake of those of us who are just coming to this, could we have an explanation of how to turn on TrueType, perhaps in the wiki? Thank you again.

**Comment by stsp** [comment]
They are still on by default.
Please check any problem's
existence by first removing
`~/.dosemu` to see if this isn't
a local misconfiguration (assuming
you never touched `/etc/dosemu/*`)

**Comment by emendelson** [comment]
Yes, I see - the TTF font looks so much like the old bitmaps that I didn't realize it was TTF. Well done, and thank you.
