### ISSUE TITLE
Sim City 2000 demo installer from Sim City CD crashes through `system\krnl286`

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1528]
> No, something else then.
> Worth a new ticket.

_Originally posted by @stsp in https://github.com/dosemu2/dosemu2/discussions/1075#discussioncomment-1186711_

**Comment by stsp** [comment]
Please provide a screen shot,
not a quote.

**Comment by stsp** [comment]
And -D9+M log.

**Comment by jschwartzenberg** [comment]
![Screenshot_20210816_210801](https://user-images.githubusercontent.com/877112/129616734-15738436-6134-45b7-84e1-cd80d5fe21f7.png)

Matching log:
[boot.log.gz](https://github.com/dosemu2/dosemu2/files/6994811/boot.log.gz)

**Comment by stsp** [comment]
I added the untested patch
to branch "rep", please test.

**Comment by jschwartzenberg** [comment]
Yep, with that one it works!
