### ISSUE TITLE
Leisure suit Larry 2 installer: Packed file is corrupt

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1535]
**Describe the bug**
![Screenshot_20210821_181438](https://user-images.githubusercontent.com/877112/130328172-245f7b19-ff26-4d14-bc67-8238bbc9cc45.png)

**To Reproduce**
Just run the included `install.exe`.

**Attach program/game binaries or provide an URL**
https://freebies.indiegala.com/leisure-suit-larry-2-looking-for-love-in-several-wrong-places

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/7025807/boot.log)

**A regression?**
No idea.

**Additional info**
Works fine with DOSBox.

**Comment by stsp** [comment]
loadfix install

**Comment by jschwartzenberg** [comment]
Indeed! Silly I never knew that. It claims a bit of memory as some programs get confused? I don't think I used it before.

**Comment by stsp** [comment]
> It claims a bit of memory as some programs get confused?

Indeed.

> I don't think I used it before.

I think it is present in all DOSes.

**Comment by skitt** [comment]
> > I don't think I used it before.
> 
> I think it is present in all DOSes.

Ever since DOS 5.0 which enabled the HMA (the error is related to the A20 gate, see https://en.wikipedia.org/wiki/A20_line#EXEPACK).

**Comment by stsp** [comment]
Also worth to note that freedos
does "interesting" things: it actually
keeps a20 disabled, and enables
it only when entering the syscall.
Perhaps loadfix is not even needed
under freedos.
fdpp removes that and relies on
loadfix instead, the way ms-dos
did.
