### ISSUE TITLE
how do i fix this issue? ncurses apps not render properly in tmux?

### ISSUE THREAD

**Issue by gotbletu** [dosemu2/dosemu2#1538]
i havent change any settings, just the default dosemurc file
```
Name            : dosemu2-git 2.0pre8.r3110.g604ac933a-1
OS: ArcoLinux
Kernel: 5.13.13-zen1-1-zen
Name            : tmux 3.2_a-1
```

$ dosemu -t

in tmux:
https://i.imgur.com/xkXETEU.png

without tmux:
https://i.imgur.com/sTd7KYZ.png

**Comment by andrewbird** [comment]
Maybe hwinfo doesn't know how to deal with non standard screen size. Did you try tmux's `resize-pane -x 80 -y 25`?

**Comment by stsp** [comment]
The easier trick is:
`$_term_set_size = "25x80"`
Hmm, shouldn't that be "80x25"
instead...

**Comment by gotbletu** [comment]
Thanks that did the job

> The easier trick is:
> `$_term_set_size = "25x80"`
> Hmm, shouldn't that be "80x25"
> instead...

**Comment by stsp** [comment]
Would you and @magiblot forgive
me if I change that option to accept
"XxY" instead of "YxX" notation, so
that it will be "80x25"?
Would that be a good change?

**Comment by magiblot** [comment]
> Would that be a good change?

I support that change.

**Comment by stsp** [comment]
OK, done then.
Please use `$_fixed_term_size = "80x25"`
from now on.
