### ISSUE TITLE
Is dosdebug's mcbs command showing proper data?

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1541]
The recent MCB data block markup I recently added looks strange (shows 'COMMAND - Data') with the last block. I see this at least with FreeDOS, FDPP and MSDOS so I'm pretty sure it's not a quirk of the DOS I'm using. I'll use Qemm 7.5's MFT, but I don't think it's specific to that.

MSDOS 6.22                                                                      
                                                                                
before prog run                                                                 
----------------                                                                
                                                                                
dosdebug> mcbs                                                                  
050f:0000 0x0004 [FREE]
0514:0000 0x0005 [FREE]
051a:0000 0x0007 [FREE]
0522:0000 0x9adc [COMMAND - Data] (END)
                                                 
dosdebug> d 050f:0000 16                                                        
                                                                                
050f:0000 4D 00 00 04 00 BB DC 07 3C 05 74 06 BB 5F 07 BE  M....;\.<.t.;_.>     
                                                                                
whilst mft is running the last MCB is in use and marked as 'Z' type                                                                       
----------                                                                      
                                                                                
dosdebug> mcbs                                                                  
050f:0000 0x000d [MFT - Environment]                                            
051d:0000 0x9ae1 [MFT] (END)                                                    
dosdebug> d 050f:0000 16                                                        
                                                                                
050f:0000 4D 1E 05 0D 00 BB DC 07 3C 05 74 06 BB 5F 07 BE  M....;\.<.t.;_.>     
dosdebug> d 051d:0000

051d:0000 5A 1E 05 E1 9A E9 45 01 4D 46 54 00 C0 86 06 E8  Z..a.iE.MFT.@..h
                                                                      
                                                                                
after mft has exited
--------------                                                                  
                                                                                
dosdebug> mcbs                                                                  
050f:0000 0x9aef [COMMAND - Data] (END)                                         
                                                                                
dosdebug> d 050f:0000 16                                                        
050f:0000 5A 29 04 EF 9A BB DC 07 3C 05 74 06 BB 5F 07 BE  Z).o.;\.<.t.;_.>     
                                                                       
/*
 Memory Control Block (10h bytes)
00 Type ('M' or 'Z' if last)
01 PSP segment of owner (0=free,8=DOS)
03 Size (paragraphs)
05 Unused
08 Program name (4.0+)
*/

So the freed space coalesced into one block, which is nice, but is it really fully allocated to and so owned by command.com? How does it then get used by DOS for launching a new program?

**Comment by stsp** [comment]
Can't reproduce:
```
dosdebug> mcbs

ADDR(LOW) PARAS  OWNER
007c:0000 0x0016 [FREE]
0093:0000 0x0034 [FREE]
00c8:0000 0x9f36 [FREE] (END)
```

```
dosdebug> mcbs

ADDR(LOW) PARAS  OWNER
007c:0000 0x0017 [MFT - Environment]
0094:0000 0x9f6a [MFT] (END)
```

```
dosdebug> mcbs

ADDR(LOW) PARAS  OWNER
007c:0000 0x0017 [FREE]
0094:0000 0x9f6a [FREE] (END)
```

**Comment by andrewbird** [comment]
How strange! What DOS are you using, and can you dump the MCB so I can see what the difference is?

**Comment by stsp** [comment]
`Version string (Int21.33FF): FDPP kernel 1.3 [GIT: 1.3-40-gae4ec75] (compiled Sep  9 2021)`

```
dosdebug> mcbs

ADDR(LOW) PARAS  OWNER
007c:0000 0x0016 [FREE]
0093:0000 0x0034 [FREE]
00c8:0000 0x9f36 [FREE] (END)

dosdebug> d 00c8:0000

00c8:0000 5A 00 00 36 9F 84 85 86 87 88 89 8A 8B 8C 8D 8E  Z..6............
```

After mft:
```
dosdebug> mcbs

ADDR(LOW) PARAS  OWNER
007c:0000 0x0017 [FREE]
0094:0000 0x9f6a [FREE] (END)

dosdebug> d 0094:0000

0094:0000 5A 00 00 6A 9F 9A F0 FE 00 00 00 00 00 00 00 00  Z..j..p~........
```

OK?

**Comment by andrewbird** [comment]
I'll try again using freedos, though I'm sure I saw it there before I tried on MS-DOS 6.22.

**Comment by andrewbird** [comment]
So with FreeDOS 1.20, I get different but still strange results
~~~
dosdebug> mcbs
02b0:0000 0x12c1 [COMMAND - Data]
1572:0000 0x8a8c [FREE] (END)

dosdebug> d 02b0:0000

02b0:0000 4D 4D C4 C1 12 00 00 00 00 00 00 00 00 00 00 00  MMDA............
dosdebug> d 1572:0000

1572:0000 5A 00 00 8C 8A 01 CB 00 00 00 00 00 00 00 00 00  Z.....K.........
~~~

**Comment by stsp** [comment]
> 02b0:0000 0x12c1 [COMMAND - Data]

No idea what command.com consumes
so much memory. But its not comcom32.
And of course there is nowhere you
specified that.

**Comment by andrewbird** [comment]
It's standard that FDPP uses comcom32, FreeDOS uses freecom, and MSDOS uses its own command.com, that's the default config. So in any case it seems there's no problem, just an oddity that dosdebug displays fine.

**Comment by stsp** [comment]
Some command.com may allocate more,
or even all memory when not executing an
external program. But that's not comcom32.
