### ISSUE TITLE
non-ACSII/accented characters input with dead key

### ISSUE THREAD

**Issue by fhanzlik** [dosemu2/dosemu2#1544]
Not sure when it is possible (IMO should be) - I would like the corresponding characters to be sent to DOS according to the set keyboard layout in Linux desktop (I switch between US and Czech).  My FreeDOS autoexec.bat contains (there isn't :
...
lh display con=(EGA,(850,852),(4,3)) /V
mode con codepage prepare=((852) c:\cpi\ega.cpx)
mode con codepage select 852
...

Now with US layout I can enter all ASCII chars, with Czech layout I can enter all czech characters that are directly on the keyboard (e.g. á,é,ě,ú,ů,§,...). But accented characters cannot be entered using dead keys (Czech layout has dead keys ´/ˇ/° for acute, caron and ring above) nor using Compose key. This is big problem for characters, which are not directly on Czech keyboard (all uppercase chars with diacritics and rare lowercase chars as ť, ď, ň).
I'm almost convinced that dead keys characters input worked in an older version of the dosemu2 (2+  years ago).

My configuration: Fedora 34 x86_64, Dosemu2 from git (2021.10.18 g505b3f2bf), Freedos 1.2

**Comment by fhanzlik** [comment]
I'm running dosemu in X11 mode from MATE terminal (dosemu -X). boot.log show:
...
VID: initializing video X
X: X_init
...
CONF: reserving 8192Kb at 0x4BA29000 for 'e' (VGAEMU LFB)
loading fonts for cp852
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
...
Warning: Using DPMI inside KVM
CONF: detected layout is "us"
CONF: detected alternate layout: cz-qwerty
...

In MATE keyboard applet I have defined 3 keyboard layouts: "English(US)", "Czech(QWERTY, extended backslash)", "Russian (phonetic, Windows).
Under Linux, dead keys and also compose key works good.
When I run Dosemu2, for now I test it only on command.com command input line, then:
- "type FILE-w-all-cp852-chars" display all characters correctly
- accented chars directly located on Czech keyboard displays/enter correctly
- writing accented characters using dead keys behaves as follows (all run from MATE terminal window):

local dosemu -t : Aá+Sš    (upper A Acute as "A", upper S with caron as two chrs "+S", lower a acute and s w caron OK)
local dosemu -X : ´A´aˇSˇs  (acute or caron as separate character + corresponding chars without diacritics)
remote dosemu -t : =Aá+Sš  (upper acute chars as duo "=" + char wo diacritics, similarly upper S with caron as two chrs "+S", 
lower a acute and s w caron OK)
remote dosemu -X : ´A´aˇSˇs  (just like local "dosemu -X" - acute or caron as separate character + corresponding chars without diacritics)

"remote" mean run dosemu2 on remote machine with command "dosemu -X", on that machine I'm connected via SSH with X11 forwarded.

**Comment by fhanzlik** [comment]
It seems as is has no effect if I:
- move "Czech(QWERTY, extended backslash)" at top
- check/uncheck "New windows use active windows layout" checkbox in Linux Layout section of Keyboard Preferences" menu
- remove Russian layout and leave only Czech and US.

What changes - when I have US keyboasr at top (and, of course, unchecked "New windows use active windows layout"),
then order in boot.log is:
...
Warning: Using DPMI inside KVM
CONF: detected layout is "auto"
CONF: detected alternate layout: cz-qwerty
EMULATE
...
and when "Czech(QWERTY, extended backslash)" is at top, then order in boot.log is:
...
Warning: Using DPMI inside KVM
CONF: detected layout is "cz-qwerty"
CONF: detected alternate layout: auto
EMULATE
...
But in any setting, is not possible type accented char with using dead key - with "dosemu -X" it display two chars, diacritics alone and char wo diacritics.

**Comment by fhanzlik** [comment]
> Testing my working Spanish SDL scenario with `-X` instead gives the following incorrect result
> 
> ```
> BLASTER=A220 I5 D1 H5 P330 T6
> MIDI=SYNTH:2 MAP:E MODE:0
> C:\>´E 
> ```
> 
> So at least for me it appears to be an X-Windows problem

It behaves the same way for me - two characters, diacritics alone first and typed character without diacritics second.
But X-Window problem? Whether I type (in Linux) on the command line, in an plaintext editor or a word processor, the result is always correct.

**Comment by stsp** [comment]
@fhanzlik can you check the change in https://github.com/dosemu2/dosemu2/issues/1544#issuecomment-950392128
please?

**Comment by fhanzlik** [comment]
Hi Stas, I'm sorry, I didn't know it was up to me. I will try to try it during the day or in the evening, if there is a moment left.
I will let you know.

**Comment by fhanzlik** [comment]
I tried patch above (
...
-               if (*ch != sym) {
+               if (*ch != sym && !is_keysym_dead(*ch) &&
+                               state->accent == DKY_VOID) {
...)
in dosemu -X mode, and it seems as it behaves the same as before - accented chars directly on keyboard are OK, but when tried type them using dead key, then it output two characters (diacritical mark alone and then typed character) - see attached screenshot.
Diacritical mark appears immediately after pressing dead key, it isn't delayed until following char pressed. It is also possible type a series of diacritical marks in a row by pressing the corresponding dead keys.

Also with $_debug = "-a+9cwkX", according to the occurence of "replace char %x with %x\n" in log it seems, as:

- as a circle above the letter is recognized matching key without SHIFT (on US backquote "`", instead of "~")

- the dead key is not buffered (remembered), and is only detected for the first time after starting Dosemu.

- character processing behaves differently after starting DOS in en_US and in en_US after switching from Czech

- pressing dead keys "ˇ" (caron) or "˚" (ring above), the mouse cursor disappears and is not visible the next time you type.
But appears by pressing SHIFT, releasing it disappears again. Pressing dead key "ˊ" (acute) does not cause the mouse cursor to disappear.

A attached some boot.log created with the debug above, in all Dosemu started with en_US layout:
"a,^,a,á,'a,a,'a,a_boot.log.gz" - where was typed keys:
a
CapsLock (switch to Czech layout)
a
á    (accented letter directly on keyboard)
' a   (dead key acute + a)
a

"s,^,s,ˇs,s_boot.log.gz":
s
CapsLock (switch to Czech layout)
s
ˇ s     (dead key caron + s)
s

"s,^,'s,s,LSHIFT,s_boot.log.gz" (mouse cursor disappearing/appearin on SHIFT pressing):
s
CapsLock (switch to Czech layout)
ˇ s    (dead key caron + s)
s
LeftShift
s

HTH, Franta


![dosemu2_w_patch-1544](https://user-images.githubusercontent.com/9540755/140007558-48a033c0-e94d-43d2-85a9-f717e3bc11c4.png)
[a,^,a,á,'a,a,'a,a_boot.log.gz](https://github.com/dosemu2/dosemu2/files/7490138/a.a.a.a.a.a.a_boot.log.gz)
[s,^,'s,s,LSHIFT,s_boot.log.gz](https://github.com/dosemu2/dosemu2/files/7490139/s.s.s.LSHIFT.s_boot.log.gz)
[s,^,s,ˇs,s_boot.log.gz](https://github.com/dosemu2/dosemu2/files/7490140/s.s.s.s_boot.log.gz)

**Comment by stsp** [comment]
What is "CapsLock (switch to Czech layout)"?
If I am to reproduce this, would it
be enough for me to switch to Czech
layout in the gnome layout switcher?

**Comment by stsp** [comment]
So I added cs layout to keyboard
switcher, but it behaves exactly like
en layout (dosemu-unrelated, even
in any terminal).

**Comment by stsp** [comment]
Ah, got it!
I need to press '=' key (dead
key I suppose) and then any
symbol:
ẃóẃ

**Comment by stsp** [comment]
So:
- contrary to what Andrew said, SDL doesn't seem
to handle czech layout on its own. It doesn't produce
any unicode strings at all, leaving us with keypresses.
- if the right layout is specified, things seem to work
with sdl: `$_layout = "cz-qwerty"`
- With X it doesn't seem to work.

**Comment by stsp** [comment]
I've found that this patch seems
to work with X:
```
diff --git a/src/base/kbd_unicode/serv_xlat.c b/src/base/kbd_unicode/serv_xlat.c
index fce123d6a..4570a0025 100644
--- a/src/base/kbd_unicode/serv_xlat.c
+++ b/src/base/kbd_unicode/serv_xlat.c
@@ -1650,7 +1650,8 @@ static void put_keynum(Boolean make, t_keynum key, t_unicode sym,
                /* switch active keymap if needed */
                state->rules->activemap = state->rules->charset.keys[sym].map;
                ch = get_rule_ptr(key, state);
-               if (*ch != sym) {
+               if (*ch != sym && !is_keysym_dead(*ch) &&
+                               state->accent == DKY_VOID) {
                        k_printf("replace char %x with %x\n", *ch, sym);
                        *ch = sym;
                }
diff --git a/src/plugin/X/keyb_X_keycode.c b/src/plugin/X/keyb_X_keycode.c
index 0d364ec8c..398c48521 100644
--- a/src/plugin/X/keyb_X_keycode.c
+++ b/src/plugin/X/keyb_X_keycode.c
@@ -695,6 +695,7 @@ void X_keycode_process_key(Display *display, XKeyEvent *e)
 #endif
        make = e->type == KeyPress;
        X_sync_shiftstate(make, e->keycode, e->state);
+#if 0
        if (config.layout != -1) {
                /* use classic X_keycode mode from dosemu1.
                 * We don't need xkb here as we are only interested
@@ -702,6 +703,7 @@ void X_keycode_process_key(Display *display, XKeyEvent *e)
                put_keycode_grp(make, e->keycode, e->state);
                return;
        }
+#endif
 #ifdef HAVE_XKB
        key = Xkb_lookup_key(display, e->keycode, e->state);
 #else
```

... if `$_layout = "cz-qwerty"` is also set.
Can you please check that?
I am quite confident that serv_xlat.c
part is correct, so I'll apply it if it works
for you too. As for why `#if 0` is needed,
I don't yet know.

**Comment by stsp** [comment]
I applied a few patches which
"fixes" things for me. But I haven't
found any major bug.
I think the problem was that you
didn't set `$_layout = "cz-qwerty"`

**Comment by fhanzlik** [comment]
Yes, I didn't set $_layout = "cz-qwerty" (ev. $_layout = "cz-qwertz") - $_layout option I had unused, commented - because I thought it would work, with possibility switch between en_US and cs_CZ also in DOS. That "default: 'auto' (which tries to generate the table from the current Linux console settings)" from dosemu.conf comment about keyboard layout, I understood so that DOS will follow switching the keyboard under X. And it almost works - with "en" layout I can type all ASCII in X and also in DOS, and with "cs" layout I can type all accented characters which are directly on individual keys. Only typing accented chars using dead keys is not working.

In DOS I need, in addition to Czech characters, I also need to write some ASCII characters that are not in the Czech layout (@,<,>,[,],'). Thus when Dosemu isn't able detect current X layout, I have IMO two options, none is optimal:

1) dosemu.conf without any '$_layout = ...', which will allow me switching layout in X, and Dosemu will handle properly all characters from both layout, but I cannot use dead keys.

2) dosemu.conf with $_layout = "cz-qwerty" - then Dosemu ignore keyboard switching in X and writes Czech characters in both X layouts, en or cs. And to type ASCII chars that are not in the Czech keyboard layout, I must use the DOS keyb utility/driver - thus 
I'll have twokeyboard switchers, one for X and the other for DOS (and will have less memory for DOS tasks).

It is so?

**Comment by fhanzlik** [comment]
> Ah, got it! I need to press '=' key (dead key I suppose) and then any symbol: ẃóẃ

Yes, "=" in US layout is acute "ˊ" dead key, with shift ("+" in US) it is caron "ˇ" dead key, and last is ring above("˚") - tilde "~" in US

**Comment by stsp** [comment]
OK, its now possible to specify 2
layouts, like this: `$_layout = "us,cz-qwerty"`.
So now you have the third option,
in an addition to the 2 you mentioned
above.

**Comment by fhanzlik** [comment]
Yeah, possibility to specify two layouts is really perfect! I now tried 448fb58, and it seems be almost OK. Only one things seems be wrong - dead key "acute" ("=" on US, keycode 13) work only with lower case letters, not with upper case. Dead key "caron" (same key as "acute", but with shift) work well with both lower and upper letters.
Thanks for this perfect solution!

**Comment by stsp** [comment]
Should now be fixed.
This time there appeared some real bugs.

**Comment by fhanzlik** [comment]
>  This time there appeared some real bugs.
It sounds scary, but it seems as everything about dead keys and layout switching is now working!
Thanks!

**Comment by stsp** [comment]
Pasting works too?

**Comment by fhanzlik** [comment]
If you mean pasting from the clipboard (issue #1546), I continue there.

**Comment by fhanzlik** [comment]
Moreover, one positive thing: Until a few hours ago, it was not possible to write a letter 'Ú' (upper U acute) - according to my tests, the only from the Czech alphabet (at the same time, all others, including other acute vowels ÁÉÍÓ and all letters with caron, was possible to type perfectly), which is typed using dead key. And now - it is working, I can type it without problem!

PS: somewhere at the beginning of the description of this issue I wrote that problem is also with dead key "ring above" (keycode 41, '~'/'`' on US keyboard, typed with Shift). This dead key works in Linux X11, but it seems, as in Dosemu isn't defined (according to src/base/kbd_unicode/keymaps.c -> t_keysym shift_map_cz_qwerty[] or t_keysym shift_map_cz_qwertz[] - there is 0xeff8 (ring above), instead of DKY_DEAD_ABOVERING).
But IMO this is not problem and it can stay as is, because in Czech alphabet only letter with ring above is "u" (as ů/Ů) - but small letter "u" with acute is directly as key on Czech keyboard, and this accented vowel may, except in very rare cases, occur only within word or at word end, not at the beginning - thus except some capital word transcription this is not used.

**Comment by stsp** [comment]
Good to know that we are strong
on an i18n field. :)

**Comment by fhanzlik** [comment]
Just don't shout it! Or in the next issue, you will have to learn all the chinese characters ;)  ;)  ;)

**Comment by stsp** [comment]
But I haven't seen any characters even
in your case. All I've seen were the
question marks.
Its your fault.
Please comment out the
`PS: I have also '$_external_char_set = "utf8"' and '$_internal_char_set = "cp852"' in dosemu.conf, in all tests.`
changes you did in the config, and follow the
instructions that it will write on start.

**Comment by stsp** [comment]
You should see something like this:
```
ERROR: Can't find codepage for "cz".
Please add the mapping to locales.conf and send patch.
```

Please DO that rather than to work
around. You'll save me a lot of debugging
time for the next round.

**Comment by fhanzlik** [comment]
Hi Stas, can You be more  specific? I not understand, what I did wrong and what I should do now. My comment about $_external_char_set/$_internal_char_set should have been in my first report, which opened this case, I forgot to mention it there, so I wrote it later. 
And as for your instructions, what do you mean? I see only something about "auto mode" - which I don't know what that means, and dosemu.conf does not mention such a mode.
In any case, it was by no means my intention to conceal anything, and I always tried to give the most accurate description of the case and the information around it. I appreciate your work and it is in my interest to make it as effective as possible.

**Comment by stsp** [comment]
Just comment out those settings
in dosemu config. It should write
what to do on a next start.
We need to integrate your locale.
Then I will see your chars.

**Comment by stsp** [comment]
I mean, you altered the config instead
of doing what dosemu asks you to do
when the config is not altered.
This is not something bad, but you
need to try again without doing that.
Then we will integrate the support
for your locale.

**Comment by fhanzlik** [comment]
I probably live in another universe :(
I still don't really know what's going on.
My character set is definitely cp852, I know that and I don't need the program to recommend it to me.
I've had some settings in the dosemu.conf years ago, that's why the file is, isn't it?
Are you saying that I don't have the $_external_char_set/$_internal_char_set option used in the dosemu.conf, that the program will advise me something?
When there are no these options in the configuration file, the program does not ask me or recommend anything - neither in the DOS window, nor on stderr, nor in the boot.log.

And maybe an important thing: I have Czech accented letters displayed correctly in one of these cases:
1) $_internal_char_set = "cp852" in dosemu.conf and then I not need any "display con=(ega,437,2)"/"mode con codepage prepare=((852) f:\cpi\ega.cpx)"/"mode con codepage select 852" in autoexec.bat

2) or I have no $_internal_char_set in dosemu.conf, and then I need display con/mode con stuff in autoexec.bat

**Comment by stsp** [comment]
> Are you saying that I don't have the $_external_char_set/$_internal_char_set option used in the dosemu.conf,
> that the program will advise me something?

Yes, that should be the case.

**Comment by stsp** [comment]
Ok, just put the output of `locale`
command here, as I suppose that's
gonna be faster than any other route. :)

**Comment by fhanzlik** [comment]
I have set it to en_US - when i report some Linux problem, I don't have to translate error messages from Czech to English.

$ locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=

**Comment by stsp** [comment]
This is not useful for adding Czech locale.

**Comment by fhanzlik** [comment]
Ehm, problem is where? Dosemu works great for me, I have full support for Czech and ASCII - I do not see any shortcomings. That I want one character set/language in DOS and another in Linux is probably not abnormal, is it?
Your goal is any wizard in a Dosemu that tells the user everything / offers everything / sets it ?

**Comment by stsp** [comment]
It should set these settings based
on your locale. Of course in your
case it doesn't do so, and offers
nothing.

**Comment by fhanzlik** [comment]
Aha, that explains my lack of understanding.
I have one more joke: in the Czechoslovak republic, before the expansion of the use of IBM cp852 codepage, codepage 895 (also known as KEYBCS2/MJK/čeština bratří Kamenických(borthers Kamenický Czech) was widely used and still used in many programs (or the program offers a choice between the two) - which allowed better support for semigraphic characters (various box drawing chars namely).
See eg. http://linux.fjfi.cvut.cz/~zub/cp895/  (zmiňuje i podporu v DOSEMU ;)  or https://en.wikipedia.org/wiki/Kamenick%C3%BD_encoding
Dosemu still support it: src/plugin/extra_charsets/cp895.c
So I always specify the page in the dosemu.conf anyway...

**Comment by stsp** [comment]
I was entirely shocked by
the fact that running
`LANG=cs_CZ.UTF-8 dosemu`
already allows me to see the Czech
letters, even w/o any patches!
I even thought that dosemu2 got
some AI and is learning things
without me even coding them in.
It appeared almost so.
When I run it that way, then my
usual cp866 is no longer used,
and cp437 is. It appears cp437
has many accented letters within,
and dosemu2 was choosing the
best approximations from 437.
So the closer look revealed they
do not always look exactly the same,
but since I never deal with accented
chars, it was difficult for me to
spot the difference initially.

**Comment by andrewbird** [comment]
I'll recheck with Spanish keyboard in a couple of days when I return home, but certainly the `real fixes` you mentioned look likely to fix the issues I saw before with dead key shifted letters, and pasting too.

**Comment by andrewbird** [comment]
##### SDL
Spanish keyboard works fine generating dead key shifted letters `É` etc
Pasting Spanish characters `éñÉÑ` into the dosemu SDL window works file too.

##### X
Spanish keyboard generates dead key shifted letters `É` etc, but dead key does produce 'ERROR: $_layout inconsistency' in terminal. I suspect this is due to my having LANG and LANGUAGE variables still set to en_GB as when I set them to es_ES the message doesn't appear.
Pasting Spanish characters `éñÉÑ` into the dosemu X window works file too.

**Comment by stsp** [comment]
> when I set them to es_ES the message doesn't appear.

Is this with $_layout commented out?

**Comment by andrewbird** [comment]
It's the default config file, no customisation.

**Comment by stsp** [comment]
Was ES layout properly detected?

**Comment by andrewbird** [comment]
Yes, it detected es-latin1

**Comment by stsp** [comment]
Could you please try the patch I
pushed to the separate branch?

**Comment by andrewbird** [comment]
Yes that works nicely
~~~
Using closest match (es-latin1) for scan/virtual codes mapping.
CONF: detected layout is "es-latin1"
CONF: detected alternate layout: uk
KBD: probing 'X11' mode keyboard client
KBD: initialising 'X11' mode keyboard client
KBD: Keyboard init ok, 'X11' mode
~~~
Spanish keyboard generates dead key shifted letters É etc and no warning message even though LANG set to en_GB.
Pasting Spanish characters éñÉÑ into the dosemu X window works file too.

**Comment by stsp** [comment]
So should now be fixed.
I applied a slightly modified patch,
but it should be the same thing.

**Comment by andrewbird** [comment]
The new patch is working fine, thanks.

**Comment by fhanzlik** [comment]
I just tried DOSEMU2 45bb94cc.
With default dosemu.conf, no .dosemurc, default autoexec.bat (fdautoem.bat in my case of FreeDOS) without any "display con=("/"mode con codepage ...", and run "LANG=cs_CZ.utf8 dosemu -X" in X terminal I have in boot.log:
...
loading fonts for cp852
VID: initializing video X
X: X_init
Registering HWRAM, type=e base=0x4b1e8000 size=0x400000
CONF: reserving 4096Kb at 0x4B1E8000 for 'e' (VGAEMU LFB)
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
Warning: Your fluidsynth is too old
DPMI: mem init, mpool is 140468224 bytes at 0x42bf2000
Warning: Using DPMI inside KVM
CONF: detected layout is "auto"
CONF: detected alternate layout: cz-qwerty
...

and I can in DOS without problem type all US ASCII and Czech letters, both those directly on keyboard and with dead keys (caron and accute). Very nice! Thanks!

One small cosmetic bug, perhaps unrelated to this issue (but I mentioned it above): mouse cursor disappear.
According my observations, this happens immediately when the SHIFT key is released. This may be the first key pressed after starting DOSEMU. It remains invisible, but appears while the SHIFT key is pressed. 
Should I report it as another, independent issue?

**Comment by fhanzlik** [comment]
Hi Stas, thank You for the clarification. So this means, that the mouse (including cursor visibility) in X no longer works automatically (as it was before), but must be explicitly enabled with emumouse command in DOS autoexec.bat? (and visibility with pressed any SHIFT key is only nice bonus)

I think it's because of the unification with the SDL mode. But then it is IMO necessary to correct the documentation, in src/doc/README/mouse is stated:
Under X, or in terminal mode, you don't need to do anything,
...
On the console, in text mode, without root, the GPM library can be used,
and no extra setup is necessary.
...
Now I tried it with "emumouse 3 c 1" in fdautoem.bat - and mouse cursor is visible and it seems OK.
Thanks.

**Comment by stsp** [comment]
Its all the same.
Its already in fdautoem.bat, so
is still automatic.

**Comment by fhanzlik** [comment]
Hm, I assume that the text I mentioned in the src/doc/README/mouse  file does not deal with DOS, but only with DOSEMU.
I think that earlier DOSEMU in X mode displayed the mouse cursor without having to have a emumouse line in the autoexec.bat file or anything else on the DOS side.
I'm not entirely sure, but I can try it tonight. Anyway, it's probably not important - more importantly, the behavior is consistent with the documentation - which is probably not easy either, given what has changed "under the hood" of the program over the 25+ ?? years ;)

**Comment by stsp** [comment]
There is no any inconsistency with
documentation. Documentation does
not say whether or not the mouse is
going to be visible after boot.
The only thing documentation says
(which is also quite obvious) that
the mouse is going to be visible in
any DOS programs.
