### ISSUE TITLE
problem with entering strings with accented characters via clipboard. 

### ISSUE THREAD

**Issue by fhanzlik** [dosemu2/dosemu2#1546]
When I in Linux somewhere (document etc.) grab text with some accented characters, e.g.:

"Červená še Žežulička, Ámosův příliš žluťoučký kůň úpěl ďábelské ódy, ĎÓŘÉMÍ."

(all are supported in CP852 DOS charset) into Linux primary clipboard and try insert it into dosemu2 DOS window, it has two problems:
1) characters with diacritics are inserted incorrectly
2) insertion depends on actually selected Linux keyboard layout:

When actual Linux keyboard layout is "English(US)" :
C:\>+Cervená še +Ze6ulička, Amos;v p59li3 žluťou4k7 ků+n [pěl +d8belské dy, +DO+REMI.
C:\>+Cervená 3e +Ze6uli4ka, Amos;v p5íliš 6luťou4k7 k;+n [p2l +d8belsk0 dy, +DO+REmI. 
^^When Linux keyboard layout switched to "Czech(QWERTY, extended backslash)" : ^^
(on Czech keyboard, "š" is same key as "3" on US,
"č" is same key as "4" on US,
"í" same key as "9" on US,
"ž" same key as "6" on US,
"ů" same key as ";" on US,
"ě" same key as "2" on US,
"é" same key as "0" on US)
I have no idea, why is letter "M" (third from string end) different once and then (uppercase vs. lowercase).

**Comment by stsp** [comment]
I think `$_layout` was not properly set also here.

**Comment by fhanzlik** [comment]
Tried with a00446521 git version: some accented letters (exactly these, which are not directly on keyboard keys in cz_qwerty layout) are inserted incorrectly - see attached printscreen. Text, which I copy from some text editor (Pluma, Gedit,..):
;~019@#ěšžýáúůÉÝÚÍÓÁťďňĚŘĎŽČŇěřáóčšíýúůÉÝÚÍÓĚŤŠŽŇ


[copy_primary_clipbd](https://user-images.githubusercontent.com/9540755/140654698-3865f4f5-eafc-4c0f-9257-dc86f7c4199f.png)

**Comment by stsp** [comment]
Is $_layout set properly?

**Comment by stsp** [comment]
And if so - can all these chars be
typed by the keyboard?

**Comment by fhanzlik** [comment]
layout I have set as '$_layout = "us,cz-qwerty"'. And - yes, all these characters I can type on keyboard, accented when switching to cz-qwerty. What is interesting and maybe important: characters, which are pasted correctly, are these, which are directly on Czech keybord. Pasted incorrectly are these, which must be typed using dead keys (caron or acute).
Pasting behaves independently on actual keyboard layout (which is IMO desirable).

And for completeness, copy and pasting in the reverse direction (when I type from keyboard or from file any character, ASCII or Czech, in DOS and then select it on DOS window by mouse lclick over and then paste it in Linux /eg. in pluma, gedit or so/) works well.

**Comment by stsp** [comment]
> Pasting behaves independently on actual keyboard layout (which is IMO desirable).

This may not be the case.
Try `$_layout = "cz-qwerty"` only
and see if pasting works the same
way as before.

**Comment by fhanzlik** [comment]
With $_layout = "cz-qwerty" only pasting works quite right. Problem is only when two layouts are specified.
PS: I have also '$_external_char_set = "utf8"'  and '$_internal_char_set = "cp852"' in dosemu.conf, in all tests.

**Comment by fhanzlik** [comment]
I now tried also without explicitly defined $_layout in dosemu.conf, and now test it with copy command (as 'copy con: fileSpec'). I did several same text pasting, after each past I manually typed <Enter> in DOS. Result see on attached screenshot: although all lines should be same, they aren't. Seems as something in dosemu is overwrited or so.
Also, after pasting some line, mouse cursor disappears, permanently.
Again, I pasted string:

;~019@#ěšžýáúůÉÝÚÍÓÁťďňĚŘĎŽČŇěřáóčšíýúůÉÝÚÍÓĚŤŠŽŇ

![multiple_paste_without_layout_specified](https://user-images.githubusercontent.com/9540755/140665488-652ae3ca-06f4-435d-80a2-d51ecb69c596.png)
.

**Comment by stsp** [comment]
Should now be fixed.
Please use new tickets if
you find more oddities.

**Comment by fhanzlik** [comment]
Can confirm, from my tests, pasting now works correctly.
Again, many thanks for your efforts!
