### ISSUE TITLE
Street FIghter 2 crashes (RTC timer irqs)

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#155]
When I run Street Fighter 2 Championship Edition in dosemu, it appears at least some sound effects are not played at the right speed. In dosbox these do sound correctly.
It's easy to reproduce when you pick Ken and do a combo such as right right punch.

More info about the game:
I can't find anything online about the DOS version anymore, the original link here died.

**Comment by stsp** [comment]
Please add the `-D9+S` log, closing dosemu
when bad sound is currently playing.

**Comment by jschwartzenberg** [comment]
When I try this now, the sound even completely disappears after around 10 seconds. When I try it with -D9+S the game hangs or locks up  when the fight is about to start. So I can't reproduce the sound effect then.

**Comment by stsp** [comment]
Regression?

**Comment by jschwartzenberg** [comment]
The strange low slow sounds no, it also happens in 1.4. The sound doesn't disappear in 1.4 though, so that's a regression.

**Comment by stsp** [comment]
Of course the most interesting is to bisect
the logging crash. The rest can be fixed with
the log. :)

**Comment by stsp** [comment]
Hmm... There are not only sound artifacts!
The game looks full of problems on latest
dosemu. I'll bisect later.

**Comment by stsp** [comment]
This regressed at 5ee681aa, which
means I can do very little about this,
except maybe adding an option that
restores the original behaviour.
Anyway, not a recent regression, so
not holding pre8.

**Comment by stsp** [comment]
I added the "pic_revert" branch where I
did a very dirty revert of 5ee681a, and sf2
now is stable. But there is some strange
flicker at the top of the screen sometimes,
so probably other regressions exist.

**Comment by stsp** [comment]
As for sound problems: it uses direct
DAC access. The rate problem therefore
can't be fixed. :(

**Comment by stsp** [comment]
The flicker is avoided if in setup you
choose ` Video Timing 0`.

**Comment by jschwartzenberg** [comment]
This should probably be documented in emufailure then.

**Comment by stsp** [comment]
Maybe we can add an option to select
the sound frequency for every game that
uses direct DAC access. Try chaning the
`DAC_BASE_FREQ` const in dspio.c
(maybe also changing in dspio.c:312
from `PCM_FLAG_RAW` to `PCM_FLAG_SLTS`
would be needed). If you can find the
freq that suits to this game, then maybe
we can go this way instead of emufailures.

**Comment by stsp** [comment]
For example the following seems to
give the perfect sound:
```
diff --git a/src/base/dev/sb16/dspio.c b/src/base/dev/sb16/dspio.c
index 925d4f4c0..1d5872768 100644
--- a/src/base/dev/sb16/dspio.c
+++ b/src/base/dev/sb16/dspio.c
@@ -45,7 +45,7 @@
 #include <assert.h>
 #include <math.h>
 
-#define DAC_BASE_FREQ 5625
+#define DAC_BASE_FREQ 8000
 #define PCM_MAX_BUF 512
 
 struct dspio_dma {
@@ -309,7 +309,7 @@ void *dspio_init(void)
     pcm_set_connected_cb(dspio_is_connected);
     pcm_set_checkid2_cb(dspio_checkid2);
     state->dac_strm = pcm_allocate_stream(1, "SB DAC", (void*)MC_VOICE);
-    pcm_set_flag(state->dac_strm, PCM_FLAG_RAW);
+    pcm_set_flag(state->dac_strm, PCM_FLAG_SLTS);
     state->dma_strm = pcm_allocate_stream(2, "SB DMA", (void*)MC_VOICE);
     pcm_set_flag(state->dma_strm, PCM_FLAG_SLTS);
 
```

**Comment by stsp** [comment]
Sound should now be much better.
Don't forget to do
`git cherry-pick pic_revert`
to get the game working at all.

**Comment by stsp** [comment]
It appears the sound in SF2 is
generated by the RTC timer, not PIT.
That means it is not going to be fixed
by #1588 ... or at least not that simple.

**Comment by stsp** [comment]
Do you still have this "champion edition"
version? I can only download the japaneese
one, and it seems to have some problems
under dosemu2 these days.

**Comment by jschwartzenberg** [comment]
I am not sure. I don't think I deleted it, but I will have to do some digging and see...
