### ISSUE TITLE
JIT is slow, time outs at start, caused by a SIGSEGV.

### ISSUE THREAD

**Issue by robert-j** [dosemu2/dosemu2#1557]
**Describe the bug**

I'm running dosemu with

$_cpu_vm = "emulated"
$_cpuemu = 0

Whenever I'm starting a Borland DPMI (16-bit) program, a time out of about 2-3 seconds occurs
(it depends on the size of the program).

The time out is most likely caused by the GDB backtrace being logged to boot.log.
The issue is the SIGSEGV, of course.

**To Reproduce**

Run the supplied "test.exe".

[jittest.zip](https://github.com/dosemu2/dosemu2/files/7661632/jittest.zip)

**Attach the log**

[boot.log](https://github.com/dosemu2/dosemu2/files/7661635/boot.log)

**A regression?**

Likely. I've updated today to 2.0~pre8-7133-0d3f410dc+202112060502~ubuntu21.04.1
from a version from October.

**Comment by stsp** [comment]
This only happens with
`$_cpu_vm_dpmi = "emulated"`
not with `$_cpu_vm = "emulated"`

**Comment by stsp** [comment]
Should now be fixed, thanks.
