### ISSUE TITLE
State of ctmouse support

### ISSUE THREAD

**Issue by bolle732** [dosemu2/dosemu2#1561]
The TODO file states, that the support for the mouse wheel should be implemented as by ctmouse. Is this really still missing or incomplete ?

I ask here, because there is a new CuteMouse driver for PC/GEOS which works fine in DOSEMU2 out of the box. The source code can be found here:

https://github.com/bluewaysw/pcgeos/tree/master/Driver/Mouse/ [ctm | ctmabs | imps2]

Maybe, the entry in the TODO file can be updated or removed.

**Comment by stsp** [comment]
Yes, I completely forgot that we
still have that TODO file. It should
probably be removed, as now we
use github milestones.
I removed the outdated entries now.
Were you able to fix other GEOS
incompatibilities?

**Comment by bolle732** [comment]
There is a new VESA driver which is much more stable. Especially in higher resolutions like full HD.

**Comment by bolle732** [comment]
The only problem I'm aware right now is with the serial driver. But no one cares at the moment.

**Comment by stsp** [comment]
Is there a package I can try out?
