### ISSUE TITLE
set up COUNTRY settings

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1579]
As fdpp now has the built-in country
support, we need to start using it.

**Comment by andrewbird** [comment]
Do you think it might be possible to build it dynamically for FDPP from the host system? My machine has this
~~~
$ locale -c -k LC_MONETARY
LC_MONETARY
int_curr_symbol="GBP "
currency_symbol="£"
mon_decimal_point="."
mon_thousands_sep=","
mon_grouping=3;3
<snip>
~~~

But I've no idea what calls locale makes to obtain that info.

**Comment by stsp** [comment]
No dynamic building.
I only want to dynamically set
COUNTRY=ctry,cp
as it seems to be enough for fdpp now.

**Comment by stsp** [comment]
Hmm...
I suppose we now need to tag new
fdpp release and raise the deps, as
this feature won't work with anything
that was tagged to the date.
