### ISSUE TITLE
Remember earlier text mode when switching in and out of graphic mode?

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1589]
This is a very specialized request:

If I run this command before starting WordPerfect for DOS:

`xmode -mode 81`

the window changes to 80 cols x 43 lines, and WPDOS starts up with an 80x43 window.

If I then use Shift-F7, V, to get a graphics mode print preview in WPDOS, and then press F7 to exit the screen preview, the text mode reverts to 80x25. 

Is it possible for dosemu2 to remember the most recent text mode when switching in and out of a graphic mode, and then return to that that text mode?

Alternatively, could we someday have a way of setting the number of text rows/columns of the dosemu2 window when it starts up, so that it could use that setting as the default for that session? This might be another way to solve the problem.

I know that I can have any row/column setting if I start dosemu2 in terminal mode, but I can't use any graphic feature (like print preview) if I run WordPerfect in terminal mode.

Thanks for considering these questions. I know they're not urgent.

**Comment by stsp** [comment]
The problem is not dosemu2 not remembering
something. The problem is that WP doesn't.
It sets default mode 3 and not the mode that
was previously set.

**Comment by emendelson** [comment]
I'm sorry to take so long to reply. Under DOSBox-X, WPDOS 6.x returns to the previous window size. If I run DOSBox-X (with output=ttf) and use the command

`mode con lines=43`

and then open WPDOS 6.2 in a 43-line window, and then use print preview, and then return to text mode, WP returns to the 43-line screen, not a 25-line screen.

I think (but am not certain) that DOSBox-X has code that remembers the text mode when switching in and out of graphic mode. Is it possible that (someday) dosemu2 might be able to do this also?

**Comment by stsp** [comment]
WPDOS doesn't remember mode.
He explicitly sets mode 3, not the previous
mode. This is a fact that can't be changed
by the "can dosemu2 remember the mode"
question.
Can WP remember the previous mode
instead of explicitly setting mode 3?

> mode con lines=43

That one changes font size, not mode.

**Comment by stsp** [comment]
libi86 test failed again, Andrew any idea?

**Comment by stsp** [comment]
OK I tried to remember the font size
in some situations.

**Comment by andrewbird** [comment]
@stsp I suspect it may be ia16-gcc toolchain related, even the head of libi86 has been failing for the last few days see https://github.com/tkchia/libi86/actions

**Comment by emendelson** [comment]
@stsp - In DOSBox-X, with the output set to ttf, the command 

`mode con lines=43`

preserves the font size, and changes the window size. With non-ttf output, it changes the font size, not with ttf output.

**Comment by stsp** [comment]
This doesn't matter because technically
mode con lines=43
only changes the font size (and adjusts
scanline number accordingly).
How dosbox implements that in practice,
is an implementation detail.
What matters is that dosbox remembers
that setting across mode changes, so in
that case we can do that too.

**Comment by emendelson** [comment]
Still returns to 25-line text mode after opening in a 43-line window and opening Print Preview.

**Comment by stsp** [comment]
I tried with mode.com from freedos
and from pc-dos, and in both cases
things worked as expected.
@taviso maybe you can check if
mode con lines=43
now permanent even when wp switches
to graphics mode and back?

**Comment by emendelson** [comment]
No luck with xmode; will copy freedos mode and try later.

**Comment by stsp** [comment]
Who said there would be any luck
with xmode? I told you many times
that WP doesn't remember previous
mode. That makes xmode out of the
picture.

**Comment by emendelson** [comment]
Ah - I understand (finally!!!)

**Comment by emendelson** [comment]
... and confirming that this works exactly as you say when I use freedos mode.com to set the line numbers. Thank you!
