### ISSUE TITLE
mouse broken in WP62

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1590]
Almost doesn't move vertically.
Horizontal movement is fine,

**Comment by stsp** [comment]
Seems to have regressed after a (correct) #1517 fix.

**Comment by stsp** [comment]
@emendelson I am surprised you haven't
said mouse in WP62 is broken for half an year...

**Comment by emendelson** [comment]
That's because I don't use the mouse in WP...! But I'll check on it regularly now.

**Comment by emendelson** [comment]
I'm running Linux in a VMware VM, and the mouse doesn't work in WP 6.x at all. I have the driver set to MOUSE.COM, but left-click and right-click both do nothing. Maybe it needs real hardware? I can set that up if needed.

**Comment by stsp** [comment]
You need "absolute/pen", not mouse.com.
