### ISSUE TITLE
Y-mouse position wrong at 80x43/50 text mode for example in BorlandPascal IDE

### ISSUE THREAD

**Issue by MGreim** [dosemu2/dosemu2#1593]
**Describe the bug**
Since version 2.0~pre9-7307-f649aec31+202202210216~ubuntu20.04.1 and also in the version before
the y-position of the cursor in the text mode 80x43 is about 50% too wide in the north. 
So any click in the window sets the x-position right, but the y-position to y/2. 
The x position is always ok. 
Everything is fine in the 80 x 25 text mode. 
Tested with BorlandPascal IDE in 80x43 mode (wrong) and Paradox 4.0 in the 80x25 mode (working fine). 

The mouse cursor works fine in the versions before!

**To Reproduce**
Open BorlandPascal 7.02
place the mouse cursor anywhere -> everything is fine. 
Now switch the IDE to 80x43 in Options-Environment->Preferences
No the y-mouse position will be wrong. 
Return to 80x25 -> everything will be fine again. 

**Attach program/game binaries or provide an URL**
n/a

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.

**A regression?**
this problem came up about 10 days ago. 

**Additional info**
Please write here if you did any dosemu2 setup
customizations, like installing any custom DOS
or command.com, or altering the dosemu2
configuration settings. Note that freedos, even
from dosemu-freedos package of dosemu1, counts
as a custom DOS and should be mentioned here.
Also make a note if it is a protected or real-mode
program. If you suspect any particular dosemu2
component (DPMI, PIC, PIT etc) to be responsible
for the problem, please write.
[boot.log](https://github.com/dosemu2/dosemu2/files/8111160/boot.log)
[boot.log](https://github.com/dosemu2/dosemu2/files/8111165/boot.log)

**Comment by stsp** [comment]
Thank you!
Bisect: 2d190d65

**Comment by stsp** [comment]
Problematic change reverted.
Should now work.

**Comment by MGreim** [comment]
Perfect! I have tested it and it works!
Many thanks, very helpful. 
Markus
