### ISSUE TITLE
Terra Nova game uses 100% CPU and is visibly choppy.

### ISSUE THREAD

**Issue by uralets** [dosemu2/dosemu2#1599]
**Describe the bug**
Subj.

**To Reproduce**
Install the game inside DOSEMU.
Launch the game.
Launch top while running the game.

**Attach program/game binaries or provide an URL**
https://www.***-games.ru/game/download/get.php?fileid=6353&modal=1

**Attach the log**
Done.

**A regression?**
No idea.

**Additional info**
OS Ubuntu 20.04 Focal
Kernel Linux 5.16.10
CPU AMD FX-6100 @ 4.5GHz
GPU Radeon HD 7770
MESA 21.3.7~kisak1~f

Ubuntu packages from https://launchpad.net/~dosemu2/+archive/ubuntu/ppa are used.

Launching with FDPP

**DOSBOX-staging (https://dosbox-staging.github.io) uses less and is relatively smooth.** Even in game using the higher resolution setting (looks noticeably better so it does work). See the attached screenshots.
No custom /etc/dosemu/dosemu.conf or ~/.dosemurc. No userhook.bat or any other custom init files.

Might copy over all the data from the disc image and edit out references to it in the game's tn.conf - so no mounting inside DOSEMU is even needed.

Using the game-generated univbe driver or setting available XMS/EMS to 16 meg instead of 8 doesn't seem to make any difference.

[boot.log](https://github.com/dosemu2/dosemu2/files/8208086/boot.log)
![Снимок экрана в 2022-03-08 17-06-12](https://user-images.githubusercontent.com/45916341/157287670-849a6fd2-a992-486a-afcc-57a1a88cea4a.png)
![Снимок экрана в 2022-03-08 21-41-22](https://user-images.githubusercontent.com/45916341/157288004-1ddd52ae-5923-452d-8ee3-b1b113035579.png)

**Comment by stsp** [comment]
And if configured with General Midi,
then on my system it eats 120% of CPU -
20 goes to the midi synth.
But I can't tell if the game is "visibly choppy".
How should I see that?

**Comment by uralets** [comment]
> And if configured with General Midi,
> then on my system it eats 120% of CPU -
> 20 goes to the midi synth.
> 
As I mentioned in my other issue I have a hardware MIDI synth onboard
my soundcard - just no idea how to properly tell DOSEMU2 to use it.
But it's a moot point anyway - the performance issue exists regardless
of what MIDI output is set up inside the game.

> But I can't tell if the game is "visibly choppy".
> How should I see that?
> 
I'm not sure what the demo allows you to do (I'll have to dl it and try
out - if you aren't too squeamish you could get the full iso via the
link I've provided (*** == old)

In full version at least you can start a new game, then proceed to a
tutorial - which starts the actual gameplay.

Hmm... While I'm testing again as I'm writing this I'm noticing that
when I have DOSEMU2 in a window the game seems to work OK, even if I
set the higher resolution in the options. But when I switch to
fullscreen, especially with the "high" resolution on it's dog slow.
Now, I thought SDL2 hardware scaling would take care of that?? Again,
the high CPU usage is there, regardless of fullscreen or windowed. And
DOSBOX works OK in both cases, all the while using less CPU.


For reference here's the DOSBOX output while launching and playing
around a bit (notice it does the right thing in regards to scaling,
going fullscreen with DOSEMU2 just stretches the image w/o regard for
aspect ratio, let alone I guess respecting square/non-square pixels):

dosbox-staging version v0.76.0-1+ubuntu20.04
---
CONFIG: Loading primary file /home/user/.config/dosbox/dosbox-
staging.conf
OPENGL: Pixel buffer object extension: available
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
SDL: Mouse will move seamlessly without being captured.
MEMORY: Base address: 0x7f7052fff010
MEMORY: Using 4096 DOS memory pages (16 MiB)
RENDER: Using GLSL shader 'default'
MIXER: Negotiated a 44100-Hz output rate and 1024-byte blocksize
ALSA: Client initialised [17:0]
MIDI: Opened device: alsa
MIXER: FM channel operating at 44100 Hz without resampling
MIXER: SB channel operating at 22050 Hz and upsampling to the output
rate
MIXER: SPKR channel operating at 18939 Hz and upsampling to the output
rate
MIXER: DISNEY channel operating at 10000 Hz and upsampling to the
output rate
MAPPER: Found no joysticks
MAPPER: Loaded default key bindings
MOUNT: Path '.' found
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's
options.
MAIN: Draw resolution: 320x200, double-width, double-height, pixel
aspect ratio: 1.20
SB16: DSP was reset
SB16: Suppressed initial 1-byte non-DMA transfer
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Draw resolution: 320x200, double-width, double-height, pixel
aspect ratio: 1.20
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Draw resolution: 320x200, double-width, double-height, pixel
aspect ratio: 1.20
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
SDL: captured the mouse
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
SDL: released the mouse
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
SDL: captured the mouse
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
SDL: released the mouse
^[^NMAIN: Draw resolution: 640x400, double-width, pixel aspect ratio:
1.20
SDL: captured the mouse
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
SDL: released the mouse
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
SDL: captured the mouse
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Draw resolution: 320x200, double-width, double-height, pixel
aspect ratio: 1.20
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
MAIN: Draw resolution: 640x400, double-width, pixel aspect ratio: 1.20
SDL: released the mouse

**Comment by stsp** [comment]
> my soundcard - just no idea how to properly tell DOSEMU2 to use it.

Hmm, try this in ~/.dosemu/.dosemurc
(yes, different path):
$_midi_driver = "alsa_virmidi"
That seems to be undocumented, not
sure why. If that works, it should be
mentioned in dosemu.conf.

**Comment by stsp** [comment]
> fullscreen, especially with the "high" resolution on it's dog slow.

Try disabling $_X_lin_filt/$_X_bilin_filt

**Comment by uralets** [comment]
I'm giving up for now, it's late and I'm a bit tired. I'll get back to
ya tomo.

**Comment by stsp** [comment]
I did a few changes to help with that.
Also please see if $_SDL_hwrend helps.
It may not work properly, but perhaps
the right time is to get it fixed. There is
no other way to speed up SDL post-processing.
