### ISSUE TITLE
Program made in clipper crashs on shared-folder Windows mounted on linux.

### ISSUE THREAD

**Issue by ojrcampos** [dosemu2/dosemu2#1606]
Program made in clipper does not run in shared folder on windows network.

In a local folder works perfectly. But in a shared folder on windows and mounted on linux the program crashes every time when I run the .exe file.

**Comment by jschwartzenberg** [comment]
There might be a hint in the log file. Could you provide the program?

**Comment by stsp** [comment]
Lets close this until the ticket
is properly filled.
