### ISSUE TITLE
wordperfect dos 6.2 freezing at startup

### ISSUE THREAD

**Issue by hightechsister** [dosemu2/dosemu2#1607]
**Describe the bug**
When trying to start wordperfect 6.2 for dos, startup gets stuck at the Corel WordPerfect 6.2 title screen and just stays there.
![wp62stuck](https://user-images.githubusercontent.com/37092155/160273100-654de7b0-91b9-46bc-a3f5-f8f0486e7bec.png)

**To Reproduce**
c:\> corel\wp62\wp

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8357150/boot.log)

**A regression?**
It was working before on 2.0~pre8-7256-6426f4896+202201251932~ubuntu21.04.1

**Comment by stsp** [comment]
Bisect: 77177b04b

**Comment by stsp** [comment]
WP masks all interrupts except
timer and kbd, which also masks
vtmr...
That sucks!

**Comment by stsp** [comment]
Multiple problems actually.
WP communicates with timer handler
via stack, but vtmr's stack gets hooked
to the DOS STACKS.

**Comment by stsp** [comment]
Fixed a few problems.
Still unclear how to fix rest...

**Comment by stsp** [comment]
Should now be fixed.
Thanks!

**Comment by hightechsister** [comment]
Thanks so much for looking into this issue!
