### ISSUE TITLE
Regression: -dumb mode is now line buffered where it wasn't before

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1614]
**Describe the bug**
In the `-dumb` I/O mode we used to get keypress by keypress input to the DOS application. In particular this enabled using lDebug's DCO1 flag 800h to enable line editing mode. It also means the DOS application can detect and handle Control-C.

**To Reproduce**
Download keybtest.com from https://pushbx.org/ecm/test/20220413.com or the repo at https://hg.pushbx.org/ecm/keybtest (requires lmacros to build). Run the executable using `dosemu -dumb`. Press keys such as Up arrow, Left arrow, Down arrow, Right arrow, Ctrl-C, then Enter. (Pressing Enter (CR) makes the test program end itself.)

Here's the output from my current default dosemu:

```
Welcome to dosemu2!
    Build 2.0pre8-20191102-1332-g9cf2b7560
About to Execute : keybtest.com
About to Execute : keybtest.com
011B
1A5B "["
1E41 "A"
011B
1A5B "["
2044 "D"
011B
1A5B "["
3042 "B"
011B
1A5B "["
2E43 "C"
2E03
```

Here's the output from current most recent commit of dosemu2, just built today:

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20220331-118-gadb226f4f
^[[A^[[D^[[B^[[C^C
Terminated with signal 2
```

Note how the Control-C makes dosemu terminate itself. Here's a run of just Up, Left, Down, Right, Enter:

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20220331-118-gadb226f4f
^[[A^[[D^[[B^[[C
011B
1A5B "["
1E41 "A"
011B
1A5B "["
2044 "D"
011B
1A5B "["
3042 "B"
011B
1A5B "["
2E43 "C"
```

Note that this displays the control character sequences in some way, and line buffers them until Enter is pressed. The DOS application only sees the "full line".

Here's the output of the full sequence from the dosemu2 commit before [the one that changed stdio handling recently](https://github.com/dosemu2/dosemu2/commit/7f9163c1f43e9180920818819e97f9554f52dab2). It works as expected.

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20220330-111-g09cba86f1
011B
1A5B "["
1E41 "A"
011B
1A5B "["
2044 "D"
011B
1A5B "["
3042 "B"
011B
1A5B "["
2E43 "C"
2E03
```

**A regression?**

Worked before https://github.com/dosemu2/dosemu2/commit/7f9163c1f43e9180920818819e97f9554f52dab2

**Comment by stsp** [comment]
If you need non-dumb features,
just don't use `-dumb`. Use `-td -kt`
instead. This is compatible with any
dosemu version.

It would be more productive to see
how the native DPMI now crashes
at your VM.

**Comment by ecm-pushbx** [comment]
Why can't you leave `-dumb` as is and allow explicit `-td -ks` for the new behaviour?

I'll get back to the native DPMI problem on the new kernel, today or tomorrow.

**Comment by stsp** [comment]
Exactly for the reason of ^C:
in dumb mode it should terminate
dosemu, as otherwise there is no
way to terminate it if it hangs, other
than to send signal from another
terminal. In all other modes you
have some way of terminating, and
in dumb mode that should be ^C.
Besides, why do you want an
incompatibilities with some versions,
if `-td -kt` always works?

**Comment by ecm-pushbx** [comment]
> Besides, why do you want an incompatibilities with some versions,

I don't understand what you mean by incompatibilities. I want `-dumb` to remain `-td -kt` the same way it used to be (hence regression). You want to change it to `-td -ks` which from my perspective is introducing an incompatibility.

DPMI native problem on our server created in https://github.com/dosemu2/dosemu2/issues/1615

**Comment by ecm-pushbx** [comment]
> In all other modes you have some way of terminating

Not really relevant but I wonder what are these ways of termination in other modes? The only way I know of is when you use an SDL or X window to close the graphical window.

**Comment by stsp** [comment]
In most back-ends Ctrl-Alt-PgDn is
a shutdown and Ctrl-Alt-* is a reboot.

But lets re-open this for the sake of
line-buffered output. How should I
see it actually is?

**Comment by ecm-pushbx** [comment]
I don't understand your last question.

**Comment by ecm-pushbx** [comment]
I meant the input is line buffered with `-td -ks`. Not the output. As in, DOS only gets a "full line" of input. The Escape sequence is buffered until I press Enter, then the entire "line" is sent to DOS.

**Comment by ecm-pushbx** [comment]
Different example for the line buffering of the input, using keybtest once again. First load the application and enter the string "abcdef":

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20220414-119-g99464dbf8
abcdef
```

DOS doesn't receive any of this yet. However, it is echoed to the terminal while entering it. Now press Enter:

```
1E61 "a"
3062 "b"
2E63 "c"
2064 "d"
1265 "e"
2166 "f"
```

The entire "line" is sent at once.

**Comment by stsp** [comment]
Ah, that's fine then.
Just do: `stty -icanon -echo ; dosemu -dumb ; stty icanon echo`

**Comment by stsp** [comment]
> I don't understand what you mean by incompatibilities.

I mean with current and some
past revisions after the change.
You have a way to avoid any
incompatibilities.
