### ISSUE TITLE
CPUEMU: stack patch failure, fix source code!

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1616]
As requested: https://github.com/dosemu2/dosemu2/issues/1615#issuecomment-1099166484

> Please open another ticket for that "stack patch failure" error.

**Describe the bug**

The boot.log file is filled with many messages reading `CPUEMU: stack patch failure, fix source code!`.

**To Reproduce**

Load up the command line interface of lDebug. Enter some random commands. Quit the debugger. (This test is based on the other ticket so it uses lDebugX and loads the dpmistck.com example. However, we need not enter Protected Mode to reproduce this log message.)

**Attach program/game binaries or provide an URL**

Executables provided in https://pushbx.org/ecm/test/20220414/

**Attach the log**

Log: https://pushbx.org/ecm/test/20220414/1528.log

Output: https://pushbx.org/ecm/test/20220414/1528.txt

**Comment by ecm-pushbx** [comment]
Note: Command line to run dosemu used:

```
dosemu -K "$PWD" -dumb -E "ldebugx.com /c='r dco or= 800;g' dpmistck.com" -I "cpu_vm_dpmi native" -I "serial { com 2 device /tmp/vptty-dos }" -td -kt
```

The latest git dosemu2 commit is used, without any patches: https://github.com/dosemu2/dosemu2/commit/99464dbf8ddf1da3b0e438b9aaa582bcb57bd7f7

**Comment by stsp** [comment]
Yes, can reproduce stack patch failure.

**Comment by stsp** [comment]
Should now be fixed.
