### ISSUE TITLE
Crash with "Fault in dosemu code, in_dpmi=0" terminating lDebugX in PM

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1620]
**Describe the bug**

Running https://github.com/dosemu2/dosemu2/commit/db595c7ea597e3ae5122ec2f7744277bcfba47a0 with `-I "cpu_vm_dpmi native"` and the `WANT_SIGRETURN_WA 1` patch, I get crashes when lDebugX's Q command is used in PM.

**To Reproduce**
Run lDebugX on the dpmistck.com example (with `/c='r dco or= 800'` to enable `rawinput`). Run the `g` command once. Run `g 211` to enter Protected Mode. Run `t10` in Protected Mode. Run `q` in Protected Mode.

Expected result: lDebugX runs PM interrupt 21h function 4Ch in Protected Mode in the debuggee's context, terminating it. [The part of the test that runs after the child process terminated](https://hg.pushbx.org/ecm/dpmitest/file/0d92e208e190/dpmistck.asm#l407) runs, displaying "Child process terminated okay", and terminates itself with V86M interrupt 21h function 4Ch. The debugger then uninstalls itself and returns to dosemu, which also terminates.

Actual result: No message reading "Child process terminated okay". dosemu crashes.

**Attach program/game binaries or provide an URL**
https://pushbx.org/ecm/test/20220423/ has ldebugx.com and dpmistck.com

**Attach the log**

Output: https://pushbx.org/ecm/test/20220423/1625.txt Log: https://pushbx.org/ecm/test/20220423/1625.log

**Comment by ecm-pushbx** [comment]
Once in PM running `g` to make the client terminate itself and return to the debugger in V86M, then the `q` command of the debugger works as expected, no crash.

**Comment by stsp** [comment]
Please use latest build.
Otherwise source line
numbers do not match and
the log is useless.

**Comment by ecm-pushbx** [comment]
Okay, building now. I tested running `q` in PM with lDDebugX running inside lDebugX, no such crash occurred.

**Comment by ecm-pushbx** [comment]
I dropped the `t10` command, just `q` in PM is enough. Output: https://pushbx.org/ecm/test/20220423/1700.txt Log: https://pushbx.org/ecm/test/20220423/1700.log

**Comment by ecm-pushbx** [comment]
`-I "cpu_vm_dpmi emulated"` crashes in the same way.

**Comment by ecm-pushbx** [comment]
`rawinput` is not needed to trigger this crash, either.

**Comment by stsp** [comment]
Probably fixed, please check.

**Comment by ecm-pushbx** [comment]
Yes, works as expected now, thanks again!
