### ISSUE TITLE
Fullscreen is shown in scaled widescreen in some conditions

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#1621]
**Describe the bug**
When dosemu is in fullscreen textmode (i.e. just showing the DOS command line) and a graphics program is started (e.g. Windows 3), the graphics program is stretched to the screen's aspect ratio, making it look ugly.

This does not happen when the graphics program is started while dosemu is in windowed mode, and then dosemu is put into fullscreen. In this case the graphics program is shown in the DOS mode's aspect ratio (usually 4:3) with black borders on the side.

This is a regression from some ancient build I was running before (8f662d4319d I think, but not sure). In the old build, the graphics would always show letterboxed (black borders on both sides of the screen). I haven't yet had time to run a regression test.

Arguably scaling the output to the monitor's native aspect ratio or even up-scaling 4:3 to match the width of the monitor instead of the height (and throw away top/bottom pixels) may be desirable in some situations, so a config option is worth a thought.

Interestingly the wrong aspect ratio stays around when switching back to windowed mode. I'll attach screenshots to compare.

**To Reproduce**
1) Use a widescreen monitor and resolution
2) start dosemu
3) put it in fullscreen
4) start a Windows or a graphical game of your choice

**Attach the log**
-D+9v boot.log coming in a further comment.

**A regression?**
Yes. It didn't happen in my almost a year old version I was using previously (well, it did all I wanted it to do... :-) )

**Additional info**
hwrend and ttf fonts don't make a difference.

**Comment by stefand** [comment]
![boxed](https://user-images.githubusercontent.com/521262/164992292-d919efe3-a239-4512-9933-8d3eb7871136.png)
![wide](https://user-images.githubusercontent.com/521262/164992309-bf8b0018-db69-4a92-a1c2-a3e9553cc774.png)

boxed.png is the way I want it to be, and how it used to be. wide.png makes everything look ugly and stretched.

**Comment by stefand** [comment]
[boot.txt.gz](https://github.com/dosemu2/dosemu2/files/8550334/boot.txt.gz)

boot.log, -D+9v

**Comment by stsp** [comment]
I don't have such monitor but
see if this helps:
```
diff --git a/src/plugin/sdl/sdl.c b/src/plugin/sdl/sdl.c
index 637d37230..f207765d0 100644
--- a/src/plugin/sdl/sdl.c
+++ b/src/plugin/sdl/sdl.c
@@ -905,7 +905,7 @@ static void SDL_change_mode(int x_res, int y_res, int w_x_res, int w_y_res)
     }
     /* set window size again to avoid crash, huh? */
     SDL_SetWindowSize(window, w_x_res, w_y_res);
-  } else {
+  } else if (!config.X_fixed_aspect || is_text) {
     SDL_GetWindowSize(window, &w_x_res, &w_y_res);
   }
   if (config.X_fixed_aspect) {
```

**Comment by stefand** [comment]
You didn't buy a monitor or laptop in the past 15 years?

Anyhow, the patch seems to work :-)

**Comment by stsp** [comment]
> You didn't buy a monitor or laptop in the past 15 years?

Indeed.
I am on Phenom2 CPU now, and
MultiSync 1980SXi monitor. :)
In 1980, not too many people had
2 PCs at home, so this is probably
the only monitor model in the world
that has 1 DVI-d input, and 1 DVI-i
input that works only in DVI-a mode.
I recently had a very lengthy challenge
of converting hdmi into DVI-a. :)

**Comment by stsp** [comment]
So I am not only coding the
retro-computing emulators, but
am actually using the retro-computing
HW.

**Comment by sjnewbury** [comment]
This bug seems to have returned despite the commit being present, at least when using Sway.  Is there any particular reason why fixed-aspect doesn't apply to text modes too anyway?

**Comment by stsp** [comment]
That's not text modes.
IIRC this `is_text` means that we
render ttf for text, rather than the
DOS font rasterization. For ttf
rendering the aspect is maintained
by the font metrics.

I can't reproduce the problem under
X. Can you check if it is wayland-specific?

**Comment by stsp** [comment]
So it really had to be named
`is_ttf_text` to avoid the confusion.

**Comment by sjnewbury** [comment]
> That's not text modes. IIRC this `is_text` means that we render ttf for text, rather than the DOS font rasterization. For ttf rendering the aspect is maintained by the font metrics.
> 
> I can't reproduce the problem under X. Can you check if it is wayland-specific?

Never mind, it was due to Olivier  Fourdan's hidpi scaling patchset I had applied to Xwayland.  I built a new vanilla Xwayland and it's back to normal.  Not sure why it caused this, probably a bug in the patchset when fullscreen.  I hadn't noticed previously since I usually start with "dosemu -S" which isn't affected since I use the wayland sdl driver.

**Comment by stsp** [comment]
`-S` is the default, so noting should change.
Good to know things work properly on
wayland, as so far I only did the minimal
wayland testing under qemu.

**Comment by sjnewbury** [comment]
That's odd, it's not defaulting to `-S` here.  If I unset DISPLAY "dosemu" just runs in the terminal.   "dosemu -S" works as expected.

**Comment by stsp** [comment]
Unsetting DISPLAY causes X driver of SDL
to fail. For me, unsetting DISPLAY leads to
the use of the Wayland SDL driver.

**Comment by sjnewbury** [comment]
What I meant is if `-S` is default, why is it defaulting to X11? (not SDL)

I would expect X11 output to fail with DISPLAY unset, I was just demonstrating that it was defaulting to X11.

My SDL defaults to the Wayland driver, you weren't to know that, I should have made it clear.  Fixing Wayland support is a hobby of mine! :-)

**Comment by stsp** [comment]
> I would expect X11 output to fail with DISPLAY unset, I was just demonstrating
> that it was defaulting to X11.

It was defaulting to X11 because
SDL (and therefore -S) does have
the X11 driver within.
Dosemu's own X11 support is not
enabled by default, but you can run
`dosemu -X` to see the difference.

**Comment by sjnewbury** [comment]
Then why, without DISPLAY being set is it falling back to running in the terminal, unless I use `dosemu -S`?  Something's fishy here.

**Comment by stsp** [comment]
OK, sorry, my testing was
inconsistent. I didn't unset
DISPLAY, but rather made it
empty.

> Unsetting DISPLAY causes X driver of SDL
> to fail.

That should be corrected to:
Unsetting DISPLAY causes dosemu2
to skip using sdl or X and proceed
with the terminal output. Which is
exactly what you see.
So sdl is a default, yes, unless you
unset DISPLAY (which is what you
actually do).

**Comment by sjnewbury** [comment]
Right, that makes sense now :-)

Perhaps it should check for WAYLAND_DISPLAY too though?
