### ISSUE TITLE
Terra Nova installer unable to reach the right 50% with mouse

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1632]
**Describe the bug**
I can only reach the left part of the screen in the installer. When the cursor is in the middle, it leaves the window on the right side already. Top to bottom is fine.
![Screenshot_20220515_091650](https://user-images.githubusercontent.com/877112/168461739-b68b4f04-81f8-405c-be23-743ca1198306.png)
This is as far as it goes.

**To Reproduce**
Obtain the ISO. Then use `cdemu` or a related tool to load it and run DOSEMU2:
```
cdemu load 0 TNF108.iso
dosemu -cdrom /run/media/julius/TNF108
```
Inside DOSEMU2:
```
g:
install
```

**Attach program/game binaries or provide an URL**
I used the link from #1599 

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8694451/boot.log)

**A regression?**
Possibly, there were many mouse changes, but I never tried this game/installer before.

**Additional info**
No special configuration.

**Comment by jschwartzenberg** [comment]
The game itself has the same issue:
![Screenshot_20220515_093202](https://user-images.githubusercontent.com/877112/168462234-34e07fba-46d9-4f28-ae68-5d7aca96fc0e.png)

**Comment by stsp** [comment]
Ctrl-Alt-Home for mouse grab.
Also please mention in all tickets if
tn demo can be used instead.

**Comment by jschwartzenberg** [comment]
Yeah the demo installer shows the same. (For the demo I found.) Grabbing the mouse allows reaching all parts of the window. I totally forgot about it.

**Comment by stsp** [comment]
So you need to do `emumouse x 16`
before starting the game.
I close this as notabug unless
@javispedro can say that with
his driver it works better. In that
case maybe some other work-around
is needed.

**Comment by stsp** [comment]
OK, it actually does work with
his driver, so I suppose we can
add some option to ignore
user's speed.

**Comment by stsp** [comment]
You can now do
`xmode -mouse-ungrab-tweak on`
before starting the game.
Or set the same setting in .dosemurc.
