### ISSUE TITLE
Ne strange behaviour in 80x50 mode of Borland Pascal 7.01

### ISSUE THREAD

**Issue by MGreim** [dosemu2/dosemu2#1633]
**Rescaling in BP 7.01 in 80x43/50 is strange**
In the latest version 
dosemu2-2.0pre9
Revision: 7076

the behaviour of dosemu2 has changed in worse manner. 
Until last week dosemu2 was starting with an 80x25 screen. 
When I then started BP in the 80x43/50 mode the window was automatically 
resizing from 4:3 to some 4:5 or so. 
Now dosemu2 is squeezing the smaller font in the standard 4:3 window. 
I played 2 hours around with the dosemu.conf, but no chance to change it to the old, better behaviour. 

**To Reproduce**
Just starting BP and switch between 

Environment -> Preferences 25 Lines <-> 43/50 lines
the aspect ratio keeps the same. 

**Logs**
[boot.log](https://github.com/dosemu2/dosemu2/files/8710111/boot.log)
![Bildschirmfoto zu 2022-05-17 18-45-24](https://user-images.githubusercontent.com/7490847/168865437-17d6e7e5-436f-4c61-9101-f219edf8596b.png)

Unfortunately I have no screenshot from the aspect ratio of the window before.

**Comment by stsp** [comment]
Should now be fixed, thanks.

**Comment by MGreim** [comment]
Thanks, fast service, works perfect now again!
Just a hint for other users: 
Its important for this kind of application to set 
`$_force_vga_fonts=(off)'

Below a proof

![Bildschirmfoto zu 2022-05-19 11-55-41](https://user-images.githubusercontent.com/7490847/169266930-2d09a997-1e2f-4e6a-9d30-c7fd093a8b51.png)

**Comment by stsp** [comment]
> Its important for this kind of application to set

Its off by default.
Still, in the future we may add
a ttf font with proper aspect ratio
for 80x50, and the resize that
you have now, will go away again.

@andrewbird have you seen any
TTF fonts for 80x50 mode?

**Comment by andrewbird** [comment]
> have you seen any
TTF fonts for 80x50 mode?

No sorry I haven't seen anything. The IBM VGA flexi TTF we use was created by [int10h.org](https://int10h.org/blog/2018/05/flexi-ibm-vga-scalable-truetype-font/) to recreate the classic 80x25 IBM VGA look. I haven't used 80x43 or 80x50 for many years, but from what I remember it was pretty horrid in its day. I would imagine the flexi TTF scaled to suit 80x50 would be more appealing.

**Comment by stsp** [comment]
> I would imagine the flexi TTF scaled to suit 80x50 would be more appealing.

You mean down-scale vertically?
I am afraid down-scaling would
reduce the quality a lot, so I'd
rather leave window resized
(as now) until we have a font
with proper aspect ratio.

**Comment by MGreim** [comment]
fine, I guess I am not the only "old man" using the ancient Borland IDE etc. There are still many 16 bit processors (80186) around..

**Comment by andrewbird** [comment]
> You mean down-scale vertically?

Possibly, but not necessarily. The original 80x50 font was very square (9x8?) and it was horrid to look at on real hardware. I think its only benefit in use was the number of lines you could display and an accurate TTF version would have the same vertically compressed unappealing look. So the natural thing in a windowed environment (because we can!) is to increase the vertical scale of the window and text to something more comfortable. I suspect that by the time this vertical upscaling has been applied, the aspect ratio of a new TTF font would be approaching that of our existing TTF font. To me, using the existing TTF font and increasing the vertical window size for 80x43 and 80x50 modes is aesthetically similar. So is that what you have now in the second screenshot above?

All very subjective, of course.

**Comment by stsp** [comment]
2 problems with that approach.
- Not all backends are windowed.
  Eg in kms console the window
  can't be enlarged vertically, so
  instead 2 things happen simultaneously:
  smaller font is chosen and horizontal
  shrink is done, so at the right side of
  the screen you have a "very thick"
  border. This all still looks quite good,
  so I am impressed by the such an
  intelligent combined actions of
  dosemu2 and sdl. :)
- font tracking is now implemented, so
  if VGA font is altered, ttf shuts down.
  If you have window enlarged, then
  such shutdown will be more visible
  as the window would be resized back
  to normal.

So I still think having a proper 8x8/square
fonts would be good, but current situation
is not too bad either. :)

**Comment by emendelson** [comment]
In DOSBox-X and vDos, you can use any TTF font for any window size. There seems to be no reason to need a special font for lines > 25. Consolas seems to be the preferred font under Windows for DOSBox-X and vDos.

**Comment by stsp** [comment]
The reason is to have proper
aspect ratio. Clearly 8x16 and
8x8 fonts have different aspect
ratio. We currently don't have a
TTF font for 8x14 and 8x8,
which is why the window have
to resize.
