### ISSUE TITLE
PIC/Timer issues

### ISSUE THREAD

**Issue by robert-j** [dosemu2/dosemu2#1634]
**Describe the bug**

It seems that calibration loops implemented by programming the timer to use a higher resolution is broken, at least using

    2.0~pre9-7417-cf2305534+202205180216~ubuntu22.04.1

**To Reproduce**

Run the [attached](https://github.com/dosemu2/dosemu2/files/8734650/test.zip) test case. It hangs.

**A regression?**

It looks so. It doesn't happen with

    2.0~pre8-7256-6426f4896+202201251932~ubuntu21.04.1

**Comment by robert-j** [comment]
The code looks like this (extracted from Borland Pascal's RTL, comments by me). Not sure where it hangs, maybe in the @@2 loops (there are 2 of them), which means that the ticker doesn't get updated.

    init:

    mov     es, 0040h  ; BIOS seg
    mov     di, 6ch       ; BIOS ticker

    in      al, [21h]       ; reprogram timer
    push    ax
    mov     al,0feh
    out     21h,al

    mov     bl,es:[di]

    @@2:
    cmp     bl,es:[di]
    je      @@2
    mov     bl,es:[di]
    mov     ax,-28
    cwd

    call    delayloop

    not     ax
    not     dx

    xchg    dx,cx
    mov     bx,1193
    mul     bx
    xchg    cx,dx
    xchg    dx,ax
    mul     bx
    add     ax,cx
    adc     dx,0

    mov     word ptr delaycnt, ax
    mov     word ptr delaycnt+2, dx
    pop     ax
    out     21h,al

    ret

    delayloop:

    @@1:
    sub     ax,1
    sbb     dx,0
    jc      @@2
    cmp     bl,es:[di]
    je      @@1
    @@2:
    ret

**Comment by stsp** [comment]
Should now be fixed, thanks.
A big one. :)

**Comment by robert-j** [comment]
There is still an issue with the new PIC code.

When I reprogram the 8254 to timer mode 2, read/write channel 0, reading from [40:6c] is periodically returning stale or wrong values. About 1x per second the value of [40:6c] is ca. 1000ms too high.

Do you want me to file a new bug report for this, or may I continue here? I'm preparing a test case for it.

**Comment by stsp** [comment]
Yes, please open a new ticket
and make a note if this is a
regression or not.
