### ISSUE TITLE
8254 in mode 2 not monotonic

### ISSUE THREAD

**Issue by robert-j** [dosemu2/dosemu2#1639]
**Describe the bug**

When I reprogram the 8254 to timer mode 2, read/write channel 0, reading from [40:6c] is not always monotonic.

**To Reproduce**

See the attached [test case](https://github.com/dosemu2/dosemu2/files/8773392/tmtest.zip). It should print a digit every second, for 5 seconds, but often it outputs 2-3 consecutive digits. This means that reading from [40:6c] did not return a monotonic value.

**A regression?**

Yes, it does not happen with versions before the PIT/PIC rework.

**Comment by stsp** [comment]
> When I reprogram the 8254 to timer mode 2

Isn't it 2 by default?

**Comment by stsp** [comment]
Please attach test sources too.

**Comment by robert-j** [comment]
I'd gladly attach some source code, but I just killed my dosemu installation (#1640). I'll try blindly.

**Comment by stsp** [comment]
> I'd gladly attach some source code, but I just killed my dosemu installation

No idea what does it mean.
In #1640 you killed dosemu
process, not dosemu
installation.

**Comment by robert-j** [comment]
Sorry for being unclear, I mean that I cannot test anymore, I cannot compile, etc. I'll try to replace 4dos with dosemu's default and see if I get it working again.

**Comment by robert-j** [comment]
Here's the source code: [tmtest.zip](https://github.com/dosemu2/dosemu2/files/8775370/tmtest.zip). It's Borland Pascal, but the relevant part is assembler.

**Comment by stsp** [comment]
Why do you mask in
IMR if interrupts already
disabled?
Does the same problem
happen if IMR is not used?

**Comment by robert-j** [comment]
Good question, it's 30 years old code :) But it still happens if I don't mask additionally using the IMR.

**Comment by stsp** [comment]
I think your test is wrong.
I can do this:
```
--- a/src/base/dev/misc/vtmr.c
+++ b/src/base/dev/misc/vtmr.c
@@ -103,8 +103,8 @@ static void vtmr_io_write(ioport_t port, Bit8u value)
         vtmr_pirr &= ~msk;
         if (!masked) {
             vtmr_irr |= msk;
-            if (!(vtmr_imr & msk))
-                pic_request(vip[timer].irq);
+//            if (!(vtmr_imr & msk))
+  //              pic_request(vip[timer].irq);
         } else {
             pic_untrigger(vip[timer].orig_irq);
             pic_request(vip[timer].orig_irq);
@@ -269,7 +269,7 @@ static void vtmr_lower(int timer)
     if (timer >= VTMR_MAX || !(vtmr_irr & (1 << timer)))
         return;
     vtmr_irr &= ~(1 << timer);
-    pic_untrigger(vip[timer].irq);
+//    pic_untrigger(vip[timer].irq);
 }
 
 void vtmr_register(int timer, void (*handler)(int))
```
which stops the timer completely.
With dosdebug I can do this:
```
dosdebug> d 40:6c

0040:006c 82 50 14 00 00 00 00 00 00 04 00 00 14 14 14 00  .P..............
```
to verify that the timer isn't
running. Also I see that DOS
time is not moving.

But exactly with that change
your test starts to count w/o
any delays at all.
Why is that?

**Comment by stsp** [comment]
I think you are returning the
function results a wrong way.
I looked up my own old sources
and they have this:
```
mov @result,cx
```
But you are putting results
into stack??
I think your test was giving
the seemingly correct results
in the past, by a pure luck.
Or am I wrong?

**Comment by robert-j** [comment]
The function was written for a Turbo Pascal version that did not support "assembler". The code is inlined inside a normal function. And in such functions the return value is on the stack.

Indeed, assembler functions would use al, ax, dx:ax, or as you wrote, @result, but this is not an assembler function.

Edit: I'm going to rewrite it using "modern" (like, less than 30 years old 😀) Borland Pascal stuff. Just to be sure I'm not wasting our time.

**Comment by stsp** [comment]
OK but you need to explain
why your test counts w/o any
delay if I stop the timer as shown
above.

**Comment by robert-j** [comment]
I have really no idea. The code enters an endless loop when "ReadTimer" returns 0 or any other constant all the time.

**Comment by stsp** [comment]
I also can't find any flaw in
the code, so I can only suspect
bad return via stack.
It would be good if you disable
the timer as shown above, and
look at what happens in your code
then.

**Comment by robert-j** [comment]
I have modernized the function

    function ReadTimer : LongInt; assembler;
    asm
      cli               { Disable interrupts }
      mov   dx, $20     { Address PIC ocw3 }
      mov   al, $0A     { Ask to read irr }
      out   dx, al
      mov   al, $00     { Latch timer 0 }
      out   $43, al
      in    al, dx      { Read irr }
      mov   di, ax      { Save it in DI }
      in    al, $40     { Counter --> bx }
      mov   bl, al      { LSB in BL }
      in    al, $40
      mov   bh, al      { MSB in BH }
      not   bx          { Need ascending counter }

      in    al, $21     { Read PIC imr }
      mov   si, ax      { Save it in SI }
      mov   al, $0FF    { Mask all interrupts }
      out   $21, al

      mov   ax, $40     { read low word of time }
      mov   es, ax      { from BIOS data area }
      mov   dx, es:[$6C]

      mov   ax, si      { Restore imr from SI }
      out   $21, al

      sti               { Enable interrupts }
      mov   ax, di      { Retrieve old irr }
      test  al, $01     { Counter hit 0? }
      jz    @done       { Jump if not }
      cmp   bx, $FF     { Counter > $FF? }
      ja    @done       { Done if so }
      inc   dx          { Else count int req. }
    @done:
      mov   ax, bx      { Function result in dx:ax }
    end;

Still the same, also with the IMR stuff removed.

I'll try with your patch applied.

**Comment by robert-j** [comment]
I have got another [test](https://github.com/dosemu2/dosemu2/files/8782150/tt.c.txt), this time in C (Borland C).

The test is part of a good hardware interrupt and timer documentation posted to Garbo aeons ago.

http://www-ftp.lip6.fr/pub/pc/garbo/pc/programming/pctim003.zip

You'll see how dosemu is returning non-monotonic timestamps. Press ESC for the continuous  test.

Here's a [binary](https://github.com/dosemu2/dosemu2/files/8782168/tt.zip).

I also run the test under DOSBox where it also counts backwards, but very seldom (2x per minute).

**Comment by stsp** [comment]
What timestamps does it
mean? PIT counters?
I would prefer to continue
with your test. At least we
know that you want to test
40:6c counter.

**Comment by stsp** [comment]
But you are right, on pre9
this test never fails!
So indeed we have a regression.

**Comment by robert-j** [comment]
Yes, it's the same computation, done in a more canonical way (and in C).

The reason why I came with a C sample is that Borland Pascal does not know "unsigned long". I was afraid, that there is a bug related to this in my code, but it doesn't seem so.

**Comment by stsp** [comment]
OK, cool, got your C sources,
looking in...

**Comment by stsp** [comment]
So when timer interrupts no
longer come, it will sure as hell
consider backward jumps, as
the counters can go back.
Is this why your pascal test
also breaks?

**Comment by robert-j** [comment]
Yes, most likely.

**Comment by stsp** [comment]
Could you please remove the
second sampling, after sti?
```
        asm sti;                        /* Force interrupt ENABLE */
        ctcvalue = - ((ctchigh << 8) + ctclow);
        tickcount2 = * BIOS_TICK_COUNT_P;
        asm popf;
        if ((tickcount2 != tickcount1) && (ctcvalue & 0x8000))
                tsp->ticks = tickcount1;
        else
                tsp->ticks = tickcount2;
```
I'd like to see a clean test that
only has one sampling with
interrupts disabled. I don't want
to deal with any other complexity. :)

**Comment by robert-j** [comment]
Just a moment ...

[tt.zip](https://github.com/dosemu2/dosemu2/files/8782382/tt.zip)

**Comment by stsp** [comment]
Hmm, this one breaks even
on pre9. :)

**Comment by stsp** [comment]
I have 1 idea.
In your pascal test you used
irr to compensate 1 tick.
Now you no longer used it.
Can it be the problem?

**Comment by stsp** [comment]
I think if you add that irr
compensation, you'll fix
the test at least on pre9.

**Comment by stsp** [comment]
Or maybe you need to
first latch the pit counter and
then latch the bios counter?
And w/o any cli/sti.
What do you think?

**Comment by robert-j** [comment]
Do you want to see how it behaves w/out disabling the interrupts? Because the specs of the 8254  explicitly warns about doing this, for both the counter and the BIOS area.

Or do you mean I should mask the interrupts like I did it in the pascal code?

**Comment by stsp** [comment]
When you disable interrupts,
the timer may overflow but the
interrupt won't be triggered.
In your pascal test you read
irr to catch that condition.
If irr&1==1 you increment the
counter.
This test doesn't have such
compensation.

**Comment by stsp** [comment]
I pushed the "pitfix" branch
where I made it so that irr&1
is properly simulated.
That seems to make your
original pascal test better,
but not perfect still.
It doesn't affect your last
test as it lacks the irr
compensation.

**Comment by stsp** [comment]
I made a few fixes.
Now there are the following problems:
1. pic_watch() is not called frequently enough
    so the timer interrupts are not in sync with
    the pit counter.
- This problem affects both tests.
In pre9 timers were running in pic_activate()
which was called much more frequently.

Possible solutions:
1a. Call pic_watch() more frequently.
      Not a dosemu2 way of solving things. :)
1b. Implement event-based timer subsystem.
      This is what I was going to do anyway.
      But it will likely not solve the problem fully:
      some de-syncs might still be possible.
1c. Move pit to a separate thread, which
      will decrement the counter and raise
      an irq at the right time.
      I was planning that for a future, threaded
      architecture is not yet ready.
So we are going to look into 1b here.

2. pic0.irr&1 is not properly emulated by
    dosemu2's bios firmware (yes, I moved
    pit emulation into firmware mostly, because
    also in the modern motherboards it can
    be emulated with HPET+firmware instead
    of using real PIT, and that has many
    advantages and many problems).
- This problem affects only pascal test,
  and in a much smaller scale than the
  first problem. It prevents the pascal
  test from doing the 1 tick compensation
  with irr check.

As a solution to this, I created a patch
(in a pitfix branch) that emulates the
correct behaviour of pic0.irr&1.
But in a presence of problem 1, such
fix doesn't help at all because the timer's
irq is not triggered at the right moment,
so the irr-fix will also not trigger at the
right moment.
As a quick fix I could call pic_watch()
when irr is being read by your test app,
but unfortunately this doesn't help because
its too late to run firmware code that
emulates this irr behaviour when real
irr is already being read by an app.
So I suppose this fix can live in a
separate branch until some solution
for problem 1 materializes.

**Comment by stsp** [comment]
In ioasyn branch I've replaced
the current IO demux subsystem
with threaded one.
On top of that I am going to
implement the event-based
timers, which will fix that.

In a mean time it would be
good if people test the ioasyn
branch, because I am afraid
of a countless regressions
again...

**Comment by stsp** [comment]
Pushed event timers subsystem
into a separate branch.
Your tests feel good (Cish test
shows some de-syncs, but its
expected).
But it needs some more debugging.

**Comment by stsp** [comment]
[tt.c.txt](https://github.com/dosemu2/dosemu2/files/8856703/tt.c.txt)
This is a fixed version
of your test. It shows no
problems with my new code,
which I'll push.
Your initial version shows
lots of false backward jumps,
and your pascal test is slightly
better as it does the IRR
compensation. But even
the pascal test is broken
because the timer may
trigger after latch, which
will lead to the false
compensation.

**Comment by stsp** [comment]
So would be good to know
if the current code suits your
needs.

@bpranoto would be cool
if you check IPX on current
code base. Hope it survived.

**Comment by andrewbird** [comment]
So I noticed you have some tests in here, is there a possibility of refining those into something simple (just a pass/fail) and consistent, that I can add to the test suite?

**Comment by stsp** [comment]
Unfortunately these tests
should be continuously running
to see if the timer behaves
consistently.
Maybe we can add such to
the weekly test-suit, and allow
to run for 2 minutes or so?

**Comment by stsp** [comment]
In that case you just need
to kill dosemu after a certain
period of time, and then analyse
the log to see if test haven't
failed.

**Comment by stsp** [comment]
Or for example the test can
be changed to exit on the first
failure. In that case, time-out
would mean success.

**Comment by stsp** [comment]
Overall having such test
would be very good, as I
think the timer subsystem
is going to be worked on
quite a lot. It should be
fully rewritten, and preferably
w/o too many regressions.
As of today, its probably
only half-rewritten.

**Comment by stsp** [comment]
Do you have Borland C
installed? The test is very
simple. If you don't have
Borland C, I can do the
modifications you desire.
If you have Borland C, you
can do them yourself in a
minute. :)

**Comment by andrewbird** [comment]
Thanks, I think I'll try to tweak the test program to compile with gcc-ia16 and also make it non interactive. Is there a known licence / is it okay to include in Dosemu2?

**Comment by stsp** [comment]
> is it okay to include in Dosemu2?

I don't see any license strings
in a file, so I guess its ok.
Also I think there is some liberty
in tests, as they are not the part
of a dosemu binary/distribution.

**Comment by andrewbird** [comment]
So I got the program to compile and run, but I'm not too confident that I didn't mess things up since I don't seem to be able to get a sensible correlation between runtime and number of times through the loop. I don't really know these timers, so I have to believe the comment that a tick is 0.8381 microseconds although obviously there is a cost to the printfs etc. Perhaps I didn't set up the timer correctly?

[t12.zip](https://github.com/dosemu2/dosemu2/files/8865152/t12.zip)

**Comment by andrewbird** [comment]
Actually If I calculate the elapsed time things work out correctly. This new version runs for exactly 120 secs. 
[t13.zip](https://github.com/dosemu2/dosemu2/files/8865235/t13.zip)

**Comment by stsp** [comment]
`#define _BORLANDC_SOURCE`
Is this still needed?

Looks cool, thanks.

**Comment by stsp** [comment]
By the way, you may consider
measuring with host's `time`
command that test actually ran
for 2 minutes.
This will mean that no matter
what CPU load is on CI, the
timers are still correct.
(of course some +-5 seconds
should be reserved for dosemu2
startup)

**Comment by stsp** [comment]
```
$ time dosemu -K ./sample15.exe 
real	1m2,534s
```
Doesn't look like 120 seconds
to me though.

**Comment by andrewbird** [comment]
I timed it more simply; I hit return in dosemu window to start, then switched to terminal and ran date immediately, when the test completed I ran date again. I guess I just got lucky!
~~~
ajb@polly:~/Desktop$ date
Wed  8 Jun 22:41:44 BST 2022
ajb@polly:~/Desktop$ date
Wed  8 Jun 22:43:44 BST 2022
~~~

I'll tidy this up into a proper test.

**Comment by andrewbird** [comment]
> #define _BORLANDC_SOURCE

Yes it's for tkchia's libi86 to include the Borland specific `outportb` and `inportb` functions.

**Comment by andrewbird** [comment]
I added the test. On my system the test shows 122 secs, that's including starting / stopping of dosemu and also setting up the test environment, so not too far out.

**Comment by stsp** [comment]
But on my system it showed
1 minute, as you've seen...

**Comment by stsp** [comment]
```
$ time dosemu -K ./sample15.exe 
real	2m2,784s
```
Now its ok...

**Comment by stsp** [comment]
So maybe I did something wrong.
It works properly now.

**Comment by andrewbird** [comment]
> So maybe I did something wrong.

Maybe you tested my first attempt (t12) rather than the 2 minute one (t13).

**Comment by bpranoto** [comment]
On Wed, Jun 8, 2022 at 6:46 PM Stas Sergeev ***@***.***>
wrote:

> So would be good to know
> if the current code suits your
> needs.
>
> @bpranoto <https://github.com/bpranoto> would be cool
> if you check IPX on current
> code base. Hope it survived.
>
>
>
Just git pull. Unfortunately, I can't compile..


int.c: In function ‘int33_unrevect_fixup’:
int.c:1748:1: internal compiler error: in move_insn, at haifa-sched.c:5463
 1748 | }
      | ^
0x7fd4ffa44082 __libc_start_main
../csu/libc-start.c:308

**Comment by stsp** [comment]
Please do:
```
make clean
./default-configure -d
make -j 9
```
That should work (because of -d).

**Comment by bpranoto** [comment]
Thanks. I can compile now. Unfortunately, ipx doesn't work.
Attached is the log with -Dn
[boot.log](https://github.com/dosemu2/dosemu2/files/8927765/boot.log)

**Comment by stsp** [comment]
Thanks, could you please re-check?

**Comment by bpranoto** [comment]
Now dosemu crashes:

```
[boot.log](https://github.com/dosemu2/dosemu2/files/8928033/boot.log)
```

**Comment by bpranoto** [comment]
```
ipx.c:907:3: runtime error: member access within null pointer of type 'struct ipx_socket_t'
ERROR: Fault in dosemu code, in_dpmi=0
ERROR: cpu exception in dosemu code outside of VM86()!
sig: 11 trapno: 0x0e  errorcode: 0x00000004  cr2: 0x0000001c
eip: 0x564bfb644f2c  esp: 0x7ffdc55e3820  eflags: 0x00010213
cs: 0x0033  ds: 0x0000  es: 0x0000  ss: 0x002b
fs: 0x0000  gs: 0x0000
fsbase: 0x7fee1935c880 gsbase: (nil)

```

**Comment by stsp** [comment]
And now?

**Comment by bpranoto** [comment]
No crash, but still doesn't work
[boot.log](https://github.com/dosemu2/dosemu2/files/8928349/boot.log)

**Comment by stsp** [comment]
Thanks, please open another
ticket then. I'll probably need
ssh for that, as setting up IPX
these days is quite difficult.

**Comment by bpranoto** [comment]
Done.

I have also prepared the dosemu installation with drdos 7.03 + vlm netware client.  May be you can also solve fdpp+ipx problem at https://github.com/dosemu2/fdpp/issues/197
Please write me to bpranoto@gmail.com for ssh access information.

**Comment by stsp** [comment]
Thanks, I will contact you by
mail later.
