### ISSUE TITLE
2.0~pre9-7424-680b0bdfd+202205250302~ubuntu22.04.1 broken

### ISSUE THREAD

**Issue by robert-j** [dosemu2/dosemu2#1640]
**Describe the bug**

The version mentioned in the title does not boot. It hangs while loading 4dos.com, my command.com
replacement.

It started to happen after I've updated to:

    dosemu2 (2.0~pre9-7424-680b0bdfd+202205250302~ubuntu22.04.1) over
    (2.0~pre9-7419-7a419e49d+202205200247~ubuntu22.04.1)

[.dosemurc](https://github.com/dosemu2/dosemu2/files/8773434/dot.dosemurc.txt)
"dosemu -s" [boot.log](https://github.com/dosemu2/dosemu2/files/8773437/boot.log)
"dosemu -s -Da": [boot.log.gz](https://github.com/dosemu2/dosemu2/files/8773448/boot.log.gz)

I'm usually running under sudo (dosemu -s), but it also occurs w/out "-s".

**Comment by stsp** [comment]
Why do you use -s?

Can't reproduce, works for me:
```
c:\>ver /r
 
4DOS 8,00   FreeDOS 7,10
4DOS Build 200 (Feb 27 2009)
DOS Revision A; DOS is in HMA
```
What exactly should be done?

**Comment by robert-j** [comment]
I'm using -s to be able to access the packet driver in eth mode. tun doesn't work for me anymore after I've updated to Ubuntu 22.04. Since I'm unsure who is causing the issue, I didn't file a bug here. The packet driver code is giving up with "device busy" when it's trying to open the tun device. The tun device is bridged together with the eth device, so it might be really busy in some sense... no idea what it is.

About 4dos: I was using this configuration since ages. It just stopped working after the aforementioned update. While loading 4dos, dosemu just hangs and it gets killed by a "this app ist not responding" dialog.

**Comment by stsp** [comment]
tun also needs -s so don't
use it. Use slirp.

So if it hangs hard, please
do `dosemu -gdb` and in gdb
please produce a stack trace
when it hangs, with `bt f`.

**Comment by robert-j** [comment]
It used to work w/out -s before the Ubuntu update, using a bridge. The tun device was specifically created to be owned by the user who later starts dosemu. It worked like a champ. Never had to run dosemu as root, or with "-s" until now.

**Comment by stsp** [comment]
> The tun device was specifically created to be owned by the user

Ah that makes sense, but since
it doesn't work any more, just use
slirp.

**Comment by stsp** [comment]
In fact, there are very few
(just 3) places that can return
EBUSY:
https://github.com/torvalds/linux/blob/master/drivers/net/tun.c
and the only one that can
potentially apply, seems to
be this:
https://github.com/torvalds/linux/blob/master/drivers/net/tun.c#L758
So here:
https://github.com/dosemu2/dosemu2/blob/devel/src/dosext/net/libpacket.c#L379
you can try to add that
`IFF_MULTI_QUEUE`
and see if that helps.

**Comment by robert-j** [comment]
When I replace 4dos with the FDOS shell then it's booting again into the command prompt. Starting 4dos.com manually from the shell is hanging dosemu again. But at least I"m back in business.

**Comment by robert-j** [comment]
gdb doesn't work for me as I instantly get a SIGSEGV. Do I have to ignore certain signals?

Note that I'm not using kvm, so dosemu is running in emulation mode.

**Comment by stsp** [comment]
Well in emulated mode it
hangs for me too.

**Comment by robert-j** [comment]
The backtrace doesn't look good w/out symbols. Do you keep the symbols of the Ubuntu package?
Anyways, you seem to be able to reproduce it, while I forgot *again* to tell you that I'm running emulated :( Sorry, I simply assumed that attaching the logs would be enough info.

Thread 1 "dosemu.bin" received signal SIGINT, Interrupt.

0x00007f1bf003b793 in ?? ()

(gdb) bt f

#0  0x00007f1bf003b793 in ?? ()
No symbol table info available.
#1  0x0000000000000246 in ?? ()
No symbol table info available.
#2  0x0000558c9eecc185 in Exec_x86 ()
No symbol table info available.
#3  0x0000558c9eebe334 in ?? ()
No symbol table info available.
#4  0x0000558c9eec9002 in e_vm86 ()
No symbol table info available.
#5  0x0000558c9eeb0ff5 in ?? ()
No symbol table info available.
#6  0x0000558c9eeb1f75 in loopstep_run_vm86 ()
No symbol table info available.
#7  0x0000558c9ee565c5 in main ()
No symbol table info available.

**Comment by robert-j** [comment]
> In fact, there are very few (just 3) places that can return EBUSY: https://github.com/torvalds/linux/blob/master/drivers/net/tun.c and the only one that can potentially apply, seems to be this: https://github.com/torvalds/linux/blob/master/drivers/net/tun.c#L758 So here: https://github.com/dosemu2/dosemu2/blob/devel/src/dosext/net/libpacket.c#L379 you can try to add that `IFF_MULTI_QUEUE` and see if that helps.

Will try, although this kernel code part is like 8 years old.

**Comment by robert-j** [comment]
One question about gdb and emulation mode: I was only able to run dosemu under gdb when I'm ignoring SIGSEGV, because it gets triggered instantaneously:

handle SIGSEGV nostop noprint

It this expected? Is it some kind of intended trap?

**Comment by stsp** [comment]
Yes, that is intentional.
Self-modifying code or some
VGA access may sigsegv.
