### ISSUE TITLE
dosemu2 crashes ( again )

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1647]
**Describe the bug**
a dosemu2 crash

**To Reproduce**
run the attached test program, invoke.exe.

**Attach program/game binaries or provide an URL**
[invoke.zip](https://github.com/dosemu2/dosemu2/files/8800254/invoke.zip)

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/8800256/boot.log.zip)

It's a 16-bit DPMI client with 16-bit stack running in a 32-bit code segment.
Removing the STI makes the crash disappear - but I'm aware that STI, taken for itself - is not a problem for a dpmi client program.

**Comment by stsp** [comment]
Thanks!
