### ISSUE TITLE
Can't build: gpg: keyserver receive failed: Server indicated a failure

### ISSUE THREAD

**Issue by RossBoylan** [dosemu2/dosemu2#1649]
**Describe the bug**
I am trying to build the package on a Debian 11 system, using https://github.com/dosemu2/dosemu2/wiki/Building-From-Source as a guide.  It says to clone and  then run `ci_prereq.sh`.  I ran the first line of that script independently, with additional debugging info.  It failed with
```
gpg: keybox '/tmp/tmpcjw8ab77/pubring.gpg' created
gpg: keyserver receive failed: Server indicated a failure
```

**To Reproduce**
1. clone repository
2. as root, execute `add-apt-repository -m ppa:dosemu2/ppa`
3. Hit ENTER to continue when asked
4. 2 was executed in a bash subshell of emacs

**Variation**
I ran the same command in 2. in a regular bash shell (i.e., under Konsole, not emacs).  This seemed to work better:
```
gpg: keybox '/tmp/tmp6a9zkca0/pubring.gpg' created
gpg: /tmp/tmp6a9zkca0/trustdb.gpg: trustdb created
gpg: key EBE1B5DED2AD45D6: public key "Launchpad PPA for Dosemu2" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
```

Comments:
   1. Either the terminal environment did matter, or some random thing allowed (I think) reception to succeed.
   2. It's not completely clear to me whether this is an overall success, because the significance of the final `no valid OpenPGP data found` is unclear.  If that's just a reflection of not finding an ultimately trusted key, it's not surprising.
   3. You might want to note the deprecation of apt-key, though I guess that's more an issue for `add-apt-repository`.

**Comment by stsp** [comment]
I can only suggest other
forums, like askubuntu.com.
launchpad signs PPA
automatically, so if you have
that problem, it should not
be specific to our PPA.

**Comment by stsp** [comment]
Hope you've found a fix
elsewhere.
