### ISSUE TITLE
Can't run dosemu2 as root

### ISSUE THREAD

**Issue by mikesixes** [dosemu2/dosemu2#1653]
**Describe the bug**
A description of what the problem is.
Trying to run dosemu2 in Ubuntu 20.04. The app I'm trying to run uses ethernet, but it's not a network app. It just uses ethernet as a high-speed serial port to communicate with a machine controller. It uses a packet driver for that. The computer and the machine just broadcast packets at each other as raw ethernet packages with no tcp/ip headers.The config file tells me that I can't use the "eth0" and packet driver functions without root privileges. When I try to run dosemu as root, it tells me "Running dosemu2 as root is highly discouraged" and doesn't offer me any way to get around the roadblock. Does this mean that the ethernet functions are simply not available, or is there some workaround to allow me to use a packet driver without a network connection?

**To Reproduce**
Steps to reproduce the behaviour:
Just try to start dosemu with sudo, or when you're logged in as root.

**Attach program/game binaries or provide an URL**
If the problem needs specific DOS files to reproduce, please attach
or provide the download URL.

**Attach the log**
Didn't create any boot log, since it didn't boot.
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.

**A regression?**
If you happened to know this problem didn't
exist on dosemu1 or some earlier versions of
dosemu2, please write.

**Additional info**
I installed win98 dos boot files

Please write here if you did any dosemu2 setup
customizations, like installing any custom DOS
or command.com, or altering the dosemu2
configuration settings. Note that freedos, even
from dosemu-freedos package of dosemu1, counts
as a custom DOS and should be mentioned here.
Also make a note if it is a protected or real-mode
program. If you suspect any particular dosemu2
component (DPMI, PIC, PIT etc) to be responsible
for the problem, please write.

**Comment by stsp** [comment]
Try `dosemu -s`

**Comment by stsp** [comment]
This will be printed in an
error msg from now on.
