### ISSUE TITLE
DJGPP compiler/link seems to be broken for cpu tests

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1657]
Currently the cpu tests cannot be built on Ubuntu 20.04 (the version we use on Github actions). Actually we skip in this case, so the test suite overall won't fail, but of course the cpu tests won't be performed. Here's what I see when running the compilation by hand.
~~~
$ (cd test/cpu && git clean -d -f -x)
$ make -C test/cpu all
make: Entering directory '/clients/common/dosemu2.git/test/cpu'
i586-pc-msdosdjgpp-gcc -Wall -O2 -g -fno-strict-aliasing -fno-pic -fno-pie -no-pie  -o dosbin.exe test-i386.c test-i386-code16.S test-i386-vm86.S -lm
test-i386.c: In function 'test_exceptions':
test-i386.c:2055:9: warning: array subscript 0 is outside array bounds of 'char[0]' [-Warray-bounds]
 2055 |         *(char *)0x234 = 1;
      |         ^~~~~~~~~~~~~~
test-i386.c:2067:14: warning: array subscript 0 is outside array bounds of 'char[0]' [-Warray-bounds]
 2067 |         v1 = *(char *)0x234;
      |              ^~~~~~~~~~~~~~
/usr/lib/gcc/i386-pc-msdosdjgpp/12.1.0/../../../../i386-pc-msdosdjgpp/bin/as: unrecognised option '--gdwarf-5'
/usr/lib/gcc/i386-pc-msdosdjgpp/12.1.0/../../../../i386-pc-msdosdjgpp/bin/as: unrecognised option '--gdwarf-5'
make: *** [Makefile:12: dosbin.exe] Error 1
make: Leaving directory '/clients/common/dosemu2.git/test/cpu'
~~~

**Comment by stsp** [comment]
@jwt27 could you please explain
this `--gdwarf-5` error? I think this
is something with your djgpp build.

Also that -Warray warning looks
crazy as hell.

**Comment by jwt27** [comment]
Thanks for the ping.  I don't have a Ubuntu 20.04 system right now but I'm guessing binutils-djgpp 2.34 is the last one available there?
gcc (>= 11.1) now defaults to DWARF 5 debug info if it detects that the build-time binutils supports that, and I always use the latest.  So instead I'll have to build against different binutils versions for each Ubuntu version.

Quick workaround if you need it to work *right now*: compile with `-gdwarf-4`.

**Comment by stsp** [comment]
> binutils-djgpp 2.34 is the last one available there?

Seems so, checked here.

> So instead I'll have to build against different binutils versions for each Ubuntu version.

How about forcing gcc (with
configure flags) to not use dwarf5?

> Quick workaround if you need it to work right now

Yep, that's what Andrew already
did.

**Comment by skitt** [comment]
Yes, 2.34 on 20.04, 2.35.1 after that; 2.37 was subtly broken in various ways and got withdrawn.

**Comment by jwt27** [comment]
> How about forcing gcc (with configure flags) to not use dwarf5?

That would be a lot easier, but no such option exists.

> Yes, 2.34 on 20.04, 2.35.1 after that; 2.37 was subtly broken in various ways and got withdrawn.

Do you happen to recall in what way it was broken?  I never encountered problems with it but there were some posts on the djgpp mailing list about issues in the native port.
v2.38 improves section alignment for coff-go32 objects, by the way.  Not related to this, but would be nice to have.

**Comment by andrewbird** [comment]
> binutils-djgpp 2.34 is the last one available there?

@jwt27 I may be missing something here, but isn't that under your control? What's to stop upgrading it to a more compatible version (v2.38?), on platforms such as Ubuntu 20.04 that come with a native binutils of v2.34?

**Comment by jwt27** [comment]
The whole PPA (binutils/gcc/libc/watt32) has just one version number.  I intentionally left the first number 0 to avoid conflict with Stephen's binutils-djgpp, or other parts of the toolchain in case those are added to Debian at some point.  But yes, if I changed it to something above 2.35.1 it would override that.

**Comment by andrewbird** [comment]
Sorry I mistakenly believed that all the *djgpp* packages were from the same source. Now I see that binutils-djgpp is separate from your packages.

**Comment by jwt27** [comment]
Finally had some time to look into it.  The toolchain PPA now uses sane version
numbers for binary packages (figured it out thanks to a Stackoverflow post by
@skitt).  If you install binutils-djgpp now you should always get the latest
version.

I also reorganized the libc/utilities packages a bit, so to upgrade you'll need
to run `apt full-upgrade` or specify the package names explicitly.
