### ISSUE TITLE
ESC key is killing Windows instantly

### ISSUE THREAD

**Issue by robert-j** [dosemu2/dosemu2#1661]
**Describe the bug**

Windows 3.11 for Workgroups is crashing with

    ERROR: DPMI: HW interrupt stack corrupted

when the ESC  key is pressed.

**To Reproduce**

Start Windows and press ESC :) It's not important at what moment. The first press is killing it, even during the start when the desktop is barely visible.

**A regression?**

Yes.

**Additional info**

DPMI mode: KVM

It doesn't cash with

    $_cpu_vm_dpmi = "emulated"

Tested with:

    Architecture: amd64
    Version: 2.0~pre9-7453-b8485bbc3+202206100316~ubuntu22.04.1

The previous version (a few days old) was also crashing. Unfortunately, I did not log which version it was before upgrading.

**Comment by stsp** [comment]
Please attach -D9+M log.

**Comment by robert-j** [comment]
File is actually a BZ2. Had to rename it to please Github.

[boot.log.bz2.zip](https://github.com/dosemu2/dosemu2/files/8879805/boot.log.bz2.zip)

**Comment by stsp** [comment]
Can you check if the problem
is from commit a5a60b49?
Otherwise please give me
the archive of your win311.
Mine seems to work ok.

**Comment by robert-j** [comment]
My Win311 installation is probably a bit weird: it was previously installed in a VMware VM, and I just took it from there and thought ha ha, this would never run! But it did from scratch.

But I'm successfully running it unchanged since 1.5 years under dosemu2.

How can I send you the link?

**Comment by stsp** [comment]
You can send me email.
It can be found in package info and
other places.

**Comment by stsp** [comment]
Reproduced with release build.
This is not a code bug.
It just seems that gcc doesn't
permit any more the aliasing
via ptr to union with compatible
member.

**Comment by stsp** [comment]
Btw, I've found your e-mail
in spam. I think emails are
unreliable these days, and
needs to be "pinged" here
for confirmation.
For example I never
received any credentials
for ssh access from a nearby
ticket, so I wonder if it was
eaten by a spam filters too...

Overall, if anyone sent me
any e-mail and got no reply,
please ping me on github.
And do so with any subsequent
e-mail.

**Comment by robert-j** [comment]
I've been hit by this GCC behavior, too. It also used to give false positives in the past, which made it easier for me to overlook real issues.

Thank you!

**Comment by stsp** [comment]
Have you received the updated
build? LP is not building any more.

**Comment by robert-j** [comment]
Yes, I did, and it works. Thanks!

**Comment by robert-j** [comment]
Something I forgot:

Since 1-3 updates I had a very strange networking issue:

Whenever I've freshly started my Ubuntu VM, networking in dosemu2 was dead until I restarted dosemu2 for a couple of times.
100% reproducible! It was really wicked, because not only my code was failing. It was wattcp as well and any other
packet driver app I tried.

The failure was that no packets were received by the packet driver consumer, although the logs (and tcpdump) showed
that packets were on the wire.

With your update this glitch is gone as well! Like it never was there. I did not change anything else on my system.

**Comment by stsp** [comment]
There were possible timer
deadlocks because of threading.
Maybe that fixed the problem
because that could explain
that the packets are coming
in but the timer handler does
not process them (for example).

**Comment by stsp** [comment]
How goes your ndis support btw? :)

**Comment by robert-j** [comment]
The timer was the first thing I checked, but it worked well. Maybe it was the wait pattern, which both my code and wattcp are using:

    while (!elapsed)
        pushf
        cli
        read BIOS ticks from [40:6c]
        popf

Pretty basic stuff with no PIC/PIT programming involved. The other issues I had with the timer were for a PING use case where I wanted a better resolution than 1/18.

On NDIS:

I'm still not familiar enough with dosemu2's sources do make some progress. 

But all I'd need to know is basically:

1. how to install a FAR proc (stdcall convention, params passed on the stack) trap into DOS' memory space so DOS apps can invoke them
2. how to call stdcall FAR procs of DOS programs (ditto with stack params) from inside dosemu2

Maybe you have a couple of links inside dosemu2' sources where I can make myself familiar with this stuff.

**Comment by stsp** [comment]
> The other issues I had with the timer were for a PING use case where I wanted a better resolution than 1/18.

Are you happy with current
resolution?

> Maybe you have a couple of links inside dosemu2' sources where I can make myself familiar with this stuff.

See pkt_receiver_callback_thr() that
saves regs and calls to DOS 2 times.

pkt_reset() installs the call-back
for DOS. When called to
BIOS_HLT_BLK_SEG:pkt_hlt_off
the control transfers to pkt_hlt() fn.
Such names are because there is
a hlt instruction in realmode space.
It traps to emulator and invokes the
registered handler.
So its all very simple.

**Comment by robert-j** [comment]
The timer works better than before, although it still can occur that 5-10 probes are coming really fast behind each other. But it still have to read (again) your posts on #1639 to understand better why this 30 years code if failing. I forgot about this stuff.

Yes, pktnew.c is like the best place for me to start.

It looks like I can use reuse libpacket.c w/out any trouble, although it's somewhat interleaved with pktnew. Let's see.

Edit: I was asking about STDCALL because I thought that there are places in dosemu2 that do similar things. But STDCALL war really seldom used, so there are most likely none ;) Since NDIS is more an OS/2 thing, it's ridden with this calling convention. No register passing at all. But I understand that dosemu2 can do everything, so it's just a matter of interpreting the registers at the time of the trap.

**Comment by stsp** [comment]
> The timer works better than before, although it still can occur that 5-10 probes are coming really fast behind each other.

You mean your pascal test?
Well I looked at it again and
I don't know why would it fail.
As your C test didn't have the
IRR compensation, it would
be quite difficult to debug.
Please replicate the IRR logic
into C and I'll look again.

**Comment by stsp** [comment]
> Well I looked at it again and
> I don't know why would it fail.

I think I do.
You have:
```
    $81/$FB/$FF/$00/       {cmp  bx,$FF     ;Counter > $FF?}
    $77/$01/               {ja   done       ;Done if so}
```
But it the multitasking OS you
need to assume much larger
errors. So try 0x2000 instead
of 0xff.

**Comment by stsp** [comment]
I pushed the patch to use
SCHED_FIFO for io thread
(which also governs timer)
and that seems to improve
the accuracy.
But still far above 0xff ticks...

One trick I can think of is
to disable VME and manually
check timers on `cli`. In that
case the timer inside your
critical section will be more
or less up-to-date.

**Comment by stsp** [comment]
I added such hack to the
tmrhack branch, but even
that doesn't allow to keep
the error within 0xff ticks
reliably...
