### ISSUE TITLE
sdl uses hw accel

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1666]
Even though not enabled in
the config, sdl uses hw accel:
```
(gdb) thread 3
[Switching to thread 3 (Thread 0x7fffe5998640 (LWP 437067))]
#0  0x00007ffff69d594a in __futex_abstimed_wait_common () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff69d594a in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007ffff69d8140 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libc.so.6
#2  0x00007fffebdb322b in util_queue_thread_func ()
   from /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fffebdb2e7b in impl_thrd_routine ()
   from /usr/lib64/dri/radeonsi_dri.so
```

**Comment by stsp** [comment]
https://github.com/libsdl-org/SDL/issues/5793
Filled bug upstream.

**Comment by stsp** [comment]
As per SDL devs, they have now
rendering and post-processing separated.
I can disable the HW post-processing
separately, but should I do that?
@stefand could you please check
how it works now? I think we now
have the HW scaling and post-processing
with SW rendering. Which looks like
a very good combo to me.
But does it work?

**Comment by stsp** [comment]
Fixed to some extent, but not
for the fedora-provided build.

**Comment by Nobody-Special** [comment]
Is this issue still relevant since #1957 is closed?

**Comment by stsp** [comment]
Well, its relevant in a sense that we
still are not sure if its safe to use an
acceled fb when rendering is threaded.
But since no one have complained
(except for the WSL2-related crash
that Bart recently worked around),
and given that there will be no
unaccelerated wayland support anyway,
and given that the aforementioned
upstream bug is already fixed, lets
close this.

Essentially we'll get our rendering
done rightly only with sdl3. And I
am already donating them on patreon
for this and other features for us to
materialize.
