### ISSUE TITLE
weird build failures on LP

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1670]
The build log is full of crap,
like:
https://launchpadlibrarian.net/606658021/buildlog_ubuntu-impish-amd64.dosemu2_2.0~pre9-7462-c6941207d+202206120316~ubuntu21.10.1_BUILDING.txt.gz
```
during RTL pass: sched2
/<<PKGBUILDDIR>>/build/../src/base/core/int.c: In function ‘int33_unrevect_fixup’:
/<<PKGBUILDDIR>>/build/../src/base/core/int.c:1746:1: internal compiler error: in move_insn, at haifa-sched.c:5471
 1746 | }
...
-ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -o coopth.o /<<PKGBUILDDIR>>/build/../src/base/core/coopth.c
The bug is not reproducible, so it is likely a hardware or OS problem.
make[3]: *** [/<<PKGBUILDDIR>>/build/../src/Makefile.common.post:89: int.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

I am especially puzzled with the
"bug is not reproducible" sentence...

https://launchpadlibrarian.net/606657812/buildlog_ubuntu-focal-amd64.dosemu2_2.0~pre9-7462-c6941207d+202206120316~ubuntu20.04.1_BUILDING.txt.gz
This one fails during configure...

So while I very well expected
the hundreds of problems after
those "heavy threading" games,
I thought they are going to be
run-time, not compile-time or
configure-time...

**Comment by stsp** [comment]
Filled in gcc bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105936

This doesn't seem to even be
related to recently added threading,
so not sure why everything suddenly
broke.

**Comment by stsp** [comment]
The backport to gcc-10 branch
have happened.
@skitt would you like to make
sure it hits debian? That may
eventually make it into ubuntu.
Also the gcc-9 branch should
be updated manually as for gcc
upstream it is EOL.

**Comment by andrewbird** [comment]
I hit the same thing on Debian 11 when building packages just now. I did notice that my non package builds on Ubuntu 20.04 still work, so perhaps there's some different compilation flags used for the packages that trigger it?

**Comment by stsp** [comment]
Which ones do you use?
Anyway, I think switch to clang
would be the right answer.

**Comment by andrewbird** [comment]
Nothing special to me, just the standard `compiletime-settings.devel`.

**Comment by stsp** [comment]
devel!
No optimization is enabled.

**Comment by andrewbird** [comment]
~~Mmm I don't know what's going on but the problem now seems to have infected @tkchia's ia16-gcc too, see https://github.com/tkchia/gcc-ia16/issues/113 . There's an interesting titbit about `-O1` working but not `-O2`.~~

Edit: I may be just seeing a pattern where there isn't one, on closer examination the internal compiler error is different!

**Comment by stsp** [comment]
Filled ubuntu ticket:
https://bugs.launchpad.net/dosemu2/+bug/1978504

**Comment by stsp** [comment]
Hmm, I didn't mean to fill it as
dosemu2 bug...
Needs resubmitting.

**Comment by stsp** [comment]
No, wasn't filled against dosemu2.
Just some weird magic about URL
fiddling on LP.
Anyway, filled another one:
https://bugs.launchpad.net/bugs/1979054

**Comment by stsp** [comment]
Switched to clang.
