### ISSUE TITLE
Amazon Guardian of Eden hangs during intro

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1671]
**Describe the bug**
The game hangs on this screen:
![Screenshot_20220612_140753](https://user-images.githubusercontent.com/877112/173232453-ccbc5f67-079b-4479-85df-1ba66f4dfd8a.png)

**To Reproduce**
Install and run the game.

**Attach program/game binaries or provide an URL**
[amazon.tar.gz](https://github.com/dosemu2/dosemu2/files/8885798/amazon.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8885799/boot.log)

**A regression?**
Unknown

**Comment by stsp** [comment]
> A regression?
> Unknown

Well, not the right time for
that. I added threading so
the info about a regression
is very needed.

**Comment by jschwartzenberg** [comment]
Same behavior with b10018cc6393d083f385c3ac0ae3d7ba20115c7e

**Comment by stsp** [comment]
You can ignore that error
on exit, or do the full rebuild.

**Comment by jschwartzenberg** [comment]
Yeah, will just ignore it. Does that revision still make sense for testing otherwise?

**Comment by stsp** [comment]
No, needs to go 6ac304fb or
below, where everything was
still calm.

**Comment by jschwartzenberg** [comment]
Seems with 4313fdc51b49a2f112a69a5bdc211f5e49f50429 the game doesn't even start.

**Comment by jschwartzenberg** [comment]
Ah tried again, same hang.

**Comment by stsp** [comment]
Works on pre9.

**Comment by stsp** [comment]
Bisect: 77177b04

**Comment by stsp** [comment]
Should now be fixed.
But you still need
`$_timer_tweaks = (on)`

**Comment by jschwartzenberg** [comment]
Yep, that helps. I know get a terminal filled with:
```
ERROR: callback queue overflow, pic
ERROR: callback queue overflow, pic
ERROR: callback queue overflow, pic
ERROR: callback queue overflow, pic
ERROR: callback queue overflow, pic
```
[boot.log](https://github.com/dosemu2/dosemu2/files/8903135/boot.log)

And no sound. Separate issues?

**Comment by jschwartzenberg** [comment]
Btw. is there any disadvantage having `$_timer_tweaks = (on)` (by default)?

**Comment by stsp** [comment]
It probably has a pc-speaker
sound which we do not support.
And I can't reproduce this overflow.

**Comment by jschwartzenberg** [comment]
Yeah indeed it's pc-speaker. I misremembered what I heard in DOSBox.

**Comment by stsp** [comment]
> Btw. is there any disadvantage having $_timer_tweaks = (on) (by default)?

If you know any other way
to find out, than to do that
and wait for bug reports,
then let me know. :)
But when everything is
already broken and LP is
not building, and timer's
stack is half-written,
this isn't going to help.

**Comment by jschwartzenberg** [comment]
Yeah, I was just curious if you were aware of disadvantages at this point :)

**Comment by stsp** [comment]
Sure, it can break some multitaskers.
Of course we can do it dosemu1-way,
like adding a watch-dog over a stalled
timer, and to use the internal stack to
not push an extra frame to user's stack...
But I'd rather not do that.
Yes, dosemu1 could run all these by
default. We should do that too, but
not necessarily by applying hack over
hack over hack. But, for example, by
applying the binary patches at run-time.
