### ISSUE TITLE
Diggers doesn't register mouse clicks

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1672]
**Describe the bug**
I can't click on anything

**To Reproduce**
Run the game, use crtl+alt+home to capture the mouse, try to click a button.

**Attach program/game binaries or provide an URL**
[diggers.tar.gz](https://github.com/dosemu2/dosemu2/files/8886618/diggers.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8886619/boot.log)

**A regression?**
The problem occurs also with 499d99323f29d642155297c83e4ad9bc104502a5.

**Comment by stsp** [comment]
Nah, who cares about digger,
if we won't have LP builds in any
near future. :)

**Comment by stsp** [comment]
It needs some installation,
Please pack the already installed
one.

**Comment by jschwartzenberg** [comment]
[diggers.tar.gz](https://github.com/dosemu2/dosemu2/files/8902964/diggers.tar.gz)
Here's the installed game.

**Comment by stsp** [comment]
Works perfectly here.
I can click both in menu
(to start the game) and in
a game itself.

**Comment by jschwartzenberg** [comment]
You can't reproduce? I couldn't get through the menu. I'll try it on another system.

**Comment by jschwartzenberg** [comment]
Clicks seem to work now, but I can't mouse the mouse up. When I move up, it jumps to the upper left corner. Does the mouse really work without any issues on your end?

**Comment by stsp** [comment]
Even with Ctrl-Alt-Home?
Yes, works perfectly here.
