### ISSUE TITLE
Multiple DPMI clients may cause DosEmu to "lock" ( "endless" loop )

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1677]
**Describe the bug**
DosEmu supports multiple DPMI clients ( one client starting another one ), and this works in principle.
If the launching client has hooked into an interrupt vector chain ( int 0x21 for example ), there's apparently that "loop" problem if the new client uses that interrupt in protected-mode.

**To Reproduce**
The simple dpmi.exe program, started with cmdline parameter "-z", should trigger that behavior. That option causes the program to hook into int 0x21 and then start another instance of itself. 

**Attach program/game binaries or provide an URL**
[DPMI.EXE.zip](https://github.com/dosemu2/dosemu2/files/8901934/DPMI.EXE.zip)

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/8901937/boot.log.zip)

I removed about 10,000,000 lines from the log with repeating info.

**Additional info**
I tested dpmi.exe with option -z under plain DOS with hdpmi, in WinXP's NTVDM, in a Win95 DOS-Box and even in a Win31 DOS-BOX. In all environments the little program works as expected.

**Comment by andrewbird** [comment]
Do you have the source for the little test program as it might be nice to add it to the Dosemu test suite, if you are agreeable?

**Comment by Baron-von-Riedesel** [comment]
yes.
https://github.com/Baron-von-Riedesel/HX/tree/master/Src/DPMI

**Comment by stsp** [comment]
Should now be fixed.
vtmr and coopth make debugging
of dpmi interrupts a nightmare.

**Comment by Baron-von-Riedesel** [comment]
I#d like to try, but got an internal compiler error:

gcc -c -imacros config.hh -MD -DCFLAGS_STR=" -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -fpie -O2   " -I../../../src/include -I../../../src/plugin/include -I../../../src/base/bios/x86 -I/home/sam/dosemu2/src/include -I/home/sam/dosemu2/src/base/lib  -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -fpie -O2    -o int.o int.c
during RTL pass: sched2
int.c: In function ‘int33_unrevect_fixup’:
int.c:1748:1: internal compiler error: in move_insn, at haifa-sched.c:5471

with compiler

gcc (Debian 10.2.1-6) 10.2.1 20210110

**Comment by stsp** [comment]
This is already fixed in upstream gcc
(look in a nearby ticket for more info)
but you need to ping debian to get the
patch quickly.
For now dosemu is buildable on copr
(fedora) but not on LP.

**Comment by stsp** [comment]
https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=f2851a7cff4d74edca26d39c7bfa1264355a22ed
So you need to ask debian
to include this patch.

**Comment by Baron-von-Riedesel** [comment]
> So you need to ask debian to include this patch.

Thanks for the hint!
I remember that a few years ago I wanted to register to the "official" debian forum, but the try was rejected because I was "a known spammer"!

So I better avoid any contact to those guys... :))
and will do nothing until the problem "has fixed itself"...

**Comment by stsp** [comment]
I had the very same thing
with ubuntu forums, when I
used the list.ru e-mail domain.
You can see that hilarious
thread here:
https://bugs.launchpad.net/ubuntuforums.org/+bug/1786920

> So I better avoid any contact to those guys... :))

Exactly what I did in the
aforementioned thread. :)

**Comment by stsp** [comment]
> and will do nothing until the problem "has fixed itself"..

Oh, you can try
`CC=clang ./default-configure`.
And if that works, we should
probably just switch to clang.
I don't know what makes it so
difficult, considering that only
clang can be used to build
fdpp, and now the same with
dosemu2.

**Comment by andrewbird** [comment]
>> Do you have the source for the little test program as it might be nice to add it to the Dosemu test suite, if you are agreeable?

> yes.
https://github.com/Baron-von-Riedesel/HX/tree/master/Src/DPMI

Thanks, I hadn't realised it was your usual dpmi test program. I'm already using an older version of it (218) and just use the binary from the zip on your github. I'll see about adding the `-z` test to our suite.
