### ISSUE TITLE
Seven Cities of Gold hangs on start-up

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1678]
**Describe the bug**
Starting the game doesn't get far:
![Screenshot_20220614_211343](https://user-images.githubusercontent.com/877112/173670365-480a9df6-290e-46cf-a740-4d98876bf925.png)

**To Reproduce**
Install the game, start the game.

**Attach program/game binaries or provide an URL**
See #1668

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8903170/boot.log)

**A regression?**
Need to check

**Comment by stsp** [comment]
Please pack the installed one.

**Comment by jschwartzenberg** [comment]
[7cities.tar.gz](https://github.com/dosemu2/dosemu2/files/8931409/7cities.tar.gz)

**Comment by stsp** [comment]
Here's the patch:
```
Comparing C:\7cities\7cities.old and C:\7cities\7cities.exe
000049DE:     72  90
000049DF:     D8  90
```

Please update emufailures on wiki
coz I am a bit tired. ;)
