### ISSUE TITLE
Build scripts/instructions: trouble with tkchia ppa

### ISSUE THREAD

**Issue by RossBoylan** [dosemu2/dosemu2#1679]
**Describe the bug**

Preparing to build from source, early setup adds the `tkchia` PPA.  After enabling it, `apt update` fails.

Inspection of the ppa, specifically http://ppa.launchpad.net/tkchia/build-ia16/ubuntu/dists/ shows no entry for kinetic, which is what the sources.list entry seeks.

**To Reproduce**

0. This is on a Debian 11 (stable, bullseye) system, amd64 architecture
1. As previously [reported](https://github.com/dosemu2/dosemu2/issues/1649), `add-apt-repository` doesn't work, at least with Ubuntu ppa's on this system.  Since the setup script executes this command as the first step, that's a problem.
2. Fix the [bug in add-apt-repository](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012649).  See the report there for a much fuller analysis and suggested fix.  Eventually I'll get the patch I'm using up there (also available below).
3. Having manually taken care of the first repository, `dosemu2`, while diagnosing the problem above, complete the steps at the start of `ci_prereq.sh`:  
```shell
sudo add-apt-repository -y ppa:jwt27/djgpp-toolchain
sudo add-apt-repository -y ppa:tkchia/build-ia16
```
These run without complaints.
4. The next step in the script is to update the package information:
```shell
# date; apt update
Tue 14 Jun 2022 10:53:39 PM PDT
Hit:1 http://localhost:3142/debian bullseye InRelease
Hit:2 https://packages.microsoft.com/repos/vscode stable InRelease
Hit:3 http://localhost:3142/debian-security bullseye-security InRelease
Hit:4 http://ppa.launchpad.net/dosemu2/ppa/ubuntu kinetic InRelease
Get:5 http://ppa.launchpad.net/jwt27/djgpp-toolchain/ubuntu kinetic InRelease [18.1 kB]
Ign:6 http://ppa.launchpad.net/tkchia/build-ia16/ubuntu kinetic InRelease
Get:7 http://ppa.launchpad.net/jwt27/djgpp-toolchain/ubuntu kinetic/main i386 Packages [1,040 B]
Get:8 http://ppa.launchpad.net/jwt27/djgpp-toolchain/ubuntu kinetic/main amd64 Packages [1,712 B]
Get:9 http://ppa.launchpad.net/jwt27/djgpp-toolchain/ubuntu kinetic/main Translation-en [652 B]
Err:10 http://ppa.launchpad.net/tkchia/build-ia16/ubuntu kinetic Release
  404  Not Found [IP: 185.125.190.52 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/tkchia/build-ia16/ubuntu kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
5. Verify the `tkchia` distributions do not have a `kinetic` entry

**Comments**

1. The instructions and the commands to add the repositories do not mention `kinetic`.  It seems  likely that `add-apt-repository` came up with it on its own as either the current release, or the release that was current when Debian 11 was frozen (pretty recently).
2. So one solution might be to change the release name in the sources.list entry.  What it should be, and whether they all need to be the same, I don't know.  My guess is all 3 PPA's should be using the same release.  This involves manually editing after the fact.
3. A longer-term fix would be to change the script and instructions to specify an appropriate release.  I *suspect* `add-apt-repository` may support this because the man page says "In the third form, the given distribution component will be enabled for all sources."  But the man page is badly mangled--there is no 3rd form shown--and I'm not sure if "component" and "release" are the same things.
4. The error message suggests that relaxing security might be a solution.  I don't think that would help at all in this case, since the file, and the accompanying release, is just absent.
5. Another "solution" would be for `tkchia` to add the `kinetic` release.

**The Patch**
`add-apt-repository` is from the `software-properties` source package.  It ends up calling `ppa.py`, which is what needs the fix.  Starting at line 270, my modified version is
```python
        res = subprocess.call(["apt-key", "--keyring", apt_keyring, "add",
            tmp_export_keyring])
```
In the original, the last argument is `tmp_keyring`, which fails because that file is in keybox format.
Newer versions of `gpg` exhibit this pickiness; I gather older ones didn't.

**Comment by andrewbird** [comment]
Hello Ross,
   I should point out that `ci_prereq.sh`,`ci_build.sh` and `ci_test.sh` exist only to setup the environment (the ci means continuous integration) for the dosemu2 test suite to run. That test suite is not part of the mandatory build process from source. So I see you are trying to get `ci_prereq.sh` to run cleanly in order to install all the requisite build packages. That's probably my fault, as somewhere in the past I may have recommended it on an issue ticket as a quick way of doing things on Ubuntu, even though extra packages are installed that are only required for running the test suite.
   The salient part of this is that PPAs (jwt27 and tkchia) are not required to build dosemu2, the package fdpp usually obtained from Dosemu2 PPA is. I think you can avoid that PPA also by building a Debian fdpp from source first.

**Comment by andrewbird** [comment]
I should also have said the definitive build requirements for debian packages will always be found in

https://github.com/dosemu2/dosemu2/blob/55afca4547477c5bfe44af89dae484b79227659d/debian/control

and

https://github.com/dosemu2/fdpp/blob/068b5eee1f5b1fd87aa9a1fb7ceb703b5e3970da/debian/control

**Comment by stsp** [comment]
> as somewhere in the past I may have recommended it on an issue ticket

https://github.com/dosemu2/dosemu2/wiki/Building-From-Source
You recommended it right here.

**Comment by andrewbird** [comment]
It is recommended there, but not by myself according to the change history. Here's the first occurrence I can find of when `ci_prereq.sh` occurs outside of the test regime context https://github.com/dosemu2/dosemu2/issues/1485 . It seems this is also the guy that wrote the wiki entry using it. However since github doesn't cc emails from sender to sender, I don't have any prior comment (to find in my search) that I might have written myself.

**Comment by stsp** [comment]
OK, well, please fix the wiki then,
if possible, thanks. :)

**Comment by RossBoylan** [comment]
Yes; I was just following the instructions at https://github.com/dosemu2/dosemu2/wiki/Building-From-Source.

The debian control file will only work if everything it needs is present, and I gather that's quite problematic. I recall seeing the history of attempts to package it on Debian, which ran afoul of dependencies on various binary only and/or proprietary tools.  Oddly, I can't find those  reports now, and perhaps things have changed.  I know I've built it in the past with the help of some binary blobs.

**Comment by andrewbird** [comment]
I just ran through building FDPP and Dosemu2 packages on a Debian 11 VM here. I documented it in the wiki https://github.com/dosemu2/dosemu2/wiki/Building-packages-for-Debian . That said it doesn't currently complete building the Dosemu2 packages because I'm hitting the 'GCC internal compiler error` that's affecting even our Ubuntu builds.

**Comment by stsp** [comment]
I replaced `cp` with `ln` in
command.com section.

**Comment by andrewbird** [comment]
Sounds good.

**Comment by stsp** [comment]
Well, cool but I am not sure such
approach is future-proof.
Who will update the doc once some
other dep is added?
I am quite sure there might be a
tool somewhere to DL all deps and
then build the deb.
Does anyone know such tool?

**Comment by andrewbird** [comment]
I wrote a little bit of python to extract the build deps from fdpp / dosemu then dedupe them, but I don't know how to handle alternatives such as 'lld | lld-8'. 
```python
from debian import deb822                                                       
                                                                                
import re                                                                       
                                                                                
                                                                                
def get_build_depends(fname):                                                   
    with open(fname) as f:                                                      
        rel = deb822.Deb822(f)                                                  
        s = re.sub(r'\(.+\)', r'', rel['Build-Depends'] )                       
        l = [x.strip() for x in s.split(',')]                                   
        return l                                                                
                                                                                
                                                                                
l1 = get_build_depends("../fdpp.git/debian/control")                            
l2 = get_build_depends("debian/control")                                        
                                                                                
# Add together and deduplicate                                                  
l3 = list(set(l1 + l2))                                                         
                                                                                
print(' '.join(l3))                                                             
```

~~~
$ python3 t.py 
autotools-dev libxext-dev debhelper libreadline-dev libslang2-dev make xfonts-utils clang bash libsdl2-image-dev ladspa-sdk libbsd-dev binutils-dev libsdl2-ttf-dev fdpp-dev pkg-config git libslirp-dev binutils gawk libsdl2-dev libjson-c-dev libelf-dev linuxdoc-tools libx11-dev libgpm-dev diffutils autoconf libfontconfig1-dev coreutils libao-dev automake bison lld | lld-8 flex libieee1284-3-dev nasm libasound2-dev libfluidsynth-dev sed libstdc++-10-dev findutils
~~~

**Comment by stsp** [comment]
> alternatives such as 'lld | lld-8'.

Perhaps check them with `apt-cache`?

**Comment by andrewbird** [comment]
It seems there are many to choose from on my system
~~~
apt-cache search lld | grep '^lld[ -]'
lld - LLVM-based linker
lld-10 - LLVM-based linker
lld-6.0 - LLVM-based linker
lld-7 - LLVM-based linker
lld-8 - LLVM-based linker
lld-9 - LLVM-based linker
lld-11 - LLVM-based linker
lld-12 - LLVM-based linker
~~~

**Comment by stsp** [comment]
Try a simple rule: if left-side
operand (`lld`) is found in cache -
use that. Otherwise validate
right operand.
I'll put "more generic" names
at a left side.

**Comment by RossBoylan** [comment]
`mk-build-deps` in `devscripts` makes a binary package that has all the build dependencies of the control file.  Installing it (`dpkg -i`) should force their installation.  Did you have something like that in mind?

There's also `dpkg-genbuilddeps` but that looks much more heavy weight, and might even require you to have already solved the problem since it watches what you need as you do a build, which of course is impossible if you don't have the dependencies.

**Comment by andrewbird** [comment]
>  Did you have something like that in mind?

Yes that's exactly what I've been looking for! I tried it out on my Ubuntu system, though I needed to install the `equivs` package before it would work. It seems the build wiki for debian 11 can now be simplified somewhat.

**Comment by andrewbird** [comment]
Thanks to @RossBoylan's little gem, the wiki page got a lot cleaner.

**Comment by stsp** [comment]
Its still quite broken.
`sudo dpkg -i dosemu2-build-deps*.deb`
just complains about missing deps.

**Comment by stsp** [comment]
Hmm, well, it actually schedules
the missing packages for the next
`apt install -f` so the doc is correct.
But I wonder if there is a less confusing
technique. People do not like getting
an errors, and also that error sets
non-zero exit status.
I am surprised apt implemented it that
way...

**Comment by skitt** [comment]
> Its still quite broken. `sudo dpkg -i dosemu2-build-deps*.deb` just complains about missing deps.

That can’t work on its own (you need `apt install -f` as you saw), you need to run `sudo apt install ./dosemu2-build-deps*.deb` if you want a single-step install command.

**Comment by stsp** [comment]
`you need to run sudo apt install ./dosemu2-build-deps*.deb`

Ah, if this is the only way that works,
then the doc is still incorrect. Its just
that I tried exactly
`sudo apt install ./dosemu2-build-deps*.deb`
after seeing the failure from dpkg, and I
wasn't sure which one have scheduled
the update on `install -f`.

So the doc needs to be fixed, but I still
can't get the 1-step install from that.
`sudo apt install ./dosemu2-build-deps*.deb`
also errors out.

**Comment by andrewbird** [comment]
So is it the ./ that tells apt install that I want to install the 'filename.deb' found on my local filesystem rather than lookup 'filename.deb'  as if it were a package name in the repo?

**Comment by stsp** [comment]
Yes, that seems to be the case
about `./`. And according to @skitt 
I think you need to do exactly that,
not dpkg, to schedule the `install -f`.

Its very confusing.
Can someone please come up
with the single-step install, pretty
please? :)

**Comment by stsp** [comment]
Hmm, but the single-step install
will also install that -build-deps*
package itself! Which we don't need...
So there can't be a single-step
solution? :(

**Comment by stsp** [comment]
Well, please come up with at least
a single-line solution then. :)
Passing error msgs to /dev/null
and being resistant to `-o pipefail`
and alike things... crap.

**Comment by skitt** [comment]
Yes, there is a single-step solution, using `mk-build-deps` itself: `mk-build-deps --install --root-cmd sudo --remove`. This will generate the build-dependency package, install it along with all dependencies, then remove it, leaving the dependencies in place.

**Comment by skitt** [comment]
> So is it the ./ that tells apt install that I want to install the 'filename.deb' found on my local filesystem rather than lookup 'filename.deb' as if it were a package name in the repo?

Pretty much; any path works, so really it’s the presence of a `/` which determines the behaviour.

**Comment by stsp** [comment]
> This will generate the build-dependency package, install it along with all dependencies, then remove it,

Why can't it just install the deps,
w/o any singing and dancing?
But oh well.
Sounds "good". :)

**Comment by stsp** [comment]
How to de-schedule this `install -f`
stuff?

**Comment by skitt** [comment]
> How to de-schedule this `install -f` stuff?

Remove the build-dependency package. `install -f` doesn’t perform a “scheduled” installation, it fixes broken dependencies; if you remove the package causing the broken dependency, `install -f` no longer has anything to do.

**Comment by stsp** [comment]
I don't understand.
Remove in what sense?
From disk? Or as in "uninstall"?
I don't think it was installed, it
errored out instead. Or was it
installed nevertheless?

Ah, checked with `dpkg-query -s`.
Indeed is was installed!
Also `dpkg -i`, as in the current doc,
is actually doing the same thing, so
the doc works.

So while `dpkg -i` at least writes the
long msg that the packaged is installed
but not configured, apt fails with the
hard error and no indication that it
actually installed something... except
that it did.
Sigh.

**Comment by stsp** [comment]
So in this case the current doc
doesn't mention how to remove
that unneeded deps package.
So I suppose,
`mk-build-deps --install --root-cmd sudo --remove`
should be used instead.

**Comment by skitt** [comment]
I’ve updated the wiki to use that instead.

**Comment by stsp** [comment]
> I’ve updated the wiki to use that instead.

Only in fdpp paragraph though.

**Comment by skitt** [comment]
Ah yes, I missed the second one, fixed.

**Comment by stsp** [comment]
Thanks!

@RossBoylan does this help?

**Comment by andrewbird** [comment]
@skitt Thanks for the info on `apt install ./somepackage.deb`, all my debian life I've been doing `dpkg -i somepackage.deb ; apt install -f` and always thought it was pretty crap. Now you've enlightened me I'll never go back!

**Comment by RossBoylan** [comment]
I add my thanks to @skitt: I had tried `apt install` with a deb and failed; I didn't know I needed a `/` to get the correct interpretation.

The instructions in https://github.com/dosemu2/dosemu2/wiki/Building-packages-for-Debian may now be getting me to the expected compiler error.  That means I can't actually build the package (still). Would using `clang` work better?
I get to the step of building dosemu2 and see

```
gcc -c -imacros config.hh -MD -DCFLAGS_STR=" -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -ggdb3 -fpie   -g -O2 -ffile-prefix-map=/usr/local/src/dos/dosemu2=. -fstack-protector-strong -Wformat -Werror=format-security" -I../../../src/include -I../../../src/plugin/include -I../../../src/base/bios/x86 -I/usr/local/src/dos/dosemu2/build/../src/include -I/usr/local/src/dos/dosemu2/build/../src/base/lib -Wdate-time -D_FORTIFY_SOURCE=2 -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -ggdb3 -fpie   -g -O2 -ffile-prefix-map=/usr/local/src/dos/dosemu2=. -fstack-protector-strong -Wformat -Werror=format-security -o render.o /usr/local/src/dos/dosemu2/build/../src/base/video/render.c
during RTL pass: sched2
/usr/local/src/dos/dosemu2/build/../src/base/core/int.c: In function ‘int33_unrevect_fixup’:
/usr/local/src/dos/dosemu2/build/../src/base/core/int.c:1748:1: internal compiler error: in move_insn, at haifa-sched.c:5471
 1748 | }
      | ^

## leading to
make[2]: Leaving directory '/usr/local/src/dos/dosemu2/build/src'
make[1]: *** [Makefile:30: default] Error 2
make[1]: Leaving directory '/usr/local/src/dos/dosemu2/build'
dh_auto_build: error: cd build && make -j8 returned exit code 2
make: *** [debian/rules:6: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed
make: *** [Makefile:65: deb] Error 29

```

There are also some warnings like
```
gcc -c -imacros config.hh -MD -DCFLAGS_STR=" -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -ggdb3 -fpie   -g -O2 -ffile-prefix-map=/usr/local/src/dos/dosemu2=. -fstack-protector-strong -Wformat -Werror=format-security" -I../../../../src/include -I../../../../src/plugin/include -I../../../../src/base/bios/x86 -I/usr/local/src/dos/dosemu2/build/../src/include -I/usr/local/src/dos/dosemu2/build/../src/base/lib -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/local/src/dos/dosemu2/build/../src/base/lib/mcontext -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -ggdb3 -fpie   -g -O2 -ffile-prefix-map=/usr/local/src/dos/dosemu2=. -fstack-protector-strong -Wformat -Werror=format-security -o debug.o /usr/local/src/dos/dosemu2/build/../src/arch/linux/async/debug.c
gcc -c -imacros config.hh -MD -DCFLAGS_STR=" -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -ggdb3 -fpie   -g -O2 -ffile-prefix-map=/usr/local/src/dos/dosemu2=. -fstack-protector-strong -Wformat -Werror=format-security" -I../../../src/include -I../../../src/plugin/include -I../../../src/base/bios/x86 -I/usr/local/src/dos/dosemu2/build/../src/include -I/usr/local/src/dos/dosemu2/build/../src/base/lib -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/local/src/dos/dosemu2/build/../src/include/keyboard -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -ggdb3 -fpie   -g -O2 -ffile-prefix-map=/usr/local/src/dos/dosemu2=. -fstack-protector-strong -Wformat -Werror=format-security -o keymaps.o /usr/local/src/dos/dosemu2/build/../src/base/kbd_unicode/keymaps.c
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c: In function ‘init_bins’:
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c:1265:40: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
 1265 | #define smallbin_at(M, i)   ((sbinptr)((char*)&((M)->smallbins[(i)<<1])))
      |                                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c:2268:19: note: in expansion of macro ‘smallbin_at’
 2268 |     sbinptr bin = smallbin_at(m,i);
      |                   ^~~~~~~~~~~
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c: In function ‘prepend_alloc’:
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c:1265:40: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
 1265 | #define smallbin_at(M, i)   ((sbinptr)((char*)&((M)->smallbins[(i)<<1])))
      |                                       ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c:1427:38: note: in definition of macro ‘RTCHECK’
 1427 | #define RTCHECK(e)  __builtin_expect(e, 1)
      |                                      ^
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c:1962:26: note: in expansion of macro ‘smallbin_at’
 1962 |   else if (RTCHECK((F == smallbin_at(M,I) || ok_address(M, F)) &&\
      |                          ^~~~~~~~~~~
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c:2151:20: note: in expansion of macro ‘unlink_small_chunk’
 2151 |   if (is_small(S)) unlink_small_chunk(M, P, S)\
## and many more, ending
/usr/local/src/dos/dosemu2/build/../src/base/lib/misc/dlmalloc.c:3309:11: note: in expansion of macro ‘insert_chunk’
 3309 |           insert_chunk(fm, p, psize);
      |           ^~~~~~~~~~~~
0x7f9f27b4ad09 __libc_start_main
	../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
```

**Comment by stsp** [comment]
> Would using clang work better?

`CC=clang ./default-configure && make clean && make -j 9`
and let us know.

**Comment by andrewbird** [comment]
`CC=clang ./default-configure && make clean && make -j 2` seems to build fully on Debian 11 for me. How would one adapt the package to build with clang?

**Comment by stsp** [comment]
Probably by adding clang to
Build-Depends and doing
something like
`export CC=clang` in debian/rules?

**Comment by RossBoylan** [comment]
Convincing the debian build to switch compilers seems a bit tricky: https://wiki.debian.org/CrossBuildPackagingGuidelines#Setting_the_correct_compiler.  Not exactly following the advice there, I tried
```shell
export CC=clang
make deb

# and then
DEB_BUILD_OPTIONS=CC=cmake make deb

#and then
export DEB_BUILD_OPTIONS=CC=cmake
make deb
```
(from the top level directory), none of which persuaded it to use `clang`.  The use of `DEB_BUILD_OPTIONS` was a guess based on examining `buildtools.mk`.

Argh!  That should be `CC=clang` consistently.  Unfortunately, repeating the last step with that correction still gets gcc as the compiler.

**Comment by RossBoylan** [comment]
`DEB_BUILD_OPTIONS` [policy](https://www.debian.org/doc/debian-policy/ch-source.html) in section 4.9.1 says flags should be lowercase, and  there are none to change `CC`, though `noopt` presumably affects optimization.  The policy also says unrecognized options should be ignored.  The tops of my build logs actually show

```shell
$ make deb
Thu 16 Jun 2022 05:28:58 PM PDT
debuild -i -us -uc -b
 dpkg-buildpackage -us -uc -ui -i -b
dpkg-buildpackage: warning: invalid flag in DEB_BUILD_OPTIONS: CC=clang
dpkg-buildpackage: info: source package dosemu2
```
So I guess it's not surprising setting it had no effect.

I tried `export CC=clang` in the `debian/rules` file.  **This seems to work.**  Build proceeded without errors; there were some warnings about redefining the printf macro.  The debs were created.  

Is there any kind of test suite that can be run to check that the new compiler hasn't introduced new bugs?

There were some errors at the end, though I think all were from lintian (but perhaps they were saved up from earlier?):
```
...
Now running lintian dosemu2_2.0~pre9-1_amd64.changes ...
E: dosemu2 changes: bad-distribution-in-changes-file focal
E: dosemu2: custom-library-search-path usr/lib/dosemu/libplugin_fdpp.so /usr/lib/fdpp
E: dosemu2: depends-on-essential-package-without-using-version Depends: bash
E: dosemu2: depends-on-essential-package-without-using-version Depends: coreutils
W: dosemu2: package-contains-upstream-installation-documentation usr/share/doc/dosemu2/INSTALL
Finished running lintian.
```

The output of the configuration was also a little weird: it said it was using `clang`, and the actual compile steps clearly used it, but the `using a GNU C compiler` test also passed.  Maybe because it's compatible?  E.g.,

```
...
make[1]: Entering directory '/usr/local/src/dos/dosemu2'
dh_auto_configure -O--parallel -- \
	--enable-debug --disable-xbacktrace \
	--with-plugindir=/usr/lib/dosemu \
	--with-x11fontdir=/usr/share/fonts/X11/misc
	cd build && ../configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --enable-debug --disable-xbacktrace --with-plugindir=/usr/lib/dosemu --with-x11fontdir=/usr/share/fonts/X11/misc
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking how to run the C preprocessor... clang -E
....
```

**Comment by RossBoylan** [comment]
Looking ahead to `comcom32`, as long as I did put in the ppa reference, would `apt install comcom32` be equivalent to the steps in the final paragraph of https://github.com/dosemu2/dosemu2/wiki/Building-packages-for-Debian?

**Comment by skitt** [comment]
To specify the compiler when using `debuild`, use `-e`:

    debuild -e CC=clang -i -us -uc -b

**Comment by stsp** [comment]
debuild is only used by `make deb`
under our control. All other uses of
debuild, including the one on LP, are
not via `make deb` so we can't force
-e there.
How can we modify the debian/rules
instead?

**Comment by skitt** [comment]
> How can we modify the debian/rules instead?

https://github.com/dosemu2/dosemu2/pull/1682

**Comment by skitt** [comment]
I’ve filed an issue in Debian too, https://bugs.debian.org/1013122

**Comment by stsp** [comment]
Thanks.
