### ISSUE TITLE
Baby Jo hangs or crashes

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1689]
**Describe the bug**
Whenever I run it, sometimes it seems to hang on the language screen, sometimes I can get it to move to the title screen. Sometimes I see a crash. Something seems buggy.

**To Reproduce**
Unpack, move into `baby`, run `babyjo`

**Attach program/game binaries or provide an URL**
[baby.tar.gz](https://github.com/dosemu2/dosemu2/files/8934236/baby.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8934237/boot.log)

**A regression?**
unknown, I should test

**Comment by stsp** [comment]
Maybe timer_tweaks?

**Comment by jschwartzenberg** [comment]
Yep that solves it...

**Comment by stsp** [comment]
Update the docs.

**Comment by jschwartzenberg** [comment]
Added to wiki.
