### ISSUE TITLE
Debian installation instructions: trouble near the end

### ISSUE THREAD

**Issue by RossBoylan** [dosemu2/dosemu2#1690]
**Describe the bug**
This is a problem with the documentation on https://github.com/dosemu2/dosemu2/wiki/Building-packages-for-Debian.

`apt install` refuses to install the `dosemu2` package, I believe because of a missing dependency on `comcom32`.

**To Reproduce**
I roughly followed the [instructions](https://github.com/dosemu2/dosemu2/wiki/Building-packages-for-Debian) up to the step of installing `dosemu2`.  I did not `apt install` it.

Then I skipped to installing `comcom32`.  The path given for the zip file was incorrect; I corrected it on the wiki and used that path to retrieve it, following the remainder of the steps to install it.

The I attempted to install `dosemu2` as instructed:

```shell
root@barley:/usr/local/src/dos# date; apt install ./dosemu2_2.0~pre9-1_amd64.deb 
Sat 18 Jun 2022 12:12:52 PM PDT
# ...
Note, selecting 'dosemu2' instead of './dosemu2_2.0~pre9-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dosemu2 : Depends: comcom32 (>= 0.1~alpha2) but it is not installable
           Recommends: fluid-soundfont-gm but it is not going to be installed
           Recommends: install-freedos but it is not installable
E: Unable to correct problems, you have held broken packages.
root@barley:/usr/local/src/dos# dpkg -l dosemu2
dpkg-query: no packages found matching dosemu2
```
Note particularly "selecting 'dosemu2' instead of './dosemu2_2.0~pre9-1_amd64.deb' ".  This might be the result of having earlier put the `dosemu2` ppa in my apt sources list (since removed); however I never installed it that way, and I don't see it in the cache.  Maybe it's just a standard notification of the package name being extracted from the longer filename?

Having skipped ahead, `comcom32.exe` is presumably where it needs to be; the problem is that was done outside the package system and so formally its package is not installed.

The last `dpkg -l` shows no sign of the package being installed, even in a broken state.

I'm not sure how important the lack of `fluid-soundfont-gm` and `install-freedos` are; obviously the instructions provide for building `fdpp`, which I think basically is freedos.

**Work-around?**

Use `dpkg -i` instead of `apt install`:

```shell
# date; dpkg -i dosemu2_2.0~pre9-1_amd64.deb 
Sat 18 Jun 2022 12:15:53 PM PDT
Selecting previously unselected package dosemu2.
(Reading database ... 435193 files and directories currently installed.)
Preparing to unpack dosemu2_2.0~pre9-1_amd64.deb ...
Unpacking dosemu2 (2.0~pre9-1) ...
dpkg: dependency problems prevent configuration of dosemu2:
 dosemu2 depends on comcom32 (>= 0.1~alpha2); however:
  Package comcom32 is not installed.

dpkg: error processing package dosemu2 (--install):
 dependency problems - leaving unconfigured
# ...
Errors were encountered while processing:
 dosemu2
root@barley:/usr/local/src/dos# dpkg -l dosemu2
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
iU  dosemu2        2.0~pre9-1   amd64        fast and secure DOS emulator
```

There are still errors, but the files are put in place.  Final status is Unpacked, which leaves a lot of phases still to go.

In particular, if there are any postinst scripts they probably haven't been run.  But looking in the `debian/` directory of the source it doesn't look as if there are any.

Despite all the problems, when I type dosemu in a shell it launches a DOS window.

**Solutions**

Several alternatives occur:
1. Document the use of `dpkg -i` instead of `apt install` as well as the expected noise and its insignificance (I hope).
2. Instruct people to edit comcom32 out of the `debian/control` file before building dosemu2.
3. Provide instructions (ugh) or a makefile fragment (probably still ugh) to turn the downloaded comcom32.zip into a proper package.
4. Tell people to add the ppa repository to their apt trusted sources.  This would eliminate the current instructions about comcom32, but there are at least 3 drawbacks.
     a) The easy instruction is to use `add-apt-repository`.  But it's currently [broken](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012649), at least in Debian.  So to be useful there'd have to be an alternative, which would be more steps.
     b) This means the ppa versions, built for Ubuntu, would be likely to replace the local ones built for Debian, at least when a new version comes out (if only updates are a problem we could tell people to remove the ppa once installation is done).
     c) Since the packages there are built for Ubuntu it's possible they won't be exactly right for Debian.
5. Use configuration or makefile magic to achieve the equivalent of option 2, but automatically.  Since Debiain and Ubuntu are basically the same, this seems hazardous.  Perhaps more reliable would be testing whether an archive with comcom32 is available.  But that would mean we'd delete a dependency just because it couldn't be satisfied, which kind of defeats the point of a dependency.  It does suggest ...
6. Delete the comcom32 dependency for everyone, or downgrade its priority.  In principle people could use alternatives, right?
7. Instruct people to download the comcom32 deb and install it.  This assume the Ubuntu one would work for Debian.

**Comment by andrewbird** [comment]
Mmm, I didn't think of the comcom32 dependency! Perhaps we could add a step in the wiki to remove it from dosemu's debian/rules file?

**Comment by RossBoylan** [comment]
It's the control file not the rules file.

**Comment by stsp** [comment]
> Perhaps we could add a step in the wiki to remove it from dosemu's 

No.
Just put pre-built comcom32.exe
into comcom32 source dir and do
`sudo make checkinstall`.

**Comment by andrewbird** [comment]
But how is the debian dependency satisfied?

**Comment by stsp** [comment]
Try it and you'll see.

**Comment by andrewbird** [comment]
Okay, I'll take your word for it. Just glad it's fixed.

**Comment by RossBoylan** [comment]
As far as I can tell, the instructions on the wiki haven't changed.  So the problem is not fixed.

Second, what comcom32 source dir?  Following the instructions yields no source for comcom32.  Do you mean a directory under dosemu or outside of it?

**Comment by stsp** [comment]
> As far as I can tell, the instructions on the wiki haven't changed. So the problem is not fixed.

Because everyone can update our
wiki so I though you do.
But it is now updated.
