### ISSUE TITLE
Bridge 7.0 has graphical issues with some text

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1694]
**Describe the bug**
The text here looks strange, in DOSBox, it doesn't.
![Screenshot_20220619_184533](https://user-images.githubusercontent.com/877112/174491605-09c32464-2d1a-45d2-9d7f-4f0051f67f34.png)

**To Reproduce**
Just start the game. In game it's also visible.

**Attach program/game binaries or provide an URL**
[bridge7.tar.gz](https://github.com/dosemu2/dosemu2/files/8935959/bridge7.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8935960/boot.log)

**A regression?**
unknown

**Comment by stsp** [comment]
Tried `$_force_vga_fonts = (on)`?

**Comment by jschwartzenberg** [comment]
I had not, but just did and then the problem is still the same.

**Comment by stsp** [comment]
Could you please re-check?

**Comment by jschwartzenberg** [comment]
Looks great now!
![Screenshot_20220707_211342](https://user-images.githubusercontent.com/877112/177853667-0c3a8ccd-e19c-462a-9cc6-be224abde3d9.png)
