### ISSUE TITLE
Blake Stone hangs on start-up

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1695]
**Describe the bug**
Starting the game, nothing happens.

**To Reproduce**
Unpack, from `bstone` run `bstone.bat`.

**Attach program/game binaries or provide an URL**
[bstone.tar.gz](https://github.com/dosemu2/dosemu2/files/8936411/bstone.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8936412/boot.log)

**A regression?**
unknown

**Additional info**
Happens both with and without timer fixes flag enabled.

**Comment by stsp** [comment]
Not a regression.
But at least I finally fixed dosdebug. :)

**Comment by stsp** [comment]
Tests fail on libi86 again:
https://github.com/dosemu2/dosemu2/runs/6957777415?check_suite_focus=true#step:6:783
And of course all marked as "ok"...
Ideas?

**Comment by andrewbird** [comment]
It's a timeout, all the ones listed passed, but it didn't reach the end of the tests.

**Comment by stsp** [comment]
if all tests passed, how could
it not reach the end? :)

**Comment by stsp** [comment]
As for BlakeStone.
I downloaded bs3.0 from here:
https://legacy.3drealms.com/blake/index.html
and it works perfectly.
And your BlakeStone doesn't
work for me under dosbox either.
So you just need to patch it to
the latest version (patches are
on the same page by URL above).

Please see what patch is needed
to get it working, and update the
doc, thanks. :)

**Comment by andrewbird** [comment]
I said all the ones **listed** passed, those not listed were not run because the overall timeout was hit first and the timeout generated the failure result. With @tkchia's help I'm investigating changing the way we use the libi86 test suite, but currently seeing some performance problems.

**Comment by jschwartzenberg** [comment]
> And your BlakeStone doesn't
> work for me under dosbox either.

It works in my DOSBox, DOSBox-X version 0.83.16.



> So you just need to patch it to the latest version (patches are on the same page by URL above).
> 
> Please see what patch is needed to get it working, and update the doc, thanks. :)

Cool, I'll do that!

**Comment by jschwartzenberg** [comment]
It seems the patcher program doesn't work in DOSEMU. It does work in DOSBox. The version I attached here is 1.00, after using DOSBox to update it to 2.00, it worked also in DOSEMU. I had to copy `bs_aog.exe` to `bstone.exe` to let the patcher proceed, but then I saw it was patching `bs_aog.exe` but not `bstone.exe`. The game runs very slow in DOSEMU though.

**Comment by stsp** [comment]
Huh, maybe 2.0 runs slow.
3.0 runs perfectly fine.

**Comment by jschwartzenberg** [comment]
Here it was also slow. Maybe I should enable tweaks?

**Comment by stsp** [comment]
No because I do not.
Are you running the release
build of dosemu2 or debug?

**Comment by stsp** [comment]
And in fact, it is very slow
on dosbox...
We might be living in a parallel
universes. :) Its not for the first
time when the results contradict.

**Comment by stsp** [comment]
Also please make sure you have
not configured the game for the
use of a pc-speaker.

**Comment by stsp** [comment]
> And in fact, it is very slow
> on dosbox...

Note that I am running the
stuff on a retro-pc where
dosbox is always slow, but
dosemu2 is blazingly fast
(in a release builds).

**Comment by jschwartzenberg** [comment]
In DOSBox it runs ok here. But I think you use another DOSBox version as yours couldn't run 1.00 at all.

I always supply `-d` to configure, but I guess that might make it slow.

**Comment by stsp** [comment]
> I always supply -d to configure, but I guess that might make it slow.

Especially if you didn't do
a full rebuild recently.
I disabled asan, so these
days -d is almost as fast.
But you need `make clean`
and reconfigure to get that
change in.

**Comment by jschwartzenberg** [comment]
Yeah it seems particularly with this game, debug mode is significantly slower.

**Comment by stsp** [comment]
Even after a full rebuild w/o asan?

**Comment by stsp** [comment]
And yeah, indeed blakestone
works on instremu so it is affected
by #463 
But it expects so few from CPU
that even in that case it works
much faster than in dosbox, unless
you build dosemu2 with asan.

**Comment by jschwartzenberg** [comment]
Yeah indeed it's faster now. I suppose I had asan in the previous build.

**Comment by stsp** [comment]
So please update the doc and
lets close.

Btw it seems like all freedos files
were moved around.
Can you have a look at our DL
scripts?

**Comment by jschwartzenberg** [comment]
Yeah but how to deal with the patcher not working on DOSEMU?

**Comment by jschwartzenberg** [comment]
> Btw it seems like all freedos files
> were moved around.
> Can you have a look at our DL
> scripts?

That sucks, I'll take a look.

**Comment by stsp** [comment]
> Yeah but how to deal with the patcher not working on DOSEMU?

By opening a proper bug report.

**Comment by jschwartzenberg** [comment]
I added the version info to the wiki.
