### ISSUE TITLE
Blake Stone patcher hangs

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1700]
**Describe the bug**
Trying to patch Blake Stone 1.0 to 2.0, the patcher appears to hang.

**To Reproduce**
Unpack the zip file and run the installer, proceed to patch the version from the tarball.
It hangs like this whereas in DOSBox a patching process is started (which takes quite some time) and results in a patched version of the game.
![Screenshot_20220621_205543](https://user-images.githubusercontent.com/877112/174876869-ef4da706-0569-49c5-9c5b-6e7933fb8131.png)

**Attach program/game binaries or provide an URL**
Obtain the tarball here: #1695 
The patch here: ftp://ftp.3drealms.com/patches/bs20pat6.zip (possibly with `wget`)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/8952076/boot.log)

**A regression?**
unknown

**Comment by stsp** [comment]
So does this work, could you please confirm?

**Comment by jschwartzenberg** [comment]
Yep, works perfectly now!
