### ISSUE TITLE
There's something weird with the "graphics" fonts

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1708]
**Describe the bug**
Displaying some text in graphics mode ( VGA mode 0x12, 640x480x16 ), "doesn't work" when the program is launched for the first time. Exiting the program somehow fixes the bug, because the second try works without errors...

![Screenshot at 2022-06-28 16-59-05](https://user-images.githubusercontent.com/38952922/176212657-54ad89bc-ccc7-479d-ab4b-e3161ecc971f.png)

The text in the test prog is rendered "manually", without using the BIOS.
It's using the graphics font ( address int 0x43 ), though.

**To Reproduce**
just run the test prog. Or, alternatetly, just "switch" to grahics mode 0x12 and see if you can read the console text...

**Attach program/game binaries or provide an URL**

[test3.exe.zip](https://github.com/dosemu2/dosemu2/files/9002182/test3.exe.zip)

**Attach the log**
Nothing to see in the log, AFAICS...

**Comment by stsp** [comment]
```
C:\TEST>dir
 Volume in drive c is EMU DRIVE_C
 Directory of c:\TEST\
 
2022-06-28 19:02 <DIR>         .
2022-06-28 19:02 <DIR>         ..
2022-06-28 16:31          5321 TEST3.EXE
2022-06-24 07:56         18330 DPMILD32.EXE
         2 file(s)          23651 bytes
         2 dir(s)            2047 MB free
C:\TEST>test3
 
cannot find loader DPMILD16.EXE
program loading aborted
```

**Comment by Baron-von-Riedesel** [comment]
Ok, this should do better:

[test3.exe.zip](https://github.com/dosemu2/dosemu2/files/9003612/test3.exe.zip)

**Comment by stsp** [comment]
I am not getting the behavior
on your screen-shot.
Same with `dosemu -X`?

**Comment by Baron-von-Riedesel** [comment]
Ok, I found the reason: the VGA-Bios doesn't update the "character height" field in BIOS variable 40:85h when a graphics mode is set. So if you are switching to the graphics mode from a text mode with character height 14, you get that strange effect.

Since the program on exit switches to a text mode with char height 16, everything works when the program is launched again...

**Comment by stsp** [comment]
Hmm, we do not load the
font to VGA mem when setting
gfx mode. And yet set the
font size in bda?
Or maybe we should load
the font also in gfx modes?

**Comment by Baron-von-Riedesel** [comment]
> Or maybe we should load the font also in gfx modes?

Why? And where? In 16-color gfx modes all 4 planes are used...
Setting the BIOS variable is sufficient.

**Comment by stsp** [comment]
Thats the point: if we dont load any
font, why setting some size? It doesnt
relate to anything, fake value.

**Comment by Baron-von-Riedesel** [comment]
> if we dont load any font, why setting some size? 

Because it would allow the BIOS text output routine ( and hence DOS ) to display something readable.
With the attached program ( it does nothing but to set the video mode ), enter the following:

vmode 11
vmode 10
vmode 0f
vmode 0e
vmode 0d

and see if you can read what's displayed.

[VMODE.EXE.zip](https://github.com/dosemu2/dosemu2/files/9009701/VMODE.EXE.zip)

**Comment by stsp** [comment]
OK, thanks, its not a fake value
because we set 0x43 on the needed
font.

**Comment by andrewbird** [comment]
BTW github having issues with internet connectivity today, the test failed due to no access to ubuntu repos

**Comment by Baron-von-Riedesel** [comment]
Looks much better now, thanks!

Adjusting the "coluims" value at  40:4ah should improve the output even more. For example, mode 0x13 has 40 columns only.

Btw, I guess this fix might also improve the issues described at  https://github.com/dosemu2/dosemu2/issues/1694

**Comment by stsp** [comment]
Why not to create a patch? :)
Do we adjust rows?
