### ISSUE TITLE
Street Fighter 2 stalls

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1720]
Game stalls a lot after every
sound effect.
Regression of 11acfe35
It appears evtimer_block() and
evtimer_unblock() are too slow.
If they are commented out then
things are fine.

**Comment by stsp** [comment]
SF2 now works so good with
$_timer_tweaks=(on) that I wonder
if it actually should be enabled
by default. :)

**Comment by jschwartzenberg** [comment]
How do you play this? :) I can't get past:
![Screenshot_20220714_231234](https://user-images.githubusercontent.com/877112/179087060-308b6cf0-b991-4b9b-bc65-8649ed2cdf03.png)

**Comment by stsp** [comment]
Maybe you configured it for
pc-speaker, or something along
the lines.
Works perfectly here.
