### ISSUE TITLE
Strange DosEmu2 bug concerning selector 0x40

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1721]
**Describe the bug**
In many? DPMI applications selector 0x40 is used to access BIOS variables. It works, but is not covered by the DPMI specification AFAIK. AFAIU the GDT selector 0x40h cannot be used by ring3 applications in Linux, but DosEmu, as I had to learn, tries to emulate access to this descriptor.

This emulation seems to have problems. I wrote a small test program:
```
start:
    int 3
if 1
    push ds
    push 40h
    pop ds
    mov al,ds:[62h]
    pop ds
endif
    mov edx, offset szWelcome
    mov ah,9
    int 21h

    mov ax, 4C00h   ;normal client exit
    int 21h
```

It displays garbage, because register DS contains still the "emulated 0x40" selector when DOS function 09 is executed - the "pop ds" instruction obviously was somehow skipped.

**To Reproduce**
run the attached test program!

**Attach program/game binaries or provide an URL**
[DPMICL32.EXE.zip](https://github.com/dosemu2/dosemu2/files/9049182/DPMICL32.EXE.zip)

**Attach the log**
no log

**Comment by stsp** [comment]
Quite a bug.
