### ISSUE TITLE
Serial I/O fails after first byte received, locking up

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1723]
**Describe the bug**
Running my debugger application and connecting to dosemu's serial port fails. When the debugger sends its KEEP prompt, sending the prompt works (and is received by the other side). However, after the application read the first byte from the serial port (eg letter `k`) it appears to lock up.

**To Reproduce**
1.Get debugger application from https://pushbx.org/ecm/test/20220707/ldebugu.com
2. Set up PTTY using command `socat pty,link=/tmp/vptty-dos,rawer pty,link=/tmp/vptty-linux,rawer & disown`
3. Set up terminal using `picocom /tmp/vptty-linux`
4. Start dosemu2 as `dosemu -K "$PWD" -E "ldebugu.com /c='r dco or= 4800'" -I "serial { com 2 device /tmp/vptty-dos }" -dumb -td -kt`
5. Attempt to enter the `keep` keyword to the prompt shown in picocom terminal.

Result: Hang after `k` is received, application times out the prompt after 15 seconds. This is what picocom shows:

```
lDebug connected to serial port. Enter KEEP to confirm.
= k
```

Expected: `keep` then Enter input should establish serial I/O and bring up the application's command line.

**Attach the log**
https://pushbx.org/ecm/test/20220707/1422.log

**A regression?**
`2.0pre9-dev-20220706-335-ge266e48b3` (current git) fails. `2.0pre8-20191102-1332-g9cf2b7560` works.

**Additional info**
Running FreeDOS with a recent self compiled (gcc-ia16) kernel. I suspect the recent timer changes may be related to this bug.

**Comment by stsp** [comment]
Could you please narrow
the problem with git bisect?
Just disable fdpp during that,
you don't use it anyway.

**Comment by ecm-pushbx** [comment]
I don't know how exactly to use git bisect, scripting the build and the test. If you need it I can try it later this week.

**Comment by ecm-pushbx** [comment]
I managed to make a test script, quoted as follows. Unfortunately it doesn't work as intended: The dosemu with the error results in a test success, ie writing to the vptty-linux file using echo works just fine. From https://pushbx.org/ecm/test/20220707/1640.sh

```
#! /bin/bash

if [[ "$1" != RUNONLY ]]
then
  make clean || exit 125
  ./default-configure -d --prefix=$HOME/local.new \
    --with-fdtarball=dosemu-freedos-1.0-bin.tgz \
    --sysconfdir=$HOME/local.new/etc --disable-fdpp \
    --mandir=$HOME/local.new/share/man --datarootdir=$HOME/local.new/share \
    || exit 125
  make || exit 125
  make install || exit 125
  (cd ~/local.new/; ./updatedosemu.sh)
fi
truncate --size=0 /tmp/vptty-trace.log
(sleep 5; echo -ne "keep\r" >> /tmp/vptty-linux) &
~/local.new/bin/dosemu -K ~/wwwecm/test/20220707/ \
  -E "ldebugu.com /c='r dco or= 4800;\;comment;q'" \
  -I "serial { com 2 device /tmp/vptty-dos }" -dumb -td -kt
wait
if cat /tmp/vptty-trace.log | grep -q ';comment'
then
  echo Test success.
  exit 0
else
  echo Test error.
  exit 1
fi
```

If I cannot figure out how to write a test that fails I may have to resort to manually testing and marking things good or bad for bisect.

**Comment by ecm-pushbx** [comment]
(Just noticed the `wait` command is at best useless here. Oh well.)

**Comment by stsp** [comment]
> I may have to resort to manually testing and marking things good or bad

Why not?
Its just 5-10 attempts.

**Comment by ecm-pushbx** [comment]
Modified it a bit, dropping the `wait` and adding a "MANUAL" mode. This expects the user to enter the `keep` keyword to the picocom terminal, which fails as expected. However this is more work and if we use this to build and run the test, the user needs to be notified of the need for intervention. I added some handling for this. From https://pushbx.org/ecm/test/20220707/1715.sh

```
#! /bin/bash

if [[ "$1" != RUNONLY ]]
then
  make clean || exit 125
  ./default-configure -d --prefix=$HOME/local.new \
    --with-fdtarball=dosemu-freedos-1.0-bin.tgz \
    --sysconfdir=$HOME/local.new/etc --disable-fdpp \
    --mandir=$HOME/local.new/share/man --datarootdir=$HOME/local.new/share \
    || exit 125
  make || exit 125
  make install || exit 125
  (cd ~/local.new/; ./updatedosemu.sh)
fi
truncate --size=0 /tmp/vptty-trace.log
if [[ "$2" != MANUAL ]]
then
  (sleep 5; echo -ne "keep\r" >> /tmp/vptty-linux) &
else
  rm -f ~/test-ready
  echo >> ~/test-waiting "[$(date '+%Y-%m-%d %H:%M:%S %z %b %a')] Test is waiting."
  echo >> ~/test-log "[$(date '+%Y-%m-%d %H:%M:%S %z %b %a')] Test $(git describe) is waiting."
  while [[ ! -f ~/test-ready ]]
  do
    sleep 1
  done
  echo >> ~/test-log "[$(date '+%Y-%m-%d %H:%M:%S %z %b %a')] Test $(git describe) starting."
fi
~/local.new/bin/dosemu -K ~/wwwecm/test/20220707/ \
  -E "ldebugu.com /c='r dco or= 4800;\;comment;q'" \
  -I "serial { com 2 device /tmp/vptty-dos }" -dumb -td -kt
if cat /tmp/vptty-trace.log | grep -q ';comment'
then
  echo Test success.
  if [[ "$2" == MANUAL ]]
  then
    echo >> ~/test-log "[$(date '+%Y-%m-%d %H:%M:%S %z %b %a')] Test success."
  fi
  exit 0
else
  echo Test error.
  if [[ "$2" == MANUAL ]]
  then
    echo >> ~/test-log "[$(date '+%Y-%m-%d %H:%M:%S %z %b %a')] Test error."
  fi
  exit 1
fi
```

I'm trying to run bisect with this now.

**Comment by ecm-pushbx** [comment]
Got some weird failures with that where `make clean` eventually outputs `configure: error: fdpp not available!` which never happens when I run `make clean` from the shell terminal directly. Trying with `git clean -x -d -f` instead now.

**Comment by stsp** [comment]
Use `--disable-fdpp` to default-configure,
and put `plugin_fdpp off` to compiletime-settings.devel

**Comment by ecm-pushbx** [comment]
I'm already using `--disable-fdpp` to default-configure, as you can see in the 1715.sh script file. However, I wanted to `make clean` before running default-configure (but after having updated the git commit that's checked out).

**Comment by ecm-pushbx** [comment]
`git clean -x -d -f` instead of `make clean` did the trick. (Oh I just noticed I never checked the return value of `make clean` when I used it on the terminal. Probably it failed too, I just didn't notice that it did.) Anyway here's the result:

```
8190f8c1996ca851b04799af2405fee8c0a001a2 is the first bad commit
commit 8190f8c1996ca851b04799af2405fee8c0a001a2
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sun Mar 13 01:18:57 2022 +0300

    pic: replace with qemu code [#1587]

    This is a major rework of an interrupt handling subsystem.

 src/arch/linux/async/signal.c     |   2 +-
 src/arch/linux/async/sigsegv.c    |   2 +-
 src/base/bios/setup.c             |   8 +
 src/base/dev/misc/8042.c          |   6 +-
 src/base/dev/misc/kbd.c           |   2 +-
 src/base/dev/misc/rtc.c           |  10 +-
 src/base/dev/misc/timers.c        |  19 +-
 src/base/dev/misc/virq.c          |   6 +-
 src/base/dev/misc/vtmr.c          |  12 +-
 src/base/dev/ne2k/ne2000.c        |   2 +-
 src/base/dev/pic/Makefile         |  10 +-
 src/base/dev/pic/i8259.c          | 350 +++++++++++++++
 src/base/dev/pic/i8259.h          |  23 +
 src/base/dev/pic/i8259_common.c   |  75 ++++
 src/base/dev/pic/i8259_internal.h |  63 +++
 src/base/dev/pic/irq.c            |  32 ++
 src/base/dev/pic/irq.h            |  34 ++
 src/base/dev/pic/pic.c            | 866 +++++---------------------------------
 src/base/dev/sb16/sb16.c          |   8 +-
 src/base/emu-i386/do_vm86.c       |  40 +-
 src/base/emu-i386/kvm.c           |   2 +-
 src/base/misc/ioctl.c             |   2 +-
 src/base/serial/ser_irq.c         |   2 +-
 src/dosext/dpmi/dpmi.c            |  43 +-
 src/include/cpu.h                 |   2 +
 src/include/emu.h                 |   1 -
 src/include/pic.h                 |  96 +----
 27 files changed, 806 insertions(+), 912 deletions(-)
 create mode 100644 src/base/dev/pic/i8259.c
 create mode 100644 src/base/dev/pic/i8259.h
 create mode 100644 src/base/dev/pic/i8259_common.c
 create mode 100644 src/base/dev/pic/i8259_internal.h
 create mode 100644 src/base/dev/pic/irq.c
 create mode 100644 src/base/dev/pic/irq.h
bisect run success
```

**Comment by ecm-pushbx** [comment]
> (Oh I just noticed I never checked the return value of `make clean` when I used it on the terminal. Probably it failed too, I just didn't notice that it did.)

To be fair, it did solve some build problems at some point when I did `make clean` beforehand. So it "worked" in that it affected some things about building. However, it likely ran into the same fdpp problems and I just never noticed because the error messages always scrolled past undetected.

**Comment by stsp** [comment]
For me it waits, then says
`No KEEP keyword confirmation after timeout, giving up. (Keyboard enabled.)`
and then I can type anything.

**Comment by stsp** [comment]
Also I pushed the patch for
comcom32 which seems to
allow to handle the same
cmdline. So would be good
if you test with comcom32
to make sure it works the
same way as with freecom.

**Comment by ecm-pushbx** [comment]
> For me it waits, then says `No KEEP keyword confirmation after timeout, giving up. (Keyboard enabled.)` and then I can type anything.

That's the application timeout I mentioned. The intention is to enter the `keep` keyword over serial, then **control the application** across the serial port. So lDebug should display its dash `-` prompt to the serial terminal, and receive its commands from there. The "giving up" message indicates it returned control to the DOS terminal (local, not remote across serial). It is expected in the failure case that you can control the debugger from the DOS terminal once it gives up.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
Pre-existing bug actually.
Just didn't trigger before that
patch.

**Comment by ecm-pushbx** [comment]
Thanks, that fixes it indeed!

**Comment by bolle732** [comment]
Wow, this fixed PC/GEOS too!

I have a LoraWAN development board connected by USB to my notebook. Configured DOSEmu2 with
```$_com1 = /dev/ttyUSB0```
and setup GeoComm to COM1 with 57600-8N1 and I get all the output:
![PCGEOS GeoComm on DOSEmu2](https://user-images.githubusercontent.com/8956508/177926718-eec7d117-d643-483d-ab9d-cdd5af66d720.png)

A huge thank to you all!
