### ISSUE TITLE
JEMM: Strike Commander doesn't detect EMS

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1732]
**Describe the bug**
Trying to run the game shows:
![Screenshot_20220713_223243](https://user-images.githubusercontent.com/877112/178829271-fcd80f9c-c2b0-46de-9c4b-bc4c7ff9289a.png)

**To Reproduce**
Run the game.

**Attach program/game binaries or provide an URL**
[sc.tar.gz](https://github.com/dosemu2/dosemu2/files/9105861/sc.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9105856/boot.log)

**A regression?**
unknown

**Comment by runderwo** [comment]
This is an Origin game using JEMM which in turn relies on VCPI.

**Comment by jschwartzenberg** [comment]
Ah so duplicate of #353 I guess?

**Comment by stsp** [comment]
Likely a duplicate, yes.
