### ISSUE TITLE
SimCity 2000 setup fails to detect SB16

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1734]
**Describe the bug**
![Screenshot_20220716_181054](https://user-images.githubusercontent.com/877112/179362955-da84f2bb-f054-4717-bb49-56d7f3cd9009.png)

For some reason before that it also shows a memory error:
![Screenshot_20220716_181504](https://user-images.githubusercontent.com/877112/179363154-31f67753-04a5-468b-b811-cba023951c69.png)

**To Reproduce**
Run setup. Set up SB16 for SFX.

**Attach program/game binaries or provide an URL**
[simc2000.tar.gz](https://github.com/dosemu2/dosemu2/files/9126162/simc2000.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9126163/boot.log)

**A regression?**
unknown

**Comment by jschwartzenberg** [comment]
Same issue with Sim Farm:
![Screenshot_20220716_182057](https://user-images.githubusercontent.com/877112/179363360-cb21c653-8cbd-47ae-8a7b-ef420d04d7ba.png)

[simfarm.tar.gz](https://github.com/dosemu2/dosemu2/files/9126168/simfarm.tar.gz)

**Comment by stsp** [comment]
I think this is not a dosemu bug.
It simply can't detect an IRQ.
But if you set `$_sb_irq=(7)` then
it works fine.

**Comment by stsp** [comment]
Or alternatively you can click
"CHANGE SETTINGS" and set
irq 5 there. It will detect the rest.

**Comment by jschwartzenberg** [comment]
Ah indeed just an unclear setup tool. Setting the IRQ properly solves both games. Apologies for the noise and thanks a lot for checking it out!!

**Comment by stsp** [comment]
But I am not sure it cant detect irq5 on
other emulators as well. Can you check?

**Comment by jschwartzenberg** [comment]
I'll look into that. Note that it seems DOSBox uses IRQ 7 by default.

**Comment by jschwartzenberg** [comment]
Same issue when IRQ is 5 in DOSBox:
![Screenshot_20220804_074708](https://user-images.githubusercontent.com/877112/182772200-ca080822-d928-4a9f-b807-c0031622781c.png)

Similarly setting the IRQ to 5 manually solves it.

**Comment by stsp** [comment]
Thank you, so not a bug here.
Though I am pretty sure it used to detect
SB on real HW (30 years ago) and my
SB16 was on irq5 (which is why it is so
under dosemu now).
The same irq detection problem was
already observed on a millenium game.
I'll check a bit more.
