### ISSUE TITLE
Ctrl-M is indistinguishable from Enter in dosemu -t and dosemu -X

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1736]
**Describe the bug**

The Insight debugger uses the Ctrl-M shortcut. This appears to be indistinguishable from Enter when running in `dosemu -t` or `dosemu -X` mode. (The X and SDL window tests were done on a not current revision.) Not a problem when running in an SDL graphical window.

Insight expects `kbEnter		equ	1C0Dh` and `kbCtrlM		equ	320Dh` in https://hg.pushbx.org/ecm/insight/file/470e07785904/src/insight.inc#l325

**To Reproduce**

1. Start dosemu2 with `-t`
2. Run `insight.com /E`
3. Press Ctrl-M

Expected result: Display "Memory Blocks" window.

Actual result: Nothing happens.

**Attach program/game binaries or provide an URL**

https://pushbx.org/ecm/test/20220719/insight.com

**Attach the log**

https://pushbx.org/ecm/test/20220719/2200.log

**A regression?**

Not to my knowledge.

**Additional info**

Running FreeDOS kernel and FreeCOM.

**Comment by stsp** [comment]
With `cat`Ctrl-m also seems
to be indistinguishable from enter.

**Comment by stsp** [comment]
So perhaps nothing to fix here.

**Comment by ecm-pushbx** [comment]
I added the alternative keycode Ctrl-V to Insight: https://hg.pushbx.org/ecm/insight/rev/d43687316064

I also modified my keybtest program to allow entering a single CR without quitting the program: https://hg.pushbx.org/ecm/keybtest/rev/af6c4bbe8806 (You have to provide an exclamation mark on the command line, which causes it to quit after two successive CRs instead of after every CR.)

**Comment by stsp** [comment]
Thanks.
