### ISSUE TITLE
Multiple "ERROR: KVM: applying TF fixup" while running the most recent dosemu2 on home desktop

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1740]
**Describe the bug**

This error message shows up a few times, usually about four times, when running a very simple test of the debugger (lDebug).

**To Reproduce**

1. Build `Build 2.0pre9-dev-20220719-348-g269f6bac4`
2. Install locally (eg ~/local.new)
3. Run like `~/local.new/bin/dosemu -dumb -td -kt -K "$PWD" -E "ldebugu.com /c=q"`
4. After the application has quit, several errors about "applying TF fixup" are displayed.

Display output is as follows:

```
$ ~/local.new/bin/dosemu -dumb -td -kt -K "$PWD" -E "ldebugu.com /c=q"
dosemu2 2.0pre9-dev-20220719-348-g269f6bac4 Configured: 2022-07-20 15:49:08 +0000
Get the latest code at http://dosemu2.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

FreeDOS kernel - GIT (build 2043 OEM:0xfd) [compiled Jul 16 2022]
Kernel compatibility 7.10 - GNUC - FAT32 support

(C) Copyright 1995-2022 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
EMUFS host file and print access available                                     
dosemu XMS 3.0 & UMB support enabled
NOKEYB R2
Copyright (c) 2021 Robert Riebisch
dosemu EMS driver rev 0.9 installed.
dosemu CDROM driver installed (V0.2)
Kernel: allocated 33 Diskbuffers = 17556 Bytes in HMA
emufs: redirector enabled
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre9-dev-20220719-348-g269f6bac4
&q

ERROR: PKT: Cannot open tap0: Operation not permitted
ERROR: PKT: Cannot open tap0: Operation not permitted
ERROR: KVM: applying TF fixup
ERROR: KVM: applying TF fixup
ERROR: KVM: applying TF fixup
ERROR: KVM: applying TF fixup
```

Same error is displayed to the terminal when dosemu is run with `dosemu -S`.

**Attach program/game binaries or provide an URL**

https://pushbx.org/ecm/test/20220720/ldebugu.com

**Attach the log**

https://pushbx.org/ecm/test/20220720/1800.log

**A regression?**

Not to my knowledge.

**Additional info**

Obviously this is running on a system that has KVM available for dosemu. I'm using my own builds of FreeCOM and the FreeDOS kernel, available from my download directory (today's freecom.zip and fdkernel.zip) and also mirrored at https://pushbx.org/ecm/test/20220720/command.com and https://pushbx.org/ecm/test/20220720/kernel.sys

**Comment by stsp** [comment]
This only means that dosemu2
detected TF set after POPF, when
`#DE` is raised.
There was a CPU that, in VME mode,
had TF still set on `#DE`, even if
it wasn't set on stack but was in
eflags before that POPF.
To work around that, dosemu2 now
clears TF if it sees it right after POPF.
If POPF deliberately wanted to set TF,
then IIRC the `#DE` would be generated
1 instruction later, so the fixup shouldn't
trigger in that case.

Of course we can disable that fixup now
as I am using a much older CPU than before
(went to retro-CPU), and even the CPU
with that bug was also very retro so no one
perhaps is using it these days.

**Comment by stsp** [comment]
Please run:
`python test/test_dos.py PPDOSGITTestCase.test_cpu_trap_flag_kvm`
from dosemu source dir to see
if you hit the real CPU bug or a
(more likely) false-positive.

**Comment by ecm-pushbx** [comment]
Do I need fdpp installed for that? Just shows errors for both tests:

```
$ python test/test_dos.py PPDOSGITTestCase.test_cpu_trap_flag_emulated PPDOSGITTestCase.test_cpu_trap_flag_kvm
libi86-testsuite-ia16-elf not installed - skipping those

Test PP-DOS-GIT  CPU Trap Flag emulated                                          ... FAIL
Test PP-DOS-GIT  CPU Trap Flag KVM                                               ... FAIL

======================================================================
FAIL: Test PP-DOS-GIT  CPU Trap Flag emulated                                         
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/test_dos.py", line 4778, in test_cpu_trap_flag_emulated
    cpu_trap_flag(self, 'emulated')
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/func_cpu_trap_flag.py", line 66, in cpu_trap_flag
    self.assertIn("Result is (1)", results)
AssertionError: 'Result is (1)' not found in 'EndOfFile'
Further info in file '/media/ssd-data/coding/proj/20220720/dosemu2/test_dos.PPDOSGITTestCase.test_cpu_trap_flag_emulated.log'
Further info in file '/media/ssd-data/coding/proj/20220720/dosemu2/test_dos.PPDOSGITTestCase.test_cpu_trap_flag_emulated.xpt'

======================================================================
FAIL: Test PP-DOS-GIT  CPU Trap Flag KVM                                              
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/test_dos.py", line 4783, in test_cpu_trap_flag_kvm
    cpu_trap_flag(self, 'kvm')
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/func_cpu_trap_flag.py", line 66, in cpu_trap_flag
    self.assertIn("Result is (1)", results)
AssertionError: 'Result is (1)' not found in 'EndOfFile'
Further info in file '/media/ssd-data/coding/proj/20220720/dosemu2/test_dos.PPDOSGITTestCase.test_cpu_trap_flag_kvm.log'
Further info in file '/media/ssd-data/coding/proj/20220720/dosemu2/test_dos.PPDOSGITTestCase.test_cpu_trap_flag_kvm.xpt'

----------------------------------------------------------------------
Ran 2 tests in 1.375s

FAILED (failures=2)
```

**Comment by andrewbird** [comment]
> Do I need fdpp installed for that?

Yes if you want to run the FDPP flavoured tests. You could create a subdirectory in your devel directory called `test-binaries` and place this file there http://www.spheresystems.co.uk/test-binaries/FR-DOS-1.20.tar. Then call the FreeDOS flavoured test
`python test/test_dos.py FRDOS120TestCase.test_cpu_trap_flag_kvm`

**Comment by ecm-pushbx** [comment]
I ported to NASM the example case from `test/func_cpu_trap_flag.py` and ran it on its own. https://pushbx.org/ecm/test/20220720/testtf.asm

"Result is (1)" and five messages on the "applying TF fixup".

**Comment by ecm-pushbx** [comment]
> > Do I need fdpp installed for that?
> 
> Yes if you want to run the FDPP flavoured tests. You could create a subdirectory in your devel directory called `test-binaries` and place this file there http://www.spheresystems.co.uk/test-binaries/FR-DOS-1.20.tar. Then call the FreeDOS flavoured test `python test/test_dos.py FRDOS120TestCase.test_cpu_trap_flag_kvm`

Thanks, I did look into that a bit but didn't know where to get the expected files. It seems they're checksummed in the `test_dos.py` file?

**Comment by stsp** [comment]
> "Result is (1)" and five messages on the "applying TF fixup".

This seriously hints towards a
CPU bug. But lets wait for Andrew
to help you with the test.

**Comment by ecm-pushbx** [comment]
By the way, with my FreeDOS kernel patch at https://github.com/FDOS/kernel/pull/81 the four usual "applying TF fixup" messages go away. The "Result is (1)" is the same and exactly one of the messages remains.

**Comment by andrewbird** [comment]
> It seems they're checksummed in the test_dos.py file?

Yes, I wanted to be sure that if others ran the tests the binaries don't get replaced with alternative versions, e.g. from French MS-DOS 6.22 instead of English.

**Comment by stsp** [comment]
> By the way, with my FreeDOS kernel patch at https://github.com/FDOS/kernel/pull/81
> the four usual "applying TF fixup" messages go away.

Good.
fdpp fixed this years ago.

You need to run the test.

**Comment by ecm-pushbx** [comment]
I already ran it. I don't think the kernel should affect it, should it?

**Comment by stsp** [comment]
You ran it for fdpp but it didn't
work. Will you run it with Andrew's
suggestions above?

**Comment by ecm-pushbx** [comment]
I managed to run it under *my* FreeDOS kernel version (both from latest current build from my website or the one from that Pull Request with the TF setting fixed). Here's the message, maybe you missed it:

> I ported to NASM the example case from `test/func_cpu_trap_flag.py` and ran it on its own. https://pushbx.org/ecm/test/20220720/testtf.asm
> 
> "Result is (1)" and five messages on the "applying TF fixup".

**Comment by stsp** [comment]
No I didn't miss it but I don't know
if it is a success or a failure.
The test will show exactly.

**Comment by stsp** [comment]
`python test/test_dos.py FRDOS120TestCase.test_cpu_trap_flag_kvm`

**Comment by stsp** [comment]
Andrew, do we have some env
var to check if this is a test running?
I can disable the fixup when test
is running, otherwise its a bit weird
to add test and a work-around...

**Comment by ecm-pushbx** [comment]
https://github.com/dosemu2/dosemu2/blob/269f6bac43150ef6e560869ad89f0e623f765bda/test/func_cpu_trap_flag.py#L66 this seems to indicate that the result should be 1. If you insist I will try to figure out where to place the files.

**Comment by stsp** [comment]
No, result is always 1 because of
the fixup applied. I suppose later
Andrew looks for "applying TF fixup"
msg to deduce the actual result.
But its weird, we need to disable
the fixup while testing...

> If you insist I will try to figure out where to place the files.

Yes, that is needed.
And more so if we disable the fixup
while testing.

**Comment by ecm-pushbx** [comment]
I figured out to put the .tar file into `test/test-binaries/` and then ran the test, just to receive another error (not test failure, error to run the test):

```
$ python test_dos.py FRDOS120TestCase.test_cpu_trap_flag_kvm
libi86-testsuite-ia16-elf not installed - skipping those

Test FR-DOS-1.20 CPU Trap Flag KVM                                               ... ERROR

======================================================================
ERROR: Test FR-DOS-1.20 CPU Trap Flag KVM                                              
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/common_framework.py", line 139, in setUp
    self.setUpDosAutoexec()
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/test_dos.py", line 5007, in setUpDosAutoexec
    contents = (self.topdir / "src" / "bindist" / self.autoexec).read_text()
  File "/usr/lib/python3.9/pathlib.py", line 1255, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/media/ssd-data/coding/proj/20220720/dosemu2/test/src/bindist/fdautoem.bat'

----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)
```

**Comment by ecm-pushbx** [comment]
Sorry, wrong location. Also @andrewbird actually did point out where to put it, I just didn't register that. Put the file in `test-binaries/` and ran test from root dosemu2 repo dir instead. Here's the result:

```
$ python test/test_dos.py FRDOS120TestCase.test_cpu_trap_flag_kvm
libi86-testsuite-ia16-elf not installed - skipping those

Test FR-DOS-1.20 CPU Trap Flag KVM                                               ... FAIL

======================================================================
FAIL: Test FR-DOS-1.20 CPU Trap Flag KVM                                              
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/test_dos.py", line 4783, in test_cpu_trap_flag_kvm
    cpu_trap_flag(self, 'kvm')
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/func_cpu_trap_flag.py", line 98, in cpu_trap_flag
    self.fail("Fail with unknown cpu '%s'" % name)
AssertionError: Fail with unknown cpu 'AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G'
Further info in file '/media/ssd-data/coding/proj/20220720/dosemu2/test_dos.FRDOS120TestCase.test_cpu_trap_flag_kvm.log'
Further info in file '/media/ssd-data/coding/proj/20220720/dosemu2/test_dos.FRDOS120TestCase.test_cpu_trap_flag_kvm.xpt'

----------------------------------------------------------------------
Ran 1 test in 1.855s

FAILED (failures=1)
```

**Comment by stsp** [comment]
Cool, presumably you have a
CPU bug! But we need to be careful.
Andrew, what do you think?
We can either add some variable,
or perhaps add a new doshelper
instead, like ENTER_TEST_MODE,
LEAVE_TEST_MODE that some tests
will use?
For some reason I think the helper
might be a more consistent solution,
because its usually better to test a
full-featured product, not a reduced-
for-testing one.

**Comment by stsp** [comment]
Oh actually it should be a helper.
Only that solution will allow to run
the test right under dosemu (w/o
any scripts) and hope the result is
the same that is under scripts.

**Comment by andrewbird** [comment]
I'll be back in an hour, let me know what you'd like me to change in the test?

**Comment by stsp** [comment]
I did a very rough addition of a
test-mode helper (Andrew will surely
amend the test).
@ecm-pushbx what it prints now?

**Comment by ecm-pushbx** [comment]
```
$ python test/test_dos.py FRDOS120TestCase.test_cpu_trap_flag_kvm
libi86-testsuite-ia16-elf not installed - skipping those

Test FR-DOS-1.20 CPU Trap Flag KVM                                               ... FAIL

======================================================================
FAIL: Test FR-DOS-1.20 CPU Trap Flag KVM                                              
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/test_dos.py", line 4783, in test_cpu_trap_flag_kvm
    cpu_trap_flag(self, 'kvm')
  File "/media/ssd-data/coding/proj/20220720/dosemu2/test/func_cpu_trap_flag.py", line 75, in cpu_trap_flag
    self.assertIn("Result is (1)", results)
AssertionError: 'Result is (1)' not found in 'testit.bat\r\nC:\\>c:\\cputrapf\r\nERROR: KVM: not applying TF fixup (test mode)\nResult is (6)\r\nC:\\>'
Further info in file '/media/ssd-data/coding/proj/20220720/dosemu2/test_dos.FRDOS120TestCase.test_cpu_trap_flag_kvm.log'
Further info in file '/media/ssd-data/coding/proj/20220720/dosemu2/test_dos.FRDOS120TestCase.test_cpu_trap_flag_kvm.xpt'

----------------------------------------------------------------------
Ran 1 test in 0.707s

FAILED (failures=1)
```

**Comment by stsp** [comment]
`ERROR: KVM: not applying TF fixup (test mode)\nResult is (6)`
Cool, this definitely indicates a bug.
Andrew, could you please make it
so that in `Result is (N)`,
N=1 means success, N=0 - some
error, N>1 - failure (additionally
`ERROR: KVM: not applying TF fixup`
confirms the failure).

**Comment by stsp** [comment]
@ecm-pushbx now you can run
the test under dosemu itself and
get the consistent results.
But you need to re-port it from
sources.
Then you can try it on another CPU.

**Comment by stsp** [comment]
Also we need to add `AMD A10-7870K`
to known-bad CPUs.

**Comment by stsp** [comment]
So the bug is present at least in
a piledriver and steamroller AMD
CPUs.

**Comment by stsp** [comment]
Andrew updated the test.
@ecm-pushbx could you please
re-try running it?

**Comment by ecm-pushbx** [comment]
```
$ python test/test_dos.py FRDOS120TestCase.test_cpu_trap_flag_kvm
libi86-testsuite-ia16-elf not installed - skipping those

Test FR-DOS-1.20 CPU Trap Flag KVM
 ... ok (  2.18s) known bad cpu 'AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G'

----------------------------------------------------------------------
Ran 1 test in 2.181s

OK
```

**Comment by ecm-pushbx** [comment]
Did you want me to run anything else?

> Then you can try it on another CPU.

I don't have any other CPUs with systems for running dosemu2. The server I'm using does not expose KVM to userland.

**Comment by stsp** [comment]
OK, thanks.
Test behaves adequately,
identifies your CPU as bad
and prints "ok" as such.
The only thing I would be
grateful is if you find that
problem in AMD errata.
It obviously wasn't long-living:
not present on Deneb (which I
currently use), present in a
Piledriver and Steamroller,
and should be checked on
Excavator. But if we get an
errata specs, then we'll know
for sure.
