### ISSUE TITLE
VDE is not working

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1742]
**Describe the bug**
VDE doesn't work as of 167ca1c91cb0f3579e290a01fa85536fac5b9770, with the following output in the console --

/home/sysop/src/dosemu2/dosemu2-git/dosemu2/src/base/misc/ioctl.c:189:48: runtime error: index -1 out of bounds for type 'io_callback_s [1024]'
/home/sysop/src/dosemu2/dosemu2-git/dosemu2/src/base/misc/ioctl.c:196:22: runtime error: index -1 out of bounds for type 'io_callback_s [1024]'
/home/sysop/src/dosemu2/dosemu2-git/dosemu2/src/base/misc/ioctl.c:210:5: runtime error: shift exponent -1 is negative
/home/sysop/src/dosemu2/dosemu2-git/dosemu2/src/base/misc/ioctl.c:213:27: runtime error: index -1 out of bounds for type 'io_callback_s [1024]'

**To Reproduce**
Start DOSemu with VDE enabled.

**Attach program/game binaries or provide an URL**
No specific software.  (The error is reported immediately upon starting DOSemu with VDE enabled).

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/9157896/boot.log.zip)

**A regression?**
It is caused by 167ca1c91cb0f3579e290a01fa85536fac5b9770.  Reverting this allows VDE to operate properly.  

**Additional info**
None.

**Comment by stsp** [comment]
Thank you for the report and bisect!
