### ISSUE TITLE
Most recent dosemu hides cursor when running DOS program with dosemu's -E switch

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1747]
**Describe the bug**

If I run applications such as keybtest, lDebug, or Terminal with `dosemu -t -E program` then the cursor is hidden. Input works as expected. Only tested in a ssh session with ConnectBot yet, though both with and without `screen`. If I run without `-E` then the cursor appears, and stays present when I run any of the same applications.

**To Reproduce**

Just run anything with `-t -E`.

**Attach program/game binaries or provide an URL**

Example: https://pushbx.org/ecm/test/20220722/keybtest.com

**Attach the log**

https://pushbx.org/ecm/test/20220722/1250.log

**A regression?**

`Build 2.0pre8-20191102-1332-g9cf2b7560` works fine.

**Additional info**

Running FreeCOM and the FreeDOS kernel. This error seems to be quite recent as I didn't notice it before. It is possible that it occurred occasionally, but I would have noticed it if it was 100% reproducible, as it is now. I do not know what conditions may contribute to the error.

**Comment by ecm-pushbx** [comment]
Checking out 2.0pre9-dev-313-geda693bbc and building that makes the cursor work again.

**Comment by ecm-pushbx** [comment]
It's f5aec534813693a47a6694a0aca980135d37550f

```
f5aec534813693a47a6694a0aca980135d37550f is the first bad commit
commit f5aec534813693a47a6694a0aca980135d37550f
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Fri Jul 1 19:26:04 2022 +0300

    int10: set co/li for gfx modes too [#1708]

 src/base/bios/int10.c | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)
```

**Comment by ecm-pushbx** [comment]
Seems you dropped this line accidentally, re-inserting it fixes the bug on the latest commit.

```
$ git diff
diff --git a/src/base/bios/int10.c b/src/base/bios/int10.c
index 43fff7b90..f5d94e561 100644
--- a/src/base/bios/int10.c
+++ b/src/base/bios/int10.c
@@ -626,6 +626,7 @@ boolean set_video_mode(int mode)
         page_size = vga.mem.bank_pages * 4096;
       WRITE_WORD(BIOS_VIDEO_MEMORY_USED, page_size);
     }
+    WRITE_WORD(BIOS_FONT_HEIGHT, vga_font_height);
     WRITE_BYTE(BIOS_ROWS_ON_SCREEN_MINUS_1, li - 1);
     WRITE_WORD(BIOS_SCREEN_COLUMNS, co);
   }
```

**Comment by ecm-pushbx** [comment]
> This error seems to be quite recent as I didn't notice it before. It is possible that it occurred occasionally, but I would have noticed it if it was 100% reproducible, as it is now. I do not know what conditions may contribute to the error.

Probably didn't notice until today because in the last several days I used dosemu to run lDebug with `/c='r dco or= 4000'` to immediately connect to a serial port, or Insight which mostly hides the cursor intentionally.

**Comment by stsp** [comment]
No I didn't drop it, its in line 645.
So what sense does this make?

**Comment by andrewbird** [comment]
Does set_cursor_shape read the height back?

**Comment by stsp** [comment]
Ah, good catch! :)

**Comment by stsp** [comment]
So should now be fixed?

**Comment by ecm-pushbx** [comment]
Yes, it is fixed, thanks.
