### ISSUE TITLE
dosemu -t only beeps when dosemu terminates

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1754]
**Describe the bug**

Upon calling interrupt 10h service 0E07h dosemu should beep on the terminal. However, when running a very recent git dosemu2 in `-t` mode, it only beeps once dosemu itself terminates. The following text was written first with the intention to create a discussion, but while writing it I figured out that this is a dosemu2 bug.

I tried adding this patch to Insight: https://pushbx.org/ecm/test/20220723/beep.diff

```
diff --git a/src/system.inc b/src/system.inc
--- a/src/system.inc
+++ b/src/system.inc
@@ -318,7 +318,20 @@
 ; Call:	---
 ; Use:	---
 ;
+	numdef BIOSBEEP, 1
 beep:
+%if _BIOSBEEP
+	push ax
+	push bx
+	push bp
+	mov ax, 0E07h
+	mov bx, 7
+	int 10h
+	pop bp
+	pop bx
+	pop ax
+	retn
+%else
 		push	ax
 		push	cx
 		in	al,61h
@@ -340,6 +353,7 @@
 		pop	cx
 		pop	ax
 		ret
+%endif
 ;=============================================================================
 ; ascii_to_bin
 ;-----------------------------------------------------------------------------
```

However, calling this function does not beep when running Insight. For example, press Ctrl-L without having entered any search string and Insight will pop up the Message "Bytes not found." I verified that it calls the `beep` function then.

I also tried assembling `mov ax, 0E07` then `int 10` in Insight and running that with F8. Another call such as with ax = 0E26h does work (you can see the ampersand in the output on Alt+F5 show user screen).

**To Reproduce**

I simplified this to a very small test case: Run `dosemu -t -E "ldebug /c='a;mov ax, 0E07;int 10;;t;t;sleep 4 seconds;q'"` With the almost current `Build 2.0pre9-dev-20220722-354-g66e4c3ff3` dosemu will beep upon its termination (after the 4 seconds sleep command and the Q command have finished running).

**Attach program/game binaries or provide an URL**

https://pushbx.org/ecm/download/old/ldebug/20220718.zip bin/ldebug.com

**Attach the log**

https://pushbx.org/ecm/test/20220723/1355.log

**A regression?**

`Build 2.0pre8-20191102-1332-g9cf2b7560` is fine.

**Additional info**

Running FreeCOM and the FreeDOS kernel.

**Comment by ecm-pushbx** [comment]
Bisecting now, need to run 8 more steps. `Build 2.0pre8-20201217-2581-g1f0c26ee5` is fine.

**Comment by ecm-pushbx** [comment]
It's ae8b031120b91275769b833af9e08e0353da0d92

```
ae8b031120b91275769b833af9e08e0353da0d92 is the first bad commit
commit ae8b031120b91275769b833af9e08e0353da0d92
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Wed Jun 2 16:39:15 2021 +0300

    fix stdio_init() [#1486]

    config_init() was setting dbg_fd before stdio_init(),
    so the latter one did nothing.

    Call stdio_init() before config_init() and move the
    config_init()'s stdio code there to avoid any regressions.

 src/base/core/emu.c    |  2 +-
 src/base/init/config.c | 19 -------------------
 src/base/init/init.c   | 36 +++++++++++++++---------------------
 3 files changed, 16 insertions(+), 41 deletions(-)
```

**Comment by ecm-pushbx** [comment]
Fix:

```
diff --git a/src/base/init/init.c b/src/base/init/init.c
index 6fcf6b95a..c8fc41e65 100644
--- a/src/base/init/init.c
+++ b/src/base/init/init.c
@@ -69,6 +69,8 @@ static inline void dbug_dumpivec(void)
  */
 void stdio_init(void)
 {
+    setbuf(stdout, NULL);
+
     if (config.debugout == NULL) {
         char *home = getenv("HOME");
         if (home) {
```

**Comment by stsp** [comment]
Thanks!
Very helpful.
Could you please test this:
```
diff --git a/src/base/speaker/speaker.c b/src/base/speaker/speaker.c
index 09f46a14d..e207c5660 100644
--- a/src/base/speaker/speaker.c
+++ b/src/base/speaker/speaker.c
@@ -93,7 +93,10 @@ static int speaker_is_on;
 
 static void dumb_speaker_on(void * gp, unsigned ms, unsigned short period)
 {
-       putchar('\007');
+       FILE *out = (config.tty_stderr ? stderr : stdout);
+       putc('\007', out);
+       if (!config.tty_stderr)
+               fflush(stdout);
 }
 static void dumb_speaker_off(void *gp)
 {
```

**Comment by ecm-pushbx** [comment]
That also works.

**Comment by stsp** [comment]
Thank you.
