### ISSUE TITLE
dosemu -t does not beep the first time a beep is emitted from port I/O

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1755]
**Describe the bug**

Previously I looked into replacing Insight's [port beep implementation](https://hg.pushbx.org/ecm/insight/file/56900bf09a03/src/system.inc#l321) by one that calls the ROM-BIOS instead. I found that both options work on `dosemu -t` in `screen` in ConnectBot. However, testing the fix for https://github.com/dosemu2/dosemu2/issues/1754 I found that the port beeping does not work the first time it is run. Subsequent calls work fine.

**To Reproduce**

Run command like `dosemu -t -K "$PWD" -E "testbeep.com ! 1 ? 1 ?"` (! = BIOS beep, 1 = wait for one second, ? = port beep). Observe that it beeps twice where expected would be thrice.

**Attach program/game binaries or provide an URL**

https://pushbx.org/ecm/test/20220723/testbeep.com with the GNU GPL v2-or-later source at https://pushbx.org/ecm/test/20220723/testbeep.asm (needs lmacros). The portbeep function is copied directly from Insight's original beep function.

**Attach the log**

https://pushbx.org/ecm/test/20220723/1626.log

**A regression?**

Not to my knowledge.

**Additional info**

Running FreeDOS kernel and FreeCOM.

**Comment by ecm-pushbx** [comment]
Actually this revision of the test program probably doesn't need lmacros, I had it select which beep function to use based on a define previously. But now it includes both functions.

**Comment by stsp** [comment]
Does your setbuf fix affect that?

**Comment by ecm-pushbx** [comment]
I deleted that fix after you instructed me to try the patch you eventually committed. Do you want me to try it?

**Comment by ecm-pushbx** [comment]
I also tested this with mate-terminal connected to the server (ssh), running `screen` and then dosemu. Same behaviour. (By now I added a configuration option to Insight which controls whether it uses the BIOS beep or its port beep.)

**Comment by stsp** [comment]
Should now be fixed.

**Comment by ecm-pushbx** [comment]
Yes, it does now beep thrice in the test. Thank you!
