### ISSUE TITLE
Cursors leaves artefacts in dosemu -X when running with $_X_font="vga11x19"

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1756]
**Describe the bug**

I found the issue in https://github.com/dosemu2/dosemu2/issues/823 and took the line `$_X_font="vga11x19"` from that and put it in my ~/.dosemu/.dosemurc. This helped so that dosemu enlarges the window when I request an 80x50 mode. However, running Insight (which allows to work with text modes with higher amounts of rows) the cursor displayed eg in the data window leaves artefacts in the cell below the one displaying the cursor.

**To Reproduce**

1. `wget https://pushbx.org/ecm/download/freecom.zip`
2. `wget https://pushbx.org/ecm/download/ldebug.zip`
3. `unzip -j freecom.zip tools/50.com`
4. `unzip -j ldebug.zip bin/ldebug.com`
5. `wget https://pushbx.org/ecm/test/20220723/insight.com`
6. Add `$_X_font="vga11x19"` to ~/.dosemu/.dosemurc
7. Run `dosemu -K "$PWD" -E "ldebug.com /c='r dco or= 800;r dco4 or= F;g;n insight.com /E;l;g' 50.com" -I "serial { com 2 device /tmp/vptty-dos }" -X`
8. Enter Shift+D
9. Move cursor around with arrow keys

Before step 8 we can see that dosemu provides a nicely scaled window (unlike without the `$_X_font` setting). It looks like this:

![Screenshot at 2022-07-23 20-52-24](https://user-images.githubusercontent.com/31538682/180619103-838e1a63-129c-4235-988b-662623946daf.png)

However, once you enter the data window and move around the cursor some, it leaves artefacts. This in turn looks like this:

![Screenshot at 2022-07-23 20-52-40](https://user-images.githubusercontent.com/31538682/180619114-78fa565b-d3b4-4d62-aa7d-ed86f3fb3f39.png)

Redrawing the Insight screen (F5) does not help. Expanding the data window using Alt+Z does help, but not entirely; the parts that end up with the same characters displayed appear to be unaffected:

![Screenshot at 2022-07-23 20-55-09](https://user-images.githubusercontent.com/31538682/180619147-97361270-6e64-49e9-9fc4-466d4abebe60.png)

**Attach program/game binaries or provide an URL**

Listed in how to reproduce

**Attach the log**

[boot.log](https://github.com/dosemu2/dosemu2/files/9174456/boot.log)

**A regression?**

Not known.

**Additional info**

Using FreeDOS kernel and FreeCOM. On a Debian 11 desktop system.

**Comment by stsp** [comment]
Does something like this
affect the situation?
```
--- a/src/plugin/X/X_font.c
+++ b/src/plugin/X/X_font.c
@@ -153,7 +153,7 @@ static void X_draw_text_cursor(void *opaque, int x, int y, Bit8u attr,
       x * font_width,
       y * font_height + cstart,
       font_width,
-      cend - cstart + 1
+      1
     );
   }
 }
```

**Comment by ecm-pushbx** [comment]
This does fix the problem, but the cursor that blinks on and off then is only a line now. And it is displayed at the top of the cell at the cursor position, instead of bottom. But yes, no more artefacts.

**Comment by stsp** [comment]
Please find out the values of
`start` and `cstart` vars.

**Comment by stsp** [comment]
`end`, `cend` would also be good.

**Comment by ecm-pushbx** [comment]
With this patch:

```
diff --git a/src/plugin/X/X_font.c b/src/plugin/X/X_font.c
index f7f07f42f..aab9d6aec 100644
--- a/src/plugin/X/X_font.c
+++ b/src/plugin/X/X_font.c
@@ -148,12 +148,14 @@ static void X_draw_text_cursor(void *opaque, int x, int y, Bit8u attr,
     if (cstart == -1) cstart = 0;
     cend = ((end + 1) * font_height) / vga.char_height - 1;
     if (cend == -1) cend = 0;
+    X_printf("X_draw_text_cursor cstart=%i cend=%i start=%i end=%i\n",
+    	cstart, cend, start, end);
     XFillRectangle(
       text_display, text_window, text_gc,
       x * font_width,
       y * font_height + cstart,
       font_width,
-      cend - cstart + 1
+      1
     );
   }
 }
```

We get these values: (running `dosemu -X -D+9X`)

```
$ grep "X_draw_text_cursor" .dosemu/boot.log | LC_ALL=C sort | uniq
X_draw_text_cursor cstart=1 cend=32 start=0 end=13
X_draw_text_cursor cstart=16 cend=18 start=14 end=15
```

**Comment by stsp** [comment]
cend==32 while end==13 looks clearly
wrong. Please find the values of font_height
and vga.char_height so that we can see
how have that happened.

**Comment by ecm-pushbx** [comment]
```
$ grep "X_draw_text_cursor" .dosemu/boot.log | LC_ALL=C sort | uniq
X_draw_text_cursor cstart=1 cend=32 start=0 end=13 font_height=19 vga.char_height=8
X_draw_text_cursor cstart=16 cend=18 start=14 end=15 font_height=19 vga.char_height=16
```

**Comment by stsp** [comment]
OK so `end` exceeds char_height.
I simply don't know how that should
be handled. Cursor shape is set via
crtc registers and the wrong settings
are possible, as we see here.
Please see src/base/video/text.c:239
and below. There I simply mask
cursor_shape to 0x1f, but that probably
wasn't enough.
Do you (or anyone else here) happen
to know the correct behavior?

**Comment by stsp** [comment]
Also do you know how they change
font height from 16 to 8? Is it done
via int10 calls? If so then bios should
be responsible for keeping cursor
position consistent.

**Comment by ecm-pushbx** [comment]
https://github.com/FDOS/freecom/blob/7b7889c367f0742f269dfa2bfd6586993837a50d/tools/50.asm This is the call that changes into 50-line mode which I think is also what changes the height of the cells.

**Comment by ecm-pushbx** [comment]
By the way, if I focus a window other than dosemu then the "transparent" cursor shown in the dosemu window is correct.

**Comment by ecm-pushbx** [comment]
Insight sets the cursor size using https://fd.lod.bz/rbil/interrup/video/1001.html in https://hg.pushbx.org/ecm/insight/file/fb36068d7047/src/windows.inc#l1493

**Comment by stsp** [comment]
Will something like this help?
```
--- a/src/base/bios/int10.c
+++ b/src/base/bios/int10.c
@@ -1227,6 +1227,11 @@ int int10(void) /* with dualmon */
            if(LO(ax) >= 0x10 && !adjust_font_size(vga_font_height))
              v_printf("Problem changing font height %d->%d\n",
                       READ_WORD(BIOS_FONT_HEIGHT), vga_font_height);
+           if (using_mono_mode())
+             set_cursor_shape(0x0b0d);
+           else
+             set_cursor_shape(0x0607);
+
            break;
 
           case 0x20:           /* set 8x8 gfx chars */
```

Yeah, I am puzzled with such
invocation, not sure why mono
and why the params like this,
but its how it is done in other
places of int10.c.

**Comment by ecm-pushbx** [comment]
Didn't test your patch yet. But doesn't Insight's int 10h service 01h call invoke `set_cursor_shape` again at https://github.com/dosemu2/dosemu2/blob/80882dda567de16070e1187ca6e5150ab5bbbe6b/src/base/bios/int10.c#L809 overwriting whatever your patch sets?

**Comment by stsp** [comment]
What value does it set?

**Comment by ecm-pushbx** [comment]
I already linked it: https://hg.pushbx.org/ecm/insight/file/fb36068d7047/src/windows.inc#l1493 Quoted:

```
no_cursor:
		mov	cx,2020h	;### 2000h ?
		jmp	set_cursor
;
small_cursor:
		mov	cx,0607h	;### 0d0eh ?
		jmp	set_cursor
;
large_cursor:
		mov	cx,000dh	;### 000fh ?
;
set_cursor:
		push	ax
		mov	ah,1
		int	10h
		pop	ax
		ret
```

**Comment by stsp** [comment]
So maybe in case of small font
it sets large_cursor?

**Comment by ecm-pushbx** [comment]
Yes, it does. The large cursor function is called unconditionally in the Shift+D mode at https://hg.pushbx.org/ecm/insight/file/fb36068d7047/src/iface_2.inc#l1903

So I assume Insight should choose a smaller (but still large) cursor in case it runs in 50-rows mode?

It does seem like dosemu should not leave the artefacts though, even when we select a too-large cursor.

**Comment by stsp** [comment]
> So I assume Insight should choose a smaller (but still large) cursor in case it runs in 50-rows mode?

Can you try that?

> It does seem like dosemu should not leave the artefacts though, even when we select a too-large cursor.

If someone tells me how it should
work when cursor_shape in crtc is
set larger than the font, then I'll fix.
For now I am not in a mood of figuring
it out from baremetal or from other
emulators.

**Comment by ecm-pushbx** [comment]
I added a configuration item to select the value in `cx` used for the set cursor calls: https://hg.pushbx.org/ecm/insight/rev/4d7e14ca09a9

Choosing 000Bh or smaller down to 0004h (inclusive) results in the desired cursor size without artefacts (in 50-rows mode). Smaller sizes result in partial cursors at the top of the selected cell.

**Comment by ecm-pushbx** [comment]
In 25-line mode values from 0004h to 000Bh also seem to be fine, at least in `dosemu -X`. So I'm tending towards 000Bh as the default value to use for both modes.

**Comment by ecm-pushbx** [comment]
~~I could also get the initial cursor value as set by DOS/BIOS(?) when 50-rows mode is selected, and use that as "large cursor" default value. In that case your suggested patch could change things around.~~ (**ETA**: DOS usually has a small cursor, right?)

**Comment by stsp** [comment]
> (ETA: DOS usually has a small cursor, right?)

novell dos seems to have large cursor
by default in their command.com. :)
I think you should use font_height-1
for large cursor value.

**Comment by ecm-pushbx** [comment]
The Interrupt List says at https://fd.lod.bz/rbil/interrup/video/1001.html

>	applications which wish to change the cursor by programming the
>	  hardware directly on EGA or above should call INT 10/AX=1130h or
>	  read 0040h:0085h first to determine the current font height

This BDA location is listed as:

> MEM 0040h:0085h - VIDEO (EGA/MCGA/VGA) - CHARACTER HEIGHT IN SCAN-LINES

So is it valid to read `word [40h:85h]` to determine font_height? It says 16 (0010h) in 25-rows mode and 8 in 50-rows mode.

I don't understand how to get the font_height from https://fd.lod.bz/rbil/interrup/video/101130.html which is referenced in the part I quoted.

**Comment by ecm-pushbx** [comment]
The return value in `cx` says "bytes/character of on-screen font (not the requested font!)" and the table below says "graphics data for character, one byte per scan line" so probably the `cx` return value is the font_height? It seems to match: 10h in 25-rows mode, 8 in 50-rows mode.

**Comment by stsp** [comment]
Yes that looks sensible.

**Comment by ecm-pushbx** [comment]
https://hg.pushbx.org/ecm/insight/rev/8e677b69f2e0 Did that now. I may test this on some other platforms at a later time.

**Comment by ecm-pushbx** [comment]
Oops I did a wrong.

**Comment by ecm-pushbx** [comment]
https://hg.pushbx.org/ecm/insight/rev/40917cdd78b4 fix to the fix. Actually using font_height minus 1 now, still works as expected here.

**Comment by stsp** [comment]
So I don't expect we have a test-case
for this now, so it should be closed?

**Comment by ecm-pushbx** [comment]
Yes, appears to be a bug in the application. Unless you really want to look into the artefacts and compare to real machines.
