### ISSUE TITLE
DUMP.EXE (MIDI utility) crashes DOSemu

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1757]
**Describe the bug**
DUMP.EXE is a utility which sends raw MIDI data from a file to a MIDI device.  It is commonly used to send MIDI Sysex messages to initialize, reset or place a MIDI device in a particular state.  As of 8190f8c1996ca851b04799af2405fee8c0a001a2, DUMP.EXE will hang DOSemu when the utility attempts to send MIDI data from a file to a MIDI device.

MUNT is the MIDI device in use when the lock up is observed.

**To Reproduce**
Run `DUMP.EXE LARESET.SYX` from the attached DUMP.ZIP

**Attach program/game binaries or provide an URL**
[dump.zip](https://github.com/dosemu2/dosemu2/files/9175330/dump.zip)

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/9175324/boot.log.zip)

**A regression?**
Yes.  DUMP.EXE would succeed prior to 8190f8c1996ca851b04799af2405fee8c0a001a2.

**Additional info**
None.

**Comment by stsp** [comment]
Obviously you do `emusound -es mt32`
as otherwise there is no hang.
Don't do that, just use
`$_midi_driver = "munt"`.
Or if you insist switching to mt32 mode,
then do
`$_mpu_irq_mt32 = (5)`

**Comment by stsp** [comment]
Well, there is a problem with
irq2 though.

**Comment by stsp** [comment]
Should now be fixed.
Pre-existing bug.
Good that it have finally
triggered.
