### ISSUE TITLE
First Alt+O keypress (1800h) gets stuck in dosemu -t

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1759]
**Describe the bug**

The first Alt+O keypress appears to get stuck. It doesn't show up initially to the DOS interrupt 16h interface, but may be inserted later before other keypresses.

**To Reproduce**

1. Run Hacker's Keyboard on Android mobile device
2. Connect to server using ConnectBot
3. Use or do not use `screen` (no difference)
4. Run `dosemu -K "$PWD" -t -E "keybtest.com !"`
5. Press Alt+O
6. Press Alt+O again
7. Press Alt+O again
8. Press Alt+C
9. Press Enter twice

Output is **NO** reaction to first Alt+O keypress. Second and third Alt+O keypress are detected once each (keycode 1800h). Before the Alt+C keypress (2E00h) a third Alt+O keypress shows up.

Output:

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20220724-365-g80882dda5
1800
1800
1800
2E00
1C0D
```

`cat -` doesn't have this problem, it immediately receives `^[o` for each Alt+O keypress.

**Attach program/game binaries or provide an URL**

https://pushbx.org/ecm/test/20220803/keybtest.com

**Attach the log**

https://pushbx.org/ecm/test/20220803/1900.log

**A regression?**

Not known.

**Additional info**

Using FreeDOS kernel and FreeCOM.

**Comment by ecm-pushbx** [comment]
It doesn't seem to matter if an Alt+O keypress is the first or a later keypress for the application. For example, I noticed the error after having pressed F10 - O - T - S - Alt+O to bring up Insight's terminal settings page and try to close it using the "Ok" button's accelerator.

**Comment by ecm-pushbx** [comment]
Something interesting: If I press Alt+O then C, after a short delay the keycode 4D00h is produced. [According to Insight's sources](https://hg.pushbx.org/ecm/insight/file/e2f07142a116/src/insight.inc#l365) that's the right arrow keycode.

Other than that the Alt+O getting stuck appears to be reset by most other keys, ie a subsequent Alt+O will also get stuck.

**Comment by ecm-pushbx** [comment]
Arrow keycodes can be produced using all letters A, B, C, D after an Alt+O keypress. Below is the keybtest output of pressing Shift+A, Alt+O, A, Shift+B, Alt+O, B, Shift+C, Alt+O, C, Shift+D, Alt+O, D.

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20220724-365-g80882dda5
1E41 "A"
4800
3042 "B"
5000
2E43 "C"
4D00
2044 "D"
4B00
```

**Comment by ecm-pushbx** [comment]
Pressing F10, O, T, S, Alt+O, Alt+O, Shift-S results in the following keycodes:

```
    Build 2.0pre9-dev-20220724-365-g80882dda5
4400
186F "o"
1474 "t"
1F73 "s"
1800
3E00
```

3E00h is expected to mean F4, so Insight happened to run its F4 function which (expectedly) crashed the machine. I don't know by what logic the stuck Alt+O results in this keycode being received.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by ecm-pushbx** [comment]
This introduces a short but noticeable delay. It does seem to fix it though, no more stuck keypresses. Thank you!
