### ISSUE TITLE
[Annoyance] In dosemu -dumb sometimes a line is displaced by 80 columns

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1760]
**Describe the bug**

Certain control flows with my debugger in `dosemu -dumb -td -kt` mode end up with a line displaced by 80 columns, either once or multiple times. That is, it appears dosemu displays 80 blanks before some lines. I have not yet debugged at what point exactly this happens so the test case is a simple sequence involving the whole debugger.

**To Reproduce**

1. Download `lcdebugu.com` from provided link (this is a conditionally debuggable build)
2. Run ` dosemu -dumb -td -kt -K "$PWD"
-E "lcdebugu.com /d- lcdebugu.com /d+"`
3. Run `g` command
4. Run `t` command
5. First line of the trace register dump is displaced by 80 columns

Output:

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20220803-366-g700b71533
-g
~-t
                                                                                AX=0000 BX=0000 CX=0000 DX=0000 SP=0000 BP=0000 SI=0000 DI=0000
DS=3D18 ES=3D18 SS=3D18 CS=3D18 IP=0000 NV UP EI PL ZR NA PE NC
3D18:0000 CD20              int     20
~-q

Program terminated normally (0000)
-q
```

**Attach program/game binaries or provide an URL**

https://pushbx.org/ecm/test/20220806/lcdebugu.com

**Attach the log**

https://pushbx.org/ecm/test/20220806/1015.log

**A regression?**

`Build 2.0pre8-20191102-1332-g9cf2b7560` is fine.

**Additional info**

Using FreeDOS kernel and FreeCOM. Connected to server across ssh using the ConnectBot app. Happens both either under `screen` terminal multiplexer or without it.

**Comment by ecm-pushbx** [comment]
Tried to debug lCDebug's `run` function with dosemu's dosdebug but it is a pain to use (missing P command, BP command doesn't work reliably) and also apparently ignores the TF set by lCDebug so the client didn't return after executing its `retn` and instead went off into `int 20h`, which I debugged until the FreeDOS kernel calls interrupt 2Fh function 111Dh at which point the control flow got away from dosdebug and it reported it was no longer in stopped state.

```
dosdebug>
system state: emulated,stopped
AX=111d  BX=b89c  CX=0000  DX=0000  SI=0000  DI=0000  SP=08bc  BP=08c6
DS=00d9  ES=0000  FS=0000  GS=0000  FL=000b3344
CS:IP=ffff:07de       SS:SP=00d9:08bc

ffff:07de CD2F             int  2F

dosdebug>
dosdebug>
need to be in 'stopped' state for this command
```

The annoyance doesn't seem to have been caused by any of this code (lDebug `run` function until actually running client) it appears.

**Comment by ecm-pushbx** [comment]
Oh, I found this is not (only) dosemu's fault. At https://hg.pushbx.org/ecm/ldebug/file/d25551ebdef6/source/run.asm#l5700 we call interrupt 10h service 09h:

```
	push es
	mov ax, 0040h
	mov es, ax
	mov al, [es:84h]	; did the number of screen rows change?
	cmp al, [vrows]
	mov [vrows], al
	jz @F
	mov dh, al		; yes. we cannot fully restore, but at least
	mov dl, 0		; clear bottom line to ensure the debugger displays
	mov [es:50h], dx	; will be seen.
	mov bx, 0007h		; BH=video page, BL=attribute
	mov cx, 80		; CX=columns
	mov ax, 0920h		; AL=char to display
	int 10h
@@:
	pop es
```

The `vrows` variable is initially zero so the first time this code runs it will call interrupt 10h. This is supposed [to write at the cursor position](http://fd.lod.bz/rbil/interrup/video/1009.html). The memory `word [40h:50h]` is supposed to be [the first page cursor position](http://fd.lod.bz/rbil/memory/video/m00400050.html). So it appears newer dosemu2 will advance the cursor in -dumb mode when int 10h service 09h is called, but old dosemu2 will not. What is the correct way to fix this?

Additionally I should have just attempted to break at `cs:4027h` after the debug-mode lCDebug has restored the upper debugger's handlers. (Ie before the `run` function returns but after the critical part that I cannot debug.) Then I could have comfortably debugged the remainder of the interrupt return code in my debugger instead of having to try to use dosdebug.

**Comment by ecm-pushbx** [comment]
Worked around on my end by https://hg.pushbx.org/ecm/ldebug/rev/86bffc658a96

**Comment by ecm-pushbx** [comment]
By the way, to simulate the debuggee returning to lDebug in my last dosdebug session I assembled a far jump to lDebug's interrupt 1 handler before attaching dosdebug. This then allowed me to run the lDebug T command under dosdebug, including the critical parts of `run` / `intrtn`, and still have the control flow return into lDebug as expected. That is a workaround for dosdebug not calling lDebug's trace interrupt handler.

**Comment by ecm-pushbx** [comment]
Made a small test program: https://pushbx.org/ecm/test/20220806/test.asm

In recent dosemu2 `dosemu -dumb -td -kt -K "$PWD" -E "test.com"` will displace the test message. In older dosemu2 it will not displace it.

**Comment by stsp** [comment]
So what is the bug here?
Will it displace the message under gfx
back-end like SDL?

**Comment by ecm-pushbx** [comment]
I think it will not because this function should not move the cursor. I will check in a few hours on the desktop dosemu2.

**Comment by ecm-pushbx** [comment]
> So what is the bug here? Will it displace the message under gfx back-end like SDL?

Tested on the desktop in all of `dosemu -dumb -td -kt`, `dosemu -X`, and `dosemu -S`. In the windowed mode the message is not displaced (as expected). The `-dumb` mode differs between old and new dosemu2, old doesn't displace and new does displace.

**Comment by stsp** [comment]
Added missing \r.
Does this make things better?

**Comment by ecm-pushbx** [comment]
I don't think it will. There is no linebreak between the 10.09 call and the 10.0E that displays our message. And 10.09 should **not** unconditionally truncate the line, it should leave the cursor exactly where it was. Will compile and report about the results.

**Comment by ecm-pushbx** [comment]
Built this and ran the test again, message still gets displaced.

**Comment by stsp** [comment]
> And 10.09 should not unconditionally truncate the line, it should leave the cursor exactly where it was.

Yes but in dumb mode the x position
is currently not maintained so it doesn't
matter. Of course I can maintain it via
printing spaces, but no one cares.

So I don't understand, do you mean the
patch d3b1db0df is responsible for a
problem, or something else?

**Comment by ecm-pushbx** [comment]
Well, yes, sort of. 10.09 now displays literal codepoints whereas it previously displayed nothing. Both are inaccurate as to what that service should do; it should display but not advance the cursor. Prior it didn't display but did preserve the cursor. Now it does display but doesn't preserve the cursor. You'll have to decide which one is more desirable.

**Comment by ecm-pushbx** [comment]
Maybe you can check for blank (U+0020) codepoints and not display anything for those specifically. That would be an overall improvement if you otherwise retain the displaying.

**Comment by stsp** [comment]
I can add \r after every display.
Will that help?

**Comment by ecm-pushbx** [comment]
That wouldn't be accurate either. If you display some text using 10.0E and then call 10.09 the cursor should stay where it is, not skip back to the leftmost column.

**Comment by stsp** [comment]
That wouldn't be accurate but maybe
it would fix your problem. I do not intend
to make dumb mode accurate.

**Comment by ecm-pushbx** [comment]
My suggestion with checking for blanks but displaying otherwise would also fix it.

**Comment by stsp** [comment]
I don't think so.
What if someone uses blanks
for clear to eol?

**Comment by stsp** [comment]
"Fixed" then.
