### ISSUE TITLE
Strip Poker: unsupported video mode

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1764]
**Describe the bug**
Running the game shows:
![Screenshot_20220808_194230](https://user-images.githubusercontent.com/877112/183480169-5f8d70d2-b376-48c5-88dc-5b903f1e4eda.png)

**To Reproduce**
Run the game.

**Attach program/game binaries or provide an URL**
[sp.tar.gz](https://github.com/dosemu2/dosemu2/files/9283932/sp.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9283936/boot.log)

**A regression?**
Seems unlikely.

**Comment by misutoneko** [comment]
According to DOSBox documentation, this one needs either Tseng (ET4000) or Paradise to work (or Video7, I suppose).
The stripkrx.exe binary actually has some VESA references in strings and code, but I'm not sure if that code ever gets used at all(?)

The VESA version used here would be 1.2 btw (the signature check is looking for 'VESA' rather than 'VBE2').
EDIT: Correction: The newer VESA versions do use a different signature 'VBE2', but it's for the input buffer.
The output buffer signature remains the same 'VESA'. So the signature check should actually work for VBE2+ too.

**Comment by stsp** [comment]
Interesting, thanks for info.
Still it may make sense to look into
a log or otherwise find out if maybe
it just asks for the video mode with
int10, but the mode it asks for, is
specific to the video cards you mentioned.
If it does only that and doesn't access
the card-specific registers directly,
then we can easily add a support
for that. I just haven't got to look
into that myself so maybe you can. :)

**Comment by misutoneko** [comment]
Yes, it indeed does use INT 0x10 to set a 640x480x256 mode.
The mode number is 0x5F for Paradise and 0x2E for Tseng (found out these by tracing these calls in dosbox-debug).

And at least for Video7, the detection code seems to use a INT 0x10 call (AH=0x6F) also.
For Tseng/Paradise I suspect the chipset detection is done with direct port access but haven't really looked at that.

**Comment by stsp** [comment]
5f seems to be supported, others
not. So it probably doesn't get to
5f and just fails on 2e?

**Comment by misutoneko** [comment]
Yes exactly, in dosemu the chipset detection fails so no video mode setting either.
Maybe the detection part could be skipped somehow (to force Paradise).

EDIT: Yup, it can be tricked to use VESA mode by changing the byte at offset 0x1e5b0 from zero to => 0x07.
It will promptly crash dosemu with a GPF though.

**Comment by stsp** [comment]
It first calls this:
http://www.ctyme.com/intr/rb-0549.htm
to detect hercules? Weird.
Then it detects Tseng with this:
http://www.ctyme.com/intr/rb-0221.htm
Then sets mode 0x12 which is supported,
but then for some reason it detects Video7
with this (6f as you said):
http://www.ctyme.com/intr/rb-0380.htm
which fails.

**Comment by misutoneko** [comment]
Yeah there's all kinds of Hercules and CGA/EGA stuff in strings too, I guess they're residue from the Genus Microprogramming library. But yeah weird that it's still there and used that way.
There are other games that use this library too, quite a lot educational titles (but educational in a different style from this one :)
But the ones I found seem to be mostly older ones (Math Rescue, Word Rescue etc.) and don't use SVGA.

**Comment by stsp** [comment]
So is it going to work on a real vbe-compatible
cards like todays radeons and geforces?
Or does it work only with the legacy
boards? If so, I am going to close this.

**Comment by misutoneko** [comment]
I don't see any obvious way how this could be made to work without patching the binary. Vote for close.

**Comment by stsp** [comment]
Of course it would be good if
someone can actually test it
on a modern video card (w/o
any emulator).

**Comment by jschwartzenberg** [comment]
Just did this, but it seems I can't get the game to run at all:
![20220903234338](https://user-images.githubusercontent.com/877112/188288581-e10aed1e-fafa-4c58-8105-7f4e7f294e4d.png)

I don't know if the game seems to do anything odd with the partition/filesystem? I don't think my drive is failing. Maybe I should try with FreeDOS?

**Comment by stsp** [comment]
What emulator is that?
Don't tell me you are trying on
a bare-metal? :)

**Comment by jschwartzenberg** [comment]
Running it from Windows shows me:
![20220903235518](https://user-images.githubusercontent.com/877112/188288797-a4f86e64-9607-4283-9cb8-54904359fcb9.png)

This is bare-metal.

**Comment by stsp** [comment]
So basically you can't attribute
the failures to the video card because
it simply doesn't work, right?

**Comment by jschwartzenberg** [comment]
Yeah indeed, I haven't been able to get the game to run. I'll try executing the executable now instead of the batch file... Have to reboot though as this thing hangs Windows 98.

**Comment by jschwartzenberg** [comment]
Ah, that's better:
![20220904000425](https://user-images.githubusercontent.com/877112/188288989-33db897b-10b5-45cd-8b9a-c22777790b2d.png)

This is a GeForce 4 Ti4200 if I remember correctly btw.

**Comment by jschwartzenberg** [comment]
Btw. in case you're curious how I take screenshots now. That system has an AGP slot with a card that has a DVI connector. I use a DVI to HDMI cable to hook it up to the TV. On the rooted TV I use this tool: http://forum.samygo.tv/viewtopic.php?f=63&t=9201

(There is also a SB Audigy2 connected with SPDIF and with an internal pass-through the SB AWE64's SPDIF is passed to that, so I could also capture the digital audio stream off the EMU8k and OPL chips if needed.)

**Comment by stsp** [comment]
Ok, you are really a retro-computing man. :)
Though we can conclude that the game
therefore works as expected.
Right?

**Comment by jschwartzenberg** [comment]
Haha :) I'm always wondering how long I can keep this system around, I don't use it very often. (Of course I do watch TV.)

I don't know if you want to close this or change it into a feature request for this video mode. Either is fine with me :)

**Comment by stsp** [comment]
There is no such thing as a missing video
mode, at least at that stage. It uses various
calls to detect the old video boards, and
that fails. Maybe if some detection succeeded,
it would then try an unsupported video mode.

**Comment by jschwartzenberg** [comment]
I guess in theory the detection could be patched but then it still won't work? I'll check if there are different versions of this game out there.

**Comment by misutoneko** [comment]
As I mentioned you can force VESA by patching the binary, e.g. in Linux that can be done with something like:
echo -e 07 |xxd -p -r |dd of=stripkrx.exe bs=1 conv=notrunc seek=124336

(Or just use some hex editor.)
For Video7, just use 06 instead of 07 as the value, that one also manages to initialize the screen.
It will also fail but in a slightly different way.

**Comment by stsp** [comment]
Yes, that works, thanks:
```
0001E5B0:     00         07
```

**Comment by jschwartzenberg** [comment]
Yeah, I see the girl, hear some sound and then crash. Should I try this on bare metal?

**Comment by stsp** [comment]
Would be interesting.
Or in dosbox?

**Comment by jschwartzenberg** [comment]
Seems they all behave the same. This is on bare metal:
![20220908202830](https://user-images.githubusercontent.com/877112/189198642-91ee34bc-34ff-4908-850f-dbc6965a49f4.png)

When I push some button, I hear some prrrrr noise from the pc speaker.

Probably this one can only run in something like PCem or MAME.

DOSBox shows a lot of `ERROR CPU:Illegal Unhandled Interrupt Called 6`.

**Comment by stsp** [comment]
The girl on that screen-shot
is not worth the trouble then.

**Comment by jschwartzenberg** [comment]
Note that it hangs at this screen, I can't get it to proceed, just ctrl+alt+del allows rebooting. That girl actually also shows on dosemu with that patch :)
