### ISSUE TITLE
Unnecessary Roughness doesn't start (ERROR: DPMI: Warning: trying to leave DPMI when in_dpmi_pm_stack=1)

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1767]
**Describe the bug**
![Screenshot_20220813_092942](https://user-images.githubusercontent.com/877112/184473888-fb3f1c55-44e5-4069-b1f0-3316fbb7aa1e.png)

**To Reproduce**
Just run it.

**Attach program/game binaries or provide an URL**
[ur.tar.gz](https://github.com/dosemu2/dosemu2/files/9331021/ur.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9331023/boot.log)

**A regression?**
Might this be related to recent changes?

**Comment by stsp** [comment]
Works on pre7.

**Comment by stsp** [comment]
Bisect: 49678ab
Hmm.
Works with `$_cpu_vm_dpmi = "native"`

**Comment by stsp** [comment]
It does some crap like loading
GDT code selectors after checking
them with verr, into DS. But in our
kvm setup there are no user-readable
code regs.
I suspect this is not going to be fixed.

**Comment by stsp** [comment]
Turned out to be the major bug in
instr_dec library.
I reverted instremu removal and used it
for mis-implemented instructions, as
instremu does things rightly, whereas
my instr_dec still doesn't work. :(

**Comment by stsp** [comment]
Damn, wrong bug. :(
Had to close #1768 instead

**Comment by stsp** [comment]
> Works with $_cpu_vm_dpmi = "native"

Seems to not working now even with native. :(

**Comment by stsp** [comment]
Works with this change:
```
diff --git a/src/base/emu-i386/kvm.c b/src/base/emu-i386/kvm.c
index 88d973159..d3060e6cd 100644
--- a/src/base/emu-i386/kvm.c
+++ b/src/base/emu-i386/kvm.c
@@ -725,8 +725,8 @@ void mprotect_kvm(int cap, dosaddr_t targ, size_t mapsize, int protect)
       monitor->pte[page] |= PG_PRESENT | PG_RW | PG_USER;
     else if (protect & PROT_READ)
       monitor->pte[page] |= PG_PRESENT | PG_USER;
-    if (cap & MAPPING_KVM)
-      monitor->pte[page] &= ~PG_USER;
+//    if (cap & MAPPING_KVM)
+//      monitor->pte[page] &= ~PG_USER;
   }
   monitor->cr3 = sregs.cr3; /* Force TLB flush */
 }
```

It seems to require writable IDT.
It does SIDT.
As for why it doesn't work with native
DPMI, is likely because when I tested
it last time, UMIP was enforced on the
kernel. But these days they started to
emulate all instructions, effectively
disabling UMIP. :( So SIDT is not
trapped again.

@ricardon how have that happened?
We relied on UMIP, and you started
to emulate all instructions as if there
is no UMIP?

**Comment by stsp** [comment]
I added the PR with basic UMIP
support for our kvm back-end.
But as for native dpmi, it all depends
on @ricardon who can hopefully
make UMIP to work again.

**Comment by jschwartzenberg** [comment]
This one still doesn't run "out of the box" as far as I can see? When I run it now I get the same error as in the original screenshot.

**Comment by stsp** [comment]
It works with kvm only.
And only if your CPU supports umip,
grep umip /proc/cpuinfo

**Comment by jschwartzenberg** [comment]
> And only if your CPU supports umip,
> grep umip /proc/cpuinfo

So that's the missing part here:
```
[julius@elleboog ~]$ grep umip /proc/cpuinfo
[julius@elleboog ~]$ echo $?
1
```
Would it make sense to print a warning when using KVM on a CPU without umip?

**Comment by stsp** [comment]
OK, added, but only to log, not to console.

**Comment by jschwartzenberg** [comment]
I cannot judge how hard it would be to have a console variant. Maybe if you observe many duplicate bug reports because people are not well-aware of the specific mode and variation DOSEMU2 runs in, it would make sense to have more visibility on this. I understand there's a goal to have all modes bring equal compatibility too.

**Comment by stsp** [comment]
> Maybe if you observe many duplicate bug reports

... then there would be a speech. :)
Maybe in that case I'll add some umip-less hack.
But so far we are talking about one random,
non-interesting game.
When we had flashing textures in wolf3d, I
spent 6 years chasing it, because wolf is an
iconic game. But I won't spend any more
time on this game.

> I understand there's a goal to have all modes bring equal compatibility too.

Again, not for some random crappy game.

**Comment by stsp** [comment]
You probably missed the fact that
recently I didn't hesitate to disable
1-2 glorious Andrew CI tests just to
not write the lock manager and use
the native locking instead.
And this is a much "wider" action
than to rely on umip, and not to have
the parity for native dpmi back-end.
I.e. in a larger projects disabling CI
tests to push some patch forward,
may be a great shame, but in dosemu2 -
"everything suits, whatever works".
There are no coding resources
for any other approach. In fact, as the
time shows, even this approach doesn't
save the world. :)

**Comment by stsp** [comment]
And in fact, here's the solution for
umip-less CPUs:
```
Comparing G:\ur.old and G:\ur.exe
0002AC4E:     A5      90
0002AC4F:     A5      90
```

**Comment by jschwartzenberg** [comment]
Cool! That indeed makes it run!! Would it make sense to update the wiki?

**Comment by stsp** [comment]
As you wish.
I can't say that this game is even
playable under dosemu2, so I don't
care.

**Comment by jschwartzenberg** [comment]
True that. I seems good to collect these kinds of patches though. They might help people in ways we cannot anticipate, maybe even unrelated to DOSEMU2 usage.
