### ISSUE TITLE
Alien Legacy doesn't run: ERROR: unsupported instr_len b5 5a

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1768]
**Describe the bug**
The game appears to hang on start-up. A lot of stuff is printed to the terminal.
```
ERROR: unsupported instr_len b5 5a
ERROR: eip: 0x02396f7b  esp: 0x02422ea8  eflags: 0x00010206
        trapno: 0x0d  errorcode: 0x00000040  cr2: 0x4135c000
        cs: 0x02bf  ds: 0x02c7  es: 0x02c7  ss: 0x02c7  fs: 0x0000  gs: 0x0317
EAX: 02580e44  EBX: 02580e4c  ECX: 02580e40  EDX: 0242826c
ESI: 02580e4c  EDI: 0241dd90  EBP: 02422f04
OPS  : 00 c7 42 40 6c 00 00 00 8b 10 -> 0f b5 5a 40 65 8b 1b 89 5a 46 
STACK: 58 02 c7 02 58 02 c7 02 39 02 -> 44 0e 58 02 40 0e 58 02 4c 0e
```

**To Reproduce**
Run the game.

**Attach program/game binaries or provide an URL**
[alegacy.tar.gz](https://github.com/dosemu2/dosemu2/files/9334062/alegacy.tar.gz)

**Attach the log**
[boot.log.gz](https://github.com/dosemu2/dosemu2/files/9334060/boot.log.gz)

**A regression?**
unknown

**Comment by stsp** [comment]
instr_len() in instremu.c doesn't implement
decoding of 0x0f-escaped opcodes.
@bartoldeman could you please explain
how the `it[]` array was filled, what sources
have you used for that? Can it be used for
the 0x0f-escaped opcodes, or another array
should be filled?
instremu itself calculates instr len together
with decoding modrm, so originally no bug
existed. But I use instr_len() externally, so
it would be good to have it properly implemented.
In this particular case it seems to fail on an
lgs instruction.

**Comment by stsp** [comment]
Turned out to be the major bug in
instr_dec library.
I reverted instremu removal and used it
for mis-implemented instructions, as
instremu does things rightly, whereas
my instr_dec still doesn't work. :(

**Comment by jschwartzenberg** [comment]
This one indeed works now! Great!

**Comment by stsp** [comment]
I reworked the fix, and lXX instructions
are now handled by instr_dec lib alone,
w/o instremu machinery.
For this I used the technique we didn't
try before. Namely, an "asm patches" on
the stack. Not sure if there going to be
any other use for such technique, than
to "get rid of instremu by any price", but
its quite a funny thing to have.
