### ISSUE TITLE
Storing Volume Name on MFS

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1769]
I'm looking at this problem https://github.com/FDOS/label/issues/17 over on FreeDOS and so I wrote some tests, see https://github.com/andrewbird/dosemu2/tree/t25. As you can see if you look at the tests https://github.com/andrewbird/dosemu2/runs/7827393203?check_suite_focus=true there are some FAT problems on FDPP and FreeDOS which should be looked at also, but on MFS all DOSes fail. 

Essentially the test does:
  1/ Using an extended FCB create a file that has filename 'SENTINEL' and attribute 0x8.
  2/ Do 'DIR' to see if that is recognised a the volume label

I've checked the xattr that's on the created file and it's just showing 0x20 (Archive), so somewhere it's losing the 0x8(Vol) bit

I can also see that on the MS-DOS 6.22 FAT test, such volume labels are stored in the BPB, even though we ask DOS to create a file in the root dir with VOL attribute, see:
~~~
C:\>testit.bat
testit.bat

C:\>d:

D:\>
D:\>rem DIR

D:\>c:\labcreat
Operation Success

D:\>DIR

 Volume in drive D is SENTINEL   
 Volume Serial Number is 1234-5678
 Directory of D:\

File not found

D:\>rem end
~~~

I wonder if we can't filter out the MFS calls that have the VOL attribute, and save / restore the value using xattrs as a sort of BPB location for MFS
~~~
ajb@polly:/clients/common/dosemu2.git$ xattr -l test-imagedir/dXXXXs/d
user.VOLUMENAME: MYNAME
~~~

**Comment by stsp** [comment]
As we already use xattrs for, well,
attrs, why not to store also the vol
attr there?
AFAIK the volume label displayed,
is just the first file with `vol` attr, so
you probably don't need any special
handling.

**Comment by andrewbird** [comment]
> As we already use xattrs for, well,
attrs, why not to store also the vol
attr there?
AFAIK the volume label displayed,
is just the first file with vol attr, so
you probably don't need any special
handling.

Yes a file with the volume attribute is the method of storing volume name on pre v4 DOS. Afterwards space was allocated in BPB for it. It has the advantage that there is no longer any problem in having a file / directory with the same name as the label. Here is an example on MS-DOS 6.22 (FAT) where there is a directory called 'sentinel' and the label is subsequently set the same.
~~~
C:\>testit.bat
testit.bat

C:\>d:

D:\>mkdir sentinel

D:\>echo hello >> sentinel\one.txt

D:\>
D:\>rem DIR

D:\>c:\labcreat
Operation Success

D:\>DIR

 Volume in drive D is SENTINEL   
 Volume Serial Number is 1234-5678
 Directory of D:\

SENTINEL     <DIR>         08-15-22   4:35p
        1 file(s)              0 bytes
                      10,608,640 bytes free

D:\>rem end
~~~

What's interesting is that the label is set by calling int21/16h to FCB creat a file in the root dir with vol attribute and the MS-DOS kernel actually stores it in the BPB, leaving the existing directory intact. Doing the same thing on FreeDOS/FDPP the call will return fail.

**Comment by stsp** [comment]
But since redirector doesnt deal with
bpb, I suppose this 4.0 way is sufficient.
Otherwise you need to allocate extra file
for xattrs and get races between multiple
dosemus.

**Comment by andrewbird** [comment]
> But since redirector doesnt deal with
bpb, I suppose this 4.0 way is sufficient.

Quite possibly (if you mean < 4?), but currently it doesn't work for setting at least as a plain file is created instead (the vol attribute is lost).

> Otherwise you need to allocate extra file
for xattrs and get races between multiple
dosemus.

I was thinking of applying the new volumename xattr to the unix directory that contains the top of the DOS drive, so avoiding a race, but I'm not sure if xattrs is atomic?

There's already something special going on with MFS regarding volume name. Somehow it's populated automatically from the last components of the unix directory and there's no correspondingly named file with volid attr set.
~~~
Interactive Prompt!
C:\>dir
 
 Volume in drive C is IR DXXXXS C
 Directory of C:\
 
TMP          <DIR>         08-15-22   4:35p
<snip>
~~~

**Comment by stsp** [comment]
Using root dir xattr sounds like an idea,
but at the same time I remember the
posdibility to just set the vol attribute on
an existing file with diskeditor.
If that normally (w/o diskeditor) fails on
fat and only creat call can set vol, then
I suppose its ok.

**Comment by andrewbird** [comment]
I used WDE (for my very first time) to test this **(on MS-DOS 6.22)**

1/ set the volume name to 'sentinel'
2/ created a file called 'twiddled'
3/ used wde to change the attrs from 0x20 (archive) to 0x8 (vol), as below
~~~
 
     Name: TWIDDLED
  Created: 01-01-1980 00:00:00.0        Attributes: --V---
 Accessed: 01-01-1980                      Cluster: 0002
 Modified: 08-15-2022 18:48:38                Size: 12
~~~

4/ did DIR on drive d: (FAT12), 'twiddled' file has disappeared but BPB volume name is still shown in preference.
~~~ 
C:\WDE>d:
 
D:\>dir
 
 Volume in drive D is SENTINEL
 Volume Serial Number is 1234-5678
 Directory of D:\
 
File not found
 
D:\>\ 
~~~

**Comment by stsp** [comment]
Can you set VOL with a DOS call?
I guess your wde (disk editor?) does
direct fs access.
I wonder if the DOS setattr call fails.

**Comment by andrewbird** [comment]
Actually I made a mistake, I didn't notice there was another entry in the root directory with the vol bit set (it had archive too).
~~~
 
 
C:\WDE>dir d:
 
 Volume in drive D is TWIDDLED
 Volume Serial Number is 1234-5678
 Directory of D:\
 
SENTINEL                 0 08-15-22   6:46p
        1 file(s)              0 bytes
                      10,612,736 bytes free
 
~~~
I removed that vol bit from its attrs and ...
So it seems that the first file found with vol bit set is used in preference to bpb volname value. And the original operation to create a file with vol attribute set must have created both the file and set the bpb volume name.


I also note that in the case where a directory with the target name sentinel exists, the file with volume name 'sentinel' is also created, without regard for the duplicate name. Here I removed the vol bit from the 'sentinel' file, and set it on 'twiddled'
~~~
 D:\>dir
 
 Volume in drive D is TWIDDLED
 Volume Serial Number is 1234-5678
 Directory of D:\
 
SENTINEL     <DIR>         08-15-22  11:44p
SENTINEL                 0 08-15-22  11:44p
        2 file(s)              0 bytes
                      10,604,544 bytes free
~~~

As a test I removed all the files with a vol bit set, and the dir/vol command shows 'has no label', so:
1 / whilst the bpb is set on file creat with vol bit, it seems it is never referenced
2/ msdos 6.22 is quite happy to have two filesystem entries with the same name if one is a directory and the other is a volume name.

It seems less than clear cut on what behaviour MFS should have, closing until I get some inspiration.

**Comment by skitt** [comment]
> Can you set VOL with a DOS call? I guess your wde (disk editor?) does direct fs access. I wonder if the DOS setattr call fails.

Labels can be created using [interrupt 0x21 service 0x16](https://fd.lod.bz/rbil/interrup/dos_kernel/2116.html) with an extended FCB; see https://github.com/FDOS/label/blob/master/src/label.c for an example implementation.

**Comment by stsp** [comment]
The question was whether you can
set the VOL to an existing file.
With diskeditor you can, but with
DOS call?

**Comment by skitt** [comment]
> The question was whether you can set the VOL to an existing file. With diskeditor you can, but with DOS call?

Ah right, no, there is no DOS call to set the volume bit on an existing file.

**Comment by andrewbird** [comment]
RBIL mentions that setattr int21/43 http://www.ctyme.com/intr/rb-2803.htm won't change DIRECTORY or VOLUME bits, but I didn't try this myself.

**Comment by andrewbird** [comment]
> Labels can be created using [interrupt 0x21 service 0x16](https://fd.lod.bz/rbil/interrup/dos_kernel/2116.html) with an extended FCB;

Actually there's an interesting note in the RBIL there about FCBs not working on FAT32, which is another thing to consider.

> see https://github.com/FDOS/label/blob/master/src/label.c for an example implementation.

Yep that's the program I'm looking at to debug for its issue https://github.com/FDOS/label/issues/17 . I wrote a test based on its volume setting method, see 98e1a8e8557
