### ISSUE TITLE
Calling int 2F.1680 in a loop with Disabled Interrupts sometimes loops infinitely, dosdebug says IF is on

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1773]
**Describe the bug**

I ran into a bug in Insight [in which it disabled interrupts (DI)](https://hg.pushbx.org/ecm/insight/rev/73e1b07abd73), then called interrupt 2Fh service 1680h [in a loop expecting a timer tick interrupt to occur](https://hg.pushbx.org/ecm/insight/file/73e1b07abd73/src/dialogs.inc#l506) and modify the tick count at `dword [40h:6Ch]`. I fixed this by [explicitly enabling interrupts](https://hg.pushbx.org/ecm/insight/file/8550a32eb2ae/src/keyboard.inc#l319) in the `idle` function.

I assume the bug previously evaded notice because dosemu2 will enable interrupts when the interrupt 16h service 01h is called. Most of the control flow loops in Insight will wait on keyboard input, not timer ticks. The loop in `run_push_button` however waits only for timer ticks.

Now as to the bugs in dosemu2:

1. Running dosdebug it shows values like `FL=00133a94` in which the Interrupt Flag (value 200h) appears to be set. This confused me during debugging.
2. Sometimes it appears that 2F.1680 enables interrupts, other times it does not. I suggest always enabling interrupts to be consistent.

**To Reproduce**

1. Run `dosemu -K "$PWD" -E "ldebugu.com timercli.com"`
2. Input a `g` command
3. dosemu hangs (`htop` shows 100% CPU time use)
4. Connect `dosdebug`
5. Input a `stop` command to `dosdebug`
6. Input `t` commands until test application code is disassembled
7. Note the `FL` value in `dosdebug` display
8. Run `kill` command in `dosdebug`

Oddly enough, running `dosemu -K "$PWD" -E "ldebugu.com /c=g timercli.com"` or  `dosemu -K "$PWD" -E "timercli.com"` the loop finishes unexpectedly, no infinite loop.

**Attach program/game binaries or provide an URL**

https://pushbx.org/ecm/test/20220821/

**Attach the log**

https://pushbx.org/ecm/test/20220821/1750.log

**Additional info**

Running FreeDOS kernel and FreeCOM.

**Comment by stsp** [comment]
Should now be fixed.
