### ISSUE TITLE
Enhancement: Don't require hard disk images to have a partition table

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1779]
Currently Dosemu accepts hard disk images that have either:
  - Dosemu header + partition table + filesystem
  - Partition table + filesystem

It would be really nice if Dosemu could work with bare filesystem images, so some scenario like this would be possible
~~~
dd if=/dev/zero of=fat32.img bs=1024k count=50
mkfs.fat -F 32 fat32.img
echo hello >  file1.txt
echo there > file2.txt
mmd -i fat32.img bob
mcopy -i fat32.img file1.txt file2.txt '::\bob' 
~~~

- Configure dosemu to use fat32.img as a harddisk
- Dosemu sees that it's a bare image and constructs an mbr/partition table on the fly

There already seems to be something similar in disks.c for raw partitions, https://github.com/dosemu2/dosemu2/blob/de40f54be505aff88d12e308065f1d7dbf2a28d5/src/base/misc/disks.c#L864

**Comment by stsp** [comment]
So why would this not work even now?
Looking into the code I can see that it
is trying to read MBR from /dev/hda by
stripping the last letter from eg /dev/hda6.
But it can tolerate the failure, in which
case it synthesizes the MBR by hands.
So I suppose that already works?

**Comment by andrewbird** [comment]
I tried it yesterday and the drive didn't appear in DOS. I'll try again, perhaps I did something wrong.

**Comment by andrewbird** [comment]
It looks as if it might be almost there, but I get two different results depending upon which DOS I use.
~~~
$ cat test-imagedir/dosemu.conf 
$_force_fs_redirect = (off)
$_hdimage = "dXXXXs/c:hdtype1 fat12.img +1"
$_floppy_a = ""
~~~

~~~
$ dd if=/dev/zero of=test-imagedir/fat12.img bs=1024k count=10
$ mkfs.fat -F12 test-imagedir/fat12.img
~~~


##### msdos 6.22 - drive d: seems to be overwritten with commands
~~~
CONF: disk type 'Directory' drive C:                                            
Setting up hdimage /tmp/test-imagedir/fat12.img                                 
Set up as an image                                                              
CONF: disk type 'Image' header_size: 0 drive D:                                 
default_drives 1                                                                
Added drive 2 (82): /clients/common/dosemu2.git/commands                        
Setting up default drives from F                                                
Added drive 3 (83): /usr/share/comcom32                                         
Added drive 4 (84): /usr/share/dosemu2-extras/bat                               
~~~
~~~
C:\>dir d:
 
 Volume in drive D is COMMANDS
 Volume Serial Number is 4ADD-1B8C
 Directory of D:\
 
FDPPCONF SYS           343 09-02-22   6:44p
FDPPAUTO BAT           604 06-04-22   2:28p
DOSEMU       <DIR>         09-02-22   6:56p
        3 file(s)            947 bytes
                   2,096,103,424 bytes free
 
C:\>dir e:
 
 Volume in drive E is IT COMMANDS
 Directory of E:\
 
FDPPCONF SYS           343 09-02-22   6:44p
DOSEMU       <DIR>         09-02-22   6:56p
FDPPAUTO BAT           604 06-04-22   2:28p
        3 file(s)            947 bytes
                   2,147,450,880 bytes free
~~~

##### FDPP seems to get confused during boot and can't find command.com
~~~
CONF: disk type 'Directory' drive C:                                            
Setting up hdimage /tmp/test-imagedir/fat12.img                                 
Set up as an image                                                              
CONF: disk type 'Image' header_size: 0 drive D:                                 
default_drives 1                                                                
Added drive 2 (82): /clients/common/dosemu2.git/commands                        
Setting up default drives from F                                                
Added drive 3 (83): /usr/share/comcom32                                         
Added drive 4 (84): /usr/share/dosemu2-extras/bat                               
~~~
~~~
 
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
D: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD5, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
CONFIG.SYS error in line 8
>>>device=dosemu\umb.sys
          ^
UMBs unavailable!
CONFIG.SYS error in line 9
>>>devicehigh=dosemu\ems.sys
              ^
UMBs unavailable!
CONFIG.SYS error in line 11
>>>devicehigh=dosemu\emufs.sys /all
              ^
UMBs unavailable!
CONFIG.SYS error in line 12
>>>devicehigh=dosemu\cdrom.sys
              ^
Process 0 starting: F:\command.com /e:384 /p /k %FDPP_AUTOEXEC%
Bad or missing Command Interpreter: F:\command.com /e:384 /p /k %FDPP_AUTOEXEC%
 Enter the full shell command line:              
~~~

##### with same config + image made with mkimage16 (has Fat12 filesystem at partition 1) and FDPP it looks like this
~~~
CONF: disk type 'Directory' drive C:                                            
Setting up hdimage /tmp/test-imagedir/fat12.img                                 
Set up as an image                                                              
CONF: disk type 'Image' header_size: 128 drive D:                               
default_drives 1                                                                
Added drive 2 (82): /clients/common/dosemu2.git/commands                        
Setting up default drives from F                                                
Added drive 3 (83): /usr/share/comcom32                                         
Added drive 4 (84): /usr/share/dosemu2-extras/bat                               
~~~
~~~
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
 
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
G: HD5, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)
Process 0 starting: F:\command.com /e:384 /p /k %FDPP_AUTOEXEC%
 
FreeDOS userspace tools can be installed with: insfdusr
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre9-dev-20220902-392-geafb3b4e3
Interactive Prompt!
~~~

**Comment by stsp** [comment]
Why don't you hint dosemu2 that
its a partition image and not a hdimage?

**Comment by andrewbird** [comment]
> Why don't you hint dosemu2 that
its a partition image and not a hdimage?

I couldn't seem to convince dosemu via config that the image was a partition. I did some experimentation with modifying the IMAGE handling code and have it working except for FAT32 images. They use a v7 EBPB which we don't know to parse yet, as I need to interrogate the VBR for various values. See https://en.wikipedia.org/wiki/BIOS_parameter_block#FAT32

**Comment by stsp** [comment]
Should now be implemented.

**Comment by andrewbird** [comment]
Ahh thanks, I did it here a little differently by fixing up IMAGE processing to recognise a VBR and generate a MBR for it, see https://github.com/andrewbird/dosemu2/commit/b0ff83693d47ee2686184acf0ab1e49c168ae93e

Anyway I'll try out your method now.

**Comment by stsp** [comment]
I think your code is good too, but
can you unify it with `set_part_ent()`?
Then lets apply.

**Comment by andrewbird** [comment]
> can you unify it with set_part_ent()?

Probably. I used `build_pi()` which seems to do mostly the same thing without the length detection and it also uses the partition struct rather than twiddling bytes. I also note that `dir_setup()` uses `build_pi()` too, so if you don't mind be asking why is it to be preferred in this case?

**Comment by stsp** [comment]
How about getting rid of a
set_part_ent() then? I don't
know why it should be preferred,
I just happened to use it in my
patch. :)

**Comment by andrewbird** [comment]
Okay, thanks. I'll look at tidying up what I have and see if `set_part_ent()` and `build_pi()` functionality can be combined.

**Comment by andrewbird** [comment]
I'm looking at the partition code and so I'm setting up a test environment.

I added a temporary disk to my system and partitioned it as follows:
~~~
Device     Boot  Start       End   Sectors   Size Id Type
/dev/sdb1         2048     26623     24576    12M  1 FAT12
/dev/sdb2        26624     59391     32768    16M  4 FAT16 <32M
/dev/sdb3        59392    131071     71680    35M  6 FAT16
/dev/sdb4       131072 234441647 234310576 111.7G  5 Extended
/dev/sdb5       133120    231423     98304    48M  b W95 FAT32
/dev/sdb6       233472 234441647 234208176 111.7G  c W95 FAT32 (LBA)
~~~

Next I gave myself reasonable permissions to it
~~~
# setfacl -m u:ajb:rw /dev/sdb1
# setfacl -m u:ajb:rw /dev/sdb2
# setfacl -m u:ajb:rw /dev/sdb3
# setfacl -m u:ajb:rw /dev/sdb5
# setfacl -m u:ajb:rw /dev/sdb6
and
# setfacl -m u:ajb:r /dev/sdb
~~~

The last one because I think the current code wants to copy the partition code from the MBR of the real disk. Why does it do this, as from what I can see there's no opportunity to use multiple partitions from the same physical disk on the same DOS visible disk? Is there any advantage to copying the real partition table rather than generating one, if not it would be nice not to have to give dosemu read access to the whole disk just to read the partition table.

Then I format each partition as normal user, which proves I have proper access
~~~
$ mkfs.fat -F32 /dev/sdb5
...
~~~

Before I start modifying I'm trying out the current situation, however I'm getting an odd error
~~~
$_force_fs_redirect = (off)                                                     
$_hdimage = "dXXXXs/c:hdtype1 /dev/sdb2 +1"                                     
$_floppy_a = ""                                                                 
~~~
Then startup dosemu/fdpp
~~~
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
D: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MBartition table drive 01h sector 0
E: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD5, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
Error reading partition table drive 01h sector 0Error reading partition table drive 01h sector 0CONFIG.SYS error in line 1
>>>SWITCHES=#0
~~~
in the boot log
~~~
PARTITION auto                                                                  
PARTITION SETUP for /dev/sdb2                                                   
Using MBR from /dev/sdb for PARTITION /dev/sdb2 (part#=2).                      
beg head 32, sec 33, cyl 0 = end head 167, sec 38, cyl 1                        
pre_secs 2048, num_secs 24576 = 6000, -dp->header 0 = 0x0                       
DESTROYING any traces of partition 2                                            
DESTROYING any traces of partition 3                                            
DESTROYING any traces of partition 4                                            
~~~
Which looks okay except that it says it's destroying traces of our partition (I also checked with sdb1 - same result though).

The same thing occurs if I use any of the partitions, including the 5/6 which should get a generated partition table as they are logical partitions.

So what am I missing?

**Comment by stsp** [comment]
> The last one because I think the current code wants to copy the partition code from the MBR of the real disk.

There is a fall-back to not do that.
I also don't see the reason to.
So if you want to remove that code
and always synthesize mbr, then
fine with me.

**Comment by andrewbird** [comment]
I did think of a reason how the real mbr might be useful. It actually may have boot code on there we could use to boot from the partition. I looked at mkfatimage16.c and can see that we actually place some boot code in our generated mbr. I saw that bootnorm.s gets assembled and included into the mbr via an xxd hack, which got me thinking about some enhancement coming in c23, have you seen the new `#embed`  https://thephd.dev/finally-embed-in-c23 feature?
Current work in progress is here https://github.com/andrewbird/dosemu2/commit/c1a4deb9c205932e4a3201258000f3d6933cfa4e but I need to think about what to do in the code section of the mbr, perhaps I should include bootnorm.xxd?

**Comment by stsp** [comment]
Not impressed with embed.
It seems to be a hack that formats your
binary as a sequence of numbers, but
unless you specify the var of type char,
the results would be weird.

Why do you need bootnorm, just call mbr
code via inte6.

**Comment by andrewbird** [comment]
So will that only boot DOS variants that we figured out how to boot on virtual fatfs (dir), or is it more generic?

**Comment by stsp** [comment]
I think its absolutely generic.
DOS-specific boot sector usually
resides in the first sector of the
partition itself IIRC.

**Comment by andrewbird** [comment]
Okay I've switched to using the 0xe6 boot code now for the mbr https://github.com/andrewbird/dosemu2/tree/t25. One thing I do have to extend is the logic for partition type in `build_pi()`.
https://github.com/dosemu2/dosemu2/blob/421b41bdf7c85c193f35d425fb7c0430a16ecd66/src/base/misc/disks.c#L747-L752
Have you an idea on how to deal with FAT32?

**Comment by stsp** [comment]
I don't see if you handle the
new `part_mage` flag that may
indicate that the type was switched
from image to partition.
What is the problem with fat32?

**Comment by andrewbird** [comment]
> I don't see if you handle the
new part_mage flag that may
indicate that the type was switched
from image to partition.

I don't, so I have to rethink about that.

> What is the problem with fat32?

Only that currently fat32 VBR images (assuming they are > 16mb) are given type 0x06 (big fat16) when they should be 0x0b or 0x0c(LBA). Looking at the FDPP kernel ISFAT32 macro it looks like I can infer that it's FAT32 if the bpb->sectors_per_fat is zero.

Thanks.

**Comment by andrewbird** [comment]
I pushed https://github.com/andrewbird/dosemu2/tree/t25 again. Now has fixes for most of the issues you raised, FAT32 partition type support in the partition table, detection of geometry for images with MBR but no Dosemu header, and tightened checking around validity of negative offsets.

**Comment by stsp** [comment]
> detection of geometry for images with MBR but no Dosemu header

But that IMHO is not supposed to be
here. Could you please split it into a
separate patch-set?
