### ISSUE TITLE
overtake HMA

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1782]
fdpp recently stopped using HMA.
There was no reason to use it as
99% of fdpp code runs in a 64bit
space.
So now what can we do with such
a precious resource? The obvious
choice seems to be to optionally
move the private lowmem heap
there. That would add ~17K to the
already rather abundant UMB space
and will definitely make @bolle732 
happy.
And in fact I can't think of anything
else. Yes, moving just 17K to HMA
doesn't sound as a very effective
usage. But I don't think we can
move big things there, like EMS
frame. I don't think we can move
bios pages there, I don't think we
can partition HMA for UMBs, etc.
So if anyone knows how can we
get the good use of HMA, please
speak up. :)

**Comment by ecm-pushbx** [comment]
Does this heap you speak of include DOS data structures such as DPB, CDS, SFT, UPB (block device's unit structure)? Does fdpp have any buffers? All of these can go to the HMA without much problems I believe.

**Comment by stsp** [comment]
Yes, this now includes everything.
Relocating facilities were the major
target for fdpp. Now it occupies
pretty much 0 of the low memory.
All together it occupies ~17K in
the private heap of dosemu2.
Buffers are reduced to just 3
of them.

**Comment by bolle732** [comment]
I don't have any idea what else could be put into the HMA.

I think, it would be nice if FDPP can relocate its private part from UMB to HMA. For a DOS application which can access HMA by itself, you could make a config switch, so the private part fo FDPP stays in the UMB.

**Comment by stsp** [comment]
> I think, it would be nice if FDPP can relocate its private part from UMB to HMA.

This is exactly what was
disabled by default. You can't
easily enlarge the UMBs after
fdpp have relocated itself to HMA,
so that technique didn't help much.
Now HMA is in the hands of dosemu2
completely, but unfortunately it
seems like dosemu2 can only
move 17K there, 15 of which are,
again, fdpp. :)
I wish we could move bigger things,
but I don't see how.

**Comment by stsp** [comment]
Well, fdpp can't be put to HMA as
a blob, because it doesn't work in
tiny model. And when it does, it has
lots of incompatibilities, i.e. progs
just use hard-coded SDA offsets with
DOS_DS for example.

We can still move fdpp private heap
to HMA, which is currently ~8.5K and
also includes the ~2.5K of relocatable
fdpp code (which has previously been
moving to HMA by freedos core).

> All of these can go to the HMA without much problems I believe.

You are right, and I see you have
intentionally omitted SDA and LoL.
Which should stay in UMB together
with the code (init+relocatable), which
will then be stalled. Normally the code
is copied elsewhere and is overwritten
by a heap in its original location, but
with heap initially in HMA, nothing
will be overwritten and re-used.
The code will then be needed that
converts the code space to a
free UMB after initialization is
complete. Code to free is ~4.5K.

So:
1. The current 17K dosemu heap
    can be reduced by 4K.
2. After init is completed, ~4.5K of
    code space can be converted to the free UMB.
3. These ~8.5K then will be occupied in HMA.

Not sure if 8.5K worth a trouble, given
that currently we have no code in fdpp
to create new UMBs on a fly. It will have
to be written...

**Comment by ecm-pushbx** [comment]
> i.e. progs just use hard-coded SDA offsets with DOS_DS for example.
> 
> > All of these can go to the HMA without much problems I believe.
> 
> You are right, and I see you have intentionally omitted SDA and LoL. Which should stay in UMB together with the code (init+relocatable), which will then be stalled.

Yes, SDA, List of Lists, and the DOS stack should stay in the UMA or LMA and cannot go into the HMA without some loss of compatibility. (FreeDOS and MS-DOS always put them into the LMA I believe, DR-DOS can relocate the DOS data segment into the UMA too.)

> Normally the code is copied elsewhere and is overwritten by a heap in its original location, but with heap initially in HMA, nothing will be overwritten and re-used. The code will then be needed that converts the code space to a free UMB after initialization is complete. Code to free is ~4.5K.
> 
> So:
> 
>     1. The current 17K dosemu heap
>        can be reduced by 4K.
> 
>     2. After init is completed, ~4.5K of
>        code space can be converted to the free UMB.
> 
>     3. These ~8.5K then will be occupied in HMA.
> 
> 
> Not sure if 8.5K worth a trouble, given that currently we have no code in fdpp to create new UMBs on a fly. It will have to be written...

It's better if the kernel can add additional UMBs after any device driver has been loaded, anyway. I don't think FreeDOS does allow that. UMBPCI documents a usecase where two different drivers make available UMBs, first UMBPCI and then a memory manager like EMM386.

**Comment by stsp** [comment]
> It's better if the kernel can add additional UMBs after any device driver has been loaded,

In our case the driver doesn't matter
because fdpp starts into UMB initially.
So in that case fdpp should just create
an extra MCB, should be pretty simple.

**Comment by stsp** [comment]
HMA heap now supported.
But getting the use of a freed
space is not yet possible.

**Comment by stsp** [comment]
> Does this heap you speak of include DOS data structures such as DPB, CDS, SFT, UPB (block device's unit > structure)? Does fdpp have any buffers? All of these can go to the HMA without much problems I believe.

**Comment by stsp** [comment]
> Does this heap you speak of include DOS data structures such as DPB, CDS, SFT, UPB (block device's unit 
> structure)? Does fdpp have any buffers? All of these can go to the HMA without much problems I believe.

Tried than now and got +9K
of free UMB space w/o any
extra work. :)
Some extra work (dynamic
head resize + creating a new
UMB) would give ~6K more.

**Comment by stsp** [comment]
> All of these can go to the HMA without much problems I believe.

So the only question I have
now is why freedos doesn't do
that. It took me only 2 lines of
change in fdpp to implement
that suggestion, and it gives
more than my planned heap
move (which is still an ongoing
work). So if freedos can't do
that, my only guess is that
their memory subsystem is
badly architected.

**Comment by stsp** [comment]
Seems to work.
So in total I moved ~13.5K to
HMA and added 3K more to
UMB pool.
@bolle732 you are welcome
to test the new functionality by
setting `$_dos_up = (2)`.

**Comment by stsp** [comment]
Still ~51.5K of HMA space free,
so it might be worth a try to add
the proper HMA functionality to
fdpp in a hope geos to eventually
use HMA on its own.

**Comment by bolle732** [comment]
I'm testing this currently on another notebook at home, as my main device is still running Ubuntu 20.04.

So, I've setup everything with latest DOSEmu2, FDPP but a slightly older COMCOM32 (as I didn't recalled the way to install dgjpp). No hacks in the source from my side.

I set `FILESHIGH=120` in `userhook.sys`.

My `dosemurc` contains an entry for the VESA modes I'm using (`$_X_vesamode = "..."`) and this memory related options:

```
$_ems = (0)
$_xms = (32768)
$_umb_b0 = (on)
#$_dos_up = (on)
```

With that configuration, `mem.exe` is reporting **252K** UMB total und **219K** free.
GEOS heap is at **979'888** bytes.

Now setting the option `$_dos_up = (2)` in `dosemurc`. The `mem.exe` is reporting **267K** UMB total und **238K** free. This is a very nice improvement!

Unfortunately, GEOS heap stays at the same **979'888** bytes.

The `$_dos_up = (2)` does have the desired effect to `mem.exe`, but does not to GEOS heap. So GEOS seems not to recognize some part of UMB.

I could see this lines after the listing of the drives during startup:
```
Unable to hook into himem.sys, UMB disabled.
Make sure himem.sys is loaded right before umb.sys in your config.sys.
```

Does this indicate something or only some noise? 

Regarding GEOS using HMA, I found in my last research a compile time option for the kernal of GEOS, but no code for it. And this option seems always be disabled. Looks like someone had the idea and never implemented it. Or it was used for the GlobalPC which was produced around 1999/2000. They made some optimization with the memory manager so they could activate some basic Javascript support in the browser. But this only worked on that specific hardware.

**Comment by stsp** [comment]
> I'm testing this currently on another notebook at home, as my main device is still running Ubuntu 20.04.

Yeah, thank you.
Perhaps we need to move 20.04
to dosemu-legacy recipe.

> So, I've setup everything with latest DOSEmu2, FDPP but a slightly older COMCOM32 (as I didn't recalled
> the way to install dgjpp).

We realize the problem with djgpp,
therefore there is:
https://dosemu2.github.io/comcom32/files/comcom32.zip
This is the latest pre-built comcom32.
You can use that link whenever you
can't install from LP.

> Does this indicate something or only some noise?

Its now fixed so could you please retry?

> Regarding GEOS using HMA, I found in my last research a compile time option for the kernal of GEOS, but no code

Why geos doesn't use eg EMS?
EMS was specified exactly for those
who don't want to go to prot mode
and yet needs lots of RAM.

**Comment by stsp** [comment]
Hi Andrew, all tests have failed. :(
https://github.com/dosemu2/dosemu2/actions/runs/3261378920/jobs/5363306909
Could you please ignore the
dosemu return value for asan
builds?

**Comment by andrewbird** [comment]
I'll have a look later, but I thought we were already dealing with that asan return value issue somehow?

**Comment by stsp** [comment]
This time it decided to crash on exit.

**Comment by andrewbird** [comment]
Not sure I can do anything about the majority of the failures as those are from libi86 tests. I believe those tests use the dosemu exit value to indicate pass or fail to the autotest runner.
Of the others:
- test_dos.PPDOSGITTestCase.test_cpu_2_jitnative
  test_dos.PPDOSGITTestCase.test_cpu_simnative
  both fail with signal eleven during test rather than exit

- test_dos.PPDOSGITTestCase.test_passing_dos_errorlevel_back
  ignoring the return value wlll make the test invalid

- test_dos.PPDOSGITTestCase.test_passing_environment_variable
  can tweak this to ignore, but without the other tests being done, it seems pointless

**Comment by bolle732** [comment]
PC/GOES crashes after last commit:
```
commit e442a7b096a7263dd47e1c84f79bd80b050ae6b4 (HEAD -> devel, origin/devel, origin/HEAD)
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Mon Oct 17 13:56:53 2022 +0500

    xms: drop external HMA hook [#1782]
    
    ... after successful HMA allocation.
```

Error message is:
```
ERROR: SIGILL while in vm86(): 64be:00e4
ERROR: general protection at 0x7f6f6e539fc7: af
```

Addresses changes from run to run.

Going back to `f020186fa1d2f3cb640173c5f117a9ff8efae15c` works fine...

**Comment by stsp** [comment]
Thanks, could you please retry?

**Comment by bolle732** [comment]
Yes, that fixed it! Thanks a lot!

**Comment by stsp** [comment]
Andrew so how to manually
start full ci other than by using
the appropriate tag in commit
msg? (which is what I haven't
done).
It seems when I restart particular
run, it uses the same commit
as before.

**Comment by andrewbird** [comment]
> Andrew so how to manually
start full ci other than by using
the appropriate tag in commit
msg?

There's nothing to do that at present, but I have an idea I might try to implement.

> It seems when I restart particular
run, it uses the same commit
as before.

Yes that's normal behaviour.

**Comment by bolle732** [comment]
Regarding EMS vs XMS:

Yes, PC/GEOS can use both, even at the same time. A max of 16MB for each. Together with disk swap, there is 48MB swap space at maximum. From the help file, it even could use "extended" memory above 1MB, if XMS is not used. But I never had one of this hardware RAM cards.

A quick test using EMS showed a reduction of the available heap by ~16k. And each swap driver (EMS, XMS, disk) needs a good amount in the heap for the mapping table. Depending the programs used, it could be more beneficial to give up one of the swap drivers if those programs used a lot of fixed RAM (aka non swappable). So, heap exhaustion vs maximum available virtual memory.

My experience from the past was, that it was more stable without EMS as this gave more heap space. But under DOSEmu2, where plenty conventional RAM and UMB is available, that could be different. Sure, EMS is lighter without switching to protected mode. But the speed difference to XMS is not that visible.

**Comment by stsp** [comment]
> use "extended" memory above 1MB, if XMS is not used. But I never had one of this hardware RAM cards.

Its not a hardware ram card,
its int15. You can load only
umb.sys (w/o ems.sys) and
then int15 can be used.

So have you got more UMBs
now with dos_up=2?

**Comment by andrewbird** [comment]
@stsp, I just raised a PR with a manual test trigger action in it for you.

**Comment by bolle732** [comment]
> Its not a hardware ram card, its int15. You can load only umb.sys (w/o ems.sys) and then int15 can be used.

Ok, seems I confused it.  But could be another interesting experiment.

> So have you got more UMBs now with dos_up=2?

Unfortunately no. Setting `$_dos_up` to `(on)` or `(2)` doesn't make any difference regarding the amount of GEOS heap. DOS `mem.exe` does see a difference in UMB (252K vs 267K).

**Comment by stsp** [comment]
>  both fail with signal eleven during test rather than exit

And for these cases I don't
see the crash info in the log.
Can you reproduce that locally?

**Comment by stsp** [comment]
> mem.exe does see a difference in UMB (252K vs 267K).

Yes but it also sees it in a
very strange way.
I disabled some new code
in fdpp and `mem` now shows
correct results.
Could you please see if
something changed?

**Comment by bolle732** [comment]
With latest FDPP changes (disable UMB hole  punching), GEOS heap is still the same, DOS `mem.exe` shows 255K total UMB.

**Comment by stsp** [comment]
Before that last change, mem indeed
showed more total umbs than now, but
also much more used umbs, which was
completely unexpected. Now both total
and used - lowered to normal.

But why geos doesn't react at all to so
many different changes is something
for you to debug. As for me it looks more
like some heap limit was reached.

**Comment by andrewbird** [comment]
> >  both fail with signal eleven during test rather than exit

> And for these cases I don't
see the crash info in the log.
Can you reproduce that locally?

No, I built with asan on, then did
~~~
ajb@polly:/clients/common/dosemu2.git$ test/test_dos.py --require-attr=cputest PPDOSGITTestCase
Test PP-DOS-GIT  CPU test: native vm86 + native DPMI (i386 only)                 ... skipped "x86_64 doesn't support native vm86()"
Test PP-DOS-GIT  CPU test: JIT vm86 + native DPMI                                ... ok ( 17.95s)
Test PP-DOS-GIT  CPU test: JIT vm86 + JIT DPMI                                   ... ok ( 17.24s)
Test PP-DOS-GIT  CPU test: JIT vm86 + KVM DPMI                                   ... ok ( 16.14s)
Test PP-DOS-GIT  CPU test: KVM vm86 + KVM DPMI                                   ... ok ( 16.55s)
Test PP-DOS-GIT  CPU test: KVM vm86 + JIT DPMI                                   ... ok ( 15.98s)
Test PP-DOS-GIT  CPU test: KVM vm86 + native DPMI                                ... ok ( 15.35s)
Test PP-DOS-GIT  CPU test: KVM vm86 + simulated DPMI                             ... ok ( 29.02s)
Test PP-DOS-GIT  CPU test: simulated vm86 + simulated DPMI                       ... ok ( 25.33s)
Test PP-DOS-GIT  CPU test: simulated vm86 + KVM DPMI                             ... ok ( 17.23s)
Test PP-DOS-GIT  CPU test: simulated vm86 + native DPMI                          ... ok ( 15.86s)
Test PP-DOS-GIT  CPU Trap Flag emulated                                          ... ok (  5.49s)
Test PP-DOS-GIT  CPU Trap Flag KVM                                               ... ok (  5.73s)

----------------------------------------------------------------------
Ran 13 tests in 198.091s

OK (skipped=1)

ajb@polly:/clients/common/dosemu2.git$ sudo mv /dev/kvm{,.off}
[sudo] password for ajb: 
ajb@polly:/clients/common/dosemu2.git$ test/test_dos.py --require-attr=cputest PPDOSGITTestCase
Test PP-DOS-GIT  CPU test: native vm86 + native DPMI (i386 only)                 ... skipped "x86_64 doesn't support native vm86()"
Test PP-DOS-GIT  CPU test: JIT vm86 + native DPMI                                ... ok ( 15.26s)
Test PP-DOS-GIT  CPU test: JIT vm86 + JIT DPMI                                   ... ok ( 17.48s)
Test PP-DOS-GIT  CPU test: JIT vm86 + KVM DPMI                                   ... skipped 'No KVM available'
Test PP-DOS-GIT  CPU test: KVM vm86 + KVM DPMI                                   ... skipped 'No KVM available'
Test PP-DOS-GIT  CPU test: KVM vm86 + JIT DPMI                                   ... skipped 'No KVM available'
Test PP-DOS-GIT  CPU test: KVM vm86 + native DPMI                                ... skipped 'No KVM available'
Test PP-DOS-GIT  CPU test: KVM vm86 + simulated DPMI                             ... skipped 'No KVM available'
Test PP-DOS-GIT  CPU test: simulated vm86 + simulated DPMI                       ... ok ( 24.72s)
Test PP-DOS-GIT  CPU test: simulated vm86 + KVM DPMI                             ... skipped 'No KVM available'
Test PP-DOS-GIT  CPU test: simulated vm86 + native DPMI                          ... ok ( 16.80s)
Test PP-DOS-GIT  CPU Trap Flag emulated                                          ... ok (  7.25s)
Test PP-DOS-GIT  CPU Trap Flag KVM                                               ... skipped 'No KVM available'

----------------------------------------------------------------------
Ran 13 tests in 81.610s

OK (skipped=8)
~~~

All seems fine here, I'm afraid. Perhaps you fixed it in the meantime?

**Comment by stsp** [comment]
No, didn't.
And therefore I propose to disable
asan CI builds. Asan will not be fixed:
https://gcc.gnu.org/bugzilla//show_bug.cgi?id=101476

It would be interesting to see these
crashes "not on exit" but if they don't
happen locally then we can't.

**Comment by stsp** [comment]
Even @amluto ignored the kernel
part of the problem. :(
@amluto why not to review this small patch?
https://lore.kernel.org/lkml/20220126191441.3380389-1-stsp2@yandex.ru/

**Comment by bolle732** [comment]
> But why geos doesn't react at all to so
> many different changes is something
> for you to debug. As for me it looks more
> like some heap limit was reached.

As far I can imagine from the source code, GEOS could maybe only use the biggest free UMB space. And it seems to allocate whole 1KB blocks. Still investigating in my spare free time.

But at the end, you did a really great job with the memory management which is huge contribute to the GEOS folk too! I'm trying to write up a document with all information about running PC/GEOS under DOSEmu2. This will need some time, but that should go hopefully to the wiki of DOSEmu2. I'm using Obsidian for this and hopefully wont use a lot of special flowered markdown code.

**Comment by andrewbird** [comment]
I was thinking about tidying up this patch to display the HMA in dosdebug;s mcbs command
```diff
+  // Now see if HMA is in Win95 mcb format
+  for (i = 0x0000, hdr = 1; i < 0xfff0; /* */) {
+    struct HMCB *hmcb, *htmp;
+
+    hmcb = MK_FP32(0xffff, i);
+    if (hmcb->signature[0] == 'M' && hmcb->signature[1] == 'S' && hmcb->next < 0xfff0) {
+      htmp = MK_FP32(0xffff, hmcb->next);
+      if (htmp->signature[0] == 'M' && htmp->signature[1] == 'S') {
+        // seeming valid hmcb
+        if (hdr) {
+          mhp_printf("\nADDR(HMA) PARAS  OWNER\n");
+          hdr = 0;
+        }
+        mhp_printf("ffff:%04x 0x%04x [%s]\n", i, hmcb->size / 16, hma_id_to_name(hmcb->owner));
+      } else if (hmcb->next == 0) {
+        mhp_printf("ffff:%04x (END)\n", i);
+        break;
+      }
+    }
+    i += 0x10;
+  }
 }
```
It's been a while since I tried it, and as I remember I tested it on Win95, but it doesn't seem to display anything with FDPP. Doesn't it use the Win95 HMA block format?

**Comment by stsp** [comment]
There is an issue about that:
https://github.com/dosemu2/fdpp/issues/183
Someone should just implement.

**Comment by andrewbird** [comment]
Oh so I just misremembered that FDPP already did it. Sorry about the noise!

**Comment by stsp** [comment]
No, I never said that HMA is officially
supported by fdpp. What is supported,
is very specific: we support moving some
dos parts to HMA. But the generic hma
support is todo. And unfortunately even
geos doesnt use it so that todo is low-prio.
Its upsetting that such a core concepts in
freedos are so rudimentary that we need
to write the new code every now and then.
