### ISSUE TITLE
Bad or missing Command Interpreter: command.com

### ISSUE THREAD

**Issue by fuck-shithub** [dosemu2/dosemu2#1783]
**Describe the bug**
Upon launching dosemu I get
```
Bad or missing Command Interpreter: command.com /e:384 /p /k %FDPP_AUTOEXEC%
Enter the full shell command line:
```

**To Reproduce**
Steps to reproduce the behaviour:
Literally just launch dosemu. Idk what I'm doing wrong. There's barely any documentation and I followed the installation instructions. Btw I use Gentoo.

**Attach the log**
FDPP kernel 1.6 [GIT: 1.6-27-g58a3acf] (compiled Sep 12 2022)
fdpp: plugin loaded: 1
ERROR: Neither freecom nor comcom32 installation found.
Use DOSEMU2_EXTRAS_DIR env var to specify location of freedos
or DOSEMU2_COMCOM_DIR env var for alternative location of comcom32
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: config variable c_user set
CONF: Parsing /home/user/.dosemu/.dosemurc file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Disabling use of pentium timer
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x20000)
CONF: DPMI linear reserve base addr = 0xffffffff
CONF: DPMI linear reserve size = 0x8000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
default_drives 0
Setting up drive C, ~/.dosemu/drive_c
Creating default drive C
Added drive 0 (80): ~/.dosemu/drive_c
default_drives 1
Added drive 1 (81): /usr/local/share/dosemu/dosemu2-cmds-0.3
Setting up default drives from E
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 enabled.
CONF: config variable c_system unset
Command line: /usr/local/bin/dosemu.bin -o /home/user/.dosemu/boot.log
Warning: Linux kernel 5.18.19; CPU speed is 4000000000 Hz
Warning: CPU-EMU speed is 4000 MHz
CONF: V86 cpu vm set to -1
CONF: DPMI cpu vm set to -1
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
Warning: dosemu2-2.0pre9-dev-20220910-400-g637186d43 is coming up on Linux version 5.18.19-gentoo-r1 #1 SMP PREEMPT_DYNAMIC Sat Aug 27 21:04:44 CEST 2022 x86_64
Warning: Compiled with gcc version 11.3.0Warning:  64bit
Warning: CFLAGS: -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wno-address-of-packed-member -fpie -O2
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 17Kb at 0xF9C00 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0246
initial segment bases: fs: 0x7fd05cd180c0  gs: (nil)
ERROR: KVM: error opening /dev/kvm: Permission denied
Warning: KVM not available: Permission denied
Warning: using CPU emulation for vm86()
Warning: using CPU emulation for DPMI
VID: initializing SDL plugin
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Conventional memory mapped from 0x7fd058802000 to 0x40be8000
DPMI memory mapped to 0x40cf8000 (reserve) and to 0x42cf8000 (main)
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
loading fonts for cp437
VID: initializing video sdl
VID: SDL plugin initialization completed
Registering HWRAM, type=e base=0x400e7000 size=0x400000
CONF: reserving 4096Kb at 0x400E7000 for 'e' (VGAEMU LFB)
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
Cannot lock down 107341340 byte memory area (Cannot allocate memory)
Cannot lock down 107341340 byte memory area (Cannot allocate memory)
Warning: fluidsynth sound font unavailable at /usr/share/soundfonts/default.sf2
ERROR: MUNT: Can't find /home/user/.dosemu/roms/MT32_CONTROL.ROM
ERROR: userspace pings are disabled.
	To enable them, do as root:
	echo 0 65535 > /proc/sys/net/ipv4/ping_group_range
DPMI: mem init, mpool is 140468224 bytes at 0x42cf8000
Warning: Using DPMI with CPU emulator
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============

CONF: freeing region for 'E' (EMS page frame)
config.boot_dos set to 400000
config.int_hooks set to 0
config.force_revect set to 0
CONF: reserving 116Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 39Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
leavedos(SDL_handle_events:1445|0) called - shutting down
2 threads still active
leavedos thread started
leavedos thread ended
	tid=278 state=3 name=fdpp thr off=0
coopthreads stopped
======================= LEAVE CPU-EMU ===============

Package info:
Package info:

**A regression?**
dosemu1's Gentoo ebuild segfaults, lol.

**Additional info**
I changed nothing. Just followed install instructions. You tell me what I'm doing wrong :shrug:

**Comment by andrewbird** [comment]
> ERROR: Neither freecom nor comcom32 installation found.

Do you have comcom32 installed? It should be found here `/usr/share/comcom32/command.com` if so. BTW which install instructions have you been following?

**Comment by fuck-shithub** [comment]
I was reading the install instruction form the INSTALL file. Looks like I missed the command.com part. After downloading that and symlinking it works now.

**Comment by andrewbird** [comment]
Cool, I'm glad you are sorted!
