### ISSUE TITLE
Dragonsphere causes DOSEMU to suddenly quit with Jack error

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1786]
**Describe the bug**
Clicking start causes DOSEMU2 to terminate.

**To Reproduce**
Start the game.
Proceed through the first screens.
Click start.

**Attach program/game binaries or provide an URL**
[dragonsp.tar.gz](https://github.com/dosemu2/dosemu2/files/9592505/dragonsp.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9592506/boot.log)

**A regression?**
Seems possibly related to Jack? I don't think I use Jack for anything usually?

**Comment by stsp** [comment]
I think your alsa midi is
configured to jack. It seems
you don't have fluidsynth
soundfonts installed, and
so dosemu2 probably falls
back to alsa. And your alsa
might be misconfigured as
there are lots of errors from
it in the log.

**Comment by jschwartzenberg** [comment]
It seems the packages in Parabola/Arch somehow end up installing Jack. I can't find any configuration related to this, but I'm afraid this distro is kind of broken. Thanks for pointing it out!
