### ISSUE TITLE
Shadow Caster: ERROR: PM stack invalid, in_dpmi_pm_stack=1

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#1803]
**Describe the bug**
Shadow Caster crashes DOSEMU2 at some point with `ERROR: PM stack invalid, in_dpmi_pm_stack=1`.

**To Reproduce**
Run the game, try to get further. I had to push enter at some point to get a crash.
It crashes as well with `$_cpu_vm_dpmi="native"` but it seems somewhat differently.

**Attach program/game binaries or provide an URL**
[shadow.tar.gz](https://github.com/dosemu2/dosemu2/files/9740154/shadow.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/9740156/boot.log) (`$_cpu_vm_dpmi="native"`)
[boot.log.1.log](https://github.com/dosemu2/dosemu2/files/9740163/boot.log.1.log)

**A regression?**
unknown

**Comment by stsp** [comment]
Should now be fixed.
