### ISSUE TITLE
Int21/7303 maximum return values?

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1820]
I'm running dosemu on a new laptop that has a filesystem with 460GB free space. I see the maximum freespace values returned (by freecom) is around 260GB. I tried to read the last long thread #544 on the subject to determine why it was clamped at this level, but I don't see the reason. I tried this patch which unsurprisingly reported the correct values, what would it break and surely Win95 could report the full size of a FAT32 volume?

```diff
diff --git a/src/dosext/mfs/mfs.c b/src/dosext/mfs/mfs.c
index d4876842f..011c2cf58 100644
--- a/src/dosext/mfs/mfs.c
+++ b/src/dosext/mfs/mfs.c
@@ -1455,10 +1455,10 @@ static int dos_get_disk_space(const char *cwd, unsigned int *free, unsigned int
     *spc = _spc;
     *total = _total;
     *free = _free;
-    return (1);
+    return 1;
   }
   else
-    return (0);
+    return 0;
 }
 
 /*
@@ -4256,7 +4256,7 @@ static int dos_fs_redirect(struct vm86_regs *state, char *stk)
         if (dos_get_disk_space(drives[dd].root, &free, &tot, &spc, &bps)) {
           u_short *userStack = (u_short *)sda_user_stack(sda);
           if (userStack[0] == 0x7303) { /* called from FAT32 function */
-            while (tot > 65535 && spc < 128) {
+            while (tot > 65535 && spc < 512) {
               spc *= 2;
               free /= 2;
               tot /= 2;
```

Here's what RBIL has to say https://fd.lod.bz/rbil/interrup/dos_kernel/217303.html#sect-3268

**Comment by stsp** [comment]
What value exceeds dword w/o that change?
I think it would be better to change 65535
here to something else, as it seems wrong
check for dword.

**Comment by andrewbird** [comment]
> What value exceeds dword w/o that change?

It doesn't but the code following it clamps `tot` and `free` to 65535.

From reading a thread of yours from 2014, it is suggested by bart that the code is trying to avoid overflow in the caller, hence limiting the values even though they are 32 bits each so that they may be multiplied. See  https://sourceforge.net/p/dosemu/feature-requests/75/

I did a slightly revised patch here https://github.com/andrewbird/dosemu2/commit/4f1fe609b1b89e07be07cd1c9fbadb35471a5a15 where the 2GB limit is observed for int21/36 but with int21/7303 it's much higher (maybe it doesn't need to be limited at all?)

**Comment by stsp** [comment]
Bart only meant that for 36 I believe.
And instead we see that loop for 7303?
Something looks very wrong.
For 7303 there should be no clamping,
and therefore probably no loop.

**Comment by stsp** [comment]
I think whoever implemented this 7303
was mistakenly assuming the values are
still word. git blame should say who was
that.

**Comment by stsp** [comment]
OK the problem is not in 7303 or alike,
but instead in
http://www.ctyme.com/intr/rb-4317.htm
I made it now explicit that `spc` is byte.
This makes your proposed change
obviously wrong.

**Comment by andrewbird** [comment]
> Bart only meant that for 36 I believe.

Yes, he also mentions that 7303 would need to be implemented in dosemu to report it properly, so clearly was talking about 36.

> I think whoever implemented this 7303
was mistakenly assuming the values are
still word.

Yes but the trouble is that there are two ways 7303 can be satisfied:
- If the DOS doesn't implement 7303, then our failback is used `mfs_fat32` and the values are passed as dword
  https://fd.lod.bz/rbil/interrup/dos_kernel/217303.html#sect-3268
- FDPP calls it via the redirector interface which is mostly word based(I just saw your last post)
  https://fd.lod.bz/rbil/interrup/network/2f110c.html#4315
  In this case the spc and bps will need to be adjusted to get the total value under 0xffff.
  In light of your info about spc being byte based, this calls into question whether using this existing redirector interface is the right thing to do?

**Comment by stsp** [comment]
For fdpp - no.
Lets introduce 1183 extension and
do the right thing.

**Comment by stsp** [comment]
For doses that implement 7303, we
do our best by increasing spc and bps.
For those that don't, we have mfs_fat32().
And for fdpp we can have 1183 extension.
I believe all cases are then covered.

**Comment by andrewbird** [comment]
I notice that in FDPP 7303 treats spc value returned from redirector as word, not byte. 
```c
  if (cdsp->cdsFlags & CDSNETWDRV)
  {
    if (remote_getfree(cdsp, MK_FAR_SCP(rg)) != SUCCESS)
      return DE_INVLDDRV;


    xfsp->xfs_clussize = rg[0];
    xfsp->xfs_totalclusters = rg[1];
    xfsp->xfs_secsize = rg[2];
    xfsp->xfs_freeclusters = rg[3];
```

**Comment by stsp** [comment]
Maybe freedos was trying that as
an extension. But it doesn't work
because we never allowed spc
above or equal to 128.

**Comment by andrewbird** [comment]
Anyway I like your idea of implementing redirector function 1183, it seems better than shoehorning. BTW we'll need to start using 7303 in comcom32 as well.

**Comment by andrewbird** [comment]
Did you start work on implementing redirector function 1183, or shall I have a go?

**Comment by stsp** [comment]
No, I didn't do anything.
I even already forgot what should it do. :)
So please do!
Thanks. :)

**Comment by andrewbird** [comment]
So really to implement a new [int2f/110c](http://www.ctyme.com/intr/rb-4317.htm) that can pass larger values. There doesn't seem to be any spare registers to pass the extra info, so should I widen to use 386 registers, or pass a pointer to a struct and if so should it be caller or callee provided?

**Comment by stsp** [comment]
Since I completely forgot everything,
let me start from silly questions.
Do you really want to return the crap
like "bytes per sector", "total clusters"
and so on? Maybe you can just return
the drive size and free space, and
allow 7303 to translate that to the
silly stuff?
Then no problems about registers.

**Comment by andrewbird** [comment]
> Maybe you can just return
the drive size and free space, and
allow 7303 to translate that to the
silly stuff?

I think then I'd be guessing about individual components, with no ability to report them correctly should they actually be significant.

Since [int21/7303](http://www.ctyme.com/intr/rb-3227.htm) passes a pointer to the caller's buffer, is there any reason I shouldn't pass that pointer through to our new redirector function and have that populate it?

**Comment by stsp** [comment]
These values are purely fake.
You can just return 2 values as
a number of LBA blocks, and
then down-scale them in a loop,
increasing some other value.
We already have such code.

Of course you can pass in a table,
but since you are developing an
extension and is not bound to any
compatibility, I am sure you would
regret introducing the mess instead
of a clean and small extension.

Also. What you propose is essentially
the same thing. You will do the host
call like statvfs() that returns exactly
the values I am talking about. And you
pass a silly table, which you need to
fill from these values. Same thing!
I just propose to do it not in mfs.c.
How would that make your work any
harder?

**Comment by andrewbird** [comment]
> Also. What you propose is essentially
the same thing. 

Agreed.

> I just propose to do it not in mfs.c.

So it ends up in two places, FDPP and mfs.c:mfs_fat32()

**Comment by stsp** [comment]
Right, but I think minimizing the
extensions scope and making them
more generic, is more important
than some duplication.

Also note that 7303 operates with
things like "clusters", "allocation units"
and so on. They have zero sense
for the redirector, whereas DOS may
have some knowledge of what does
this mean. Redirector only knows the
size, free space and an LBA block size.

**Comment by andrewbird** [comment]
> Right, but I think minimizing the
extensions scope and making them
more generic, is more important
than some duplication.

okay.

> Redirector only knows the
size, free space and an LBA block size.

So I should return:
  total size in blocks (AX:BX)
  free space in blocks (CX:DX)
  block size  (SI)

Which gives maximum size of 2TB @ 512 byte block, or do you think it should be larger somehow?

**Comment by stsp** [comment]
I wouldn't even return the block
size, and maybe spare AX for
some err code, unless there is
already an established practice
among neighboring functions to
use AX for partial values?

As for should it be larger - please
remind me the maximum of the
7303 table? I think it can't leverage
2TB anyway, or can it?

**Comment by stsp** [comment]
Well, it also just uses "number of
sectors" as a DWORD, so 2Tb should
be the good match.

**Comment by andrewbird** [comment]
I was using the blocksize to scale the free & avail. Without it I can only pass 4GB as bytes.

**Comment by andrewbird** [comment]
Unless we document the values as returned in xx byte blocks.

**Comment by andrewbird** [comment]
So about the input. The original int2f/110c function receives a CDS pointer which naturally limits the function's callers to those that  can supply one i.e. DOS kernel, so for example calling it from mfs_fat32() is not possible. But we don't really need this, a drive letter is enough to find the host path. Are you happy that it takes a pointer to a string (like Qualify Filename)?

**Comment by stsp** [comment]
> Unless we document the values as returned in xx byte blocks.

In 512b blocks.

I think CDS is needed for 0xc to use cds_dpb
for getting some geometry values. If we only
return sizes then indeed I suppose CDS is not
needed. Still I am not sure you need or should
call it from mfs_fat32().

**Comment by andrewbird** [comment]
> Still I am not sure you need or should
call it from mfs_fat32().

Then I'll revert to passing a CDS pointer, there's no other reason.

**Comment by andrewbird** [comment]
This is done now (also on FreeDOS)
