### ISSUE TITLE
Native DPMI fails again: Your kernel does not support UC_STRICT_RESTORE_SS and the work-around in dosemu is not enabled.

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1825]
**Describe the bug**

Running a simple DPMI test with dosemu `-I "cpu_vm_dpmi native"` fails on our Debian 11 amd64 server since https://github.com/dosemu2/dosemu2/commit/de40f54be505aff88d12e308065f1d7dbf2a28d5

It displays the error message:

> Your kernel does not support UC_STRICT_RESTORE_SS and the work-around in dosemu is not enabled.

**To Reproduce**

Run `dosemu -I "cpu_vm_dpmi native" -K "$PWD" -E "ldebugx.com /c='?build;r dco or= 800;g;g;q' dpmimini.com" -dumb -td -kt`

The message "Welcome in 32-bit protected mode." will not display for revisions de40 and more recent. The test program will run fine for the parent of de40, https://github.com/dosemu2/dosemu2/commit/a767186ce23eecf450552472909fdef0a5b33615

**Attach program/game binaries or provide an URL**

https://pushbx.org/ecm/test/20221127/

**Attach the log**

https://pushbx.org/ecm/test/20221127/1111.log failure, https://pushbx.org/ecm/test/20221127/1108.log success

https://pushbx.org/ecm/test/20221127/1126.log failure with `-D+9M`, https://pushbx.org/ecm/test/20221127/1125.log success with `-D+9M`

**A regression?**

a767 works fine.

**Additional info**

FreeDOS kernel and FreeCOM used.

**Comment by ecm-pushbx** [comment]
I need to use native DPMI because the server does not offer KVM to our OS and I want to run tests which check that segment limits are respected. dosemu2 without KVM and without native DPMI does not respect limits. Example is in https://hg.pushbx.org/ecm/ldebug/rev/0ee74639badc

**Comment by stsp** [comment]
Is this with PPA build?

**Comment by stsp** [comment]
I think this can only happen with
`./default-configure -d` i.e. non-PPA
build. In that case try
`./default-configure -d --enable-system-wa`

**Comment by ecm-pushbx** [comment]
> I think this can only happen with `./default-configure -d` i.e. non-PPA build.

Yes, I'm building it myself from git. And I do include the `-d` switch to `default-configure`.

> In that case try `./default-configure -d --enable-system-wa`

It works with that. Does that mean we should close this issue?

**Comment by stsp** [comment]
I enabled debug info by default.
Hope that removes any necessity
to use -d for you.

**Comment by ecm-pushbx** [comment]
Thanks! Dropping both `-d --enable-system-wa` makes it work with your most recent revision.

**Comment by stsp** [comment]
Except that tests fail...
Will take a look.

**Comment by stsp** [comment]
> Thanks! Dropping both -d --enable-system-wa makes it work with your most recent revision.

That was also before, just w/o debug info.
But we need debug info for bug-reporting,
so let it always be there.

**Comment by stsp** [comment]
Hopefully fixed the tests and int24
breakage too. But not sure as fdpp
currently doesn't run dosemu tests...

**Comment by andrewbird** [comment]
But you know you can just do a manual trigger on dosemu's GitHub actions tab?

**Comment by stsp** [comment]
Seems to work, thanks.
