### ISSUE TITLE
Dosemu2 (SDL2) crashes going into fullscreen

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1827]
**Describe the bug**
Dosemu2 SDL2 (dosemu -S) will crash when switching to full-screen with the Ctl-Alt-F key combination.

**To Reproduce**
Start Dosemu2 compiled with SDL2 with or without the -S switch, then press Ctl-Alt-F to bring Dosemu2 to full-screen.  Dosemu2 crashes.

**Attach program/game binaries or provide an URL**
It happens independent of any specific program running.  Using this key combination at a DOS prompt is sufficient to trigger the crash.

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/10145469/boot.log.zip)

**A regression?**
Yes, but I don't know when this problem originally occurred.

**Additional info**
Starting Dosemu2 with -X allows this key combination to bring Dosemu2 to full-screen without the crash.

SDL2 version is 2.0.22.  Dosemu2 is current as of 2-Dec-2022.

```
SDL_update
SDL: entering fullscreen mode
SDL: keyboard grab activated
SDL: mouse grab activated
PIC: Requested irq lvl f
PIC: Cascade irq 2 set to 1
PIC: int out set to 1
PIC1: isr=0 imr=0 irr=80
SDL: SDL_change_config: item = 1, buffer = (nil)
change_config: item = 1, buffer = (nil)
SDL: SDL_change_config: item = 1, buffer = 0x966ffa50
SDL: SDL_change_config: win_name = COMMAND ( rem ) - MICRON [keyboard+mouse grab] 
processing async callbacks
SDL_update
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x400
  Serial number of failed request:  604
  Current serial number in output stream:  605


```

**Comment by stsp** [comment]
May be related to this:
https://github.com/libsdl-org/SDL/issues/3871
in which case you need 2.0.24.
But I am not sure as dosemu has a
work-around which worked for me well.
Does this happen with a particular DOS
resolution?
Can you try the latest sdl with the needed
fixes in?

**Comment by jharrison03** [comment]
Working now with latest SDL.  Didn't realize how out of date my version was.

**Comment by stsp** [comment]
Thanks for update.
Not sure why my work-around
didn't work for you, but lets not
bother about outdated software.
