### ISSUE TITLE
Regression, cannot start Win 3.11 anymore

### ISSUE THREAD

**Issue by robert-j** [dosemu2/dosemu2#1831]
**Describe the bug**

Attempting to start Win 3.11 is crashing dosemu 2 right after or during displaying the logo with: 

    ERROR: get_dos_mem failed
    ERROR: OUCH! attempt to execute interrupt table - quickly dying
    ERROR: SIGILL while in vm86(): 0001:001b

**To Reproduce**
Start Windows.

**Attach the log**

- [small-boot.log](https://github.com/dosemu2/dosemu2/files/10197700/small-boot.log)
- [large-boot.log.gz](https://github.com/dosemu2/dosemu2/files/10197717/large-boot.log.gz)

The latter is actually a bz2-file.

**A regression?**

Yes, it didn't happen the last time I tried (about 4-5 days ago).

**Comment by stsp** [comment]
Thanks.
I replicated the old logic now, could you
please retry?

**Comment by stsp** [comment]
libi86 tests failed, but according to
the log, its something with gold...
Andrew, do you happen to know
what gold is doing here?

**Comment by andrewbird** [comment]
Probably best to give tkchia a prod, there seems to have just been some big binutils merge https://github.com/tkchia/binutils-ia16/issues/10

**Comment by andrewbird** [comment]
tkchia has now provided a fix, so if you rerun the tests they should be okay.
