### ISSUE TITLE
instremu and fp87-sim have inline asm

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1833]
instremu.c contains OPandFLAGxx macros
with inline asm, that are not under ifdef of
HOST_ARCH_X86.
@bartoldeman how difficult would it be to
provide a replacement? Do you have any
hints about where should I look for those?
Can something be taken from simx86?

**Comment by bartoldeman** [comment]
I think you can simply not compile the whole instremu.c if not HOST_ARCH_X86. Unless things have changed it's only used for kvm and native.

**Comment by stsp** [comment]
But don't we have those
instremu-only vga modes?

**Comment by stsp** [comment]
Ah I guess even for instremu-only
modes its unused when simx86 is
used. Interesting, looking...
Thanks!

**Comment by bartoldeman** [comment]
yes, for the JIT, the cpatch code takes care of it, and for the simulator, all memory accesses go via `do_read_byte` and friends.
https://github.com/dosemu2/dosemu2/blob/d5197a56d74ae00f73b59b4f36b0da5c05dacccc/src/base/misc/dos2linux.c#L627

**Comment by stsp** [comment]
Sigh, msdos/instr_dec.c calls
instr_binary_xxx() and that gets
to those flags...

**Comment by stsp** [comment]
Made a private copy of instr_len()
in case instremu is not compiled in,
but still no idea about instr_binary_xxx() :(

**Comment by stsp** [comment]
Hmm, actually decode_memop()
is only needed for ldt writes, on which
simx86 probably doesn't fault.
decode_segreg() and decode_selector()
do not go into instremu.
So perhaps some ifdeffery will help.

**Comment by bartoldeman** [comment]
yes it looks you're right. LDT writes go like this:
```
do_write_byte() in dos2linux.c
emu_pagefault_handler() in protmode.c
emu_ldt_write() also in protmode.c
msdos_ldt_write() in msdos_ldt.c
direct_ldt_write() also in msdos_ldt.c
memcpy()
```
so the instruction decoding happened at a higher level and is no longer necessary.

**Comment by stsp** [comment]
Why those OPandFLAGs do not
pre-set flags? They do an op and
then pushf/pop (why not lahf?), but
the flags before op are unknown?
Is this accurate?

**Comment by bartoldeman** [comment]
They do not need to because the relevant flags are only written, not read (sbb/adc need to read carry but use OPandFLAGC).

lahf could be quicker but doesnt exist on some early AMD and doesn't set OF, so you'd need to combine it with `seto`

**Comment by stsp** [comment]
Thanks, so I'll ifdef instremu out.
I am quite disappointed that the
instruction decoding lib appeared
to be incomplete, so if you have an
idea how to add the missing (on
non-x86 host) functionality, please tell. :)
But so far I'll add ifdefs as obviously
this is the only thing I can do quickly.

**Comment by stsp** [comment]
Omg, fp87-sim.c is full of asm. :(

**Comment by bartoldeman** [comment]
yes, some lazy coding there... (from a looong time ago).
I suppose one can switch off FPU support for non-x86 for now (e.g. emulate 486SX without coprocessor), it'll be slow but at least it should boot and run things.

**Comment by stsp** [comment]
Yeah, I seriously underestimated the
porting efforts... In contrast, fdpp was
ported to arm in 10 minutes - with whole
freedos!
dosemu1 devs definitely deserve the
punishment. :) I guess we eventually
need to replace simx86 with tcg.

**Comment by stsp** [comment]
So there are only 2 offenders now:
instremu and fp87-sim. The rest compiles
fine.
I appreciate any hints about solving that.

**Comment by bartoldeman** [comment]
Really instremu is unused in a sim setting (or did I miss something?).
I've got a first patch for fp87-sim, checking for correctness (with the cpu tester).

**Comment by stsp** [comment]
> Really instremu is unused in a sim setting (or did I miss something?).

The problem is that I am getting
reduced instr_dec lib, which I compile
also outside of dosemu code. It of
course never worked there for many
other reasons, but I am still updating
that code and is using it for DPMI testing
(see pmdapi repo on my page).
And I really intended to eventually get
it to work, because recently the conversion
of msdos.c to dpmi-1.0, which took 15
years, was finally completed.
How difficult does it look to fix also that?

**Comment by stsp** [comment]
> How difficult does it look to fix also that?

Not necessarily instremu - maybe something
simple can be hacked up specially for instr_dec?

**Comment by bartoldeman** [comment]
I can have a look for instr_dec, the flag manipulation in codegen-sim.c is all in C and can be ported with a little effort.

**Comment by stsp** [comment]
That would be really cool, thanks!

**Comment by stsp** [comment]
> I can have a look for instr_dec, the flag manipulation in codegen-sim.c is all in C and can be ported with a little effort.

If only that...
instremu.c also executes the ops
themselves natively, so just porting
flags is not enough. :(

**Comment by stsp** [comment]
So that seems to have been fixed,
thanks Bart!
