### ISSUE TITLE
avoid linking with asm-compiled objects

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1834]
We still have plenty of .S files that
are linked in to the main executable.
They all needs to be converted to .s,
using Andrew's xxd trick.
(except probably mcontext/asm.S)

Andrew, would you like to take a look
at converting the rest of them?
Arm port is quite near, those are the
remaining obstacles I believe.

**Comment by stsp** [comment]
With some linker tricks I managed
to re-create objects with almost the
same symbols as where with the
host compilation.
So the conversion process went
very easily.

**Comment by andrewbird** [comment]
Sorry I've been travelling today and missed this conversation.

**Comment by stsp** [comment]
But I've found much simpler way
than the xxd-style conversion you
did, so it would be a waste of your
time to ask for an xxd conversion.
Thanks anyway. :)
