### ISSUE TITLE
rework linear allocations

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1846]
Linear allocations regressed when
moving to 64bit address space.
Bart provided a quick fix in #1845.
Lets apply it, but there are disadvantages:
- mapping_find_hole() is inherently
  non-portable (think of cygwin)
- it has a slight chance to fail
- if we need to alias DPMI memory
  (I actually tried that in some of my
  vgaemu speedup attempts but all failed),
  this won't work.

So lets have this ticket for the future.
I think the real solution should be some
riding on an mremap()s back. Since we
cleaned up our code from mem_base, we
should be able to safely expand and move
our pool with mremap(). This will also
highlight any left-overs where we still use
raw pointers instead of dosaddr_t.
But for now smalloc() doesn't support that.
So would be a bit of work.

**Comment by bartoldeman** [comment]
yes I don't like mapping_find_hole either, so submitted #1847.

I'd propose the following:
* get rid of config.dpmi_lin_rsv_base for simplicity. I believe we needed that once upon a time for HX mappings at 0x400000 (4MB) but that place is always mapped these days anyways.
* reserve 4GB in total on 64-bit, 2GB (maybe 1G, on non-ancient Linux 2GB is always possible, not sure about other OS) on 32-bit. Nice thing about 4GB is that the JIT's generated code can't access any DOSEMU code/data any more.
* don't use `mmap` any more to allocate additional memory (e.g. vgaemu LFB buffer), but get that via `smalloc` from `lin_pool`. This way we don't have to worry about negative addresses, as there is only one big contiguous chunk of address space from dosaddr_t 0 to e.g. 2GB.

**Comment by stsp** [comment]
Even if 4Mb is always mapped, we need
to make sure its always free for fixed alloc.
Are you sure it is going to work w/o explicit
reserving?

Why reserving xGb is any better than
to increase $_dpmi to that value, which
is what I already suggested? :) In that
case you avoid the third pool. Unless
you can convince me that the 4Mb
reserve is actually not needeed, its the
same thing.

**Comment by stsp** [comment]
> get rid of config.dpmi_lin_rsv_base for simplicity.

I misread that, you propose to remove
only an option. Done in #1848 .

> don't use mmap any more to allocate additional memory (e.g. vgaemu LFB buffer)

And for xms, which has a "lock emb"
feature to get the physical address.
Good idea.

**Comment by stsp** [comment]
I reworked existing patches to
actually use the 3rd mem pool.
Enough of simplifications, but
the ideas are all still the same.

**Comment by stsp** [comment]
So I think only XMS remained, right?

**Comment by bartoldeman** [comment]
No XMS is ok, it's not mapped into DOS space, the memory is only accessed via memcpy's.

Although it's the only remaining user of `mmap_mapping`, it could use `mmap_mapping_ux` instead, and then `mmap_mapping_ux` can be renamed to `mmap_mapping`.

**Comment by stsp** [comment]
Its not all that simple, see xms_lock_EMB().

**Comment by stsp** [comment]
Maybe if EMBs are page-aligned, we
could implement lock_EMB as alias_map
and unlock_EMB as unmap... But I don't
see them being page-aligned.

**Comment by stsp** [comment]
Also even w/o lock_EMB our XMS
pull should all be available to int15
API for the external himem to work.

**Comment by stsp** [comment]
I merged the changes to make xms
64bit-safe. In fact, making EMBs
page-aligned was The Thing. :)
It now works very similar to EMS:
allocated in a shared pool somewhere
in 64bit space, and is mapped into
DOS-visible space on demand.
No more split memcopy, physaddr_to_unixaddr
and other tricks to lie about an XMS
addresses - all removed.

**Comment by stsp** [comment]
Hi Andrew, can you reproduce the
test failures locally?
https://github.com/dosemu2/dosemu2/actions/runs/3775323284/jobs/6417941235
Works fine for me...

**Comment by stsp** [comment]
> Although it's the only remaining user of mmap_mapping, it could use mmap_mapping_ux instead,
> and then mmap_mapping_ux can be renamed to mmap_mapping.

Done, although w/o renaming.
Anything else you mentioned about
mapping simplifications?
Can't find now, but I think you suggested
a bit more. But I was too busy with xms,
sorry. :) Now xms seems to finally calmed
down.

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2/actions/runs/3819180453/jobs/6496543132
Hi Andrew, all dr-dos tests have
failed and no logs? What happened?

**Comment by andrewbird** [comment]
Well the libi86 tests are timing out for DR-DOS (and here locally too). For some reason the job was cancelled, presumably Github didn't like the lack of progress, or the total time or whatever. In the case of cancellation no logs are collected, and unfortunately there's nothing I can do about that. Running a single libi86 test locally also fails with timeout, but there's no clue as to what's going on as the logs are minimal. The libi86 tests are executing dosemu from the command line with `-k` so there's no chance to run dosemu 'by hand' and run testit.bat in the DOS shell.
~~~
test/test_dos.py DRDOS701TestCase.test_libi86_item_011; stty sane
~~~
Note the terminal is screwed up if dosemu is killed (due to our timeout expiring), so have to reset it afterwards.

I attached the only log produced [test_dos.DRDOS701TestCase.test_libi86_item_011.log](https://github.com/dosemu2/dosemu2/files/10331431/test_dos.DRDOS701TestCase.test_libi86_item_011.log)

Normally libi86 tests produce a 'testsuite.log' which we rename into test_dos.DRDOS701TestCase.test_libi86_item_011.xpt, but there's nothing there, it's just as if the test isn't executed.

**Comment by andrewbird** [comment]
This seems to make it work
```diff
diff --git a/src/bindist/bat/exechlp.bat b/src/bindist/bat/exechlp.bat
index a5358edef..440e82544 100644
--- a/src/bindist/bat/exechlp.bat
+++ b/src/bindist/bat/exechlp.bat
@@ -11,7 +11,8 @@ lh %DOSEMU_SYS_CMD%
 set SHELL_CALL_DEFAULT=
 goto cont
 :not_comcom
-call %DOSEMU_SYS_CMD%
+rem call %DOSEMU_SYS_CMD%^M
+lh %COMSPEC% /E:1024 /C %DOSEMU_SYS_CMD%^M
 :cont
 if "%DOSEMU_EXIT%" == "1" exitemu %ERRORLEVEL%
 C:
```

**Comment by stsp** [comment]
Someone needs to add dr-dos
to the dosemu-installotherdos
script. Would you like to do that?
Then I'll be able to test it before
committing things.

**Comment by andrewbird** [comment]
Not sure there's any need, doesn't the script already offer opendos 7.02?

**Comment by stsp** [comment]
It does, but in opendos, the `call`
seems very buggy.
a.bat:
`echo hello`
aa.bat:
```
call a.bat
echo world
```
```
C:\>aa
 
C:\>call a.bat
echo world
 
Command or filename not recognized
```
Completely broken.

**Comment by andrewbird** [comment]
I think you have a line ending problem. It behaved the same on DR-DOS 7.01 until I did unix2dos on them both.

**Comment by stsp** [comment]
Good guess. :)
So now if I do
`dosemu -dos opendos702 -E aa -T`
then aa.bat is properly executed.
So how to reproduce the problem?

**Comment by andrewbird** [comment]
> So how to reproduce the problem?

No idea. Since the weekly cron job succeeded last week and didn't this week, I just looked what changes were done that might have affected dosemu executing command lines.

**Comment by stsp** [comment]
So -E still works properly
with any dos?

**Comment by andrewbird** [comment]
I was wrong about libi86 test using -K, it seems to be -E. Here's its entry in the process list
~~~
/bin/bash /clients/common/dosemu2.git/bin/dosemu -f /tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir -o /clients/common/dosemu2.git/test_dos.DRDOS701TestCase.test_libi86_item_011.log -tde -I if ($_com4 ne "") abort "" -I serial { com 4 device "/proc/self/fd/1" } -E exit
~~~

I've no idea how '-E exit' executes the test code

**Comment by stsp** [comment]
> I've no idea how '-E exit' executes the test code

Indeed.
I added a work-around so now it does.
It also appeared that drdos'ish command.com
was right and comcom32 was wrong. So I
first had to fix comcom32 to replicate the
problem.

**Comment by stsp** [comment]
I think this is doing quite well now.
