### ISSUE TITLE
DosEmu2 crashes in int 31h, ax=504h

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1856]
**Describe the bug**
DosEmu terminates "silently"

**To Reproduce**
Steps to reproduce the behaviour:
launch the attached app (s.exe). The first time it runs ok, the second time the crash occurs.

**Attach program/game binaries or provide an URL**
[S.exe.zip](https://github.com/dosemu2/dosemu2/files/10308326/S.exe.zip)

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/10308327/boot.log.zip)

**A regression?**
Definitely.

**Additional info**
It crashes on the first int 31h, ax=504h call ( allocate linear memory ), edx=0 ( uncommitted memory ).

**Comment by stsp** [comment]
Thanks!
