### ISSUE TITLE
Some libi86 tests are failing

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1857]
**Describe the bug**
Some tests that were passing are now failing, seemingly more so on MSDOS than FDPP

**To Reproduce**
Let's just take the one test(a libi86 sanity check) for now

~~~
$ test/test_dos.py PPDOSGITTestCase.test_libi86_item_006
Test PP-DOS-GIT  libi86 test   6 Console output testing                          ... ok ( 21.50s)

----------------------------------------------------------------------
Ran 1 test in 21.517s

OK
~~~

but on MSDOS 6.22
~~~
$ test/test_dos.py MSDOS622TestCase.test_libi86_item_006
Test MS-DOS-6.22 libi86 test   6 Console output testing                          ... FAIL

======================================================================
FAIL: Test MS-DOS-6.22 libi86 test   6 Console output testing                         
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/func_libi86_testsuite.py", line 29, in do_test_libi86
    libi86_test_item(self, test[0])
  File "/clients/common/dosemu2.git/test/func_libi86_testsuite.py", line 65, in libi86_test_item
    raise self.failureException("Test error") from None
AssertionError: Test error
Further info in file '/clients/common/dosemu2.git/test_dos.MSDOS622TestCase.test_libi86_item_006.log'
Further info in file '/clients/common/dosemu2.git/test_dos.MSDOS622TestCase.test_libi86_item_006.xpt'

----------------------------------------------------------------------
Ran 1 test in 7.539s

FAILED (failures=1)
~~~

**Attach program/game binaries or provide an URL**
If the problem needs specific DOS files to reproduce, please attach
or provide the download URL.
[logs.zip](https://github.com/dosemu2/dosemu2/files/10310061/logs.zip)

**Attach the log**
from above zip file, the salient part seems to be that stdout is missing
~~~
--- expout      2022-12-27 18:05:51.257263341 +0000                             
+++ /tmp/test-imagedir/libi86-test/tests/testsuite.dir/at-groups/6/stdout       2022-12-27 18:05:51.345265203 +0000
@@ -1,3 +0,0 @@                                                                 
-w00t                                                                           
-                                                                               
-w0000t                                                                         
6. metacheck.at:89: 6. Console output testing (metacheck.at:89): FAILED (metacheck.at:91)
~~~
**A regression?**
yes

**Additional info**
Before I updated the following packages the test was failing on FDPP also.
~~~
 binutils-ia16-elf causeway-dosx comcom32 dosemu2 dosemu2-dbgsym elks-libc-gcc-ia16-elf fdpp fdpp-dbgsym gcc-ia16-elf libi86-ia16-elf libi86-testsuite-ia16-elf
 libnewlib-ia16-elf
~~~
Note that dosemu and fdpp packages above are not used, this test was run against devel dosemu/master fdpp

**Comment by stsp** [comment]
Can you check if its the problem
with external himem.sys, which
seems to be used on msdos tests?
I'll be reworking XMS support once
again.
Wrote a test-case (attached)
[test.c.txt](https://github.com/dosemu2/dosemu2/files/10310124/test.c.txt)
but there seems to be dozens of
reasons for it to fail (on any dosemu version).
So while I probably introduced a
regression, if its only on an external
himem.sys then I am going to postpone
it until the xms subsystem is properly
written.

**Comment by andrewbird** [comment]
I rem'd out the loading of himem.sys in config,sys but the test still fails.

**Comment by stsp** [comment]
62d266614
This bisects to break
test_memory_emm286_borland
test. Does it affect other tests?

**Comment by andrewbird** [comment]
Yes, here's the test run of something I'm working on, it has 15 that fail.
https://github.com/dosemu2/dosemu2/actions/runs/3789286352/jobs/6442898837

**Comment by stsp** [comment]
Could you please add a log with DOS
console output? Your tests do not
seem to produce one.

**Comment by stsp** [comment]
The problem is simple: I added
SHELL_CALL_DEFAULT var to
comcom32 but it appears you are
using native command.com for
tests, so it lacks the `call` operator.
But if we could see the DOS output
in the log, that conclusion would be
a matter of seconds.

**Comment by andrewbird** [comment]
Unfortunately that test is part of libi86 tests, everything I have (and know how to get) is attached in the first zip file. The test is using dosemu with `-K` I think from the command line, so I don't think I can even run it from the DOS prompt to capture the output.

**Comment by stsp** [comment]
OK let me add another var to detect
comcom32.

**Comment by andrewbird** [comment]
> it appears you are
using native command.com for
tests

Yes, msdos kernel and its native command.com, and likewise for dr-dos, and freedos

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
Re-pushed the fix.
It appears `call` works universally,
also for launching binaries. So for
other command.coms I can use it
instead of `lh`.

**Comment by stsp** [comment]
Fixed emm286 test too.
So there was no xms regression,
which is good. :)

**Comment by andrewbird** [comment]
Looks a lot better now, just one test failing. Pcmos build but only on fdpp, see https://github.com/dosemu2/dosemu2/actions/runs/3790016758/jobs/6444296700

**Comment by stsp** [comment]
The fix is:
```
diff --git a/SOURCES/src/import/IMPORT.MAK b/SOURCES/src/import/IMPORT.MAK
index 9710623..7af89e5 100644
--- a/SOURCES/src/import/IMPORT.MAK
+++ b/SOURCES/src/import/IMPORT.MAK
@@ -20,7 +20,7 @@
 ###############################################################################
 #
 .c.obj:
-        cl -c $<
+        loadfix cl -c $<^M
 
 .asm.obj:
         masm -Mx $*;
```

Could you please apply it to
MOS, or better just unpack
cl.exe and re-upload to their
git?

**Comment by andrewbird** [comment]
I started to make a PR for this, but I don't understand why `loadfix` isn't needed in other directories. For instance `SOURCES/src/latest/MAKEUTIL.MAK` has `cl -c` bare and is able to build compfile.exe, helpgen.exe and ed.exe quite happily?

**Comment by stsp** [comment]
For example because recursive make
invocation. If one make executes another
make and that one executes cl, then the
needed space may be occupied. Maybe
in the first case it was top-level make.
I would rather unexepack cl and upload
that to git.

**Comment by stsp** [comment]
https://www.pcorner.com/list/MISC/NDMAKE45.ZIP/MAKE.DOC/
```
When MAKE executes commands, such as `link', it checks if it's a DOS
internal command, if it's a batch file, or if it involves IO
redirection. If so, MAKE loads a second copy of COMMAND.COM and
passes it the command line. Otherwise, MAKE tries to execute the
command as a program (a .exe or .com file). This is done to prevent
loading COMMAND.COM unless absolutely necessary.
```
If not for that, our auto_loadfix would
fix the problem. It seems there is no
switch to convince "make" to always
use command.com.

**Comment by stsp** [comment]
[al.c.txt](https://github.com/dosemu2/dosemu2/files/10359364/al.c.txt)
Hi Andrew, could you please add
this test-case?

Also I wonder why UMB allocation
strategies (0x40, 0x80)
http://www.ctyme.com/intr/rb-3008.htm
only work when UMBs linked in?
http://www.ctyme.com/intr/rb-3009.htm
What is the rationale behind such decision?
I checked that linking in UMB allows
the normal strategies to allocate from
UMB, and that's perfectly fine. But why
UMB-specific strats do not see UMB
unless linked in?

**Comment by andrewbird** [comment]
In a bit of a rush, so have a look at #1872. I tweaked the messages slightly to suit my usual test style but I hope your original intent is still valid.
