### ISSUE TITLE
TradeWars 2002 (DOS BBS door game) unable to initialize the fossil driver

### ISSUE THREAD

**Issue by EricOulashin** [dosemu2/dosemu2#1868]
**Describe the bug**
Tested with 2.0~pre9-7812-6d6b458b6+202301030131~ubuntu22.04.1 (though may have started with 7811-4373124b9+202301020131).  When a user is logged into a BBS and tries to run TradeWars 2002 v3.09, TradeWars 2002 says it's unable to initialize the fossil driver and quits.  TradeWars 2002 was previously working and did not have this issue with dosemu2 2.0~pre9-7807-4e99cf2c5+202301010131

**To Reproduce**
Set up a BBS with TradeWars 2002 v3.09 as an online door game.  TradeWars 2002 should produce twerr.log with the error; alternately, in the command to run TW2002.EXE, add >err.log and the error should appear in err.log.

**Attach program/game binaries or provide an URL**
One place TradeWars 2002 can be downloaded is [here](http://digitaldistortionbbs.com/api/files.ssjs?call=download-file&dir=bbsfile_dosbbsdg&file=2002v309.zip).

**Attach the log**

FDPP kernel 1.6 [GIT: ] (compiled Dec 27 2022)
fdpp: plugin loaded: 1
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: config variable c_user set
CONF: Parsing /home/erico/BBS/sbbs/ctrl/dosemu.conf file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
CONF: 1024k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: dos_up: on
CONF: DPMI-Server on (0x20000)
CONF: DPMI base addr = 0x2000000
CONF: DPMI linear reserve size = 0x80000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 3008k bytes int15 ext memory
CONF: 1024k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: no device specified, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
CONF: Keyboard-layout us
CONF: fastfloppy = 1
default_drives 0
Setting up drive C, ~/.dosemu/drive_c
Creating default drive C
Added drive 0 (80): ~/.dosemu/drive_c
skip 2 drives from 1
CONF: disk type 'Directory' drive D:
CONF: disk type 'Directory' drive E:
CONF: disk type 'Directory' drive F:
default_drives 1
Added drive 4 (84): /usr/share/dosemu/dosemu2-cmds-0.3
Setting up default drives from H
Added drive 5 (85): /usr/share/comcom32
Added drive 6 (86): /usr/share/dosemu2-extras/bat
CONF: IPX support off
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 enabled.
CONF: config variable c_system unset
Command line: /usr/bin/dosemu.bin -o /home/erico/.dosemu/boot.log
CPU set to 486
Warning: Linux kernel 5.15.0; CPU speed is 3700000000 Hz
Warning: CPU-EMU speed is 3700 MHz
CONF: V86 cpu vm set to -1
CONF: DPMI cpu vm set to -1
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
Warning: dosemu2-2.0pre9 is coming up on Linux version 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64
Warning: Compiled with clang version 14.0.0 (gnuc 4.2)Warning:  64bit
Warning: CFLAGS: -Wno-microsoft -Wno-incompatible-pointer-types -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -fno-stack-protector -ggdb3 -fdebug-macro -fpie -g -O2 -ffile-prefix-map=/build/dosemu2-8CF70P/dosemu2-2.0~pre9-7807=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 16Kb at 0xFA000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0202
initial segment bases: fs: 0x7f563cb520c0  gs: (nil)
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Warning: Using V86 mode inside KVM
Conventional memory mapped from 0x7f56391a5000 to 0x7f5619095000
CONF: reserving 3008Kb at 0x110000 for 'x' (Extended memory (HMA+XMS))
DPMI memory mapped to 0x7f5619495000 (reserve)
CONF: reserving 64Kb at 0x100000 for 'H' (HMA)
loading fonts for cp437
VID: Video set to Video_term
Registering HWRAM, type=e base=0xa5f6000 size=0x400000
CONF: reserving 4096Kb at 0xA5F6000 for 'e' (VGAEMU LFB)
CONF: reserving 4Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
DPMI: mem init, mpool is 140468224 bytes at 0x7f561b095000
Warning: Using DPMI inside KVM
TIME: using 9154 usec for updating ALRM timer
CONF: freeing region for 'E' (EMS page frame)
ERROR: unknown window sizes li=0  co=0, setting to 80x25
booting with comcom32
Compatibility warning: CONFIG.SYS found on drive C: is not used by fdpp.
        Use C:\FDPPCONF.SYS to override or C:\USERHOOK.SYS to extend
        the default boot-up config file.
        You can also put KERNEL.SYS to drive C: to override fdpp entirely.
config.boot_dos set to 400000
config.int_hooks set to 0
config.force_revect set to 0
CONF: reserving 124Kb at 0xC1000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 40Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
About to Execute: L10MAIN2.BAT
DOS termination requested
leavedos(do_doshelper:65|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped

Package info:
dosemu2: installed
dosemu2 2.0~pre9-7807-4e99cf2c5+202301010131~ubuntu22.04.1
fdpp: installed
fdpp    1.6-1301-d010c93+202212272316~ubuntu22.04.1

**A regression?**
This did not happen with 2.0~pre9-7807-4e99cf2c5+202301010131 or with dosemu 1.

**Additional info**
dosemu.conf:

$_cpu = "80586"
$_cpu_emu = "fullsim"
$_floppy_a = ""
$_cdrom = ""
$_xms = (8192)
$_ems = (2048)
$_ems_frame = (0xe000)
$_external_char_set = "cp437"
$_internal_char_set = "cp437"
$_term_updfreq = (8)
$_layout = "us"
$_rawkeyboard = (auto)
$_mouse_internal = (on)
$_mouse_dev = ""
$_joy_device = ""
$_lpt1 = ""
$_lp2 = ""
$_speaker = ""
$_sound = (off)
$_sb_dsp = ""
$_hdimage = "+0 -2 /home/erico/BBS/sbbs/ctrl /home/erico/BBS/sbbs/data /home/erico/BBS/sbbs/exec +1"
$_lredir_paths = "/home/erico/BBS/sbbs /home/erico/BBS"
$_rdtsc = (on)
$_cpuspeed = (0)
$_hogthreshold = (1)

**Comment by stsp** [comment]
I don't see you configured any
com ports, in which case fossil
is not going to load.

**Comment by EricOulashin** [comment]
I use Synchronet (BBS software), which automatically provides a fossil
driver. At any rate, TradeWars 2002 worked with an earlier recent build of
Dosemu2 with the same configuration.

I will try configuring a com port though.

Eric

**Comment by stsp** [comment]
> I will try configuring a com port though.

Good idea and consider removing
other options that you do not use.
Otherwise it will break more than often.

**Comment by stsp** [comment]
As for what changed, now
`lh` is used by default for -E
and -K. Maybe that breaks
something, so once you update
your config, try commenting out
`set SHELL_LOADHIGH_DEFAULT=1`
in exechlp.bat.

**Comment by EricOulashin** [comment]
I tried enabling com1 in my dosemu.conf:
$_com1 = "virtual"

However, with that, I now get this error when dosemu2 starts:
Device conflict: Attempt to use /dev/pts/4 for serial and serial

**Comment by stsp** [comment]
This means you set com1 already somewhere,
for example in a command line. But we
dont see your command line.

**Comment by EricOulashin** [comment]
> This means you set com1 already somewhere, for example in a command line. But we dont see your command line.

Command line:

/usr/bin/env  HOME=/home/erico/BBS/sbbs/ctrl/ QUIET=1 DOSDRIVE_D=/home/erico/BBS/sbbs/node1/ DOSDRIVE_E=/home/erico/BBS/doors DOSDRIVE_F=/home/erico/BBS/sbbs/ctrl/ DOSDRIVE_G=/home/erico/BBS/sbbs/data/ DOSDRIVE_H=/home/erico/BBS/sbbs/exec/ NODEDIR=/home/erico/BBS/sbbs/node1/ /usr/bin/dosemu.bin -d /home/erico/BBS/sbbs/node1/ -d /home/erico/BBS/doors -d /home/erico/BBS/sbbs/ctrl/ -d /home/erico/BBS/sbbs/data/ -d /home/erico/BBS/sbbs/exec/ -d /home/erico/BBS/doors -I"video { none }" -I"serial { virtual com 1 }" -f/home/erico/BBS/sbbs/ctrl/dosemu.conf -ED:external.bat -o/home/erico/BBS/sbbs/node1/dosemu_boot.log


external.bat:

@ECHO OFF^M
SET DSZLOG=D:\PROTOCOL.LOG^M
SET SBBSNODE=D:^M
SET SBBSNNUM=1^M
SET SBBSCTRL=F:^M
SET SBBSDATA=G:^M
SET SBBSEXEC=H:^M
SET PCBNODE=1^M
SET PCBDRIVE=D:^M
SET PCBDIR=\^M
SET STARTDIR=TW2002^M
REM @lredir -f E: \home\erico\BBS\doors >NUL
REM @lredir -f F: \home\erico\BBS\sbbs\ctrl >NUL
REM @lredir -f G: \home\erico\BBS\sbbs\data >NUL
REM @lredir -f H: \home\erico\BBS\sbbs\exec >NUL
REM @lredir -f D: \home\erico\BBS\sbbs\node1 >NUL

REM @lredir -f E: linux/fs\home\erico\BBS\doors >NUL
REM @lredir -f F: linux/fs\home\erico\BBS\sbbs\ctrl >NUL
REM @lredir -f G: linux/fs\home\erico\BBS\sbbs\data >NUL
REM @lredir -f H: linux/fs\home\erico\BBS\sbbs\exec >NUL
REM @lredir -f D: linux/fs\home\erico\BBS\sbbs\node1 >NUL

E:

REM Switch to startup dir, unless its not defined
REM If not defined, go to node dir (external editors use this)
IF "%STARTDIR%"=="" D:
IF NOT "%STARTDIR%"=="" CD %STARTDIR%

REM Optionally call emusetup.bat or put that stuff here for global (in NOEMU)
REM Looks in startup dir, then ctrl dir
IF EXIST EMUSETUP.BAT GOTO EMULOCAL
IF EXIST F:\EMUSETUP.BAT GOTO EMUGLOBAL
IF EXIST E:\DOSUTILS\NUL GOTO NOEMU
IF EXIST H:\DOSUTILS\NUL GOTO NOEMU
ECHO ERROR: No emusetup.bat in E:\%STARTDIR% or F, or DOSUTILS is missing
GOTO EXEC

:EMULOCAL
CALL EMUSETUP.BAT
GOTO EXEC

:EMUGLOBAL
CALL F:\EMUSETUP.BAT
GOTO EXEC

:NOEMU
@set PATH=%PATH%;E:\dosutils;H:\dosutils;H:\dosutils\dosemu2
REM fossil driver, such as x00, bnu, or dosemu fossil.com
rem IF "FOSSIL" == "FOSSIL" @fossil.com >NUL
rem IF "FOSSIL" == "FOSSIL" bnu.com /P1 /L0=11520 >NUL
IF "FOSSIL" == "FOSSIL" x00.exe eliminate >NUL
REM share.exe for multinode file locking
@share >NUL

GOTO EXEC

:EXEC
TW2002.EXE TWNODE=1 DATA=E:\TW2002
REM TW2002.EXE TWNODE=1 DATA=E:\TW2002 >DEBUG.TXT 2>&1

IF NOT "%1" == "TEST" exitemu

**Comment by stsp** [comment]
Please locate
`/usr/share/dosemu/dosemu2-cmds-0.3/dosemu/exechlp.bat`
and remove this line:
`set SHELL_LOADHIGH_DEFAULT=1`.
Maybe that will help.

**Comment by stsp** [comment]
Please update comcom32 from PPA.
Maybe that will help.

**Comment by stsp** [comment]
With latest comcom32 build you
can pass `SHELL_LOADHIGH_DEFAULT=0`
to dosemu2's cmd line and disable
the loadhigh behavior. This is the only
change in the commits you point to,
so maybe that will help.

**Comment by stsp** [comment]
OK, if its still the problem - re-open.
Closing stalled ticket.

**Comment by EricOulashin** [comment]
> Please locate `/usr/share/dosemu/dosemu2-cmds-0.3/dosemu/exechlp.bat` and remove this line: `set SHELL_LOADHIGH_DEFAULT=1`. Maybe that will help.



> With latest comcom32 build you can pass `SHELL_LOADHIGH_DEFAULT=0` to dosemu2's cmd line and disable the loadhigh behavior. This is the only change in the commits you point to, so maybe that will help.

I specified SHELL_LOADHIGH_DEFAULT=0 in cmdhelp.bat and that fixed the problem.  Thanks!

**Comment by stsp** [comment]
Are you sure?
Maybe something else was fixed in a mean
time?
Can I see that problem without a full bbs
setup, but just by running the fossil itself?

**Comment by EricOulashin** [comment]
Yes, I tested it on my setup. I updated to the current version and
TradeWars 2002 didn't run as a door until I used that command line option.

I'm not sure of the best way to show without a BBS setup.

**Comment by stsp** [comment]
OKey, lets undefault that behavior then.

**Comment by stsp** [comment]
OKey, lets undefault that behavior then.

**Comment by stsp** [comment]
Should now be fixed.
Please check.

**Comment by EricOulashin** [comment]
> Should now be fixed. Please check.

I've installed dosemu2 2.0~pre9-7903-9d1ac8737+202302132016 and TradeWars 2002 works now without the SHELL_LOADHIGH_DEFAULT=0 explicitly being set.
