### ISSUE TITLE
LFN functions do not fully work on "lredired" FAT drives

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [dosemu2/dosemu2#1869]
**Describe the bug**
changing current directory of a FAT32 drive mounted with LREDIR, using LFN function 713Bh, may return error code 0003 ( invalid path ). 

Preconditions:
- the directory to change to must have a long filename
- it must not be located in the root dir.

**To Reproduce**
See the Screen shot

**Attach the log**
Don't know what to activate in the log.

**A regression?**
No.

**Additional info**
I got the info that error code 0003 is returned by using DEBUG

[Screenshot at 2023-01-04 13-51-48.png.zip](https://github.com/dosemu2/dosemu2/files/10344287/Screenshot.at.2023-01-04.13-51-48.png.zip)

**Comment by stsp** [comment]
```
FreeCom version 0.85a - WATCOMC - XMS_Swap [Jul 10 2021 19:28:06]
C:\>mkdir 12345678987654321
C:\>cd 12345678987654321
C:\12345678987654321>cd ..
C:\>cd 12345678987654321
C:\12345678987654321>cd ..
C:\>cd 12345678987654321
C:\12345678987654321>cd ..
C:\>rmdir 12345678987654321
C:\>
```
How to reproduce?

**Comment by ecm-pushbx** [comment]
> it must not be located in the root dir.

Your test is only in a directory located in the root directory, but the report specifies that you should test a directory within a subdirectory.

**Comment by andrewbird** [comment]
I can reproduce.

~~~
C:\>dir f: /lfn
 Volume in drive F is  MNT DOSEMU
 
 Directory of F:\
 
PROGRA~1             <DIR>  01-04-23  4:15p Program Files
VERYLO~1 TXT             9  01-04-23  4:15p verylongfilename.txt
VERYLO~2 TXT             9  01-04-23  4:15p verylongfilename2.txt
SPACEE~1 TXT             9  01-04-23  4:15p space embedded filename.txt
MIXEDC~1 EXT             9  01-04-23  4:15p MixedCaseFilename.ext
         4 file(s)             36 bytes
         1 dir(s)       1,455,104 bytes free
C:\>f:
F:\>mkdir test
F:\>cd test
F:\test>mkdir 1234567890987654321
F:\test>cd 1234567890987654321
CHDIR failed for '1234567890987654321'. 
~~~

~~~
ajb@polly:/clients/common/dosemu2.git$ mount | grep dosemu
/img/dosemu.img on /mnt/dosemu type vfat (rw,noexec,relatime,uid=500,gid=500,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=win95,errors=remount-ro)
ajb@polly:/clients/common/dosemu2.git$ ls -l /mnt/dosemu
total 3
-rwxr-xr-x 1 ajb sphere   9 Jan  4 16:15  MixedCaseFilename.ext
drwxr-xr-x 2 ajb sphere 512 Jan  4 16:15 'Program Files'
-rwxr-xr-x 1 ajb sphere   9 Jan  4 16:15 'space embedded filename.txt'
drwxr-xr-x 3 ajb sphere 512 Jan  4 16:17  test
-rwxr-xr-x 1 ajb sphere   9 Jan  4 16:15  verylongfilename2.txt
-rwxr-xr-x 1 ajb sphere   9 Jan  4 16:15  verylongfilename.txt
ajb@polly:/clients/common/dosemu2.git$ ls -l /mnt/dosemu/test
total 1
drwxr-xr-x 2 ajb sphere 512 Jan  4 16:17 1234567890987654321
~~~

**Comment by stsp** [comment]
> Your test is only in a directory located in the root directory

Thanks.
OK, Andrew is on it, it seems. :)

**Comment by andrewbird** [comment]
MFS is looking for sfn  '/mnt/dosemu/test/12345~a6', but that's our mangling method. on vfat the mangling is as per windows
~~~
$ ls /mnt/dosemu/test/12345~a6
ls: cannot access '/mnt/dosemu/test/12345~a6': No such file or directory

$ ls -ld /mnt/dosemu/test/123456~1
drwxr-xr-x 2 ajb sphere 512 Jan  4 16:17 /mnt/dosemu/test/123456~1
~~~

Leave it with me...

**Comment by Baron-von-Riedesel** [comment]
Cool! Everything works now. Nice work!

Btw., I noticed this bug several years ago, but said to myself: it's such an obvious bug, no need to bother reporting it, they will soon discover it on their own. But as it seems, LFN functionality is hardly used in DOS...

**Comment by andrewbird** [comment]
It's more likely that most people don't mount fat disks these days to run dosemu from. One more thing though, I'm not sure how dos attributes will function on there these days.
