### ISSUE TITLE
Pcmos test crashes  (on FreeDOS 1.3) under emulation, but not KVM

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#1876]
**Describe the bug**

~~~
$ test/test_dos.py FRDOS130TestCase.test_pcmos_build
Test FR-DOS-1.30 PC-MOS build script                                             ... ok ( 26.65s)

----------------------------------------------------------------------
Ran 1 test in 26.665s

OK
$ sudo mv /dev/kvm /dev/kvm.off
[sudo] password for ajb: 
$ test/test_dos.py FRDOS130TestCase.test_pcmos_build
Test FR-DOS-1.30 PC-MOS build script                                             ... FAIL

======================================================================
FAIL: Test FR-DOS-1.30 PC-MOS build script                                            
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 4864, in test_pcmos_build
    self.assertNotIn('Timeout', results)
AssertionError: 'Timeout' unexpectedly found in "ERROR: KVM: error opening /dev/kvm: No such file or directory\nfluidsynth: warning: SDL2 not initialized, SDL2 audio driver 
<snip>
~~~

Here's the salient part of  the xpt
~~~
loadfix cl -c compfile.c
Microsoft (R) C Optimizing Compiler Version 5.10
Copyright (c) Microsoft Corp 1984, 1985, 1986, 1987, 1988. All rights reserved.

compfile.c
ERROR: SIGILL while in vm86(): 1416:590e

Invalid Opcode at 590E 1416 3244 4788 001F 0003 1B2E 17A0 0023 0003 0002 0004 1B2C 

*** Error code 255
Bad or missing Command Interpreter: command.com /e:1024 /k c:\fdautoem.bat
 Enter the full shell command line: 
Timeout:300 seconds
~~~

**To Reproduce**
Run the test case as above, (with kvm disabled)
See the problem at the end of *.log and *.xpt

**Attach program/game binaries or provide an URL**
See the branch https://github.com/andrewbird/dosemu2/tree/ci-11

**Attach the log**
[t1.zip](https://github.com/dosemu2/dosemu2/files/10368248/t1.zip)

**A regression?**
No idea, couldn't be tested on FreeDOS until 1.3 as prior versions had a CDS problem preventing dosemu -E/-K

**Comment by stsp** [comment]
Please see $_cpuemu = (0) or (1)
to check if its a problem with particular
back-end.

**Comment by andrewbird** [comment]
It failed with both.

**Comment by andrewbird** [comment]
Actually with `$_cpuemu = (1)` the crash report didn't appear as the progress stalled elsewhere.
~~~
masm mosint06;^M                                                                
Microsoft (R) Macro Assembler Version 5.10 ^M                                   
Copyright (C) Microsoft Corp 1981, 1988.  All rights reserved.^M                
^M                                                                              
                                                                                
Timeout:300 seconds                                                             
~~~

I have to go out for the day now.

**Comment by stsp** [comment]
Никогда такого не было, и вот, опять.
So how could this happen that [full ci]
have passed, but now weekly tests fail?

**Comment by stsp** [comment]
Well, the freedos kernel you put
into that test, still gives
`-d/-K is not supported with this freedos version`.
So please undo or update.

**Comment by andrewbird** [comment]
> So how could this happen that [full ci]
have passed, but now weekly tests fail?

It didn't. When I added `[full ci]`, the proposed merge commit still ran as normal (which is probably what you see passing), only my branch got the full test (and failed) https://github.com/andrewbird/dosemu2/actions/runs/3864045937/jobs/6586605457. That `[full ci]` was only applied to one was unexpected by me, I'll have a look into whether I can change it somehow.

> Well, the freedos kernel you put
into that test, still gives
-d/-K is not supported with this freedos version.

Can you point me to the Github Action run where you see this please?

**Comment by stsp** [comment]
I locally tried that because build.sh
does so.

**Comment by andrewbird** [comment]
You must run `test/test_dos.py FRDOS130TestCase.test_pcmos_build` to use the FreeDOS 1.3 kernel, otherwise you'll have to set up your local dosemu to have the correct kernel. If you don't have the binaries, you can download them using 
`test/test_dos.py --get-test-binaries`.

**Comment by stsp** [comment]
But I simply dont see the need of such
upgrade. -K still not working, test fails,
whats the reason?

**Comment by andrewbird** [comment]
So I checked out devel, and fdpp master, and built them. Then did this
~~~
ajb@polly:/clients/common/dosemu2.git$ test/test_dos.py --get-test-binaries
ajb@polly:/clients/common/dosemu2.git$ test/test_dos.py FRDOS130TestCase.test_pcmos_build
Test FR-DOS-1.30 PC-MOS build script                                             ... ok ( 26.45s)

----------------------------------------------------------------------
Ran 1 test in 26.472s

OK
~~~

What are you doing different?

**Comment by stsp** [comment]
I am running build.sh after adding
`-dos xxx` to it. Mos build is quite big
so there is no point in running it as
a single test-case, as I'll need to
minimize it to locate an error.
And I simply don't know why do we
need an update that fixes nothing but
adds more problems. I thought it
would fix things.

**Comment by andrewbird** [comment]
But you're not even running the TestCase how can you complain about it? `build.sh` will just run whatever dosemu is in your path in whatever DOS drive_c you have configured.

**Comment by stsp** [comment]
Why do I need to run the test-case
to check that this freedos is completely
broken? There are other ways of checking
that. Don't you believe its broken - check
for yourself.

**Comment by andrewbird** [comment]
'this freedos'  == **what freedos?** . I've no idea what freedos you are running, it's certainly not the one configured by the test unless you are doing
~~~
bin/dosemu -n  -q -f test-imagedir/dosemu.conf --Fimagedir `pwd`/test-imagedir   
~~~

**Comment by stsp** [comment]
Exactly the same kernel that runs
with the test. Why don't you check
that for yourself? I did.

**Comment by andrewbird** [comment]
~~~
Welcome to dosemu2!
    Build 2.0pre9-dev-20230108-740-g92485e7b6
Interactive Prompt!
C:\>ver /r

FreeCom version 0.85a - WATCOMC - XMS_Swap [Jul 10 2021 19:28:06]
DOS version 7.10
FreeDOS kernel 2043 (build 2043 OEM:0xfd) [compiled May 14 2021]
~~~

**Comment by stsp** [comment]
Now try -K.

**Comment by andrewbird** [comment]
~~~
ajb@polly:/clients/common/dosemu2.git$ bin/dosemu -td -n  -q -f test-imagedir/dosemu.conf --Fimagedir `pwd`/test-imagedir -K ./my.bat
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
FreeDOS kernel 2043 (build 2043 OEM:0xfd) [compiled May 14 2021]
Kernel compatibility 7.10 - WATCOMC - 80386 CPU required - FAT32 support

(C) Copyright 1995-2012 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=    10 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
EMUFS host file and print access available                                     
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
dosemu CDROM driver installed (V0.2)
Kernel: allocated 46 Diskbuffers = 24472 Bytes in HMA
emufs: redirector enabled
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre9-dev-20230108-740-g92485e7b6

FreeCom version 0.85a - WATCOMC - XMS_Swap [Jul 10 2021 19:28:06]
DOS version 7.10
FreeDOS kernel 2043 (build 2043 OEM:0xfd) [compiled May 14 2021]
~~~

**Comment by stsp** [comment]
```
FreeDOS kernel 2043 (build 2043 OEM:0xfd) [compiled May 14 2021]
Kernel compatibility 7.10 - WATCOMC - 80386 CPU required - FAT32 support

(C) Copyright 1995-2012 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
EMUFS host file and print access available                                     
dosemu XMS 3.0 & UMB support enabled
dosemu EMS driver rev 0.9 installed.
Kernel: allocated 46 Diskbuffers = 24472 Bytes in HMA
ERROR: INT21: redirecting /home/stas/src/pcmos386v501 failed (err = 15)
ERROR: -d/-K is not supported with this freedos version
```

**Comment by andrewbird** [comment]
And the command line you used to get that, please?

**Comment by stsp** [comment]
OK I applied the patch that doesn't
print this. :)

**Comment by stsp** [comment]
So if I set
```
$_cpu_vm = "emulated"
$_cpu_vm_dpmi = "emulated"
```
and build.sh still works.
Can you suggest the minimal
change needed to reproduce
the problem?

**Comment by andrewbird** [comment]
I just disabled /dev/kvm, the dosemu selected the emulation type.

**Comment by stsp** [comment]
Have you tried that build.sh
crashes?

**Comment by andrewbird** [comment]
So if I make the change to build.sh to run using my locally compiled dosemu with the config / disks from the test as follows
```diff
diff --git a/build.sh b/build.sh
index 018dfe2..eb3dccd 100755
--- a/build.sh
+++ b/build.sh
@@ -13,4 +13,8 @@ else
     ARGS="-K SOURCES/src/MAKEMOS.BAT -U 2"
 fi
 
-dosemu -td -ks $ARGS 'path=%D\bin;%O'
+ME=/clients/common/dosemu2.git
+
+ARGS="-n -q -f ${ME}/test-imagedir/dosemu.conf --Fimagedir ${ME}/test-imagedir ${ARGS}"
+
+${ME}/bin/dosemu -td -ks $ARGS 'path=%D\bin;%O'
```

I can run the test with kvm fine.
Then clean the build `git clean -d -x -f`
sudo mv /dev/kvm /dev/kvm.off

~~~
loadfix cl -c compfile.c
Microsoft (R) C Optimizing Compiler Version 5.10
Copyright (c) Microsoft Corp 1984, 1985, 1986, 1987, 1988. All rights reserved.

compfile.c

Invalid Opcode at 590E 1416 3244 4788 001F 0003 1B2E 17A0 0023 0003 0002 0004 1B2C 

*** Error code 255
Bad or missing Command Interpreter: command.com /e:1024 /k c:\fdautoem.bat
 Enter the full shell command line: 
~~~

**Comment by stsp** [comment]
Your dosemu.conf only has
`$_force_fs_redirect = (off)`
and there seems to be no images.
So how about just finding out
what's needed in .dosemurc?

**Comment by andrewbird** [comment]
Images?

**Comment by stsp** [comment]
> So if I make the change to build.sh to run using my locally compiled dosemu with the config / disks

Ok what "disks" are needed here?

**Comment by andrewbird** [comment]
In this case only the directory under test-imagedir/dXXXXs/c

**Comment by stsp** [comment]
Yes so nothing special.
So would it be possible to do
the same with local config in
.dosemurc and no mods to
build.sh then?

**Comment by andrewbird** [comment]
> So would it be possible to do
the same with local config in
.dosemurc and no mods to
build.sh then?

Sure, but it's not something I'd want to do to the test suite. Currently it has the ability to operate completely independently of the user's normal dosemu environment, creating / deleting all config and disks before / after each individual test so that it's deterministic.

**Comment by stsp** [comment]
You dont need to do anything, just tell me
what config do I need because for me it
still doesnt crash.

**Comment by stuaxo** [comment]
@andrewbird django has a [--keepdb option](https://docs.djangoproject.com/en/4.1/topics/testing/overview/#:~:text=You%20can%20prevent%20the%20test%20databases%20from%20being,does%20not%20exist%2C%20it%20will%20first%20be%20created.) for its unit tests - instead of deleting it's database after unit testing it keeps it around, this can help diagnose problems with tests.

The Dosemu2 analogy to djangos database is the config + disks that are cleared between each test.

I wonder if having a switch to keep them would be handy here ?

You could pass in a switch `--keepdos` (or a some better name) run the test, and then do the work with to work out what's up with the test by looking at the config / disks etc.

**Comment by andrewbird** [comment]
@stsp I don't know if you are trying to be difficult, but I already showed you at least twice. Here's the latest https://github.com/dosemu2/dosemu2/issues/1876#issuecomment-1376164066 . Just to be triply sure, the config is
~~~
ajb@polly:/clients/common/dosemu2.git$ test/test_dos.py FRDOS130TestCase.test_pcmos_build
Test FR-DOS-1.30 PC-MOS build script                                             ... ok ( 40.89s)

----------------------------------------------------------------------
Ran 1 test in 40.913s

OK
ajb@polly:/clients/common/dosemu2.git$ cat test-imagedir/dosemu.conf 
$_force_fs_redirect = (off)
$_hdimage = "dXXXXs/c:hdtype1 +1"
$_floppy_a = ""
~~~

Which as you can see runs fine, but if you disable kvm like I do by renaming the device file, the error is triggered. I don't know what cpu emulator config incantation that translates to, but I'm sure you do. So to replicate this env in your personal ~/.dosemu location you can copy the `test-imagedir/dosemu.conf` to `~/.dosemu/.dosemurc` and edit the drive location to where you will move `test-imagedir/dXXXXs/c` to in `~/.dosemu`

@stuaxo keeping the work area after a single test is the default here too, as actually it's only removed before the next test.
Then to use that DOS environment 
~~~
bin/dosemu -n  -q -f test-imagedir/dosemu.conf --Fimagedir `pwd`/test-imagedir 
~~~

**Comment by stuaxo** [comment]
Cheers, that's handy to know, I think I was assuming they would all be generated in /tmp somewhere.

**Comment by stsp** [comment]
```
$ test/test_dos.py FRDOS130TestCase.test_pcmos_build
[ ^C ]
$ cat test-imagedir/dosemu.conf 
$_force_fs_redirect = (off)
```

So our configs differ?
Mine has just 1 line, which I of
course tried to put as a local config.

**Comment by stsp** [comment]
And that also seems to be the
reason why your command
`bin/dosemu -n  -q -f test-imagedir/dosemu.conf --Fimagedir `pwd`/test-imagedir`
doesn't work for me: with that
dosemu.conf there is no drive D.

**Comment by andrewbird** [comment]
> So our configs differ?

Perhaps if you hadn't Ctrl-C'd during the setup phase the whole config file would have been written.

**Comment by stsp** [comment]
No, I repeated that many times,
removing `test-imagedir` in between.
```
$ time test/test_dos.py FRDOS130TestCase.test_pcmos_build
 FRDOS130TestCase.test_pcmos_build
Test FR-DOS-1.30 PC-MOS build script                                             ... ^CTraceback (most recent call last):
...
KeyboardInterrupt


real	0m16,260s
user	0m0,093s
sys	0m0,082s

$ cat test-imagedir/dosemu.conf 
$_force_fs_redirect = (off)
```

So this time I waited 16 seconds
and still got that dosemu.conf.

**Comment by andrewbird** [comment]
Yes, but it could take longer to get to the point in the test where the remaining config gets written (immediately before running dosemu). Prior to that in this test the pcmos repo is cloned, depending upon your internet speed/site speed that could take 16 seconds. If you want to be sure put a pause into MAKEMOS.BAT and Ctrl-C when you get to that.

**Comment by stsp** [comment]
Oh, why not to write it in 1 go?

**Comment by andrewbird** [comment]
Mmm,  a slight flaw in that plan. MAKEMOS.BAT is part of the git repo checkout.

The `$_force_fs_redirect = (off)` is part of every dosemu.conf in the suite, the rest varies according to each test's needs.

Try this hack
```diff
diff --git a/test/common_framework.py b/test/common_framework.py
index 392201b14..804806a5b 100644
--- a/test/common_framework.py
+++ b/test/common_framework.py
@@ -442,6 +442,8 @@ class BaseTestCase(object):
         if config is not None:
             self.mkfile("dosemu.conf", config, dname=self.imagedir, mode="a")
 
+        raise ValueError
+
         self.logfiles['xpt'][1] = "output.log"
         try:
             ret = check_output(args, cwd=cwd, timeout=timeout, stderr=STDOUT).decode('ASCII')
```

Then
~~~
ajb@polly:/clients/common/dosemu2.git$ test/test_dos.py FRDOS130TestCase.test_pcmos_build
Test FR-DOS-1.30 PC-MOS build script                                             ... ERROR

======================================================================
ERROR: Test FR-DOS-1.30 PC-MOS build script                                            
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clients/common/dosemu2.git/test/test_dos.py", line 4859, in test_pcmos_build
    results = self.runDosemuCmdline(args, cwd=str(mosroot), timeout=300, config="""\
  File "/clients/common/dosemu2.git/test/common_framework.py", line 445, in runDosemuCmdline
    raise ValueError
ValueError

----------------------------------------------------------------------
Ran 1 test in 10.956s

FAILED (errors=1)
~~~

~~~
ajb@polly:/clients/common/dosemu2.git$ cat test-imagedir/dosemu.conf 
$_force_fs_redirect = (off)
$_hdimage = "dXXXXs/c:hdtype1 +1"
$_floppy_a = ""
~~~

**Comment by stsp** [comment]
OK I can instead just copy/paste
from here.

**Comment by stsp** [comment]
Should now be fixed.
Was hoping than the entire xms
rewrite went w/o regressions...
May also affect #1868
