### ISSUE TITLE
Accessing file located on "lredir" samba share does not work

### ISSUE THREAD

**Issue by MaxPower2005** [dosemu2/dosemu2#1890]
Hello

I'm using the latest dosemu2 + fdpp git versions on a 64bit Linux host and trying to access files on various drives from the command prompt. 
While this test works fine for files on all "local" drives, it fails (ERROR: OFD_SETLK failed, Invalid argument) for files located on a "lredir" samba share.
 
Accessing these files from outside of dosemu2 on the Linux console works in all cases, therefore I'm pretty sure it is not a simple permission problem.

I'm also pretty sure that this setup worked before when  I last used it, which was unfortunately some years ago.

STR:
- setup Samba share on server and mount share on client
- create test file "test.txt" on dosemu drive_c and copy it to share
- start dosemu2 and lredir mount share to a free drive letter
- from command prompt, execute "type c:\test.txt" and "type driveletter:\test.txt"

Attached the boot log as requested:
[boot.log](https://github.com/dosemu2/dosemu2/files/10546288/boot.log)

**Comment by MaxPower2005** [comment]
It seems like the "start" parameter of "src/dosext/mfs/mfs.c:downgrade_dir_lock()" is off-limit and therefore fcntl(fd, F_OFD_SETLK, fl) fails with EINVAL.

**Comment by stsp** [comment]
No, off-limit is intensional and permitted.
You can try to force it to some artificial
value (like 0) and still get an error.
However, IIRC that error doesnt lead to
dosemu exit, so what doesn't work?
Yes, concurrent access will lead to a data
corruption, but otherwise you can just
ignore that error.
Technical explanation is that we abuse
ofd locks instead of writing a proper lock
manager, and your samba fs doesn't
support such. So just ignore an error and
avoid concurrent access, or help us
writing the lock manager by donating
the code or money. :)

**Comment by MaxPower2005** [comment]
> However, IIRC that error doesnt lead to dosemu exit, so what doesn't work?

I get a "File not found" error as show below:
![dosemu_error](https://user-images.githubusercontent.com/30479037/216035635-97906110-a91d-4c2d-99ed-1dc3fc59bed6.png)

> You can try to force it to some artificial value (like 0) and still get an error.

Ok, if I set `fl.l_start = /*start*/0;` in downgrade_dir_lock(), this problem is gone.

Unfortunately the next problem seems to be that the system waits forever in one of the `flock()` introduced in commit 39a09f6157ac8043513e035abbc9ffd6c42872da, so I have to revert it.
After that it seems to work
![dosemu_noerror](https://user-images.githubusercontent.com/30479037/216039087-93e50098-d1db-4888-9257-cc1af8a8383e.png)

**Comment by andrewbird** [comment]
Perhaps the 'nobrl' option when mounting the smb will help? See https://linux.die.net/man/8/mount.cifs

**Comment by MaxPower2005** [comment]
> Perhaps the 'nobrl' option when mounting the smb will help?

Yes, `nobrl` is an "alternative" to reverting the commit.

**Comment by stsp** [comment]
So in this case it should now be fixed.
Please let us know what kind of "fixed"
it is, i.e. do you need `nobrl` even with
that "fix"?

**Comment by MaxPower2005** [comment]
> Please let us know what kind of "fixed" it is, i.e. do you need nobrl even with that "fix"?

To "fix" the `flock` problem, I can either mount the Samba share with `nobrl` as suggested by @andrewbird  or revert commit 39a09f6157ac8043513e035abbc9ffd6c42872da.

**Comment by stsp** [comment]
So is this correct that fb0d52f fixes
the "File not found" problem and "nobrl"
fixes some dead-lock, so you need both?

**Comment by MaxPower2005** [comment]
> So is this correct that https://github.com/dosemu2/dosemu2/commit/fb0d52f183ce7157f6034e6138bb60840247cb8a fixes the "File not found" problem and "nobrl" fixes some dead-lock, so you need both?

Yes, exactly.

**Comment by stsp** [comment]
So without nobrl, byte-range locks contend
with flock() locks?
Very "interesting" semantic...
Someone should finally write a lock manager.
Hacking around existing locks was not a
future-proof approach.
