### ISSUE TITLE
CDROM multisession mixed data audio (The CD audio is not audible in the system now.)

### ISSUE THREAD

**Issue by ThingUroboros** [dosemu2/dosemu2#1895]
**Describe the bug**
A description of what the problem is.
The CD audio is not audible in the system now.

**To Reproduce**
"I tried all three methods of connecting mixed (data + audio) image."

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man d
[boot.log](https://github.com/dosemu2/dosemu2/files/10679001/boot.log)
osemu.bin`.

**A regression?**
https://github.com/dosemu2/dosemu2/issues/874

**Additional info**
I followed the same procedure as before here https://github.com/dosemu2/dosemu2/issues/874

**Comment by ThingUroboros** [comment]
The problem may be with the Linux version, if anything changed regarding CD audio. I know that it worked in some way, that it played directly in Linux using some system player. When I played the audio track and turned off dosemu2, the audio still played.

**Comment by stsp** [comment]
So the system player doesnt work too?

**Comment by stsp** [comment]
in linux

**Comment by ThingUroboros** [comment]
When I use rhythmbox, it works in linux, even if I play it in rhythmbox and then play dosemu, I see the same track timing and shift, but if I then switch the track in rhythmbox, it also switches it in dosemu in the player.

But when I do a track swap in dosemu, nothing changes in the system.

**Comment by stsp** [comment]
Please do:
`git checkout 27f02d5 src/dosext/drivers/cdrom.c src/dosext/mfs/mscdex.c`
and re-build.
This will return you to the cdrom
driver version which you reported
as working.
Does it work for you now?

**Comment by ThingUroboros** [comment]
It doesn't work, maybe a problem in the system, I will try the old version of ubuntu, but at night

**Comment by ThingUroboros** [comment]
I have problem on 
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa
and 
This system is OK.
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyssa

But is different notebooks

**Comment by ThingUroboros** [comment]
@stsp 
I find problem, cdemu must be 3.2.4 version. (cdemu-client 3.2.4 and cdemu-deamond 3.2.4) is correct

(cdemu-client 3.2.5 and cdemu-deamond 3.2.6) have problems

**Comment by stsp** [comment]
Good, have you reported that upstream?
Eventually we will support the cd images
without cdemu, but not soon.
