### ISSUE TITLE
revisit directory structure at $HOME

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1914]
There are certain problems with current
directory structure. We can install multiple
DOSes, but for that the wrapper script
manually relocates the following:
- drive_c
- imagedir
- .dosemurc
- boot.log

Why not to have a single option to relocate
the entire root of these dirs?
No, not quite that fast.
Eg ~/.dosemu/run is not relocatable because
it is used by dosdebug.

Now if we want to support "dexe" (a
convenient way of packaging dos progs),
then we'd need to not relocate also boot.log
as the "dexe" package should be not
too much writable.

It means that the current layout is wrong.
"run" could be somewhere in /var/run as
it is used by dosdebug. Log could be
somewhere in /var/log. And while we can
move "run" anywhere we want, logs are
not that simple because people got used
to ~/.dosemu/boot.log for years.

So I have that idea: move all relocatable
stuff into ~/.dosemu2, leaving the
non-relocatable stuff in ~/.dosemu for
compatibility. Then introduce just one
option to relocate everything, rather than
by the use of 10 options as now.

**Comment by stsp** [comment]
https://github.com/dosemu2/fdpp/issues/154#issuecomment-735765667
This comment also suggest to remove
the dot in a config file name.
Time to give that a re-spin?

**Comment by andrewbird** [comment]
Probably the best place for dosdebug temp files/pipes etc is in `/var/run/user/$uid/dosemu`, at least then stale ones will be managed without needing them to be tidied away as part of the `dosemu` startup script.

**Comment by stsp** [comment]
Good idea, way to go! :)
Would you like to provide a patch?
I am a bit busy for a month now with
writing a glibc support for my new tool-chain.
Already posted ~2/3 of the whole work
to glibc ML, got a few review replies, but
still no indication that they will take it. :(
So if you move dosdebug pipes in a mean
time, that would be great.

**Comment by stsp** [comment]
But the question will stay if we should
move also the logs, or occupy ~/.dosemu2?
And that's a difficult question, I have to say.

**Comment by stsp** [comment]
Probably moving the log and providing
a compatibility symlink (which may be
dangling at times) is a kinda relief?

**Comment by andrewbird** [comment]
> But the question will stay if we should
move also the logs, or occupy ~/.dosemu2?

I don't think you can move the log to /var/log as the user won't have permission to write there.

> Would you like to provide a patch?

Okay, can do but it won't be for a few days.

**Comment by stsp** [comment]
But /var/run/user seems like the good
place for logs as well, is it not?
/var/log doesn't seem to have the user
dir. And in fact, to my shame, I didn't
even know about /var/run/user - its a
very cool thing, when have it appeared?

**Comment by andrewbird** [comment]
> its a very cool thing, when have it appeared?

In the last five years I think.

> But /var/run/user seems like the good
place for logs as well, is it not?

Maybe, however distros either have that on tmpfs or they clear it out at each boot, so don't expect them to persist.

**Comment by andrewbird** [comment]
`/var/run/user` seems to be systemd created at user login.

**Comment by stsp** [comment]
/var/tmp or /tmp are also an options to
consider.

**Comment by stsp** [comment]
> /var/run/user seems to be systemd created at user login.

This is how every app eventually and
inevitably gets dependent on systemd. :)

**Comment by stsp** [comment]
I think we can ignore the log actually,
as it is always set up by the dosemu
wrapper script. So its default location
doesn't matter at all, it can as well be
no log by default (dosemu script will
nevertheless enable it).
So I think just moving "run" out would
already allow to relocate everything.
