### ISSUE TITLE
tasm32.exe produces runtime error

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#1923]
Hi Bart, seems to be a regression in
your patches.
To reproduce, do:
```
test/test_dos.py PPDOSGITTestCase.test_memory_emm286_borland
cd test-imagedir/dXXXXs/c
dosemu -K ./tasm32.exe
```

Result:
`kvm.c:622:21: runtime error: index 1024 out of bounds for type 'unsigned int [1024]'`
then lots of stack traces and the crash.

**Comment by bartoldeman** [comment]
I don't think it was my patch but e1ba0868b5   :) Anyway, very easy to fix fortunately.
