### ISSUE TITLE
Regression printing problem from dosemu2-2.0-pre8

### ISSUE THREAD

**Issue by boyin** [dosemu2/dosemu2#1927]
**Describe the bug**
dosemu2 crashes while printing PCL6 code between pages

**To Reproduce**
crashes when using the printing feature in CCE2, an ancient program printing documentation for bridge players.
To install/run CCE2, unzip cce2.zip inside drive_c, start dosemu2, go to the CCE directory and type pcc
CCE2 is a program that edits documentation for bridger players,
pcc prints out this documentation
when starting up, PCC offers you the choice between 2-sided or not, you can choose yes or no
then pick a document to print.  Dosemu2 then crashes in between the two pages of the document.

I usually set $_lpt1 to be 
 "/usr/local/bin/gpcl6 -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -o $HOME/Documents/$(date +%Y-%m-%d-%H:%M:%S).pdf -"  (I am using ghostpdl 10 in Ubuntu 22.04)

program faults and exists with 
ERROR: EMU86: error 2

**Attach program/game binaries or provide an URL**
If the problem needs specific DOS files to reproduce, please attach
or provide the download URL.

**Attach the log**
It is located in ~/.dosemu/boot.log
To make the log more useful, you may need to enable some logging flags.
See description of -D option in `man dosemu.bin`.

Note: I ran the command in the cce directory with

dosemu -D+a -K . -X -E pcc

**A regression?**
Used to work well on dosemu2-2.0-pre8
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/10846123/boot.log.zip)

**Additional info**
[cce2.zip](https://github.com/dosemu2/dosemu2/files/10846083/cce2.zip)
[dosemurc.zip](https://github.com/dosemu2/dosemu2/files/10846116/dosemurc.zip)

**Comment by stsp** [comment]
```
Warning: KVM: KVM_CREATE_VM: Device or resource busy
Warning: KVM not available: Device or resource busy
```
You have some problems with kvm.
As a work-around try `$_cpu_vm_dpmi="native"`
and provide the results.
I don't think its a regression.

**Comment by stsp** [comment]
Well, there is a regression too: 0e720ef09

**Comment by stsp** [comment]
Should now be fixed.
@bartoldeman do you know what can
be the problem with this FPU tag reset?
