### ISSUE TITLE
FR - "Silent" boot?

### ISSUE THREAD

**Issue by ryanfantus** [dosemu2/dosemu2#1929]
Hello, I was wondering if it would be possible to have some sort of "silent boot" flag - i.e., when I launch a program directly from the linux command line using the -E flag, it would be great to skip all the boot messages. Is this possible now?

Thanks!

**Comment by ecm-pushbx** [comment]
Try the `-quiet` switch.

**Comment by ryanfantus** [comment]
Thanks! Yeah, gave that one a shot, that actually made my DOS program fail to display any output as well, though, so doesn't seem like a solution for me :/

**Comment by ecm-pushbx** [comment]
That's a bug, it should display your application's output.

**Comment by ryanfantus** [comment]
What's expected behavior if I just run `dosemu -quiet` from a command line? Right now it displays nothing at all, is that correct?

**Comment by stsp** [comment]
Maybe you are loading ansi.sys at boot?

**Comment by ecm-pushbx** [comment]
Try `dosemu -dumb -td -kt -quiet -E 'c:\command.com'`, you have to pass something in `-E` in order to display things.

**Comment by ryanfantus** [comment]
Thanks, yeah, some things seem to work and others do not. Bummer. But I appreciate the help!
