### ISSUE TITLE
LFN: Improper case in int 21 0x7160 Long File Name TrueName.

### ISSUE THREAD

**Issue by severach** [dosemu2/dosemu2#1933]
**Describe the bug**
INT 21-7160h TrueName returns canonical file name in all uppercase. For a found file it should return the case of the found file. For a not found file and not found directories that the caller might create it should return the caller's case and length. Found directories that the caller would not create can be returned in any case or as SFN as they are now.

As found in #1926, MOVE.EXE from DOS 7 upper cases file names running in DOSEMU and uses the correct case when running under Windows XP. This is a bug in DOSEMU int 21 0x7160 [TrueName](http://www.ctyme.com/intr/rb-3206.htm). Ralf Brown says "and the final result uppercased without converting any remaining long-form names to short-form". This is not correct as can be seen with this demo. VC renames with the correct case in DOSEMU so it must not be using 0x7160-TrueName or it is fixing the name after TrueName.

**To Reproduce**
See demo.

```
Windows XP:
C:\Documents and Settings\Owner\My Documents>renmove abc def
0x71A0 Volume info for C:\
BX Flags  :  1-PCD 2-UNI 14-LFN
CX MaxLen = 255
DX MaxPath= 260
ES:DI Type= FAT32
f1: abc->C:\DOCUME~1\Owner\MYDOCU~1\abc
f2: def->C:\DOCUME~1\Owner\MYDOCU~1\def
```

```
DOSEMU:
C:\UTIL\RENMOVE>renmove.exe abc def
0x71A0 Volume info for C:\
BX Flags  :  1-PCD 14-LFN
CX MaxLen = 255
DX MaxPath= 260
ES:DI Type= MFS
f1: abc->C:\UTIL\RENMOVE\ABC
f2: def->C:\UTIL\RENMOVE\DEF
```

**Attach program/game binaries or provide an URL**
```
/* 2022-03-03 Borland C++ 3.1 Small */

#include <stdio.h>
#include <dos.h>
#include <mem.h>
#include <string.h>
#include <alloc.h>
#include <stdlib.h>

int g_LFN=0;
unsigned g_LFN_MAXPATH=0;
unsigned g_LFN_MAXFILE=0;

/* http://www.fysnet.net/longfile.htm */

#define GVP_SCS (1<<0)
#define GVP_PCD (1<<1)
#define GVP_UNI (1<<2)
#define GVP_LFN (1<<14)
#define GVP_CMP (1<<15)

static int detect_LFN(unsigned *maxpath,unsigned *maxfile) {
  union REGS regs;
  static char volume[]="C:\\";
  char vo[16];

  memset(&regs,0,sizeof(regs));
  memset(&vo,0,sizeof(vo));
  *maxpath=0;
  *maxfile=0;
  regs.x.ax = 0x71A0; /* Get Volume Info */
  regs.x.dx = FP_OFF(volume);
  regs.x.di = FP_OFF(vo);
  regs.x.cx = sizeof(vo)-1;
  regs.x.cflag = 1; /* force the call to clear this */
  intdos(&regs,&regs);
  if (regs.x.cflag==0) {
    *maxfile=regs.x.cx;
    *maxpath=regs.x.dx;
#if 1
    printf(
      "0x71A0 Volume info for %s\n"
      "BX Flags  : %s%s%s%s%s\n"
      "CX MaxLen = %u\n"
      "DX MaxPath= %u\n"
      "ES:DI Type= %s\n",
      volume,
      (regs.x.bx&GVP_SCS)?" 0-SCS":"",
      (regs.x.bx&GVP_PCD)?" 1-PCD":"",
      (regs.x.bx&GVP_UNI)?" 2-UNI":"",
      (regs.x.bx&GVP_LFN)?" 14-LFN":"",
      (regs.x.bx&GVP_SCS)?" 15-CMP":"",
      regs.x.cx,regs.x.dx,vo
    );
#endif
    return((regs.x.bx&GVP_LFN)!=0);
  } else {
#if 1
    printf(
      "0x71A0 Volume info for %s\n"
      "AX Error = 0x%X\n",
      volume,regs.x.ax);
#endif
  }
  return(0);
}

static unsigned truename_LFN(const char *oldpath,char *newpath,unsigned char typ) {
  union REGS regs;

  memset(&regs,0,sizeof(regs));
  memset(newpath,0,g_LFN_MAXPATH+1);
  regs.x.ax = 0x7160;
  regs.h.cl = typ;
  regs.h.ch = 0; /* subst */
  regs.x.si = FP_OFF(oldpath);
  regs.x.di = FP_OFF(newpath);
  regs.x.cflag = 1; /* force the call to clear this */
  intdos(&regs,&regs);
  return regs.x.cflag?regs.x.ax:0;
}

static int rename_LFN(const char *oldname, const char *newname) {
  return(0);
}

static int move(const char *f1,const char *f2) {
  char *f1l=malloc(g_LFN_MAXPATH+1),*f2l=malloc(g_LFN_MAXPATH+1);
  if (f1l && f2l) {
    truename_LFN(f1,f1l,0);
    truename_LFN(f2,f2l,0);
    printf("0x7160\nf1: %s->%s\nf2: %s->%s\n",f1,f1l,f2,f2l);
  }
  if (f1l) free(f1l);
  if (f2l) free(f2l);
  return(0);
}

int main(int argc,char *argv[]) {
  g_LFN=detect_LFN(&g_LFN_MAXPATH,&g_LFN_MAXFILE);
  if (argc==3) {
    return move(argv[1],argv[2]);
  }
  return(1);
}
```

**Comment by andrewbird** [comment]
It seems I was suspicious of that when I wrote the LFN tests
https://github.com/dosemu2/dosemu2/blob/d799f2758ff7ff65b0c1a0e61c165632d21a2446/test/test_dos.py#L3517-L3530

**Comment by stsp** [comment]
So do you take this up? :)

**Comment by andrewbird** [comment]
Yes, I'm just rewriting the test first though.

**Comment by andrewbird** [comment]
@severach if you do int21/0x7160/0 with input `nonExist\NewFile` what do you get on XP (if it isn't obvious :smile:, the directory 'nonExist' doesn't exist)?

**Comment by severach** [comment]
Windows XP. Would be good to try these in Win95-WinMe,2000 and the real mode LFN DOS emulators to see where this capitalization claim comes from and to check for minor differences. I think Windows XP chooses the SFN to make it more likely that the path will fit in the 260 character limit. This is only possible on a filesystem that reliably stores the SFN.

```
C:\DOCUME~1\Owner\MYDOCU~1>renmove Folder12\fIle344 fOlder1234\FiLe35258
0x7160
f1: Folder12\fIle344->C:\DOCUME~1\Owner\MYDOCU~1\Folder12\fIle344
f2: fOlder1234\FiLe35258->C:\DOCUME~1\Owner\MYDOCU~1\fOlder1234\FiLe35258
```

Non existent files and folders return the caller's case and length.

```
C:\DOCUME~1\Owner\MYDOCU~1>mkdir XyZZy35228

C:\DOCUME~1\Owner\MYDOCU~1>echo > XyZZy35228\DOSEmuDOSEmulator

C:\DOCUME~1\Owner\MYDOCU~1>renmove a\a XYZZY35228\DOSEMUDOSEMULATOR
0x7160
f1: a\a->C:\DOCUME~1\Owner\MYDOCU~1\a\a
f2: XYZZY35228\DOSEMUDOSEMULATOR->C:\DOCUME~1\Owner\MYDOCU~1\XYZZY35228\DOSEMUDOSEMULATOR
```

Files and folders that do exist return the caller's case, not the file case as I had hoped. This is easier to program as the callers files and folders are not inspected.

```
C:\DOCUME~1\Owner\MYDOCU~1>renmove ..\test ..\..\test2
0x7160
f1: ..\test->C:\DOCUME~1\Owner\test
f2: ..\..\test2->C:\DOCUME~1\test2

C:\DOCUME~1\Owner\MYDOCU~1>renmove .\..\test .\.\..\..\..\test2
0x7160
f1: .\..\test->C:\DOCUME~1\Owner\test
f2: .\.\..\..\..\test2->C:\test2

C:\DOCUME~1\Owner\MYDOCU~1>renmove a\..\b\..\c\..\d a\.\b\.\c\..\d
0x7160
f1: a\..\b\..\c\..\d->C:\DOCUME~1\Owner\MYDOCU~1\d
f2: a\.\b\.\c\..\d->C:\DOCUME~1\Owner\MYDOCU~1\a\b\d

C:\DOCUME~1\Owner\MYDOCU~1>renmove c:x\y c:z
0x7160
f1: c:x\y->C:\DOCUME~1\Owner\MYDOCU~1\x\y
f2: c:z->C:\DOCUME~1\Owner\MYDOCU~1\z

C:\DOCUME~1\Owner\MYDOCU~1>renmove ..\..\..\..\..\..\a b
0x7160
f1: ..\..\..\..\..\..\a->C:\a
f2: b->C:\DOCUME~1\Owner\MYDOCU~1\b
```

Looks like TrueName's main job is to fill in drive letters, CWD, and resolve embedded .\ and ..\ 

Going too far doesn't seem to matter.

```
C:\DOCUME~1\Owner\MYDOCU~1>echo Cast it into the fire > Isuldir

C:\DOCUME~1\Owner\MYDOCU~1>renmove a\ring ISULDIR\NO
0x7160
f1: a\ring->C:\DOCUME~1\Owner\MYDOCU~1\a\ring
f2: ISULDIR\NO->C:\DOCUME~1\Owner\MYDOCU~1\ISULDIR\NO
```

Truename doesn't care if we try to use a file as a folder or misspell Isildur.

```
C:\DOCUME~1\Owner\MYDOCU~1>renmove ...\c ....\d
0x7160
f1: ...\c->C:\DOCUME~1\Owner\MYDOCU~1\..\c
f2: ....\d->C:\DOCUME~1\Owner\MYDOCU~1\...\d

C:\DOCUME~1\Owner\MYDOCU~1>renmove ...X\c ....Y\d
0x7160
f1: ...X\c->C:\DOCUME~1\Owner\MYDOCU~1\...X\c
f2: ....Y\d->C:\DOCUME~1\Owner\MYDOCU~1\....Y\d
```

Looks like it trims unused trailing separator dots. This seems sketchy. Microsoft isn't good about writing test cases. One time I went looking for CommandLineToArgvA and only found the wide version CommandLineToArgvW. So I rewrote it using the Microsoft function as the right answer for the test cases. I made so many test cases that I found case classes where Microsoft's code was wrong. I had to exclude the test cases with bad results.

Fortunately this doesn't matter since Windows does not allow me to make files or folders like "....".

```
C:\DOCUME~1\Owner\MYDOCU~1>renmove \\server\share\foo \\client\sh\bar.
0x7160
f1: \\server\share\foo->\\server\share\foo
f2: \\client\sh\bar.->\\client\sh\bar

C:\DOCUME~1\Owner\MYDOCU~1>renmove \\ \\x
0x7160
f1: \\->\\
f2: \\x->\\x
```

Looks like network access is recognized and returned with only minor modifications.

In my old DOS days (Feb 2001) DOS TrueName-SFN was an undocumented function so I had written my own that also included trailing slash and wildcard assist. I'm looking through the test cases to find oddballs.

```
C:\DOCUME~1\Owner\MYDOCU~1>renmove c:\\foo\\bar zee\\\zoo
0x7160
f1: c:\\foo\\bar->c:\foo\bar
f2: zee\\\zoo->C:\DOCUME~1\Owner\MYDOCU~1\zee\zoo
```

Looks like it cleans up repeated slashes, usually created with vars in bat files: `%DIR%\%FILE%` where DIR may or may not have a trailing slash.

```
C:\DOCUME~1\Owner\MYDOCU~1>renmove d: C:
0x7160
f1: d:->
f2: C:->C:\DOCUME~1\Owner\MYDOCU~1

C:\DOCUME~1\Owner\MYDOCU~1>renmove c:.\ c:.
0x7160
f1: c:.\->C:\DOCUME~1\Owner\MYDOCU~1\
f2: c:.->C:\DOCUME~1\Owner\MYDOCU~1
```

Missing drive letters are dealt with rather harshly. Just drive letters are left without a trailing slash. DOSEMU also blanks the missing drive but includes a trailing slash on valid drives. Looks like we can find cases where the trailing slash is included.

```
C:\DOCUME~1\Owner\MYDOCU~1>renmove a/b c/d
0x7160
f1: a/b->C:\DOCUME~1\Owner\MYDOCU~1\a\b
f2: c/d->C:\DOCUME~1\Owner\MYDOCU~1\c\d
```

Mysteriously forward slashes are converted to backslashes. DOSEMU does this too.

Windows CMD won't launch a DOS program with a file long enough to test the 260 character limit. I had to add some lines.

```
#if 1
    char lng[384];
    memset(lng,0,sizeof(lng));
    memset(lng,'a',sizeof(lng)-1);
    truename_LFN(lng,f1l,0);
    printf("0x7160\nlng: %s->%s\n",lng,f1l);
#endif

C:\DOCUME~1\Owner\MYDOCU~1>renmove a/b c/d
0x7160
lng: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa->
0x7160
f1: a/b->C:\DOCUME~1\Owner\MYDOCU~1\a\b
f2: c/d->C:\DOCUME~1\Owner\MYDOCU~1\c\d
```

Looks like too long names are discarded. Same with DOSEMU. What happens when we add more lines to break this up?


```
#define OFS (191)
    lng[OFS+0]='\\';
    lng[OFS+1]='.';
    lng[OFS+2]='.';
    lng[OFS+3]='\\';
C:\DOCUME~1\Owner\MYDOCU~1>renmove a\b c\d
0x7160
lng: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\..\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa->
0x7160
f1: a\b->C:\DOCUME~1\Owner\MYDOCU~1\a\b
f2: c\d->C:\DOCUME~1\Owner\MYDOCU~1\c\d
```

This resolves to a destination of less than 256. DOSEMU handles this. Windows XP does not. What did I tell you about Microsoft's ability to write test cases!

Let's move the .. ahead to see how far we can take this.

```
#define OFS (272)
```

Neither DOSEMU nor Windows XP can do this one. I made it into a for() loop to see where it fails.

DOSEMU: With a CWD of C:\UTIL\RENMOVE\ "aaa\..\aaa" fails at 241. `16 character CWD+a241+"\.." = 260`. The next character \ would have reset the count back to 16 but DOSEMU ran out of space.

**Comment by ecm-pushbx** [comment]
> Looks like it trims unused trailing separator dots. This seems sketchy.

Trailing dots are never written to the disk by DOS or MSW, neither in SFNs nor LFNs. The `*.*` wildcard can match a nonexistent trailing dot that the DOS pretends to be there, if a filename doesn't have any dot at all. It may be valid to pass in a name with trailing dots but it actually accesses the on-disk name with all trailing dots truncated away.

MSW 4.x (95/98/Me) does, by the way, allow a three dots `...` directory name which is resolved like two dotdots, or four dots `....` which is resolved like three dotdots.

**Comment by andrewbird** [comment]
So I've been running some tests on Win98, and can already see some differences from the report on WinXP. I see 
~~~
# So on Win98 LFN 7160/0 seems to have the following rules                   
# 1/ Any '..\' are resolved                                          
# 2/ Any '.\' are stripped                                          
# 3/ If no drive specification then default drive is prepended     
# 4/ If not absolute path, then current directory for drive is inserted between drive and relative path
# 5/ All path components (except final) are upcased
# 6/ Final path component case is preserved from the request        
# 7/ No path component has to exist on the filesystem               
~~~

I have to repeat the same tests on WinXP, but from the tests that @severach did before the WinXP seems a little more sane. For instance he had `Owner` which is mixed case so is LFN (although less than or equal to 8 chars) in the current directory path, and it wasn't upcased along with the SFN components, presumably because it represented the case of the actual directory.
