### ISSUE TITLE
Polish locale

### ISSUE THREAD

**Issue by Nobody-Special** [dosemu2/dosemu2#1969]
**Describe the bug**
Missing locale support for "pl_PL".

**To Reproduce**
1. Set `LANG` to `pl_PL.UTF_8` in `/etc/locale.conf`
2. Run `dosemu`
3. Stdout: `ERROR: Can't find codepage for "pl_PL.UTF-8". Please add the mapping to locales.conf and send patch.`

**Attach program/game binaries or provide an URL**
Not applicable.

**Attach the log**
Not applicable.

**A regression?**
No.

**Additional info**
Not applicable.

**Proposed solution**
Add `{ "lang": "pl_PL", "codepage": "cp852", "country": 048 },` at the 64 line in `etc/locales.conf`.

**Comment by stsp** [comment]
Ok, thanks, I added that.
