### ISSUE TITLE
Too slow while accessing NFS share

### ISSUE THREAD

**Issue by nnn19** [dosemu2/dosemu2#1990]
As of now, DOSEmu 2 is much more perfect on running applications and we could migrate from DOSEmu now but with one single glitch.

Unlike DOSEmu, DOSEmu 2 is too slow while accessing NFS share with same set of configurations.

Emu 2 outperforms earlier Emu while accessing local storage / data (for sure).

But while accessing NFS share, Emu 2 is too slow and in the same setup / server / nodes, another node with earlier Emu performs very well.

Any tweaking needed under Emu 2 configuration ?

**Comment by stsp** [comment]
Try running `speed 0`

**Comment by jharrison03** [comment]
How are you accessing the shares?  I have NFS speed issues too, but I'm accessing the shares through a Netware 4.2 NFS Gateway, which exports these NFS shares as Netware volumes on the client (so I'm not sure where the speed issues are coming from - but It's somehow related to DOSEMU as it doesn't happen under something like Windows under QEMU.  Actual Netware shares don't have the drastic slowdown that is observed on the NFS shares.

Just doing something like 'DIR' on my exported home directory is extremely slow.

**Comment by nnn19** [comment]
@stsp there is no change with speed settings.
@jharrison03 I am directly accessing lredir-ed NFS Shares. Both server and client runs linux. 
The slowness does not exist with earlier DOSEmu.

**Comment by stsp** [comment]
Try mounting with nolock option.

**Comment by jharrison03** [comment]
On the NFS server?  That's not a valid option.

EDIT:  Disregard that...  It's probably not valid because I'm running as NFSv2 so the Netware portion can communicate with it.

**Comment by nnn19** [comment]
Yes. Both with DOSEmu and DOSEmu2, the NFS Share is mounted with nolock.

**Comment by nnn19** [comment]
Will a strace output for DOSEmu2 - entering into and loading a data file from NFS will help?

**Comment by stsp** [comment]
If you can analyze such output and
try to identify the problem from it, then
of course its helpful.
You can also use `dosemu -perf` to
generate the data for `perf` tool.

**Comment by nnn19** [comment]
OpenSUSE Server with NFS Share (noac,nolock)
mounted to Ubuntu  22.04  LTS
running dosemu2   2.0~pre9-7779-8e52b75ae+202212181901~ubuntu22.04.1 amd64

strace dosemu  
[d-strace-full.txt](https://github.com/dosemu2/dosemu2/files/11343879/d-strace-full.txt)

dosemu  -perf 
[d-perf.txt](https://github.com/dosemu2/dosemu2/files/11343882/d-perf.txt)

Advise how I can help by reviewing the strace output.

**Comment by stsp** [comment]
Your strace traces bash because
you haven't specified `-f`. Also it lacks
timestamps as you haven't used `--timestamps`.
Perf doesn't write into a log but in a
separate file.

Your best bet would be to give me an
ssh access with a short instructions of
how to reproduce the bug, as its very
unlikely that you'll be able to use these
tools on your own.

**Comment by stsp** [comment]
But before anything else, you could note
that your log is full of xattrs errors.
You need to enable xattrs first,
with the "user_xattr" mount option.

**Comment by stsp** [comment]
Actually it seems you need to pass
"user_xattr,vers=4.2" options..

**Comment by stsp** [comment]
And it seems you need a kernel-5.9 or
more recent for nfs4.2 support.

**Comment by andrewbird** [comment]
> Actually it seems you need to pass
"user_xattr,vers=4.2" options..

I think it's default once you have a kernel that supports it, both on the server and client. Since updating my server to Ubuntu 22.04.2 all my xattr warnings went away.

**Comment by stsp** [comment]
On nfs?

**Comment by andrewbird** [comment]
Yep

**Comment by stsp** [comment]
Is it shown in mount options
displayed by `mount`?

**Comment by andrewbird** [comment]
~~~
oliver:/export/clients on /clients type nfs4 (rw,relatime,vers=4.2,rsize=524288,wsize=524288,namlen=255,
hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.3.57,local_lock=none,addr=192.168.3.45)
~~~

**Comment by nnn19** [comment]
@stsp  Yes. I will set xattr at nfs client. The site uses good old Linux Server (very hard to upgrade it  - atleast not for the time being).

Giving access for that site's server / client will take time.

Secondly do you mean strace -f -r dosemu.

If so, I shall ask a person at site to give the output of the same.

**Comment by stsp** [comment]
I usually attach strace to the running
dosemu instance with `-r -p <pid> -o log`.
In that case -f may not be needed.

Please show your `mount` output.

**Comment by stsp** [comment]
@andrewbird user_xattr is not seen in your msg.
If you set it and `nolock` then would they show up?

**Comment by andrewbird** [comment]
I don't know, but I read on the Internet that `user_attr` doesn't show up in mount options as it's the default. It obviously works, see
~~~
$ attr -l test-imagedir/dXXXXs/d/*
Attribute "DOSATTRIB" has a 5 byte value for test-imagedir/dXXXXs/d/shrtname.txt

$ df test-imagedir/dXXXXs/d/shrtname.txt
Filesystem             1K-blocks      Used Available Use% Mounted on
oliver:/export/clients 245813760 188081664  46160384  81% /clients

$ grep oliver:/export/clients /proc/$$/mounts
oliver:/export/clients /clients nfs4 rw,relatime,vers=4.2,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.3.57,local_lock=none,addr=192.168.3.45 0 0
~~~~

**Comment by stsp** [comment]
OK, good to know.
Will nolock show?

**Comment by andrewbird** [comment]
Oh yes, and I tried `nolock` on a test mount and although the mount command took the option, nothing extra appeared in mount entry.
~~~
oliver:/export/clients on /a type nfs4 (rw,relatime,vers=4.2,rsize=524288,wsize=524288,namlen=255,hard,
proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.3.57,local_lock=none,addr=192.168.3.45)
~~~

**Comment by stsp** [comment]
That's interesting!
Probably nolock doesn't work when
you specify local_lock?
So `local_lock=all` is supposed to be
faster, is it not?

**Comment by andrewbird** [comment]
Nfsv4 is new to me, but Internet seems to suggest that lock/nolock/local_lock=* are v2/v3 options and ignored on v4.

**Comment by stsp** [comment]
How weird.
But in that case you can use
`local_lock=all,vers=3`?

**Comment by andrewbird** [comment]
Yes, but then no xattrs, I suppose
~~~
# mount -o vers=3,local_lock=all oliver:/export/clients /a
Created symlink /run/systemd/system/remote-fs.target.wants/rpc-statd.service → /lib/systemd/system/rpc-statd.service.

# grep oliver:/export/clients /proc/$$/mounts

oliver:/export/clients /a nfs rw,relatime,vers=3,rsize=524288,wsize=524288,namlen=255,hard,
proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.3.45,mountvers=3,mountport=34668,
mountproto=udp,local_lock=all,addr=192.168.3.45 0 0

~~~

**Comment by stsp** [comment]
But he doesn't have an xattrs even now. :)

So.
@nnn19 could you please try "vers=3,local_lock=all"
options and post the output of a `mount` command?

**Comment by andrewbird** [comment]
I guess we should ask @nnn19 whether the files on the server are being accessed from multiple nfs client machines?

**Comment by stsp** [comment]
Maybe, but after we identify that
locks are giving the performance
problems.
Also I wouldn't expect that matters,
as if he also has the windows machine,
then the share modes are not
coordinated with dosemu anyway,
even if you promote locking.
Note that nfsv4 actually supports the
share modes directly! But they are
not exposed in linux, and no client-side
library to access them via network.

**Comment by nnn19** [comment]
The /etc/fstab line (in the DOSEmu2 machine)

10.0.0.100:/home/user1/data/g	/mnt/g	nfs	defaults,auto,tcp,noac,nolock	0 0

The mount output for the NFS share (for the DOSEmu2 machine) as it is since it was installed...

10.0.0.100:/home/user1/data/g on /mnt/g type nfs (rw,relatime,sync,vers=3,rsize=1048576,wsize=1048576,namlen=255,acregmin=0,acregmax=0,acdirmin=0,acdirmax=0,hard,noac,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.0.0.100,mountvers=3,mountport=20048,mountproto=tcp,local_lock=all,addr=10.0.0.100)

Yes. It has vers=3 and local_lock=all already.

Yes. The OpenSUSE Server's NFS share is concurrently used by several Linux nodes - they all run DOSEmu (32 Bit) and essentially we are keeping all those Linux at an earlier version to make older DOSEmu run. Now (as DOSEmu2 is ready) I am trying to migrate to newer versions.

**Comment by stsp** [comment]
Is your problem specific to nfs, i.e.
is it fast on local fs?

**Comment by nnn19** [comment]
Yes. Yes.  

DOSEmu2 is much more faster than DOSEmu when all the files and the application are available in local Linux machine. Great speed. Great performance - Reports are all faster.

And DOSEmu2 is much slower than DOSEmu when all the files and the application are from NFS Share.

**Comment by andrewbird** [comment]
@nnn19 so are your multiple nfs clients accessing the same file set of files on the server. If so, with dosemu1 have you experienced file corruption due to simultaneous access?

**Comment by stsp** [comment]
OK so if its not locking then remaining
thing can be xattrs. You can use fuse_xattrs
https://stackoverflow.com/questions/24629459/how-to-use-extended-file-attributes-on-nfs
for xattrs emulation. See if all errors are
then gone from the log.

**Comment by nnn19** [comment]
@andrewbird  Yes. There are several clients accessing same set of data files.  We had developed the software which handles the files with an option set and reviewed by other clients and hence avoids data corruption - This is running for 2+ decades.

Now, we are developing in LAMP. But still maintaining our customers who still uses our older technology. We also give HTML outputs, CSV outputs, JSON outputs, etc from our Text Application itself.

**Comment by nnn19** [comment]
@stsp - Yes and thanks. I will try tomorrow morning with my customer machine. It is 9:25 p.m. here.

**Comment by stsp** [comment]
dosemu2 has locking support, so you'd
need no work-arounds to avoid data
corruption. Although in this case the
nfs locks should be remote, not local,
which will probably be even slower. :)

**Comment by nnn19** [comment]
Can not be. We still use File locking and Record locking in client side Text Application. In addition we set a flag and review.

To note...the same program runs much faster in DOSEmu.

Also to note...the DOSEmu2 shows slowness even for just loading the FOXPro itself - much before our application itself is loaded.

**Comment by nnn19** [comment]
@andrewbird   We still use File locking and Record locking in client side Text Application. In addition we set a flag and review.

**Comment by nnn19** [comment]
@stsp  Do you say, DOSEmu's own locking might be the reason for the slowness? If so, it would also slow down just loading of FOXPro itself.  Is this right?

**Comment by stsp** [comment]
Its not "own locking", its just
that the "File locking and Record
locking in client side Text Application"
simply doesn't work in dosemu1,
but does in dosemu2. So no additional
"flag and review" would be needed.

The locking is probably not the reason
of slowness if you make them local on
an nfs level w/o any improvement.

**Comment by nnn19** [comment]
Ok. So, this gives the reason. Anyway, I will try xattr, etc tomorrow morning and post further.

**Comment by nnn19** [comment]
And as per the need...I will create ssh access for you.

**Comment by stsp** [comment]
> And as per the need...I will create ssh access for you.

This didn't seem to materialize.
