### ISSUE TITLE
ERROR: cpu exception in dosemu code outside of DPMI client!

### ISSUE THREAD

**Issue by Syndel-Markus** [dosemu2/dosemu2#1995]
dosemu fails to start

After installing the build I tried the following:

`dosemu`

and

`dosemu -2 -dumb`

Both gave out the same error.

[boot.log](https://github.com/dosemu2/dosemu2/files/11299578/boot.log)
[dosemu.conf.txt](https://github.com/dosemu2/dosemu2/files/11299581/dosemu.conf.txt) <-file extension changed to be able to upload.

Besides small changes to the attached config file, no other modifications have been made.  No other programs were involved.

**Comment by stsp** [comment]
Hi Bart.

The crash happens because of division
by zero at fp87-sim.c:646:
`case 0x7e: WFR1 /= WFR0; break;`
Could you please take a look?

**Comment by bartoldeman** [comment]
This is on arm, important detail.. I'll try to follow the backtrace to see what is going on here.

**Comment by stsp** [comment]
```
qemu-system-arm -M virt \
    -kernel ./vmlinuz-5.17.5-300.fc36.armv7hl \
    -initrd ./initramfs-5.17.5-300.fc36.armv7hl.img \
    -m 2G \
    -append "root=UUID=5780470e-61ea-46ef-bf37-0de8af2e89f2 ro console=ttyAMA0 rootwait rd.plymouth=0 plymouth.enable=0" \
    -netdev type=user,id=net0 -device e1000,netdev=net0 \
    -drive file=Fedora-Minimal-36-1.5.armhfp.raw,format=raw,id=hd,if=none \
    -device virtio-blk-device,drive=hd \
    -monitor none \
    -smp 4
```

This is a setup for an ARM vm.
Fedora-Minimal-36-1.5.armhfp is available
for download from fedora site.
But I am still struggling with building comcom32
for that fedora... But you can bypass that
step and use freecom instead.
There is a gotcha in that fedora image:
on the first run it presents a small
text-based setup menu that has root
account disabled and "add admin user"
step unselected. If you naively continue,
you'll need to delete an image and try
again, as there seem to be no recover
from such a wonderful defaults...

**Comment by bartoldeman** [comment]
I didn't test but #1998 should fix it, and it should be done in any case.
