### ISSUE TITLE
Dosemu2 won't compile under Devuan 4/Debian 11

### ISSUE THREAD

**Issue by TerryTRSPanda** [dosemu2/dosemu2#2000]
**Describe the bug**
I ran make deb as instructed in the wiki and I have a build error and I think it might be related to the previous error I had with commandcom32 

**To Reproduce**
Follow the debian build instruction in debian

`---------------------------------DONE Installing-------------------------------

  - You can type 'dosemu' to run DOSEMU2.
make[2]: Leaving directory '/home/user/src/dosemu2/build/src'
make[1]: Leaving directory '/home/user/src/dosemu2/build'
   dh_install -O--builddirectory=build
   dh_installdocs -O--builddirectory=build
   dh_installchangelogs -O--builddirectory=build
   dh_installman -O--builddirectory=build
   dh_installinit -O--builddirectory=build
   dh_installsystemduser -O--builddirectory=build
   dh_perl -O--builddirectory=build
   dh_link -O--builddirectory=build
   dh_installxfonts -O--builddirectory=build
   dh_strip_nondeterminism -O--builddirectory=build
   dh_compress -O--builddirectory=build
   dh_fixperms -O--builddirectory=build
   dh_missing -O--builddirectory=build
   dh_strip -O--builddirectory=build
   dh_makeshlibs -O--builddirectory=build
   debian/rules override_dh_shlibdeps
make[1]: Entering directory '/home/user/src/dosemu2'
dh_shlibdeps -X.so
dh_shlibdeps -- -dRecommends -pshlibs-
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/fdpp/libfdpp.so.32.9 (used by debian/dosemu2/usr/lib/dosemu/libplugin_fdpp.so)
Hint: check if the library actually comes from a package.
dh_shlibdeps: error: dpkg-shlibdeps -Tdebian/dosemu2.substvars -dRecommends -pshlibs- debian/dosemu2/usr/bin/mkfatimage16 debian/dosemu2/usr/bin/dosdebug debian/dosemu2/usr/bin/dosemu.bin debian/dosemu2/usr/lib/dosemu/libplugin_fluidsynth.so debian/dosemu2/usr/lib/dosemu/libplugin_fdpp.so debian/dosemu2/usr/lib/dosemu/libplugin_json.so debian/dosemu2/usr/lib/dosemu/libplugin_sdl.so debian/dosemu2/usr/lib/dosemu/libplugin_libao.so debian/dosemu2/usr/lib/dosemu/libplugin_console.so debian/dosemu2/usr/lib/dosemu/libplugin_XKmaps.so debian/dosemu2/usr/lib/dosemu/libplugin_alsa.so debian/dosemu2/usr/lib/dosemu/libplugin_term.so debian/dosemu2/usr/lib/dosemu/libplugin_ladspa.so debian/dosemu2/usr/lib/dosemu/libplugin_gpm.so debian/dosemu2/usr/lib/dosemu/libplugin_X.so debian/dosemu2/usr/lib/dosemu/libplugin_lpt.so debian/dosemu2/usr/lib/dosemu/libplugin_slirp.so returned exit code 25
dh_shlibdeps: error: Aborting due to earlier error
make[1]: *** [debian/rules:20: override_dh_shlibdeps] Error 25
make[1]: Leaving directory '/home/user/src/dosemu2'
make: *** [debian/rules:7: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed
make: *** [Makefile:65: deb] Error 29
`

**Comment by skitt** [comment]
As mentioned previously, you need to delete `/usr/local/lib/fdpp` and restart the build.

**Comment by TerryTRSPanda** [comment]
Oh sorry, I though it would be more organized here, but I have the same issue even after doing as instructed, but I'll close this one and go back to the other issue that I'll link here so it can be less fragmented.


https://github.com/dosemu2/comcom32/issues/70#issuecomment-1519400300

**Comment by TerryTRSPanda** [comment]
Eh, eff it, I'm reopening, it was already closed in the previous thread, so I reopened it and I tried removing fdpp and reinstalling it and got the same error.

**Comment by stsp** [comment]
Please, stay focused.
All your logs contain the references
to `/usr/local/lib/fdpp`. This means
you install it with `make install`,
instead of from the deb package built
with `make deb`.
So you were suggested to first do
`make uninstall` and then reinstall,
but from the package! Not with another
`make install`. After which you need
to rebuild the dosemu2 package, and
re-install in, but again, not with
`make install` or alike.

**Comment by TerryTRSPanda** [comment]
so make install for everything and skip the deb building and checkinstall?

**Comment by TerryTRSPanda** [comment]
Thank you, doeemu works beautifully
