### ISSUE TITLE
New warning

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#2002]
~~~
In file included from dnative.c:24:
/dosemu2.git/src/base/lib/libpcl/pcl.h:45:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if WANT_UCONTEXT
    ^
/dosemu2.git/src/base/lib/libpcl/pcl.h:36:43: note: expanded from macro 'WANT_UCONTEXT'
#define WANT_UCONTEXT (_WANT_UCONTEXT || !defined(MCONTEXT))
                                          ^
~~~

**Comment by stsp** [comment]
Defined produces undefined...
Where have you got that warning?
Fixed.

**Comment by andrewbird** [comment]
> Where have you got that warning?

Ubuntu 22.04 (clang 14)

**Comment by stsp** [comment]
Ah I forgot we still use clang under ubuntu
by default because of some debian-specific
problems in the past, but at home I am using
gcc...
Well, so I am currently fighting in clang
bugzilla against the (harmful to fdpp) changes
in clang-16. If I won't succeed, we'll get back
to gcc by default.
