### ISSUE TITLE
-perf gives an error

### ISSUE THREAD

**Issue by nnn19** [dosemu2/dosemu2#2003]
**Describe the bug**
dosemu -perf gives an error

**To Reproduce**
Ubuntu Mate 20.04.6
dosemu2   2.0~pre9-8022-4a338810d+202304211816~ubuntu20.04.1 amd64 

dosemu -perf
/usr/bin/dosemu: line 225: exec: perf: not found

Line 225 has
DPID="$(echo "$BASHPID"; exec 1<&3; exec $COMMAND -L "Command line: `echo $COMMAND | tr -s ' '`" "$@")"

**Attach the log**
[d-strace-perf.txt](https://github.com/dosemu2/dosemu2/files/11344031/d-strace-perf.txt)

**A regression?**
Not for older dosemu.
BUT this error **does not** come in
20221218 build
dosemu2   2.0pre9-7779-8e52b75ae+202212181901ubuntu22.04.1 amd64

**Comment by stsp** [comment]
If perf not found, then install perf.

**Comment by nnn19** [comment]
which perf
returns nothing both in Ubuntu 22.04 machine and Ubuntu Mate 20.04 machine.

Which utils will provide this?

dosemu -perf runs well in Ubuntu 22.04 which has 
2.0pre9-8022-4a338810d+202304211816ubuntu20.04.1 amd64
build.

And dosemu -perf returns 
/usr/bin/dosemu: line 225: exec: perf: not found
in Ubuntu Mate 20.04 which has 
2.0pre9-7779-8e52b75ae+202212181901ubuntu22.04.1 amd64
build.

**Comment by stsp** [comment]
```
$ dpkg-query -S `which perf`
linux-tools-common: /usr/bin/perf
```

Anyway, I don't think you'll be
using this tool or a strace, so I
guess we'll end up with ssh.
