### ISSUE TITLE
DOSLFN not working with MSDOS 6.22

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#2004]
**Describe the bug**
Similar to https://github.com/dosemu2/fdpp/issues/221 but with MS-DOS 6.22. I think this means that our LFN code is being authoritative over a FAT drive.
~~~
C:\>testit
 
C:\>c:\doslfn -f-
DOSLFN 0.41f (haftmann#software & jmh 4/2022): switch(es) taken
 
C:\>d:
 
D:\>c:\lfnvinfo D:\
ERRNO(27)
 
D:\>rem end
 ~~~

**To Reproduce**
`test/test_dos.py MSDOS622TestCase.test_lfn_volume_info_fat16` using the branch I have at https://github.com/andrewbird/dosemu2/tree/lfn-problem

**Attach program/game binaries or provide an URL**
Alternatively I have the extracted to simple test case [t1.zip](https://github.com/dosemu2/dosemu2/files/11357616/t1.zip). run as follows
```bin/dosemu -n -f test-imagedir/dosemu.conf -o test.log --Fimagedir `pwd`/test-imagedir``` then once in the dos environment, run the batchfile `testit`

**Attach the log**
[t2.zip](https://github.com/dosemu2/dosemu2/files/11357633/t2.zip)

**A regression?**
Not sure but unlikely as I never tested with doslfn before.

**Additional info**

**Comment by andrewbird** [comment]
I did a little debugging with a dosdebug and can see that the doslfn handler is run first, so I don't think this is a dsoemu issue. Closing!

**Comment by stsp** [comment]
doslfn needs fat32 support (0x73 funcs).
I wonder how mandatory is that, maybe
there is some run time or compile time
switch to not require that.
