### ISSUE TITLE
Nightly batch file script seems to be crashing at some point

### ISSUE THREAD

**Issue by ryanfantus** [dosemu2/dosemu2#2011]
**Describe the bug**
I use dosemu2 to run vintage BBS door games. I've noticed that some of the doorgames complain about nightly maintenance not running, however I have a maintenance script which triggers nightly. 

Stepping through the script manually seems to work fine.

Running the script intentionally from a CLI also seems to work fine.

My suspicion is this: I'm using `-dumb` to run this job, is it possible that long periods of time with no screen updates or anything make dosemu stop? Where would I find the correct logs here?

**To Reproduce**
Create a batch file, something like "maint.bat", and place it in root c:\ directory (or wherever). Make sure the batch script has long periods of seeming inactivity, maybe a long timeout or something.

Run this manually and see it complete as expected.

Run this using `-dumb` and note that it doesn't seem to complete.

**Comment by stsp** [comment]
> Where would I find the correct logs here?

You can do `dosemu -D9+dD` and use
`~/.dosemu/boot.log` which will then contain
all the file accesses. It will be possible to
see if it looked for the bat file in question.
