### ISSUE TITLE
Testing Mouse desyncs in different video modes using Neopaint 3.2a

### ISSUE THREAD

**Issue by stuaxo** [dosemu2/dosemu2#2013]
Neopaint has an option to set the video mode 
![image](https://github.com/dosemu2/dosemu2/assets/179677/3f1bc403-85a1-4681-8b27-63ef26d87610)

I used this to check the default mouse behaviour for these modes, to see if the pointer becomes desynced when you move the cursor off the window and back:

| Mode           | Horizontal Movement                   | Vertical Movement                             | Synched |
|----------------|---------------------|-------------------------------|---------------------|
| 320x200x256    | Appears Doubled     | Correct                       |                     |
| 320x200x32k    | Appears Doubled     | Correct                       |                     |
| 320x200x64k    | Appears Doubled     | Correct                       |                     |
| 320x200x16m    | Appears Doubled     | Correct                       |                     |
| 640x350x2      | Correct             | Limited to top of the screen  |                     |
| 640x350x16     | Correct             | Limited to top of the screen  |                     |
| 640x480x2      | Correct             | Limited to top of the screen  |                     |
| 640x480x16     | Correct             | Limited to top of the screen  |                     |
| 640x480x256    | No desync           | No desync                     |       ✔️          |
| 640x480x32k    | No desync           | No desync                     |       ✔️          |
| 640x480x64k    | No desync           | No desync                     |       ✔️          |
| 640x480x16m    | No desync           | No desync                     |       ✔️          |
| 800x600x256    | No desync           | No desync                     |       ✔️          |
| 800x600x32k    | Desync              | No desync                     |                     |
| 800x600x64k    | No desync           | No desync                     |       ✔️          |
| 800x600x16m    | No desync           | No desync                     |       ✔️          |
| 1024x768x256   | No desync           | No desync                     |       ✔️          |
| 1024x768x32k   | No desync           | No desync                     |       ✔️          |
| 1024x768x64k   | No desync           | No desync                     |       ✔️          |
| 1024x768x16m   | Desync              | No desync                     |                     |

**Comment by stsp** [comment]
For "appears doubled" case try
`emumouse x 16`.

**Comment by stuaxo** [comment]
I haven't been able to get 320x200 to do anything sensible yet, I'll get some results for that, but making emumouse x bigger or smaller than 8 is not helping.

For 640x480 16 color `emumouse x 6 y 40` is synced in horizontal and vertical, however if you then switch to a vesa 640x480 mode like 640x480x256, 640x480x32k etc those modes are no longer synced.

**Comment by stuaxo** [comment]
Here are some screenshots of 320x200.  The cursor is positioned close to the right-most point of the window (the big cursor being the one inside the app, and little one is the native one outside dosemu)

![Screenshot from 2023-06-06 12-21-53](https://github.com/dosemu2/dosemu2/assets/179677/b05897ac-3bb0-4c4d-90f3-975ef81d7ab2)
![Screenshot from 2023-06-06 12-21-03](https://github.com/dosemu2/dosemu2/assets/179677/098f5b33-abef-41ea-aa62-2c9d5f5f43b5)
![Screenshot from 2023-06-06 12-24-57](https://github.com/dosemu2/dosemu2/assets/179677/197910a4-bd29-4f84-8856-ae89f8a8296e)

It shows minimum internal x resolution as 640 and minimum internal y resolution as 200 - (though it's in text mode when it displays that).

**Comment by stuaxo** [comment]
Re:  640x480x16 vs the vesa modes of that res.
Is there something special the mouse does in vesa modes (hence the 'ignore vesa modes' setting), that doesn't have an equivalent in the vanilla 640x480x16 vga mode ?

**Comment by stsp** [comment]
This was done 7 years ago: f8891e0f90
So I can't properly recall.
But IIRC the problem was that the MS
mouse driver is not aware of VESA modes,
and some progs relied on that fact.
I think the problem was that GEOS had
the cursor de-syncs, so maybe @bolle732 
remembers something.

Overall the desyncs are not a bug.
But AFAIK dosbox and virtualbox mouse
add-on use different technique than dosemu2
does. So if you have no desyncs in dosbox
then it would be possible to add another
compatibility knob to emumouse.com.

**Comment by stuaxo** [comment]
I need to have a further look..

dosbox - by default has an "auto capture" thing turned on and is desynced when I hit Ctrl-F10 to toggle it off.

dosbox-x - seemed to work out of the box, I only tried 640x480x16, 320x200x256 and 1024x768 but they were all correct.

I'll see if these are extras added to dosbox-x or settings that exist in doxbox I can apply.

As a first impression of dosbox-x, it's nice that debugging tools are available straight from a menu along with options to change disk etc.

On the mouse front It tells me it's using internal emulation, so I'll see what info there is on that.

**Comment by stsp** [comment]
Please try `$_mouse_ungrab_tweak = (on)`

**Comment by stuaxo** [comment]
With that setting 640x480x16 is correct, and of course no issue on 640x480x256 either.

320x200 didn't seem correct, I'll try some of the other modes when I get back in a bit.


Off topic I got distracted for a moment that dosbox-x has an HX dos release, which runs in dosemu:
![image](https://github.com/dosemu2/dosemu2/assets/179677/199d5341-e115-4f60-b764-0ef2e391c499)

**Comment by stsp** [comment]
Uh, wow!
How's the speed?
Should we document that finding?
Its amazing that dosbox-X can do
such things while we only got an
arm support...

**Comment by stuaxo** [comment]
I'll open a new ticket for it, we can work out those details and do a bit of testing with it.

**Comment by stsp** [comment]
I added `U` opt for emumouse to enable
the ungrabbed tweak. Ideally it should be
dosbox-X compatible. Although you indicate
its not quite there yet...

> I'll open a new ticket for it, we can work out those details and do a bit of testing with it.

Don't expect me to do much until I complete
my tool-chain for comcom32. Hopefully this
year it will be completed...

**Comment by stuaxo** [comment]
Nice, I might have to try `emumouse u` when this build appears on the PPA, I upgraded to a ubuntu lunar (23.04) and some things broke in the build, I'll have a stare at them tomorrow - one bit might be that clang seems to now be 15.

gcc-ia-16 needs a little more baking before it's available on lunar
https://github.com/tkchia/gcc-ia16/issues/138

**Comment by stsp** [comment]
emumouse u is the same as ungrab
tweak in dosemurc.
ia16-gcc is not needed to build any
component of dosemu2.
clang-15 and lunar is supported, in fact
I use lunar myself.

**Comment by bolle732** [comment]
> I think the problem was that GEOS had
> the cursor de-syncs, so maybe @bolle732
> remembers something.

There has been different problems with the mouse during the evolution of DOSEmu which all get sorted out fine. One problem I remember was that the mouse has been clipped into a small space, not being able to access all the screen space. The other problem has been with artifacts due to mouse cursor not being delete completely.

But syncing, I don't remember.

**Comment by stsp** [comment]
> One problem I remember was that the mouse has been clipped into a small space, not
> being able to access all the screen space.

Do you need to run `emumouse s 1`
these days to circumvent the problem,
or the problem is gone completely?

**Comment by stuaxo** [comment]
I'm having a play with vs dos to build DOS executables, having integration tests is needed - I can only really guess what neopaint does in different situations, I'd like to reproduce any behaviour under code we control (and more selfishly play with some dos graphics code 🖥️)

**Comment by bolle732** [comment]
> Do you need to run `emumouse s 1`
> these days to circumvent the problem,
> or the problem is gone completely?

I'll have to check this on another machine when I get on it. My machine here is still Ubuntu 20.04 and I can't upgrade in the near future.

**Comment by stsp** [comment]
What's the problem with 20.04?
It should be supported, see here:
https://code.launchpad.net/~dosemu2/+recipe/dosemu2-daily

**Comment by bolle732** [comment]
I'll compile it on that machine by myself for being able to bisect. Wasn't there a problem with the version of LLD? Is that resolved?

**Comment by bolle732** [comment]
Ok, I retested compiling current GIT versions of comcom32, fdpp and dosemu2 on Ubuntu 20.04 and everything worked without an issue ;-) Holy smoke, I didn't noticed it before...

**Comment by bolle732** [comment]
> Do you need to run `emumouse s 1`
> these days to circumvent the problem,
> or the problem is gone completely?

No, I reviewed my installation and there's no manual `emumouse` invocation anywhere.

**Comment by stsp** [comment]
Thanks for info, so that option was added
for something else we can't remember.
Use ppa builds and you will be up to date
with everything.

**Comment by bolle732** [comment]
Thanks, I'll have the PPA on another machine. This one is for testing and bisecting. But really good to know, that I can compile again ;-)

**Comment by stuaxo** [comment]
Updated from ppa and things work as expected with the ungrab tweak.

**Comment by stsp** [comment]
Which things?
What was fixed?

**Comment by stuaxo** [comment]
Apologies for being unclear :)

The mouse ungrab tweak works as expected with neopaint: I can choose graphics modes that were an issue before - move the mouse off the window and then back on again and it doesn't move in X or Y.

With mouse ungrab tweak disabled things are the still the same (as expected).

So the + is that ungrab is a good workaround.

I'm still interested in seeing if it's possible to get the mouse to behave in this app in the same way by default (without necessarily setting the ungrab tweak) - for instance seeing if I can reproduce the difference between 640x480x16 color and 640x480x256 color outside of neopaint, and build out some tests.

**Comment by stsp** [comment]
> The mouse ungrab tweak works as expected with neopaint

This is strange because earlier it didn't
work for you when enabled via config.
Its the same thing. Yes, I applied a small
mouse fix in between, but it was supposed
to be completely unrelated. If it occasionally
fixed all the neopaint's problems, then I am
surprised.

> I'm still interested in seeing if it's possible to get the mouse to behave in this app in the same way by default

Either by creating the .bat file for startup, or
by applying that setting into a config.

> 640x480x16 color and 640x480x256 color outside of neopaint, and build out some tests.

SerfCity game was such a test.
It made me to implement the very complex
scheme that can produce desyncs. I don't
suppose you can play SerfCity with ungrabbed
mouse under dosbox-X.

**Comment by stuaxo** [comment]
I'll give it a go in the next few days and see what happens.

**Comment by stsp** [comment]
> I'll give it a go in the next few days and see what happens.

Please let us know when this happens.
