### ISSUE TITLE
add missing dpmi-1.0 functionality

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2020]
I documented the missing 1.0 functionality:
c6444ae
Seems quite feasible these days, the list is
rather small. 10 years of porting msdos.c to
1.0 functionality yielded results. :) Most notably
we have now per-client IDTs, which was the
major show-stopper in the past.

**Comment by stsp** [comment]
dpmi-1.0 LDT is merged, which is a
biggest deal in this task.
So only a few dpmi-1.0 missing funcs
remain.
As we now have the shlock lib that allows
for a cheap refcounting of global resources,
we can arrange the shm functions in a
dpmi-1.0 way.

**Comment by stsp** [comment]
Finally I realized what does this bizarre
"mapped" page type in dpmi-1.0 spec mean.
It means that this page was mapped into
a pre-existing linear memory region, so it
overwrites some other page.
That info should be used on freeing, to
restore the pages before releasing them to
smalloc pool.

**Comment by stsp** [comment]
0xd02 would require coopth support.
But coopth in PM is currently only available
to msdos.c, not to dpmi.c, and I don't think
I want to change that.
So that func can only be implemented
via some callback to msdos.c, like current
ldt_monitor extension is doing...
That's quite a mess.

**Comment by stsp** [comment]
0xd02 also needs a multiple-dosemu
tests on CI.

**Comment by andrewbird** [comment]
> 0xd02 also needs a multiple-dosemu
tests on CI.

I'm working on adding something to the test framework that will allow an arbitrary number of `dosemu -K ... ` command line instances in separate threads, collect the output from each, and finally have the test thread evaluate the pertinent output. Synchronisation of the threads will be the responsibility of whatever DOS command is run in each thread. This is likely to be a quicker solution for me than trying to figure out how to use pexpect with threads and individual ptys. At the moment I'm super busy with other non dosemu stuff, so it could be a little unpolished. :smile:

**Comment by stsp** [comment]
> Synchronisation of the threads will be the responsibility of whatever DOS command is run in
> each thread. This is likely to be a quicker solution for me than trying to figure out how to use
> pexpect with threads and individual ptys.

How can that work?
I think in every dosemu session you
need to be able to wait for some output
to justify if the test was good or bad.

**Comment by andrewbird** [comment]
> I think in every dosemu session you
need to be able to wait for some output
to justify if the test was good or bad.

Yes I was thinking that just redirecting stdout and stderr to a different file on each instance would suffice. However I find that while starting just one instance works fine (the boot occurs, the batchfile is run, and the output is captured), starting two instances causes both boots to stall until they eventually time out. I'm not sure whether this is because at present both instances are sharing the same FAT/MFS filesystem to boot and some conflict is occurring, or that I do need separate ptys. I'll keep playing around when I have some time.

**Comment by stsp** [comment]
When you run with stdio redirected to
a file, you don't need a pty. pty is only
used when the stdio is not redirected.
Maybe you redirected not all 3 stdio
fds?

I also don't believe running from the same
FS can produce the problem, as that is a
common scenario.

**Comment by stsp** [comment]
I wrote a test-case:
https://github.com/stsp/shmipc
and tested #2075 
Please use the above test-case
when you add multiple sessions
suit.

**Comment by stsp** [comment]
Before implementing 0x50b, it
seems 0x500 needs to be revisited.
It looks quite wrong now.

**Comment by andrewbird** [comment]
> I also don't believe running from the same
FS can produce the problem, as that is a
common scenario.

It seems that your fix for #2084 also cured the problem I was seeing here, thanks! I'll try to get the test framework update finished now.

**Comment by stsp** [comment]
Sigh, yes, that was a major bug...
And more than one actually. :(
I got locking wrongly in shlock lib,
and now have already punished
myself by writing the full-blown IPC
framework with all the synchronization
primitives. If that is not a punishment,
then I don't know what is. :)

**Comment by stsp** [comment]
I rewrote the shlock lib to the lock-free
algorithms. So if anything bad happens
(in case of some races), it will at least not
be a full dead-lock any more.

**Comment by stsp** [comment]
@jschwartzenberg I think you
played with dpmione under qemu.
Would you like to try this code:
https://github.com/stsp/shmipc
under dpmione?
Its easily buildable, just
`make OS=DOS`

**Comment by andrewbird** [comment]
> I wrote a test-case:
https://github.com/stsp/shmipc
and tested https://github.com/dosemu2/dosemu2/pull/2075
Please use the above test-case
when you add multiple sessions
suit.

What happened to the test case, I don't see it here, perhaps it was dropped from the branch?

**Comment by stsp** [comment]
The branch is called `main`, which
is a new github's default.
What is the problem?

**Comment by andrewbird** [comment]
> What is the problem?

I was expecting to find just a small test rather than a multi file repo. I'll have to study this properly when I have more time. Currently I'm working on an outdoor project that I need to get done before the winter comes. As we have good weather here for many days progress is good and when I finish each evening I'm worn out, but that means I have nothing left for Dosemu.

**Comment by stsp** [comment]
Unfortunately its a big test-case.
But at the end, you just run it on
both VMs w/o any arguments, and
it does the handshake and prints
messages.

**Comment by stsp** [comment]
Outdoor projects are good too. :)
