### ISSUE TITLE
Fedora build is broken

### ISSUE THREAD

**Issue by Nobody-Special** [dosemu2/dosemu2#2022]
**Describe the bug**
Fedora build is broken.

**To Reproduce**
Update dosemu2 to the latest version available on stsp/dosemu2 copr.

**Attach program/game binaries or provide an URL**
Not applicable.

**Attach the log**
<details>
<summary>dosemu -dumb output</summary>

```
CONFIG.SYS error in line 17
>>>devicehigh=dosemu\cdrom.sys
              ^
Process 0 starting: E:\command.com /e:384 /p /k %FDPP_AUTOEXEC%
Bad or missing Command Interpreter: E:\command.com
Bad or missing Command Interpreter: E:\command.com
mkdir(): Permission denied
mkdir(): Permission denied
```
</details>

<details>
<summary>bootlog with +c debug flag</summary>

```
FDPP kernel 1.6 [GIT: ] (compiled Jun 12 2023)
fdpp: plugin loaded: 1
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: config variable c_user set
CONF: Parsing /home/kami/.dosemu/dosemurc file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to 2
CONF: CPU VM set to -1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: dos_up: on
CONF: DPMI-Server on (0x20000)
CONF: DPMI base addr = 0x20000000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes int15 ext memory
CONF: 16384k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
default_drives 0
Setting up drive C, /home/kami/.dosemu/drive_c
Added drive 0 (80): /home/kami/.dosemu/drive_c
default_drives 1
Added drive 1 (81): /usr/share/dosemu/dosemu2-cmds-0.3
Setting up default drives from E
Added drive 2 (82): /usr/share/comcom32
Added drive 3 (83): /usr/share/dosemu2-extras/bat
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 enabled.
CONF: config variable c_system unset
Command line: /usr/bin/dosemu.bin -o /home/kami/.dosemu/boot.log -td -ks
debug flags: +c
Warning: Linux kernel 5.15.90; CPU speed is 3600000000 Hz
Warning: CPU-EMU speed is 3600 MHz
CONF: V86 cpu vm set to 2
CONF: DPMI cpu vm set to -1
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
Warning: dosemu2-2.0pre9 is coming up on Linux version 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64
Warning: Compiled with gcc version 12.3.1Warning:  64bit
Warning: CFLAGS: -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -ggdb3 -fpie -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 16Kb at 0xFA000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
Warning: KVM not available: No such file or directory
Warning: using CPU emulation for vm86()
Warning: using CPU emulation for DPMI
VID: Video set to Video_none
CONF: reserving 64Kb at 0xB0000 for 'v' (Video memory)
Registering HWRAM, type=L base=0 size=0x110000
Conventional memory mapped from 0x41e00000 to 0x42800000
CONF: reserving 16384Kb at 0x900000 for 'x' ((null))
CONF: reserving 8128Kb at 0x110000 for 'X' (EXT MEM)
Registering HWRAM, type=X base=0x110000 size=0x1ef0000
Registering HWRAM, type=U base=0x28710000 size=0x1ef0000
CONF: reserving 64Kb at 0x100000 for 'H' (HMA)
loading fonts for cp437
VID: initializing video none
Registering HWRAM, type=e base=0xe0000000 size=0x400000
CONF: reserving 4Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
DPMI: mem init, mpool is 140468224 bytes at 0x62800000
Warning: Using DPMI with CPU emulator
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============
CONF: freeing region for 'E' (EMS page frame)
booting with comcom32
config.boot_dos set to 400000
config.int_hooks set to 0
config.force_revect set to 0
CONF: reserving 64Kb at 0xA0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 124Kb at 0xC1000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 40Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
mkdir(): Permission denied
mkdir(): Permission denied
leavedos(fdpp_exit:96|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped
======================= LEAVE CPU-EMU ===============
```
</details>

I don't know where to look for "the correct" `CONFIG.SYS`,
so I attach the only one I have found.

<details>
<summary>/usr/share/dosemu/dosemu2-cmds-0.3/c/config.sys (with added line numbers)</summary>

```
 1 rem generic config.sys for DOSEMU + any DOS
 2 rem must be copied to C:\
 3 rem SWITCHES=/F
 4 DOS=UMB,HIGH
 5 lastdrive=Z
 6 files=40
 7 stacks=0,0
 8 buffers=10
 9 device=c:\dos\himem.sys
10 device=d:\dosemu\emufs.sys
11 device=d:\dosemu\umb.sys
12 devicehigh=d:\dosemu\ems.sys
13 devicehigh=d:\dosemu\cdrom.sys
14 install=d:\dosemu\emufs.com
15 rem uncomment to load another bitmap font (see also autoemu.bat)
16 rem devicehigh=c:\dos\display.sys con=(ega,,1)
17 rem for MS-DOS:
18 shell=c:\command.com /e:1024 /p /k d:\autoemu.bat
```
</details>

**A regression?**
Yes. Current (broken version) of dosemu2 is _2.0pre9 Configured: 2023-06-13 20:18:37_.
Last known (not narrowd down) working version of dosemu2 is _2.0pre9 Configured: 2023-05-31 18:16:24_

**Additional info**
Newly installed dosemu2 on a newly installed Fedora 38.

Please tell me where should I look for `command.com`, so that I could confirm it's truly missing and it's not a problem with the file permissions.
**FYI**: It's not in `/usr/share/dosemu/dosemu2-cmds-0.3/dosemu/`.

I'll try to build it from source when I'll have time to do so. :)

**Comment by stsp** [comment]
So it failed to create a directory in
/var/lock. Could you please check
why is so?

**Comment by Nobody-Special** [comment]
<details>
<summary>ls -la /var/lock (WSL Fedora)</summary>

```
lrwxrwxrwx 1 root root 11 Apr 30 08:48 /var/lock -> ../run/lock/
```
</details>
<details>
<summary>ls /var/run/lock -la (WSL Fedora)</summary>

```
drwxr-xr-x  3 root root  60 Jun 14 07:41 ./
drwxr-xr-x 28 root root 700 Jun 14 07:41 ../
drwxr-xr-x  2 root root  40 Jun 14 07:41 subsys/
```
</details>

<details>
<summary>ls -la /var/lock (Bare metal Fedora)</summary>

```
drwx------@  - root 14 cze 09:12 lvm
drwxr-xr-x@  - root 14 cze 09:12 subsys
.rw-r--r--@ 22 root 14 cze 09:12 asound.state.lock
.rw-r--r--@ 22 root 14 cze 09:12 card0.lock
```
</details>

Ps. Previous version doesn't have this issue. Has the behaviour of dosemu changed between versions?

**Comment by stsp** [comment]
> Has the behaviour of dosemu changed between versions?

Yes.
For freebsd port the most important bit
was to relax the requirement of an OFD
locks. Same is for cygwin btw.
We had both region locking and share
modes implemented via OFD locks.
The approach I took, was to rewrite
share to use the portable uucp-style
locks (/var/lock) and just disable the
region locks for freebsd.

So yes, things changed and uucp-style
locks are now a mandatory requirement.
If fedora doesn't give a write perm to
`/var/lock` then its a boomer.

**Comment by Nobody-Special** [comment]
Here is what I found.
Fedora's default permissions for "`/var/lock/`" are 755.
`/var/lock/` links to `../run/lock/`.
`/var/run/` links to `../run/`.
So in the end `/var/lock/` is at `/run/lock/` with permissions 755.

~~I don't think that relative symlinks are a problem, though I could be wrong.~~
~~Is it possible that selinux is at fault?~~

**Comment by stsp** [comment]
What kind of selinux or symlinks you
mean, if the perms are 0755 with root.root
owner? This means only root can write
there, period.

I've found this:
https://bugzilla.redhat.com/show_bug.cgi?id=49908
Here they ended up using some /var/lock/uucp
directory, which doesn't even exist these days.

**Comment by Nobody-Special** [comment]
Mea culpa. I've totaly overlooked the ownership of the directory.

**Comment by stsp** [comment]
So not a big problem, lets just use /tmp
for lock files, ignoring FHS:
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s09.html

**Comment by stsp** [comment]
Please check that it now works as
expected.

**Comment by Nobody-Special** [comment]
Sure. Just waiting for the copr build to finish.

**Comment by Nobody-Special** [comment]
Still fails.

<details><summary>ls -la /tmp</summary>

```
drwxrwxrwt  6 root root  120 Jun 14 10:56 ./
dr-xr-xr-x 19 root root 4096 Jun 14 07:40 ../
drwxrwxrwx  2 root root   60 Jun 14 07:40 .X11-unix/
drwx------  3 root root   60 Jun 14 07:41 systemd-private-d06b6f38604c4c1eba23cb37778e1140-dbus-broker.service-UsS1rG/
drwx------  3 root root   60 Jun 14 07:41 systemd-private-d06b6f38604c4c1eba23cb37778e1140-systemd-logind.service-ZrH5yY/
drwx------  3 root root   60 Jun 14 07:41 systemd-private-d06b6f38604c4c1eba23cb37778e1140-systemd-resolved.service-e3jqId/
```
</details>

Same story 🤦 **EDIT**: boot.log and error message of `dosemu -dumb -D +c` haven't changed.

**Comment by stsp** [comment]
No, its not the same.
Also you need to do `ls -ld` not
`ls -la` to see the dir perms, but
from `-la` it is also seen that
/tmp has 0777.

**Comment by Nobody-Special** [comment]
> No, its not the same.

I've meant that the boot.log and error messages are the same.
Not that the `/tmp` permissions are the same as of `/var/lock`.

> Also you need to do ls -ld

You mean "[...] *could do* [...]", but fair point. Duly noted.

> /tmp has 0777.

1777

**Comment by stsp** [comment]
> 1777

01777
Leading 0 means octal format.

Anyway...
I can run dosemu2 from copr on fedora
in `-t` mode. Gfx modes do not work but
terminal mode works fine, so I assume
the locking part is fixed.
Can you confirm that?

**Comment by stsp** [comment]
It seems like, besides freebsd and cygwin,
our regular duty would be to port to every
new fedora...

**Comment by Nobody-Special** [comment]
I can confirm that it now works in all modes (text and gfx).

**Comment by stsp** [comment]
Though nothing changed from your
prev reply, but ok.

**Comment by Nobody-Special** [comment]
> nothing changed from your prev reply.

How so? Copr was rebuild due to 64e7c2e commit.

**Comment by stsp** [comment]
This is the fdpp-related commit that
has nothing to do with locking problems.
And I checked that locking is fixed,
before applying that commit. Its unrelated.

**Comment by Nobody-Special** [comment]
Probably I've f*ed-up somthing while updating.
Anyway, I'm glad it's fixed.

Hopefully you won't hear from me until monday,
when I'll be trying to build dosemu2 on Cygwin. XD

P.S. Maybe in the meantime I'll try and build dosemu2 on termux, on rooted android. Wish me luck.

**Comment by stsp** [comment]
Yes, thats interesting.
timerfd is the last unportable thing right
now, but on android it might be there, plus
there could be glibc. So while I am quite
sure it will find where to break, I am curious. :)
