### ISSUE TITLE
No output after publishing pre9-8168

### ISSUE THREAD

**Issue by Xeeynamo** [dosemu2/dosemu2#2033]
## Describe the bug

I get no output to stdout when running dosemu with `-quiet -dump -E`. It was working up to `2.0~pre9-8157-0d03713b8+202306261916~ubuntu22.04.1` and it started giving problems since `2.0~pre9-8168-26c2d54c9+202306270453~ubuntu22.04.1`.

## To Reproduce

Create the file `dosemurc` with the following content:

```
$_cpu_vm = "emulated"
$_cpu_vm_dpmi = "emulated"
$_sound = (off)
$_hogthreshold = (0)

$_cpuspeed = (333.333)
$_pci = (off)
$_rdtsc = (off)
$_term_color = (off)
$_ipxsupport = (off)
$_pktdriver = (off)
```

Now simply run `dosemu -quiet -f ./dosemurc -K . -E "DIR"`. 

## Attach program/game binaries or provide an URL

Last successful CI run: https://github.com/Xeeynamo/sotn-decomp/actions/runs/5383265910/jobs/9769793028

Last unsuccessful CI run: https://github.com/Xeeynamo/sotn-decomp/actions/runs/5392855417/jobs/9793281786

## Attach the log

[boot.log](https://github.com/dosemu2/dosemu2/files/11886507/boot.log)

## A regression?

Yes, it worked until `8157` and it is currently giving problems at `8168`.

## Additional info

`dosemurc`:

```
$_cpu_vm = "emulated"
$_cpu_vm_dpmi = "emulated"
$_sound = (off)
$_hogthreshold = (0)

$_cpuspeed = (333.333)
$_pci = (off)
$_rdtsc = (off)
$_term_color = (off)
$_ipxsupport = (off)
$_pktdriver = (off)
```

**Comment by stsp** [comment]
Should now be fixed, thanks.
There is nothing about -dumb or -E
here, just an uninitialized variable happened
because you disabled sound.
If you didn't use -quiet, you'd see the
proper error msg.

**Comment by stsp** [comment]
Btw, what is that CI testing you do?
Maybe we can borrow some for our
CI suite? :)

**Comment by Xeeynamo** [comment]
> Btw, what is that CI testing you do? Maybe we can borrow some for our CI suite? :)

The CI uses dosemu2 to run some MS-DOS CLI tools. I also written a [minimalist Dockerfile](https://github.com/Xeeynamo/wine-psyq/blob/master/Dockerfile.ubuntu-msdos) to embed dosemu2 to use some very old CLI compilers. There's no particular science behind those Dockerfiles and CI. Please be free to copy or use it as a reference if that can be helpful. And thank you for promptly dealing with the issue!

**Comment by stsp** [comment]
Note that dosemu2 is very relocatable.
You can run it from its build dir, w/o installing.
The only external component it will then
look for is comcom32, but even that can
be specified via an env var.
Home dir (~/.dosemu) can also be relocated.
That said, you probably don't need docker.

**Comment by mkst** [comment]
following on from this, is there a guide / any documentation around an absolute minimal configuration for dosemu2 - we only want to run old dos CLI commands, we don't need any sound / fancy graphics etc, as we are using dosemu as part of the compilation process it can be called hundreds/thousands of times and so the quicker it executes, the shorter the overall compilation.

**Comment by stsp** [comment]
You can reduce it, yes.
Run `./default-configure` and at the
end it will list all plugins that it is going
to use. Edit `compiletime-settings`
file and add the lines there, like:
`plugin_xxx off`
where xxx is the name from the
configure output.
Then restart `./default-configure`
and it should list fewer plugins.

But I don't think it will save a lot of
a start-up time, maybe a fraction of
the second.
Perhaps you can turn dosemu2
into a server by redirecting its
stdio to some named pipe. Then
you can simply write the DOS
commands to that pipe from your
build system, instead of restarting
dosemu2 every time. That should
save a lot, but I haven't tried that
technique myself.
