### ISSUE TITLE
Compilation fails with error: unknown type name 'ssize_t'

### ISSUE THREAD

**Issue by PaddyMac** [dosemu2/dosemu2#2039]
My current environment is FreeBSD 14-CURRENT with LLVM 16 as the compiler. I got the following error using the latest git code:

`7 warnings generated.
cc -c -imacros config.hh -MD -DCFLAGS_STR=" -Wno-microsoft -Wno-incompatible-pointer-types     -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -Wno-string-plus-int -fno-stack-protector -ggdb3 -fdebug-macro -fpie -O2   " -I../../../../src/include -I../../../../src/plugin/include -I/usr/home/patrick/work/dosemu2/src/base/bios/x86 -I/usr/home/patrick/work/dosemu2/src/include -I/usr/home/patrick/work/dosemu2/src/base/lib -I/usr/local/include -DOPLTYPE_IS_OPL3 -Wno-microsoft -Wno-incompatible-pointer-types     -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -Wno-string-plus-int -fno-stack-protector -ggdb3 -fdebug-macro -fpie -O2    -o adlib.o adlib.c
cc -c -imacros config.hh -MD -DCFLAGS_STR=" -Wno-microsoft -Wno-incompatible-pointer-types     -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -Wno-string-plus-int -fno-stack-protector -ggdb3 -fdebug-macro -fpie -O2   " -I../../../../src/include -I../../../../src/plugin/include -I/usr/home/patrick/work/dosemu2/src/base/bios/x86 -I/usr/home/patrick/work/dosemu2/src/include -I/usr/home/patrick/work/dosemu2/src/base/lib -I/usr/local/include -DOPLTYPE_IS_OPL3 -Wno-microsoft -Wno-incompatible-pointer-types     -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -Wno-string-plus-int -fno-stack-protector -ggdb3 -fdebug-macro -fpie -O2    -o opl.o opl.c
cc -c -imacros config.hh -MD -DCFLAGS_STR=" -Wno-microsoft -Wno-incompatible-pointer-types     -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -Wno-string-plus-int -fno-stack-protector -ggdb3 -fdebug-macro -fpie -O2   " -I../../../../src/include -I../../../../src/plugin/include -I/usr/home/patrick/work/dosemu2/src/base/bios/x86 -I/usr/home/patrick/work/dosemu2/src/include -I/usr/home/patrick/work/dosemu2/src/base/lib -I/usr/local/include -DOPLTYPE_IS_OPL3 -Wno-microsoft -Wno-incompatible-pointer-types     -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -Wno-string-plus-int -fno-stack-protector -ggdb3 -fdebug-macro -fpie -O2    -o dbadlib.o dbadlib.c
cc -c -imacros config.hh -MD -DCFLAGS_STR=" -Wno-microsoft -Wno-incompatible-pointer-types     -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -Wno-string-plus-int -fno-stack-protector -ggdb3 -fdebug-macro -fpie -O2   " -I../../../../src/include -I../../../../src/plugin/include -I/usr/home/patrick/work/dosemu2/src/base/bios/x86 -I/usr/home/patrick/work/dosemu2/src/include -I/usr/home/patrick/work/dosemu2/src/base/lib -I/usr/local/include -DOPLTYPE_IS_OPL3 -Wno-microsoft -Wno-incompatible-pointer-types     -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -Wno-address-of-packed-member -Wno-string-plus-int -fno-stack-protector -ggdb3 -fdebug-macro -fpie -O2    -o mpu401.o mpu401.c
In file included from mpu401.c:25:
../../../../src/include/ringbuf.h:43:1: error: unknown type name 'ssize_t'
ssize_t rng_get_free_space(struct rng_s *rng);
^
mpu401.c:143:16: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
            mpu->uart = 1;
                      ^ ~
1 warning and 1 error generated.
gmake[2]: *** [/usr/home/patrick/work/dosemu2/src/Makefile.common.post:82: mpu401.o] Error 1
gmake[2]: Leaving directory '/usr/home/patrick/work/dosemu2/src/base/dev/sb16'
gmake[1]: *** [/usr/home/patrick/work/dosemu2/src/arch/linux/Makefile.main:115: base/dev/sb16] Error 2
gmake[1]: Leaving directory '/usr/home/patrick/work/dosemu2/src'
gmake: *** [Makefile:30: default] Error 2`

FORTUNATELY, Google came up with the correct answer. I added the following line to src/include/ringbuf.h

#include <sys/types.h>

and it completed compilation successfully. I don't know if that's the ideal place to add the include directive, but it worked.

**Comment by stsp** [comment]
Thanks, lets do just that then.
