### ISSUE TITLE
With -I "cpu_vm_dpmi native" on Linux kernel 6.1.0-9 (Debian 12) RN and RM don't work

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#2042]
**Describe the bug**
In native DPMI mode on my new Debian 12 installation on an amd64 machine, MMX appears to be supported but registers always read as zero, using lDebugX's RM command or reading from the MM0 variable. 8087 FPU instructions seem to run fine too but the lDebugX command RN always lists all registers as empty.

This is the kernel:

```
test$ uname -srvmpio
Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 unknown unknown GNU/Linux
```

On our server which also runs an amd64 Debian, but without access to KVM, the native DPMI mode allows to use both the x87 and MMX registers as expected.

If I do not specify the `cpu_vm_dpmi native` option then RN works and RM is rejected by the debugger, indicating it did not detect the machine as supporting MMX.

**To Reproduce**

* `wget https://pushbx.org/ecm/download/lcdebug.zip`
* `cp ~/proj/dpmitest/dpmimini.com . -a` (from https://hg.pushbx.org/ecm/dpmitest repo)
* `unzip -j lcdebug.zip bin/lcdebugx.com`
* download Script for lDebug files from https://pushbx.org/ecm/test/20230708/
* `dosemu -dumb -td -kt -K "$PWD" -E "lcdebugx.com /c=ytestmmx.sld dpmimini.com" -I "cpu_vm_dpmi native"`

Output from running MMX test:

```
test$ dosemu -dumb -td -kt -K "$PWD" -E "lcdebugx.com /c=ytestmmx.sld dpmimini.com" -I "cpu_vm_dpmi native"
dosemu2 2.0pre9-dev-20230704-1320-g3b250d8d0 Configured: 2023-07-06 10:08:54 +0000
Get the latest code at http://dosemu2.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

FreeDOS kernel - GIT (build 2043 OEM:0xfd) [compiled Jul  3 2023]
Kernel compatibility 7.10 - GNUC - FAT32 support

(C) Copyright 1995-2022 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled
UMBs unavailable!
dosemu EMS driver rev 0.9 installed.
UMBs unavailable!
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)

FreeCom version 0.85a - GNUC - XMS_Swap [Mar 31 2023 23:40:37]
BLASTER=A220 I5 D1 H5 P300 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre9-dev-20230704-1320-g3b250d8d0
~&ytestmmx.sld
~&g
DPMI entry hooked, new entry=11F5:50DE
Protected mode breakpoint at 015Dh.
32-bit code segment breakpoint at 016Fh.

Unexpected breakpoint interrupt
AX=0200 BX=00E8 CX=0105 DX=000A SP=FFFC BP=0000 SI=0253 DI=50DE
DS=3144 ES=4145 SS=3144 CS=3144 IP=013E NV UP EI PL ZR NA PE NC
3144:013E 89E5              mov     bp, sp
~&g 15D
Succeeded in unhooking interrupt 2Fh.
AX=0001 BX=00E8 CX=0105 DX=000A SP=FFFC BP=FFFC SI=0253 DI=50DE
DS=00B7 ES=00BF SS=00B7 CS=011F IP=015D NV UP EI PL NZ NA PO NC
011F:015D 8CCB              mov     bx, cs
~&rm qwords
MM0=00000000:00000000  MM1=00000000:00000000
MM2=00000000:00000000  MM3=00000000:00000000
MM4=00000000:00000000  MM5=00000000:00000000
MM6=00000000:00000000  MM7=00000000:00000000
~&r mm0 2642
~&rm qwords
MM0=00000000:00000000  MM1=00000000:00000000
MM2=00000000:00000000  MM3=00000000:00000000
MM4=00000000:00000000  MM5=00000000:00000000
MM6=00000000:00000000  MM7=00000000:00000000
~&r mm0 .
MM0 00000000
~#q
Security warning: native DPMI mode is insecure, adjust $_cpu_vm_dpmi
ERROR: MIDI: unsupported synth mode mt32
ERROR: KVM: applying TF fixup
ERROR: KVM: applying TF fixup
test$
```

Log of the above session: 
[boot.log](https://github.com/dosemu2/dosemu2/files/11986493/boot.log)

Output from running x87 test:

```
test$ dosemu -dumb -td -kt -K "$PWD" -E "lcdebugx.com /c=ytestf.sld dpmimini.com" -I "cpu_vm_dpmi native"
dosemu2 2.0pre9-dev-20230704-1320-g3b250d8d0 Configured: 2023-07-06 10:08:54 +0000
Get the latest code at http://dosemu2.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

FreeDOS kernel - GIT (build 2043 OEM:0xfd) [compiled Jul  3 2023]
Kernel compatibility 7.10 - GNUC - FAT32 support

(C) Copyright 1995-2022 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled
UMBs unavailable!
dosemu EMS driver rev 0.9 installed.
UMBs unavailable!
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)

FreeCom version 0.85a - GNUC - XMS_Swap [Mar 31 2023 23:40:37]
BLASTER=A220 I5 D1 H5 P300 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre9-dev-20230704-1320-g3b250d8d0
~&ytestf.sld
~&g
DPMI entry hooked, new entry=11F4:50DE
Protected mode breakpoint at 015Dh.
32-bit code segment breakpoint at 016Fh.

Unexpected breakpoint interrupt
AX=0200 BX=00E8 CX=0105 DX=000A SP=FFFC BP=0000 SI=0253 DI=50DE
DS=3142 ES=4143 SS=3142 CS=3142 IP=013E NV UP EI PL ZR NA PE NC
3142:013E 89E5              mov     bp, sp
~&g 15D
Succeeded in unhooking interrupt 2Fh.
AX=0001 BX=00E8 CX=0105 DX=000A SP=FFFC BP=FFFC SI=0253 DI=50DE
DS=00B7 ES=00BF SS=00B7 CS=011F IP=015D NV UP EI PL NZ NA PO NC
011F:015D 8CCB              mov     bx, cs
~&a cs:80
011F:0080  finit
011F:0083  fld1
011F:0085  fldz
011F:0087  nop
011F:0088  jmp (ip)
011F:008B  .
~&r ip 80
~&r
AX=0001 BX=00E8 CX=0105 DX=000A SP=FFFC BP=FFFC SI=0253 DI=50DE
DS=00B7 ES=00BF SS=00B7 CS=011F IP=0080 NV UP EI PL NZ NA PO NC
011F:0080 9BDBE3            finit
~&t 4
AX=0001 BX=00E8 CX=0105 DX=000A SP=FFFC BP=FFFC SI=0253 DI=50DE
DS=00B7 ES=00BF SS=00B7 CS=011F IP=0081 NV UP EI PL NZ NA PO NC
011F:0081 DBE3              fninit
AX=0001 BX=00E8 CX=0105 DX=000A SP=FFFC BP=FFFC SI=0253 DI=50DE
DS=00B7 ES=00BF SS=00B7 CS=011F IP=0083 NV UP EI PL NZ NA PO NC
011F:0083 D9E8              fld1
AX=0001 BX=00E8 CX=0105 DX=000A SP=FFFC BP=FFFC SI=0253 DI=50DE
DS=00B7 ES=00BF SS=00B7 CS=011F IP=0085 NV UP EI PL NZ NA PO NC
011F:0085 D9EE              fldz
AX=0001 BX=00E8 CX=0105 DX=000A SP=FFFC BP=FFFC SI=0253 DI=50DE
DS=00B7 ES=00BF SS=00B7 CS=011F IP=0087 NV UP EI PL NZ NA PO NC
011F:0087 90                nop
~&rn
CW=037F SW=0000 TW=FFFF OPC=0010 IP=3040B9AB DP=FFF0BCA8
ST0=empty                 ST1=empty
ST2=empty                 ST3=empty
ST4=empty                 ST5=empty
ST6=empty                 ST7=empty
~#q
Security warning: native DPMI mode is insecure, adjust $_cpu_vm_dpmi
ERROR: MIDI: unsupported synth mode mt32
ERROR: KVM: applying TF fixup
ERROR: KVM: applying TF fixup
test$
```

Log of the above session: 
[boot.log](https://github.com/dosemu2/dosemu2/files/11986502/boot.log)

**Attach program/game binaries or provide an URL**
https://pushbx.org/ecm/test/20230708/

**Attach the log**
Uploaded above, after each session's output shown.

**A regression?**
Unknown.

**Additional info**

DOS set up according to https://pushbx.org/ecm/dokuwiki/doku.php?id=blog:pushbx:2023:0706_how_to_set_up_dosemu2_freedos_and_ldebug

**Comment by stsp** [comment]
So on which kernel mmx worked?

**Comment by ecm-pushbx** [comment]
```
$ uname -srvmpio
Linux 4.19.0 #1 SMP Thu Dec 15 20:31:06 MSK 2022 x86_64 unknown unknown GNU/Linux
```

But according to https://www.hosteurope.de/faq/server/virtual-server/kernel-version this is actually an older kernel with backports, "Virtual Server 8.3: 3.10.0".

**Comment by stsp** [comment]
Bart, could you please take a look
at what's going on here? I don't think
I can review that code.
EMU_X86_FXSR_MAGIC is defined as... 0??
How is so?

**Comment by stsp** [comment]
Ok, Bart is unavailable.
@ecm-pushbx in dnative.c:151 you can see this:
`if ((scp->fpregs->status >> 16) == EMU_X86_FXSR_MAGIC)`
This is a condition when we use mmx.
Although  EMU_X86_FXSR_MAGIC is
defined as 0, which is very suspicious.
Could you please find out the real value
of `scp->fpregs->status` on both good
and bad systems?

**Comment by ecm-pushbx** [comment]
But this line is under `#ifndef __x86_64__` https://github.com/dosemu2/dosemu2/blob/928855be8d9e637aa140dae5d17287e5682cb144/src/dosext/dpmi/dnative/dnative.c#L147

So I expect it would never be used?

**Comment by stsp** [comment]
Yes, good point.
So both MMX and STx contain zeros?
Please show the same output from good
kernel.

**Comment by ecm-pushbx** [comment]
Just output of dosemu2 running these tests on the server?

https://pushbx.org/ecm/test/20230708/goodmmx.txt and https://pushbx.org/ecm/test/20230708/goodf.txt

**Comment by ecm-pushbx** [comment]
More recent dosemu2 gives a message about using native DPMI, also on the server. Data output is the same: https://pushbx.org/ecm/test/20230708/goodmmx2.txt and https://pushbx.org/ecm/test/20230708/goodf2.txt

**Comment by stsp** [comment]
Can you write a small test-case
(exe or com) that sets the mmx,
then eg does `hlt` and then prints
its content? Maybe this can be
reproduced locally.

**Comment by ecm-pushbx** [comment]
I can prepare something next week. However, it will have to be based on one of the DPMI examples as MMX is only supported in PM.

**Comment by stsp** [comment]
Then you can do the ST0 test-case,
which presumably is possible in RM?

**Comment by bartoldeman** [comment]
I can have a look later (maybe tomorrow). Note that MMX uses x87 registers st0 to st7 (aliased by mm0 - mm7), and not the SSE register set (xmm0 - xmm7/15), so EMU_X86_FXSR_MAGIC should be irrelevant here.

**Comment by bartoldeman** [comment]
The passed (goodmmx) testcase actually uses an older dosemu2, so it's likely a regression. Most likely the newer dosemu2 will also give similar failures on the older kernel.

I should have another careful look at FPU state, most likely the DPMI (native)FPU state isn't copied to the vm86 (emulated) FPU state.

**Comment by stsp** [comment]
> so EMU_X86_FXSR_MAGIC should be irrelevant here.

Maybe, but please explain why its 0. :)

**Comment by bartoldeman** [comment]
> Maybe, but please explain why its 0. :)

it's 0 because the kernel (X86_FXSR_MAGIC) has it as 0 as well.
The magic field is set to 0xffff on old CPUs without fxsr.

**Comment by ecm-pushbx** [comment]
> The passed (goodmmx) testcase actually uses an older dosemu2, so it's likely a regression. Most likely the newer dosemu2 will also give similar failures on the older kernel.

I checked building the older revision on my local system (the "Linux 6.1.0-9-amd64") and it fails in the same way it seems. These are the commands I used:

```
git clone https://github.com/dosemu2/dosemu2 dosemu2-4beffeff4
cd dosemu2-4beffeff4/
git checkout 4beffeff4
./autogen.sh 
./default-configure --disable-fdpp
make
find -iname dosemu
```

And then: `~/proj/dosemu2-4beffeff4/2.0-pre9/bin/dosemu -dumb -td -kt -K "$PWD" -E "lcdebugx.com /c=ytestmmx.sld dpmimini.com" -I "cpu_vm_dpmi native"`

**Comment by ecm-pushbx** [comment]
Is `o32 fnsave` supposed to reset the state?

**Comment by ecm-pushbx** [comment]
Uploaded a test program to https://pushbx.org/ecm/test/20230723/

[dpmimmx.asm](https://pushbx.org/ecm/test/20230723/dpmimmx.asm) is the test program. [dpmimmx.com](https://pushbx.org/ecm/test/20230723/dpmimmx.com) is the binary. It tries to enter PM, detect MMX, `finit` things, write to `mm0` using `movq`, read the register back using `movq`, then dump using `o32 fnsave` twice, then read back the register using `movq` once more.

https://pushbx.org/ecm/test/20230723/mmxbad.txt is the bad local dosemu2. I used the same dosemu2 revision as on the server for this, but it doesn't make a difference compared to my original build (`Build 2.0pre9-dev-20230704-1320-g3b250d8d0`). https://pushbx.org/ecm/test/20230723/mmxbad.log is the log.

Likewise https://pushbx.org/ecm/test/20230723/mmxgood.txt and https://pushbx.org/ecm/test/20230723/mmxgood.log

**Comment by ecm-pushbx** [comment]
It seems that the `o32 fnsave` resets things, even when I attempt to do `o32 fldenv` immediately after. The very first `o32 fnsave` works as expected, then I read zeroes for all the `mm` register values.

**Comment by ecm-pushbx** [comment]
This is where this debugger does `o32 fnsave` to load the values for the "RM" command: https://hg.pushbx.org/ecm/ldebug/file/e049ceac52cb/source/rr.asm#l2878

It tries `o32 fldenv` afterwards: https://hg.pushbx.org/ecm/ldebug/file/e049ceac52cb/source/rr.asm#l2944

This is where the "RN" command does `o32 fnsave`: https://hg.pushbx.org/ecm/ldebug/file/e049ceac52cb/source/rr.asm#l2017

It tries `o32 frstor` afterwards: https://hg.pushbx.org/ecm/ldebug/file/e049ceac52cb/source/rr.asm#l2220

The debugger never attempts to access the x87 or MMX state or registers unless explicitly instructed using the "RM" or "RN" commands or accesses to register variables like `mm0`.

**Comment by stsp** [comment]
```
Protected mode breakpoint at 015Dh.
Have MMX breakpoint at 01D1h.
 
Error: MMX not supported.
```
What does this mean?

**Comment by ecm-pushbx** [comment]
> ```
> Protected mode breakpoint at 015Dh.
> Have MMX breakpoint at 01D1h.
>  
> Error: MMX not supported.
> ```
> 
> What does this mean?

This means that your machine running the native DPMI code appears to not support MMX, as we try to determine by checking for CPUID then running CPUID with leaf numbers 0 and 1. Look at the test program (or lDebug) source for this test. If you really want you can try to skip the test and execute the MMX instructions anyway.

**Comment by stsp** [comment]
Hmm.
Hi Bart, would you like to please enhance
CPUID in kvm to go past this first?
Currently we have:
```
  // Use the same values as in emu-i386/simx86/interp.c
  // (Pentium 133-200MHz, "GenuineIntel")
```
Bad idea. :)

**Comment by ecm-pushbx** [comment]
I don't think native DPMI should use KVM?

**Comment by stsp** [comment]
It doesn't, but I do. :)

**Comment by stsp** [comment]
kvm part is done, so now I can see
both the good and bad outputs. Which
makes sense.

**Comment by stsp** [comment]
`Warning: Using V86 mode inside KVM`
So you already use KVM.
With current fix you don't need to set dpmi
to "native", and things would works fine.

**Comment by stsp** [comment]
Should now be fixed, enjoy.

**Comment by andrewbird** [comment]
@stsp perhaps you fancy fixing some more FPU issues? In my #1885 PR (just rebased) I have the following failures.
~~~
ajb@calypso:/clients/common/dosemu2.git$ test/test_dos.py --require-attr=fputest PPDOSGITTestCase
Test PP-DOS-GIT  FPU (Qemu)           f2xm1     JIT_JIT                          ... ok (  1.44s)
Test PP-DOS-GIT  FPU (Qemu)           f2xm1     KVM_KVM                          ... ok (  0.82s)
Test PP-DOS-GIT  FPU (Qemu)           f2xm1  KVM_NATIVE                          ... ok (  0.78s)
Test PP-DOS-GIT  FPU (Qemu)           f2xm1     SIM_SIM                          ... FAIL
Test PP-DOS-GIT  FPU (Qemu)           fbstp     JIT_JIT                          ... ok (  0.80s)
Test PP-DOS-GIT  FPU (Qemu)           fbstp     KVM_KVM                          ... ok (  0.80s)
Test PP-DOS-GIT  FPU (Qemu)           fbstp  KVM_NATIVE                          ... ok (  0.77s)
Test PP-DOS-GIT  FPU (Qemu)           fbstp     SIM_SIM                          ... ok (  0.98s)
Test PP-DOS-GIT  FPU (Qemu)          fisttp     JIT_JIT                          ... FAIL
Test PP-DOS-GIT  FPU (Qemu)          fisttp     KVM_KVM                          ... ok (  0.76s)
Test PP-DOS-GIT  FPU (Qemu)          fisttp  KVM_NATIVE                          ... ok (  0.79s)
Test PP-DOS-GIT  FPU (Qemu)          fisttp     SIM_SIM                          ... FAIL
Test PP-DOS-GIT  FPU (Qemu)          fldcst     JIT_JIT                          ... ok (  0.77s)
Test PP-DOS-GIT  FPU (Qemu)          fldcst     KVM_KVM                          ... ok (  0.76s)
Test PP-DOS-GIT  FPU (Qemu)          fldcst  KVM_NATIVE                          ... ok (  0.76s)
Test PP-DOS-GIT  FPU (Qemu)          fldcst     SIM_SIM                          ... FAIL
Test PP-DOS-GIT  FPU (Qemu)   fp-exceptions     JIT_JIT                          ... FAIL
Test PP-DOS-GIT  FPU (Qemu)   fp-exceptions     KVM_KVM                          ... ok (  0.77s)
Test PP-DOS-GIT  FPU (Qemu)   fp-exceptions  KVM_NATIVE                          ... ok (  0.79s)
Test PP-DOS-GIT  FPU (Qemu)   fp-exceptions     SIM_SIM                          ... FAIL
Test PP-DOS-GIT  FPU (Qemu)          fpatan     JIT_JIT                          ... ok (  0.73s)
Test PP-DOS-GIT  FPU (Qemu)          fpatan     KVM_KVM                          ... ok (  0.82s)
Test PP-DOS-GIT  FPU (Qemu)          fpatan  KVM_NATIVE                          ... ok (  0.89s)
Test PP-DOS-GIT  FPU (Qemu)          fpatan     SIM_SIM                          ... ok (  0.99s)
Test PP-DOS-GIT  FPU (Qemu)          fscale     JIT_JIT                          ... ok (  0.83s)
Test PP-DOS-GIT  FPU (Qemu)          fscale     KVM_KVM                          ... ok (  0.78s)
Test PP-DOS-GIT  FPU (Qemu)          fscale  KVM_NATIVE                          ... ok (  0.82s)
Test PP-DOS-GIT  FPU (Qemu)          fscale     SIM_SIM                          ... ok (  0.95s)
Test PP-DOS-GIT  FPU (Qemu)            fxam     JIT_JIT                          ... ok (  0.84s)
Test PP-DOS-GIT  FPU (Qemu)            fxam     KVM_KVM                          ... ok (  0.79s)
Test PP-DOS-GIT  FPU (Qemu)            fxam  KVM_NATIVE                          ... ok (  0.88s)
Test PP-DOS-GIT  FPU (Qemu)            fxam     SIM_SIM                          ... ok (  0.97s)
Test PP-DOS-GIT  FPU (Qemu)         fxtract     JIT_JIT                          ... ok (  0.75s)
Test PP-DOS-GIT  FPU (Qemu)         fxtract     KVM_KVM                          ... ok (  0.84s)
Test PP-DOS-GIT  FPU (Qemu)         fxtract  KVM_NATIVE                          ... ok (  0.79s)
Test PP-DOS-GIT  FPU (Qemu)         fxtract     SIM_SIM                          ... ok (  0.94s)
Test PP-DOS-GIT  FPU (Qemu)           fyl2x     JIT_JIT                          ... ok (  0.73s)
Test PP-DOS-GIT  FPU (Qemu)           fyl2x     KVM_KVM                          ... ok (  0.76s)
Test PP-DOS-GIT  FPU (Qemu)           fyl2x  KVM_NATIVE                          ... ok (  0.84s)
Test PP-DOS-GIT  FPU (Qemu)           fyl2x     SIM_SIM                          ... FAIL
Test PP-DOS-GIT  FPU (Qemu)         fyl2xp1     JIT_JIT                          ... ok (  0.77s)
Test PP-DOS-GIT  FPU (Qemu)         fyl2xp1     KVM_KVM                          ... ok (  0.79s)
Test PP-DOS-GIT  FPU (Qemu)         fyl2xp1  KVM_NATIVE                          ... ok (  0.80s)
Test PP-DOS-GIT  FPU (Qemu)         fyl2xp1     SIM_SIM                          ... FAIL
Test PP-DOS-GIT  FPU (Qemu) pseudo-denormal     JIT_JIT                          ... ok (  0.80s)
Test PP-DOS-GIT  FPU (Qemu) pseudo-denormal     KVM_KVM                          ... ok (  0.78s)
Test PP-DOS-GIT  FPU (Qemu) pseudo-denormal  KVM_NATIVE                          ... ok (  0.73s)
Test PP-DOS-GIT  FPU (Qemu) pseudo-denormal     SIM_SIM                          ... ok (  0.91s)
Test PP-DOS-GIT  FPU (Qemu)    snan-convert     JIT_JIT                          ... ok (  0.82s)
Test PP-DOS-GIT  FPU (Qemu)    snan-convert     KVM_KVM                          ... ok (  0.79s)
Test PP-DOS-GIT  FPU (Qemu)    snan-convert  KVM_NATIVE                          ... ok (  0.82s)
Test PP-DOS-GIT  FPU (Qemu)    snan-convert     SIM_SIM                          ... ok (  0.95s)
~~~

Actually the Github Action for that PR is running now, so there should be a new artifact.zip file with the failures to download afterwards, see https://github.com/dosemu2/dosemu2/actions/runs/5685363036.

**Comment by stsp** [comment]
fp sim...
Not one of those things I would enjoy fixing.
Lets see what would I need, if I wanted to:
- bug ticket
- an output of expected and obtained values

**Comment by andrewbird** [comment]
I can raise a ticket if necessary, the output/expected values are in the artefact file I mentioned above, but I can't be of much help otherwise about the tests, as they were just lifted on Bart's suggestion from the Qemu project.  The sort of info you'd find in that artefact file is 
~~~
FAIL: f2xm1 0x9.0950fb020f8be81p-5, expected 0xd.d65066b1a53a1e6p-6 or 0xd.d65066b1a53a1e7p-6, got 0xd.d65066b1a53a1e9p-6
~~~
Which means very little to me, but perhaps it's enough to start debugging? Anyway, don't feel pressured into doing this, I just put a little effort into wrapping the Qemu FPU tests into our test suite, but can't add them to devel as we have failures. From time to time, when I see some commit that touches anything FPU related, I rebase and rerun the tests in the hope that they perhaps now pass and I can sneak them in. I have no real world examples of any program failing on DOS due to FPU, so it's all really contrived.

**Comment by stsp** [comment]
Perhaps you can fill in 3 tickets.
One for rounding errors, where the mismatch
is in a least-significant digit.
Another for obviously incorrect answers,
and another for non-sim errors.

**Comment by andrewbird** [comment]
Okay I'll try to get the tickets done in the next few days, thanks.

**Comment by ecm-pushbx** [comment]
> Should now be fixed, enjoy.

Thanks! It does seem to be fixed, both testmmx.sld and dpmimmx.com work as expected now (in native DPMI mode). Considering that this had to do with the KVM mode used for 86 Mode, I assume that the state was lost/corrupted whenever the machine switched into Virtual 86 Mode, including for any DOS I/O (like what the debugger does for its interface, or the dpmimmx test when it displayed things).
