### ISSUE TITLE
How to pass arguments to program started by dosemu -K ?

### ISSUE THREAD

**Issue by rkd77** [dosemu2/dosemu2#2045]
There is program /tmp/blabla.exe which accepts parameter -help .
How to run it with dosemu -K? I tried:
dosemu -K /tmp/blabla.exe -help
dosemu -K /tmp/blabla.exe -- -help
It does not work. Is there any way to pass parameters to dos program?

**Comment by stsp** [comment]
As man page says:
```
       -E dos-command
              Run  DOS  command  when  starting DOSEMU.  The linux path to the
              command can be given with -K option.  For example
              dosemu -K /home/joeuser/dosemu/freedos/bin -E "xcopy my_file my_dir"
              will run /home/joeuser/dosemu/freedos/bin/xcopy.exe with 2 argu-
              ments.
              Note:  this only works if your autoexec.bat contains "system -e"
              command.
```

**Comment by stsp** [comment]
Although in principle we can indeed
use `--` as an alias to -E.

**Comment by stsp** [comment]
That would make something like this possible:
`dosemu -K /tmp -- blabla.exe -help`
... which is still not among anything you tried.
So I guess it won't help much.

**Comment by stsp** [comment]
Or actually... we can support this syntax directly:
`dosemu -K /tmp/blabla.exe -- -help`

Does anyone think this would be a useful
extension to -K?

**Comment by stuaxo** [comment]
Yes, I think that looks handy.

**Comment by stsp** [comment]
I am currently trying to convince myself
that adding a dosbox-compatible syntax
is a better idea than extending -K in any
way.

**Comment by stuaxo** [comment]
I tend to use things like dosemu and dosbox for a bit then come back some months later.

I never need to check the manual for how to run something in dosbox or have it mount directories from the commandline: I either pass a command to run or a directory/directories, for dosemu I always need to remind myself of -E and -K

**Comment by stsp** [comment]
Yes, plus -K is already a pig of extensions:
`-K unix_path[:dos_path]` where `unix_path`
can be both a dir name or a full path...
It really should be shrunk rather than extended.

But does dosbox support
`dosbox ./cmd arg1 arg2`?
Seems args are not passed?

**Comment by rkd77** [comment]
For now -K dir -E "cmd arg" is sufficient for me. Thanks.

**Comment by stsp** [comment]
Good to know, although I added an
alternative syntax to pass the dos cmd
directly, in a dosbox-alike manner.
There are a few reasons to:
1. having dosbox-compatible syntax is
    always good
2. I've even actually seen ppl complaining
    that dosemu2 requires both -K and -E,
    which is too complex (and I've never even
    used that myself, as its really too much)
3. -K is too overloaded and this is a good
    off-load of its functionality

Though I really am not sure how dosbox-compatible
is that, given that dosbox doesn't seem to allow
passing arguments this way... So for now I put
the patch into a separate branch for further
discussions.

**Comment by stsp** [comment]
Ok, I ended up supporting both direct
cmd passing and `--`. They do not work
without each other.

So now you can do:
`dosemu /tmp/blabla.exe -- -help`
The old alternative is:
`dosemu -K /tmp -E "blabla.exe -help"`
