### ISSUE TITLE
LORD on Enigma BBS with dosemu2

### ISSUE THREAD

**Issue by AviatingPenguin** [dosemu2/dosemu2#2054]
**Describe the bug**
Running lord using dosemu2 in a BBS causing game to crash (check range error)

**To Reproduce**
Install a BBS (I use Enigma) install LORD and set it up in the bbs, log into the bbs and run the door. Note: Other door games work just fine, just not lord

**Attach program/game binaries or provide an URL**
Using Lord with the patch so it will work (files uploaded)

**Attach the log**
Log attached

**A regression?**
always a problem afaik for the last 2 years+

**Additional info**
Lord works when offline (running "start 0" for node 0) but when using "start 1" (to run on node 1) it doesn't work and crashes
Used this guide to slightly modify for it to work with enigma/bbs's 
https://medium.com/retro-future/lets-add-a-dos-game-to-enigma-1-2-41f257deaa3c

[lord407-patch.zip](https://github.com/dosemu2/dosemu2/files/12065636/lord407-patch.zip)
[lord407.zip](https://github.com/dosemu2/dosemu2/files/12065637/lord407.zip)
[boot.log](https://github.com/dosemu2/dosemu2/files/12065638/boot.log)

**Comment by stsp** [comment]
No crash seen in the log.
Please attach the screen-shot of a crash.

**Comment by stsp** [comment]
Also it might be good to share the
ready-to-use setup. You need to
pack your ~/.dosemu/drive_c or
anything else related, and upload.

**Comment by jharrison03** [comment]
Can I ask you what version of Enigma BBS this is?  

Based on your description, the BBS is probably leaving an interrupt handler installed during the shell for the door.  That's not uncommon if it's using some type of middleware like AsyncPro.

If the BBS SW has the option to terminate on doors, try that (the idea being the RTL will clean that up).

**Comment by stsp** [comment]
There was an important serial emulation
fix recently. Please re-evaluate this problem.

**Comment by stsp** [comment]
Stalled.
