### ISSUE TITLE
$_hdimage path no longer follows symlinks

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#2055]
**Describe the bug**
$_hdimage is set as follows in dosemurc --

$_hdimage = "/_my home path_/.dosemu/drives/*"

In this path I have the following --

c (directory)
d (directory)
e (a symlink to _my home path_)

DOSEmu doesn't see this symlink to my home directory (e drive) any longer, where it used to, but I'm not certain when this stopped working - maybe around one month ago.  I can use lredir.com as a work-around.

**To Reproduce**
Assign a symlinked path under the path specified by $_hdimage, and try to access this drive under DOSEmu.

**Comment by stsp** [comment]
Can't reproduce:
`$_hdimage = "+0 /home/stas/.dosemu/drives/* -1 +1"`

Gives:
```
C:\>emudrv -s
Current Drive Redirections:
C: = /home/stas/.dosemu/drive_c attrib = READ/WRITE
D: = /home/stas/.dosemu/drives/d attrib = READ/WRITE
F: = /usr/local/share/dosemu/dosemu2-cmds-0.3 attrib = READ ONLY
G: = /usr/local/share/comcom32 attrib = READ ONLY
H: = /usr/local/share/dosemu2-extras/bat attrib = READ ONLY
```

**Comment by stsp** [comment]
```
$ ls -ld ~/.dosemu/drives/d
lrwxrwxrwx 1 stas stas 2 июл 19 14:54 /home/stas/.dosemu/drives/d -> ..
```

So yes, its a symlink.
