### ISSUE TITLE
kvm.c:186:25: warning: field 'mask' with variable sized type

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2057]
```
kvm.c:186:25: warning: field 'mask' with variable sized type 'struct kvm_signal_mask' not at the end of a struct or class is a GNU extension [-Wgnu-variable-sized-type-not-at-end]
        struct kvm_signal_mask mask;
```

Hi Bart, could you please fix this?

**Comment by stsp** [comment]
Hi @bartoldeman how about looking
into this one? Might be trivial to fix.
But I find myself uncomfortable fixing
it, as only you know why it was done
that way.

**Comment by bartoldeman** [comment]
i had a look but it's not straightforward (as `struct kvm_signal_mask` comes from a header), I can only think of `malloc` for now, ie.

```
struct kvm_signal_mask *maskbuf = malloc(sizeof(*mask) + KERNEL_SIGSET_T_SIZE);
maskbuf->len = KERNEL_SIGSET_T_SIZE;
memcpy(maskbuf->sigset, &sigset, KERNEL_SIGSET_T_SIZE);
...
free(maskbuf);
```
if that's ok with you it can be done that way, though malloc is overkill...

**Comment by stsp** [comment]
But how is this a fix, if mask has a
variable sized type?
I haven't dig into the problem, but from
the first glance I don't understand why
applying sizeof to variable-sized type
can fix anything.

**Comment by stsp** [comment]
Are you sure you need a struct and
not union there?
(sorry if this question is too naive, but
I don't yet understand the problem)

**Comment by bartoldeman** [comment]
struct kvm_signal_mask is defined as
```
struct kvm_signal_mask {
 __u32 len;
 __u8 sigset[0];
};
```
here sigset is variable, but I can still take the sizeof, and it returns 4.

All the examples i can find that use kvm_signal_mask (QEMU, kvm_test) use malloc.

**Comment by stsp** [comment]
OK, then its quite clear. :)
So how about converting it to the union,
and using `offsetof(struct kvm_signal_mask, sigset)`
or even `sizeof(struct kvm_signal_mask)`
 as an addition to KERNEL_SIGSET_T_SIZE?

**Comment by bartoldeman** [comment]
yes that might work, I'll give it a try later.

**Comment by stsp** [comment]
I think using a struct here, as you do
now, is even a bit dangerous, unless
you also use packed attribute to guarantee
no padding between members.
Yes, it seems like there is not going to be
any padding in that particular case, but
with that VLA member I am not even sure
enough.
