### ISSUE TITLE
[question] how do you setup the vga on this ?

### ISSUE THREAD

**Issue by Unixware** [dosemu2/dosemu2#2059]
I am trying the DBASE V , setup works ok (DBSETUP) but loading the main program stops on a black screen - no errors.
I assume the VGA text mode is unimplemented ot somtthing like this ? thx

edit: dosbox works ok , so no problem with the DBASE installation , just to clarify this

**Comment by stsp** [comment]
Too little info.
Please see this page:
https://github.com/dosemu2/dosemu2/wiki/Modes-of-operation
for how to work in gfx mode.
