### ISSUE TITLE
Comment comparing dosemu2 KVM/V86 to qemu KVM/R86, and generally

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2066]
### Discussed in https://github.com/dosemu2/dosemu2/discussions/2064

<div type='discussions-op-text'>

<sup>Originally posted by **ecm-pushbx** August  5, 2023</sup>
I replied to a user on the FreeDOS sourceforge.net feature tracker today. The following is my text in full. Do you have anything to add or correct about the bits and bobs I wrote there? Feel free to reply here or over there.

----

> If you should decide for a special build I would suggest ldebugr as a name, the r then stands for real mode without DPMI. As I assume you want to omit the PM or DPMI part in this particular build to keep the program under 64kb.

lDebug without the X already is the 86-Mode-only variant. So if I want to add a more feature-rich build it should have a name indicating that it has more options enabled, not simply a trait that it shares with the non-X default lDebug build. (As an aside, the script names like `makerd` already use the R letter naming for the non-X builds, just not in the build name they eventually create.)

> On the other hand, if only the PM/DPMI variant LDEBUX is affected, couldn't one simply swap code parts of the LDEBUX variant into the XMS memory?

(I will reply assuming a DPMI memory allocation, which is less of a headache to access while in Protected Mode than an XMS allocation.) This would be no easier than the dual code segments approach that we already have, and would fail more often, as in you couldn't access the DPMI allocated code segment while not yet in Protected Mode, or while switched temporarily to 86 Mode.

In case you weren't aware, the dual code segments option splits off some code parts into a second code segment. This is possible in all builds of lDebug; in 86-Mode-only builds the debugger relocates a bunch of far calls (similar to MZ .EXE file relocations) during installation (from the init section), while in Protected-Mode-enabled builds all calls to dual-distance functions are done with calls to helpers that resolve the far target and return addresses in agreement with the current mode (segments in 86 Mode, selectors in Protected Mode).

So we do have a way to lower the code segment pressure, it is simply a hassle both in the work to write and use it and in the space and performance hits associated with the dual calls.

> Since dosemu2 allows you to copy and paste the text from the DOS environment into the Linux host system, I would even assume that DOSEMU2 is more of a kind of a wrapper than a full emulator.
> If the DOS application then tries to write into foreign memory areas, I wouldn't be surprised if the Linux kernel then responds with a sigkill. But that's just a guess on my part.

This is half accurate, but only just so.

For 86 Mode, both qemu and dosemu2 can use KVM, but qemu will run the client in Real 86 Mode and pass along all exceptions to the client, it appears. For dosemu2, the client still runs in Virtual 86 Mode, and some exceptions will terminate dosemu rather than be passed to the client. (lDebug's RV command can display one of four modes: Real 86 Mode, Virtual 86 Mode, or DPMI with a 16- or 32-bit code selector.)

For example, running an instruction like `mov ax, word [FFFF]` in qemu KVM will cause a Real 86 Mode General Protection Fault (interrupt 0Dh) to the client.

(An lDebug build with the build option `-D_CATCHINT0D` can be used to intercept this; without such a special handler the IRQ #5 hardware interrupt handler will be repeatedly called, easily resulting in an infinite loop. Another option to get out of the infinite loop is to `install timer, serial` and break back into the debugger using a double Control-C to the serial input. Yet another option is to build with `-D_CATCHSYSREQ -D_SYSREQINT=15h` and try to break to the debugger using the SysReq key. However, in qemu version `QEMU emulator version 7.2.2 (Debian 1:7.2+dfsg-7)` this seems to lock the keyboard input from reaching the debugger. Instead, we can try to run like (faulting instruction at 60h:0) `rc.replace g; tp 100 while csip != 60_0000 silent 1` then `rc`. This last one doesn't work properly in qemu either; even with the work-around attempt (the TP command running from RC buffer) it crashes the debugger and/or debuggee somewhat, probably due to inreentrant IRQ handlers in their ROM-BIOS. I had a similar problem on dosemu2 (the first problem, int 15h SysReq detection locking the keyboard input IRQ), which [got fixed on their end](https://github.com/dosemu2/dosemu2/issues/1780) by modifying their ROM-BIOS handler for interrupt 09h (IRQ #1). Using `-D_SYSREQINT=09h` never seems to detect the Alt+Druck (S-Abf, ie SysReq) keypress in this version of qemu.)

(In non-KVM qemu, segment limits are never checked.)

In dosemu2 KVM, the same faulting instruction will crash dosemu2 because the VMM doesn't handle it the same way.

This is not really a difference of how much of a "wrapper" or "full emulator" either program is, the faults are simply handled differently.

I do use "native DPMI" mode for dosemu2, which is probably faster than any alternative. To my understanding, it runs your DPMI Protected Mode code basically as native Linux code, with the descriptors set up to allow 16-bit and 32-bit Protected Mode execution (which still both work even with the OS in amd64 Long Mode). I'm unsure about how much this changes the big picture on faults, as some can still clearly be caught by dosemu2 and reflected into the client. (For instance, when I run `lcdebugx.com /d- lcdebugx.com dpmimini.com` then enter PM, the inner lCDebugX may cause a Page Fault accessing invalid memory at >= 1088 KiB and this will be caught by the outer lCDebugX.)

But this mode is certainly closer to regular Linux host user mode than whatever qemu does, KVM or no. On the other hand, this is not a mode used by default, you have to enable it explicitly, eg using the dosemu2 command line switch `-I "cpu_vm_dpmi native"`.</div>

**Comment by stsp** [comment]
Should now be fixed (in fdpp).

**Comment by ecm-pushbx** [comment]
It is fixed if I install the appropriate handlers. However, if my application does not install the handlers then the FreeDOS kernel appears to hook both IRQ handlers and dosemu no longer terminates on the faults, rather it will hang (as expected). This is the handlers installed by FreeDOS:

```
-di in 0D, 0C
int 0D 0070:006B (IISP)
 --> F000:F568
int 0C 0070:0056 (IISP)
 --> F000:F568
```

**Comment by ecm-pushbx** [comment]
Regarding https://github.com/dosemu2/fdpp/commit/785ee04dee3d5267b4de3f6dc56ea1bf6f341c5c what happens if the IRQs are called? You do not seem to dispatch based on IRQs anywhere.

**Comment by stsp** [comment]
Sound blaster drivers do install their
own IRQ handler, so 0xd should be
fine, but I wouldn't be so sure about
0xc, which is serial port...
That irq is normally masked on a
serial port, so the driver should provide
its own handler, but if it calls the default
handler instead of EOI, then we have a
problem.

**Comment by stsp** [comment]
> FreeDOS kernel appears to hook both IRQ handlers

Try STACKS=0

**Comment by ecm-pushbx** [comment]
> Sound blaster drivers do install their
own IRQ handler, so 0xd should be
fine, but I wouldn't be so sure about
0xc, which is serial port...
That irq is normally masked on a
serial port, so the driver should provide
its own handler, but if it calls the default
handler instead of EOI, then we have a
problem.

Why not detect IRQs the same way I do in the debugger? https://hg.pushbx.org/ecm/ldebug/file/eab8e19cb957/source/run.asm#l6147

> Try STACKS=0

Yes, with `STACKS=0` it works in the same way it used to (terminating dosemu).

**Comment by stsp** [comment]
Yes, that looks good.
Can you make a PR?

**Comment by ecm-pushbx** [comment]
I don't have fdpp builds set up currently.

**Comment by stsp** [comment]
OK, detection added.

**Comment by ecm-pushbx** [comment]
Nice!
