### ISSUE TITLE
[MS-DOS game: Gunmetal, 1998] Launches black screen, freezing DOSEMU2 session

### ISSUE THREAD

**Issue by AlbertHamik** [dosemu2/dosemu2#2077]
**Describe the bug**
When trying to launch the game, randomly the game may decide to not launch and the screen is black in the DOSEMU2 window and the session is effectively softlocked, requiring an exit and try again. The game will randomly work correctly especially when I choose to launch it with certain parameters like loading a map (ex: "gun level0") or lower graphics options (ex: "gun /nhw /l" -- with l being low).

**To Reproduce**
Try playing the game. Make note of what I did to randomly make it work above.

**Attach program/game binaries or provide an URL**
[Here](https://archive.org/details/gundemo2) is the Gunmetal demo. Doesn't matter which version of the game you get really but later ones have improved mouse support so yeah.

**Attach the log**
FDPP kernel 1.6 [GIT: ] (compiled Aug  6 2023)
fdpp: plugin loaded: 1
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to 1
CONF: CPU VM set to 1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: dos_up: on
CONF: DPMI-Server on (0x20000)
CONF: DPMI base addr = 0x20000000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes int15 ext memory
CONF: 16384k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: no device specified, type 0 using internaldriver: yes, emulate3buttons: no baudrate: 0
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
default_drives 0
Setting up drive C, /home/user/.dosemu/drive_c
Added drive 0 (80): /home/user/.dosemu/drive_c
default_drives 1
Added drive 1 (81): /usr/share/dosemu/dosemu2-cmds-0.3
Setting up default drives from E
Added drive 2 (82): /usr/share/comcom32
Added drive 3 (83): /usr/share/dosemu2-extras/bat
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 enabled.
CONF: config variable c_system unset
Command line: /usr/bin/dosemu.bin -o /home/user/.dosemu/boot.log
Warning: Your CPU doesn't support UMIP
Warning: Linux kernel 5.15.0; CPU speed is 800000000 Hz
Warning: CPU-EMU speed is 800 MHz
CONF: V86 cpu vm set to 1
CONF: DPMI cpu vm set to 1
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
Warning: dosemu2-2.0pre9 is coming up on Linux version 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64
Warning: Compiled with clang version 14.0.0 (gnuc 4.2)Warning:  64bit
Warning: CFLAGS: -Wno-microsoft -Wno-incompatible-pointer-types -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -fsigned-char -fno-stack-protector -ggdb3 -fdebug-macro -fpie -g -O2 -ffile-prefix-map=/build/dosemu2-fKiGWe/dosemu2-2.0~pre9-8246=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 16Kb at 0xFA000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
Warning: Using V86 mode inside KVM
VID: initializing SDL plugin
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Registering HWRAM, type=L base=0 size=0x110000
Conventional memory mapped from 0x7f262d000000 to 0x7f2602600000
CONF: reserving 16384Kb at 0x900000 for 'x' ((null))
CONF: reserving 8128Kb at 0x110000 for 'X' (EXT MEM)
Registering HWRAM, type=X base=0x110000 size=0x1ef0000
Registering HWRAM, type=U base=0x28710000 size=0x1ef0000
CONF: reserving 64Kb at 0x100000 for 'H' (HMA)
loading fonts for cp437
VID: initializing video sdl
VID: SDL plugin initialization completed
Registering HWRAM, type=e base=0xe0000000 size=0x400000
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
Warning: SERIAL $Id$
ERROR: MIDI: unsupported synth mode mt32
DPMI: mem init, mpool is 140468224 bytes at 0x7f2622600000
Warning: Using DPMI inside KVM
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
CONF: freeing region for 'E' (EMS page frame)
booting with comcom32
config.boot_dos set to 400000
config.int_hooks set to 0
config.force_revect set to 0
CONF: reserving 116Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 40Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
leavedos(fdpp_exit:96|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped

Package info:
dosemu2: installed
dosemu2	2.0~pre9-8246-b5c40346a+202308151346~ubuntu22.04.1
fdpp: installed
fdpp	1.6-1377-52324b2+202308061346~ubuntu22.04.1

**A regression?**
I don't recall this ever happening when I played the game in DOSEMU2 (self-compiled from repo) two years back.

**Additional info**
KVM mode. I said it in the other issue report from today but DOSEMU2 is seriously the best way to play this game that I've ever found, period. Already stated why in the other issue but tl;dr late era DOS game too demanding in most emulators and Windows version is broken currently.

**Comment by stsp** [comment]
It hangs at calibrating the joystick.

**Comment by AlbertHamik** [comment]
[Here's my new log file after disabling the joystick (issue still happens).](https://github.com/dosemu2/dosemu2/files/12356500/boot.log)

**Comment by stsp** [comment]
It calibrates the joystick nevertheless,
and it disables interrupts while doing so
(quite reasonable for a more precise
calibration).
vtmr seems to hang during that process.

**Comment by AlbertHamik** [comment]
Odd that joystick is still being calibrated. Don't know what vtmr is, but I'm guessing this game is doing something to it causing this issue, going by your statement.

**Comment by stsp** [comment]
> Don't know what vtmr is, but I'm guessing this game is doing something to it causing this issue

vtmr is our new virtual timer device.
If its irqs are masked, it should emulate
the timer in its legacy mode, where you
can't track the precise number of overflows.
But it was not checking the IF flag, so
instead of switching to legacy mode,
it just hanged.

**Comment by AlbertHamik** [comment]
Just out of curiosity when was it added?

**Comment by stsp** [comment]
commit 77177b04b3baf6038fe596dba15943ba958dde27 (origin/pr/1596)
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Tue Feb 22 00:00:22 2022 +0300

    introduce virtual timer device [#1588]

**Comment by AlbertHamik** [comment]
Huh, so this might have had some sort of influence on the game over when I last played it possibly? I was using DOSEMU2 in 2021 and I was done with it before that year ended, or early 2022 at least. This game has weird timing issues and I am wondering if this new vtmr thing impacts it at all? 

I felt like there was some small things that seemed out of sync versus my memory of when I last used the software in 2021, but, and apologies on this, I forgot to record the moments that I had pinpointed as adequate tests for the timing issue at the time. I do need to test some more though and this black screen issue is slowing me down until the update pushes through to PPA.

EDIT: Oh the update pushed through already. I posted this message up because I forgot to earlier so I only just saw it now.

**Comment by stsp** [comment]
> This game has weird timing issues and I am wondering if this new vtmr thing impacts it at all?

Not sure, not seeing the timing
problems yet.

**Comment by AlbertHamik** [comment]
admittedly it's not stuff that would be readily apparent just from casually playing the game. There's key elements to the game that always seem to vary in sync based on systems and such, and as far as I've been able to tell in the past, DOSEMU2 seemed one of the few exceptions to this but I never had anyone to corroborate that. Currently waiting on someone who is helping me behind the scenes with some things to try out DOSEMU2 for themselves.

**Comment by stsp** [comment]
Can you try the demo I downloaded
earlier, and tell your experience with that?
Maybe I don't need to D/L yours if the
problems are similar.

Note that dosbox historically works
exceptionally badly for me. I don't know
why, I just use the ubuntu-packaged build.
It never worked properly, and this game
is not an exception. Since I haven't heard
from anyone else that dosbox doesn't work
or has problems with this or that game,
I attribute that to some "bad aura".
For example I run carmageddon under
dosbox, and get gfx glitches even in the
main menu... If not everyone saying dosbox
is flawless, I'd just keep thinking dosbox
is "a joke". But probably its not, I am really
puzzled why it never worked for me for all
these 20+ years on different PCs.

**Comment by stsp** [comment]
It appears I could install dosbox-staging
and dosbox-x from snapcraft.
So when I type `dosbox-staging ./DATA.EXE`
it doesn't run data.exe, and neither does
`dosbox-x ./DATA.EXE`.
Only `dosbox ./DATA.EXE` actually runs
data.exe...
So just 1 of 3 versions can even run the
dos prog from cmdline? Really puzzled.
Plus dosbox-x start-up time is unbelievably
long. Plus both dosbox-x and doxbox starts
in a very tiny window, whereas the dosbox-staging
have the proper window size on start-up.
So just 1 of 3 can even create the proper
window on start-up...
Its not to bash on dosbox, but whenever
I am trying to use it, it falls apart for the
reasons I don't understand. :(

**Comment by stsp** [comment]
Needs to be done by properly
extending vtmr. Hacks seem to
have side-effects.
