### ISSUE TITLE
passt usermode networking

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2081]
### Discussed in https://github.com/dosemu2/dosemu2/discussions/1813

<div type='discussions-op-text'>

<sup>Originally posted by **stuaxo** October 18, 2022</sup>
Hi,
   passt looks like an interesting development for networking, aiming itself as a replacement to slirp, being taken up by qemu and podman -

http://blog.vmsplice.net/2021/10/a-new-approach-to-usermode-networking.html

https://github.com/containers/podman/pull/16141

Cheers
Stuart

</div>

**Comment by stsp** [comment]
I didn't have much luck with passt.
Filled this ticket:
https://bugs.passt.top/show_bug.cgi?id=72

It allows `links` to start, but nothing
really works. I think passt is too early
to be usable.

**Comment by stsp** [comment]
Although there is now a `passt` branch
so you can try it out.

**Comment by stsp** [comment]
Found another bug:
https://bugs.passt.top/show_bug.cgi?id=73
Still nothing works...
Well, I guess I am not the right one to keep
fixing passt.

**Comment by stsp** [comment]
So passt is now supported.
@stuaxo will you be fixing passt
so that it actually works? :)
You requested that, and I've done
my part of the deal.

**Comment by stsp** [comment]
I wonder if @mateuszviste can be
interested in looking into passt code.
He authored quite a few user-space
networking solutions in the past.

At least debugging why gopherus
doesn't accept the passt's dhcp
replies would already be a progress.

**Comment by stuaxo** [comment]
Interesting !  It's going to be a month or two before I have time, but it's now on the list of things I round-robin to.  More user friendly networking in DOSEmu2 is always a +

**Comment by stsp** [comment]
I don't yet know how is it "more
friendly". libslirp at least forks the
daemon automatically.
passt should probably be started
by systemd, but currently its not
the case.
I wish some daemon-less solution,
i.e. a lib that just spawns a thread
for tcp management. I am not
exactly sure what functionality will
be lost in that case. Perhaps DHCPs
won't get coordinated, but you can
still coordinate them using some global
resources (like files or shm).

**Comment by stsp** [comment]
> I wish some daemon-less solution,
> i.e. a lib that just spawns a thread

... which is actually exactly what happens
in libvdeslirp.c. It implements the large
framework for libslirp, like timers, poll()
emulation and many other things - all
on dosemu side! (yes, I just put it into
our repo but never looked inside). And
at the end it just spawns a thread.

Why passt is a standalone daemon, and
who needs to start it (systemd?) is unclear
to me. So IMHO libvdeslirp+libslirp is much
more user-friendly. Plus it works, while
passt has a pre-alpha quality.

**Comment by jschwartzenberg** [comment]
> Why passt is a standalone daemon, and
> who needs to start it (systemd?) is unclear
> to me.

Reading their page, they suggest this approach has security advantages.

As an end-user, I would expect the application that relies on passt (QEMU or DOSEMU2) to start the daemon in the background and kill it when it doesn't need it anymore. I would also expect each application to use its own copy of the daemon and not a single shared copy.

**Comment by stsp** [comment]
> Reading their page, they suggest this approach has security advantages.

And no quote?

> I would also expect each application to use its own copy of the daemon
> and not a single shared copy.

In this case you don't need a daemon.
The daemon is only needed to get things
coordinated, or to have special privs.

**Comment by jschwartzenberg** [comment]
From the page linked above:

> Thanks to running in a separate process from QEMU and by taking a minimalist approach, passt is able to tighten security. Its seccomp filters are stronger than anything the larger QEMU process could do. The code is clean and specifically designed for security and simplicity. I think writing passt in C was a missed opportunity. Some users may rule it out entirely for this reason. Userspace parsing of untrusted network packets should be done in a memory-safe programming language nowadays. Nevertheless, it's a step up from slirp, which has a poor track record of security issues and runs as part of the QEMU process.

**Comment by stsp** [comment]
> Thanks to running in a separate process from QEMU and by taking a minimalist
> approach, passt is able to tighten security.

Well, maybe their point is that
the networking component is
very security-sensitive, so it should
be separated and tightened.
However in this case they could
just fork() from the qemu process
internally, rather than to have the
daemon that is unclear who is going
to start.

> The code is clean and specifically designed for security and simplicity.

If only it worked...
Lets see if they will at least react
to the small patches I submitted.
So far they did not.

**Comment by stsp** [comment]
OK, my patches are now applied to
passt, and with some help from the
upstream, they (patches) actually do
even somewhat work. :)
So its not all that bad now, but still
dhcp is up to debug, and overall I
don't see how can it be any better
for us, than libslirp...

**Comment by stsp** [comment]
And in fact, because passt is so small
and slim, we could fork it and turn into
libslirp ourselves... Except for the fact
that its sources are almost as big as libslirp's.

**Comment by stuaxo** [comment]
That's good it's somewhat active. good point about wanting a layered design to enable it to work in places where a separate service isn't an option.

**Comment by stsp** [comment]
Finally nailed the DHCP problem:
https://bugs.passt.top/show_bug.cgi?id=77

**Comment by stsp** [comment]
OK, all patches are applied upstream,
so passt now supports DOS networking. :)
Even if we don't use passt, the DOS
networking will now work under qemu.
And I think this is what makes our
project unique. While there are many
DOS emulators, only we push the host
infrastructure towards the DOS support.
I am still landing the xfs patches, and
after that, we'll get the (mostly) DOS-compatible
locking in linux and posix (because posix
ofd locks are modeled after linux's impl).
There are many other projects who could
do that (samba, wine, dosbox), but seems
like no one even looks at that direction.
