### ISSUE TITLE
Launching two instances of dosemu simultaneously causes both of them to freeze

### ISSUE THREAD

**Issue by bertrandom** [dosemu2/dosemu2#2084]
**Describe the bug**
When launching two instances of dosemu at the exact same time, often both instances freeze and need to be killed.

**To Reproduce**
Steps to reproduce the behaviour:
Launch two instances of your terminal and find a way to run both commands simultaneously. iTerm2 has a feature to broadcast input to all tabs.

**Attach program/game binaries or provide an URL**
This seems to happen just from calling `dosemu` with no parameters.

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/12447539/boot.log)

**A regression?**
I was running a version of dosemu2 from April 2023 and it did not have this issue.

**Additional info**
This happens on both Ubuntu 20.04 and 22.04 for me.

**Comment by bertrandom** [comment]
https://github.com/dosemu2/dosemu2/assets/57770/d2bea377-87fa-4d95-a704-440241afa4ea

**Comment by stsp** [comment]
Should now be fixed.
Good catch!
