### ISSUE TITLE
terminal support broken by terminal clipboard update

### ISSUE THREAD

**Issue by severach** [dosemu2/dosemu2#2099]
**Describe the bug**
`dosemu -t` terminal support is broken. DOS line apps work fine. DOS full screen apps like Norton Commander and Foxpro don't paint any characters. Commands like EXITEMU and QUIT work fine, just can't see them.

**To Reproduce**
Boot DOSEmu, line text is visible.

Load NC, black screen with cursor. F10 Exit doesn't work. Press enter and F10 ANSI code is shown. Terminal emulation is not working. Type EXITEMU to exit.

Load Fox, line text is still visible. Fox full screen is not visible. Type QUIT to exit.

**A regression?**
Broken by f8d7ba65dd8a9bc311c2903647a8f7a26f7bf252. Unable to revert.

**Comment by stsp** [comment]
Try full rebuild, starting from
`make uninstall` and `git clean -fd`

**Comment by severach** [comment]
It's a package. It's always a full rebuild.

**Comment by ecm-pushbx** [comment]
I guess it may be the same cause as it was for me, a missing library for the `term` plugin: https://github.com/dosemu2/dosemu2/pull/2088#issuecomment-1712921416

**Comment by severach** [comment]
That's it.

```
checking for base64_encode_block in -lb64... no
configure: error: b64 libs not found
Configuration for term failed, disabling
```

**Comment by stsp** [comment]
So that's a missing diagnostic, not a bug.
Should now be fixed.

**Comment by severach** [comment]
That's better.

```
$ dosemu -t
ERROR: terminal support not compiled in
```
