### ISSUE TITLE
rar32.exe crashes Dosemu

### ISSUE THREAD

**Issue by 1ras** [dosemu2/dosemu2#2100]
**Describe the bug**
rar32.exe crashes Dosemu.

**To Reproduce**
1. wget ftp://ftp.rarlab.com/rar/rarx393.exe
1. Install rar32 by executing the downloaded file in Dosemu
2. CD RAR and run RAR32.EXE in Dosemu

**Attach the log**
ERROR: IP outside CS limit: ip=0x250, cs=0x97, lim=0x24f, 32=1
leavedos(dpmi_fault1:5366|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped

**A regression?**
Last version that I compiled was https://github.com/dosemu2/dosemu2/tree/d65c50710d94bcf7cb97fc5245213a72f11d1b8d which was not affected.

**Additional info**
Tried Freedos, Novell-DOS 7, DR-DOS 7.03 and 4DOS so I don't think it's related to the underlying DOS/command.com.
RAR32 is DPMI.

**Comment by stsp** [comment]
Great catch, thanks.

**Comment by 1ras** [comment]
Wow, that was fast, thanks!
