### ISSUE TITLE
Dos Navigator 1.51 fatal error with pkunzip

### ISSUE THREAD

**Issue by 1ras** [dosemu2/dosemu2#2103]
**Describe the bug**
Dos Navigator 1.51 fatal error with pkunzip:
![Screenshot_20230926_172104](https://github.com/dosemu2/dosemu2/assets/45467075/2220bda3-846f-429a-9f01-1b033d6bf157)

**To Reproduce**
1. Download Dos Navigator 1.51 from https://www.ritlabs.com/download/dn/dn151.zip and extract everything into a TEST directory
2. Download PKUNZIP.EXE from https://archive.org/download/PKUNZIP_1020/PKUNZIP.EXE and save it into the TEST directory
3. Download https://www.delorie.com/pub/djgpp/current/v2tk/allegro/all422s.zip and save it to C:\ (but do not extract it).
4. Add the TEST directory to the PATH (required by Dos Navigator to find PKUNZIP.EXE): PATH %PATH%;C:\TEST
5. Execute DN.COM
6. Within Dos Navigator navigate to the ALL422S.ZIP file and press enter to open it
7. Press enter on the ALLEGRO sub-directory (within the ALL422S.ZIP file)
8. Navigate to a text file, e.g. the AUTHORS file and press F3 to view it
9. Red fatal error message appears

**A regression?**
Yes, I did a git bisect and the issue is due to commit https://github.com/dosemu2/dosemu2/commit/988effd352b4dc2f20a439e2e3b384b919cc6708

**Additional info**
It is a bit flimsy to replicate since the issue depends on the content of the zip file (it does not happen with every zip file).
I replicated it with DR-DOS 7.03 and the dconfig.sys and dautoemu.bat that comes with Dosemu, but it might not be important.
There is no dosemurc required, everything at default.
Host system is Debian 12.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
Thanks for a bisect!

**Comment by 1ras** [comment]
Amazing, thanks!
