### ISSUE TITLE
Building in Clear Linux OS: `default-configure` fails at binutils `as` cross-assembler detection

### ISSUE THREAD

**Issue by volkertb** [dosemu2/dosemu2#2112]
**Describe the bug**

On a recent version of [Clear Linux OS](https://www.clearlinux.org/), `./default-configure`  fails at the cross-assembler detection phase, even though the available `/usr/bin/as` is an x86_64 assembler from `binutils` that supports the `--32` command-line option for building 32-bit code.

As a workaround, a symbolic link can be created as follows:

```shell
sudo ln -s /usr/bin/as /usr/local/bin/x86_64-linux-gnu-as
```

The existence of this symbolic link makes `./default-configure` complete successfully, after which `make` completes the build successfully (at least when I have supplied the argument `--disable-fdpp` to `default-configure`, I haven't tried building the project with `fdpp` yet).

**To Reproduce**

First, ensure Clear Linux OS, which is a rolling-release distribution, is up-to-date:

```shell
sudo swupd update
```

The version should be at least `40120` in the corresponding output:

```text
Update started
Version on server (40120) is not newer than system version (40120)
Update complete - System already up-to-date at version 40120
```

Then ensure that the necessary packages (or "bundles") needed to build the project are installed:

```shell
sudo swupd bundle-add binutils c-basic make c-basic-legacy
```

**NOTE**: more packages may be needed here. If you'd like me to investigate whether this list is complete or if more bundles need to be installed in the command above, please let me know.

Then check out the `dosemu2` sources and try to build them:

```shell
git clone https://github.com/dosemu2/dosemu2.git
cd dosemu2
./autogen.sh
./default-configure
```

**Attach program/game binaries or provide an URL**

n/a

**Attach the log**

```text
(...)
checking for as... /usr/bin/as
checking for i686-linux-gnu-as... no
checking for i386-elf-as... no
checking for x86_64-linux-gnu-as... no
configure: error: cross-assembler not found, please install binutils-i686-linux-gnu
```

**A regression?**
No idea. I didn't go that far investigating this.

**Additional info**

With the following workaround, the `make` built the project successfully:

```shell
sudo ln -s /usr/bin/as /usr/local/bin/x86_64-linux-gnu-as
```

The output of `as --version`:

```text
GNU assembler (GNU Binutils) 2.41
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-generic-linux'.
```

The `binutils` package was already installed and this can be done in Clear Linux OS as follows:

```shell
sudo swupd bundle-add binutils
```

Other `swupd` packages that are probably needed: `c-basic`, `make`, `c-basic-legacy` (the latter to have 32-bit C/C++ compilers as well). More bundles may or may not be needed in addition to those. If necessary, I can look into that further. Just let me know. Thanks.

**Comment by volkertb** [comment]
Update: I could also reproduce the same issue when building `dosemu2` with `fdpp`.

By the way, while building `fdpp`, I ran into the `lex: No such file or directory` error, that required me to run `export LEX=flex` before running `make`, as @stsp explained [here](https://github.com/dosemu2/fdpp/issues/227#issuecomment-1609963974).

So perhaps the `./configure` script or Makefile of `fdpp` could be enhanced to take automatically try using `flex` when `lex` isn't found. But that's of course outside the scope of this issue.

**Comment by stsp** [comment]
Configure problem should now be
fixed, please check.

**Comment by stsp** [comment]
lex should also be fixed.

**Comment by volkertb** [comment]
I rebuilt both projects without the workarounds and confirmed both issues to be fixed. Thanks for the very quick response! :rocket:
