### ISSUE TITLE
Question: how to provide libb64 sources on distros that don't have `libb64-dev`?

### ISSUE THREAD

**Issue by volkertb** [dosemu2/dosemu2#2113]
When libb64 isn't found, the configure script will disable the `term` plugin:

```text
checking for base64_encode_block in -lb64... no
Configuration for term failed, disabling
```

In [this reply](https://github.com/dosemu2/dosemu2/pull/2088#issuecomment-1712921416), @stsp gave the solution for this on Debian-based distros: `sudo apt-get install libb64-dev`.

However, on distros that don't have a libb64 development package available, such as Clear Linux OS, this is not an option.

`/usr/lib/base64` is present, but I couldn't find any available installable bundles that would provide the development files.

I did clone https://github.com/libb64/libb64 and built it with `make`. However, the Makefile of that project does not have a `make install` target. The README of the project claims that that would be "overkill" for such a project.

I tried the following (assuming the project was cloned into the directory `/path/to/libb64`):

```shell
LDFLAGS="-L/path/to/libb64/src" CFLAGS="-I/path/to/libb64/include" ./default-configure
```
The good news is that this resulted in the `term` plugin being enabled:

```text
Enabling plugins:
	gpm
	alsa
	ladspa
	extra_charsets
	term
	X
	Xkmaps
	sdl
	midimisc
	charsets
	json
	console
	modemu
	dosdrv
	doscmd
	periph
	debugger
	fdpp
```

However, when I subsequently ran `make`, it resulted in a build error in `fatfs.c` that did not occur when I built `dosemu2` earlier without adding those `LDFLAGS` and `CFLAGS` environment variables:

```text
fatfs.c: In function ‘system_type’:
fatfs.c:669:5: error: case label does not reduce to an integer constant
  669 |     case MS_D:
      |     ^~~~
fatfs.c:671:5: error: case label does not reduce to an integer constant
  671 |     case PC_D:
      |     ^~~~
fatfs.c:673:5: error: case label does not reduce to an integer constant
  673 |     case OLDDRD_D:
      |     ^~~~
fatfs.c:675:5: error: case label does not reduce to an integer constant
  675 |     case MIDDRD_D:
      |     ^~~~
fatfs.c:677:5: error: case label does not reduce to an integer constant
  677 |     case ENHDRD_D:
      |     ^~~~
fatfs.c:679:5: error: case label does not reduce to an integer constant
  679 |     case NEWPCD_D:
      |     ^~~~
fatfs.c:681:5: error: case label does not reduce to an integer constant
  681 |     case OLDPCD_D:
      |     ^~~~
fatfs.c:683:5: error: case label does not reduce to an integer constant
  683 |     case NEWMSD_D:
      |     ^~~~
fatfs.c:685:5: error: case label does not reduce to an integer constant
  685 |     case MIDMSD_D:
      |     ^~~~
fatfs.c:687:5: error: case label does not reduce to an integer constant
  687 |     case OLDMSD_D:
      |     ^~~~
fatfs.c:689:5: error: case label does not reduce to an integer constant
  689 |     case NECMSD_D:
      |     ^~~~
fatfs.c:691:5: error: case label does not reduce to an integer constant
  691 |     case FDO_D:
      |     ^~~~
fatfs.c:693:5: error: case label does not reduce to an integer constant
  693 |     case FD_D:
      |     ^~~~
fatfs.c:696:5: error: case label does not reduce to an integer constant
  696 |     case FDP_D:
      |     ^~~~
fatfs.c:699:5: error: case label does not reduce to an integer constant
  699 |     case RXO_D:
      |     ^~~~
fatfs.c:701:5: error: case label does not reduce to an integer constant
  701 |     case RXM_D:
      |     ^~~~
fatfs.c:703:5: error: case label does not reduce to an integer constant
  703 |     case RXN_D:
      |     ^~~~
fatfs.c:705:5: error: case label does not reduce to an integer constant
  705 |     case MOS_D:
      |     ^~~~
fatfs.c:707:5: error: case label does not reduce to an integer constant
  707 |     case OLDMOS_D:
      |     ^~~~
fatfs.c: In function ‘fatfs_get_part_type’:
fatfs.c:1122:3: error: case label does not reduce to an integer constant
 1122 |   case OLDMSD_D:
      |   ^~~~
fatfs.c:1123:3: error: case label does not reduce to an integer constant
 1123 |   case NECMSD_D:
      |   ^~~~
fatfs.c:1124:3: error: case label does not reduce to an integer constant
 1124 |   case OLDPCD_D:
      |   ^~~~
fatfs.c: In function ‘mimic_boot_blk’:
fatfs.c:1648:5: error: case label does not reduce to an integer constant
 1648 |     case NEWMSD_D:                     /* for IO.SYS, MS-DOS version >= 7 */
      |     ^~~~
fatfs.c:1664:5: error: case label does not reduce to an integer constant
 1664 |     case NEWPCD_D:              /* MS-DOS 4.0 -> 6.22 / PC-DOS 4.0 -> 7.0 */
      |     ^~~~
fatfs.c:1665:5: error: case label does not reduce to an integer constant
 1665 |     case MIDMSD_D:
      |     ^~~~
fatfs.c:1677:5: error: case label does not reduce to an integer constant
 1677 |     case OLDPCD_D:              /* old MS-DOS & PC-DOS < v4.0 */
      |     ^~~~
fatfs.c:1678:5: error: case label does not reduce to an integer constant
 1678 |     case OLDMSD_D:
      |     ^~~~
fatfs.c:1693:5: error: case label does not reduce to an integer constant
 1693 |     case NECMSD_D:
      |     ^~~~
fatfs.c:1702:5: error: case label does not reduce to an integer constant
 1702 |     case OLDDRD_D:              /* DR-DOS */
      |     ^~~~
fatfs.c:1706:5: error: case label does not reduce to an integer constant
 1706 |     case MIDDRD_D:              /* DR-DOS with IBM compatibility naming */
      |     ^~~~
fatfs.c:1711:5: error: case label does not reduce to an integer constant
 1711 |     case ENHDRD_D:              /* Enhanced DR-DOS 7.01.07+ */
      |     ^~~~
fatfs.c:1738:5: error: case label does not reduce to an integer constant
 1738 |     case FDO_D:                 /* FreeDOS, orig. Patv kernel */
      |     ^~~~
fatfs.c:1746:5: error: case label does not reduce to an integer constant
 1746 |     case FD_D:                  /* FreeDOS, FD maintained kernel */
      |     ^~~~
fatfs.c:1763:5: error: case label does not reduce to an integer constant
 1763 |     case RXO_D:
      |     ^~~~
fatfs.c:1764:5: error: case label does not reduce to an integer constant
 1764 |     case RXM_D:
      |     ^~~~
fatfs.c:1776:5: error: case label does not reduce to an integer constant
 1776 |     case RXN_D: {
      |     ^~~~
fatfs.c:1833:5: error: case label does not reduce to an integer constant
 1833 |     case MOS_D:                 /* PC-MOS/386 */
      |     ^~~~
fatfs.c:1834:5: error: case label does not reduce to an integer constant
 1834 |     case OLDMOS_D:              /* PC-MOS 5.01 */
      |     ^~~~
```

Maybe those environment variables actually override something instead of being appended?

Maybe I'm making a silly mistake here.

Thank you for any insights you can provide here.

**Comment by stsp** [comment]
You can use CPPFLAGS instead of CFLAGS.
As for compiler error - please find out
which exactly variable change leads to
this. I vaguely remember that problem
with some older versions of gcc, but it
should be unrelated to any flags.
There is always an option to do
`CC=clang ./default-configure`

**Comment by volkertb** [comment]
The GCC version on this system is clearly not outdated:

```
gcc (Clear Linux OS for Intel Architecture) 13.2.1 20231011 releases/gcc-13.2.0-335-g16a4df2743
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

But I'll try building with Clang as you suggested.

**Comment by volkertb** [comment]
Your suggestion to try `CPPFLAGS` instead of `CFLAGS` solved it! :slightly_smiling_face: I replaced `CFLAGS` with `CPPFLAGS` and this time it worked, with GCC:

```shell
LDFLAGS="-L/path/to/libb64/src" CPPFLAGS="-I/path/to/libb64/include" ./default-configure
make
sudo make install
dosemu -t
```

:+1: 

I also tried this with the `CC=clang` option as you also suggested, and building it like this with Clang worked too, including a functional `term` plugin:



```shell
git reset --hard
git clean -df
./autogen.sh
LDFLAGS="-L/path/to/libb64/src" CPPFLAGS="-I/path/to/libb64/include" CC=clang ./default-configure
make
sudo make install
dosemu -t
```

:+1:

Thanks!

Would be an idea to document this in the README or INSTALL configuration somewhere, for people building this on distros that don't have an easy way of installing the `libb64` development package?

**Comment by stsp** [comment]
I dont know would it make sense to
document or not, because your finding
about cflags is inconvincing to me.
You can try to reproduce that on ubuntu
and fill another ticket so that I can see
it myself first.

**Comment by volkertb** [comment]
It will almost certainly work fine in Ubuntu or Debian, since they have a `libb64-dev` package that can easily be installed through apt. Likewise, on Fedora one can install the `libb64-devel` package through dnf.

This problem occurs on distros that don't have a libb64 development package available in their package repository, such as Clear Linux OS. Usually, this can be worked around by downloading the upstream sources of the required library and building and installing them with `./configure && make && sudo make install`, but the upstream libb64 project (or at least [the fork of that project on GitHub](https://github.com/libb64/libb64)) doesn't have a `make install` target defined in its Makefile. It looks like the package maintainers of the more popular distros took care of that themselves.

I guess it could be argued that documenting "generic Linux installation instructions" (that don't assume a particular distro) is outside the scope and responsibility of this project.

Maybe an alternative option would be to allow people to download the libb64 sources to a documented subfolder of the `dosemu2` project, and let dosemu2 automatically build and include that library when it finds those sources in said subfolder? Or alternatively, add support for an optional LIBB64_SRC_PATH environment variable, which would be listed and documented in the the output of `default-configure --help`?

**Comment by stsp** [comment]
But haven't you already solved the
problem with the use of CPPFLAGS
and LDFLAGS? Why it is not a solution?

**Comment by volkertb** [comment]
Sorry, yes it was, but I was talking about my documentation suggestion, as in: adding mention of this to the README or INSTALL file.

But I guess that this GitHub issue could also more or less be considered "documentation" for anybody who runs into the same issue, and searches for the error messages above.

~~Perhaps I should open a feature request at https://github.com/libb64/libb64 for them to just add a `make install` target to their Makefile, to simplify the dosemu2 build process for those who like me are on a distro that doesn't have a libb64 development package in its repository.~~ **Update**: that project doesn't allow people to create issues, only pull requests. I don't want to go down that rabbit hole, to be honest. Oh well...

Thanks again.

**Comment by stsp** [comment]
I am not sure how will that help.
You may or may not add "make install"
to them, but this will unlikely affect the
fact that this lib is not in a ClearLinux
repository. So if you create a build
recipe for dosemu2, you need it to
build libb64 too. And if it does so,
"make install" barely makes the difference.

**Comment by stsp** [comment]
Or for example adding libb64 sources
into dosemu2 build tree barely helps for
the very same reason: if you create your
own recipe, it doesn't matter where to
build libb64, and whether to use
LDFLAGS or `make install`.
So what exactly is a problem?

**Comment by stsp** [comment]
> Update: that project doesn't allow people to create issues, only pull requests.
> I don't want to go down that rabbit hole, to be honest. Oh well...

And also their license is "strange".
I would trust that lib only when its built
by fedora or ubuntu (as in that case I
trust them), but I can't suggest building
it on your own, as I don't know the
implications of their license.

**Comment by stsp** [comment]
https://github.com/libb64/libb64/pull/8
Here you go for the `make install`.
