### ISSUE TITLE
Disabling plugins in `default-configure` script is awkward, and apparently buggy

### ISSUE THREAD

**Issue by volkertb** [dosemu2/dosemu2#2116]
**Describe the bug**

I'm trying to build `dosemu2` without the ALSA plugin. Instead, I prefer to have audio exclusively outputted though Pulseaudio (or in my case pipewire-pulse), through the `libao` library, which I have also built explicitly without ALSA support.

However, it looks like you can only tell `./default-configure` which plugins to **enable**, using `--enable-plugins=[comma-separated list]`. There is no `--disable-plugins=[comma-separated list]` counterpart to that argument that selectively **disables** plugins that are enabled by default.

So what I did was first run `./default-configure` to get the list of plugins that were enabled by default:

```text
Enabling plugins:
	libao
	gpm
	alsa
	ladspa
	extra_charsets
	term
	X
	Xkmaps
	sdl
	midimisc
	charsets
	json
	slirp
	console
	modemu
	dosdrv
	doscmd
	periph
	debugger
	fdpp
```

And then I tediously crafted a comma-separated list from this list of defaults, leaving out `alsa`:

```shell
./default-configure --enable-plugins=libao,gpm,ladspa,extra_charsets,term,X,Xkmaps,sdl,midimisc,charsets,json,slirp,console,modemu,dosdrv,doscmd,periph,fdpp
```

(Actually, in my specific case, I also had to supply the environment variables `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig`,  `LDFLAGS="-L/path/to/libb64/src"` and `CPPFLAGS="-I/path/to/libb64/include"` to the `default-configure` script, but that' outside the scope of this specific bug report.)

This resulted in a duplicate list, with each of the explicitly enabled plugin being listed twice, and `alsa` still being listed as well, albeit only once:

```text
Enabling plugins:
	libao
	gpm
	alsa
	ladspa
	extra_charsets
	term
	X
	Xkmaps
	sdl
	midimisc
	charsets
	json
	slirp
	console
	modemu
	dosdrv
	doscmd
	periph
	debugger
	fdpp
	libao
	gpm
	ladspa
	extra_charsets
	term
	X
	Xkmaps
	sdl
	midimisc
	charsets
	json
	slirp
	console
	modemu
	dosdrv
	doscmd
	periph
	debugger
	fdpp
```

Also, running `make` after than eventually resulted in a compilation error somewhere. Something with symbols being declared more than once, I believe.

It looks like the explicit selection of plugins to enable gets appended to the default list of enabled plugins, instead of replacing it.

This is actually a combined bug report and feature request. A bug report because explicitly supplying the list of plugins to enable appears to be broken. And a feature request, because it would also be much more convenient if we could just explicitly disable one or several plugins using a `--disable-plugins=[comma-separated list]` argument.

Thank you kindly for considering.

**To Reproduce**

```shell
./default-configure --enable-plugins=libao,gpm,ladspa,extra_charsets,term,X,Xkmaps,sdl,midimisc,charsets,json,slirp,console,modemu,dosdrv,doscmd,periph,fdpp
```

**Attach program/game binaries or provide an URL**

N/A

**Attach the log**

N/A

**A regression?**

I have no idea

**Additional info**

If you need me to provide more info, just let me know. Thanks.

**Comment by stsp** [comment]
default-configure looks into
`compiletime-settings` file.
There you can write
`plugin_alsa off`.
Or you can call `./configure` directly,
and pass `--enable-plugins=` to it.
But I don't recommend doing that,
because alsa plugin is needed only
for sound _recording_, rather than
output.
