### ISSUE TITLE
Repo for Fedora 39 not working

### ISSUE THREAD

**Issue by ghost** [dosemu2/dosemu2#2124]
Hi, and thank you for this software. I haven't been able to install it using the dnf method for Fedora 39. I don't know what the problem is, but it actually fails in my command line with:
sudo dnf copr enable stsp/dosemu2
Cheers, Josh

**Comment by stsp** [comment]
I also don't know, here's the log:
https://download.copr.fedorainfracloud.org/results/stsp/dosemu2/fedora-39-x86_64/06679713-dosemu2/backend.log.gz
Its always the same, and all other
builds, except fedora-39, work fine...

**Comment by stsp** [comment]
I filled up this ticket:
https://github.com/fedora-copr/copr/issues/3016
Maybe that can help.

**Comment by stsp** [comment]
Seems to now work.
