### ISSUE TITLE
How to decode payload in debug output of the packet driver

### ISSUE THREAD

**Issue by bolle732** [dosemu2/dosemu2#2125]
I'm trying to understand the packet driver and enabled the debug output with `-D+P`. It prints the payload like this:

` Payload:
 06 04 00 02 52 55 0a 00 02 03 0a 00 02 03 66 62 78 aa 22 da 0a 00 02 0f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

Is there a tool which helps in analyzing this packet data? I tried `https://packetor.com/`, but it tells me `Malformed Packet`.

**Comment by stsp** [comment]
I think you need to hack the
`printbuf()` function to dump
the entire packet as bytes.
Currently it prints headers and
payload separately.

**Comment by stsp** [comment]
Or alternatively you need to
tell the decoder that this is an
l3 payload,

**Comment by bolle732** [comment]
Hi Stas, perfect and thanks for your hint. Will try first to find an L3 decoder and the have a look to the `printbuf()`funkction.

**Comment by andrewbird** [comment]
@bolle732 have you tried wireshark? I believe you can import from [hex dump](https://www.wireshark.org/docs/wsug_html_chunked/ChIOImportSection.html) if text is in the right format, but you could probably run it on the linux interface (tap0?) behind the packet driver to capture traffic which I suspect may be easier and will give you context.

**Comment by bolle732** [comment]
I haven't but 'll try that in the next days. Thank you for the hint.
