### ISSUE TITLE
disable startup messages

### ISSUE THREAD

**Issue by ftoledo** [dosemu2/dosemu2#2126]
hi! i use dosmeu2 to run DOS BBS doors on Debian system, 
Is there a way to hide these output messages when starting dosemu?

![imagen](https://github.com/dosemu2/dosemu2/assets/95441/cd3f5b8e-3d9b-461f-a156-de2cc7d622e6)

![imagen](https://github.com/dosemu2/dosemu2/assets/95441/9a3abf01-5159-4eb6-96ee-72e4722d3bdf)

![imagen](https://github.com/dosemu2/dosemu2/assets/95441/d60832a3-1b28-436a-af0e-1dde9a6707da)

![imagen](https://github.com/dosemu2/dosemu2/assets/95441/7dbf47b7-f7d6-47bf-b468-211b14d14127)

**Comment by stsp** [comment]
Try `dosemu -quiet`
