### ISSUE TITLE
File region locking not working for LORD (Legend of the Red Dragon)

### ISSUE THREAD

**Issue by bertrandom** [dosemu2/dosemu2#2130]
**Describe the bug**
I'm working on an implementation where I'm running Legend of the Red Dragon where multiple people can run it through different instances of dosemu2, but sharing the same filesystem.

When two players start the game at the same time, both instances write to `PLAYER.DAT`, but they write to different regions of the file, so they should be able to do so. Instead, the program thinks the file is missing on one of the instances when they try to write to it at the same time. Similarly, when a player exits the game, it also flushes to `PLAYER.DAT`. So the likelihood of players starting the game at the same time or starting and exiting the game, or both exiting the game becomes higher the more players that are playing the game at the same time.

It's possible that there's a bug in the game's file locking code but it does seem like the PLAYER.DAT disappears while another instance is writing to it in my testing.

**To Reproduce**
Steps to reproduce the behaviour:
I've attached a c drive with a directory called EXAMPLE that has an instance of Legend of the Red Dragon.

Open two instances of dosemu.

Instance 1:
```
cd example
start
```

When prompted for name or handle, leave it as SYSOP and hit enter

After seeing the banner, hit Enter again.

You should see the prompt, "Your choice, warrior? [E]: "

Stop here and switch to Instance 2:
```
cd example
start
```

When prompted for name or handle, set it to SYSOP2 and hit enter

After seeing the banner, hit Enter again.

You should see the prompt, "Your choice, warrior? [E]: "

Now, simultaneously send the keystroke `E` to both dosemu instances at the same time.

On one of the instances, you may see:
```
  ** ERROR!  Can't open player.dat file, man. **
```

or

```
PLAYER.DAT not found!
Halting!
```

I had to repeat this procedure a few times to get it to repro consistently. Another option is to get both to the main menu of the game (by hitting enter a bunch) and then sending `Q` and `y` to quit the game simultaneously to both instances, where they both write to `PLAYER.DAT` at the same time, triggering the same error.

**Attach program/game binaries or provide an URL**
[lord.zip](https://github.com/dosemu2/dosemu2/files/13657259/lord.zip)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/13657264/boot.log)

**A regression?**
Not aware of a dosemu2 version where this is working.

**Additional info**
I've tested with the TESTLOCK.ZIP used here: https://github.com/dosemu2/dosemu2/issues/270 and it passes all the tests.

https://github.com/dosemu2/dosemu2/assets/57770/fc58cfb4-9303-4103-842b-214fb7f95a4c

**Comment by stsp** [comment]
Please add `-D9+Ddif` log.
How do you know there is any locking
code in the game? Maybe it just works
on a private copy of the file, then removes
the original and copies the new one over,
or something like that.
Files usually do not disappear by themselves.

**Comment by bertrandom** [comment]
[bootlog.zip](https://github.com/dosemu2/dosemu2/files/13657514/bootlog.zip)

> How do you know there is any locking
> code in the game? Maybe it just works
> on a private copy of the file, then removes
> the original and copies the new one over,
> or something like that.

The `HISTORY.DOC` file refers to file locking improvements, but also this is a BBS door game so it seems expected that multiple BBS nodes would be operating on the same files. It's possible that the author didn't implement locking on this particular file (I don't have the source code). Other aspects of the game get around this by having specific files for each node (e.g. mail, fighting), but the player.dat is the file that is shared by all the different nodes. The file itself is just a series of Turbo Pascal structures, one after another.

**Comment by stsp** [comment]
I don't see any errors in the log
related to player.dat. You probably
need to attach 2 logs: the one that
has open failure, and another one
that lead to such failure in a parallel
process.

But I see it plays around (including
the removals) of the file `playext.dax`.
What is playext.dax?

**Comment by stsp** [comment]
Also I am completely unsure the
support of multiple players means
running multiple instances of this
BBS. How do you suppose it to work
on a real machine?
I very much suspect you need to run
just 1 instance, and somehow it can
support multiple users by itself.

**Comment by stsp** [comment]
The way locks are supposed to work
in DOS, implies a client-server model.
If multiple clients access the same file
on a server, then they can lock it to
prevent other clients from modifying
it at the same time.
But your BBS is a "server" by itself,
not a client. It therefore doesn't need
to request any locks from dosemu2.
And indeed, there is 0 locking attempts
in the log.

So I really very much suspect you just
do something you shouldn't be doing.

**Comment by bertrandom** [comment]
Not sure what playext.dax is - there's a playext.dat but it doesn't seem to get modified during the game start or end.

> Also I am completely unsure the
> support of multiple players means
> running multiple instances of this
> BBS. How do you suppose it to work
> on a real machine?
> I very much suspect you need to run
> just 1 instance, and somehow it can
> support multiple users by itself.

I believe multi-node BBSes that ran on the same computer usually did so by having multiple nodes under Desqview or OS/2. You can configure multiple nodes in LORD - I haven't done so here to keep the repro case pretty straightforward, but the idea would be that each node of the BBS would launch a different instance of LORD with a different node number when the door game is launched.

But I guess it's possible that Desqview or OS/2 prevented the two processes from writing to the file at the same time?

Another option in the real-world I guess is that there are several computers but have a network share for the LORD instance.

Is there a way to write to different boot.log files for different dosemu instances? I can try to acquire better logs..

**Comment by stsp** [comment]
> I believe multi-node BBSes that ran on the same computer usually did so by having
> multiple nodes under Desqview or OS/2.

What does make you believe this is
the case? history.doc you mentioned,
says this:
```
* Completly rewritten file routines, can now support 150 players at once.
  (Old limit was 39)
```
Doesn't look like it is saying you need
to run 150 instances under desqview,
and I pretty much suspect the limit of
39 players had nothing to do with
desqview just as well. Also running
150 processes under a DOS multitasker,
doesn't sound realistic. It was supposed
to run a few processes, maybe a dozen,
but not hundreds. There were no HW
resources for such things.

> Is there a way to write to different boot.log files for different dosemu instances?
> I can try to acquire better logs..

You can use -o to write the log to any
location you want. But unless you supply
an evidence that what you do is even
remotely valid, I don't think its worth a
trouble.

**Comment by stsp** [comment]
> But I guess it's possible that Desqview or OS/2 prevented the two processes
> from writing to the file at the same time?

No, unless your client uses locking.
Locking is exactly for that.
I suspect with desqview you need
share.exe to enable the locking.
OS/2 probably provides the redirector,
similar to dosemu2.

**Comment by bolle732** [comment]
If you want to run multiple DOSEmu2 clients on the same `drive_c`, you'll should be able to do that with an overlay filesystem like ie. AUFS or SquashFS. So, every clients can use the same files and the changes go to different locations.

I did that some years ago and it worked very well.

**Comment by stsp** [comment]
I don't think this is what he wants, but
in any case, what you suggest, may
probably only work if you provide every
dosemu2 instance with a separate
mount-point that has a separate overlay.
It would be interesting to support such
setup automatically. Maybe the tools like
AppImage or similar can create such
overlays, and dosemu2's wrapper script
can ask them to do so, and use that as
drive_c. We could do with some game
distributing this way.
I haven't found the time too look around
for such solution, so maybe you can. :)

**Comment by stuaxo** [comment]
Overlays seem to be what docker does behind the scenes, and it wouldn't surprise me if flatpak does too.

Probably quite straightforward to do - in the case of docker I'm pretty sure people have re-implemented it in bash before (the bocker project) so if licenses are compatible it could be worth looking there for a quick reference.

**Comment by bolle732** [comment]
> I don't think this is what he wants, but in any case, what you suggest, may probably only work if you provide every dosemu2 instance with a separate mount-point that has a separate overlay. It would be interesting to support such setup automatically. Maybe the tools like AppImage or similar can create such overlays, and dosemu2's wrapper script can ask them to do so, and use that as drive_c. We could do with some game distributing this way. I haven't found the time too look around for such solution, so maybe you can. :)

Yes, I had it's own mount point for each instance. Don't remember if I even combined it with a jail for security. Hard time at the moment too for me. End of year is near...

**Comment by stsp** [comment]
> Overlays seem to be what docker does behind the scenes, and it wouldn't surprise
> me if flatpak does too.

I don't think you want docker for
distributing DOS games... Unless
you want to distribute them together
with dosemu2 itself, which is not
permissible due to license incompats.
AppImage looks like the best solution
for that task.
Someone needs to AppImage a game
or 2...
But not in this ticket.
