### ISSUE TITLE
Does not start due to `undefined symbol: FdppKernelLoad`

### ISSUE THREAD

**Issue by bolle732** [dosemu2/dosemu2#2131]
**Describe the bug**
Since some weeks, I'm unable to start DOSEmu2 on my Ubuntu 20.04 AMD64 notebook. Starting `dosemu` gives the following:
```
ERROR: /usr/local/lib/dosemu/libplugin_fdpp.so: /usr/local/lib/dosemu/libplugin_fdpp.so: undefined symbol: FdppKernelLoad
ERROR: can't load fdpp
ERROR: Bootable drive not found, exiting
```
This is without any `dosemurc`. Moving away `userhook.sys` doesn't help to.

**To Reproduce**
Steps to reproduce the behaviour:

Compile and install FDPP and DOSEmu2 from master on Ubuntu 20.04 AMD64

**Attach program/game binaries or provide an URL**
If the problem needs specific DOS files to reproduce, please attach
or provide the download URL.

There are no special DOS files related.

**Attach the log**
It is located in ~/.dosemu/boot.log
Unless you get the plain crash of dosemu2,
you may need to enable some logging flags
to make your report more useful.
See description of -D option in `man dosemu.bin`.

[boot.log](https://github.com/dosemu2/dosemu2/files/13659946/boot.log)

**A regression?**
If you happened to know this problem didn't
exist on dosemu1 or some earlier versions of
dosemu2, please write.

Yes, since several week. Unfortunately, I can't say the exact commit.

**Additional info**
Please write here if you did any dosemu2 setup
customizations, like installing any custom DOS
or command.com, or altering the dosemu2
configuration settings. Note that freedos, even
from dosemu-freedos package of dosemu1, counts
as a custom DOS and should be mentioned here.
Also make a note if it is a protected or real-mode
program. If you suspect any particular dosemu2
component (DPMI, PIC, PIT etc) to be responsible
for the problem, please write.

`USERHOOK.SYS`
```
FILESHIGH=120
STACKS=0
```

```
$ ll /usr/local/lib/fdpp/
total 26156
drwxr-xr-x 2 root root     4096 Dez 13 11:51 ./
drwxr-xr-x 8 root root     4096 Aug 16  2022 ../
lrwxrwxrwx 1 root root       17 Dez 13 11:48 libfdldr.so -> libfdldr.so.35.10*
-rwxr-xr-x 1 root root   186168 Dez 13 11:48 libfdldr.so.35.10*
lrwxrwxrwx 1 root root       16 Dez 13 11:48 libfdpp.so -> libfdpp.so.35.10*
-rwxr-xr-x 1 root root 13274344 Nov 27 08:39 libfdpp.so.34.10*
-rwxr-xr-x 1 root root 13309944 Dez 13 11:48 libfdpp.so.35.10*
```

```
$ ll /usr/local/bin/dosemu.bin /usr/local/bin/dosemu.bin
-rwxr-xr-x 1 root root 18451488 Dez 13 11:48 /usr/local/bin/dosemu.bin*
-rwxr-xr-x 1 root root 18451488 Dez 13 11:48 /usr/local/bin/dosemu.bin*
```

**Comment by bolle732** [comment]
I did a `make clean` / `pristine` and even a new `clone` did not help. There are no kernel files in the `drive_c`:

```
$ ll drive_c/
total 44
drwxr-xr-x 5 <USER>  4096 Dez 13 12:08 ./
drwxr-xr-x 4 <USER>  4096 Dez 13 12:10 ../
drwxrwxr-x 9 <USER>  4096 Dez 13 11:48 ensemble/
-rw-r--r-- 1 <USER>    33 Aug 22  2022 go.bat
-rw-r----- 1 <USER> 14941 Aug 22  2022 mem.exe
drwxr-xr-x 3 <USER>  4096 Nov 23 08:07 mtcp/
drwxr-xr-x 4 <USER>  4096 Nov 10 11:10 tmp/
-rw-r--r-- 1 <USER>    23 Jun  7  2023 userhook.sys

```

**Comment by stsp** [comment]
See `ldd /usr/local/lib/dosemu/libplugin_fdpp.so`

**Comment by stsp** [comment]
Perhaps you have fdpp also installed
elsewhere, like in `/usr/lib/fdpp`?

**Comment by bolle732** [comment]
This is the output from `ldd`:
```
$ ldd /usr/local/lib/dosemu/libplugin_fdpp.so
	linux-vdso.so.1 (0x00007fff12ddf000)
	libfdpp.so.35.10 => /usr/local/lib/fdpp/libfdpp.so.35.10 (0x00007ff8d2ddc000)
	libubsan.so.1 => /lib/x86_64-linux-gnu/libubsan.so.1 (0x00007ff8d2455000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff8d2432000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff8d2240000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff8d205e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff8d1f0f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff8d1ef2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff8d1eec000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff8d2ef1000)
```
I've searched for `fdpp`:
```
$ find /usr/ -name "fdpp"
/usr/local/share/fdpp
/usr/local/lib/fdpp
/usr/local/include/fdpp
```

**Comment by stsp** [comment]
So its linked to `libfdpp.so.35.10`
but not to `libfdldr.so.35.10`, which
is very strange.
Please show the output of
`pkg-config --libs fdpp`.
There is probably an outdated
pkgconf file somewhere.

**Comment by bolle732** [comment]
This is what I get:
```
$ pkg-config --libs fdpp
-L/usr/local/lib/fdpp -lfdpp -lfdldr
```

**Comment by stsp** [comment]
Please show the content of
`src/plugin/fdpp/Makefile.conf`
in dosemu2 source tree.

**Comment by bolle732** [comment]
Here it is:
```
$ cat src/plugin/fdpp/Makefile.conf
#
# (C) Copyright 1992, ..., 2014 the "DOSEMU-Development-Team".
#
# for details see file COPYING in the DOSEMU distribution
#
# Makefile.conf.in for DOSEMU
#
# This file is included by all Makefiles

FDPPFLAGS :=  
FDPPLIB := -L/usr/local/lib/fdpp -lfdpp -Wl,-rpath,/usr/local/lib/fdpp 
VG_CFLAGS = 
VG_LIBS = 
```

**Comment by stsp** [comment]
So it misses -lfdldr, but I don't know
how can that be, if pkg-config prints
it for you...
You'll have to debug the configure
script a little. You need to find out where
it sets `PKG_CONFIG_PATH` to. Then
after the line
```
PKG_CHECK_MODULES([FDPP], [fdpp >= 1.7],,
    AC_MSG_ERROR([fdpp installation not found or too old]))
```
you can print $FDPP_LIBS to see their
initial content.

**Comment by bolle732** [comment]
Hi Stas, thanks a lot for the hints!

I commented some environment variables in my `.bashrc` from another project using Watcom and used the full path when executing `default-configure -d`. Now, it works again ;-)

I'll need to debug again to find the real culprit. Either the problem arises do to my machine being a member of a domain and the `$HOME` contains `/home/<DOMAIN>/<USER>` or one the environment variables from the other project produced a clash somewhere.

```
export WATCOM=/home/<USER>/watcom
export EDPATH=$WATCOM/eddat
export INCLUDE=$WATCOM/lh:$WATCOM/h
export ROOT_DIR=<SOME_PATH>
export LOCAL_DIR=<SOME_PATH>
export PATH=$WATCOM/binl64:$WATCOM/binl:$ROOT_DIR/bin:$PATH
```

Should be close this issue and I open it again when I got more information?

**Comment by stsp** [comment]
I think you have another (older)
fdpp.pc somewhere...

**Comment by bolle732** [comment]
I couldn't find another `fdpp.pc` in my `/usr`.

```
$ find /usr/ -type f -name fdpp.pc
/usr/local/lib/pkgconfig/fdpp.pc
```

**Comment by bolle732** [comment]
This are the ones of the FDPP sources:
```
$ cat fdpp/fdpp.pc
libdir=/usr/local/lib
fdpplibdir=${libdir}/fdpp

Name: fdpp
Description: 64-bit DOS core
Version: 1.7
Libs: -L${fdpplibdir} -lfdpp -lfdldr


$ cat fdpp/fdpp.pc.in 
libdir=@LIBDIR@
fdpplibdir=${libdir}/fdpp

Name: fdpp
Description: 64-bit DOS core
Version: @VERSION@
Libs: -L${fdpplibdir} -lfdpp -lfdldr
```
