### ISSUE TITLE
make Flatpak on CI

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2132]
It is said around that AppImages can
be easily generated on CI stage.
As dosemu2 is a monster of silly deps
(djgpp, nasm-segelf etc), people who
do not use PPA, have problems building
it. But AppImage may help.
Andrew, would you like to take a look?

**Comment by probonopd** [comment]
Well, the poor guy who wants to help with the AppImage is running into exactly these issues now, trying to build it on Alpine Linux.

**Comment by stsp** [comment]
Hi @probonopd 
So if we have sdl deps broken on
alpine, then perhaps you can help
us build an AppImage on a github
CI instead?

**Comment by stsp** [comment]
So far I added Flatpack support.
It can be built with `make flatpak-build`.
There are at least 2 different instructions
how to build that on github:
https://github.com/flatpak/flatpak-github-actions
https://github.com/andyholmes/flatter
But I don't understand much of them. :)

Andrew, can you take a look?

**Comment by stsp** [comment]
Flatpak now built on CI.

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2/wiki/installing-Flatpak-package

**Comment by stuaxo** [comment]
This is great + probably the way, I'll use dosemu2 when I'm not building it.

**Comment by stsp** [comment]
The problem is that flatpak wants
to provide its own sandboxing, not
allowing the one that dosemu2 has
already. As the result, dosemu2's
native sandboxing is disabled, and
flatpak's is circumvented by allowing
the entire `/home/$USER` access
(and also `/tmp` and `/run/user`).
IMHO it is a very bad choice to force
your sandboxing on others, not allowing
them to use their own, as that leads
only to security compromise.
But yeah, they can show that dosemu2
requires an access to `~`, `/tmp` and `/run/user`
allowing the user to either trust an app
or cancel the installation. :) Which is IMHO
the worst thing the one can ever do. Its
like saying to the user "we are insecure:
if you continue the installation, you are
on your own, and don't bother us once
you are hacked". I hoped to never use
that approach to security, but flatpak
forces it on me, and I hate that.

Maybe snap can suit better, but I am
sceptical about that, and the last time I
checked snap didn't have the per-user
unpriv'd installs.

I think homebrew is an excellent tool,
but its so unpopular that I don't think
I'll bother providing dosemu2 for homebrew.

> This is great + probably the way

I see it as a disaster, but its better than
nothing at all. Once we enter debian,
things would be less complicated.

**Comment by stsp** [comment]
> I think homebrew is an excellent tool,
> but its so unpopular that I don't think

Hmm, the simple `pip install homebrew`
just proved me wrong. :)
Homebrew is right here, and is popular.
OK then, lets see if it suits.

**Comment by stsp** [comment]
Oops: https://pypi.org/project/homebrew/
So `pip install homebrew` obviously
installs the wrong thing. :(

**Comment by stuaxo** [comment]
Yep, the instructions at https://brew.sh/ are what you want.

**Comment by stsp** [comment]
Yes, but they only say how should
_I_ install it on my machine. Since
its not on any user's machine and
is not available via distro repos or
any other popular repos, its probably
a dead horse.

**Comment by stsp** [comment]
And it needs `sudo` during install, so
I can't install it from an appimaged
game package for instance.

**Comment by stuaxo** [comment]
The flatpak sandboxing thing is interesting, and yes - entering debian would change things.

I'll probably try it and play with flatseal to see what happens/breaks with sandboxing options.

**Comment by stuaxo** [comment]
I guess /home/$USER is because the user will probably want files there, many programs will want this - though I guess the abitrary nature of what may be run in DOS makes this more dangerous ?

I need to go and look up why /tmp and /run need to be the versions of these outside the sandbox.

**Comment by stsp** [comment]
The main problem with flatpak is that
you can't add user there (or at least I
haven't found such possibility), or use
`sudo` for `sudo make install` to use
`chown`.

> I guess /home/$USER is because the user will probably want files there, many programs will want
> this - though I guess the abitrary nature of what may be run in DOS makes this more dangerous ?

Of course!
Which is why dosemu2 has the very
fine-grained security sandboxing that
allows an access to the very small subset
of directories under $HOME.

> I need to go and look up why /tmp and /run need to be the versions of these outside the sandbox.

`/tmp` is used by my appimages, they mount
themselves there. dosemu2 should be able to
run them from there. `/run/user` is used for
dosdebug communication.

**Comment by stsp** [comment]
In principle I can move appimages
to `/run/user` and vacate `/tmp`.
Will do, as sharing `/tmp` is obviously
silly.

**Comment by stuaxo** [comment]
I'll read up a bit more about flatpak and portals.

GUI apps have it easy re: opening up directories, most are using some toolkit and that implicitly supports portals: the user wants to save a file, and when they navigate to a directory in the file chooser widget (say Gtk/Qt or some other portal supporting widget), they get granted permission to that directory in the background.

(Those supporting toolkits will probably be calling the portal API via DBUS behind the scenes).

In the world of DOS program in DOSEMU2, I'm not quite sure where or how that fits in:  id DOSEMU2 was run from a GUI, then that could have config options for this stuff, where you would maybe do stuff like configure the drives DOSEMU uses, and in doing that navigation enable the portals... but DOSEMU2 doesn't work like that, so it's hard to say how permissions to directories + sandboxing should work without looking at this a bit more.

**Comment by stsp** [comment]
I didn't know about an ability to
dynamically add directories to the
container. I was adding them statically
into the manifest. I wonder how that
works: so the GUI file chooser is somehow
allowed to access the host's `/home`
fully, and when you select some path,
that path gets mounted inside the
container?
This is indeed an interesting technique,
as it allows the user to "authenticate"
the path. Of course this can't work for
non-GUI apps, as even if there is an API
for dosemu2 to request the path, it would
be silly to ask the user to authenticate
every new path that dosemu2 wants to
access now. User has already put all these
dirs into his `dosemurc`, and that should
serve as an authentication point.

**Comment by stuaxo** [comment]
> https://github.com/dosemu2/dosemu2/wiki/installing-Flatpak-package

Confirming this seems to work, I didn't extensively test, but could navigate + launch dos navigator 2 from the apps directory.

**Comment by stsp** [comment]
This works, but sandboxing disabled. :(
You may want to try also this one:
https://github.com/dosemu2/mkdexe2
Once again, it works, but sandboxing is
also disabled. :) This time because of fuse...

**Comment by stsp** [comment]
Flatpak devs told me about
`flatpak-spawn`, which can automatically
duplicate a sandbox, tighten the permissions
and run another dosemu2 instance there,
passing an RPC fd from the first one...
Now this second unpriv'd dosemu2 process
has no access to the initialization state, to
configs, to anything. All it has in an RPC fd
from the first dosemu2 process...
It will have to fully initialize itself by making
only an RPC calls. This can work, but I am not
sure why I need to rewrite everything just to
work with flatpak. :(
But at least the solution is possible.

**Comment by stsp** [comment]
OK, flatpak devs are trying to convince
me that there is nothing to rewrite.
With `flatpak-spawn` I can fork the container
and provide the startup configs in R/O
mode, and allowed DOS dirs in RW mode,
and execute the unmodified dosemu2 with
that environment. So the only needed change
seems to be to support another "security
backend", which is now an RPC server to
which I feed the allowed paths. Sadly I
removed the similar "local" back-end a few
days ago, or I could re-use it for flatpak-spawn.

**Comment by andy5995** [comment]
> It is said around that AppImages can be easily generated on CI stage. As dosemu2 is a monster of silly deps (djgpp, nasm-segelf etc), people who do not use PPA, have problems building it. But AppImage may help. Andrew, would you like to take a look?

I see this issue is closed and you went in the flatpack direction. I recently experimented with attempting to build an AppImage for the git version of dosemu2 . I gave up on that, but now I see this ticket and may be will try again, if there's still some interest in it. I think the best way is to build some of the dependencies individually, upload them to a PPA, then when the appimage script builds the dosemu2 git version, it pulls in the pre-built dependencies, which should significantly reduce the time it takes to build the dosemu2 appimage itself. But I haven't done a lot of research here yet and don't know what's been discussed here and in other discussions so I'll wait to here from you.

I do have this [dosemu2-appimage](https://github.com/theimpossibleastronaut/dosemu2-appimage) build in the CI, but it builds the last release from the Ubuntu PPA.

**Comment by stsp** [comment]
There are a few things to note.
dosemu2 improved a lot on a
deps. Most of them are now
optional. Please see this page:
https://github.com/dosemu2/dosemu2/wiki/Building-From-Source
for a minimal build.

There was enormous amount
of efforts put into AppImage of
dosemu2 by @probonopd in
#2133 but it all ended up here:
https://github.com/probonopd/go-appimage/issues/270
This is why I had to resort for
flatpak: AppImage simply doesn't
handle runtime deps (of sdl).
If you managed to build sdl3
properly, then that's great.

There is also this script:
https://github.com/dosemu2/mkdexe2
that should allow packaging
DOS games to AppImages.
Though I haven't tested it for
some time, but maybe you'll
find it interesting.

Overall, I don't know the current
state of AppImage, and if it have
improved on runtime deps, it
definitely deserves another try.

**Comment by andy5995** [comment]
> There is also this script: https://github.com/dosemu2/mkdexe2 that should allow packaging DOS games to AppImages. Though I haven't tested it for some time, but maybe you'll find it interesting.
> 
> Overall, I don't know the current state of AppImage, and if it have improved on runtime deps, it definitely deserves another try.

Nice! I was able to use the mkdexe2 to bundle some games and they can be downloaded from https://github.com/theimpossibleastronaut/dosemu2-appimage/releases

When I tried running `dosemu -E <command-or-exe>` dosemu opens and closed immediately. With the appimages, it looks for dosemu in the path, so just running the game AppImage is all that's needed. [Raptor](https://github.com/theimpossibleastronaut/dosemu2-appimage/releases/tag/game-raptor-shareware), for example: `/org.dosemu2.Raptor-x86_64.AppImage`.

One obstacle I ran into using mkdex2 is that I had to `sudo ln -sf libfuse3.so.4 /usr/lib/libfuse3.so.3` due to https://github.com/dosemu2/mkdexe2/pull/1

**Comment by stsp** [comment]
> Nice! I was able to use the mkdexe2 to bundle some games and they can be downloaded from

I wouldn't be putting abandonware
on github, this is not a free software.
IMHO some separate site would be
better.

> When I tried running dosemu -E <command-or-exe> dosemu opens and closed immediately.

Use `-T` to avoid close.

> to https://github.com/dosemu2/mkdexe2/pull/1

If only things are so easy. :)
Please fix this first:
https://github.com/containers/fuse-overlayfs/issues/428
Actually there were the commits,
so maybe its already fixed?

**Comment by stsp** [comment]
Okey, actually the aforementioned
problem is indeed already fixed!
They added new switches that help.

**Comment by andy5995** [comment]
> I wouldn't be putting abandonware on github, this is not a free software. IMHO some separate site would be better.

Thank you for the suggestion. I've removed them all. The repo now just hosts the dosemu2 appimage.

**Comment by stsp** [comment]
Ok so the bug appeared not a
bug, I just needed to use another
mount mode of fuse.
So mkdexe2 should now work
again. I just find it barely useful
if we can't host the games. :(

**Comment by stsp** [comment]
Added dosbox support to mkdexe2. :)
