### ISSUE TITLE
[q] Will the doslinux run at dosemu2 ?

### ISSUE THREAD

**Issue by Sfinx** [dosemu2/dosemu2#2134]
Tried dosemu 2.0~pre9-8412-b15ad8fad+202312111916~ubuntu22.04.1 under Ubuntu,  stock MS-DOS 6.22 and dsl

https://github.com/lpsantil/doslinux/releases/download/20230930/DSL002B.ZIP

dosemu2 crashes with:

```
ERROR: unsupported SMSW dest 16
ERROR: general protection at 0x7d05d560fd5b: f3
```

**Comment by stsp** [comment]
We do not support running linux kernels
and loaders of any kind. This is not in the
scope of our project.
