### ISSUE TITLE
beertriv hangs when accessed via BBS/fossil.

### ISSUE THREAD

**Issue by nelgin** [dosemu2/dosemu2#2135]
**Describe the bug**
When running beertriv, it hangs during the drawing of the opening ansi screen.

**To Reproduce**
You're going to need a BBS to reproduce this issue. It works fine if run in local mode. 

**Attach program/game binaries or provide an URL**
https://www.endofthelinebbs.com/BEERTRIV.ZIP

**Attach the log**
Log attached

**A regression?**
No idea, just installed it.

**Additional info**
The following dosemu.conf is being used.
<pre>
$_cpu = "80586"
$_cpu_emu = "fullsim"
$_floppy_a = ""
$_cdrom = ""
# dosemu2 2.0~pre9-7807-4e99cf2c5+202301010131 was the last build to work with
# $_xms set to 1024. It seems the newer dosemu2 builds need the xms and ems settings
# increased (I used 8192 and 2048).  But even so, with the newer dosemu2 builds,
# TW2002 reports it's uneable to initialize the fossil driver, and it quits.
#$_xms = (1024)
#$_ems = (1024)
$_xms = (8192)
$_ems = (2048)
$_ems_frame = (0xe000)
$_external_char_set = "cp437"
$_internal_char_set = "cp437"
$_term_updfreq = (8)
$_layout = "us"
$_rawkeyboard = (auto)
$_mouse_internal = (on)
$_mouse_dev = ""
$_joy_device = ""
$_lpt1 = ""
$_lp2 = ""
$_speaker = ""
$_sound = (off)
$_sb_dsp = ""
# For the default dosemu2
$_hdimage = "+0 -2 /sbbs/ctrl /sbbs/data /sbbs/exec +1"
# dosemu2 with MS-DOS or another DOS
#$_hdimage = "+0 /sbbs/ctrl /doors /sbbs/ctrl /sbbs/data /sbbs/exec /sbbs/xtrn"
# For the default dosemu2
#$_com1 = "virtual"

$_rdtsc = (on)
$_cpuspeed = (0)
$_hogthreshold = (5)
$_com1 = "virtual"
$_lredir_paths = "/sbbs "
</pre>
I'm hopeful that something in the log will help determine the issue since, as I said, it's going to be harder to replicate.
[dosemu_boot.log.zip](https://github.com/dosemu2/dosemu2/files/13709194/dosemu_boot.log.zip)

**Comment by stsp** [comment]
We fixed a serious  problem in serial
emulator, but I don't know if it affects
virtual.
So please re-evaluate this ticket.

**Comment by nelgin** [comment]
When was the update? I'll pull the latest from ppa and give it a try. Thanks.

**Comment by stsp** [comment]
Just yesterday.

**Comment by nelgin** [comment]
Not picking it up via the Launchpad PPA I’m afraid. There appears to be no version of 20.04.3. I guess I can download 20.04.1 manually until that’s fixed.

**Comment by nelgin** [comment]
I’ve updated and it did not fix the issue.

**Comment by stsp** [comment]
Please make a video of your problem.
Please finally get rid of all the crap in your config.

**Comment by nelgin** [comment]
All that crap works for every other fucking game. I see new year same attitude. I wish someone with some courtesy was working this project. Forget it, I'm out.

Sent from my Metro by T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stsp** [comment]
Are you for real?
Omg.
Just to let you know, I am currently
after serious surgery, fighting for a live.
And instead of trying to relax, I decided
to answer you, just to get this shit?
You are welcome to go away.

**Comment by andrewbird** [comment]
@stsp I hope you get well soon!

**Comment by stsp** [comment]
Thank you, doctor says I'll be (more or less)
ok next week. :)
But I was really struggling for life this time,
and am still quite disabled. And yet I managed
to do dosemu2 patches and provide fixes
to users almost without an interruption!
So hearing this from some pig was an
exceptionally unpleasant surprise.

**Comment by bolle732** [comment]
Sorry for hijacking, but I wish you too the best to get back to a healthy state! Take the time you need, the world can wait. If it's not, then do some more NOPs ;-)

**Comment by stsp** [comment]
Thank you for support, it all counts!
I wouldn't be alive by now, if not for
support from my friends, who help me
also here in a hospital. :)

**Comment by nelgin** [comment]
I'm sorry you are not well and i wish you a speedy recovery.  Bring told my config is crap was also an unexpected unpleasant surprise,  especially when the same config works with 50+  other games.  I've been nothing but civil to you,  providing what information i can so i don't deserve that sort of attitude.

Sent from my Metro by T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stsp** [comment]
I asked you to clean up your config
many times, but you seem to be proud
of not doing that. Yet you expect keeping
me to identify your problems.
I don't want any conflicts here.
If you can realize that you need to do
exactly what I say when I try to  help
you, then please get back. Other people
have no problem understanding that
simple fact.
If however you have any problems with
this understanding, then please just silently
never get back.
Silently means not offending those whom
you asked for a help.
Thanks for understanding.

**Comment by stsp** [comment]
So you can tell me to re-open this ticket
and I'll take that as an indication that you
realized what am I saying.
Or take no actions if you didn't.
I personally think everyone should have
the right to amend his doings.

**Comment by stuaxo** [comment]
Apologies for being off-topic, but also hijacking this to wish for a speedy recovery, and to take as long as you need - the progress has been amazing over the last few years on this project.

**Comment by stsp** [comment]
Thanks Stu!
Will definitely take a short break, but we
need to see the dosemu2's infrastructure
parts keep appearing. While I have no
intention to write entire dosemu2 alone
(not possible for 1-man), getting the
sustainable core would be already a huge
deal. Which is why I am trying to completely
avoid working on dos compatibility or
performance. Bart was fulfilling that gap,
but seemingly not any more...
