### ISSUE TITLE
dosemu.bin: ./build/../src/base/misc/utilities.c:507: char *assemble_path(const char *, const char *): Assertion `p.we_wordc == 1' failed.

### ISSUE THREAD

**Issue by mkst** [dosemu2/dosemu2#2136]
Hello hello! Back once again with a decomp-related question (previous question was [this](https://github.com/dosemu2/dosemu2/issues/2033) one.

We run dosemu2 inside an nsjail inside a Docker container. The latest version:
```
$ dosemu --version
dosemu2-2.0pre9
Revision: 7076
```

is failing an assertion which I'm trying to troubleshoot.

Our CI [passed](https://github.com/decompme/decomp.me/pull/935/checks) 2 days ago but [failed](https://github.com/decompme/decomp.me/pull/936/checks) yesterday, so it appears to be a new problem. 

I'm struggling to find a minimal reproducible example that would help you debug along with me. The following command is executed (and fails) when running the test suite (or when called from within the application) however is not failing when I run it manually:

```
INPUT=/tmp/code.c \
OUTPUT=/tmp/object.o \
COMPILER_DIR=/backend/compilers/ps1/psyq3.3 \
COMPILER_FLAGS='-O2 -G0 -fsigned-char' \
FUNCTION=func_80133FCC \
TMPDIR=/tmp \
  /bin/nsjail \
    --mode o \
    --chroot /sandbox/root \
    --bindmount /sandbox/tmp/tmpew1e2zso:/tmp \
    --bindmount /sandbox/tmp/tmpew1e2zso:/run/user/1000 \
    --bindmount_ro /dev \
    --bindmount_ro /bin \
    --bindmount_ro /etc/alternatives \
    --bindmount_ro /etc/fonts \
    --bindmount_ro /etc/passwd \
    --bindmount_ro /lib \
    --bindmount_ro /lib64 \
    --bindmount_ro /usr \
    --bindmount_ro /proc \
    --bindmount /sandbox/tmp/tmpew1e2zso:/var/tmp \
    --bindmount_ro /backend/compilers \
    --bindmount_ro /backend/libraries \
    --env PATH=/usr/bin:/bin \
    --cwd /tmp \
    --rlimit_fsize soft \
    --rlimit_nofile soft \
    --disable_proc \
    --bindmount_ro /backend/compilers/ps1/psyq3.3 \
    --env PATH \
    --env INPUT \
    --env OUTPUT \
    --env COMPILER_DIR \
    --env COMPILER_FLAGS \
    --env FUNCTION \
    --env TMPDIR \
      -- \
        /bin/bash -euo pipefail -c 'cpp -P "$INPUT" | unix2dos > object.oc && cp ${COMPILER_DIR}/* . && (HOME="." dosemu -quiet -dumb -f ${COMPILER_DIR}/dosemurc -K . -E "CC1PSX.EXE -quiet ${COMPILER_FLAGS} -o object.os object.oc") && (HOME="." dosemu -quiet -dumb -f ${COMPILER_DIR}/dosemurc -K . -E "ASPSX.EXE -quiet object.os -o object.oo") && ${COMPILER_DIR}/psyq-obj-parser object.oo -o "$OUTPUT"'
```

our dosemurc is pretty basic:
```
$ cat dosemurc 
$_cpu_vm = "emulated"
$_cpu_vm_dpmi = "emulated"
$_sound = (off)
$_hogthreshold = (0)

$_cpuspeed = (333.333)
$_pci = (off)
$_rdtsc = (off)
$_term_color = (off)
$_ipxsupport = (off)
$_pktdriver = (off)
```

Do you have any thoughts on why the assertion is failing? Presumably we are giving a path to dosemu that it's not liking? Any ideas to help debug would be greatly appreciated!

**Comment by mkst** [comment]
OK! started looking through the most recent commits.. [this](https://github.com/dosemu2/dosemu2/commit/97dcd1f61e559f82ad41fc1d194ad68448209e40#diff-d45f7604a8993ee47afeb70b5f5e3eb674a9f14b8074004a5df3379be47e5b3c) one looks to have introduced the problem.

We are calling dosemu with bare `dosemu` which means `char *p = dirname(s);` is an empty path. Changing to calling it with `/usr/bin/dosemu` fixes the failed assertion.

I don't know whether this should be improved on your side, but at least I have a workaround for us.

**Comment by stsp** [comment]
Can you please show what exactly
path `p` contains? There is a check
at line 75 that it at least contains
"bin", so it can't be empty.
I think I should exclude that logic
for any relative paths though, to
avoid the problems.

**Comment by stsp** [comment]
I excluded the prefix logic for rel
paths, so this should now be fixed.
The real problem however is that
for some reason dosemu fails to
read `/proc/self/exe` for you and
falls back to argv0.

**Comment by mkst** [comment]
I think this is caused by the nsjail which puts a lot of restrictions on what the executable can access. Thanks for the swift turnaround!
