### ISSUE TITLE
Serial Port: mode output handshake configuration not working?

### ISSUE THREAD

**Issue by haenschen** [dosemu2/dosemu2#2138]
**Describe the bug**
When trying to print a .txt file to COM1 the zebra printer is blinking, indicating that it receives data but won't print. This might be happening due to a wrong baud rate, parity, ...?

**To Reproduce**
Build dosemu from devel with fdpp and comcom32. Add user to 'dialout' group. Install freedos via install-freedos scripts and insfdusr.
Reboot dosemu -D9+s

```
mode com1:96,n,8,1
copy print.txt COM1
```

**Attach the log**
-D9+s logs.
Not working with Ubuntu 22 6.2.0-39-generic
[boot_printer_failed.log](https://github.com/dosemu2/dosemu2/files/13798266/boot_printer_failed.log)
Working with Ubuntu 16 and dosemu2-2.0pre6
[boot_printer_working.log](https://github.com/dosemu2/dosemu2/files/13798267/boot_printer_working.log)

**A regression?**
On the exact same hardware I can print with Ubuntu 16 and dosemu2-2.0pre6. Unfortunately I was not able to build dosemu2-2.0pre6 on Ubuntu 22 yet, if needed I can try other versions to narrow the problem down...?

**Additional info**
2433fe861f6af1ae0b557ba99a456cdec696d42c with [freedos](https://github.com/dosemu2/install-freedos)
dosemu2-2.0pre6 with [dosemu-freedos-1.0-bin.tgz ](http://prdownloads.sourceforge.net/dosemu/dosemu-freedos-1.0-bin.tgz?download)
`$_com1 = "/dev/ttyS0"`

**Comment by stsp** [comment]
IIRC you had ser port logger.
If so, you need to compare the output.
Data seem right, but maybe DTR/RTS
not working as expected...

**Comment by haenschen** [comment]
Good memory :) In fact, the hardest part was finding the logger again and remembering how it worked...
Here are the results: the logger is configured to the appropriate parity, stop and data bits and baud rate. The logging is done as ASCII.
With the old system, my copied file appears 1:1 in the log.
[log_serial_working.TXT](https://github.com/dosemu2/dosemu2/files/13798775/log_serial_working.TXT)

With the new configuration only "rubbish"
[log_serial_failure.TXT](https://github.com/dosemu2/dosemu2/files/13798776/log_serial_failure.TXT)

**Comment by haenschen** [comment]
Whats the standard configuration of a serial port? I can configure the logger for that and try again to confirm.
At the moment I am using
```
Baudrate=9600
Bits=8
Parity=No
StopBits=1
```

**Comment by stsp** [comment]
Please add strace logs.
Dosemu logs should also be
enabled while doing strace logs.

**Comment by haenschen** [comment]
strace logs became quite large...
[dosemu_devel_w_strace.zip](https://github.com/dosemu2/dosemu2/files/13799339/dosemu_devel_w_strace.zip)
[dosemu_pre6_w_strace.zip](https://github.com/dosemu2/dosemu2/files/13799340/dosemu_pre6_w_strace.zip)

**Comment by stsp** [comment]
Please re-log with this patch.

**Comment by haenschen** [comment]
yes, now it's working :)
[log2.zip](https://github.com/dosemu2/dosemu2/files/13801235/log2.zip)

**Comment by stsp** [comment]
Thank you.
In this case please repeat the experiment
with fdpp instead of freedos.
insfdusr is ok, just dont boot from kernel.sys.

**Comment by haenschen** [comment]
I hope I got rid of freedos, rmfdusr wasn't really working so I deleted manually and reinstalled dosemu. This is using the mode.com from freedos 1.3. And again printing as expected :pray: 
[fdpp.zip](https://github.com/dosemu2/dosemu2/files/13801442/fdpp.zip)

**Comment by stsp** [comment]
Reinstalling dosemu doesnt help.either,
you need to remove ~/.dosemu/drive_c
But now please just do
`ver /r` after boot, to see what are you up to.

**Comment by haenschen** [comment]
Yes, I think I did that
```
ver /r
comcom32 v0.2

Reported DOS version (Int21.3000): 5.00 OEM: FDh
Reported true DOS version (Int21.3306): 7.10
Version string (Int21.33FF): FDPP kernel 1.7 [GIT: ] (compiled Dec 25 2023)
```

**Comment by stsp** [comment]
Thanks, convincing.

**Comment by stsp** [comment]
Thanks, convincing.
