### ISSUE TITLE
Unwanted cross window locks on self opened EXE files

### ISSUE THREAD

**Issue by severach** [dosemu2/dosemu2#2143]
**Describe the bug**
I start 2 DOSEMU windows and try to run FOXPROX.EXE in both. FOXPROX.EXE must open itself with O_DENYALL because the second DOSEMU window is unable to execute or even read FOXPROX.EXE. The lock persists if I `attrib +r FOXPROX.EXE`. A Linux window can read FOXPROX.EXE just fine. A copy of FOXPROX.EXE in a different folder can execute and read just fine.

This happens with both FDPP+COMCOM32 and FreeDOS+FreeCOM. FreeDOS fails silently. COMCOM32 says `Error: unable to execute D:\FPD26\FOX.EXE`. I don't use FOXPRO.EXE so I rename FOXPROX.EXE to FOX.EXE.

Same things happens if I run FOXPRO.EXE except that FOXPRO.OVL is also locked. This happens in Fox 2.0, 2.5, and 2.6a, not in 1.02.

It's not just a cross window lock. If inside Fox I try to `?fopen("FOXPROX.EXE",0)` that fails with -1. I can fopen other nearby files that aren't locked.

**Additional info**
How does one DOSEMU window know about the lock in the other? Cross window locks are not a bad feature, I'm just surprised that it's feasible.

I thought setting ReadOnly always enforces O_DENYWRITE and silently ignores O_DENYREAD and all O_DENY constants. No program can lock a ReadOnly file with O_DENYREAD to prevent others from reading it.

In Windows XP I can start the same FOXPROX.EXE in multiple command windows. The EXE and or OVL is always readable.

**Comment by stsp** [comment]
Should now be fixed.
R/O share exceptions were not checked for.
In fact, I wonder if we should allow
opening the file no matter is it R/O or
not, because the required conditions are:
1. First open is R/O
2. Second open is R/O
3. No DenyRead bits in either first or second open
4. File is R/O

Now it really seems to me that the condition
4 is redundant, so maybe we should violate
the DOS specs here?
Andrew, what do you think?
There are no test-cases for that, btw. :)

**Comment by severach** [comment]
This applies to ReadOnly file systems like CDROM and read only network share.

Windows XP seems to be ignoring O_DENYREAD for EXE and OVL. I did not set ReadOnly on anything and both FOXPRO and FOXPROX can be run in multiple command windows. Don't know how DOS handles it.

What's interesting is that if I

```
First Window
attrib -r FOXPROX.EXE
FOXPROX.EXE

Second Window
FOXPROX.EXE (this fails)
attrib +r FOXPROX.EXE
FOXPROX.EXE (this launches)
```

If Windows wasn't already ignoring O_DENYREAD it would not allow the second to launch. Windows wouldn't strictly open based on ReadOnly. It would manage the O_DENY flags on each open based on ReadOnly. If the file was already open O_DENYALL setting ReadOnly would not allow it to open again. I think setting ReadOnly is too rare to bother implementing this level of emulation. I rather like immediately fixing the problem by setting ReadOnly.

**Comment by stsp** [comment]
> I think setting ReadOnly is too rare to bother implementing this level of emulation.
> I rather like immediately fixing the problem by setting ReadOnly.

Not sure what you mean here.
Set R/O immediately when creating
any file, or what?
I think we can ignore the R/O attribute
here. No matter how hard I think about
it, I don't see the reason why R/O is required
for O_RDONLY compat open to succeed
with DenyWrite O_RDONLY previous open.

Anyway, have you tested the fix?

**Comment by stsp** [comment]
> This applies to ReadOnly file systems like CDROM and read only network share.

At least cdrom files do not always
have the R/O attribute. I think the
same is for the network share. So
that kind of solution can't work.
Ignoring R/O attribute for share mode
exceptions looks like the better approach.
But the currently implemented behavior
(since today's fix) matches DOS specs fully.

**Comment by stsp** [comment]
Hmm, scrolled down RBIL a bit, and
there is an MS-DOS-7 share table, which
does no longer rely on an R/O bit!
The behavior I implemented, is from 6.22.
So we indeed should switch to DOS7
behavior.
BUT.
DOS7 implements DenyNone somewhat
differently... It would be a bit difficult
(considering the resulting benefits) to
implement DenyNone in DOS7-compatible
way. So perhaps we need to only get rid
of an R/O bit, leaving the DenyNone to the
6.22 impl.

**Comment by severach** [comment]
The fix works fine. `attrib +R FOX.EXE` and I can launch many times. Not the same as Windows XP but fine for me.

As far as I know CDROM do not have a ReadOnly bit. ReadOnly is set by the CDROM driver to block all write and DENY attempts. My memory is dim that far back but I recall the earliest CDROM drivers did not set the ReadOnly bit which caused all sorts of problems. Then when they did, the early XCopy copiers that were not CDROM aware would copy the ReadOnly bit and I had to go -R them all. 

If there's a modern CDROM driver that leaves files open for writing on writable discs, I wouldn't know anything about that.

**Comment by stsp** [comment]
I added another fix.
Per MS-DOS-7 +R is no longer needed.
Unfortunately, we still implement the
share rules per 6.22, so here we have
a mix of versions.
But I don't mind taking the best from
different versions, and mixing on our
own. :)

**Comment by stsp** [comment]
And on a positive side, with this, running
2 instances of windows-3.1, now allows both
to have the sound. Previously only the first
one would have the sound, as windows uses
share open for sound driver files.
That was quite annoying, and now its fixed, too.

**Comment by severach** [comment]
That works too with all the EXE set back to -R.

**Comment by stsp** [comment]
I had to change also fdpp to get the
tests passing.
Andrew, do you know how to make
that not to fail on a weekly ms-dos
test? I think it will fail the fat test.
