### ISSUE TITLE
$_X_fullscreen = (on) leads to cpu exception in dosemu code outside of VM86()!

### ISSUE THREAD

**Issue by haenschen** [dosemu2/dosemu2#2145]
**Describe the bug**
When editing dosemu.conf and setting

`$_X_fullscreen = (on)`

dosemu crashes upon startup

```
ERROR: cpu exception in dosemu code outside of VM86()!
Memory access error (address is not connected to the object [0x20000])
Terminated with signal 11
```

**To Reproduce**
Linux 6.5.0-15-generic #15~22.04.1-Ubuntu with Wayland **disabled**
Build from devel and modify dosemu.conf 
`$_X_fullscreen = (on)`

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/14156954/boot.log)

**Comment by stsp** [comment]
Thanks, great catch!
