### ISSUE TITLE
Running dosemu2 with root privs is only possible with: dosemu -s

### ISSUE THREAD

**Issue by mkst** [dosemu2/dosemu2#2149]
I don't appear to be able to run dosemu as `root`. I do not want to run it as a user account via `sudo`, I just want to run it as `root` (context is that I've just spun up a Docker image to do some testing, and there is only a root user by default):
```
root@9c0b40f9d8c4:~# dosemu --version
Running dosemu2 with root privs is only possible with: dosemu -s
root@9c0b40f9d8c4:~# dosemu --version -s
Running dosemu2 with root privs is only possible with: dosemu -s
root@9c0b40f9d8c4:~# dosemu -s --version
Running dosemu2 with root privs is only possible with: dosemu -s
```
If I comment out the lines that do the check, everything works like I would expect:
```
root@9c0b40f9d8c4:~# dosemu.no_check --version
dosemu2-2.0pre9
Revision: 7076
```
.. I actually just tried adding a user and I still cannot figure out the sudo checking logic of dosemu:
```
mkst@9c0b40f9d8c4:~$ sudo dosemu --version
[sudo] password for mkst: 
Running dosemu2 with root privs is only possible with: dosemu -s
mkst@9c0b40f9d8c4:~$ sudo dosemu --version -s
Running dosemu2 with root privs is only possible with: dosemu -s
mkst@9c0b40f9d8c4:~$ echo $UID
1000
```

Perhaps the dosemu script could check whether the `$SUDO_USER` variable is set, and if so, it can set `SUDO=sudo`?
```
mark@carbon:~/github/dosemu2$ sudo sh -c 'echo $SUDO_USER'
mark
mark@carbon:~/github/dosemu2$ sh -c 'echo $SUDO_USER'

```

Is there a reason you are trying to prevent dosemu from running as root?

I've just hacked out the code and created a diff, let me know if you'd like me to raise a PR.
```diff
diff --git a/src/dosemu b/src/dosemu
index 9cd130674..a50c04890 100644
--- a/src/dosemu
+++ b/src/dosemu
@@ -25,7 +25,7 @@ USAGE:
 THISDIR="$PWD"
 ARG0="$0"
 
-unset STRING_I USE_SUDO OPTS
+unset STRING_I OPTS
 
 mkdir -p ~/.dosemu
 
@@ -103,11 +103,6 @@ while [ $# -gt 0 ] ; do
       shift
       shift
       ;;
-    -s)
-      USE_SUDO=1
-      SUFFIX="$SUFFIX \"$1\""
-      shift
-      ;;
     -t | -t[a-z] | -t[a-z][a-z] | -t[a-z][a-z][a-z])
       exec 4>&2 2>~/.dosemu/stderr.log.$BASHPID
       SUFFIX="$SUFFIX \"$1\""
@@ -136,7 +131,6 @@ while [ $# -gt 0 ] ; do
       ;;
   esac
 done
-SUFFIX="$SUFFIX $*"
 
 [ -z "$DOSEMU_QUIET" ] || OPTS="$OPTS -q"
 [ -z "$DOSEMU_LOG_FILE" ] || LOG_FILE="$DOSEMU_LOG_FILE"
@@ -159,25 +153,14 @@ fi
 
 get_binary "$0"
 
-if [ "`id -ur`" -eq 0 ]; then
-  echo "Running dosemu2 with root privs is only possible with: $(basename $0) -s"
-  exit 1
-fi
-
-SUDO=""
-# set sudo_uid/sudo_gid so that somebody who does "sudo dosemu"
-# really gets root
-if [ -n "$SUDO_UID" ] ; then
-  SUDO_UID=0
-fi
-if [ -n "$SUDO_GID" ] ; then
-  SUDO_GID=0
-fi
-if [ -n "$USE_SUDO" ] ; then
+if [ -n "$SUDO_USER" ] ; then
   SUDO=sudo
-  SUDOOPTS=-E
+  SUDO_OPTS=-E
+  SUFFIX="$SUFFIX \"$1\""
 fi
 
+SUFFIX="$SUFFIX $*"
+
 # for address sanitizer
 export ASAN_OPTIONS='handle_segv=0:abort_on_error=1:detect_leaks=0'
 export LSAN_OPTIONS='report_objects=1:fast_unwind_on_malloc=0:exitcode=0'
@@ -187,7 +170,7 @@ export UBSAN_OPTIONS='print_stacktrace=1'
 export SDL_VIDEO_X11_WMCLASS=dosemu
 
 eval "set -- $SUFFIX"
-COMMAND="$SUDO $SUDOOPTS $DBG $BINARY -o $LOG_FILE $OPTS"
+COMMAND="$SUDO $SUDO_OPTS $DBG $BINARY -o $LOG_FILE $OPTS"
 if [ -n "$STRING_I" ] ; then
   COMMAND="$COMMAND -I '$STRING_I'"
 fi

```

**Comment by stsp** [comment]
Should now be fixed.
Your patch is not good because when
dosemu detects internally-used sudo,
it activates the priv-flipping (and dropping)
machinery.
Using external sudo is tempting, but
unfortunately in this case we don't know
if it preserved HOME var or not.
If you patch sudo so that it exports the
`SUDO_HOME` var and upstream your
patch, then we'll be able to just remove
the entire hack the way you suggested
above.

**Comment by mkst** [comment]
Great stuff - I will give this a go tonight, thanks for the swift response 🙂

**Comment by stsp** [comment]
It appears I can evaluate `SUDO_HOME`
from `SUDO_USER` (obviously), so now things
like `sudo -E dosemu -s` are also supported.

In your patch, btw, I wonder why you check
for ` -n "$SUDO_USER" ` and then set sudo
options - if `SUDO_USER` is already set, its
too late to change sudo options, and running
sudo for the seccond time is not going to help.

**Comment by stsp** [comment]
`SUDO_HOME` is now implemented!
https://github.com/sudo-project/sudo/commit/602a58e86a3562472499e339d40bed83e76109dc
