### ISSUE TITLE
EDR-DOS will no longer cooperate with MFS at boot time

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#2156]
**Describe the bug**
When booting EDR-DOS 7.01.07 the process stops after examining config.sys. However If I disable the loading of emufs.sys then booting continues properly.
![Screenshot_2024-02-20_16-57-43](https://github.com/dosemu2/dosemu2/assets/220835/23f6832d-7b3e-4dc7-89f5-15698c0c7df3)

**To Reproduce**
1/ Unpack the t1.zip file in the devel directory
2/ run script ./runstandalonetest.sh

**Attach program/game binaries or provide an URL**
[t1.zip](https://github.com/dosemu2/dosemu2/files/14349084/t1.zip)

**Attach the log**
[t2.zip](https://github.com/dosemu2/dosemu2/files/14349103/t2.zip)

**A regression?**
Yes booting EDR-DOS 7.01.07 used to work fine

**Additional info**
The EDR-DOS 7.01.09 that will attempt to start as supplied in my t1.zip file is from the SvarDOS people. They seem to be working on bug fixing Udo's 7.01.08 wip at the moment, but the same problem occurs with the 7.01.07 that previously did work with MFS. If you need the older version, then you'll find the files in the x07 directory, along with @ecm-pushbx's single boot file version in directory ecm.

**Comment by stsp** [comment]
Would you like to bisect this?
Since this is dr-dos, disabling fdpp
will help aid the bisecting.

**Comment by andrewbird** [comment]
> Since this is dr-dos, disabling fdpp
will help aid the bisecting.

Ahh good idea, I will as bisecting with FDPP is pretty much impossible. It could be a large bisect as I found a reference in an issue that it worked back in 2018!

**Comment by stsp** [comment]
Should now be fixed.

**Comment by ecm-pushbx** [comment]
Regarding the fix, EDR-DOS also updates the int 31h vector segment to point to its DOS data segment. FreeDOS also happens to do that although it doesn't relocate the segment.

**Comment by stsp** [comment]
But that looks wrong because
`INT 31 - overwritten by CP/M jump instruction in INT 30`
So its basically not a vector.

**Comment by ecm-pushbx** [comment]
> But that looks wrong because `INT 31 - overwritten by CP/M jump instruction in INT 30` So its basically not a vector.

The CP/M call 5 jump instruction in the int 30h vector is a 5-byte instruction, far immediate jump 0EAh. That means only the first byte of the int 31h IVT vector is used by this instruction. Therefore the int 31h vector **segment** can be used to point anywhere, and is set by EDR-DOS and FreeDOS to point to the DOS data segment.

**Comment by stsp** [comment]
So what's the use?
Why they do so?

**Comment by ecm-pushbx** [comment]
I did note this in the FD kernel where it is set: https://github.com/FDOS/kernel/blob/8552d833bbca657591fa8e6f7276d307d7d0c7c6/kernel/main.c#L285 back in a 2022 PR https://github.com/FDOS/kernel/pull/72 accepted as https://github.com/FDOS/kernel/commit/b7345d916509640b7e53dc1d860ea34ac0d9274b

**Comment by ecm-pushbx** [comment]
> So what's the use? Why they do so?

As noted in the commit, shsucdx depends on the int 31h vector segment to track relocations of the DOS data segment. The IVT can be read while InDOS without an int 21h nor int 2Fh call, which may be preferable.

**Comment by ecm-pushbx** [comment]
More context: https://github.com/adoxa/shsucd/blob/f905b43436107b9238c11d5f9a1759c98eb5cc7d/shsucdx.nsm#L3220

**Comment by stsp** [comment]
But how can this be used if only
2 DOSes are known to do that?

**Comment by ecm-pushbx** [comment]
https://github.com/adoxa/shsucd/blob/f905b43436107b9238c11d5f9a1759c98eb5cc7d/shsucdx.nsm#L3262

`; see if we're using DR-DOS by testing the segment of Int31`

**Comment by stsp** [comment]
OK, done. :)

**Comment by andrewbird** [comment]
Cool, glad you have a fix. I'm unable to test as I have no broadband ATM. Thanks.
