### ISSUE TITLE
Updates to dosemu2 and fdpp fail on 3 up to date Linux Mint machines

### ISSUE THREAD

**Issue by WayCon2** [dosemu2/dosemu2#2160]
Latest update of dosemu2 and fdpp result in log:
CONF: reserving 116Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 40Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
ERROR: /usr/lib/dosemu/libplugin_dj64.so: libdjdev64.so.0.1: cannot open shared object file: No such file or directory
leavedos(fdpp_exit:96|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped

Package info:
dosemu2: installed
dosemu2	2.0~pre9-8495-8de3fef6f+202402211903~ubuntu22.04.1
fdpp: installed
fdpp	1.7-1490-9bd6fc0+202402212147~ubuntu22.04.1

Using Timeshift to restore prior versions of dosemu2 and fdpp , everything works fine on all three machines.
Should I just wait for the next updates? Is there really a file missing? Thank you.

**Comment by stsp** [comment]
There were some bad builds on LP.
I rebuilt the packages now and made
sure they pass CI testing.
Let me know how it goes.
Don't forget to do
`sudo apt-get update`
to refresh the metadata cache,
or it will install the old ones again.

**Comment by WayCon2** [comment]
Thank you, stsp,
Will do.

**Comment by WayCon2** [comment]
Success with all three computers. Thank you, again. I do note that the update for dosemu2 itself is gone now.

**Comment by stsp** [comment]
Gone?

**Comment by WayCon2** [comment]
Excuse me for being vague. I meant that since our discussion, I don't see the prior or any other update for dosemu2 in mintUpdate.

**Comment by stsp** [comment]
OK, there was a problem on my side.
The updates should be coming up properly
now.
I hope! :)

**Comment by WayCon2** [comment]
Yes.I got my update, today. I appreciate your efforts.
Sincerely,
wc
