### ISSUE TITLE
duke3d regressed

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2161]
- gfx artifacts in the very early intro
  (when "Duke Nukem 3D" is printed,
  the letters are glitching)
- eventually crashes with
  `dosemu.bin: sequencr.c:109: sequencer_add: Проверочное утверждение «tstamp >= s->tail->tstamp» не выполнено.`

**Comment by j2969719** [comment]
I also noticed that setup.exe seems to freeze if you select sound setup>test sound fx card.
Also when using comcom the end screen instantly becomes black and white.

**Comment by stsp** [comment]
Should now be fixed.
What kind of "end screen"?

**Comment by j2969719** [comment]
![comcom](https://github.com/dosemu2/dosemu2/assets/30291994/88f571b1-549c-4757-b5d3-fe0a4fa1be68)
![freecom](https://github.com/dosemu2/dosemu2/assets/30291994/5dc0c979-03b1-46ae-97f1-531043370983)



offtopic, but it’s really cool that comcom now stores the command history

**Comment by stsp** [comment]
Ok, I disabled the attribute reset.

> offtopic, but it’s really cool that comcom now stores the command history

And you can navigate it with the
mouse wheel, and press "enter"
with middle button.

**Comment by j2969719** [comment]
minor, command line history:
![freecom](https://github.com/dosemu2/dosemu2/assets/30291994/8d7b437a-4086-4543-88fe-24a9b138d1de)
![comcom](https://github.com/dosemu2/dosemu2/assets/30291994/363052e5-d410-466e-84ec-9a5038a96a27)

**Comment by j2969719** [comment]
Looks like there's some kind of regression again, at least I'm seeing a significant drop in performance with duke3d 1.3d (Vesa 2.0 640x480).

**Comment by stsp** [comment]
I don't see any performance drop, how
exactly should I see it?
But I again see a lot of flickering when
"Duke Nukem 3D" is printed on an intro
screen, so lets re-open this.
This flickering seems to be specific to
VESA modes.

**Comment by j2969719** [comment]
screen capture from my old laptop

https://github.com/dosemu2/dosemu2/assets/30291994/c5d8edb4-ce90-4cda-a996-5b667a388605

**Comment by j2969719** [comment]
my bad, I looked at my dosemurc and there cpu_vm and cpu_vm_dpmi were set to emulated, sorry

**Comment by stsp** [comment]
Yes, emulated dpmi is artificially slow.
But its not a regression, and there are
currently no resources to work on a
jit optimizations.

**Comment by stsp** [comment]
In a mean time, flickering should now
be fixed.
