### ISSUE TITLE
memory_dpmi_japheth.py test fails

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2168]
https://github.com/dosemu2/dosemu2/actions/runs/8224753951/job/22488964559

Hi Andrew, could you please explain
what does this test do? Seems it wants
to allocate 128Mb in 1 go, but fails
because comcom64 already consumed
some?
Also what is 218?

**Comment by andrewbird** [comment]
Hi stas, the 218 is the release of HX that the test is taken from. I'm not sure if it's possible to reduce the size requested, perhaps we have to disable that test for FDPP.

**Comment by stsp** [comment]
How about increasing DPMI mem
size to 256M for that particular test
then?

**Comment by andrewbird** [comment]
Sure, that seems like a good idea.

**Comment by andrewbird** [comment]
There seems to be another problem with pc-mos test https://github.com/dosemu2/dosemu2/actions/runs/8225834255/job/22491426939?pr=2169

**Comment by stsp** [comment]
What is this:
```
$ test/test_dos.py --list-cases

ults.upper(), "%s( +|\.)%s" % (f.upper(), e.upper()))
/home/stasults.upper(), "%s( +|\.)%s" % (f.upper(), e.upper()))
/home/stas/src/dosemu2-devel/test/test_dos.py:2097: SyntaxWarning: invalid escape sequence '\.'
  self.assertRegex(results.upper(), "%s( +|\.)%s" % (f.upper(), e.upper()), msg)
/home/stas/src/dosemu2-devel/test/test_dos.py:2257: SyntaxWarning: invalid escape sequence '\.'
  self.assertNotRegex(results.upper(), "%s( +|\.)%s" % (f.upper(), e.upper()))
/home/stas/src/dosemu2-devel/test/test_dos.py:5474: SyntaxWarning: invalid escape sequence '\S'
  x = re.match("^--require-attr=(\S+).*$", argv[1])
/home/stas/src/dosemu2-devel/test/func_ds3_share_open_access.py:438: SyntaxWarning: invalid escape sequence '\('
  m = re.search("FAIL:\('%s', '%s', '%s'\)\[.*\]" % t, results)
/home/stas/src/dosemu2-devel/test/func_ds3_share_open_twice.py:705: SyntaxWarning: invalid escape sequence '\('
  m = re.search("FAIL:\('%s', '%s', '%s', '%s', '%s'\)\[.*\]" % t, results)
/home/stas/src/dosemu2-devel/test/func_libi86_testsuite.py:23: SyntaxWarning: invalid escape sequence '\s'
  t = re.search("\s*(\d+): (.+):\d+\s+([^']+)", str(l))
libi86-testsuite-ia16-elf not installed - skipping those
```

**Comment by stsp** [comment]
Or this:
```
Test PP-DOS-GIT  PC-MOS build script                                             
... /home/stas/src/dosemu2-devel/test/common_framework.py:516: DeprecationWarning:
 datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware
 objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.starttime = datetime.utcnow()
```

**Comment by stsp** [comment]
Would it be possible to run allocation
multiple times, making sure the allocation
address and the amount of free space
are always the same?
To make sure comcom64 doesn't produce
leaks.

(sorry for double-posting, posted to
wrong ticket initially)

**Comment by andrewbird** [comment]
Sounds like you have a new version of python that's tightened syntax or typing. Can you run `python --version` and let me know the result? I'll see if I can replicate in a python virtual environment.

> Would it be possible to run allocation
multiple times, making sure the allocation
address and the amount of free space
are always the same?

I think so, but how does that test comcom leakage, surely it just checks that the test program cleans up its allocation?

**Comment by stsp** [comment]
> python --version and let me know the result?

That was fedora-40.
Will not get to that machine again
this week.

> I think so, but how does that test comcom leakage, surely it just checks that the test

Because comcom64 works and spawns
the tests. If it doesn't produce leaks
between spawns, that already is telling
something.

**Comment by andrewbird** [comment]
I'm just writing a test for memory leak. Would you expect the handle number to be reused? I'm just using __dpmi_allocate_memory() and __dpmi_free_memory().
~~~
C:\>c:\dpmileak TEST0
INFO: (TEST0) DPMI allocation info: HNDL=00000012, SIZE=00002000, ADDR=21199000
OKAY: (TEST0)
C:\>c:\dpmileak TEST1
INFO: (TEST1) DPMI allocation info: HNDL=00000016, SIZE=00002000, ADDR=21199000
OKAY: (TEST1)
C:\>c:\dpmileak TEST2
INFO: (TEST2) DPMI allocation info: HNDL=0000001a, SIZE=00002000, ADDR=21199000
OKAY: (TEST2)
C:\>c:\dpmileak TEST3
INFO: (TEST3) DPMI allocation info: HNDL=0000001e, SIZE=00002000, ADDR=21199000
OKAY: (TEST3)
C:\>c:\dpmileak TEST4
INFO: (TEST4) DPMI allocation info: HNDL=00000022, SIZE=00002000, ADDR=21199000
OKAY: (TEST4)
C:\>c:\dpmileak TEST5
INFO: (TEST5) DPMI allocation info: HNDL=00000026, SIZE=00002000, ADDR=21199000
OKAY: (TEST5)
C:\>c:\dpmileak TEST6
INFO: (TEST6) DPMI allocation info: HNDL=0000002a, SIZE=00002000, ADDR=21199000
OKAY: (TEST6)
C:\>c:\dpmileak TEST7
INFO: (TEST7) DPMI allocation info: HNDL=0000002e, SIZE=00002000, ADDR=21199000
OKAY: (TEST7)
C:\>c:\dpmileak TEST8
INFO: (TEST8) DPMI allocation info: HNDL=00000032, SIZE=00002000, ADDR=21199000
OKAY: (TEST8)
C:\>c:\dpmileak TEST9
INFO: (TEST9) DPMI allocation info: HNDL=00000036, SIZE=00002000, ADDR=21199000
OKAY: (TEST9)
~~~

**Comment by stsp** [comment]
Currently handles just increment.
Would be good if you also test "allocate
DOS memory " and also do not free
any memory on client termination to
make sure dosemu cleans up all the
allocated resources.

**Comment by andrewbird** [comment]
You can close this now I think.

**Comment by stsp** [comment]
Thanks for the work.
