### ISSUE TITLE
Llamatron: LLAMA.EXE won't start

### ISSUE THREAD

**Issue by stuaxo** [dosemu2/dosemu2#2172]
On dosemu2 I get I run: ```dosemu LLAMA.EXE```

```
Selected Sound Card not found

Try running 'Install' again - Press any key, about to exit...
```

In dosbox it runs, and sound works.

I tried running INSTALL again, but it doesn't seem to help.

**Comment by stsp** [comment]
Please fill in the tickets properly.
With URL and everything else.
Downloaded from here:
https://www.old-games.ru/game/download/get.php?fileid=7564&modal=1
Starts and works, but no sound.
Same in dosbox.

**Comment by stuaxo** [comment]
Interesting, these are different versions.

On the one you posted, if I save the options and run it again in dosbox, then it makes the "Baaa" noise but gets stuck on the splash screen.

This is the one I tested 
https://www.dosgames.com/files/llama.zip

If I unzip it fresh, then dosbox starts with sound working, while dosemu displays the message complaining about lack of soundcard.

**Comment by stsp** [comment]
Should now be fixed.
Timing problem, it clears the IRQ
counter after dispatching IRQ. So
we need to delay an IRQ for a while.

**Comment by stsp** [comment]
Such delay breaks win31, so undo.

**Comment by stsp** [comment]
Here's the binary patch:
```
Comparing SBLASTER.old and SBLASTER.BIN
00000365:     FF  01
0000036D:     26  2E
```

It doesn't give the initial "mooo" (sorry),
but the sound in game works thereafter.
