### ISSUE TITLE
Commander Keen 4 hangs/crashes sometimes when pressing Escape after entering the first level

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#2174]
**Describe the bug**
Hang or crash

**To Reproduce**
It might need a few attempts to reach a hang/crash:
1. Start dosemu2
2. Start `keen4e`
3. Press enter a few times to enter the world map
4. Walk to the first level and enter it
5. Walk/jump a bit
6. Press Escape

If you get the menu properly, quit dosemu2 and start over again.

**Attach program/game binaries or provide an URL**
[keen4.tar.gz](https://github.com/dosemu2/dosemu2/files/14619652/keen4.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/14619657/boot.log)

**A regression?**
I think it was more stable before.

**Comment by stsp** [comment]
Should now be fixed I think.
Please re-check.
Looks like a mega-bug, nice catch!

**Comment by jschwartzenberg** [comment]
Yep, I can't reproduce it anymore! Nice, quick fix :)
