### ISSUE TITLE
Epic Pinball sound effect gets stuck, keeps repeating

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#2175]
**Describe the bug**
While playing Epic Pinball, at some point a sound effect will hang up all the audio and keep repeating until you quit the game.

**To Reproduce**
Play the game, after a while you will hear the sound gets stuck with a looping effect.

**Attach program/game binaries or provide an URL**
[pinball.tar.gz](https://github.com/dosemu2/dosemu2/files/14620195/pinball.tar.gz)

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/14620199/boot.log)

**A regression?**
I don't think this happened before.

**Comment by stsp** [comment]
Can't reproduce, so can it be that
the prev commit for keen4 fixed it?
It could fix many things.

**Comment by jschwartzenberg** [comment]
I can still reproduce it. You might need to play the game for some minutes to trigger the effect.

**Comment by stsp** [comment]
Please add -D9+S log.

**Comment by jschwartzenberg** [comment]
[boot.log.gz](https://github.com/dosemu2/dosemu2/files/14620880/boot.log.gz)
it was triggered very quickly now

**Comment by Baron-von-Riedesel** [comment]
Perhaps something totally different, but:

I got the very same effect with Epic Pinball on plain DOS with vsbhda ( sbemu fork ). There might be something peculiar in the Pinball way to program the SB Pro: the DSP time constant register is written, then the mixer "mode select" register set to stereo - a ("reverse") order which emulators may not expect.

I also tried Epic Pinball on Qemu and VirtualBox - both unplayable. Kudos to the DosEmu2 developers!

**Comment by stsp** [comment]
What kind of kudos, if we have the
same bug reported here?
Although I couldn't reproduce.

**Comment by Baron-von-Riedesel** [comment]
> What kind of kudos, if we have the same bug reported here?

Because Pinball is playable in DosEmu2.

> Although I couldn't reproduce.

Well, it make take a while - sometimes 10 or 15 minutes. No idea how to speed up this.

**Comment by stsp** [comment]
I think the only way to get the
permanent sound repeating, it
to stop servicing sb irqs.
But according to the log that is
attached here, they are still serviced.
So can it be the bug in a game itself?
Is it definitely a regression?

**Comment by stsp** [comment]
Ah actually I see what's going wrong.
Seems like timing got out of sync, and
irq comes immediately after the game
started the transfer:
```
SB: DMA transfer started, count=535
SB: sample params: rate=16129, stereo=1, signed=0 16bit=0
SB: starting output
SB: Output filled, processed 32 DMA cycles
SB: Done block, triggering IRQ
SB: Activating irq type 1
SB: DMA transfer completed
PCM: resuming stream SB DMA
SB: stopping output
PCM: flushing stream 2 (SB DMA)
SB: Processed 0 268 FIFO, 504 DMA, or=0 dr=0
```

**Comment by stsp** [comment]
Can you guys please try this patch?
```
--- a/src/base/sound/sndpcm.c
+++ b/src/base/sound/sndpcm.c
@@ -57,7 +57,7 @@
 #define MAX_BUFFER_DELAY (READ_AREA_START + READ_AREA_SIZE)
 #define MIN_GUARD_SIZE 1024
 #define MIN_READ_GUARD_PERIOD (1000000 * MIN_GUARD_SIZE / (2 * 44100))
-#define WR_BUFFER_LW (BUFFER_DELAY / 2)
+#define WR_BUFFER_LW (BUFFER_DELAY / 3)
 #define MIN_READ_DELAY (MIN_BUFFER_DELAY + MIN_READ_GUARD_PERIOD)
 #define WRITE_INIT_POS (WRITE_AREA_SIZE / 2)
 
@@ -776,9 +776,9 @@ user_tstamp:
        return now - WRITE_INIT_POS;
 
     case SNDBUF_STATE_STALLED:
-       pcm.stream[strm_idx].stretch_per = now - WRITE_AREA_SIZE -
+       pcm.stream[strm_idx].stretch_per = now - WRITE_INIT_POS -
                pcm.stream[strm_idx].stop_time;
-       return now - WRITE_AREA_SIZE;
+       return now - WRITE_INIT_POS;
 
     case SNDBUF_STATE_FLUSHING:
        if (pcm.stream[strm_idx].stretch)
```

I do not claim to understand that code,
but it seems something like this can
relief the timing constraints.

**Comment by stsp** [comment]
I actually applied even the more
relaxed patch. Hope this won't cause
some clicking or delays...
Since I can't reproduce the problem,
this is just a wild guess. Let me know
if the patch doesn't help.
