### ISSUE TITLE
boot.log not properly rotated

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2183]
### Discussed in https://github.com/dosemu2/dosemu2/discussions/2182

<div type='discussions-op-text'>

<sup>Originally posted by **j2969719** April  1, 2024</sup>
I noticed a small oddity, not sure if this is really an issue or if I simply misunderstood something as usual, so posting here:
old copies of boot.log.1-boot.log.3 gradually appear in the ~/.dosemu folder, but it seems that boot.log.2 and boot.log.3 are never actually overwritten?</div>

**Comment by stsp** [comment]
Should now be fixed, please check.

**Comment by j2969719** [comment]
Сonfirm
