### ISSUE TITLE
dosemu2 can't write to mounted network drive (CIFS type)

### ISSUE THREAD

**Issue by William0027** [dosemu2/dosemu2#2188]
**Describe the bug**
Installed dosemu2 ver 2.0pre9 on Ubuntu 23.10 kernel 6.5.0-26-generic
DOSEMU seemed work normally. The problem occur when I tried to create a file on mounted network drive or copy files between local drive and network drives on Ubuntu server.
I used EDIT to create a txt file on C:, no problem. Tried to create or save the file on network drive it said unable to create or access the file. For copy, a file with 0 size is create when I tried to copy a file from local to network and vice versa.
Network drive is on a Ubuntu server (18.04), mounted on /etc/fstab.
I check on Terminal, permission is no problem, all -rwxrwxrwx and I can copy file just fine from local to mounted network drive using Terminal command line, vice versa.
It seemed that I don't have the permission to write on this mounted network drive in DOSEMU environment. 

**To Reproduce**
Steps to reproduce the behaviour:
- open terminal, run DOSEMU
- create a file using EDIT, try to save it to H: (mounted network drive), a message saying unable to create or access the xxxx file

**Attach program/game binaries or provide an URL**

'# /etc/fstab: static file system information.
'#
'# Use 'blkid' to print the universally unique identifier for a
'# device; this may be used with UUID= as a more robust way to name devices
'# that works even if disks are added and removed. See fstab(5).
'#
'# <file system> <mount point>   <type>  <options>       <dump>  <pass>
'# / was on /dev/sda2 during curtin installation
/dev/disk/by-uuid/3042c5ae-0c04-474a-936c-e54b084e7490 / ext4 defaults 0 1
/swap.img	none	swap	sw	0	0

//192.168.0.223/allusers /mnt/cifsmounth cifs noperm,noserverino,cache=none,username=user,password=pass,dir_mode=0777,file_mode=0777,uid=1000,gid=1000	0	0

usr/share/dosemu/dosemu2-cmds-0.3/fdppauto.bat content :

@echo off
rem autoexec.bat for DOSEMU2 + FDPP
path %DOSEMUDRV%:\dosemu;c:\fpd26
if not "%SHELLDRV%" == "" path %PATH%;%SHELLDRV%:\
if not "%FREEDOSDRV%" == "" path %PATH%;%FREEDOSDRV%:\bin;%FREEDOSDRV%:\gnu
if not "%USERDRV%" == "" set TEMP=%USERDRV%:\tmp
rem first run external plugins. -E commands may depend on them.
if "%XBATDRV%" == "" goto noxbat
path %PATH%;%XBATDRV%:\
for %%b in (%XBATDRV%:\dosrc.d\*.bat) do call %%b
:noxbat
rem run dosemu2 plugins, including vars and -E commands.
for %%b in (%DOSEMUDRV%:\dosemu\dosrc.d\*.bat) do call %%b
lredir h: linux\fs/mnt/cifsmounth

**Attach the log**
boot.log

FDPP kernel "- GIT " (compiled Mar 30 2024)
fdpp: plugin loaded: 1
booting with comcom64
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: dos_up: on
CONF: DPMI-Server on (0x20000)
CONF: DPMI base addr = 0x20000000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes int15 ext memory
CONF: 16384k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
default_drives 0
Setting up drive C, /home/linux-backup-1/.dosemu/drive_c
Added drive 0 (80): /home/linux-backup-1/.dosemu/drive_c
default_drives 1
Added drive 1 (81): /usr/share/dosemu/dosemu2-cmds-0.3
Setting up default drives from E
Added drive 2 (82): /usr/share/comcom64
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 enabled.
CONF: config variable c_system unset
Command line: /usr/bin/dosemu.bin -o /home/linux-backup-1/.dosemu/boot.log
Warning: Your CPU doesn't support UMIP
Warning: Linux kernel 6.5.0; CPU speed is 3198767000 Hz
Warning: CPU-EMU speed is 3199 MHz
CONF: V86 cpu vm set to -1
CONF: DPMI cpu vm set to -1
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
Warning: dosemu2-2.0pre9 is coming up on Linux version 6.5.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024 x86_64
Warning: Compiled with clang version 16.0.6 (gnuc 4.2)Warning:  64bit
Warning: CFLAGS: -Wno-microsoft -Wno-incompatible-pointer-types -Wno-address-of-packed-member -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wundef -fno-stack-protector -ggdb3 -fdebug-macro -fpie -g -O2 -ffile-prefix-map=/build/dosemu2-pYXh2Q/dosemu2-2.0~pre9-8588=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/dosemu2-pYXh2Q/dosemu2-2.0~pre9-8588=/usr/src/dosemu2-2.0~pre9-8588-6169ffd5d+202404062016~ubuntu23.10.1
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 16Kb at 0xFA000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
Warning: Using V86 mode inside KVM
VID: initializing SDL plugin
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Registering HWRAM, type=L base=0 size=0x110000
Conventional memory mapped from 0x746dbfc00000 to 0x746d95200000
CONF: reserving 16384Kb at 0x900000 for 'x' ((null))
CONF: reserving 8128Kb at 0x110000 for 'X' (EXT MEM)
Registering HWRAM, type=X base=0x110000 size=0x1ef0000
Registering HWRAM, type=U base=0x28710000 size=0x1ef0000
CONF: reserving 64Kb at 0x100000 for 'H' (HMA)
loading fonts for cp437
Registering HWRAM, type=e base=0xe0000000 size=0x400000
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
VID: initializing video sdl
VID: SDL plugin initialization completed
Warning: SERIAL $Id$
Warning: userspace pings are disabled.
	To enable them, do as root:
	echo 0 65535 > /proc/sys/net/ipv4/ping_group_range
DPMI: mem init, mpool is 140468224 bytes at 0x746db5200000
Warning: Using DPMI inside KVM
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
CONF: freeing region for 'E' (EMS page frame)
booting comcom64
config.boot_dos set to 400000
config.int_hooks set to 0
config.force_revect set to 0
CONF: reserving 116Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 40Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
loading comcom64.exe
DOS termination requested
leavedos(do_doshelper:65|0) called - shutting down
coopth_unsafe_detach() called by build/../src/plugin/dj64/djdev64.c
leavedos thread started
leavedos thread ended
coopthreads stopped

Package info:
dosemu2: installed
dosemu2	2.0~pre9-8588-6169ffd5d+202404062016~ubuntu23.10.1
fdpp: installed
fdpp	1.7-1501-091c157+202403301131~ubuntu23.10.1
dj64: installed
dj64	0.1-0~202404032132+202404032216~ubuntu23.10.1
comcom64: installed
comcom64	0.1-0~202404032205+202404041401~ubuntu23.10.1

**dosemu2 origins**
installed from terminal
sudo add-apt-repository ppa:dosemu2/ppa
sudo apt update
sudo apt install dosemu2

**Comment by stsp** [comment]
> It seemed that I don't have the permission to write on this mounted network drive in DOSEMU environment.

Permission scheme is not yet implemented
(but it will be, so you'll get the desired problems :)
This is more likely a lack of extended attributes
(user xattrs) support, or range locks support.

Andrew, do you remember what problems we
have with cifs? One day that all should be documented...

In a mean time, please produce a `-D9+Dd`
log, and add it here as an attachment, not
inline.

**Comment by andrewbird** [comment]
> Andrew, do you remember what problems we
have with cifs?

I never tried with CIFS, but I have successfully used (but lots of warnings) on NFS before v4.2, which had no xattr support.

> In a mean time, please produce a -D9+Dd log

Also the CIFS server log would be useful, if possible.

**Comment by William0027** [comment]
[boot.log](https://github.com/dosemu2/dosemu2/files/14897661/boot.log)

**Comment by William0027** [comment]
ERROR: MFS: failed to set xattrs for /mnt/cifsmounth/erp_1/test/write.txt: Operation not supported
ERROR: MFS: failed to set xattrs for /mnt/cifsmounth/erp_1/test/write.txt: Operation not supported
ERROR: MFS: failed to set xattrs for /mnt/cifsmounth/erp_1/test/~0xx.tmp: Operation not supported

**Comment by stsp** [comment]
This is not a `-D9+Dd` log.

**Comment by stsp** [comment]
@jschwartzenberg IIRC you were the last
one testing on some no-xattr FS. Can you
re-check if things still work?

**Comment by stsp** [comment]
@William0027 please add the `-D9+Dd` log
or nothing can be done here.

**Comment by William0027** [comment]
Sorry for late reply. Just back from holiday. Will submit ASAP

**Comment by William0027** [comment]
Hi, can you tell me how to produce -D9+Dd log ? Sorry for my ignorance, I
tried to search web but nothing came out.

**Comment by stsp** [comment]
By running `dosemu -D9+Dd`

**Comment by William0027** [comment]
okay. thanks

**Comment by William0027** [comment]
[boot.log](https://github.com/dosemu2/dosemu2/files/14967396/boot.log)

**Comment by William0027** [comment]
hope this one is correct

**Comment by stsp** [comment]
There are too many things in the log.
Creating, deleting multiple times.
Please reproduce the problem just
once, attach the log, and tell exactly
what you did and what was the problem.

**Comment by William0027** [comment]
[boot.log](https://github.com/dosemu2/dosemu2/files/14968971/boot.log)

**Comment by William0027** [comment]
I deleted all old boot.log files in ~/.dosemu folder.
run dosemu -D9+Dd
run Edit from command line
try to save to H:\erp_1\test\test8.txt using save as..
failed, then exit without saving
exitemu
that's all
But, when I checked, the log file is so long.

**Comment by stsp** [comment]
I've found the problem:
```
MFS: error, region already locked
```
I think you are hitting this bug:
https://www.uwsg.indiana.edu/hypermail/linux/kernel/1806.3/01437.html
Try `nobrl` mount option to disable
the byte-range locks.

**Comment by William0027** [comment]
Tried nobrl, can save file on network drive now. Terminal shows ERROR: MFS: failed to set xattrs for ...., but it's ok

**Comment by William0027** [comment]
Will do more tests and update. Thank you very much !

**Comment by stsp** [comment]
So cifs doesn't support both xattrs
and brlocks, and doesn't even report
that brlocks are unsupported...
Pure piece of crap.

**Comment by William0027** [comment]
Everything works flawlessly now. Thank you for your help ! So I guess I can close this thread now ?

**Comment by William0027** [comment]
Everything works flawlessly now. Thank you very much for your help !
