### ISSUE TITLE
run-time error M6111: MATH

### ISSUE THREAD

**Issue by haenschen** [dosemu2/dosemu2#2203]
**Describe the bug**
Legacy application crashes
```
run-time error M6111: MATH
floating-point error: stack underflow
```

**Attach the log**
Which debug flags are helpful? -D9 log
[boot.log](https://github.com/dosemu2/dosemu2/files/15142822/boot.log)

**A regression?**
[dosemu2-2.0pre6](https://github.com/dosemu2/dosemu2/releases/tag/dosemu2-2.0pre6) is fine :sweat_smile:
But I think it also used to work some weeks/months ago...

**dosemu2 origins**
latest devel

**Additional info**
Tested freecom and comcom32 from ppa

**Comment by haenschen** [comment]
Error doesn't happen with
`$_cpu_vm = "emulated"`

**Comment by stsp** [comment]
Can you provide an application?

**Comment by stsp** [comment]
Please always write an updates on
github, after sending private e-mails.
I've occasionally found your e-mail
in spam.
