### ISSUE TITLE
Don't seem to be able to compile dosemu2 now

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#2205]
**Describe the bug**
Don't seem to be able to compile dosemu2 now

**To Reproduce**
Try to compile.

**Attach program/game binaries or provide an URL**

**Attach the log**
~~~
cpu-emu.c:1158:25: error: unknown type name '_Float128'
    union { float128 f; _Float128 ld; } y;
                        ^
cpu-emu.c:1183:25: error: unknown type name '_Float128'
    union { float128 f; _Float128 ld; } y = { .ld = TheCPU.fpregs[k] };
                        ^
~~~

**A regression?**
Yes

**dosemu2 origins**
Git

**Additional info**
Ubuntu 22.04

**Comment by stsp** [comment]
Probably fixed now, please check.

**Comment by andrewbird** [comment]
Cool, that's fixed. Thanks!
