### ISSUE TITLE
Redirector int 2Fh function 112Dh expected by MS-DOS v4.00 missing

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#2206]
**Describe the bug**
The command.com builtins `copy` and `type` of MS-DOS v4.00 depend on [some int 21h function 57h subfunctions](https://fd.lod.bz/rbil/interrup/dos_kernel/215702.html). The kernel redirects these to [int 2Fh function 112Dh](https://fd.lod.bz/rbil/interrup/network/2f112d.html#sect-4395) on dosemu2 MachFS drives.

**To Reproduce**
Try running `copy somefile.dat e:\tmp` (NB no trailing slash after a subdirectory name allowed.) or `type somefile.dat`

**Attach program/game binaries or provide an URL**
https://pushbx.org/ecm/download/old/msdos4/20240430.zip has io.sys, msdos.sys, command.com needed to reproduce

**A regression?**
No / very unlikely.

**dosemu2 origins**
From git.

**Additional info**
I [made the redirector functions optional](https://hg.pushbx.org/ecm/msdos4/rev/cf97c97c1d9b) for my patched MS-DOS v4.00 fork.

Here's [the kernel implementation](https://hg.pushbx.org/ecm/msdos4/file/609bbd2ecff2/src/DOS/HANDLE.ASM#l559) of the functions. A little below it there's [the passing onto the redirector](https://hg.pushbx.org/ecm/msdos4/file/609bbd2ecff2/src/DOS/HANDLE.ASM#l620). Apparently the redirector is expected to pass along its return values to the int 21h caller by modifying the user stack frame directly (only CF/error ax get handled by DOS).

**Comment by stsp** [comment]
Where do they store these on fat?

**Comment by ecm-pushbx** [comment]
They don't, if you follow the call chain you'll find https://hg.pushbx.org/ecm/msdos4/file/609bbd2ecff2/src/DOS/EXTATTR.ASM which has a lot of "FAKE FAKE" comments. Apparently writes are ignored and reads return either the buffer size (2) or a single word reading 0.

**Comment by stsp** [comment]
Then why do we want to implement them?
Why there are some problems with them
unimplemented?

**Comment by ecm-pushbx** [comment]
The command.com in the (unpatched) v4.00 release depends on them. Try booting these files and run `copy` or `type` on dosemu drives.

**Comment by stsp** [comment]
But how can this be if they are not
implemented/fake?

**Comment by ecm-pushbx** [comment]
Presumably it was planned but not included in the release. I don't know a point to calling these but it's what command.com does.

**Comment by stsp** [comment]
So am I right that all we need it
to always return some empty list?
If so, can you make such a patch?

**Comment by ecm-pushbx** [comment]
My patched version works fine so my need for a dosemu patch is not big. Just wanted to report it for the record.

**Comment by stsp** [comment]
But can you tell exactly what
should be enough to implement?

**Comment by ecm-pushbx** [comment]
You can look at the interrupt list which I linked to begin with; the description of the redirector function is a bit sparse but basically you should mimic what the DOS kernel does for local drives:

> The command.com builtins copy and type of MS-DOS v4.00 depend on [some int 21h function 57h subfunctions](https://fd.lod.bz/rbil/interrup/dos_kernel/215702.html). The kernel redirects these to [int 2Fh function 112Dh](https://fd.lod.bz/rbil/interrup/network/2f112d.html#sect-4395) on dosemu2 MachFS drives.

You will find what is sufficient if you study the sources I linked:

> Here's [the kernel implementation](https://hg.pushbx.org/ecm/msdos4/file/609bbd2ecff2/src/DOS/HANDLE.ASM#l559) of the functions. A little below it there's [the passing onto the redirector](https://hg.pushbx.org/ecm/msdos4/file/609bbd2ecff2/src/DOS/HANDLE.ASM#l620). Apparently the redirector is expected to pass along its return values to the int 21h caller by modifying the user stack frame directly (only CF/error ax get handled by DOS).

and

> They don't, if you follow the call chain you'll find https://hg.pushbx.org/ecm/msdos4/file/609bbd2ecff2/src/DOS/EXTATTR.ASM which has a lot of "FAKE FAKE" comments. Apparently writes are ignored and reads return either the buffer size (2) or a single word reading 0.

**Comment by stsp** [comment]
Obviously there is no need to implement
those. They just need to return no error,
or maybe an empty descriptor, or something
like that.

**Comment by ecm-pushbx** [comment]
Yes.

> Apparently writes are ignored and reads return either the buffer size (2) or a single word reading 0.
