### ISSUE TITLE
DR-DOS 7.01 file copy rejected

### ISSUE THREAD

**Issue by andrewbird** [dosemu2/dosemu2#2211]
**Describe the bug**
Copying a file from one directory to a subdirectory is rejected
~~~
C:\>testit.bat
testit.bat

C:\>
C:\>copy version.bat c:\tmp
Source and Destination cannot be the same file
       0 File(s) copied
~~~

**To Reproduce**
Run new test from my ci-105 branch https://github.com/andrewbird/dosemu2/tree/ci-105
    `./test/test_dos.py DRDOS701TestCase.test_command_com_command_copy`

**Attach program/game binaries or provide an URL**
https://github.com/andrewbird/dosemu2/tree/ci-105

**Attach the log**
An earlier test run can be seen here (I've since removed the call to mkdir \tmp as it's always there) https://github.com/andrewbird/dosemu2/actions/runs/9083304735/job/24961718871

**A regression?**
Unknown - I spotted that I couldn't build freecom on DR-DOS 7.01, but I find it hard to believe that such a basic command was never working.

**dosemu2 origins**
git

**Additional info**

**Comment by stsp** [comment]
Could you please specify the reproducing
steps using a command-line, rather than
test_dos.py? test_dos.py only say "failure",
but its hard to go from there.
Or maybe you can add some option to
test_dos.py to not launch the test, but
stop at the interactive prompt?

OTOH when I run the pre-existing copy
of dr-dos 7.01 and do "copy bugs.txt tmp",
it copies the file.

**Comment by stsp** [comment]
> test_dos.py to not launch the test, but
> stop at the interactive prompt?

Or even better - prepare the test and print
a command it is going to use to start this
test, and exit.

**Comment by stsp** [comment]
Its not a dr-dos even.
Its Caldera OpenDOS.
Yes, with that one I can reproduce.

**Comment by andrewbird** [comment]
Okay I'll sort something out in few hours.

**Comment by stsp** [comment]
So it seems int21h/ah=0x60 (truename)
calls int2fh/ax=0x1123 (qualify filename).
We do not implement this.
All other DOSes are fine with that, and
all other functions that call 1123 internally,
are fine with the failure. But "truename"
returns with CF set.
I suspect command.com doesn't check
CF and looks into an output buffer anyway,
finding the same content there. And from
that it deduces the copy is to the same
location.

**Comment by stsp** [comment]
So this works:
```
--- a/src/dosext/mfs/mfs.c
+++ b/src/dosext/mfs/mfs.c
@@ -4256,6 +4256,10 @@ do_create_truncate:
         Debug0((dbg_fd, "Qualify Filename: %s -> %s\n", name, dst));
         return TRUE;
       }
+      if ((((u_short *)sda_user_stack(sda))[0] >> 8) == 0x60) {
+        strcpy(dst, name);
+        return TRUE;
+      }
       break;
     }
 
```

I don't know what would be a proper fix.
Bart was always against implementing
that function and it would be interesting
to find out what he thinks about that problem.
But I haven't heard from him for very long... :(

**Comment by stsp** [comment]
OK, I recalled that, unlike dosemu1,
dosemu2 has this second_revect machinery,
where we can add a small fix-ups like
this one. So the "fix" appears trivial. :)

**Comment by stsp** [comment]
2 libi86 tests failed:
https://github.com/dosemu2/dosemu2/actions/runs/9085777250/job/24969889885
But locally they are OK...
Could you please check?

**Comment by andrewbird** [comment]
Worked okay on my branch. Not sure why those tests (which seemed to be unrelated) failed for you.

**Comment by stsp** [comment]
So we seem to have some instability,
which chooses only the "fscking" tests -
the ones where you can see nothing
informative in the logs.
How about dropping the libi86 tests?
They don't show up anything useful
in the logs, so you end up debugging
the test, not the program...
Of course unless they can be fixed.
But you already said they can't?

**Comment by andrewbird** [comment]
Yes we could drop them, a different one just failed in my PR!

**Comment by andrewbird** [comment]
I added a commit to my PR to disable the libi86 tests, which is a shame because they gave a lot of coverage, but as you said they are difficult to debug.
