### ISSUE TITLE
ERROR: cpu exception in dosemu code outside of DPMI client!

### ISSUE THREAD

**Issue by mbagdasarov** [dosemu2/dosemu2#2216]
**Describe the bug**
dosemu -2 -dumb (same as just dosemu) prints
`Process 0 starting: E:\command.com /e:384 /p /k %FDPP_AUTOEXEC% /M2
CPU set to 286
ERROR: alsa_midi:default (ALSA err 2): open /dev/snd/midiC0D0 failed: No such file or directory
snd-virmidi module not loaded or device "default" not configured
see "amidi -l" for the list of midi devices
dosemu.bin: thunks.c:232: dj64init: Assertion disp_fn failed.

ERROR: cpu exception in dosemu code outside of DPMI client!
Aborted (Signal sent by tkill() 720950 1000)
`

**To Reproduce**
I have the same behaviour downloading image from ubuntu ppa and building locally, both debug and release versions, so
for me it's sufficient to do just `git clone ... && cd dosemu2 && ./autogen.sh && ./default-configure -d && make; sudo make install`

Log file:
[boot.log](https://github.com/user-attachments/files/15533346/boot.log)

**Comment by stsp** [comment]
The problem is that `comcom64` package
is not yet updated in PPA. It will soon happen,
and the problem will go away.
Am I right everything worked for you
properly till yesterday?

Anyway, Mikhail Bagdasarov, is this really you? :)

**Comment by mbagdasarov** [comment]
Yep, it's me :) If you happen to have any messenger, I would be more than happy to have a chat.
mbagdasarov at protonmail.com <<= my e-mail

I haven't used dosemu2 on this machine before, so, unfortunately, I can't really verify whether it's regression or not.
Let's wait then for comcom64, hope it'll help

**Comment by stsp** [comment]
Wow!
How have you even came here? :)

I removed the crashing assert now,
but there will be a boot failure anyway,
before comcom64 is updated.
You took an exceptionally unfortunate
time-frame, because I pushed a very
big update just yesterday, and now am
facing the problems like this one.
Things are very stable most of the time,
so you just got out of luck exactly today. :(

**Comment by stsp** [comment]
I think all components have now updated,
so things should work. Please let me know
if they still don't.

Also I mailed to the aforementioned address,
but was probably spam-blocked. I only have
the session-desktop messenger, its open-source.
Looking forward to see you there. :)

**Comment by stsp** [comment]
Got this mail delivery failure today from
the last week's mailing:
```
<mbagdasarov at protonmail dot com>: host mailsec.protonmail.ch[185.70.42.129] refused
    to talk to me: 421 4.7.0 mailin027.protonmail.ch Error: too many
    connections from 178.154.239.215
```

So unless you provide another e-mail
address or install session, I can't reach
you. :(
