### ISSUE TITLE
how to add an user in deb package?

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2223]
Hi @skitt 

I can't get dh_installsysusers to work.
I did this (in a separate branch):
https://github.com/dosemu2/dosemu2/commit/768ea02d7eb7477267d2c292474795d4f6f10988
but it doesn't add any user.
Could you please help?

**Comment by skitt** [comment]
User creation in Debian packages is done with `addgroup` and `adduser`, not `dh_installsysusers` (at least, not commonly, yet). https://wiki.debian.org/AccountHandlingInMaintainerScripts gives details; in your case:

```
addgroup --system _dosemu2
adduser --system --group _dosemu2 _dosemu2
```

etc.

I haven’t tried `dh_installsysusers` yet; I gather from its documentation that it’s supposed to add snippets for `postinst` scripts, so you’d need

```
#DEBHELPER#
```

in your script (which is recommended in `postinst` scripts anyway). Presumably if you had that before the `case` statement then you’d be able to use the created users.

**Comment by stsp** [comment]
Thanks!
`#DEBHELPER#` actually worked!
But I suppose you suggest `adduser`
nevertheless, as compat==14 is probably
an unacceptable compatibility break?
Do you know since what ubuntu it is
supported?

Also I guess you don't actually need
`addgroup` here, as `adduser` adds
both by default. But that's minor.
The bigger problem is this one:
https://bugzilla.redhat.com/show_bug.cgi?id=2294815
Which means I probably can't do that
on rpm just yet.
So I guess its not the right time to
commit these changes just yet. :(

**Comment by stsp** [comment]
Hmm, otoh I can probably just use
postinst also there, instead of waiting
for the fix...

**Comment by skitt** [comment]
`adduser` in current unstable [creates system users in the `nogroup` group](https://manpages.debian.org/unstable/adduser/adduser.8.en.html#Add_a_system_user), that’s why I explicitly used `addgroup`.

`debhelper` compatibility level 14 is still undergoing development. For `dh_installsysusers` in level 14, you need 13.8 or later, which means 23.10 or later.

**Comment by stsp** [comment]
Understood, thanks!
I guess `nogroup` is fine with me,
as `dosemu2` is a pseudo-user anyway,
that can only own the files in /tmp.

**Comment by stsp** [comment]
Even %post in rpm is running before
adding the user... So in rpm its completely
broken.

**Comment by stsp** [comment]
I've done this:
```
execute_after_dh_installinit:
        dh_installsysusers
```
to leave things at compat 12.
That worked quite well, except for
the Focal, which says:
`dh_installsysusers: Command not found`.
Is there any way to make that
command conditional somehow?
Or just finally dropping Focal may be
a better option...

**Comment by stsp** [comment]
```
execute_after_dh_installinit:
        dh_installsysusers || true
```
quite works. :)
