### ISSUE TITLE
Cannot start DOSEMU2

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#2225]
**Describe the bug**
DOSEMU2 reaches an invalid opcode quickly after starting.

**To Reproduce**
Steps to reproduce the behaviour:
Starting it up on a machine with the same specs as mine.

**Attach program/game binaries or provide an URL**
n.a.

**Attach the log**
[boot.log](https://github.com/user-attachments/files/16113818/boot.log)

**A regression?**
yes

**dosemu2 origins**
self-built, no customizations

**Comment by stsp** [comment]
`Warning: MFS: couldn't find path /home/julius/.dosemu/drive_c/`
Does that exist?
Can you give an ssh? :)

**Comment by jschwartzenberg** [comment]
That's there:
```
[julius@elleboog ~]$ ls -lhd /home/julius/.dosemu/drive_c
drwxr-xr-x 53 julius julius 12K mrt 15 20:52 /home/julius/.dosemu/drive_c
```

Let me look into SSH...

**Comment by jschwartzenberg** [comment]
![Screenshot_20240706_002932](https://github.com/dosemu2/dosemu2/assets/877112/cf9802fd-599c-4365-b1bf-fc01572ad54a)

**Comment by stsp** [comment]
I added the work-around, could you
please re-check?

**Comment by jschwartzenberg** [comment]
With eb29f2f29f7b48f847d2c3bc128d7f9d7f306168 (current devel) it works.

**Comment by stsp** [comment]
I pushed a few fixes, but it will take
some time before I re-enable priv sep.

**Comment by stsp** [comment]
"Cannot continue from exception" is
now fixed in dj64dev.

**Comment by stsp** [comment]
... and in comcom64.

**Comment by andrewbird** [comment]
Do you need to update the PPA for dj64dev, I get missing `/usr/include/djdev64/dj64thnk.h` when I try to build dosemu2?

**Comment by stsp** [comment]
No, just do `make clean` in dosemu2 first.
Also you need to re-enable priv sep manually
for now, by uncommenting this line:
https://github.com/dosemu2/dosemu2/blob/devel/src/base/core/emu.c#L358

**Comment by stsp** [comment]
Also you won't hit any bugs at all,
because priv sep is not enabling itself
w/o `make install`. Since you never do
`make install`, you avoid any troubles.

**Comment by andrewbird** [comment]
Thanks, that fixed the build for me. Actually I'm just running the coverity build as it's been a while.

**Comment by stsp** [comment]
Yeah, makes sense!
I'll make sure to not do any more
radical changes before the next -pre
release. So checking things would be
good.

**Comment by stsp** [comment]
Another attempt to re-enable priv sep.
Please test!

**Comment by stsp** [comment]
Nope, not doing that. :)

**Comment by stsp** [comment]
OK, passed CI.
So hope it now works. :)
But at the same time, there
could be 1024+ more places
in the code that needs updating
to priv sep. Only testing can tell.
