### ISSUE TITLE
virtual comport broken with priv sep

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2227]
### Discussed in https://github.com/dosemu2/dosemu2/discussions/2226

<div type='discussions-op-text'>

<sup>Originally posted by **nelgin** July  6, 2024</sup>
I just noticed on my BBS that dosemu2 games. is no longer working. Games just exit right back to the menu. They seem to work in local mode. I've regressed my BBS software back to March and still see the problem so I'm guessing the a regression with dosemu2 somewhere.

I'd like to install the previous version, dosemu2 2.0~pre9-8552-fe5977761+202403162131~ubuntu22.04.1, but I don't see the binary .deb files anywhere. Google throws up nothing.

Does anyone know a place to get this and any related dependencies? I may need to go back a few months. Maybe I am going to have to build the older version myself, which isn't ideal because it wouldn't re-create, exactly, the ppa version.

Thanks,
</div>

**Comment by stsp** [comment]
Quote from discussions:

/dev/pts/3 is probably the tty device that spawns dosemu. In a shell if you sudo you get a new tty device.

CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
SER0: /dev/pts/5

It looks like it's using it as the serial device?

bbs@bbs:/sbbs/exec$ tty
/dev/pts/1
bbs@bbs:/sbbs/exec$ sudo tty
/dev/pts/5

**Comment by stsp** [comment]
> /dev/pts/3 is probably the tty device that spawns dosemu.

Ah, for the "virtual" comport that
certainly makes sense.

@nelgin
I added the small patch to branch
"virt". Please make sure it doesn't
break virtual comport. Priv sep is
already disabled in that branch, so
things should work w/o extra efforts.
If this patch is not breaking anything,
I'll include it when priv sep is finally
fixed.

**Comment by nelgin** [comment]
Glad we got to the bottom of that one quickly. Thanks for the speedy response.
