### ISSUE TITLE
Netscape 2.0 installation crashes and triggers DPMI issue

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#2231]
**Describe the bug**
This assertion failure is shown after trying to install Netscape 2.0 and trying to exit Windows after that fails:
```
dosemu2.bin: dpmi.c:1641: post_rm_call: Assertion `old_client <= in_dpmi - 1' failed.

Aborted (Signal sent by tkill() 26549 1000)

ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

removing stale files:
/var/run/user/1000/dosemu2/dosemu.dbgin.26549
/var/run/user/1000/dosemu2/dosemu.dbgout.2654
```

**To Reproduce**
1. Extract the files
2. Start Windows 3.1
3. Run the `setup.exe`
4. You'll get an error message suggesting to restart your system:
![Screenshot_20240707_213435](https://github.com/dosemu2/dosemu2/assets/877112/dd10a76c-8850-4b16-aeaa-2295aa0e2fcf)
Followed by another error message:
![Screenshot_20240707_213541](https://github.com/dosemu2/dosemu2/assets/877112/9b4bc2ee-401f-4d07-9144-a5f50539fdc1)
5. Close the errors
6. Try to exit Windows
7. DOSEMU2 will hang with the assertion failure output

**Attach program/game binaries or provide an URL**
http://ftp.lanet.lv/ftp/windows/www/netscape2.02/n16e202.exe

**Attach the log**
[boot.log](https://github.com/user-attachments/files/16120517/boot.log)

**A regression?**
I think this used to work.

**dosemu2 origins**
self-built

**Comment by stsp** [comment]
I don't think this ever worked.
This requires win32s to run.
What worked is netscape-408.
But even that one broke because
of the `win87em.dll`'s famous bug.

**Comment by stsp** [comment]
You can still get netscape-408 running
with `$_cpu_vm_dpmi = "emulated"`,
although its rather slow that way.

**Comment by stsp** [comment]
Oh, and in fact, netscape-408 works
perfectly with `$_mathco = (off)`, wow!
@stefand IIRC you asked me about that.
Sorry for such an obvious solution
provided that late! :)

**Comment by stsp** [comment]
OK, I made it so that no need to
even disable `$_mathco` - its now
automatic.
`win87em.dll`'s problem solved! :)

**Comment by stefand** [comment]
I think you pointed out $_mathco to me at the time. I think there was a bug that made it not work back in the day but you fixed it fairly quickly.

Wouldn't it be better to make $_mathco default to disabled? With the win31 hack, doesn't that mean that I can't enable the coprocessor without a code change even if I want to?

Thinking further: It should be able to detect the CPU bug (run a FPU instruction, save FPU state, see if %cs has a non-zero value) and make dosemu pick a default or "auto" value based on that.

**Comment by stsp** [comment]
I think the hack is rather harmless.
Userspace apps do not care: they
use FPU if needed, relying on an OS
emulation of it, if anything. Since FPU
is not actually disabled (via cr0), they
will still work on a real FPU.
I think its only for win87em.dll: it stops
using the FPU natively.
If you find any problems with it, please
let me know, but for now I hope that's
fine as-is.

**Comment by stsp** [comment]
Anyway, the installer of Netscape 2.0
does the wild jump, namely it jumps
70 bytes before PSP. What does it expect
there, is unclear, and eventually the code
pointer gets to `cd20` of PSP, which is
a process termination.
Maybe win32s puts something there
(that we do not), or maybe the problem
is elsewhere.
Given that netscape-4 works fine now,
I don't think its important to debug the
"bad exit" of some win32s-based app.
Unless of course you can prove it actually
worked better in the past, or that it works
differently on other emulators.

**Comment by jschwartzenberg** [comment]
I thought win32s wasn't supported at all? I don't have win32s installed. Does this installer have its own copy?

**Comment by stsp** [comment]
That's why it doesn't work.

**Comment by jschwartzenberg** [comment]
Cool that 4.08 is working though :)
I just logged on with AIM through phoenixim.ddns.net:
![Screenshot_20240709_221350](https://github.com/dosemu2/dosemu2/assets/877112/0f7b22fa-0db5-4757-8bae-e9590f0f8ff2)

**Comment by stsp** [comment]
Hmm, so you managed to use that
twinsock? You are not even on trumpet?

**Comment by stefand** [comment]
> I think the hack is rather harmless. Userspace apps do not care: they use FPU if needed, relying on an OS emulation of it, if anything.

This is from memory from years ago:

If Windows thinks there's no FPU, the NE loader will replace FPU instructions with int 0x34 to int 0x3e instructions that will eventually be handled by win87em.dll. The .exe / .dll files have special relocation markers for that.

So while you are correct that if an application executes an FPU instruction it won't care about the $_mathco setting, all well behaved win16 applications will have their FPU instructions patched out by Windows. You can tell the difference by running the simple benchmark in Microsoft's FPU coding example (winfloat.exe -> floatapp.exe):

off: 385 ms
on: 109 ms

(The test tells you the time it needed, so lower is better. This is with $_cpu_vm_dpmi = "kvm". "native" is a lot slower in this case.)

In Wine the test takes 0 ms - we discussed this before: Even with an FPU present Windows replaces fwait with 0x3d ints, which take quite some time. Wine totally ignores the float relocs, so fwait will just be an fwait.

**Comment by stsp** [comment]
Ok, so we can add "auto" value, which
means "disabled under win31, enabled
otherwise", as it is now.
How important is that, given the low
use of win31 under dosemu2, and the
fact that all apps work anyway? Do you
expect someone to notice any slowdown,
dig google, find this thread and re-enable
$_mathco under win31?

> Thinking further: It should be able to detect the CPU bug (run a FPU instruction, save FPU state,
> see if %cs has a non-zero value) and make dosemu pick a default or "auto" value based on that.

I don't think this makes any sense, as
I have that problem on an AMD Phenom2
from early 2000s. IIRC there were 2
separate problems, like that Intel completely
deprecated FPU pointers in newer CPUs,
and that under KVM you get the 64bit-compatible
state format, where they were deprecated
from the very beginning (I may be wrong on
the details though).
