### ISSUE TITLE
Doors stopped working again

### ISSUE THREAD

**Issue by nelgin** [dosemu2/dosemu2#2240]
**Describe the bug**
I just updated and noticed my DOS doors are not working via my BBS again. I am not sure when they stopped, unfortunately.

**To Reproduce**
Setup a Sycnhronet BBS with dosemu2 support, run the game...

**Attach program/game binaries or provide an URL**
Any dos program. Not sure attaching a binary will help since it works standalone, not via the BBS.

**Attach the log**
Attached

**A regression?**
It worked on earlier versions of dosemu before this privilege separation thing?

**dosemu2 origins**
PPA

**Additional info**
Yeah, you hate this...

/usr/bin/env HOME=/sbbs/ctrl  /usr/bin/dosemu -quiet -dumb -no-priv-sep -d /sbbs/node2/ -d /sbbs/xtrn -d /sbbs/ctrl/ -d /sbbs/data/ -d /sbbs/exec/ -d /sbbs/xtrn -f/sbbs/ctrl/dosemu.conf -ED:external.bat -o/sbbs/node2/dosemu_boot.log  -D+a

external.bat looks like this, fwiw
```
$ cat external.bat
SET BRAINEX=E:\BRAINEX\BRAINEX.INI
PATH=%PATH%;E:\BRAINEX

E:

REM Switch to startup dir, unless its not defined
REM If not defined, go to node dir (external editors use this)
IF "%STARTDIR%"=="" D:
IF NOT "%STARTDIR%"=="" CD %STARTDIR%

REM Optionally call emusetup.bat or put that stuff here for global (in NOEMU)
REM Looks in startup dir, then ctrl dir
IF EXIST EMUSETUP.BAT GOTO EMULOCAL
IF EXIST F:\EMUSETUP.BAT GOTO EMUGLOBAL
IF EXIST E:\DOSUTILS\NUL GOTO NOEMU
IF EXIST H:\DOSUTILS\NUL GOTO NOEMU
ECHO ERROR: No emusetup.bat in E:\%STARTDIR% or F, or DOSUTILS is missing
GOTO EXEC

:EMULOCAL
CALL EMUSETUP.BAT
GOTO EXEC

:EMUGLOBAL
CALL F:\EMUSETUP.BAT
GOTO EXEC

:NOEMU
@set PATH=%PATH%;E:\dosutils;H:\dosutils;H:\dosutils\dosemu2
REM fossil driver, such as x00, bnu, or dosemu fossil.com
rem IF "$RUNTYPE" == "FOSSIL" @fossil.com >NUL
rem IF "$RUNTYPE" == "FOSSIL" bnu.com /P1 /L0=11520 >NUL
IF "$RUNTYPE" == "FOSSIL" x00.exe eliminate >NUL
REM share.exe for multinode file locking
@share >NUL

GOTO EXEC

:EXEC
$CMDLINE
REM Operation Overkill II-specific cleanup
if exist oonode.dat del oonode.dat
if exist oonode.dat del oonode.dat
REM $CMDLINE >DEBUG.TXT 2>&1

IF NOT "%1" == "TEST" exitemu
```

and dosemu.conf
```
$_cpu = "80586"
$_cpu_emu = "fullsim"
$_floppy_a = ""
$_cdrom = ""
$_xms = (8192)
$_ems = (2048)
$_ems_frame = (0xe000)
$_external_char_set = "cp437"
$_internal_char_set = "cp437"
$_term_updfreq = (8)
$_layout = "us"
$_rawkeyboard = (auto)
$_mouse_internal = (on)
$_mouse_dev = ""
$_joy_device = ""
$_lpt1 = ""
$_lp2 = ""
$_speaker = ""
$_sound = (off)
$_sb_dsp = ""
$_hdimage = "+0 -2 /sbbs/ctrl /sbbs/data /sbbs/exec +1"
$_rdtsc = (on)
$_cpuspeed = (0)
$_hogthreshold = (5)
$_com1 = "virtual"
$_lredir_paths = "/sbbs "
$_unix_exec = "/sbbs/exec/sexyz"
```
[dosemu_boot.log.zip](https://github.com/user-attachments/files/16261585/dosemu_boot.log.zip)

**Comment by stsp** [comment]
So does `-no-priv-sep` still fixes the problem?

**Comment by nelgin** [comment]
Unfortunately not. It's in there on the command line.

**Comment by nelgin** [comment]
Well it did...and now it doesn't. I've done a few updates of the OS which includes dosemu2 so I'm not sure exactly when it broke, because there's no indication that is has unless you actually run the game via the BBS.

**Comment by stsp** [comment]
Well it broke at 1666aaf11
obviously because you haven't
tested it. Should be quite simple
to fix though.

**Comment by nelgin** [comment]
Yes, I tend to agree. The previous version I had installed was 2.0~pre9-8764-00f5a4a45+202407052146~ubuntu22.04.1

I'll test the fix out in the morning if there's a ppa ready.

**Comment by stsp** [comment]
Should now work.

**Comment by stsp** [comment]
... without `-no-priv-sep` too, I hope.

**Comment by nelgin** [comment]
No updated ppa available yet, so I'll try a bit later.

Thanks.

**Comment by nelgin** [comment]
Looks like dosemu2 has been stuck "waiting to build" for 6 hours or so according to launchpad.

**Comment by andrewbird** [comment]
I poked it, let's see if the build completes.

**Comment by stsp** [comment]
You can as well do `make flatpak-build`
to build dosemu2 completely with deps
and test the patch.

**Comment by nelgin** [comment]
Thanks Andrew. I installed the package and yes...and no. Most of the doors work. Of the 20 or so I tested, 1 hangs, 2 exit.

When I run 8 Way Slots on the BBS, the screen clears and just hangs, a CTRL-C will actually terminate it and return me to the bbs. If I run in the a dosemu shell, I get "Overflow in module 8WAYS    at address 00C2:262E". I'll attach the debug boot log and the slots directory so you have what I have.

```
Executing cmd-line: /usr/bin/env HOME=/sbbs/ctrl  /usr/bin/dosemu -quiet -dumb -d /sbbs/node1/ -d /sbbs/xtrn -d /sbbs/ctrl/ -d /sbbs/data/ -d /sbbs/exec/ -d /sbbs/xtrn -f/sbbs/ctrl/dosemu.conf -ED:external.bat -o/sbbs/node1/dosemu_boot.log -D+a
```

[dosemu_boot.log.zip](https://github.com/user-attachments/files/16273356/dosemu_boot.log.zip)
[slots.zip](https://github.com/user-attachments/files/16273362/slots.zip)

A few fellow systems ask why they should use dosemu2 when dosemu1 is working perfectly fine for them. Unfortunately, with these recent breakages, I don't have a good argument for it any more. I used to be able to say "it just works". :(

**Comment by stsp** [comment]
So `-no-priv-sep` supposedly doesn't help?
You logs do not even mention `8WAYS.EXE`,
but instead they have things like
`MFS: find file /home/bbs/sbbs/ctrl/.dosemu/drive_c/e:512`
which is entirely ridiculous and means a
config mess-up. And since you are not
goign to clean up your configs, please
spare us from the lengthy words about
your friends asking about using dosemu1
and so on. You are free to use whatever
dosemu works for you, and until you stop
messing with the configs, your problems
won't be replicated.

**Comment by stsp** [comment]
OK, no, spoke too soon.
`e:512` indeed happens with -E so
looking...

**Comment by stsp** [comment]
`e:512` weirdness in a log is now
fixed, but it wasn't a regression, and
didn't do any harm.
Also except the aforementioned
1666aaf1 there was nothing else that
could regress bbs.
So either that commit is still not
entirely fixed, of `-no-priv-sep` should
fix the problem as before?

**Comment by stsp** [comment]
> a CTRL-C will actually terminate it and return me to the bbs.

This seems to be the case since 6515b0e8f
which is over a year ago. Are you sure its a
regression?

**Comment by stsp** [comment]
> When I run 8 Way Slots on the BBS, the screen clears and just hangs, a CTRL-C will actually terminate it and
> return me to the bbs. If I run in the a dosemu shell, I get "Overflow in module 8WAYS at address 00C2:262E".
> I'll attach the debug boot log and the slots directory so you have what I have.

Checked with dosemu2, dosemu1 and
dosbox. All consistently show the same
overflow msg:
![image](https://github.com/user-attachments/assets/31090a39-4830-4e14-839e-a2031b950f7f)

**Comment by stsp** [comment]
Arrgh, since when screen-shots stopped
adding window decorations? The above
screen-shot is from dosbox-staging, even
if this fact is unfortunately not so visible. :)

**Comment by nelgin** [comment]
It used to work, I know it did otherwise I wouldn't have had it installed. Someone played it on Jul 20 2023. Oh yeah, it was me...

![image](https://github.com/user-attachments/assets/0379a296-ab21-4242-8150-71f417f91f86)

**Comment by stsp** [comment]
> It used to work, I know it did otherwise I wouldn't have had it installed. Someone played it on Jul 20 2023.
> Oh yeah, it was me...

Its not for the first time when you
provide bad things. A year or 2 ago
I've got similarly non-working thing
from you, and after wasting hours,
have found that some .bat file is needed
to run, to get rid of an error.

Same here: I don't know what worked for
you and when, but what you attached
here, doesn't work on any emulator. If
there is again a magic bat file somewhere
to run, this time I won't deduce it myself.
When you find out how to get it to work
on dosbox-staging, maybe there will be
some conclusion about dosemu2.

**Comment by nelgin** [comment]
Not wasting any time on it is a good thing. In future I will do more due diligence before reporting such issues. This one is resolved, at least.
