### ISSUE TITLE
Does DOSMEMU2 work in a VM?

### ISSUE THREAD

**Issue by martykazmaier** [dosemu2/dosemu2#2243]
I'm needing to run Dosemu2 for a BBS for DOS doors.  The thing is, I don't have bare metal, only VMs.  Will this work?  I don't have the ability to use a stand along system for this project.

**Comment by stsp** [comment]
Yes, of course it does.
It works under qemu, and for any
VM it doesn't work, you need to report
the bug to VM authors, not here.

**Comment by stsp** [comment]
I've seen your vmware posting, but
your problem has nothing to do with
vmware. dosemu2 runs perfectly fine,
it says `Welcome to dosemu2!`, which
is seen from your log.

Just stop using `-X` and `-s` switches.

**Comment by martykazmaier** [comment]
It starts, but the command prompt is never shown.  I've tried without -X and -s with the same results and am pretty sure that I didn't use them last time, I may have included the wrong log, but it shows the same result. On Jul 22, 2024 6:44 AM, Stas Sergeev ***@***.***> wrote:
I've seen your vmware posting, but
your problem has nothing to do with
vmware. dosemu2 runs perfectly fine,
it says Welcome to dosemu2!, which
is seen from your log.
Just stop using -X and -s switches.

**Comment by martykazmaier** [comment]
Sorry,  it's really hard to copy the log to my apache system from Ubuntu.On Jul 22, 2024 10:04 AM, Marty Kazmaier ***@***.***> wrote:It starts, but the command prompt is never shown.  I've tried without -X and -s with the same results and am pretty sure that I didn't use them last time, I may have included the wrong log, but it shows the same result. On Jul 22, 2024 6:44 AM, Stas Sergeev ***@***.***> wrote:
I've seen your vmware posting, but
your problem has nothing to do with
vmware. dosemu2 runs perfectly fine,
it says Welcome to dosemu2!, which
is seen from your log.
Just stop using -X and -s switches.

**Comment by stsp** [comment]
Please show the output of:
`echo $TERM`
`echo $DISPLAY`
`echo $WAYLAND_DISPLAY`
`echo $XDG_SESSION_TYPE`

**Comment by martykazmaier** [comment]
***@***.***:~$ echo $TERM
xterm-256color
***@***.***:~$ echo $DISPLAY
:0
***@***.***:~$ echo $WAYLAND_DISPLAY
wayland-0
***@***.***:~$ echo $XDG_SESSION_TYPE
wayland

I hope this helps some...


________________________________

**Comment by stsp** [comment]
I think you added nansi.sys (or similar).
Remove that and you'll get the prompt.

**Comment by martykazmaier** [comment]
Dosemurc shows the following:

$_cpu = "80486"
$_cpu_emu = "vm86"
$_hogthreshold = (10)
$_external_char_set = "cp437"
$_internal_char_set = "cp437"
$_layout = "us"
$_rawkeyboard = (0)
$_joy_device = ""
$_speaker = ""
$_sound = (off)
$_com1 = "virtual"

~/.dosemu/drive_c/userhook.sys has the following:
device=c:\x00\x00.sys E

That is required as a fossil driver for the dos doors that I'll be running, and others have working with no issues.  I don't have any *ansi.sys loading.

________________________________

**Comment by stsp** [comment]
`$_com1 = "virtual"` is a problem.
Remove it and dosemu2 will run in your VM.

**Comment by martykazmaier** [comment]
Ok, I created a .dosemurc_nocom like I hadn't and the tutorial suggested with the $_com1 removed.  It's working now.  I'll need that when a modem connection is detected, which it will be when the bbs is running.  Thanks, I hadn't looked at that.

Now:  dosemu -f ~/.dosemu/.dosemurc_nocom works great.

________________________________
