### ISSUE TITLE
freecom build failing

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2246]
https://github.com/dosemu2/dosemu2/actions/runs/10117294658/job/27981952888
Looks like an upstream change,
Andrew can you look?
Maybe get freecom from some tagged
version?

**Comment by andrewbird** [comment]
It seems that Freecom hasn't changed for two weeks and it builds successfully under MS-DOS 6.22 so I doubt that's the problem. Did you try rerunning the job as it looks similar to the random file access problem we sometimes see with the pcmos buiid?

**Comment by stsp** [comment]
Yes, that appears true.
I wonder what actually happens.
`make` calls `command /c ..\scripts\rmfiles watcomc.cfg`
and command.com reports
`No such file or directory` which `make`
then prints? I am not sure actually because
the message is:
`Error(E14): Cannot execute (..\scripts\rmfiles): No such file or directory`
which suggests `make` itself could check
the path. Although there is actually no
`..\scripts\rmfiles` but rather `..\scripts\rmfiles.bat`.

Would it be possible to add the test
that makes this `watcomc.cfg` in a loop?
Maybe that will allow to trigger the bug
more easily.

**Comment by stsp** [comment]
It seems to be doing exec of
`rmfiles.com`, then `rmfiles.exe`.
Then does QualifyFilename `rmfiles.bat`,
and if that fails (as it always does), then
findfirst of `rmfiles.bat`. If found - runs
`command /c`, otherwise tries the PATH
search and eventually prints this error.
Presumably `findfirst` failed...
Alternatively, maybe after QualifyFilename
failure, fdpp's truename() did something
wrong, so `findfirst` was fed with bad path.
I guess we need to have -D9+Dd logging
for this and pcmos tests. Then it would be
easier to see what have failed.

**Comment by stsp** [comment]
Found the problem:
`COMSPEC=E:\COMMAND.COM\COMMAND.COM`
Andrew, could you please add the
`COMSPEC` validation to the initial
boot test? This will allow to reproduce
the bug very quickly.

**Comment by stsp** [comment]
Now comcom64 CI is failing:
https://github.com/dosemu2/comcom64/actions/runs/10143574695/job/28047226952
I suspect its some out-of-sync packages
because dosemu2's CI passes.
But the problem is, comcom64's CI
doesn't upload any logs.
Can you take a look at why its so?

**Comment by andrewbird** [comment]
From what I can see the test is only that Dosemu starts and comcom64 responds to `ver`. Perhaps I should see if I can generate a cut down version of dosemu's test suite that only includes tests that exercise comcom.

**Comment by stsp** [comment]
Problem solved by updating dosemu2
on PPA. But the log would be good,
nevertheless. Who knows when it fails
again.
