### ISSUE TITLE
ipx interop with dosbox

### ISSUE THREAD

**Issue by stefand** [dosemu2/dosemu2#2254]
dosemu2 has IPX support that hooks up to Linux's IPX stack. This presumably allows talking to other IPX machines (dos / win <= xp / novell) on the same network. dosbox on the other hand has an IPX implementation that encapsulates IPX packets in UDP packets. This is easy to set up for dos network games because it doesn't need a native IPX stack (it is dead since Windows Vista) and does not need root.

Now the feature request is this: Please consider implementing the same IPX over UDP protocol so games running in dosemu2 can talk to games running in dosbox.

User-facing documentation of dosbox's ipxnet can be found here: https://www.dosbox.com/wiki/Connectivity#IPX_emulation . Some standalone ipxnet servers that may be helpful for understanding and testing the protocol are found at the bottom of this page.

Semi-relatedly, the dosbox fork dosbox-x seems to have means to talk to real dos machines on the network: https://dosbox-x.com/wiki/Guide%3ASetting-up-networking-in-DOSBox‐X . From the looks of it it uses libpcap and cap_net_raw, but is comparably difficult to use if everyone is running the game in an emulator - it needs extra software on Windows and extra permissions on Linux.

**Comment by stsp** [comment]
Yes, given that we already have an
IPX driver, just adding the different
link layer looks doable.
Maybe one day. :)

> Semi-relatedly, the dosbox fork dosbox-x seems to have means to talk to real dos machines on the network:

We can do that already if you set up
the TAP device. Hmm, and in fact...
Since we can do that, then maybe
the relay stuff can be done completely
on a host machine? Which means you
don't even need to wait for it to be
implemented inside dosemu2.

**Comment by stsp** [comment]
So would you like to explore the
possiblity of using TAP device and
tunneling with essentially the linux
tools?
For that you need to disable the
dosemu's IPX driver, and instead
load the lsl/pdether/ipxodi under DOS.

**Comment by stefand** [comment]
I think for a user who's using gaming those aren't too appealing. They need configuration on both the dosemu side and dosbox-x side for e.g. a Windows player (and even dosbox-x is not "standard" dosbox).

In my ideal world dosemu would support the dosbox protocol as seamlessly as possible, e.g. by just typing the same setup commands in dosemu that you'd type in dosbox

"ipxnet startserver 12345" on one machine
"ipxnet connect 192.168.10.2 12345" on the other

and dosemu's ipx driver magically switches from talk-to-linux-ipx mode to dosbox-compatible udp tunnel mode.

**Comment by stefand** [comment]
Oh for some examples of games that use the IPX API for multiplayer: I personally played Screamer 2 that way. Some other examples I found online are Blood and Warcraft 2. https://www.abandonwaredos.com/abandonware-list.php?tp=1&kword=356&theme=LAN has others, although it also lists Win9x games and I haven't verified those entries.

**Comment by stsp** [comment]
No, there is no configuration required, neither
on dosbox nor on dosemu side. dosemu2 gives
you an IPX frames on tap device. You are free
to do whatever you want with them, including
the encapsulation to UDP and sending to a
dosbox server. It may be more convenient to
do the encapsulation directly by dosemu2, but
its not there, so just try the same in a less
convenient way.

**Comment by stsp** [comment]
There is no shortage of IPX games.
I was testing doom and GTA, although
it was something like 20 years ago. :)

**Comment by stsp** [comment]
Wow, @andrewbird are you working on this?
Github shows lots of your commits here.

**Comment by andrewbird** [comment]
No, a false alarm I'm afraid. When I needed to test the new package test I needed to bring my fork's devel branch up to date. Unfortunately Github saw all the #issue numbers embedded in your commits and added references again to the issues. Additionally emails about @mentions were also sent. I wonder if there's any way to silence this, as surely it happens a lot to people.

**Comment by stsp** [comment]
OK, but note that hashes on commits differ.
So maybe you cherry-picked instead of rebasing?

**Comment by andrewbird** [comment]
Just looking though my shell history. I only seem to have the `git pull upstream devel; git push origin -f devel` that I did after the test to 'repair' my origin/devel. I wouldn't have cherry-picked all those commits, as I only wanted to bring mine up to date for a ci test. That said, I might have done something stupid, like to forget that I was on the topic branch and pulled your current devel on top to test, then the hashes would be different. So if that's the case then I probably won't generate all that noise again in the future.

So what are you doing with ipx, are you working on making a Dosbox style ipx over udp backend?

**Comment by stsp** [comment]
Суббота, 21 сентября 2024 г получено от Andrew Bird:
> Just looking though my shell history. I only seem to have the `git pull upstream devel; git push origin -f devel` that I did after the test to 'repair' my origin/devel. I wouldn't have cherry-picked all those commits, as I only wanted to bring mine up to date for a ci test. That said, I might have done something stupid, like to forget that I was on the topic branch and pulled your current devel on top to test, then the hashes would be different. So if that's the case then I probably won't generate all that noise again in the future.

I think pulling alone is not enough
to get hashes different. It should
merge. Maybe you then rebased
without this new --rebase-merges
option? Git broke command-line
compatibility here, so I bet you got
tricked.

 
> So what are you doing with ipx, are you working on making a Dosbox style ipx over udp backend?

Not started it yet. Too many
surgeries this year, so taking a
bit of relax. :)
But that's the idea, so if you want
to add a back-end - no problems.
The back-end code is now cleanly
separated (but untested).

**Comment by stsp** [comment]
Should now work.
`emuipx -c localhost:1024` or like that.
Haven't got any luck with ipxrelay yet,
but with dosbox it operates normally.

@bpranoto could you please check if
IPX still work in your setup?

**Comment by stefand** [comment]
Cheers, I'll give it a try in the next days :-)

**Comment by stsp** [comment]
https://github.com/stsp/ipxrelay
Got it to work with ipxrelay.
