### ISSUE TITLE
unix command hangs

### ISSUE THREAD

**Issue by severach** [dosemu2/dosemu2#2257]
**Describe the bug**
Running `unix` from a DOS prompt hangs.

**To Reproduce**
`unix ls`

**Comment by stsp** [comment]
For me it works.
Anyone?

**Comment by andrewbird** [comment]
I get this
~~~
ajb@calypso:~/Desktop$ dosemu
ERROR: Cannot drop root uid or gid!
ERROR: KVM: KVM_RUN failed: Input/output error

Segmentation fault (Address not mapped to object [0x7e9016c00990])

ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.
~~~
[t1.zip](https://github.com/user-attachments/files/16611220/t1.zip)

Sorry, but I have to go out now, so can't investigate further.

**Comment by stsp** [comment]
```
(No debugging symbols found in /usr/libexec/dosemu2/dosemu2.bin)
(gdb) Attaching to program: /usr/libexec/dosemu2/dosemu2.bin, process 21490
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Inappropriate ioctl for device.
```
Come on!
You are not the novice first-time user here.

**Comment by stsp** [comment]
OTOH I reproduced something similar.
Looking...

**Comment by andrewbird** [comment]
To be honest you were lucky to get what you did, I was just walking out of the door!
With symbols:
~~~
ajb@calypso:~/Desktop$ dosemu
ERROR: Cannot drop root uid or gid!
ERROR: KVM: KVM_RUN failed: Input/output error

Segmentation fault (Address not mapped to object [0x7fc6ed200990])

ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.
~~~
I had to control-C twice in the terminal to kill the Dosemu window. Here's the log 
[t2.zip](https://github.com/user-attachments/files/16617490/t2.zip)

**Comment by stsp** [comment]
Ok, thanks. I didn't know you re-install things
and symbols every time you report a bug. :)
Anyway, I already reproduced the problem and
got ~10 patches, but its still not working. :(

**Comment by andrewbird** [comment]
> Ok, thanks. I didn't know you re-install things
and symbols every time you report a bug. :)

No but I had a new machine and so a fresh install of the OS since last time I reported a bug with the PPA packaged dosemu. On the upside I've now documented how to install the symbol packages in the wiki, so I don't have to go looking through dosemu issues for instructions on how to do it every time.

**Comment by stsp** [comment]
Well but your log still contains no symbols...
Not your fault though. :)
Symbols are broken too.
Will push fixes in a minute.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by severach** [comment]
The hang is gone. A read only command like ls or pwd works. Writing something doesn't.

```
C:\>unix cp /dev/null /tmp
C:\>unix cp /dev/null /home/chris/c
cp: cannot create regular file '/home/chris/c/null': Permission denied
C:\>unix whoami
dosemu2
C:\>unix ls -l /tmp/null
-rw-rw-r-- 1 dosemu2 dosemu2 0 Aug 14 15:37 /tmp/null
C:\>unix ls -ld /home/chris/c
drwxr-xr-x 52 chris users 4096 Aug 14 15:31 /home/chris/c
```

**Comment by stsp** [comment]
Writing works.
You can run `unix cat` and type
letters. On enter, cat will echo them.

**Comment by severach** [comment]
Keyboard writing may work. File writing doesn't. See the log. During `unix` I am user `dosemu2` not user `chris`.

**Comment by stsp** [comment]
File IO is not going to work via unix.com.
Reading still works, but that's a bug.
I'll disable reading too.
If you can access some file with unix.com,
then any DOS prog can.
No one wants the DOS prog to do
`unix rm -rf ~`
or read some secret file with your card
number in plain text. :)

**Comment by severach** [comment]
Don't we have permissions to allow that, which I immediately patch away because I do want that.

Anyways the only two things I need is LFN rename and access to the clipboard. No existing rename or move works for me. Either they don't parse quotes, they don't use the LFN API, or aren't freely distributable. Even if one were found that did all that it still a hassle because Norton Commander and Foxpro strip single and double quotes from command lines.

Rename is available through the LFN API so starting with #1933 I wrote RENAMEL. It's better and simpler than all the path fixes needed for `unix mv` and it accepts [] as quote characters which both Foxpro and Norton Commander let through, eliminating the need for an intermediate bat file.

How can I get clipboard access, like `xsel -bi`?

**Comment by andrewbird** [comment]
If you are up for writing something yourself (and you seem to be) try looking at [int2f 1700](https://fd.lod.bz/rbil/interrup/windows/2f1700.html#4681) which Dosemu now supports to exchange with the desktop clipboard.

**Comment by stsp** [comment]
> Don't we have permissions to allow that, which I immediately patch away because I do want that.

You can use `dosemu -no-priv-sep`.
Also: you are free to patch away anything
you want on your PC. But patching away
security restrictions for all arch-linux users
is a very bad idea.

> Anyways the only two things I need is LFN rename and access to the clipboard. No existing rename or move works for me.
> Either they don't parse quotes, they don't use the LFN API, or aren't freely distributable.

I recently added some quoting support in
comcom64. But I haven't actually tested it
with LFNs.
Why writing stuff yourself or patching away
security restrictions, instead of fixing comcom64,
either by yourself (preferably) or by bug-reporting?

> How can I get clipboard access, like xsel -bi?

https://pushbx.org/ecm/download/old/toclip/
I don't know why it is "old" though.
Maybe @ecm-pushbx can clarify what is new?

**Comment by ecm-pushbx** [comment]
> > How can I get clipboard access, like xsel -bi?
> 
> https://pushbx.org/ecm/download/old/toclip/ I don't know why it is "old" though. Maybe @ecm-pushbx can clarify what is new?

The "old" in this path just means that besides the most recent build this also contains older builds. Most recent build is always at https://pushbx.org/ecm/download/toclip.zip as well. And the source is in the repo at https://hg.pushbx.org/ecm/toclip

**Comment by severach** [comment]
The privilege patch (see #2065) is a private patch so only I get it. I'm taking it out since I don't need to call unix any more. LFN rename is fixed by RENAMEL and I leave the `xsel.sh` script so I can manually run it from a bash window.

I checked comcom and FreeCOM. Both handle quotes properly. The problem is Foxpro that strips quotes from command lines. It's not just a one off. Norton Commander does it too so apparently it was a standard. Foxpro `!move "A B" "C D"` is stripped to `move A B C D`. Quotes are gone before either COMMAND or MOVE have a chance to parse them. A command processor does parse the lines to find the "<>|" pipe redirects so having MOVE parse quotes differently doesn't do much good. Adding Foxpro's lesser known string type "[]" was the solution to avoid an intermediate bat file. They are not valid DOS SFN characters and are completely ignored by command processors and clib argv parsers. I just grab the original command line from PSP:0x80 0x81 and parse it with more bash like rules.

toclip isn't working. It seems internally consistent. Anything I put in `toclip -c` I can get back out with `toclip -p`. Nothing goes in or out of the Cinnamon clipboard or middle click copy paste.

I'll need to add some code to toclip because I can't work with a 58K limit. The INT 2F 1703h API allows any amount of data to be put to the clipboard without far pointers or DPMI but due to a MS mistake, getting from the clipboard is limited. The entire clipboard must fit in your buffer or you can't get anything. Adding a seek position to INT 2F 1704h and having INT 2F 1705h allow multiple calls with registers for buffer size and amount returned could have worked but they didn't do that. Looks like a full toclip can put any size in real mode and get small sizes in real mode, switching to DPMI if the size is too large for the largest farcoreleft(). I only need large put, not large get, so real mode is fine for me.

The good news is that toclip + DOSEMU will paste better than xsel. xsel must "TSR" in DOS lingo to provide the clipboard contents and it often terminates early during a large paste providing only partial data, and even less on a second paste. DOSEMU remains running and can reliably serve the entire clipboard many times.

dosemu2/comcom64#101

**Comment by stsp** [comment]
I think the different syntax is to escape
spaces, so perhaps this should work too:
`copy A\ B C\ D`. If it doesn't, we may consider
fixes.

Please see this page about clipboard:
https://github.com/dosemu2/dosemu2/wiki/Clipboard-usage

**Comment by stsp** [comment]
> Adding a seek position to INT 2F 1704h and having INT 2F 1705h allow multiple calls with registers for buffer
> size and amount returned could have worked but they didn't do that.

Discuss your APIs with @ecm-pushbx and
we can get them. Although dosbox-X has some
`CLIP$` device IIRC, so maybe that approach
suits better for your needs?

**Comment by severach** [comment]
Might as well add toclip to the wiki page.

\ is the path character so it can't be used for escaping. Your copy command thinks A and C are dirs, B and  D are files. That could work for me and RENAMEL as I could add the ability to convert / to \ to allow for \ as an escape or even add a different escape character. I'd rather not have RENAMEL stray too far away from existing RENAME and MOVE tools.

Ctrl-Alt-C works. I don't run any insecure programs so I don't know why all this security is needed. Is there a config option that lets me always start in Clipboard Native mode?

I don't think Microsoft had an interest in WINOLDAP Clipboard to file. If it didn't fit into your average DOS editor, it doesn't matter.

We can't change int 2F 1704h or 1705h. It would have been nice to have the seek in 1705h but there just aren't enough registers for it. We'd need to add new 17xx calls. We could change 1704 and 1705 if there was another API call to enable DOSEMU WinOldAPP extended API mode. That would require updating RBIL. Best to just create a new API GET CLIPBOARD. It could be done in a single 1705h replacement if one of the registers had a multiplier.

```
https://fd.lod.bz/rbil/interrup/windows/2f1705.html#4686
INT 2F - MS Windows "WINOLDAP" - GET CLIPBOARD DATA
	AX = 1705h
	DX = clipboard format supported by WinOldAp
	ES:BX -> buffer
Return: AX = status
	    nonzero success
	    0000h   error, or no data in this format in Clipboard

We could add a new 17xxh, same as 1705h but with:

SI:CX = size of buffer (in)
SI:CX = size of data written to buffer (out)
DS:DI = seek position (abusing DS like this seems like not a good idea)
DI = seek position*64 (seeking to 4GB ought to be enough for anybody)
```

If the clipboard fits in our buffer we can get the whole thing. Otherwise we get it in multiple of 64 blocks until SI:CX returns zero or less than what was requested.

If they had any sense, all those sizes would have been *64 and would only take a single register.

**Comment by ecm-pushbx** [comment]
> 
> We could add a new 17xxh, same as 1705h but with:
> 
> SI:CX = size of buffer (in)
> SI:CX = size of data written to buffer (out)
> DS:DI = seek position (abusing DS like this seems like not a good idea)
> DI = seek position*64 (seeking to 4GB ought to be enough for anybody)
> ```
> 
> If the clipboard fits in our buffer we can get the whole thing. Otherwise we get it in multiple of 64 blocks until SI:CX returns zero or less than what was requested.
> 
> If they had any sense, all those sizes would have been *64 and would only take a single register.

Do you mean 64 KiB as a multiplier? Not sure how you get 4 GiB from 64 times 65536. Anyway, you can pass some of the values in a memory buffer then point `ds:di` or whatever to that buffer. No reason to put everything into registers. (For DPMI use it is nicer to pass the segment value in a non-segreg however.) Passing a buffer is how Enhanced DR-DOS's 64-bit seek function int 21.7142 works as well. dosemu2's mfs knows this function now too.

**Comment by stsp** [comment]
> Might as well add toclip to the wiki page.

I think you can do that too.

> \ is the path character so it can't be used for escaping. Your copy command thinks A and C are dirs, B and D are files.

It would be very strange to rely on that.
DOS doesn't allow to have both the file
and the dir with the same name, so such
indication would be redundant, and I don't
think someone actually expects trailing
slash to identify the dir.

> Ctrl-Alt-C works. I don't run any insecure programs so I don't know why all this security is needed. Is there a
> config option that lets me always start in Clipboard Native mode?

`$_SDL_clip_native`

**Comment by severach** [comment]
You're right. I did 64*65536=4194304 and thought I had 4GB.

**Comment by andrewbird** [comment]
So to avoid inventing new int2f/17xx interrupts what about utilising the 'DX = clipboard format' to define a new format, which in our case is a structure that informs dosemu about our new data requirements?
~~~
INT 2F - MS Windows "WINOLDAP" - SET CLIPBOARD DATA
	AX = 1703h
	DX = clipboard format supported by WinOldAp (see [#02723](https://fd.lod.bz/rbil/interrup/windows/2f1703.html#table-02723))
	ES:BX -> data (see [#02724](https://fd.lod.bz/rbil/interrup/windows/2f1703.html#table-02724),[#02725](https://fd.lod.bz/rbil/interrup/windows/2f1703.html#table-02725))
	SI:CX = size of data
Return: AX = status
	    nonzero data copied into the Clipboard
	    0000h   failure
~~~

From what I can see on the Internet the following CF_XXXX formats are defined
~~~
/*
 * Predefined Clipboard Formats
 */
#define CF_TEXT             1
#define CF_BITMAP           2
#define CF_METAFILEPICT     3
#define CF_SYLK             4
#define CF_DIF              5
#define CF_TIFF             6
#define CF_OEMTEXT          7
#define CF_DIB              8
#define CF_PALETTE          9
#define CF_PENDATA          10
#define CF_RIFF             11
#define CF_WAVE             12
#define CF_UNICODETEXT      13
#define CF_ENHMETAFILE      14
#if(WINVER >= 0x0400)
#define CF_HDROP            15
#define CF_LOCALE           16
#endif /* WINVER >= 0x0400 */
#if(WINVER >= 0x0500)
#define CF_DIBV5            17
#endif /* WINVER >= 0x0500 */

#if(WINVER >= 0x0500)
#define CF_MAX              18
#elif(WINVER >= 0x0400)
#define CF_MAX              17
#else
#define CF_MAX              15
#endif

#define CF_OWNERDISPLAY     0x0080
#define CF_DSPTEXT          0x0081
#define CF_DSPBITMAP        0x0082
#define CF_DSPMETAFILEPICT  0x0083
#define CF_DSPENHMETAFILE   0x008E

/*
 * "Private" formats don't get GlobalFree()'d
 */
#define CF_PRIVATEFIRST     0x0200
#define CF_PRIVATELAST      0x02FF

/*
 * "GDIOBJ" formats do get DeleteObject()'d
 */
#define CF_GDIOBJFIRST      0x0300
#define CF_GDIOBJLAST       0x03FF

~~~

Perhaps we could choose something outside of this range say 0x6885 ('DU') as the format then pass a structure that defines where and how much we really want to pass. So for example:
```c
char far *p;

struct {
     WORD version;  // in case we need to change the structure
     WORD subtype; // something indicative of what we are transferring (0 for unknown / binary)
     void far *data;
     DWORD size; // bytes
} s;
#define DU_VERSION 0x1

#define OURDATASIZE 0x10000 
p = fmalloc(OURDATASIZE);
/* do something with p */
s.version = DU_VERSION;
s.subtype = 0;
s.data = p;
s.size = OURDATASIZE;

AX = 0x1703;
DX = 0x6885; // DU
ES = FP_SEG(s);
BX = FP_OFF(s);
SI = 0;
CX = sizeof(s);

int2f();
```

**Comment by ecm-pushbx** [comment]
0x6885 is "UD" in NASM as a word operand, or when written to memory as a little-endian word. Only [in MASM](https://pushbx.org/ecm/dokuwiki/blog/pushbx/2024/0812_early_august_work#two-byte_text_literals) would it be "DU".

**Comment by stsp** [comment]
I didn't follow closely, so what problem
are we solving? 1704 can return any
size. Buffer in real mode can exceed
64K, if need be. What doesn't work?

Вторник, 27 августа 2024 г получено от Andrew Bird:

**Comment by stsp** [comment]
Although yes, 1704 sucks: what if someone
changed the clipboard content after 1704 call?
So I would understand if someone wishes to
avoid 1704 all together.
So what if we have the new call to write the
content of a clipboard to an fd?

**Comment by andrewbird** [comment]
> 0x6885 is "UD" in NASM as a word operand, or when written to memory as a little-endian word. Only [in MASM](https://pushbx.org/ecm/dokuwiki/blog/pushbx/2024/0812_early_august_work#two-byte_text_literals) would it be "DU".

Yep not enough thought on my part went into that!



> What doesn't work?

Not sure, really.

> Although yes, 1704 sucks: what if someone
changed the clipboard content after 1704 call?

Indeed. I think when I originally played with this I had the clipboard contents copied into a temporary buffer on 1704, then 1705 returned that, not the current clipboard contents. Not sure if that ever made it into published patches.

> So what if we have the new call to write the
content of a clipboard to an fd?

Fine by me, I'll leave it to others to decide what fits best.

**Comment by severach** [comment]
Clip programs need a way to detect if DOSEMU is running to use or not use the extra functionality. We'd need to define extra constants for every clipboard format a caller might want. I only want text but that doesn't mean everyone else only wants text. We could use the custom clipboard format as a trigger to enable the extended API. Incompatible hosts would return INVALID CLIPBOARD FORMAT. DOSEMU would return success and we know that DOSEMU or compatible is the clipboard host and the extended API is enabled.

Get 1705 only returns the entire buffer. In real mode small we can have a 58K buffer. In real mode large or with far pointers we can have maybe a 400K if the program you're shelling from has left that much. Need DPMI mode to get clipboards larger than that, if there is any memory left. If Size 1704 exceeds your largest buffer size, you don't get anything. The way the WinAPI usually handles this is you call FooGet() with a zero length buffer to get the length. Then you call FooGet() with a non zero length buffer to get the data. DOS would call 1705 over and over to get the data. 1704 is barely needed.  The clipboard host could reset the seek value on 1701 or 1704 and remember it for each successive 1705 call. Win32 has large buffers so usually doesn't do this. Making the seek implicit makes the new 1705 call fit in registers without a memory buffer.

Between Clipboard Open and Close, the clipboard host cant change the size between 1704 and 1705, even if the system clipboard changes, unless it is intentionally changed by the caller with Empty 1702 or Set 1703. The temporary buffer should be made on Open 1701 and persist until Close 1708 to keep all calls consistent. No data is sent to system clipboard until 1708. DOSEMU should send a 1708 if the program crashes with the clipboard open.

Then there's 1709 Compact. What's that for? Maybe if our max buffer size is only 400K, we can compact to 400K and maybe get some of it? Do any clip programs use this?

**Comment by stsp** [comment]
> Not sure if that ever made it into published patches.

I think we can circumvent that problem by
returning an error in this case (or an empty data),
forcing the caller to retry the 1704 round-trip.
And adding some bit to DX to indicate that we
passed len, also looks reasonable.

**Comment by stsp** [comment]
> Between Clipboard Open and Close, the clipboard host cant change the size between 1704 and 1705

Good point.
That's what we obviously forgot to do.
Ok, this all started to make sense for me now.
So I suppose you don't really need the seek
functionality, in/out len should be enough? In
which case you are not out of registers.

**Comment by stsp** [comment]
> SI:CX = size of buffer (in)
> SI:CX = size of data written to buffer (out)
> DS:DI = seek position (abusing DS like this seems like not a good idea)
> DI = seek position*64 (seeking to 4GB ought to be enough for anybody)

So I propose DI to have some magic
value, that indicates SI:CX have size.
To test the functionality, that very same
magic value should be returned by 1704
in DI.

**Comment by severach** [comment]
I memset all my REGS ensuring that unused registers are all zero. I'm not trying to fuzz. I want the call to work. Noone else does this so unused registers come with all sorts of random stack values.

That's why I suggested the custom clipboard format to enable the API. 1704 doesn't change anything so put it there.

Only having an in and out length is enough to get however much fits into my buffer. The seek is needed to get the whole thing within the crushing buffer limits of real mode DOS.

**Comment by stsp** [comment]
But 1704 is not documented to return
an error on an unsupported format.

**Comment by stsp** [comment]
> Only having an in and out length is enough to get however much fits into my buffer.

No one prevents you from doing multiple
calls. Obviously with the size passed, only
that size should be removed from the buffer.

**Comment by severach** [comment]
>To test the functionality, that very same
>magic value should be returned by 1704
>in DI.

The clipboard program needs a way to know that DOSEMU is running and DI contains a magic value, and fail back to the old way.

Would you provide a random value in 1704,DI which is to be submitted to 1705,DI to enable the extended functionality. Or would the magic value be a published constant which the caller checks DI for, then places in 1705,DI to maintain the extended functionality. Seems like the toclip code would make 1705,DI whatever was already in REGS from 1704,DI, unintentionally enabling the extended API. You'd need to ask the caller to mangle the DI bits in some standard way like bit invert to prevent this.

**Comment by stsp** [comment]
Yes, that's right.
Bit invert is fine with me.

> Or would the magic value be a published constant which the caller checks DI for

Of course.
Checks, inverts, passes.

**Comment by stsp** [comment]
Added open/close ops.
Please test.

**Comment by stsp** [comment]
@ecm-pushbx are you OK with the
DI magic value proposal?

**Comment by ecm-pushbx** [comment]
I'm not sure I understand, you want to add a magic signature to [int 2Fh function 1704h](https://fd.lod.bz/rbil/interrup/windows/2f1704.html#4685)? This is not documented as returning anything or changing `di` so I'm against that. Why not add a new function like 170Bh or 17C0h?

**Comment by stsp** [comment]
> I'm not sure I understand, you want to add a magic signature to

Yes, so that we can check if the extension is supported.

> This is not documented as returning anything or changing di so I'm against that.

But its not like its saying "all other regs
preserved". And RBIL actually says that
when there is a need. So I really don't
expect anyone to depend on it being
preserved, or?

> Why not add a new function like 170Bh or 17C0h?

Because not passing len to 7105 is crazy.
I now agree with @severach its nothing but
a programming mistake. Note that 7104 can
return the len you can't allocate under real-mode.

**Comment by stsp** [comment]
Be 7104 documented to return word len,
that would be an entirely different story.
But it returns whole 32bit.
W/o passing actual len to 7105 this is already
more broken than the one can ever wish.

**Comment by ecm-pushbx** [comment]
> But its not like its saying "all other regs
> preserved". And RBIL actually says that
> when there is a need. So I really don't
> expect anyone to depend on it being
> preserved, or?

I disagree.

**Comment by stsp** [comment]
> I disagree.

Because you have actually checked its
preserved by win31/95? Or else why?

**Comment by ecm-pushbx** [comment]
I don't think that the Interrupt List notes every preserved register and that you can assume you're free to change one if it isn't listed. It may occasionally list a register being preserved vs being changed, but it isn't as systematic as you claim.

**Comment by stsp** [comment]
My claim is basically that you can't assume
its preserved, unless explicitly stated.
But we can check the reality.
If win31/95 actually preserves it, then there
is a very minor chance someone could depend
on that. But if it doesn't?

**Comment by ecm-pushbx** [comment]
I may get around to trying it in MSW 98SE at a later time. I'm not terribly interested in this, just replied because you mentioned me.

**Comment by stsp** [comment]
Well, you maintain toclip.
Adding anything w/o you approval is futile.

**Comment by stsp** [comment]
Of course eventually we'll fork everything,
and comcom64 will just have a toclip command. :)
But its not there yet.

**Comment by ecm-pushbx** [comment]
> Well, you maintain toclip. Adding anything w/o you approval is futile.

Feel free to fork or "take over" it. I don't have strong feelings on it, and don't generally use it.

**Comment by stsp** [comment]
In any case, if you are REALLY against
this, then whatever you code up in toclip,
we'll have to work with. :)

**Comment by stsp** [comment]
> Feel free to fork or "take over" it.

I am not planning a straight fork.
Just eventually replicate it in comcom64.
But if you add it to freedos, the chances
of such event will reduce, as in that case
I'll just add it to install-freedos.

**Comment by stsp** [comment]
Hmm, but what I SHOULD do is to add it
to msdos.c. Its not there yet.

**Comment by stsp** [comment]
And besides, what is 7109?
http://sinil.in/rbil/2f/1709
Does it solve our problem?

**Comment by stsp** [comment]
Say, if the clipboard data is 200K and
we "compact" it to 64K, what happens?

**Comment by stsp** [comment]
> Hmm, but what I SHOULD do is to add it
> to msdos.c. Its not there yet.

Even this can't be done w/o extension. :(
Our msdos.c uses EMS frame for flip buffers,
which is 64K.
Though I guess we probably can try set the
desired size with 7109. Or is this even worse
than involving DI in 7104/5?

**Comment by severach** [comment]
Even worse, 7109 doesn't accept a DX clipboard type. Say the clipboard has text, html, bitmap, tiff, and a 0x80 blob. What gets compacted? And what is return "DX:AX = number of bytes in largest block of free memory"? Did you even implement 7109 or is it too nonsensical?

>But 1704 is not documented to return
>an error on an unsupported format.

Is WinOldAp in Windows XP? I tried a program to test that and couldn't get int 2F,1700 to work. If 1704 doesn't return an error, it should return zero because, whatever format is being requested, there isn't any? In that case, returning a magic number would indicate that DOSEMU is present and has turned on the extended API.

**Comment by stsp** [comment]
7105 accepts type.
What I had in mind is 7104, 7109, 7105
round-trip.
Please check if 7104 preserves or
destroys DI on various windoses.
If it preserves, someone could
potentially depend on that (which
is very unlikely)

Вторник, 27 августа 2024 г получено от Chris Severance:

**Comment by stsp** [comment]
So I mean something like this logic:
- call 7104
- try to alloc as much
- if you couldn't alloc as much, call 7109 to inform about that
- call 7105

Whether or not it is better than the DI magic,
is what I am not certain. It just makes it look
like we added no extensions.

**Comment by ecm-pushbx** [comment]
I checked on my MSW 98SE install (physical 686 machine). Copying some text from notepad, then opening the clipboard with 2F.1701 and querying with 2F.1704.dx=0001 does preserve DI. It seems not to change any registers other than DX:AX.

**Comment by stsp** [comment]
The alternative possibility can be to
provide some magic value to 1705,
and if it understands, it inverts that
value, otherwise preserves.

**Comment by stsp** [comment]
Nope, bad idea.
It seems, querying for the extension
is best at 1701 time:
http://sinil.in/rbil/2f/1701
```
Return:
AX = status
nonzero success 
```
Obviously here we CAN use the
magic value, as its certainly going
to be non-zero. And it should then
be provided to 1705 in DI.

**Comment by stsp** [comment]
I ended up adding a very simple extension
that only supports up to 64K sizes. Otherwise
I'd have problems with msdos.c. With that,
its now added to msdos.c as well.
Please test.

**Comment by stsp** [comment]
Added a `clip` command to comcom64.
For now it only prints the clipboard content
and exits.
@severach would you like to add the rest
of the functionality you need? Should be
quite trivial.

**Comment by severach** [comment]
I have "a\nb\nc\n" in my clipboard. For the unbuffered test with a large buffer size I receive the whole thing AX=7 including an extra \0.

For the buffered test my buffersize CX=3. My first call to 1705 returns AX=3 "a\n\0". My second call to 1705 returns AX=0. I'm expecting AX=3 "b\n\0". I didn't see any seek reset code in 1704 1701, or seek+= code in 1705 so I didn't expect this to work yet.

For non D2 mode I call open 1701 , get size 1704, and get 1705. For D2 mode I don't bother with 1704. I call 1701 and 1705 over and over until AX==0.

**Comment by stsp** [comment]
Should now work.

**Comment by severach** [comment]
Calling 1705 multiple times works well.

For fun I 1703 setclipboard with the compiled executable `toclip.exe`. setclipboard code skips all \0. This shows a problem with code pages. I setclipboard then 1705 getclipboard. The getclipboard text terminates early near a high ASCII 0x80-0xFF, probably an invalid UTF-8. The clipboard pastes complete into a Linux GUI text editor.

If I convert all \0 and high ASCII characters to space during setclipboard, getclipboard is complete though mostly spaces.

If I load TOCLIP.EXE in a Linux GUI editor and copy, the full text comes through getclipboard. Null bytes are converted to 2 characters slash zero. Most of it is "?" for untranslatable characters.
***
```
static int gentest(void) {
  FILE *fo=fopen("testfile.txt","wb");
  if (fo) {
    int i;
    for(i=1; i<=255; i++) {
      fputc((i==10 || i==13)?' ':i,fo);
      if ((i+1)%16==0) fputc(10,fo);
    }
    fclose(fo);
  }
  return(fo?0:1);
}
```

I made a test file with all ASCII values. DOSEMU I setclipboard, getclipboard. getclipboard is complete and exact. Paste into Linux GUI editor translates perfectly. GUI copy and getclipboard is complete and exact.

Windows 98 works less well with cp437. I setclipboard, getclipboard data is the same. I paste into Notepad and every character translates to something. Some translate exact. Other translate to line block characters (+-|).

Seems that TOCLIP.EXE is being detected as UTF8 and ASCII 1-255 test file is being detected as cp437.

**Comment by stsp** [comment]
Good to know.
If you need to pass binary formats
in windows, you can probably use
the appropriate format in DX, but
dosemu2 doesn't support any.
Now you may want to work on a
clip command of comcom64, which
currently only dumps the clipboard
to stdout.

Понедельник, 2 сентября 2024 г получено от Chris Severance:
