### ISSUE TITLE
Documentation for configuration syntax

### ISSUE THREAD

**Issue by everythingiscode** [dosemu2/dosemu2#2268]
I have been struggling to make some sense about how to use more advanced configurations. Generally there is no good and up to date documentation about how configuration in dosemurc (which uses $_xxx syntax) corresponds to values that could be set via `-I` command line parameter.
Also I struggle to understand what actually can be configured in terms what are all the configuration parameters.  dosemu2 source code contains parser.y file, but I am not exactly an expert in reading flex or yacc notation (whatever it is) and again none of that seems to be documented.
My main goal is to come up with a set of config options, idally using `-I` command line to set environment variables, so dosemu can recognize them and list when invoking SET from the dos.
It seems parser.y has references to setenv but would be nice to know how can that be leveraged. 
Help would be appreciated.

**Comment by andrewbird** [comment]
If you look at `/etc/dosemu/dosemu.conf` you'll find some description of the options available to put in your `~/.dosemu/dosemurc`. I don't really know much about `-I` options, perhaps someone else can help there.

**Comment by everythingiscode** [comment]
@andrewbird i am aware of the file, however what I lack is the information on:
1. what are all the possible configuration options considering what is available in `parser.y`
2. what is the syntax for `-I` and generally what inline configuration is supported.
3. is there a way to configure DOS environment variables form the command line?

**Comment by stsp** [comment]
> what are all the possible configuration options considering what is available in parser.y

As Andrew already pointed - those that
are in dosemu.conf. Sure you can dig more
from the parser, but they can be removed,
and are never documented.

> what is the syntax for -I and generally what inline configuration is supported.

None documented.
You can see `man dosemu.bin` for
a list of documented options.

> is there a way to configure DOS environment variables form the command line?

`dosemu VAR=val`

**Comment by sillyc0n** [comment]
dosemu `VAR=val` is exactly what i need!

thank you.
