### ISSUE TITLE
dj64init_once failed

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#2276]
**Describe the bug**
dosemu2 runs into `dj64init_once failed` and stops when I try to start it

It would seem good if the error message would be clearer in case something like this goes wrong.

**To Reproduce**
Build the latest on Trisquel 11 and try to run it

**Attach program/game binaries or provide an URL**
n.a.

**Attach the log**
[boot.log](https://github.com/user-attachments/files/17179823/boot.log)

**A regression?**
oui

**dosemu2 origins**
self-built

**Comment by stsp** [comment]
This likely means that something isn't
up-to-date, either dj64dev or dosemu2.

**Comment by jschwartzenberg** [comment]
I rebuilt and reinstalled both, but now I'm running into:
```
dj64: API version mismatch, got 0 want 1
dosemu2.bin: dosobj.c:103: mk_dosobj: Assertion `initialized' failed.

Aborted (Signal sent by tkill() 45932 999)

ERROR: Please update dosemu from git, compile it with debug
info and make a bug report with the content of ~/.dosemu/boot.log at
https://github.com/dosemu2/dosemu2/issues
Please provide any additional info you can, like the test-cases,
URLs and all the rest that fits.

removing stale files:
/run/user/1000/dosemu2/dosemu.dbgin.45932
/run/user/1000/dosemu2/dosemu.dbgout.45932
```

**Comment by stsp** [comment]
This means comcom64 is not up to date.
What are you doing??

**Comment by jschwartzenberg** [comment]
Ah great! Recompiling comcom64 fixed it! Thanks!

I was just building everything, but it seems I lost track of which things depend on what. Both regarding build time & runtime.

**Comment by stsp** [comment]
How is that?
How to produce the "outdated" binaries?

**Comment by jschwartzenberg** [comment]
Compile the latest comcom64 against an outdated dj64. Then Bring dj64 up to date and only compile dosemu2...

**Comment by stsp** [comment]
:)
Oookey.

**Comment by jschwartzenberg** [comment]
Yeah the comcom64 build didn't complain my dj64 was old, but the dosemu2 one did ;)

**Comment by stsp** [comment]
Because for comcom64, the outdated
dj64 is not a problem. It could work, built
with any.
The problem is the version mismatch
between the startup code compiled
into comcom64, and the dj64 runtime
installed on host. You can only solve
that by doing `make static` in comcom64.
In that case all runtime is packed in,
so you may avoid that particular problem.
But there may still be a version mismatch
between the packed runtime and djdev64
libs on host, so they won't be able to
bootstrap it.

**Comment by stsp** [comment]
In fact, I implemented a kind of
dynamic linking to solve that problem.
In that case, both the startup code
and runtime are loaded from host.
But that mode is only available for
dj64dev demos. Its not available for
comcom64 currently. I guess I need
to think about making it available.
That would allow to have comcom64.exe
mostly independent of whatever is
installed on host.

**Comment by jschwartzenberg** [comment]
I see. Traditionally one wouldn't expect such coupling, but with your explanation it makes sense.

I guess I do not fully oversee the advantages of the dj64 library being dynamically loaded by programs such as comcom64 and what other possibilities there will be in the future with this.

**Comment by stsp** [comment]
If I can make the 32bit startup code
to be dynamically loaded, then it will
match the runtime installed on host,
making the better portability. If you
update dj64, 32bit startup will also be
updated.
Currently the 32bit startup is packed
into comcom64 itself.

**Comment by jschwartzenberg** [comment]
Btw. I have no idea whether this is a real issue (seems not):
```
echo "Your make is too old, have 4.3 need 4.4"
Your make is too old, have 4.3 need 4.4
```

**Comment by stsp** [comment]
`make` started to add things it
had to add 30 years ago. It recently
added integer compare operators
and synchronization points for
parallel build. Of course I used those,
but some replacement is also provided
for older versions.
make-4.3 added the `&:` delimiter
to specify multiple files from single
rule - yes, there wasn't a syntax even
for that! Better late than never. :)

**Comment by jschwartzenberg** [comment]
Alright, maybe good to know that Ubuntu 22.04/Trisquel 11 still rely on version 4.3. So the new features can be safely used by 2030 or so ;) ;)

**Comment by stsp** [comment]
By 2030 maybe meson or something
else will grow up.
