### ISSUE TITLE
Add support for Raspberry Pi?

### ISSUE THREAD

**Issue by mcericdos** [dosemu2/dosemu2#2277]
The ARM64 compiles of DOSEMU2 and related for Ubuntu from the PPA seem to be close to installable on Raspberry Pi OS, but a few conflicts remain, according to the log of a user who tried to install it:

```
Depends: libc6 (>= 2.38) but 2.36-9+rpt2+deb12u8 is to be installed
Depends: libreadline8t64 (>= 6.0) but it is not installable
Depends: djdev64 but it is not installable

```
For the latter, one just has to look at the parent directory:
http://ppa.launchpad.net/dosemu2/ppa/ubuntu/pool/main/d/
already contains a djdev64 subdirectory.

So the remaining questions are:

- Could dosemu2 be happy with a slightly older libc6? 
- And would a more widespread (?) libreadline than "8t64 6.0" also be acceptable?

Thanks!

**Comment by stsp** [comment]
The answer is yes to both, but you
miss the fact that our PPA is for ubuntu,
not for RPiOS. This means, I do not
write the versions you see, no, debuild
does. You simply need to build things
yourself.

**Comment by stsp** [comment]
Use `make deb` for simplicity.

**Comment by mcericdos** [comment]
Where can I contact the debuild maintainers? My assumption is that the dosemu2 team itself, also for CI, maintains a build config to make it possible to automatically generate the Debian/Ubuntu packages, so I hoped that it would be feasible to adjust a few requirements to allow the packages to install on Raspberry Pi as well.

I do not think the user who tried to **install** dosemu2 is able to also **build** it on his Raspberry. He had tried to use a screen reader in dosbox and qemu, so trying dosemu2 sounded like an improvement given that it is far more modern than classic dosemu and easier to use than "qemu-system-i386 -nographic -m 16 -k en-us -rtc base=localtime -soundhw sb16,adlib -device cirrus-vga -hda freedos.img -cdrom FD12CD.iso -boot order=d" and having to play with diskimages or DOS networked tools to get files in and out of qemu.

At the moment, qemu nevertheless seems to be an acceptable way to run DOS on the Raspberry, but as you know, that is not very DOS-friendly.

**Comment by stsp** [comment]
> Where can I contact the debuild maintainers?

You can contact `@skitt` here or
elsewhere, but he won't tell you
anything different. If you think
I write these versions, then take
a look into
https://github.com/dosemu2/dosemu2/blob/devel/debian/control
and find them - you can't.
Another thing you can try is to
d/l builds for different ubuntu
versions, and you'll discover the
different versions of deps. Because
debuild writes them out.

You can also try `make flatpak-build` -
that builds dosemu2 with all deps
in 1 go.

**Comment by mcericdos** [comment]
Thanks for the link! The linked blob says depend on libreadline-dev, which sounds less specific than that 8t64 thing? Not sure how it creates the libc6 dependency and defines what the minimum required versions are, though. The git and debhelper lines do state which minimum version to require, the rest probably ends up defining a requirement in the style of "must have the same version of the library which was there while building the deb package" by not specifying a minimum version?

Are there pre-made flatpaks of dosemu2 for arm64 available?

**Comment by stsp** [comment]
> Are there pre-made flatpaks of dosemu2 for arm64 available?

Not quite yet.
But if you make sure they work
on RPi (by doing `make flatpak-build`),
then we may consider adding.
It would also be interesting to
separately test ubuntu-built flatpack
on RPi, but I suppose that is going
to work if RPi-built one works.

**Comment by mcericdos** [comment]
I do not have ARM64 Linux devices, but I could ask around.

**Comment by stsp** [comment]
... or use qemu. :)
This is how I implemented arm64
support into dosemu2, but I used
ubuntu image, not RPiOS.
