### ISSUE TITLE
Possible updater problem

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#2286]
### Discussed in https://github.com/dosemu2/dosemu2/discussions/2285

<div type='discussions-op-text'>

<sup>Originally posted by **WayCon2** October  7, 2024</sup>
Some months ago the dosemu2 updates were not functioning properly and were soon repaired. I believe that is happening again. Here is what I get in terminal: 

(base) wayne@OPlex-7050:~/.dosemu/drive_c$ dosemu
ERROR: MFS: /home/wayne/.dosemu/drive_c/ unaccessible
ERROR: INT21: redirecting C: failed (err = 3)
(base) wayne@OPlex-7050:~/.dosemu/drive_c$

I await any possible response. Thank you,

WayCon2

</div>

**Comment by WayCon2** [comment]
Thank you, stsp. Here's what I did: (base) wayne@OPlex-7050:~$ /home/wayne/Downloads/ci_build.sh
Cloning into 'localfdpp.git'...
remote: Enumerating objects: 2195, done.
remote: Counting objects: 100% (2195/2195), done.
remote: Compressing objects: 100% (1228/1228), done.
Receiving objects: 100% (2195/2195), 1.26 MiB | 1.14 MiB/s, done.
remote: Total 2195 (delta 1671), reused 1311 (delta 915), pack-reused 0 (from 0)
Resolving deltas: 100% (1671/1671), done.
[sudo] password for wayne:         
You are about to add the following PPA:
 More info: https://launchpad.net/~stsp-0/+archive/ubuntu/nasm-segelf
Press Enter to continue or Ctrl+C to cancel

gpg: keybox '/etc/apt/keyrings/6B1BC3F1D8709B5A217DE0455ED4B4F6784FCB26.keyring' created
gpg: key 5ED4B4F6784FCB26: public key "Launchpad PPA for stsp" imported
gpg: Total number processed: 1
gpg:               imported: 1
You are about to add the following PPA:
 More info: https://launchpad.net/~stsp-0/+archive/ubuntu/thunk-gen
Press Enter to continue or Ctrl+C to cancel

gpg: keybox '/etc/apt/keyrings/6B1BC3F1D8709B5A217DE0455ED4B4F6784FCB26.keyring' created
gpg: key 5ED4B4F6784FCB26: public key "Launchpad PPA for stsp" imported
gpg: Total number processed: 1
gpg:               imported: 1
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:4 http://ppa.launchpad.net/dosemu2/ppa/ubuntu noble InRelease
Get:5 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Ign:6 http://packages.linuxmint.com wilma InRelease
Get:3 https://raw.githubusercontent.com/abcd567a/ubuntu24/master ./ InRelease [2,115 B]
Hit:7 https://repo.nordvpn.com/deb/nordvpn/debian stable InRelease
Hit:8 http://packages.linuxmint.com wilma Release
Hit:10 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Get:11 https://ppa.launchpadcontent.net/stsp-0/nasm-segelf/ubuntu noble InRelease [17.8 kB]
Get:12 https://ppa.launchpadcontent.net/stsp-0/thunk-gen/ubuntu noble InRelease [17.8 kB]
Get:13 https://ppa.launchpadcontent.net/stsp-0/nasm-segelf/ubuntu noble/main amd64 Packages [520 B]
Get:14 https://ppa.launchpadcontent.net/stsp-0/nasm-segelf/ubuntu noble/main i386 Packages [520 B]
Get:15 https://ppa.launchpadcontent.net/stsp-0/nasm-segelf/ubuntu noble/main Translation-en [420 B]
Get:16 https://ppa.launchpadcontent.net/stsp-0/thunk-gen/ubuntu noble/main amd64 Packages [496 B]
Get:17 https://ppa.launchpadcontent.net/stsp-0/thunk-gen/ubuntu noble/main Translation-en [328 B]
Fetched 166 kB in 2s (88.0 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
mk-build-deps: You must have equivs installed to use this program.
(base) wayne@OPlex-7050:~$ /home/wayne/Downloads/ci_test.sh
/home/wayne/Downloads/ci_test.sh: line 16: [: missing `]'
python3: can't open file '/home/wayne/test/test_dos.py': [Errno 2] No such file or directory
make: *** test/cpu: No such file or directory.  Stop.

=====================================================
=        Tests run on various flavours of DOS       =
=====================================================
(base) wayne@OPlex-7050:~$ dosemu
ERROR: MFS: /home/wayne/.dosemu/drive_c/ unaccessible
ERROR: INT21: redirecting C: failed (err = 3)

**Comment by WayCon2** [comment]
OK. I installed mk-build-deps, and found a missing space before a bracket.

**Comment by WayCon2** [comment]
Now I see all your comments. Thank you. Have you changed one or more of the bashes, or should I add them myself?

**Comment by WayCon2** [comment]
I downloaded the old files again and the new python file. Run them in any order, I get: 

(base) wayne@OPlex-7050:~$ /home/wayne/Downloads/ci_test.sh
/home/wayne/Downloads/ci_test.sh: line 16: [: missing `]'
mkdir: cannot create directory ‘test-binaries’: File exists
python3: can't open file '/home/wayne/test/test_dos.py': [Errno 2] No such file or directory
make: *** test/cpu: No such file or directory.  Stop.

=====================================================
=        Tests run on various flavours of DOS       =
=====================================================
(base) wayne@OPlex-7050:~$ 

Thank you in any case.

**Comment by WayCon2** [comment]
Hello,I note that you closed #2286. I'm wondering if you are saying that you have said what needs to be said, and that you won't say anything (or not much) more. Is that the case (if this email isn't going too far)?In any case, I thank you for your time,wc

    On Monday, October 7, 2024 at 03:57:40 PM EDT, Stas Sergeev ***@***.***> wrote:  
 
 


Closed #2286 as completed via dbc903e.

**Comment by stsp** [comment]
I waited for the packages to rebuild
on LP. They are now available, please
make sure that everything work.
Thanks for reporting this problem,
it was more than severe (CI passes
but completely unbootable packages,
I'd say its a bullshit).

**Comment by WayCon2** [comment]
Thank you. I'm glad you were able rebuild. I'll go back and try again. Also, do you think at some point I will be able to do a clean reinstall and have my employees update from update manager? Good work (but my wife just came in and it's time to attend to dinner and her). wc

**Comment by WayCon2** [comment]
Thank you, yet again.I was having a little trouble, when update manager showed a new version was available. I updated and everything works. I suppose it's the coward's way out, but it does work, and without special settings. Anyway, I like the program and use it everyday. Good, good work.Sincerely,wc

    On Monday, October 7, 2024 at 06:25:26 PM EDT, Stas Sergeev ***@***.***> wrote:  
 
 


I waited for the packages to rebuild
on LP. They are now available, please
make sure that everything work.
Thanks for reporting this problem,
it was more than severe (CI passes
but completely unbootable packages,
I'd say its a bullshit).

**Comment by stsp** [comment]
Building from sources should also
work if you think its less coward.
Just dont forget to uninstall the
package first, or use `make deb`
to build the package locally.

Вторник, 8 октября 2024 г получено от WayCon2:
>  Thank you, yet again.I was having a little trouble, when update manager showed a new version was available. I updated and everything works. I suppose it's the coward's way out, but it does work, and without special settings. Anyway, I like the program and use it everyday. Good, good work.Sincerely,wc
>

**Comment by WayCon2** [comment]
Hello, Stan,
I thought I'd give you a heads-up that the recent update of dosemu2 has a problem. This is the error message on terminal:

ERROR: /usr/lib/dosemu/libplugin_dj46.so /lib/libdjstub64.20.0.2: version 'DJSTRUB_0.5' not found (required by /lib/dosemu/libplugin_dj46.so)
I felt you should know.
I appreciate your work,
Sincerely,
Wayne Conti


    On Monday, October 7, 2024 at 11:45:19 PM EDT, Stas Sergeev ***@***.***> wrote:  
 
 

Building from sources should also
work if you think its less coward.
Just dont forget to uninstall the
package first, or use `make deb`
to build the package locally.

Вторник, 8 октября 2024 г получено от WayCon2:
> Thank you, yet again.I was having a little trouble, when update manager showed a new version was available. I updated and everything works. I suppose it's the coward's way out, but it does work, and without special settings. Anyway, I like the program and use it everyday. Good, good work.Sincerely,wc
>

**Comment by stsp** [comment]
'DJSTRUB_0.5'? It should be
 'DJSTUB_0.5'

Please do `dpkg-query -s djdev64`
to see if its the latest version or not.

**Comment by stsp** [comment]
Probably fixed now, please check.

**Comment by WayCon2** [comment]
Thank you, Serge,Just got to my email. I'll verify your probabilities, when I'm near that computer.Sincerely,Wayne C.

    On Friday, October 25, 2024 at 06:14:03 AM EDT, Stas Sergeev ***@***.***> wrote:  
 
 


Probably fixed now, please check.
