### ISSUE TITLE
Dosemu2 fails to load

### ISSUE THREAD

**Issue by ashley-dos** [dosemu2/dosemu2#2293]
**Describe the bug**
Dosemu2 fails to load - crashes continually i.e. every time for the several days
[boot.log.txt](https://github.com/user-attachments/files/17518489/boot.log.txt)

**To Reproduce**
Enter command:
/usr/bin/dosemu -d /home/acbeeby -d /home/myname/DOS

**Attach program/game binaries or provide an URL**
'screenshot' of terminal window contents:
[terminal.txt](https://github.com/user-attachments/files/17518808/terminal.txt)

acbeeby@acbeeby-G41M-Combo:~$ /usr/bin/dosemu -d /home/acbeeby -d /home/acbeeby/DOS
ERROR: /usr/lib/dosemu/libplugin_sdl.so: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
ERROR: failed to load sdl plugin
ERROR: /usr/lib/dosemu/libplugin_slirp.so: libslirp.so.0: cannot open shared object file: No such file or directory
ERROR: /usr/lib/dosemu/libplugin_sdl.so: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
ERROR: ladspa: failed to load filter.so
dj64init_once failed
acbeeby@acbeeby-G41M-Combo:~$

**Attach the log**
dosemu/boot.log is attached as boot.log.txt

**A regression?**
this problem didn't exist on earlier versions of dosemu2:
Have used dosemu2 for several years.
Problem started "about" 21st October, 2024

**dosemu2 origins**
PPA

**Additional info**
no customisation. used 'out of the box'

**Comment by stsp** [comment]
Should now work, thanks.
Just forgot to do `git push`. :(
Not sure why you have so many
missing deps. But I suppose this
is intentional?

**Comment by ashley-dos** [comment]
Hi Stas,

Yes; working now. I am very grateful!

Could you explain what are "missing deps" - presumably "missing dependencies"? And presumably in my boot.log? Could I trouble you to point them out (or maybe just one) so that I can look into it please - maybe understand the significance? Does it matter?

 I am surprised that there hasn't been other reports before mine.

Many thanks for sorting this so quickly.

Ashley

**Comment by stsp** [comment]
There were other reports today, for
example this: https://github.com/dosemu2/dosemu2/issues/2286#issuecomment-2436637836
But I am not sure if its the same problem.

@andrewbird can we have the package
test running 2 or 3 times a week? That
seems to be a plague. :(

Missing dependencies are these:
```
ERROR: /usr/lib/dosemu/libplugin_sdl.so: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
ERROR: failed to load sdl plugin
ERROR: /usr/lib/dosemu/libplugin_slirp.so: libslirp.so.0: cannot open shared object file: No such file or directory
ERROR: /usr/lib/dosemu/libplugin_sdl.so: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory
ERROR: ladspa: failed to load filter.so
```
You probably have these packages not
installed.

**Comment by ashley-dos** [comment]
Hello,

I'm not sure if replying to the email below will get to the right person?

I have discovered today that dosemu loads, and will execute .bat files; but
it will not execute .exe files e.g. *program*.exe (I get the message
"Error: unable to execute *program*.exe"

Any ideas please?

Thanks,

Ashley Beeby

**Comment by stsp** [comment]
Sorry about this.
I am building the fix already.
Update in a few hours.

**Comment by ashley-dos** [comment]
Stas,

thank you for the fix!

Ashley
