### ISSUE TITLE
`./configure` and `./default-configure` scripts complain about `searpc` not being found, even though I just installed it

### ISSUE THREAD

**Issue by volkertb** [dosemu2/dosemu2#2295]
**Describe the bug**
See title. Basically, the configure script (both the default one and the regular one) complain about `searpc` (or `libsearpc`) missing, so I go ahead and compile and install `searpc`, after which the `dosemu2` configure script continues to complain about it missing.

**To Reproduce**

First, get and build the latest version of the `dosemu2` sources:

```shell
cd /tmp
git clone https://github.com/dosemu2/dosemu2.git
cd dosemu2
./autogen.sh
./default-configure
```

The command `./configure` also fails with the same error.

Then, get and install `libsearpc`, following the instructions of that project's [INSTALL](https://github.com/haiwen/libsearpc/blob/master/INSTALL) file:

```shell
cd /tmp
git clone https://github.com/haiwen/libsearpc.git
cd libsearpc
./autogen.sh
./configure
make
sudo make install
```

Then retry building dosemu2:

```shell
cd /tmp/dosemu2
./autogen.sh
./default-configure
```

It still can't find (lib)searpc.

And again, it also fails when I try the regular `configure` script, instead of `default-configure`:

```shell
cd /tmp/dosemu2
./autogen.sh
./configure
```

**Attach program/game binaries or provide an URL**
N/A

**Attach the log**
Instead of a runtime log, here is the last part of the console output of the `./default-configure` command:

```text
[..]
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB2... yes
checking for SEARPC... no
configure: error: libsearpc-devel not found
Configuration for searpc failed, disabling
configure: Compiling with debug info...
checking for execinfo.h... yes
checking for backtrace... yes
checking for backtrace_symbols... yes
configure: Compiling with x86 emulator
configure: Compiling with x86 JIT
configure: Compiling with default target CPU...
configure: Compiling as PIE for x86_64...
configure: Enabling native DPMI support...
configure: Enabling fast context switching...
configure: optimization set to -O2
configure: error: searpc not available!
```

**A regression?**
I don't know, since the last time I built dosemu2, it didn't yet have searpc/libsearpc as a build dependency. (That was a while back.)

**dosemu2 origins**
I cloned it from the GitHub repo. See reproduction steps above.

**Additional info**
The distro that I tried this on is Clear Linux OS, version 42590.

Running `default-configure` with the `--disable-searpc` parameter did allow it to finish, but at the end, it did log a warning to the console:

```text
configure: WARNING: searpc not available!
```

So that warning implies that Dosemu2 will be working suboptimally without it.

**Comment by stsp** [comment]
> So that warning implies that Dosemu2 will be working suboptimally without it.

Its only for security.
Try `pkg-config --libs libsearpc`
