### ISSUE TITLE
ERROR: unexpected CPU exception 0x0e err=0x00000014 cr2=ffff3698 while in vm86 (DOS)

### ISSUE THREAD

**Issue by mkst** [dosemu2/dosemu2#2317]
**Describe the bug**

We are [experiencing](https://github.com/decompme/decomp.me/actions/runs/12222691631/job/34093284501?pr=1387) crashing of (latest) dosemu2 when our `dosemurc` includes `$_sound = (off)`

```
Page fault at eip=ded16000
eax=00185744 ebx=0016bd50 ecx=00000000 edx=00185765 esi=00061d3b edi=0000004d
ebp=0016bd40 esp=0016bd30 cs=1a7 ds=19f es=19f fs=19f gs=1b7 ss=1af cr2=0000bff6
Call frame traceback EIPs:
  0xded16000
  0x0004fe63
  0x0002442c
  0x00026e93
```

Same setup as before, using [nsjail](https://github.com/google/nsjail) under Ubuntu 22.04. (issues raised before [1](https://github.com/dosemu2/dosemu2/issues/2265) and [2](https://github.com/dosemu2/dosemu2/issues/2149).

Obviously we can remove this line from our config, but we added it as we thought disabling sound would speed up invocation/execution.

The binary being run is CC1PSX.EXE from [this](https://github.com/mkst/esa/releases/download/psyq-binaries/psyq3.3.tar.gz) archive. Invocation something like:

```bash
HOME="." /usr/bin/dosemu -dumb -f dosemurc -K . -E "CC1PSX.EXE -quiet -o object.s object.oc"
```

**Comment by stsp** [comment]
You mean, enabling sound avoids crash?

**Comment by mkst** [comment]
Removing that line from config avoids the crash.. which I guess is the same thing as enabling sound (but I didn't try explicitly setting to on)

**Comment by stsp** [comment]
So where to get this object.oc?

**Comment by mkst** [comment]
E.g.
```c
void foo() {};
```
Save with windows line endings

**Comment by stsp** [comment]
Yes, its reproducible sometimes.
Rather rarely.

**Comment by mkst** [comment]
Interesting, it happens (I think) every time with our setup (using nsjail)

**Comment by stsp** [comment]
What kind of thing is this?
It has `Turbo-C - Copyright (c) 1988 Borland Intl.`
and also lots of djgpp and go32 strings!
I thought I am the first one who implemented
the custom go32-compatible stub.

Is this a C compiler for sony PS?
Is it open-source?

**Comment by mkst** [comment]
It is indeed a compiler for PlayStation, unfortunately this particular binary isn't open source, but it is based on GCC (2.6.x) if that helps at all?

**Comment by stsp** [comment]
It doesn't help, I am just curious,
as it seems to be a djgpp wrapped
into something custom.
Does it require cwsdpmi.exe under
bare-metal DOS, or it works w/o
external DPMI server?

**Comment by mkst** [comment]
Unfortunately I don't know - I've never tried to run this executable outside of dosemu2/dosbox

**Comment by stsp** [comment]
And on dosbox it doesn't require anything
to enable DPMI? Because normal djgpp
tools do require cwsdpmi.exe there.

**Comment by stsp** [comment]
So the problem is 06950a7f which is
quite sad. Please use:
`$_cpu_vm_dpmi = "native"`
as a work-around for now.

@andrewbird would you like to
add this to the test-suit please?

**Comment by stsp** [comment]
Please try this patch:
```
--- a/src/base/emu-i386/simx86/econfig.h
+++ b/src/base/emu-i386/simx86/econfig.h
@@ -56,7 +56,7 @@
 #undef DEBUG_TREE
 #define DEBUG_TREE_FILE        "/DOS/treedump.log"
 
-#define        USE_LINKER      1       // 0 or 1
+#define        USE_LINKER      0       // 0 or 1
 #undef DEBUG_LINKER
 #undef SHOW_STAT
 
```
For me it seems to be a 100% cure.
Probably we finally got the test-case
for the linker instability which I suspected
for years but could never reproduce.

**Comment by stsp** [comment]
Should now be fixed.
