### ISSUE TITLE
RFE: Allow specifying an executable or slirp for the $_com[1-16] settings

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#406]
While there are multiple ways to get a working network connection within dosemu, the easiest way seems to be:
1. Run: socat PTY,echo=0,link=/tmp/vmodem exec:slirp,pty,stderr,setsid
2. Specify: $_com1 = "/tmp/vmodem"
3. Install Trumpet Winsock (or similar tool) and set it to SLIP on COM1

This could be made even easier by letting dosemu run slirp directly with a special keyword. Another option could be to have a exec keyword so that one could also put 'bash' there. (There also seems to be the 'virtual' keyword for that though.)

I would imagine something like $_com1 = "slirp" or $_com1 = "exec:/usr/bin/slirp" (or "exec:/bin/bash").

**Comment by stsp** [comment]
> Install Trumpet Winsock

You mean under windows?

> option could be to have a exec keyword so that one could also put 'bash' there.

Everything is possible, patches welcome. :)

**Comment by jharrison022** [comment]
If you can run Windows for Workgroups, I'm almost sure there's a native packet driver shim available.

I remember running IE 5 under WFW 3.11 just for kicks.  No Trumpet Winsock, but I think you may need that for old Netscape.

**Comment by jschwartzenberg** [comment]
I've looked around for such a shim but I can only find them the other way around (exposing an NDIS3 driver as a packet driver interface).

I was also thinking of executing slirp using `unix` instead, so this feature wouldn't have to be implemented. Then it would be really neat to have access to all the configuration settings from dos (maybe through the system command).

I also noticed that slirp isn't included in all distros :(
Maybe it would be easier to include an init/systemd script with dosemu which sets up a dosbr0 similar to libvirt's virbr0 if this vde2 stuff doesn't get off the ground.

**Comment by stsp** [comment]
> I guess there are other tools that support SLIP over a serial port as well though. 

If you can find any, then this makes sense.
But implementing this just for slirp, which is
not available anywhere, makes me too lazy. :)

**Comment by jschwartzenberg** [comment]
Another use I could come up with is running bash or another shell so that it's easy to access a console from dos through a terminal program. But I just tried this: `unix bash` which seems to work as well.

Do you know whether there's a way to run programs in the background with `unix`? Maybe there are actually dos TSRs that would allow that?

**Comment by jschwartzenberg** [comment]
With `$_vnet = "tap"` it's possible to automate network configuration from within dosemu when a preconfigured nat bridge is set up. Installing libvirt will do this. (I think also lxc, virtualbox, vmware, etc. set up such a bridge on installation, just a different device name for the bridge needs to be used then.)

To get this to work:
Use `visudo` to edit `/etc/sudoers` and add these lines:
```
Cmnd_Alias TAP_UP        = /sbin/ip link set dev tap[0-9] up
Cmnd_Alias TAP_TO_BRIDGE = /sbin/ip link set dev tap[0-9] master virbr0
%libvirtd ALL=(root) NOPASSWD: TAP_UP, TAP_TO_BRIDGE
```

Then edit `autoexec.bat` (or `autoemu.bat`) and add these lines:
```
unix sudo ip link set dev tap0 master virbr0                   
unix sudo ip link set dev tap0 up
```

After starting `dosemu -s` now, things like watt32b will just work (if dosemu gets tap0). It would be nice to see which tap device was assigned to dosemu (maybe through the system command). Another way would be to configure a bridge device in dosemu.conf and let dosemu add its tap interface to the bridge and bring it up itself.
Also dosemu could come with a script to set up a nat-bridge. Maybe this could work by calling networkmanager as well as this might be the easiest way to start a proper dnsmasq instance.


Using slirp with a serial port and a packet driver for slip should allow automatic networking without the '-s'.

It seems that 'unix slirp' also working inside dosemu. Is anyone aware of a SLIP client that can hook up to stdin/out instead of a serial port? :)

**Comment by stsp** [comment]
I don't see your point, we already have
vde that does this all. And yes, allowing
to hook slirp to serial port would be nice;
I already hooked modemu to it, which
was more difficult, but slirp is more difficult
to test, so I haven't done this yet.
I don't see why the one would wonder
about things that require privs to set up.
Its not a problem to hook in slirp, its just
me not yet implementing it, plus you can
nevertheless use it with socat, so what's
the deal?

**Comment by stsp** [comment]
Also I wonder why can't slirp itself create
a pty for dosemu's use. Much fewer work.

**Comment by jschwartzenberg** [comment]
But vde especially patched isn't included anywhere. I wonder why there's no release with the important patches in all distributions. Is it really maintained?

**Comment by stsp** [comment]
https://aur.archlinux.org/packages/vde2-dosemu2/
I think there is some libvirt-based replacement that
also uses slirp, and because of that, vde is not
maintained. But not sure.

**Comment by stsp** [comment]
No, its more likely that vde is unmaintained
simply because qemu have embedded slirp
in, and there are nothing else in the world but
qemu. :) There are probably no slirp alternatives
for the mere mortals.

**Comment by jschwartzenberg** [comment]
Indeed I just checked, libvirt doesn't support user space networking at all from what I can see.

I was looking online for a dos serial port emulator which could hook up stdout/in. Then I could point that to `unix slirp` :) :) I haven't found anything yet though.

**Comment by stsp** [comment]
It is not difficult to allow dosemu to use
slirp. We just need to implement popen2()-alike
function that uses forkpty() instead of fork()
and hook that into ser_init.c. You can try that
yourself, really a small task.

**Comment by stsp** [comment]
https://libvirt.org/formatdomain.html#elementsNICSSlirp
This of course does not mean libvirt uses slirp.
It likely just supports configuring qemu to use slirp.

**Comment by jschwartzenberg** [comment]
Yes indeed. Maybe `macvtap` would also be neat in combination with dosemu's existing ethernet support in case a user wants to avoid NAT. That would still require '-s' though.

Wouldn't it be easier to just start socat and slirp from autoexec.bat and point them to a virtual serial port of dosemu (like ~/.dosemu/vmodem)?

**Comment by stsp** [comment]
Not for user as he won't be able to do
that by only altering the config.
By the way, I see no reason in the use
of autoexec for this as then any script
can do it prior to starting dosemu. Doing
this from autoexec may not work as dosemu
may try to open the port earlier, when it
is not created yet.

**Comment by jschwartzenberg** [comment]
But maybe there could be a default configuration for that? I don't think it's a problem when the port is opened before something is connected to it.

**Comment by stsp** [comment]
There is no port before you created it
with socat! So believe me its a problem.

**Comment by jschwartzenberg** [comment]
Yes, you're completely right, I was mixing it all up.

**Comment by jschwartzenberg** [comment]
I mailed a bit with the Slirp maintainer. He suggested the qemu code as it's maintained. I understand qemu's code is much uglier than vde though. So I guess the best way forward would be to add vde support to qemu first so that vde gets more supported ;)

**Comment by stsp** [comment]
> I mailed a bit with the Slirp maintainer.

With what maintainer?

> I understand qemu's code is much uglier than vde though.

vde just ported some earlier qemu code.
Porting qemu code by hands is difficult,
but there seems to be some libslirp that
ported some qemu version...

> So I guess the best way forward would be to add vde support to qemu first

Why do you think qemu does not support
it already?

**Comment by jschwartzenberg** [comment]
I mailed with Kelly Price. This libslirp appears to look quite nice indeed. (1) It seems it would be really cool to put that in all kinds of emulators, also things like mame. I wonder how many programs use it now.

I would think that qemu could drop its internal implementation if vde would be supported.

(1) https://github.com/rd235/libslirp

**Comment by stsp** [comment]
> I would think that qemu could drop its internal implementation if vde would be supported.

And google thinks qemu already supports vde.

**Comment by jharrison022** [comment]
@jschwartzenberg,

I'm not quite grasping what you're trying to do, but looking at this from the outside it seems you might be making something more complicated than it needs to be. :)

If you can locate the archive TCP32B.ZIP previously hosted on the MS FTP site, it's a free (beer) and official TCP/IP package for WFW with a packet->NDIS3 shim that installs as network card into WFW.

If you can get this set up, you can honest-to-FSM run IE 5.1 and a bunch of other stuff under Win 3.1 without all the underlying DOS kludges.

FWIW, I run both Netware and various WATTCP stuff simultaneously on top of the DOSemu packet driver with little fuss.

**Comment by jschwartzenberg** [comment]
I'm aware of that network stack. I don't think it will run inside dosemu however, as it seems to use a lot of VxDs. I was looking at the older stack which at least seems to have less of them and it appears only "file and printer sharing" is not working with that one (that's the error I get). I didn't see any shim driver in there though, but maybe I missed it.

Would you know the name of the shim driver in the newer stack?

**Comment by stsp** [comment]
> Would you know the name of the shim driver in the newer stack?

I really think there is either none or maybe
in a form of vxd. Why people dislike trumpet
winsock? It is absolutely amazing that it
exists and works under dosemu as good as
it does.

**Comment by jharrison022** [comment]
I don't dislike Trumpet but I think this is a solved problem unless I'm misunderstanding something (and it's quite possible I am).

**Comment by jschwartzenberg** [comment]
Trumpet Winsock is not freeware and still actively sold. In dosemu it indeed works with both Slirp+socat and through winpkt with dosemu's packet driver. It'd be nice to have one of the freeware stacks working as well though.

**Comment by jharrison022** [comment]
> I'm aware of that network stack. I don't think it will run inside dosemu 

Well I think that's the real fix.

**Comment by stsp** [comment]
> Trumpet Winsock is not freeware and still actively sold.

Even its win16 version?

> Well I think that's the real fix.

We can't support this. Our windows support
is limited to ring3 drivers, that excludes vxds.

**Comment by jschwartzenberg** [comment]
Yes, even the win16 version. See:
http://www.trumpet.com.au/index.php/downloads.html
https://thanksfortrumpetwinsock.com/

**Comment by jschwartzenberg** [comment]
Btw. for reference: http://sdfox7.com/win31.htm
Both stacks from Microsoft are there, TCP32B and WFWTCP. I was looking at WFWTCP myself as it includes far fewer VxDs. I've also read that IE includes a dialer. It might work with Slirp as well, I haven't tried this yet.

**Comment by jharrison022** [comment]
@jschwartzenberg 

Have you looked at the last Novell 16-bit stack from Client32?

**Comment by jschwartzenberg** [comment]
No I never looked at it. Could you tell me more about it?

**Comment by jschwartzenberg** [comment]
Some more Winsocks are here:
http://dl.xs4all.nl/Museum/winsock-l/stacks/
http://dl.xs4all.nl/Museum/winsock-l/Winsock_Bundles/
http://dl.xs4all.nl/Museum/Demon/ibmpc/win3/winsock/stacks/

The most interesting one is here:
http://dl.xs4all.nl/Museum/winsock-l/winsock/ToryWinsock/

It has a GPL license, so it could even be embedded into dosemu. It comes with some source to be compiled on the unix side which can then be reached by the program over a serial line. Programs using winsocks will then open sockets directly on the host.

**Comment by stsp** [comment]
> It has a GPL license, so it could even be embedded into dosemu.

Why is this any better than the packet
driver under GPL that is already embedded
into dosemu? Its slower.
Windows part does not include sources
and does not seem to be GPL.

**Comment by jschwartzenberg** [comment]
This solution would allow Windows applications to bind directly to the network interface of the system that dosemu is running on. It will be fully compatible with things like active ftp without any special configuration as programs can just open a port.

For the packet driver solution there are possibly other Winsocks that will work as well, but at least the Trumpet one is still sold. And there's no easy way to avoid NAT.

**Comment by stsp** [comment]
Sounds good but it will only give
the speed of the dial-up connection
because of the serial port.

**Comment by jschwartzenberg** [comment]
I wish my dial-up connection was as fast as my serial port back then :)
I guess I should test this solution and see what will happen. I never saw very high network speed in dosemu though. Maybe there are some tricks to get a faster than real hardware serial port.

**Comment by jschwartzenberg** [comment]
I just checked, the sources for the Windows part are there as well! It'd be interesting to get it all to build. Here's is a bit more information from the author: http://www.troy.rollo.name/opensource.html
(OT: I had never heard of TKERN. Downloads seem to be here: http://cd.textfiles.com/cica/cica9603/disk2/disc2/programr/00_index.htm)

**Comment by jschwartzenberg** [comment]
I can confirm that Ultra TwinSock 0.2 works. The unix code from that version compiles relatively easy on OpenSUSE 42.3 and I managed to use Netscape:
![dosemu-twinsock](https://user-images.githubusercontent.com/877112/30785026-3b6e7b5e-a160-11e7-8741-8d32841c0796.png)

I have DOSEMU set up to use `/tmp/vmodem` and use this command: `socat PTY,echo=0,link=/tmp/vmodem exec:bash,pty,stderr,setsid`. Then I run ./tshost after starting Ultra TwinSock. Once tshost prints its output TwinSock detects that it's connected.

**Comment by stsp** [comment]
Cool!
What speed does it use for COM port?
Have you also tried ToryWinsock?
We probably need to document your
findings.

**Comment by jschwartzenberg** [comment]
Tory just seems to be a misspelling of Troy. The application shows "Speed 256000", I guess I'd have to do some benchmarks to see how fast things can go. I don't know if changing the source and recompiling could make it faster.

Btw. I just tried this `unix 'wget http://www.watt-32.net/watt32b-2.2-dev.10.zip --quiet -O -' > watt32b.zip` but this seems to be extremely slow (and the file is corrupt, I suppose there is line ending conversion going on). Do you happen to know whether this is indeed supposed to be slow?

**Comment by stsp** [comment]
> Tory just seems to be a misspelling of Troy.

So does this work?

> and the file is corrupt, I suppose there is line ending conversion going on

Try `cfmakeraw` option of socat on client
side (on dosemu side it does it itself).

**Comment by jschwartzenberg** [comment]
Yes, Troy's WinSock == TwinSock.

I'll look into that, but with this performance I'm not sure whether `unix 'wget ...' > x:\tmp\somefile.zip` a good idea in general for downloading.

**Comment by stsp** [comment]
Does it work faster with trumpet?

**Comment by jschwartzenberg** [comment]
I'd have to benchmark Troy's VS Trumpet. I never had very fast download speeds in dosemu in general. With Netscape and Troy I get a bit above 8 kB/s. The bottleneck doesn't seem to be with the serial line speed (maybe it's Netscape). I should test Trumpet with both Slirp and the packet driver.

**Comment by stsp** [comment]
Don't forget `speed 0`

**Comment by jschwartzenberg** [comment]
Note I'm working on a Github repo for TwinSock: https://github.com/jschwartzenberg/twinsock
In any case having a GPL'ed Winsock (and in general more Win16 source code easily accessible) seems useful.

**Comment by andrewbird** [comment]
@jschwartzenberg that's interesting. Is it fully buildable fully from source, what tools does it require? I wonder if it could use a #167 implementation if it existed.

**Comment by stsp** [comment]
@andrewbird It is very unlikely because
#167 mentions a trumpet-specific API, plus
this one just uses the serial port on guest
side.

**Comment by andrewbird** [comment]
@stsp I don't really know what a winsock needs to provide. I was wondering if the serial implementation could be stripped away and the remainder connected up to the Linux host networking somehow. If that were possible then it would need a DOS <> Linux interface and the possibility of that being the #167 interface occurred. Lots of unknowns, at least to me, and hence my wild speculation. :smile:

**Comment by stsp** [comment]
> up to the Linux host networking somehow.

It does exactly this - via a serial port.

**Comment by jschwartzenberg** [comment]
@andrewbird I haven't built the Windows part myself yet. I appears the original binaries were built using a Borland compiler. I hope that it can be done with OpenWatcom as well. I still want to add some more things to this repo and then I'll try building it.

The tshost unix binary is not very hard to compile. I also had to do this to get the screenshot above, there aren't any pre-built binaries for this part.

I could imagine that the serial part could be replaced with something similar to VirtIO, I guess this would make it similar to what Merge/Win4Lin did. It also shipped with its own Winsock.

**Comment by stsp** [comment]
> The tshost unix binary is not very hard to compile.

I wouldn't say that. I tried `build.sh` and got
a lot of errors. Would be nice if you fix building.

**Comment by jschwartzenberg** [comment]
Yes, the version from the repo misses some needed fixes. The easiest one to get going (which I haven't added yet) is this one: http://dl.xs4all.nl/Museum/winsock-l/winsock/ToryWinsock/ultrts02.zip

If you get a compilation error with that one, removing the offending line (or making the types equal) should solve the problem. I'll add Ultra Twinsock and the other fixes to the repo when I have a bit more time.

**Comment by stsp** [comment]
So how does this go?
Have you managed to compile?
That would be a good start for porting
it from serial to packet driver.

**Comment by jschwartzenberg** [comment]
I still need to further into this. I recently got the compiler.

But a cool feature idea I just came up with: connecting and disconnecting serial ports at runtime through a command

It could work like the other DOSEMU specific commands and and allow you to specify to what a COM1-16 should be connected. Maybe even just query the next available port and hook that up to what is specified. One could plug in a USB serial device and within DOSEMU2 trigger a command to hook up `/dev/ttyUSB0` to the next free COM port.

**Comment by stsp** [comment]
This will usually work only if the
com port was available during boot.
DOS initializes them at start.
In any case, the "cool feature" is
the one that many people will use. :)

**Comment by jschwartzenberg** [comment]
Yes, like with real hardware, a bunch of unconnected COM ports should be available all the time. Then I imagine this kind of use case from a batch script running inside dosemu:
1.  `unix socat PTY,echo=0,link=/tmp/vmodem exec:slirp,pty,stderr,setsid`
2.  `emucom com4 /tmp/modem`
3. start SLIP DOS program that uses SLIP

Another is the case with connecting and setting up a USB serial device without having to update the DOSEMU configuration each time.

Another one is not running `slirp` but the Twinsock host tool and then launching Windows.

Being able to dynamically connect and disconnect COM ports makes sense I think :)

**Comment by stsp** [comment]
You can as well have something like
"service dosemu reload" to reload the
config at run-time. Or some tool to change
any config setting at run-time. This is a
long story.
Essentially, there is no guarantee that
in any particular moment the TSR fossil
is not reading/writing that port, so that
you can just disconnect it...

**Comment by jschwartzenberg** [comment]
> You can as well have something like
> "service dosemu reload" to reload the
> config at run-time. Or some tool to change
> any config setting at run-time. This is a
> long story.

I suppose the config variables could be updated by changing the unix environment variables that they are exposed as.


> Essentially, there is no guarantee that
> in any particular moment the TSR fossil
> is not reading/writing that port, so that
> you can just disconnect it...

That would be the same as physically unplugging the port while it's in use on real hardware.

**Comment by stsp** [comment]
> That would be the same as physically unplugging the port while it's in use on real hardware.

Except that its not needed, because dosemu2
already supports expansion cards that provide
many com ports. And if some particular prog
can't use such expansion card and still need
many ports, then this case should be studied,
rather than to implement something in dosemu
w/o any concrete use-case.

**Comment by stsp** [comment]
https://en.wikipedia.org/wiki/Serial_Line_Internet_Protocol
This article says that SLIP uses escapes
over the raw TCP packets. So in that case
do we need to tell libslirp that we want to
use SLIP instead of raw TCP?
Or are these escapes "harmless enough"
that TCP just ignores them so they do not
hurt?

I think it won't be difficult to allow binding
a com port to the network back-end.
I suppose SLIP also works if we bind
COM1 to eg TAP device?

**Comment by stsp** [comment]
So finally this is implemented, 6
years after the request. :)
Better late than never.

**Comment by jschwartzenberg** [comment]
Nice!!! I'll check this out with Twinsock!

**Comment by jschwartzenberg** [comment]
I cannot get it to work with either TwinSock 2.0 or Ultra TwinSock. 
[twnsck20.zip](https://github.com/dosemu2/dosemu2/files/10523360/twnsck20.zip)
[ultrts02.zip](https://github.com/dosemu2/dosemu2/files/10523362/ultrts02.zip)

I put this in my `.dosemurc`:
```
$_com1 = "exec bash"
```

I get a Bash shell in Windows' Terminal, but somehow I can't get this in TwinSock anymore.
Btw. I had to change `tshost.c` to get it to compile as follows:
```
--- a/tshost.c
+++ b/tshost.c
@@ -570,7 +570,7 @@ WriteSocketData(tws_sockinfo *psi)
        }
        else
        {
-               iResult = sendto(psi->iServerSocket,
+               iResult = send(psi->iServerSocket,
                                psi->pdata->pchData + psi->pdata->iLoc,
                                psi->pdata->nBytes - psi->pdata->iLoc,
                                psi->pdata->iFlags);
```
But I don't even reach the point where I can execute it yet.

**Comment by stsp** [comment]
Maybe it doesnt use stdio?
When you execute it directly under bash,
you might be able to type input and see
its output.

**Comment by jschwartzenberg** [comment]
No it does actually. It's supposed to show the terminal, but it seems it hangs the Windows environment in some way. In the past it worked. There are some more things I could test though (standard/enhanced mode, maybe tweak more serial port settings).

**Comment by stsp** [comment]
What windows, you mean win31
in the guest? Have it regressed?

**Comment by jschwartzenberg** [comment]
Yes, it's all running in win31. There might be a regression related to serial communications.

**Comment by stsp** [comment]
I suppose you don't need `exec`
to reproduce it, so maybe a bisect?

**Comment by jschwartzenberg** [comment]
Indeed, I could reproduce it without `exec` too. I'll look into bisecting. I hope the last working version isn't too old. Do you know if there were any significant changes in this area at a certain point?

**Comment by stsp** [comment]
Please see #1868 
He points to a very recent good commit.

**Comment by stsp** [comment]
hi, have you checked the commit
mentioned as good in #1868 ?

**Comment by jschwartzenberg** [comment]
Hi apologies for the late response. I checked that commit, but it didn't seem to work. I was also thinking that it might be related to the DOS version (I tested on MS-DOS before), so I wanted to first find a working total environment and work from there. I didn't have time anymore however :(
