### ISSUE TITLE
emm286 support

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#422]
To support emm286, we need at least
the following things:

- split out `umb.sys`. It is very simple by itself,
but it needs to know what emm will be used.
If emm286 will be used, then `umb.sys` should
allocate all including 0xe000, but should leave 0xe000
in case `ems.sys` is used later. This means we need
some `FULL` param to `umb.sys`, or maybe
`NOEMS`? :) Perhaps the simplest solution is
to have `umb.sys` to allocate all, but if `ems.sys`
is used, then `umb.sys` should not be loaded
at all, meaning that `ems.sys` will have a slightly
different builtin version of `umb.sys`. Thoughts?

- make `msdos.c` to respect the native EMM
instead of doing the direct calls to the builtin one.
Unfortunately this will require a quite large rework
of `msdos.c` itself and the surrounding infrastructure
(callbacks, helpers, etc)

**Comment by stsp** [comment]
I've started adding umb.sys in a separate branch.
So far just a trimmed down ems.sys.
Everyone is welcome on working on it. :)

**Comment by stsp** [comment]
We now have the fully functional umb.sys, so
the first part of the task is complete. ems.sys
is stripped to only support UMB for compatibility.
Now you can do:
```
device=e:\dosemu\umb.sys full
devicehigh=c:\emm286.exe 8192
```
and get 8Mb of EMS without ems.sys.

Now I wonder how to proceed with the second
part of the task, which is to teach msdos.c to
use the external EMM. I can think of the following
options:
1. Offload EMS mapping to realmode helpers.
This will mean the realmode helper should run
before pre_extender(), which means a complete
rewrite of msdos.c's infrastructure in a very
sub-optimal way. API will become insane as DPMI
will no longer be able to call pre_extender() directly.
2. Implement coopthreads backend for protected
mode and coopthreadize DPMI to make it re-enterable.
Then msdos.c will be able to request the EMS
mapping and DPMI will serve it in another coopthread
like do_call_back() does for realmode. Crazy.

So if someone knows how to solve the msdos.c's
part of the problem, please write.

**Comment by stsp** [comment]
Another interesting EMM to try:
http://www.emsmagic.com/

**Comment by stsp** [comment]
By the way, this looks like one of many examples
where dosemu2 has a much larger and horribly more
complex code that doesn't provide an answer to
the simplest needs.
Another examples include:
https://github.com/stsp/dosemu2/pull/128#issuecomment-174225954
https://github.com/stsp/dosemu2/issues/544
https://github.com/stsp/dosemu2/issues/463#issuecomment-333348667
https://github.com/stsp/dosemu2/issues/155#issuecomment-336635254
The above tickets resulted in either an unfixed
regressions, or in a huge work (in times of months) of
integrating the simple things into an already complex
dosemu2-specific code, making it times more complex.
In this particular ticket we had msdos.c - a single
file of size 44K in dosemu1, and "msdoshlp.[ch] msdos/*" -
15 files of about 100K size total in dosemu2, w/o
any chance to swap EMS manager without introducing
yet another 100K of a horribly complex code
(like protected-mode coopthreads backend in msdoshlp.c
which no one will ever understand or look into, once it is
written).
Just an observation. Something is not going well here.

**Comment by stsp** [comment]
> stsp commented on 26 Jun 2018

```
15 files of about 100K size total in dosemu2, w/o
any chance to swap EMS manager without introducing
yet another 100K of a horribly complex code
(like protected-mode coopthreads backend in msdoshlp.c
which no one will ever understand or look into, once it is
written).
```

Interesting prediction, but so far it
took only ~30K of code "which no one will ever understand"
in msdoshlp.c and coopth_pm.c, and will perhaps
need another +10K to glue in the emm286 manager.
But debugging these 30K and porting the existing
msdos.c to it, was a pure nightmare.

**Comment by stsp** [comment]
So new coopthreads model allows
to put external code in. emm286
was glued in with some code from
djgpp and pmdapi projects.
Ability to put in external code, should
really help.

**Comment by andrewbird** [comment]
Is there any test utility that can exercise the emm286 functionality that I can add to the test suite?

**Comment by stsp** [comment]
Yes, tasm32.exe and tasmx.exe
are the good ones. They do not
use EMS directly, but they exercise
the dosemu's support of it.
No command-line args are needed,
they would use that quite a lot just
when displaying help.

**Comment by andrewbird** [comment]
Any specific version?

**Comment by stsp** [comment]
I have tasmx 4.1 and tasm32 5.0.

**Comment by andrewbird** [comment]
Thanks. I'll have a look at adding a test tomorrow.

**Comment by stsp** [comment]
I think the next goal would be
the ability of adding the 64bit
tests. Coopth might be able to
switch between 64 and 32.

**Comment by andrewbird** [comment]
I'll need some help with understanding what's required.

**Comment by stsp** [comment]
Its yet to be written...
I am thinking of the fdpp-alike
tool-chain, but this time with
prot-mode support.
It will probably require most
of the same components that
fdpp has, like a small dynamic
linker, loader, run-time lib...
and who knows what else. :)
So far even the coopth-DPMI
frame-work is not fully done.
But its getting well.

**Comment by stsp** [comment]
There is probably some instability
because I've seen this a couple of
times this week:
`ERROR: HLT: hlt_default(0x0220) called, exiting`
But I've no idea how to reproduce,
except that it happens after some
start/exit of DPMI progs.
Maybe tests will help with that...
but unsure. :(

**Comment by stsp** [comment]
So to test emm286 you need
to do this:
```
--- fdppconf.sys        2021-12-11 23:38:50.409381214 +0300
+++ fdppconf.sys.emm286 2021-12-11 23:33:23.632371099 +0300
@@ -5,8 +5,9 @@
 dosdata=umb
 lastdrive=Z
 int0divz=off
-device=dosemu\umb.sys
-devicehigh=dosemu\ems.sys
+device=dosemu\umb.sys /full
+;devicehigh=dosemu\ems.sys
+devicehigh=c:\emm286\emm286.exe 4096
 rem emufs.sys /all replaces emufs.com
 devicehigh=dosemu\emufs.sys /all
 devicehigh=dosemu\cdrom.sys
```

That used to work also before
for emm-using progs, but borland
tools (like tasm32/tasmx or bc)
or win31 couldn't work that way
before.
