### ISSUE TITLE
Tetris Classic hangs at the title screen if it's started after Jungle Book

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#492]
When I first run Jungle Book, then quit with `alt+q` and then run Tetris Classic, the intro sound doesn't play and the game hangs at the title screen. Starting Tetris Classic without sound doesn't make a difference.

I couldn't reproduce this hang with other games (tried with Aladdin and Micro Machines) instead of Jungle Book.

More info about Jungle Book: http://gameswin.org/gameen.php?id=2011
And Tetris Classic: http://www.abandonia.com/en/games/914/Tetris+Classic.html

**Comment by stsp** [comment]
Worth trying on other emus like pcem.

**Comment by jschwartzenberg** [comment]
Yes, I forgot to mention that I also want to try this directly on hardware.

**Comment by jschwartzenberg** [comment]
Just tested this on hardware without emulation and then the issue does not occur.

**Comment by stsp** [comment]
Same dos?

**Comment by jschwartzenberg** [comment]
No, I will test that. I just noticed this warning, maybe it's related:
```
ERROR: DPMI: Warning: trying to leave DPMI when in_dpmi_pm_stack=1
```
This warning is printed after exiting Jungle Book with `alt+q`.

**Comment by stsp** [comment]
Likely so.
It means that the program have actually crashed.
Please add the `-D9+M` log (don't bother running
tetris, I only need the crash).

**Comment by jschwartzenberg** [comment]
Here you go:
[boot.log.gz.base64.txt](https://github.com/stsp/dosemu2/files/1404805/boot.log.gz.base64.txt)

(For some reason just gz isn't accepted by Github anymore.)

**Comment by stsp** [comment]
Try `$_cli_timeout = (0)`
With that, please attach `-D9+Mr`

**Comment by jschwartzenberg** [comment]
Here is the new log:
[boot.log.gz.base64.txt](https://github.com/stsp/dosemu2/files/1404937/boot.log.gz.base64.txt)

**Comment by stsp** [comment]
Is this still a problem?

**Comment by jschwartzenberg** [comment]
Yes, I can also reproduce it on my new system. Let me know if you'd want to try to reproduce this, I can provide both games.

**Comment by stsp** [comment]
The initial links are broken.

**Comment by jschwartzenberg** [comment]
The to get Tetris Classic is working, here is the other game:
[runbeforetetrisc.zip](https://github.com/dosemu2/dosemu2/files/5075737/runbeforetetrisc.zip)
