### ISSUE TITLE
Super Tetris has weird sounds

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#512]
When playing Super Tetris, there are issues with the sounds (which start playing after the music finishes). In DOSBox the sounds seem to be better.

Here is more info about the game: https://www.myabandonware.com/game/super-tetris-1a0

This is one of those classics that really should have good support in DOSEMU2 ;)

**Comment by stsp** [comment]
Its using direct dac writes.
The only fix I can offer is an option
that will allow to set the fixed sampling
rate, and you'll have to set it per every
game.

**Comment by stsp** [comment]
dosemu2 is really not for very
old games - dosbox is. dosemu2 is
for hungry prot-mode games. :)

**Comment by stsp** [comment]
It is even worse.
When music is playing, it programs the
PIT to approx 1KHz, but when it plays
sounds, it uses 5.6KHz, which dosemu
currently cannot handle.

**Comment by jschwartzenberg** [comment]
It seems version 1.4 handled this game better. Would you like a bisect?

Another game that has strange sounds is Duke Nukem 2. It already had this problem in 1.4 though. Should I open a separate issue for that?

**Comment by stsp** [comment]
OK, seems to work perfectly on a
pic_revert branch. I'll think of the
work-around later.
We may need to list the programs
that are affected by that change.
