### ISSUE TITLE
DOS command "system -ep" displays "About to Execute : " line twice

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#746]
**Describe the bug**
When running a command with dosemu -E (system -ep in autoexec.bat), the line "About to Execute : " is displayed twice.

**To Reproduce**

```
$ dosemu -dumb -E whatever
dosemu2 2.0pre8-20190108-824-g311412462
Configured: 2019-01-07 22:38:52 +0100
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org

ERROR: fdpp booting, this is very experimental!
FDPP kernel 0.1beta3 [GIT: beta-3-11-gc30c6bc] (compiled Jan  7 2019)
Kernel compatibility 7.10 - GNUC - 80386 CPU required - FAT32 support

Written by Stas Sergeev, FDPP project.
Based on FreeDOS sources (C) Pasquale J. Villani and The FreeDOS Project.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

C: HD1, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
D: HD2, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
E: HD3, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
F: HD4, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=  2000 MB
dosemu XMS 3.0 & UMB support enabled                                           
dosemu EMS driver rev 0.8 installed.
EMUFS host file and print access available
Kernel: allocated 115 Diskbuffers = 62560 Bytes in HMA
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:0
Welcome to dosemu2!
    Build 2.0pre8-20190108-824-g311412462
About to Execute : whatever
About to Execute : whatever
Bad command or filename - "whatever".
```

**Comment by stsp** [comment]
This is an incompatibility within different command.coms.
Please use `4dos.com` for now to avoid this.
It implements ae00 interface fully.
freecom only considers the internal commands
after the ae00 substitution, so eg `dosemu -E dir -T -td`
will work correctly, but `dosemu -E mem -T -td` will not.
Fortunately freecom would still execute the original cmd
as a fall-back. Unfortunately, MS-DOS's command.com
doesn't execute the original cmd as a fall-back, so for
MS-DOS, -E is completely broken.
comcom32 doesn't support ae00 at all, and as the result,
works perfectly (using generic.com).

So we have a regression of the broken -E on MS-DOS,
and we have a freecom bug that you've noticed.
Both problems look too minor to act.
Please switch to 4dos.com as a work-around, or just
ignore the problem, or use comcom32 to avoid ae00
and any related problems.

**Comment by stsp** [comment]
I added the proper 4DOS support to system.com.
Not sure if anything else can be done on dosemu side.

**Comment by stsp** [comment]
@andrewbird do you happen to know
why on dr-dos the config.sys is not
being processed, and `system -e`
causes crash? I tried different versions,
I thought only latest edr-dos breaks,
but seems like all of them do.

**Comment by andrewbird** [comment]
Not sure, I haven't noticed it, but I haven't run the full tests lately. Have you an example?

**Comment by stsp** [comment]
Sorry, config.sys mess was my own stupidness,
fixing it now. Its just that I haven't used DR-DOS
myself before.

**Comment by stsp** [comment]
Ok, DR-DOS works perfectly now, and did
so before too, for everyone who configured it properly
by hands (I now only updated default config.sys).
And yet -E doesn't work on any version of it.
Which looks strange as RBIL explicitly mentions
Novell DOS in ae00 comments. Does anyone have
a genuine Novell DOS? I can't find one.

So basically currently -E only works on freecom
(with bugs, but works), on comcom32 (uses generic.com)
and on 4DOS (perfectly).
While I'd like to care only about FDPP/comcom32
combo from now on, this list looks too small and dull...

**Comment by stsp** [comment]
Hmm, 4DOS is open-source, so do we still
need comcom32? :)

**Comment by andrewbird** [comment]
Not sure about the licence though see https://web.archive.org/web/20090326064216/http://4dos.zzl.org:80/#licence_

**Comment by andrewbird** [comment]
I believe this is the march 93 update of DR-DOS 6.00 which is the first to work with MFS
ftp://major.butt.care/mirrors/DOS Software/OS/DR DOS/Drdos60/ after that came the first branded Novell release (7.0) which you can find here https://winworldpc.com/product/dr-dos/7x

**Comment by stsp** [comment]
Yes, yes, wikipedia is also clear on that license:
https://en.wikipedia.org/wiki/4DOS

Also freecom docs say this:
```
7. The original command line is tried as either drive change ("?:" syntax)
        or external command. Note: Any change of both the command name buffer
        (DS:[SI]) and command name buffer (DS:[BX}) are ignored.
...
III. Incompatiblies

- In earlier versions FreeCOM used the command line buffer (DS:[BX])
        to execute an external command, if applicable; thusm allowing an
        extension to re-write the command line. This is NO LONGER so, for
        compatibly with MS COMMAND.
```
Great choice of what to stay compatible with!
You have to stay compatible with the good implementations
of command.com (like 4DOS), and instead they took the
worst one. :(

**Comment by stsp** [comment]
Thanks for Novell DOS pointer!
So its command.com works very well for -E.
And it can be used with DR-DOS, too.
So it seems DR-DOS also stripped the
functionality for the sake of compatibility,
as did freecom. :(

**Comment by stsp** [comment]
So the list is:

`-E` works perfectly on:
- Novell DOS
- 4DOS (with any DOS)

Broken on:
- MS-DOS
- PC-DOS
- DR-DOS

Works using generic.com as a fall-back:
- FreeDOS (but tries ae00 first, resulting in 2 "About to Execute" msgs)
- FDPP/comcom32

comcom32 is a temporary solution, I don't
want to invest any time into it until we have
comcom64. With all the fall-backs it works
surprisingly well.
I wonder if something needs to be done with
a "broken" list though.

**Comment by stsp** [comment]
Oh, and freecom appears to not support `%ERRORLEVEL%` -
an extension that allows to access an exit code as a variable.

**Comment by stsp** [comment]
And also freecom doesn't exit with exit
code of last cmd that was started with `/C`,
so with freecom it is not possible to return
the DOS exit code to linux.

I added the missing features into comcom32,
so now exit status works with both 4DOS and comcom32,
and freecom is a complete outsider. NovellDOS's
command.com is also bad at exit status and `%ERRORLEVEL%`.

As for fixing -E - I did all the planned changes,
but I can't fix it. Most command.coms do not
free enough memory when calling ae01, so
running the command with 4b from there is not
possible.
So this is CANTFIX.
We need to abandon freecom ASAP, and use
either 4DOS or comcom32. 4DOS is so cool,
it supports everything, its really sad I need to
add features to comcom32 instead...

**Comment by stsp** [comment]
I think this can be fixed if system.com just
sets the needed variables and autoexec
executes the actual command using these
variables.
This will make it impossible to execute anything
with system.com alone, but hope no one
uses it outside of an autoexec.bat.
#913

**Comment by stsp** [comment]
Correction to the ae01 table.
I didn't set PATH properly when testing
previous time, so MS/PC DOSes didn't
work for me.

`-E` works perfectly on:
- Novell DOS
- 4DOS (with any DOS)

Broken on:
- DR-DOS

Works using generic.com as a fall-back:
- FreeCOM (any DOS/freedos, tries ae00 first, resulting in 2 "About to Execute" msgs)
- MS-DOS (2 "About to Execute")
- PC-DOS (2 "About to Execute")
- FDPP/comcom32

So there is no difference between freecom and
ms-dos's command.com in that regard.

**Comment by stsp** [comment]
Should now be fixed (for any command.com).
