### ISSUE TITLE
Window Integration with host system

### ISSUE THREAD

**Issue by RossBoylan** [dosemu2/dosemu2#821]
**Describe the bug**
dosemu launches and  shows a window, but the window's icon does not appear in the taskbar, and eventually screws up the association of task bar icons with programs.

**To Reproduce**
Running KDE Plasma 5.14.5, KDE Frameworks 5.54.0, qt 5.11.3 on linux kernel 4.18.0-4-amd64 on Debian testing/buster.  dosemu2, fdppm comcom32 built into debian packages from git today.  Type dosemu in a Konsole (also tried dosemu -S, same results).

**Results**
The dosemu window opens as expected.  However, the taskbar at the bottom has no entry for it.  When I `<alt>-<tab>` to bring up the window switcher, it does have an entry for the window (with a tiny blue icon), but selecting it, either by cycling through and releasing or by clicking directly, does not bring the window up.

After those experiments with the `<alt>-<tab>` I noticed the task bar icon for another window, though continuing to show the icon for the other window (emacs) actually had become associated with the dosemu window (hovering over the icon showed a preview of the window, and clicking on it brought the window up or down).  There was also a light grey bar just above the icon, suggesting perhaps to graphical objects hiding in the same space.  Actually, all my taskbar icons have become associated with different programs than the ones they depict.  It looks as if a different program is now on the "can't activate" list.

This doesn't seem like something that should be possible, and so it may reflect bugs in the desktop environment.  However, this is the only program for which I've had this problem.

**Attach the log**
[boot.log](https://github.com/stsp/dosemu2/files/3170959/boot.log)

**Comment by stsp** [comment]
Try `dosemu -X` - still the same?

**Comment by RossBoylan** [comment]
dosemu -X is way better; in fact I don't see any problems at all with it.

BTW, after I posted my initial report I discovered the damage was even more extensive.  The notification area of the taskbar was not getting updated, leading me to think it was 6:30 when it was really 9:00!

So I guess for now I'll stick with -X.  Apparently the default is SDL.

Ross

________________________________________

**Comment by stsp** [comment]
Default is sdl, but not only dosemu
uses sdl. I suppose no problems with
dosbox?

**Comment by RossBoylan** [comment]
Haven't tried dosbox under this OS release; it was OK for earlier ones.

The session I started with -X, even without any apps running, seems to use noticeably more CPU.  It was close to undetectable under SDL, but 5 or 6% under X.  Although, once I start my semi-graphical program, useage drops to 1-2% (!?).

________________________________________

**Comment by stsp** [comment]
I filled the bug about excessive CPU usage.
For me it happens regardless of -X.

**Comment by t9999clint** [comment]
I've noticed a similar bug with my installation. I'm using KDE Neon. I think I've tracked it down to a KWin bug on my system. It's turning off the compositor and it's making KWin freakout. I've seen it do this with Parsecd and RetroArch as well.

I've found a workaround that seems to solve the issue for me. Rightclick on the the top of the dosemu display window, go to more actions, special application settings. Then from there go to the appearance & fixes section, check the box for Block compositing, choose Force, and No.
You can also just disable the compositor completely.
![Screenshot_20190517_143602](https://user-images.githubusercontent.com/50733691/57955045-f404a380-78b1-11e9-8616-9d14a00b810f.png)

**Comment by RossBoylan** [comment]
> I filled the bug about excessive CPU usage.
> For me it happens regardless of -X.

Yes, I'm seeing it either way, -S or -X, too.

What I though was an interface style difference seems actually to be something else.
When dosemu2 has just launched and is sitting at the prompt waiting for text input (albeit within a graphics window): 5 or 6% CPU.   After I launch my 80x50 semi-graphical app, which does respond to mouse clicks (and so, I though would go crazy polling) the useage drops to 1%.

**Comment by RossBoylan** [comment]
> I've noticed a similar bug with my installation. I'm using KDE Neon. I think I've tracked it down to a KWin bug on my system. It's turning off the compositor and it's making KWin freakout. I've seen it do this with Parsecd and RetroArch as well (I think they also use SDL).
> 
> I've found a workaround that seems to solve the issue for me. Rightclick on the the top of the dosemu display window, go to more actions, special application settings. Then from there go to the appearance & fixes section, check the box for Block compositing, choose Force, and No.
> You can also just disable the compositor completely.

@t9999clint An impressive bit of detecting.  How did you figure that out?  Are there any open KDE bugs about it?

I tried your solution--changing the application settings, not stopping all compositing--and it seems to work for me too.  I switched back to -S since I gather that's preferred.

I should mention I'm also using the nvidia proprietary driver.

The stop all compositing would be something affecting the whole KDE window system, right?

3 caveats:

1. I'm not sure I was getting any misbehavior just now even before I blocked compositing, so there may be something else at work.  In particular, a window icon appeared on my task bar before I changed any settings, and before it didn't.
2. When I started dosemu2 without any options the first time I still got X, not SDL.  Does it have some way of remembering the previous choice?  I looked in the log and the config files it said it was parsing and see nothing there selecting the video mode.  I.e., X wasn't made the default.  I later used an explicit -S, which the boot.log confirms activates SDL.
3. Even with the compositor change the placement of the icon in the task bar is odd: it appears on the far left, rather than the far right of the window icons, as I think every other app does.  This isn't much of a problem, though it does slightly violate (my?) expectations.  But it's weird.

**Comment by stsp** [comment]
X by default may happen because
of the custom font use. We do not
yet do SDL font rendering. So even
when you force -S, there is a nuclear
mix of an x and sdl code.

**Comment by RossBoylan** [comment]
Just noticed another SDL/X difference.  While running dosemu -S I checked the battery status and it said, roughly, "power management disabled while playing a game (SDL)".  When I closed dosemu and restarted with -X, there was no such notice.

No idea if there's a way to use SDL and say you're not a game.  I also don't know what part of the system is making this decision, if it's KDE or something lower down.

Ross

________________________________________

**Comment by stsp** [comment]
Thank @t9999clint for providing the hint.
I don't think much else can be done on this here.

**Comment by 1ras** [comment]
SDL can be told to not send a hint to disable the compositor with

`export SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0`

As dosemu is not a game, I assume it makes sense to add this to the dosemu startup script.

**Comment by stsp** [comment]
Sounds good.
