### ISSUE TITLE
flashing textires in Spear of Destiny (vm86 jit)

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#86]
The bug happens only when $_cpu_emu="vm86"
but not "vm86sim". Same is under dosemu1.

**Comment by stsp** [comment]
Commit d265cc32 makes this much, much
more difficult to reproduce, but its still there.
Does this ring any bells?

**Comment by mcericdos** [comment]
I do not have Spears of Destiny but I do wonder about the current status... So the problem almost never happens any more? What was the background of the problem?

**Comment by stsp** [comment]
http://www.myabandonware.com/game/spear-of-destiny-1l7
The problem now requires a bit of efforts to
reproduce, while previously it was always there.
Plus vm86jit is no longer a default option, so it
is a bit obscured. Debugging this jit is quite hard.

**Comment by stsp** [comment]
https://sourceforge.net/p/dosemu/bugs/447/
This thread has some patch that does not work.

**Comment by stsp** [comment]
This has a lot of "### Node self hit" in the
log, and I suspect this has something to do
with the self-hitting node spans across the
page boundaries. I suspect so because
d265cc32 was covering the hits across
page boundaries, too, and made the problem
much less visible.

**Comment by stsp** [comment]
Does not happen with something like this:
```
diff --git a/src/emu-i386/simx86/interp.c b/src/emu-i386/simx86/interp.c
index 5ce316e10..936ac86c1 100644
--- a/src/emu-i386/simx86/interp.c
+++ b/src/emu-i386/simx86/interp.c
@@ -315,6 +315,7 @@ static unsigned int FindExecCode(unsigned int PC)
         * any signal processing. Jumps are defined as
         * a 'descheduling point' for checking signals.
         */
+#if 0
        while (!(CEmuStat & (CeS_TRAP|CeS_DRTRAP|CeS_SIGPEND|CeS_LOCK)) &&
               ((InterOps[Fetch(PC)]&1)==0) && (G=FindTree(PC))) {
                if (debug_level('e')>2)
@@ -331,6 +332,7 @@ static unsigned int FindExecCode(unsigned int PC)
                }
                if (TheCPU.err) return PC;
        }
+#endif
        return PC;
 }
 #endif
```

Which looks like a very strong hint to
the node invalidation corner-case.

**Comment by stsp** [comment]
Does not happen with something like this:
```
diff --git a/src/emu-i386/simx86/memory.c b/src/emu-i386/simx86/memory.c
index c6214c452..a833069da 100644
--- a/src/emu-i386/simx86/memory.c
+++ b/src/emu-i386/simx86/memory.c
@@ -370,8 +370,8 @@ int e_handle_pagefault(struct sigcontext *scp)
         * linked by Cpatch will do it */
        /* ACH: we can set up a data patch for code
         * which has not yet been executed! */
-       if (InCompiledCode && !e_querymark(addr, 1) && Cpatch(scp))
-               return 1;
+//     if (InCompiledCode && !e_querymark(addr, 1) && Cpatch(scp))
+//             return 1;
        /* We HAVE to invalidate all the code in the page
         * if the page is going to be unprotected */
        codehit = 0;
```

So its cpatch-specific.

**Comment by stsp** [comment]
Spoke too soon: still reproducible even
w/o cpatch. :(

**Comment by jschwartzenberg** [comment]
Don't know if this is useful, but there's source for Spear of Destiny:
http://wolfenstein.wikia.com/wiki/Source_code

**Comment by stsp** [comment]
That might be interesting.
Have you tried building it? :)

On a side note: seems like recent
commit b3a8a9cd has some impact
on this, making it easier to trigger...

**Comment by stsp** [comment]
This fixes it:
```
diff --git a/src/base/emu-i386/simx86/interp.c b/src/base/emu-i386/simx86/interp.c
index 47361bd07..0b402ab76 100644
--- a/src/base/emu-i386/simx86/interp.c
+++ b/src/base/emu-i386/simx86/interp.c
@@ -335,7 +335,7 @@ static unsigned int FindExecCode(unsigned int PC)
         * a 'descheduling point' for checking signals.
         */
        while (!(CEmuStat & (CeS_TRAP|CeS_DRTRAP|CeS_SIGPEND|CeS_LOCK)) &&
-              ((InterOps[Fetch(PC)]&1)==0) && (G=FindTree(PC))) {
+(PC<0x51000 || PC>0x60000)&&       ((InterOps[Fetch(PC)]&1)==0) && (G=FindTree(PC))) {
                if (debug_level('e')>2)
                        e_printf("** Found compiled code at %08x\n",PC);
                /* ---- this is the MAIN EXECUTE point ---- */
```

So quite a large buffer where we don't
sense the code overwrites. The interesting
thing is that the higher margin of the buffer
is responsible for the nearest textures, and
the lower - for distant textures. So when you
see a flashing texture, you know what margin
is to adjust, depending on the distance to
that texture.
So it almost looks like wolf compiles shaders
and puts them to that buffer, in some magic
way that we can't detect.

**Comment by stsp** [comment]
This hack fixes it:
```
diff --git a/src/base/emu-i386/simx86/trees.c b/src/base/emu-i386/simx86/trees.c
index ccc18a9dd..cbf0f13ba 100644
--- a/src/base/emu-i386/simx86/trees.c
+++ b/src/base/emu-i386/simx86/trees.c
@@ -1220,6 +1220,7 @@ int Tree_InvalidateNodePage(int addr, int len, unsigned char *eip, int *codehit)
   G = CollectTree.root.link[0];
   if (G == NULL) goto quit;
   /* find nearest (lesser than) node */
+#if 0
   for (;;) {
       if (G->key > al) {
        if (G->link[0]==NULL) break;
@@ -1233,6 +1234,8 @@ int Tree_InvalidateNodePage(int addr, int len, unsigned char *eip, int *codehit)
       }
       else break;
   }
+#endif
+while (G->link[0]) G = G->link[0];
   if (debug_level('e')>1) e_printf("Invalidate from node %08x on\n",G->key);
 
   /* walk tree in ascending, hopefully sorted, address order */
```

So indeed the bug is in an AVL search... :(

**Comment by stsp** [comment]
Removing bounty as the bug is
(more or less) located.

**Comment by stsp** [comment]
OK, so the more I look at our avl impl,
the more I think its a pure fake.
Our `NEXTNODE` macro which is used
in a code that is supposed to traverse
entire tree (or large parts of it), looks like
this:
```
#define NEXTNODE(g)     ({__typeof__(g) _g = (g)->link[1]; \
                          if ((g)->rtag == PLUS) \
                            while (_g->link[0]!=NULL) _g=_g->link[0]; \
                          _g; })
```
It can only traverse a sub-tree, as there
is no back-tracking to parents. In fact, in
`struct avltr_node` I can't even find the
link to parent.
So my theory is that this fake impl used
to work more or less until commit 60aaad9e
that allowed a much larger code nodes.
With large code nodes you can't get away
with only traversing a sub-tree when doing
the node invalidations. And it all broke to
hell.
That also explains why I thought the self-hitting
nodes are the problem. Self-hitting nodes are
usually very large, and that is why I've seen
problems mostly with them...

Besides NEXTNODE, another confirmation
of my conspiracy theory is this line:
https://github.com/dosemu2/dosemu2/blob/devel/src/base/emu-i386/simx86/trees.c#L1113
Why would we end the search once we need
to go RIGHT from the MINUS node? Simply
because in this case we need a back-track
to parent, and its not there.

Bart, have you looked at that code?
Am I just misunderstanding it, or is it really
a pure fake/half-implemented stuff?

**Comment by bartoldeman** [comment]
The code is complex but it mostly works (well except for this issue). I'll take a look.

However I get the feeling that `FindTree` could be faster if using a hash table instead of searching the tree.

The find code is taken from avltr_find in libavl 1.4:
```
/* Search TREE for an item matching ITEM, and return a pointer to it
   if found. */
void **
avltr_find (const avltr_tree *tree, const void *item)
{
  const avltr_node *p;

  assert (tree != NULL);
  p = tree->root.link[0];
  if (p == NULL)
    return NULL;
  for (;;)
    {
      int diff = tree->cmp (item, p->data, tree->param);

      /* A3. */
      if (diff < 0)
        {
          p = p->link[0];
          if (p == NULL)
            return NULL;
        }
      else if (diff > 0)
        {
          if (p->rtag == MINUS)
            return NULL;
          p = p->link[1];
        }
      else
        return (void **) &p->data;
    }
}
```
There is a newer libavl these days but I would be surprised if this code wouldn't work. It's all text book algorithms.

**Comment by stsp** [comment]
Searching is only a one part of a tree.
What doesn't work is iteration.

**Comment by stsp** [comment]
I.e. NEXTNODE() is not for searching.
Was it in a lib?

**Comment by stsp** [comment]
Hashing can be faster than tree afaik
only if you use too many buckets.
In which case I would propose to rather
just use the mpmap. Just create a whole
4 or 8Mb array of pointers per mpmap,
and its super fast.

**Comment by stsp** [comment]
And an extra advantage is that you
won't need to do invalidate, then
resetpagemarks, then unprotect -
everything will be in a same map.

**Comment by stsp** [comment]
So libavl has https://github.com/sam0x17/libavl_fork/blob/master/avl.h#L74
avl_traverser with stack.
I think it still doesn't traverse the entire
tree, but NEXTNODE() doesn't even traverse
a sub-tree, it basically doesn't work at all.
And I can't find NEXTNODE() in a lib, so
I suspect it was invented within dosemu.

**Comment by stsp** [comment]
https://github.com/sam0x17/libavl_fork/blob/master/avl.c#L578
Just compare this avl_t_next() with our NEXTNODE().

**Comment by stsp** [comment]
Also see how simple it is with rbtree:
https://github.com/michelmegens/RBtree/blob/master/tree.c#L160
Here its obvious what every function
does. For example tree_find_successor()
back-tracks to parent if the RIGHT node
is missing. This is what we need,
InvalidateNodePage() expects such
behaviour. . But in libavl, even with their
traverser, its still unclear to me if they
can go to parent nodes, or only traverse
the sub-tree.

**Comment by bartoldeman** [comment]
You may have an easier time comparing with libavl 1.4:
ftp://ftp.gnu.org/pub/gnu/avl/avl-1.4.0.tar.gz
libavl 2.0 has a lot of things rewritten.

**Comment by stsp** [comment]
Yes, that one has the code somewhat
resembling our NEXTNODE() in avltr_next().
Which makes no sense to me. :(
At least in newer lib they have a proper
traverser with stack...
Interestingly, putting
`avl tree "right thread tag"`
into duckduckgo search, points
exactly and only to dosemu sources!
Nice! :)
So I don't even know if there are other
sources for me to learn that magic.

**Comment by stsp** [comment]
OK, found it:
https://www.geeksforgeeks.org/threaded-binary-tree/
So basically stack-less traversing is possible
too. Now needs to find out if it is properly
implemented here...

**Comment by stsp** [comment]
So what libavl calls "MINUS" means
a node with thread, and what they
call "PLUS" means normal node.
Mystery solved, back to work. :)

**Comment by stsp** [comment]
Note that you can't really use hashes
here. While in theory, with having lots
of hash buckets, you can over-speed
the b-tree on some large amount of
code nodes searched, what you can't
do is a traversal. I.e. things like
InvalidateNodePage that need to traverse
the page of nodes (and do not need
any search at all, or maybe only one
search of a starting node), are becoming
very slow.
So, after reading how the thread-tree
works, I actually am under impression
that avl was the right choice here. :)
Not something I frequently say about
the dosemu1.0 choices, but it seems
to be the one.

**Comment by bartoldeman** [comment]
ok, good to see we're finally understanding this code better! Well after all AVL trees are a Soviet invention :)

I just noticed when profiling that FindTree is the function that the JIT spends the most time in now, so also wondered if instead of just one LastXNode there could be multiple ones, ie. not to replace the whole AVL tree by a hash table but have a hash table into the tree to speed up the most recently used searches.

**Comment by stsp** [comment]
> Well after all AVL trees are a Soviet invention :)

That team had such a big developments
in a computer science and an algorithm theory,
that they didn't hesitate to write a chess engine
based on their inventions, and of course it
became a world champion of chess engines
(Kaissa engine).

> also wondered if instead of just one LastXNode there could be multiple ones

Maybe something like this can help?
```
diff --git a/src/base/emu-i386/simx86/interp.c b/src/base/emu-i386/simx86/interp.c
index b36f48738..09fe5ae1f 100644
--- a/src/base/emu-i386/simx86/interp.c
+++ b/src/base/emu-i386/simx86/interp.c
@@ -361,7 +361,8 @@ static unsigned int FindExecCode(unsigned int PC)
         * a 'descheduling point' for checking signals.
         */
        while (!(CEmuStat & (CeS_TRAP|CeS_DRTRAP|CeS_SIGPEND|CeS_LOCK)) &&
-              ((InterOps[Fetch(PC)]&1)==0) && (G=FindTree(PC))) {
+              ((InterOps[Fetch(PC)]&1)==0) && e_querymark(PC, 1) &&
+              (G=FindTree(PC))) {
                if (debug_level('e')>2)
                        e_printf("** Found compiled code at %08x\n",PC);
                /* ---- this is the MAIN EXECUTE point ---- */
```

**Comment by bartoldeman** [comment]
That patch certainly helps, when running zx_emul FindCode goes from 14% to 12% of total execution time in the devel build.

**Comment by stsp** [comment]
Not a big improvement then...
But applied.
Do you know why it is called that
much? There is a node linker, your
patches to compile all opcodes,
and now also this, and it is still
excessively called? :(

**Comment by stsp** [comment]
Can you check that its not `TraverseAndClean()`
who eats time, but rather is the search itself?

**Comment by bartoldeman** [comment]
even with most of the opcodes now compiled (popf, sti, and iret are still todo though they are not as common as near call/ret) it still needs to be used after every `ret` or other indirect jmps and calls. So now the JIT just spends a long time in that main while loop in `FindExecCode` without going back to the interpreter.

I can confirm from perf annotating it's the search itself that takes time (the loop that starts with
```
for (;;) {                                                                             ▒
       │           int diff = (key - I->key);    
```

**Comment by stsp** [comment]
Will it help if we do the following:
1. Return node ptr in eax, instead of PC
PC can be got from that easily.
2. FindTree() can have a second
argument - the node to start searching
from. Something like LastXNode, but
more efficient.

Notably, with ret or indirect jump that
may not help much... But at least it
agrees with your idea to prioritize
recently execed code.

**Comment by stsp** [comment]
And of course I suspect that avl
have no efficient algo to search
from non-root node...
With rbtree at least you can go
upwards, so such a search can
be coded.

**Comment by stsp** [comment]
I fixed the search bug in InvalidateNodePage(),
and now Spear is 99% fixed. I mean, it is now a
great challenge to reproduce flashing, and at
most one pixel will flash, so its very difficult
to notice, too. But its still there. :(

I believe I've got the next handle though.
It seems that the overlapping nodes are
possible. The following checks trigger:
```
diff --git a/src/base/emu-i386/simx86/interp.c b/src/base/emu-i386/simx86/interp.c
index 2281b7d38..48fe7229d 100644
--- a/src/base/emu-i386/simx86/interp.c
+++ b/src/base/emu-i386/simx86/interp.c
@@ -3274,6 +3274,10 @@ repag0:
                                        CODE_FLUSH();
                                        NewIMeta(P0, TheCPU.mode, &rc);
                                }
+                             if (FindTree(PC)) {
+                                     error("FSCK\n");
+//                                     CODE_FLUSH();
+                             }
                        }
                }
                else
diff --git a/src/base/emu-i386/simx86/trees.c b/src/base/emu-i386/simx86/trees.c
index 1177ca440..93871491f 100644
--- a/src/base/emu-i386/simx86/trees.c
+++ b/src/base/emu-i386/simx86/trees.c
@@ -1226,6 +1226,7 @@ int Tree_InvalidateNodePage(int addr, int len, unsigned char *eip, int *codehit)
         TNode *G2;
        if (G->rtag == MINUS) break;
        G2 = G->link[1];
+assert(G2->seqbase >= G->seqbase + G->seqlen);
        if (G2 == G || G2->key > al) break; else G = G2;
       }
       else break;
```

Having overlapped nodes again leads to
the codemarks corruption, as we never know
if some node before G exist that crosses the
start of G, and so we need to go back infinitely
when invalidating. Which is why
https://github.com/dosemu2/dosemu2/issues/86#issuecomment-636560066
fixes the problem completely (it goes back
infinitely), while the correct fix (that I've just
pushed to devel) - just partially.

Bart, do you have any idea how to avoid
overlaping nodes?
Hope now you see why I am not applying
your cache patch: this bug is very difficult
to debug, so anything that can obscure its
debugging even more, scares me as hell.
But this time I am really quite confident I
am on the right track (just like I was 1024+
times before...)

**Comment by bartoldeman** [comment]
yes this is a tough one to diagnose.

I believe `FindTree` is correct .. and that's what the cache patch is addressing. That's fairly simple because in FindTree we want an exact match for the key, no nearest search.

But here we are dealing with `Tree_InvalidateNodePage`, a function called far less often, which was obviously not correct, and is more complex, and the proposed cache is not used at all for that function. It will take me some time to understand all this perfectly..

**Comment by stsp** [comment]
Tree_InvalidateNodePage() is fixed - I am pretty
sure its correct now. What I see now is overlapping
nodes. Its not difficult to detect, see the prev comment:
it suggests assert() that triggers when overlapping nodes
are found.
There is a simple source of overlapping nodes:
in interp we simply do not check every address
when generating new node, so it can easily hit
the already existing one. But I can add such a
check, and I still see the overlapping nodes
sometimes. So there is also a non-trivial source
of them. I wonder if your recent patches that
compile jmp and call can cause the overlapping
nodes, for example if the node jumps backwards,
but the jump destination is within that same node...

**Comment by stsp** [comment]
I created the branch "tmp" to show you
what am I up to.
It has all the detections enabled, and it
also adds the checks that should avoid
overlapping nodes. But they do not avoid
all of them, and I wonder where could
they come from now, when I am checking
e_querymark() before generating anything...

**Comment by bartoldeman** [comment]
The compile jump and call patches are to unknown destinations so they just add tail code (i.e. eax has the new eip, which FindTree must then look up). It would be odd for those to cause overlaps.
So I don't think it's a new issue.

But there are 4 callers of NewIMeta in interp.c, so one of them should cause overlaps then...

**Comment by bartoldeman** [comment]
What I mean is that the node linker is explicitly disabled for ret and indirect call/jmp.

There is one thing I realized the other day that *could* mess things up, namely segment registers.
The current lookup mechanism is purely based on key, and ignores cs, if the same code is executed with a different cs there could be issues. I'll get back about this later, I can't remember the exact issue now.

**Comment by stsp** [comment]
Yes, node linker is disabled.
So my guess was that we exit back to interp
and generate from the jump destination. If
that destination is within the same node, then
we can generate the overlap.
But perhaps its not possible, as my
e_querymark() check in "tmp" branch
should detect that and purge the page.
Have you looked into "tmp"?

**Comment by stsp** [comment]
https://github.com/dosemu2/dosemu2/commit/d2d54938bf50c2d2c10d9ad699700cf87d9d3179

**Comment by stsp** [comment]
OK, the querymark() check appears good!
The "fsck" check was not checking "alive".
So having some progress.

**Comment by stsp** [comment]
Applied the fix that avoids the overlap
with dead nodes.
The rest shold be quite straight-forward...
I hope.

**Comment by stsp** [comment]
This oldest and the most difficult bug is finally closed!
