### ISSUE TITLE
doom2 is quite slow

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#909]
**Describe the bug**
And the sound is choppy.

**Comment by jschwartzenberg** [comment]
Maybe related to this?
https://github.com/stsp/dosemu2/blob/daf87de2dc0039d0d220d55c97125879433864c2/doc/EMUfailure.html#L359

What happens when disabling sound?

**Comment by stsp** [comment]
I don't think its related, but, in a lack of
other options (so far), will try later.
You can try too, btw. :)
Duke is quite fast actually.

**Comment by stsp** [comment]
No, doesn't make it faster, plus this ticket
is mostly about the choppy sound. Disabling
the sound won't help much.

**Comment by ThingUroboros** [comment]
possible reason:
https://virtuallyfun.com/wordpress/2019/03/05/degrading-qemu-performance-in-doom/
https://virtuallyfun.com/wordpress/2019/03/15/degrading-qemu-performance-in-doom-part-ii/

Qemu v 0.9 is better but 
The main issue at hand is the watcom retail doom has self modifying code that kills the newer qemu dynamic translations, although the newer ones fare much better, the graphics Io seems to lag.. Maybe it’s my perception I haven’t measured

**Comment by stsp** [comment]
In our case this is unlikely related,
as no cpu emulation is going on.
Some problem with interrupts or with
timer here.

**Comment by stsp** [comment]
doom2 is blazingly fast on pre-8.
So something had heavily regressed.

**Comment by stsp** [comment]
In current devel the regression
is reduced to bare minimum:
basically it is only visible now
in debug builds.
What remains is similar to
#463 so I close this.

**Comment by stsp** [comment]
> What happens when disabling sound?

OK, you appear right: it
was indeed related to sound code. :)
There was a contended lock.

**Comment by stsp** [comment]
> although the newer ones fare much better, the graphics Io seems to lag..

You appear right: the graphics
lag is because doom sets up mode-X.
