### ISSUE TITLE
Running on Windows 10

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#930]
I happen to have a Windows 10 installation on which I could try DOSEMU2. It's possible to run different kinds of Linux compatible GNU environments on top of Windows 10 without a Linux kernel. Here I am using Ubuntu 18.04. I installed comcom32, fdpp and dosemu2. On launch I get this:
![image](https://user-images.githubusercontent.com/877112/65838537-3a5c1b80-e304-11e9-8e17-a76107974347.png)
On the console I get this:
```
$ dosemu
ERROR: iopl(): Function not implemented
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
shared memfd open() failed: Function not implemented
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory
ERROR: alsa_midi (ALSA lib): seq_hw.c:466:(snd_seq_hw_open) : No such file or directory open /dev/snd/seq failed
ERROR: DPMI support is not enabled on your kernel.
Make sure the following kernel options are set:
        CONFIG_MODIFY_LDT_SYSCALL=y
        CONFIG_X86_16BIT=y
        CONFIG_X86_ESPFIX64=y
INFO: booting with comcom32, this is very experimental
INFO: fdpp booting, this is very experimental!
Compatibility warning: CONFIG.SYS found on drive C: is not used by fdpp.
        Use C:\FDPPCONF.SYS to override or C:\USERHOOK.SYS to extend
        the default boot-up config file.
        You can also put KERNEL.SYS to drive C: to override fdpp entirely.
````

No idea if this makes sense to pursue, but I thought it might be interesting to see how far it gets.

**Comment by jschwartzenberg** [comment]
[boot.log](https://github.com/stsp/dosemu2/files/3668012/boot.log)

**Comment by stsp** [comment]
On windows you need to put freecom.exe
to C:\ and symlink it to command.com.
Our DPMI impl is not supported yet, but
it will work fine on windows-10 next year
(or you can sign up for the alpha testing
program and test their WSL2 right now).

But iopl() error makes not sense.
Are you running as root?

**Comment by jschwartzenberg** [comment]
No, I wasn't running as root. Should I run `dosemu -s`?

**Comment by stsp** [comment]
Hope iopl() msg is now gone.

**Comment by stsp** [comment]
Thanks to Bart's great work, you can now
run dosemu on windows-10 (I enabled work-around now).
There are a few caveats:
- needs to install xming
- make sure DISPLAY is set to `localhost:0` rather than just `:0`
because in the later case SDL will try MIT-SHM and that will fail.
(but dosemu -X can work in either case)
- no sound
- most of DPMI progs will crash simx86 (even if
they work under linux), but comcom32 starts, and
you can run real-mode games

**Comment by stsp** [comment]
Works much better now under wsl!

**Comment by jschwartzenberg** [comment]
I can't test this anymore as I got rid of that Windows 10 installation.

**Comment by stsp** [comment]
That's sad, as I can do that rarely by
abusing one of the windows PCs at work.

**Comment by stsp** [comment]
But its not very good yet.
Its roughly like if you run under linux
with `$_cpu_vm_dpmi = "emulated"`.
Not all progs work yet, and all sorts of
various problems like no sound.
And I don't think we can package dosemu2
for windows's wsl anyway (or bundle it
with entire ubuntu rootfs)

**Comment by jschwartzenberg** [comment]
I think once it would be part of Debian/Ubuntu it would be available there when you'd run a Ubuntu userland in there.

**Comment by stsp** [comment]
I am not sure if ubuntu takes entirely everything
from debian or selectively, but I think dosemu2
will remain in PPA even if it is taken by
debian (which usually takes all, or most of).

Being proud of running under windows in an
ubuntu environment is futile. No one will
(or should) install ubuntu, xming and all that
just to run dosemu2 without sound. Its cool
that it can work at least as much, but its not
useful in practice. Packaging as a separate
app and having a host FS access would
give more chances, but I am afraid this will
require porting at least to cygwin.

**Comment by stuaxo** [comment]
Is an MSys build with SDL a possible future for Windoes 10 ?

**Comment by stsp** [comment]
Only if very distant.
cygwin is much more realistic.

**Comment by stuaxo** [comment]
Does cygwin provide more unixy interfaces to make this easier ?

**Comment by stsp** [comment]
That's the whole point of it.
It provides posix.

**Comment by stuaxo** [comment]
Interestingly it looks like SDL in cygwin is possible, which could mean no need for X on Windows
http://www.libsdl.org/extras/win32/cygwin/README.txt

There is also Cynal which looks let's you distribute cygwin apps as ordinary Windows executable
http://www.kylheku.com/cygnal/

Between those two it might be possible to get a user experience that's not too bad on Windows.

**Comment by stsp** [comment]
It seems, cygnal is only needed if
your program uses some posix
tools (via popen() or otherwise).
Instead of using them from cygwin
bundle, cygnal emulates the needed
behaviour on top of the windows
native tools, but it obviously supports
just a few things (can fake /bin/sh
invocation with command.com).
I don't think we are going to need
it, and the cygwin port would be
difficult, because dosemu2 uses
a wide variety of non-posix APIs.

**Comment by npmcs** [comment]
Can you give a guide to the steps you used to get dosemu2 running on Windows 10?

**Comment by stsp** [comment]
You need to install ubuntu under WSL,
and run xming.
Its quite cool that it runs at all, but its
mostly a joke. Unless you are a developer
and want to move the windows port forward,
dont try this at home. :)

**Comment by npmcs** [comment]
I run dosemu2 on Centos and Ubuntu using VMware Player for testing purposes on Windows 10
We use dosemu and dosemu2 to run our Epos system on Linux servers and it works very very well

**Comment by stsp** [comment]
If just for testing, then indeed you can
use the wsl setup. See the beginning of
this thread for some hints with DISPLAY.

**Comment by npmcs** [comment]
Thanks I will try that

**Comment by stsp** [comment]
Are you still using dosemu1?
If so, would be nice to summarize where
does it have an advantage over dosemu2.

**Comment by npmcs** [comment]
We started out using dosemu1 many years ago and while it  works very well for us  on 32 bit servers we found dosemu2 gave better performance on 64 bit servers. In the past we installed 32 bit OS on the servers to run the dosemu1 but now we are replacing these servers with 64bit OS and migrating over to dosemu2. The combination of a dos based application running on a modern 64bit  Linux server using dosemu2  runs very quick. We use it to run our dos based epos system across our 17 retail locations. With all the addition tools that the Linux OS offers this provides us with a very stable and fast solution.

**Comment by stsp** [comment]
Good to know.

**Comment by npmcs** [comment]
After upgrading two of our Centos servers to version 7 we noticed the dosemu2 would not run under any of the scripts in the crontab

After some investigation we discovered that we needed to change the startup command within the script.

Previously we had          dosemu -K  "Linux path to the batch file"

Changed to                   dosemu -dumb -K  "Linux path to the batch file"

This worked, it appears you need to add the -dumb in the startup line.

**Comment by stsp** [comment]
Please open a new ticket and follow
the reporting guidelines.
Provide the log, the command line and
an error message you get.
Command line should better be checked
with dosemu.bin, as `dosemu` script
morphs an input (makes -td from -dumb).
