### ISSUE TITLE
remove global config

### ISSUE THREAD

**Issue by stsp** [dosemu2/dosemu2#947]
global, only-root-writable config seems unneeded
these days.

**Comment by stefand** [comment]
I use it to provide a configuration to multiple Linux users.

I have a Linux system I use for LAN parties. Lots of games are installed natively, with Wine, dosbox and dosemu2 and hooked up to start menu entries. I've hacked in the ability to boot extra copies of this system via PXE and nfsroot, so I usually have a handful of people playing, each with their own separate Linux user and $HOME.

I suppose I could point to a global config file from my start menu entries via -f if /etc/dosemu/dosemu.conf is gone - that's how I handle those games that need dosbox. The other useful thing I do with the config file is to provide a "default" configuration with a drive setup that matches the drives in Wine if one just runs "dosemu" from the command line. That's helpful for sharing game installations between Win 3.1 and Wine.

**Comment by jschwartzenberg** [comment]
There are still some options marked `[priv]` that cannot be set in `.dosemurc`.

Note that you can use the environment variable `dosemu__hdimage` to override the `$_hdimage` setting in the config file.

Maybe comparable to `WINEPREFIX` in a way, but I think having a full `DOSEMU2PREFIX` could be useful too.

**Comment by stsp** [comment]
The idea was that in 99% of cases
no config changes are required at all,
and the remaining people may want
to change 1-2 option per user, in
dosemurc. In fact dosemurc is much
more readable than the glibal config,
as it only contains the lines that change.
I won't rush removing the global config
if people still use it, but I'd like to know
what tweaks you do and maybe they
can be done automatically. So you
change drive pathes, anything else?
Do you need to change drives, or
only add to existing ones? In the latter
case other options exist.

**Comment by stefand** [comment]
I change the following things:

- Drive paths ($_hdimage = "/etc/dosemu/drives/* +1")
- $_mouse_dev, although that is always a one-off setting
- $_cdrom. I guess I should set up a /dev/cdrom symlink some day...
- $_joy_device = "" to stop the HDD accelerometers from controlling my games :-)
- $_com1 = "mouse" - kinda one-off together with _mouse_dev
- $_lpt1 = "lpr". I find piping postscript or text out of Windows 3.11 much easier than finding proper drivers
- $_vnet = "tap" . Dangling leftover from my Netscape experiments. I still have to migrate my network based games from dosbox to dosemu.
- $_tapdev = "tap0" 
- $_SDL_hwrend = (on) . I have  TODO for a bug report though. It shows a black screen on the Nvidia blob driver

My drive setup links /opt/windows to c. That's my wine drive_c, doesn't really contain any DOS stuff and is read-only for most users (except C:\windows\temp and C:\users\<user> being a symlink)
d and e are placeholders that will be replaced by lredir -fC pointing to my cdemu mount dir and HW cdrom mount dir. Drive f is a placeholder too and will be lredir'ed to ${HOME}/.wine/overlay later, which is an aufs overlay for those games that insist on writing to their own install directores. All my dos games live in F:\dos.

It's kinda implied in the above setup - only part of my config lives in dosemu.conf, a big part is in fdppconf.sys and fdppauto.bat. They do the drive handling, load cdrom.sys for cdemu and real optical drive, set PATHs etc.

**Comment by stsp** [comment]
> $_tapdev = "tap0"

Default.

> $_SDL_hwrend = (on) . I have TODO for a bug report though.

No need. It would be enabled if it worked.
I don't want to apply the openGL-specific
work-arounds to my code (openGL sucks,
if you ask me), and Vulkan integration in
SDL seems to be done with a different set
of APIs:
https://wiki.libsdl.org/SDL_Vulkan_CreateSurface
I am not sure why it is so. My hopes were
that SDL will just allow me to select from
GL or Vulkan, but the rest will stay as it is.
But it doesn't seem to be the case. If there
is a migration guide on how to port the SDL-based
code from GL to Vulkan, please point me to
it. But then, openGL API in SDL has the
software fall-back, but Vulkan probably does
not? I.e. some deep knowledge of SDL is
needed to point me to the right direction.
For now my approach is "don't touch - won't
stink". That code was already fully rewritten
when switching from SDL1, and I am not sure
why should I do that again, and if so - will it
be the last, or SDL guys will come up with
yet another breakage later.

Speaking of your config mods - the only reason
why you want to have the global config is that
you seem to demand the same set of changes
for multiple users at once. This is a valid scenario,
but its probably not a common-place one.
What I dislike about the current dosemu.conf
is that its only root-writable (as it probably should,
being in /etc). In your case it seems tempting to
create a "dosemu" group and have a config for
that group. But I am not sure we have a standard
place for some group-specific configs (there is
no home dir for a group). Something to think about. :)
I think distro guys like @skitt can suggest the
best approach for that problem.

**Comment by stefand** [comment]
Yeah, you are right, there's no inherent need for this thing being in /etc as long as there's some way to make it apply to user accounts without manually configuring something in every $HOME/.dosemu.

> > $_tapdev = "tap0"
> 
> Default.

Hmm, I had the impression without this it tries to create a new interface if I pre-create tap0. I saw a recent patch in that area though.

> I don't want to apply the openGL-specific
> work-arounds to my code

The "the" makes me think there's code working around the NV driver problem. Can you point me to it? hwrend works nicely on the open source radeon driver and it is a big speed boost at a 4k X11 resolution.

I had a quick look at the code triggered by turning on hwrend, and it seemed to me that you let SDL do all the heavy lifting. So I was somewhat surprised that something as fundamental as SDL is broken that badly on Nvidia. Although it might have something to do with threading - setting up the GL context from one thread and rendering from another.

> (openGL sucks, if you ask me),

OpenGL is ok for your purposes, the drivers suck though. Don't expect Vulkan drivers to be much better. And then a few years ago someone had the great idea of exposing GL via JavaScript in a web browser...

**Comment by stsp** [comment]
> Although it might have something to do with threading - setting up the GL
> context from one thread and rendering from another.

Exactly!
And for SW rendering it is MUCH better
to have them in a separate threads, so I
don't want to change that.
VK has no such problem, so I viewed it
as a potential solution. Until SDL guys
coded it into a different APIs (maybe they
had to? Maybe this is the only right way?
I really don't know, any docs are appreciated).
So now I am completely lost and prefer to
not touch that code as long as it works.
Open-source drivers simply allow you to
do what is an undefined behaviour in a
GL standard (at least that is my understanding).

**Comment by stefand** [comment]
I barely know SDL, but I think the use case of just blitting memory onto the screen is relatively rare these days. If you set up OpenGL or Vulkan you will probably render with them, and at that point they are very different and having a common init API won't make much sense.

**Comment by stsp** [comment]
> I barely know SDL, but I think the use case of just blitting memory
> onto the screen is relatively rare these days.

If you look at sdl/sdl.c, you'll note that
it is all about creating the texture and
rendering it to the video plane. I thought
its a most "modern" way of doing things.

> and at that point they are very different and having a common init API won't make much sense.

I've found the sfml thread that thinks otherwise:
https://en.sfml-dev.org/forums/index.php?topic=19822.0
It proves nothing, of course, because it seems like
sfml still haven't materialized that plan.

**Comment by stsp** [comment]
After reading a bit more, it doesn't look like
SDL provides any VK-based rendering. It
only allows you to create the VK surface
for your SDL window, but the rendering
itself should be done by some other
(SDL-unrelated) means. Which is definitely
not what I want.

**Comment by stsp** [comment]
You don't need to use shaders for text
rendering. If you have each char in a
separate texture in video mem, you can
render them very fast. This can even be
done in SDL, and will work also with the
software rendering. The problem here is
not in the rendering itself, but in a way
you are going to track the changes in
user fonts. Which may became dirty
once you start dealing with CGA mode
that has the font table split, unlike other
modes.

> see if shaders could decode the data in planar modes.

IIRC we already do that in a separate thread.
I wanted to play with massive parallelism here,
when every rectangle is processed by a separate
thread from the pool, but never completed that
task. But its possible and is portable. Shaders
will not give you any benefits there. They may
give you something for scaling and filtering, but
we simply rely on SDL to do that. And it does
so quite poorly, shaders could do much better.
But I'll let SDL to use shaders.

**Comment by stsp** [comment]
Just to have a summary in the ticket:
global config is root-writable, and is almost
never needs to be changed - people should
put their changes to ~./dosemu/.dosemurc.
But some people want the same set of changes
for multiple users, so before removing the
global config, we need to think how to do
that. And as long as the global config doesn't
hurt much, it may be better to not do anything
in that direction.
