### ISSUE TITLE
Tetris Gold has multiple issues

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#956]
**Describe the bug**
Probably this should be in multiple issues, but I'm not sure if these are really dosemu issues or whether the games are just very buggy.

**To Reproduce**
- Faces crashes dosemu when you quit the game.
- The launcher cannot install anything due to disk space error
- (sound issue I fixed, delete `tc.cfg` then the game will ask for the device)
- Multiple games cannot create their own high scores file

**Attach the binaries or provide an URL**
http://www.abandonia.com/en/games/5341/Tetris+Gold.html

**Attach the log**
Not sure what I should provide now.

**Comment by stsp** [comment]
> Not sure what I should provide now.

As usual: is it a regression, on what DOS
it works etc.

**Comment by jschwartzenberg** [comment]
I'll have to check regarding the regression. I tried it on MS-DOS 6.22.

**Comment by stsp** [comment]
Ping.
Also sounds like an MFS problems?
Are they all still here?

**Comment by andrewbird** [comment]
Does the ISO file unpack properly for you as after loopback mounting on linux I see errors when trying to copy the files off?
~~~
./vidplay/democntl.swt
tar: ./vidplay/democntl.swt: Read error at byte 0, while reading 370 bytes: Input/output error
./vidplay/swtgame.bat
tar: ./vidplay/swtgame.bat: Read error at byte 0, while reading 1223 bytes: Input/output error
./vidplay/swtwin.ctl
tar: ./vidplay/swtwin.ctl: Read error at byte 0, while reading 1 byte: Input/output error
./vidplay/tetris.avi
tar: ./vidplay/tetris.avi: File shrank by 7039720 bytes; padding with zeros
~~~

And the system log shows
~~~
[ 5434.031240] attempt to access beyond end of device
[ 5434.031242] loop0: rw=524288, want=115816, limit=115180
[ 5434.031246] attempt to access beyond end of device
[ 5434.031247] loop0: rw=0, want=115312, limit=115180
~~~
