### ISSUE TITLE
Remote X11 crashes, some with printer error when running carrier

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#986]
**Describe the bug**
Different variants of remote X11 show different crashes.

**To Reproduce**
`ssh -X localhost` before running dosemu

**Attach the binaries or provide an URL**
Tested with `carrier`

**Attach the log**
`ssh -X localhost` then `dosemu`
[boot.log](https://github.com/stsp/dosemu2/files/4051770/boot.log)

`ssh -X localhost` then `dosemu -X`
[boot.log](https://github.com/stsp/dosemu2/files/4051772/boot.log)

**Comment by stsp** [comment]
Could you please bisect that?

**Comment by jschwartzenberg** [comment]
Do you have an idea which version makes sense to start from?

**Comment by stsp** [comment]
The one that works.
pre8?

**Comment by jschwartzenberg** [comment]
With pre8 I'm getting different crashes! I'll see if I can find a version that worked.

**Comment by stsp** [comment]
Is it only specific to carrier?

**Comment by jschwartzenberg** [comment]
It seems other games do run, at least prince2 does.

**Comment by jschwartzenberg** [comment]
2.0pre6.1-dev has again different crashes, it seems remote X11 was not really tested a lot.

**Comment by stsp** [comment]
No one knew it should be separately
tested with this carrier game.
Try dosemu1,

**Comment by jschwartzenberg** [comment]
Yep, it works fine in dosemu1!

**Comment by jschwartzenberg** [comment]
For `dosemu -X`
22e3c8b9da9525def10fc9200562986d4310d15b is the first bad commit

For `dosemu` without `-X` it's already between
6f12ca7c2bee5b698671eaf5c281ac2a145ecb64 and 05635a3f806a680ffc666c68c34c9bc9dc4160f4, I can bisect that one as well.

**Comment by jschwartzenberg** [comment]
The pic_revert branch works fine both with `-X` and without `-X`.

**Comment by jschwartzenberg** [comment]
Second bisect, without `-X` so with SDL I guess gives this:
5ee681aa114f003132bba3b6710bbb2f1e7fb014 is the first bad commit

**Comment by stsp** [comment]
Locally I can't reproduce this, even
with `ssh -X localhost`.

**Comment by jschwartzenberg** [comment]
Is there a log I could provide?

**Comment by stsp** [comment]
Maybe a good and bad logs -D9+rdD#g

**Comment by jschwartzenberg** [comment]
Now it crashes even without remote X11. Bad log: 
[boot.log.gz](https://github.com/stsp/dosemu2/files/4112640/boot.log.gz)

pic_revert (good):
[boot.log.gz](https://github.com/stsp/dosemu2/files/4112652/boot.log.gz)

**Comment by stsp** [comment]
With the same printer error?

**Comment by jschwartzenberg** [comment]
No, that was a different error. You cannot reproduce any of this?

**Comment by stsp** [comment]
Nope, but its not a top priority anyway,
as we know that pic_revert helps, and
this is all that is needed.
I'll get back to your ssh for kvm problem
though.

**Comment by jschwartzenberg** [comment]
Sure, just let me know when!

**Comment by stsp** [comment]
> as we know that pic_revert helps, and
> this is all that is needed.

Plus the fact that it is not specific to "ssh -X",
of course. Otherwise it would be something
more interesting than just pic_revert.

**Comment by jschwartzenberg** [comment]
Are you planning to do the pic_revert? Is there more testing to be done?

**Comment by stsp** [comment]
Not yet decided what hack is to do best.
This affects very small amount of progs,
that will likely not work (reliably) on qemu
too.

**Comment by jschwartzenberg** [comment]
Maybe at least document them in emufailure?

**Comment by stsp** [comment]
Have you checked on qemu already?

**Comment by jschwartzenberg** [comment]
Not yet, let me see.

**Comment by jschwartzenberg** [comment]
`carrier` runs in QEMU with KVM:
![image](https://user-images.githubusercontent.com/877112/75117647-a5234000-5673-11ea-9759-022ca18a47f7.png)

**Comment by stsp** [comment]
It works in dosemu most of the time too.
Try other games, like street fighter, that
definitely exhibit that problem.

**Comment by stsp** [comment]
> Are you planning to do the pic_revert? Is there more testing to be done?

Finally - yes.
Please check against current devel
and see if `$_timer_tweaks = (on)`
fixes this.
Please re-open if you have any new findings.
