### ISSUE TITLE
Aborting PKZIP operation causes anomalies

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#999]
**Describe the bug**
Aborting an archive creation using CTRL-C with PKZIP 2.50 results in one of two errors:

1 - DOSemu crashes and prints the following to the console:
`ERROR: SS selector invalid: 0x015F, type=0 np=1`

2 - PKZIP exits to a DOS command prompt and the following is printed to the console:
`ERROR: DPMI: Warning: trying to leave DPMI when in_dpmi_pm_stack=1`

**To Reproduce**
Create an archive with PKZIP, and while PKZIP is running, abort the archive creation with CTRL-C.  This is without the "-)" flag.  One of the two errors above will be observed.

**Attach the binaries or provide an URL**
[pkz250r.zip](https://github.com/stsp/dosemu2/files/4123539/pkz250r.zip)

**Attach the log**
[boot.log.zip](https://github.com/stsp/dosemu2/files/4123531/boot.log.zip)
[dosemurc.zip](https://github.com/stsp/dosemu2/files/4123563/dosemurc.zip)

**Comment by jharrison03** [comment]
PKZIP/UNZIP works fine otherwise - it's when you hit the brakes this error comes up.

**Comment by jharrison03** [comment]
Borland "make" 4.0 from Turbo assembler seems to exhibit the same problem as PKZIP --

Aborting a "make" with Ctrl-C gives these same errors.  

Borland make 3.6 from Turbo C can abort with Ctrl-C with no problems observed.

**Comment by stsp** [comment]
Please add -D9+M log.

**Comment by stsp** [comment]
So the -D9+M log?
